### ISSUE TITLE
incorrect captalization: global.extensions.dataPlanePerProxy

### ISSUE THREAD

**Issue by gmflau** [solo-io/gloo#10051]
### Version

main (1.18.x beta)

### Gateway API

Gloo Edge API

### Describe the requested changes

The helm value: global.extensions.dataPlanePerProxy in our doc (https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/enterprise_helm_chart_values/) should be global.extensions.data**p**lanePerProxy.  Lowercase: **p**

**Comment by nfuden** [comment]
@gmflau any chance you would want to open a pr for this? Thanks for the issue either way!
