### ISSUE TITLE
Not all kubernetes e2e tests are getting run on PRs

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#10103]
### Do you have a suggestion for code improvement or tracking existing technical debt? Please describe.

Our [kubernetes e2e tests](https://github.com/solo-io/gloo/tree/main/test/kubernetes/e2e) consist of a set of top-level test suites that run "test installations" that each tests one or more "features". On PRs, to save CI time we [load-balance tests](https://github.com/solo-io/gloo/blob/main/test/kubernetes/e2e/load_balancing_tests.md) so that a subset of tests runs on each cluster. To do this, we define [regexes](https://github.com/solo-io/gloo/blob/58c532b256b4f437b5f98b4480916a9a1f2eb028/.github/workflows/pr-kubernetes-tests.yaml#L57-L81) for which tests will run on each cluster. This usually involves splitting up the top-level suites (e.g. TestK8sGateway) between different clusters. The problem is that when we register new tests under a top-level suite (e.g. [here](https://github.com/solo-io/gloo/blob/f89eec59130f473fe66b519da91d1f4277a19f00/test/kubernetes/e2e/tests/k8s_gw_tests.go#L22)) we may forget to add the new tests to the GH workflow.

Note that on the nightly tests, we [run all tests](https://github.com/solo-io/gloo/blob/58c532b256b4f437b5f98b4480916a9a1f2eb028/.github/workflows/nightly-tests.yaml#L66-L70) (i.e. with no regex), instead of splitting, so we don't run into this problem. Sometimes tests that we forgot to add to the PR workflow show failures in nightlies, but those are less visible unless we monitor them regularly.

As part of this issue, we should do the following:
- [x] fix the DirectResponse test, which we know to be failing, but currently only runs on nightlies https://github.com/solo-io/gloo/issues/10058
- [x] check if we are accidentally skipping any other kubernetes e2e tests in gloo, and add all the missing tests to the [test matrix](https://github.com/solo-io/gloo/blob/58c532b256b4f437b5f98b4480916a9a1f2eb028/.github/workflows/pr-kubernetes-tests.yaml#L57-L81) - https://github.com/solo-io/gloo/pull/10197
    - [x] ~do the same for solo-projects~ - only the OSS suites run on nightlies and not PRs
- [x] add to the gloo e2e test [README](https://github.com/solo-io/gloo/blob/main/test/kubernetes/e2e/README.md) 
    - [x] a reminder about adding new test suites/features to the matrix if they are not already covered by an existing regex - https://github.com/solo-io/gloo/pull/10197
    - [x] document the desired behavior that in OSS we want to run all kubernetes e2e tests on both PRs & nightlies  - https://github.com/solo-io/gloo/pull/10197
    - [x] add the same reminder / desired behavior in a solo-projects README, except that in EE we want to run OSS-defined tests only in nightlies, and run EE-specific tests on both nightlies and PRs - https://github.com/solo-io/solo-projects/pull/7045
- [ ] come up with an automated way of detecting whether not all tests are being run in gloo / solo-projects PRs (jacob had a suggestion of getting all tests that ran on nightlies, and comparing to what runs in a PR; can we find a way to do something similar without relying on nightlies running first?) - we should timebox this, and break it out into a separate issue if necessary

**Comment by davidjumani** [comment]
> come up with an automated way of detecting whether not all tests are being run in gloo / solo-projects PRs

go test --list does something similar however it only reports the top level tests run and not subtests so this would not work
An alternative would be to grep for ^Test in our test directory and compile the list but that again would be cumbersome and not display the required hierarchy.

**Comment by davidjumani** [comment]
Created a followup for automating detection : https://github.com/solo-io/gloo/issues/10202
