### ISSUE TITLE
clusteringress-proxy does not exist

### ISSUE THREAD

**Issue by munjal-patel** [solo-io/gloo#1019]
Hello,

I am trying to set up Knative with Gloo by following this documentation:
https://knative.dev/docs/install/knative-with-gloo/

However, after deploying the sample `hello-world` service, I am not able to invoke it.
The reason for it is that the `clusteringress-proxy` does not exists in my cluster.

Running `glooctl proxy url --name clusteringress-proxy` returns following:
```
Error: could not detect 'clusteringress-proxy' service in gloo-system namespace. Check that Gloo has been installed properly and is running with 'kubectl get pod -n gloo-system': services "clusteringress-proxy" not found
Usage:
  glooctl proxy url [flags]

Flags:
  -h, --help            help for url
  -l, --local-cluster   use when the target kubernetes cluster is running locally, e.g. in minikube or minishift. this will default to true if LoadBalanced services are not assigned external IPs by your cluster

Global Flags:
  -i, --interactive        use interactive mode
      --name string        the name of the proxy service/deployment to use (default "gateway-proxy-v2")
  -n, --namespace string   namespace for reading or writing resources (default "gloo-system")
      --port string        the name of the service port to connect to (default "http")
```

I would really appreciate any help here.

**Comment by ilackarms** [comment]
can you show `kubectl get pod -n gloo-system`?

**Comment by ilackarms** [comment]
what version of knative are you installing?

**Comment by munjal-patel** [comment]
@ilackarms here is the result from `kubectl get pod -n gloo-system`

![image](https://user-images.githubusercontent.com/51474446/62892944-43663e80-bcfe-11e9-9702-176e0e89fba7.png)

I just did `glooctl install knative` to install `knative` on a vanilla GKE cluster.

Thanks!

**Comment by ilackarms** [comment]
I'm so sorry, I'm still working on updating the docs for this change. 

Everywhere you see `clusteringress-proxy` in commands should be replaced with `knative-external-proxy`. Sorry about that! The update will be in soon
