### ISSUE TITLE
Configuring custom domain for Gloo with Knative

### ISSUE THREAD

**Issue by munjal-patel** [solo-io/gloo#1025]
Hello,

I installed Gloo for Knative by following instructions here:
https://knative.dev/docs/install/knative-with-gloo/

However, I do not find any documentation on configuring custom domain for Gloo.
I tried this Knative guide. But I don't think that applies here.
https://knative.dev/docs/serving/using-a-custom-domain/

Can someone please help me out / point to a correct documentation on how to do this?

Thanks!

**Comment by ilackarms** [comment]
@munjal-patel thanks for trying Gloo with Knative. I followed the instructions in the tutorial and they worked fine for me (I was able to change my domain to `example.io`). Did you have a problem configuring a custom domain suffix with Gloo+Knative?

Knative passes the suffix in its `ingress.internal.knative.dev` CRD, which Gloo picks up. Gloo doesn't know whether the domain is custom or not, it simply reads the domains from the Knative `Ingress` custom resource as they are provided.

Knative gives Gloo something like this:

```yaml
  spec:
    rules:
    - hosts:
      - helloworld-go.default.svc.cluster.local
      - helloworld-go.default.example.io
      http: ...
````

and Gloo transforms it to something like this (for Envoy):
```json
{
   "@type": "type.googleapis.com/envoy.admin.v2alpha.RoutesConfigDump",
   "dynamic_route_configs": [
    {
     "version_info": "7325124724267633638",
     "route_config": {
      "name": "http-routes",
      "virtual_hosts": [
       {
        "name": "default_helloworld-go-0",
        "domains": [
         "helloworld-go.default.svc.cluster.local",
         "helloworld-go.default.svc.cluster.local:80",
         "helloworld-go.default.svc",
         "helloworld-go.default.svc:80",
         "helloworld-go.default",
         "helloworld-go.default:80",
         "helloworld-go.default.example.io",
         "helloworld-go.default.example.io:80"
        ],
        "routes": [
         {
          ...
```

**Comment by ilackarms** [comment]
@munjal-patel closing this for now. feel free to reopen if your issue has not been resolved
