### ISSUE TITLE
Backport stopwatches for translator and envoy syncer to 1.17

### ISSUE THREAD

**Issue by DuncanDoyle** [solo-io/gloo#10278]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.17.3

### Is your feature request related to a problem? Please describe.

We should backport the translator stopwatches that were inteoduced in PR https://github.com/solo-io/gloo/pull/10229 to our 1.17.x release to provide Gloo Gateway users with additional metrics to monitor their Gloo translation time.

### Describe the solution you'd like

Backport PR https://github.com/solo-io/gloo/pull/10229 to 1.17.x

### Describe alternatives you've considered

n.a.

### Additional Context

n.a.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206681874205238/1208702372559093) by [Unito](https://www.unito.io)

**Comment by sam-heilbron** [comment]
I assumed that these changes were introduced in this PR: https://github.com/solo-io/gloo/pull/10243. The remaining work to fully introduce this would be to release gloo oss and pull that into Gloo Enterprise

**Comment by DuncanDoyle** [comment]
OK, wasn't aware we already did the backport. So I guess this will be part of Gloo Gateway EE 1.17.4 ...

**Comment by ashishb-solo** [comment]
https://github.com/solo-io/gloo/pull/10301 merged, so i think we can close this. this will get released in https://github.com/solo-io/solo-projects/issues/7190
