### ISSUE TITLE
Problem with gloo.solo.io/oss-image-tag image for arm architecture during Gloo component deployment

### ISSUE THREAD

**Issue by Ellioben** [solo-io/gloo#10356]
### Version

main (1.18.x beta)

### Gateway API

Gloo Edge API

## Problem Description
I'm attempting to deploy Gloo components on an arm - architecture device based on the deployment plan from the website (https://docs.solo.io/gloo-edge/main/guides/dev/building-and-deploying-gloo/). I encountered an issue when executing the `glooctl install gateway` command.
Originally, the images that this command depends on are all in amd64 architecture. I have already changed the other required images that I could find to the arm64 architecture. However, I can't find the deployment method for the `gloo.solo.io/oss-image-tag` image in arm architecture. This has halted the entire deployment process, and I hope to get relevant guidance regarding the deployment of this image in arm architecture.

## Environment Information
- Architecture: arm
- Operating System Information (please fill in the specific version): [Your operating system version]
- Gloo Version (if known): [The version number of Gloo, if available]

## Steps Already Taken
- Manually modified other dependent images to the arm64 architecture version.
- Thoroughly reviewed the official documentation (https://docs.solo.io/gloo-edge/main/guides/dev/building-and-deploying-gloo/), but found no information regarding the deployment of the `gloo.solo.io/oss-image-tag` image in arm architecture.
## Expected Result
I hope to obtain the deployment method for the `gloo.solo.io/oss-image-tag` image in arm architecture so that I can successfully complete the deployment of Gloo components on the arm-architecture device.

### Link to any relevant existing docs

[Building and Deploying Gloo Gateway from Source :: Gloo Edge Docs](https://docs.solo.io/gloo-edge/main/guides/dev/building-and-deploying-gloo/)

**Comment by nfuden** [comment]
Hey thanks for the issue. Right now we only create our envoy version with amd. 
There has been some work in the Solo org to get multi arch working which we may be able to follow. As part of our donation cleanup we also want to change some of the ci setups to be less reliant on google cloud bot webhooks and rely more on github runners. 

That being said if people have interest with regards to setting up multiarch it would be a great starting point.
