### ISSUE TITLE
upgrade utils unit tests knows how to handle certain github cases [It] should return latest patch

### ISSUE THREAD

**Issue by sheidkamp** [solo-io/gloo#10369]
### Which tests failed?

upgrade utils unit tests knows how to handle certain github cases [It] should return latest patch

Example: https://github.com/solo-io/gloo/actions/runs/11887374701/job/33120025484

```
upgrade utils unit tests knows how to handle certain github cases [It] should return latest patch
/home/runner/work/gloo/gloo/test/kube2e/upgrade/upgrade_utils_test.go:26

  [FAILED] Unexpected error:
      <*eris.rootError | 0xc001ff3d40>: 
      Could not find a recent release with version prefix: v1.8
      {
          global: false,
          msg: "Could not find a recent release with version prefix: v1.8",
          ext: nil,
          stack: [0x30e4185, 0x30e46dd, 0x2f632af],
      }
  occurred
  In [It] at: /home/runner/work/gloo/gloo/test/kube2e/upgrade/upgrade_utils_test.go:30 @ 11/18/24 07:29:11.507

  Full Stack Trace
    github.com/solo-io/gloo/test/kube2e/upgrade.glob..func1.2.1()
    	/home/runner/work/gloo/gloo/test/kube2e/upgrade/upgrade_utils_test.go:30 +0xb8
```

Need to port https://github.com/solo-io/gloo/pull/10359/commits/275117dba8e442d5fab19ea420a27d83d299ece9 and https://github.com/solo-io/gloo/pull/10359/commits/664f692e023f555a37eed6baafe171937bab5d60 to `1.16.x` and `1.15.x`

**Comment by npolshakova** [comment]
https://github.com/solo-io/gloo/pull/10375 and https://github.com/solo-io/gloo/pull/10376 have merged, can close out
