### ISSUE TITLE
Better syntax error checking for Virtual Services

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#1036]
In a route if you mistakenly type a value versus a list for route matcher methods option, for example, Gloo will just ignore the invalid option versus flagging an error

```
- matcher:
    methods: "OPTIONS"
    prefix: /
```

**Comment by yuval-k** [comment]
xref: https://github.com/solo-io/solo-kit/pull/213

**Comment by rickducott** [comment]
Glooctl check and the UI help for this. There is a lot more we could do around validation, and a number of other related issues. Closing this one as stale.
