### ISSUE TITLE
Buildbot CI Job is Failing at Step 7

### ISSUE THREAD

**Issue by danehans** [solo-io/gloo#10482]
### Which tests failed?

Buildbot `Step #1 - "run-tests": Step #7` fails [here](https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=edf8e51b-cf05-404d-9324-17c9931b7746) for several PRs, for example:

https://github.com/solo-io/gloo/pull/10481
https://github.com/solo-io/gloo/pull/10478
https://github.com/solo-io/gloo/pull/10446

### Initial Investigation

Reviewed job logs and the failures are similar across the above example PRs.

**Comment by davidjumani** [comment]
The tests were disabled as part of https://github.com/solo-io/gloo/pull/10458 and the test failure tackled as part of https://github.com/k8sgateway/k8sgateway/issues/10400
