### ISSUE TITLE
Annotate gateway service for internal load balancer IP

### ISSUE THREAD

**Issue by keiransteele** [solo-io/gloo#1049]
When installing the gateway with ```glooctl install gateway``` I need to then to annotate the service to change the load balancer to an internal IP on Azure. It would be good if this could be done on install rather than having a public IP provisioned just to then have it swapped for a private IP. I didn't see any option for this in the Helm chart either but I would prefer to stay away from helm if possible.

```
kubectl annotate service gateway-proxy-v2 service.beta.kubernetes.io/azure-load-balancer-internal="true" -n gloo-system
```

**Comment by ilackarms** [comment]
@keiransteele this can be done today with via the Helm chart using the `extraAnnotations` field here: https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/8-gateway-proxy-service.yaml#L13

Currently `glooctl` uses `helm` to generate the manifests which it then runs through `kubectl apply`. You can override values in the helm chart by passing a values file with the `--values` flag.

We could consider adding flags to `glooctl install` to make it easier to tweak values in the Helm chart. is this a feature you'd be interested in?
