### ISSUE TITLE
Add additionalPrinterColumns to CRDs

### ISSUE THREAD

**Issue by leosunmo** [solo-io/gloo#1061]
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns

This would be a great addition for UX when using `kubectl` or something like https://codeberg.org/hjacobs/kube-web-view.

It's only K8s 1.11+ but I don't think it causes issues with older versions of Kubernetes, will need to test but should be easy enough.

**Comment by rickducott** [comment]
I am a huge fan of this idea, and we are utilizing this for other projects now. That said, given the state of the Gloo backlog, I need to close this as stale because it's not clear when we'll be able to take a look at it. We would appreciate a contribution here.
