### ISSUE TITLE
Need doc for integrations with Nomad&Consul?

### ISSUE THREAD

**Issue by dereknex** [solo-io/gloo#107]
I see that features contain `HashiCorp Stack (Vault, Consul, Nomad)`. But I can't find any doc say that.

**Comment by ilackarms** [comment]
`glooctl` can be configured from the command line with flags (if you don't want to rely on `~/.glooctl/config.yaml`)

take a look at `glooctl --help` for the full list of configuration options for glooctl.

**Comment by dereknex** [comment]
Thank you for your quick reply！
