### ISSUE TITLE
Documentation Issue for issues 990/991

### ISSUE THREAD

**Issue by antoniotamer** [solo-io/gloo#1070]
Issue #991 and PR #990 seem to not be thoroughly documented. I left a note in Issue #991, but it's already been closed, so I thought I'd drop a note here. Please disregard if this was documented elsewhere, and thank you for implementing this fix. 

I'll quote here what I entered on #991:

Hi @mitchdraft 

The only docs I could see for this fix is this issue, which above refers to keys
```
aws_access_key
aws_secret_key
```

however, the code uses the more conventional `aws_access_key_id` and `aws_secret_access_key` (which worked great for me)

Could this feature be documented a little bit better so as to avoid confusion?

Thank you by the way for this implementation, it was a much needed feature for me and my team.

**Comment by mitchdraft** [comment]
Thanks for flagging this @antoniotamer, it was an oversight. I will update the docs

**Comment by mitchdraft** [comment]
@antoniotamer please take a look at the updated docs and let me know if they meet your expectations https://gloo.solo.io/v1/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk/#awssecret

**Comment by mitchdraft** [comment]
feel free to reopen if you would like further updates
