### ISSUE TITLE
allow customizing the envoy stats filter through a helm chart

### ISSUE THREAD

**Issue by yuval-k** [solo-io/gloo#1079]
Envoy generates a lot of stats. so many infact that they may cause promethues to crash.
envoy supports a [state matcher](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto#envoy-api-msg-config-metrics-v2-statsconfig) to allow filtering of stats presented in the admin page.
we should add it to our helm chart to make it easy to change.

**Comment by rickducott** [comment]
I think we've looked at this but it's a bit tricky because we rely on this config for our own usage stats. We have worked with customers to avoid crashes, however. Going to close this issue as stale since there isn't a clear path forward.
