### ISSUE TITLE
Cannot use ingress if HTTP port ≠ 80 (ingress doesn't strip port number from HTTP Host header)

### ISSUE THREAD

**Issue by jpetazzo** [solo-io/gloo#1080]
**What I do:**

- deploy a web service
- create an Ingress resource for that web service
- install Gloo Ingress Controller
- since I don't have an actual LoadBalancer, try to connect to the NodePort

**What I expect:**

- I can connect to the web service through the host declared in the Ingress resource

**What I see instead:**

- 404

**Detailed reproduction steps:**

Please note that I am testing this directly from my cluster (so I can use 127.0.0.1 to connect to a NodePort), but if you are using a remote cluster, you can replace 127.0.0.1 with the IP address of one of your nodes below.

```bash
NODEADDR=127.0.0.1
```

Deploy the web service and creating an Ingress:
```bash
kubectl create deployment web --image=nginx
kubectl expose deployment web --port=80
kubectl apply -f- <<EOF
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web
spec:
  rules:
  - host: web.$NODEADDR.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
EOF
```

I install Gloo with `glooctl install ingress`.

Then, I send test requests. Note that the way I obtain the ingress proxy port below is not 100% foolproof (since `.spec.ports[] might be sorted in a different order); I don't remember how to write the correct JSON Path expression :sweat: 
```bash
PORT=$(kubectl --namespace=gloo-system get svc ingress-proxy -o jsonpath='{.spec.ports[0].nodePort}')
curl -v web.$NODEADDR.nip.io:$PORT # 404
curl -v $NODEADDR:$PORT -H "Host: web.$NODEADDR.nip.io" # NGINX hello page
```

**Versions etc:**

```
$ glooctl --version
glooctl community edition version 0.18.21
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Other details:**

- it is not possible to specify the port number in the `host` field in the Ingress resource, because the semi-colon is an invalid character there
- since I didn't know if that was supposed to work at all, I did a similar test with Traefik, it seems to be stripping the port number and works correctly
- why am I doing this? Because I want to do demos/tests/etc in lightweight environments, easy to reproduce, even for people who don't have access to LoadBalancer, ExternalIP, or HostNetwork.

**Comment by rickducott** [comment]
Closing as stale
