### ISSUE TITLE
implement glooctl edit virtualservice

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1094]
currently, use of  `glooctl edit virtualservice` is disabled 

due to the fact that `glooctl edit virtualservice ratelimit`  was added as a subcommand of the above

we should split `glooctl edit ratelimit` out into its own top-level command so users can access the  `glooctl edit virtualservice` command once again.

@mitchdraft

**Comment by ashleywang1** [comment]
It was never implemented to begin with, causing confusion. The ratelimit code implemented it for `glooctl edit virtualservice ratelimit`, and that can be extended for just `glooctl edit virtualservice`

**Comment by EItanya** [comment]
removing bug label for the above reason
