### ISSUE TITLE
add ability to toggle routes

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1096]
it would be a nice feature on routes (perhaps in the upcoming api changes) to be able to set `disable:true`, which will cause Gloo to skip adding those routes to the envoy config. make it easy for users to test new routes without having to delete them or reorder them in the virtualservice

releveant to #1062

**Comment by rickducott** [comment]
Could use delegation selectors now to get creative about testing new routes without modifying a VS.
