### ISSUE TITLE
glooctl knative failed to create kube client 

### ISSUE THREAD

**Issue by amir3code** [solo-io/gloo#1102]
Hello!  

I have installed an ubuntu VM with `MicroK8S` and `glooctl` on it.  

When I try to install `glooctl knative` I get the following error:

```
amir@lubuntu:~$ glooctl install knative
"Sun, 01 Sep 2019 10:37:01 +0430: github.com/solo-io/gloo/projects/gloo/cli/pkg/helpers/clients.go:113"	failed to create kube client: &errors.withStack{
  error: &errors.withMessage{
    cause: clientcmd.errConfigurationInvalid{
      &errors.errorString{
        s: "no configuration has been provided",
      },
    },
    msg: "getting kube config",
  },
  stack: &errors.stack{
    0xcf9eb2,
    0x1f053ba,
    0x1f050c2,
    0x23284bd,
    0x232f0f8,
    0x6797c1,
    0x67a3f7,
    0x679d3b,
    0x24193f4,
    0x4334bf,
    0x460d41,
  },
}

```

![image](https://user-images.githubusercontent.com/26854204/64072514-fc3bef80-cca4-11e9-9dbc-9ab91b1e7d49.png)

I dont know the reason, I just installed microk8s on a fresh ubuntu vm. no other thing, I dont know why it is occurring.  

Can somebody guide and help me??

**How to reproduce?**
Use vagrant `ubuntu/bionic64` box and install `MicroK8S` and then try to install `gloo`.

**Comment by ilackarms** [comment]
@amir3code this means `glooctl` couldn't find your `kubeconfig`. by default it looks in `${HOME}/.kube/config`

You can override this by setting the `KUBECONFIG` environment variable

**Comment by amir3code** [comment]
@ilackarms Thanks! yeah It was the issue. I created a kubeconfig file using [this tutorial](http://docs.shippable.com/deploy/tutorial/create-kubeconfig-for-self-hosted-kubernetes-cluster/) and it actually gave me another error which I referenced [here](https://github.com/solo-io/gloo/issues/1106).

I try to solve the new problem and post the results here.

**Comment by rickducott** [comment]
I think the issue here is resolved, and the ticket hasn't been updated for 3+ months, so marking as stale. Please let us know if you are continuing to see issues.
