### ISSUE TITLE
add a `--force` flag for knative install

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1104]
currently, `glooctl install knative` will error out if `knative-serving` is already found in the system:  https://github.com/solo-io/gloo/blob/master/projects/gloo/cli/pkg/cmd/install/knative.go#L55

we should add a `--force` flag to override this behavior (existing installation can be updated with `kubectl apply`)

**Comment by rickducott** [comment]
Closing as stale since this hasn't been updated in 3+ months.
