### ISSUE TITLE
consul upstream destination only works if `gloo-system` is in watchNamespaces

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1107]
if `watchNamespaces` is in use, and `gloo-system` is not in the watchNamespaces list, then fake consul upstreams (created by the `hybridClient`) will not be observable to Gloo (and `consul` type destinations will not be found).

this is because the "fake" consul upstream client converts consul services to upstreams in `gloo-system`: https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/upstreams/consul/conversions.go#L49

cc @marcogschmidt @yuval-k

**Comment by rickducott** [comment]
Not aware of anyone experiencing this problem, so closing this issue as stale.
