### ISSUE TITLE
gateway proxies can only deploy to release namespace via helm chart 

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1115]
currently, the Gateway controller must live in the same namespace as any deployed proxies. This makes a multi-tenancy model difficult to achieve where different namespace owners have their own proxy config.

Currently all gateway resources processed by the `gateway` controller will get merged to the same proxy resource [regardless of the namespace in which the gateway lives](https://github.com/solo-io/gloo/blob/master/projects/gateway/pkg/syncer/translator_syncer.go#L66).

The only way to run gateway proxies in multiple namespaces currently requires installing a `gateway` controller to multiple namespaces, which is redundant

**Comment by rickducott** [comment]
Closing this issue as stale since this hasn't been updated in 3+ months, and the underlying behavior and install options have changed.
