### ISSUE TITLE
Use gateway-proxy-v2 as default proxy name

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1123]
The gateway-proxy service has been recently renamed to `gateway-proxy-v2`, but the `glooctl proxy url` command (and possible other sibling commands) is still looking for `gateway-proxy`, causing an error:

![image](https://user-images.githubusercontent.com/16148461/64345394-46cbad80-cfbe-11e9-893d-02a5312b0f23.png)

We should update the default service name the command is using.

**Comment by ashleywang1** [comment]
https://github.com/solo-io/gloo/blob/c2e95f8a9f2ec5c559e8f2985bb575d1a742a2a9/projects/gloo/cli/pkg/cmd/gateway/root.go#L19

Resolved here.
