### ISSUE TITLE
support websocket traffic

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1132]
implementation should be simple, add a `websocket` field to `RoutePlugins` which will become `use_websocket` on the envoy route: https://www.envoyproxy.io/docs/envoy/v1.6.0/api-v1/route_config/route#config-http-conn-man-route-table-route-use-websocket

Envoy websocket architecture: https://www.envoyproxy.io/docs/envoy/v1.6.0/intro/arch_overview/websocket

**Comment by kdorosh** [comment]
@kdelorey `RoutePlugins` has been renamed to `RouteOptions` in Gloo 1.0. Please open any PR against `feature-rc1` branch. Thanks!

**Comment by kdelorey** [comment]
Looking at this more, as far as I can tell, Envoy moved from a `use_websocket` option to a more general [upgrades](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-msg-config-filter-network-http-connection-manager-v2-httpconnectionmanager-upgradeconfig). I think this happened in v1.8.0 of Envoy. The arch overview seems to have be updated to reflect this change too: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/websocket.html?highlight=websocket

So I guess one question would be, should Gloo follow suit and I make the configuration support upgrades generally, or should it be a simple boolean flag for websockets?

The configuration would look something like:
```
allowWebSocket: true
```
or something like
```
allowedUpgrades:
- websocket
```

**Comment by kdelorey** [comment]
Also upgrade configuration can happen on the `HttpConnectionManager` too. Should I also add the option to that plugin in addition to a per-route configuration (while obeying the rules of the table in the above linked arch overview).

**Comment by EItanya** [comment]
Great questions! In general we try to add both levels of config where possible.
As far as how to surface the upgrade is interesting. After reviewing the API it seems that the upgrade config allows for type, disabling, and a whole new filter chain. I think for now a good solution might be something like this.

```proto

message HcmSettings {
  // ... prior content
  repeated UpgradeConfig upgrade_configs = 1;
}

message UpgradeConfig {
  message WebSocket {
  }

  oneof upgrade_type {
    WebSocket websocket = 1;
  }
}
```

Let me know if that makes 

Thanks in advance for all the help :)

**Comment by kdelorey** [comment]
@EItanya, I like it! One of the things that concerned me with the "general" approach was validation. I didn't even think about just leveraging the protos for that. Thanks for the advice!

**Comment by kdelorey** [comment]
The implementation is done, but I have a few questions on #1784

**Comment by kdelorey** [comment]
@ilackarms The PR to resolve this has been merged in and this issue can be resolved.
