### ISSUE TITLE
gateway should default only to vs in its own namespace

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1142]
currently, a gateway without any selector for virtualservices will select *every* virtual service in the cluster (that is either http or https depending on the gateway config)

this behavior should be restricted to the namespace the gateway lives in, both to support a better multi-tenancy model, and avoid bugs where virtual services with domain conflicts are created in different namespaces

**Comment by kdorosh** [comment]
closed by https://github.com/solo-io/gloo/pull/1674
