### ISSUE TITLE
community edition: new read only UI shouldn't allow the creating of objects even if they aren't really created

### ISSUE THREAD

**Issue by fmedery** [solo-io/gloo#1146]
The latest version of `glooctl community edition` installs what seems to be a read only version of the Enterprise Dashboard.
There is not visual indication that it's read only. 

We can interact with the UI and create VirtualService, as an example, without error **but** it will not be apply to Kubernetes

How to reproduce:
* create a virtual service using the UI, no error or warning that it will not be apply
* refresh the page
* the virtual service has not been created and you won't see it in the UI

Expected behavior:
* clear message that it is read only
* no way to create object

**Comment by rickducott** [comment]
The UI should now properly propagate an error here.
