### ISSUE TITLE
Function discovery not running

### ISSUE THREAD

**Issue by abrahamTesfu** [solo-io/gloo#115]
following running gloo with docker-compose, while the other services are up after running command `docker-compose up` function discovery is not running. 

`docker ps`
returns 

-  soloio/envoy:0.2.28
-  soloio/petstore-example:v0.1

**Comment by ilackarms** [comment]
Make sure to run `prepare-config-directories.sh` before running `docker-conpose up`

**Comment by abrahamTesfu** [comment]
where is that shell script, i don't see it

**Comment by abrahamTesfu** [comment]
never mind, this is only possible in the manual installation.
can we fix the guide.

**Comment by ilackarms** [comment]
@abrahamTesfu ah you're right, the script invocation is missing from our docs.
I can't get around to the fix today, but if you'd like to open a PR we'd greatly appreciate it (the docs on gloo.solo.io are located in `docs/` in the project root)

**Comment by ilackarms** [comment]
The script is located in `install/docker-compose/`
