### ISSUE TITLE
Use better ginko flags for CI

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1153]
follow the recommendations here https://onsi.github.io/ginkgo/#ginkgo-and-continuous-integration

**Comment by kdorosh** [comment]
Added some of the flags in the above PRs, but would still like to add -race to the e2e/regression tests as well as randomize the test ordering

**Comment by rickducott** [comment]
This issue is stale. I know we are looking at CI improvements now, and ironing out flakes that were preventing these flags from being used, so I'm assuming other issues are being used to track current improvements we need.
