### ISSUE TITLE
usability feature: `glooctl proxy record`

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1158]
we should be able to filter the logs from envoy to include the set of info for an individual request

currently, user must manually parse the logs during a `glooctl proxy logs -f` and try to determine where the request-related logs begin and end

**Comment by rickducott** [comment]
This seems like a very useful feature if we had the bandwidth to tackle it, however given we haven't updated this issue since it was created, I am going to close as stale. We would welcome contributions here.
