### ISSUE TITLE
Simplify VirtualService API, possibly other APIs

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1171]
Virtual Service API can be cleaned up:
- [ ] Rename `feature-rc1` branch to `master` and `master` to `v0.x.y`; duplicate of https://github.com/solo-io/gloo/issues/1843
- [x] Remove the conversion job, rename all v2 stuff to v1
- [x] Delete EVERY deprecated field/message from our protos
  - [x] Undeprecate extensions and clearly document their new purpose (https://github.com/solo-io/gloo/issues/1205)
- [x] Address all `TODO(kdorosh)` and remove deprecated codepath support
  - [x] In Gloo
  - [x] In GlooE
- [x] ~Add an “enterprise” block to the plugin definition and allow configuring all enterprise plugins there (strongly typed).~ decided we'd rather all plugins live at the same level 
    - [x] Deprecate/remove the their opaque configs under extensions
    - [x] Update glooctl writes to use new convention
       - [x] Rate limiting
       - [x] Ext auth
    - [x] Update docs to use new convention
        - [x] Ext auth
        - [x] Rate limiting
        - [x] JWT
        - [x] RBAC
        - [x] WAF
    - [x] ~Write cronjob to move old configs to new config~ we are supporting both for now
- [x] Flatten/simplify other virtual service configs where sensible

Ticket is to determine the difficulty of implementation and whether the changes will have an acceptable payoff in the long run.

Other ideas include moving the entire `RoutePlugins` config up one level: https://github.com/solo-io/gloo/blob/master/projects/gateway/api/v1/virtual_service.proto#L215

Open to concrete ideas/suggestions for other simplifications here.

Anything come to mind @rickducott @yuval-k @ilackarms @EItanya @mitchdraft ?

**Comment by rickducott** [comment]
I want to move away from the word "plugins" entirely in our API. Some reasons: 
* It is an unnecessary layer of nesting
* It exposes an internal implementation detail without providing any clarity to the user 
* It has confused us internally -- confusing a plugin that is part of the product from a plugin that is written and maintained by a customer
* It has confused people externally -- expecting the API can be extended with custom plugins without having to rebuild the server

**Comment by kdorosh** [comment]
Adding to the list here:
- proposed simplifications to the rate-limiting API: https://github.com/solo-io/gloo/pull/1213
- Simplify WAF API by using the [Settings](https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/enterprise/plugins/waf/waf.proto#L11-L19) message for routes and vhosts instead of having their own messages (remove `settings` nesting and proto duplication)
  - Also consider removing the CoreRuleSet message if proto supports optional `oneof`s
- Same trick for RBAC, remove the `Config` [message](https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/enterprise/plugins/rbac/rbac.proto#L46-L49) and flatten this up a level
  - Combine with Vhost/Route extensions and remove their specific messages as well

**Comment by kdorosh** [comment]
after discussion with @ilackarms and @yuval-k , leaning towards a rename of `plugins` rather than a complete removal/flattening of the plugins API.

Flattening would be challenging, and possibly more trouble than it's worth because we'd have to flatten plugins to **two** different messages for `VirtualHost`s and `Route`s:
* Gloo VirtualHost: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/proxy.proto#L129-L154
* Gateway VirtualHost: https://github.com/solo-io/gloo/blob/master/projects/gateway/api/v1/virtual_service.proto#L149-L174
* Gloo Route: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/proxy.proto#L156-L185
* Gateway Route: https://github.com/solo-io/gloo/blob/master/projects/gateway/api/v1/virtual_service.proto#L306-L332

This means that every plugin we add in the future would have to be added and documented twice, and would lead to large amounts of API bloat. (proto3 `any` and writing our own marshal/unmarshal logic for gogoproto are even uglier alternatives)

The reason for the near-duplicate messages is to keep the Gloo/Gateway abstraction -- Gloo `Route`s (and therefore Gloo `VirtualHost`s with Gloo `Route`s) don't need to and shouldn't know about route delegation (the differing config on the `Route` messages).

A proper rename addresses all of @rickducott 's concerns (bar the unnecessary nesting, which I'm arguing here is necessary)

**Comment by rickducott** [comment]
What is the proposed name? 

Just to be clear, this is what we have now:
```
plugins:
  hostRewrite: 
    hostRewrite: foo
  prefixRewrite:
    prefixRewrite: bar
  ...
```

And after the change, we will have: 

```
newName: 
  hostRewrite: foo
  prefixRewrite: bar
  ...
```

Is that right?

**Comment by kdorosh** [comment]
Initial rename idea is `trafficPolicy`.

Yes, we would still be flattening the host/prefix rewrites.

**Comment by kdorosh** [comment]
Another recent idea is to delete the `VirtualHost` abstraction altogether from Gloo, looking into it more

**Comment by ilackarms** [comment]
@kdorosh we can remove the `virtualHost` field from the Virtual Service entirely + move field in the `VirtualHost` up one level.

the current structure exists because the original virtualHost was imported directly from gloo

**Comment by ilackarms** [comment]
@rickducott @kdorosh personally i like `options` as a replacement for `plugins`. it communicates that these are optional fields which extend the basic functionality (route to a destination)

**Comment by ilackarms** [comment]
another api break worth considering:
- gateways that have empty `virtualService` refs should only select vs in their own namespace. currently they select all vs in the cluster, which is problematic for multi-tenant and self-service config models

**Comment by marcogschmidt** [comment]
Another are that I strongly feel we should consider refactoring is the `Destination` message.

```proto
message Destination {

    oneof destination_type {
        core.solo.io.ResourceRef upstream = 10;
        KubernetesServiceDestination kube = 11;
        ConsulServiceDestination consul = 12;
    }

    DestinationSpec destination_spec = 2;
    Subset subset = 3;
}
```

My concerns:
- From just looking at the API, it is not possible to understand which `destination_type`s support `DestinationSpec` and `Subsets`
- Some `DestinationSpec`s intuitively feel like they should be destination_types (e.g. `aws`, `azure`)
- `Subsets` is a pretty low-level concept that I think we can expose in more intuitive ways (e.g. `ConsulServiceDestination`s allow you to target services based on tags and data centers; behind the scenes we use subsets, but the user does not have to be aware of that).

I think we can make this central part of our APIs much more user-friendly. Such a refactor will however require vast changes to most of Gloo's components, e.g. FDS, UDS, a good number of plugins, and all the Gloo translation logic.

**Comment by ilackarms** [comment]
empty matcher should default to match all instead of return err

**Comment by ilackarms** [comment]
when we do the breaking change we should default FDS to whitelist mode  (less aggressive)

**Comment by kdorosh** [comment]
- [ ] get rid of `upstreamSpec`, it looks weird nested under `spec`:
```yaml
spec:
  upstreamSpec:
```

**Comment by ilackarms** [comment]
llinking #1489 and #1484 as relevant (potentialy breaking) changes

**Comment by kdorosh** [comment]
Move:
```
    // prefix for addressing envoy stats for the tcp proxy
    string stat_prefix = 3;
```
In HttpListener and TcpListener into appropriate `HttpConnectionManagerSettings` message

**Comment by kdorosh** [comment]
I opened individual issues for each unfinished bullet point to track any remaining open work. 

No need to track progress on this epic anymore now that Gloo 1.0 is out.
