### ISSUE TITLE
CI Resilience: tracking flakes, stale resources

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1179]
this week we have had CI issues related to flakes, stale resources in the cluster, and cluster locking issues.

Please track such failures here

Known issues:
- concurrent build steps can produce stale resources in shared clusters if Step A fails while Step B has deployed resources. Resources from Step B will never get cleaned up
  - partially mitigated by job that purges stale namespaces after a timeout
  - potential fix: update cluster lock logic to purge stale resources immediately after acquiring the lock and waiting to acknowledge cluster acquisition until resources have been removed
    - challenge: how to identify stale resources
  - potential fix: separate clusters for each test (via KIND or otherwise)
- tests don't clean up their resources
  - fix: identify such tests and fix them
- flake: some tests are inherently fragile
  - generic fix: identify such tests, make them more robust
  - potential fix: run them with additional retries (this will slow down builds so perhaps only run them during releases and allow multiple retries there)

**Comment by rickducott** [comment]
This is stale
