### ISSUE TITLE
Helm template bug?

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1216]
From a developer at my company:

```
There seems to be a bug in the latest gloo tar on k8s — the apiServer section is missing in it’s values.yaml, leading to:
Error: render error in "gloo/templates/36-apiserver-role.yaml": template: gloo/templates/36-apiserver-role.yaml:1:14: executing "gloo/templates/36-apiserver-role.yaml" at <.Values.apiServer.enable>: nil pointer evaluating interface {}.enable
```

**Comment by mitchdraft** [comment]
Hi @derrickburns, we briefly included the apiserver for Gloo's UI in the helm chart. 

That introduced some versioning challenges so we removed it here: https://github.com/solo-io/gloo/pull/1181/files#diff-7fdfdc4e5341525def94d7ee75900708L33

If you are using a values spec from sometime between versions v0.18.33 and v0.18.4 of those templates you will get this error. In retrospect, we should have left the deprecated values

Could you tell me which version of Gloo your teammate is working with?
And are you using custom helm values? If so, removing the apiserver values should resolve the error

**Comment by derrickburns** [comment]
I will try to reproduce.

**Comment by rickducott** [comment]
I believe this is fixed - closing.
