### ISSUE TITLE
nil settings value crashes Gloo

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#1253]
Currently the Gloo setup syncer function has the behavior that if the refresh rate is nil in the settings it will crash the Gloo pod. This value should probably have a default and spawn a warning, rather than sending the pod into a crash loop

https://github.com/solo-io/gloo/blob/2733ec6654619ea3a09d37ac3e7628488114f02c/projects/gloo/pkg/syncer/setup_syncer.go#L191

**Comment by rickducott** [comment]
Don't have a strong opinion, but devil's advocate is we can fix a crash loop a lot faster than a subtly logged error. At any rate, closing as stale since we haven't updated the issue in 3+ months.
