### ISSUE TITLE
Function destination: queue publishing

### ISSUE THREAD

**Issue by george-oakling** [solo-io/gloo#1255]
Hi, according to the documentation section Destinations Gloo is able to have a destination as:

> API call on a service (e.g. a REST API call, OpenAPI operation, XML/SOAP request etc.), or publishing to a message queue (e.g. NATS, AMQP, etc.).

but I can't find any example of the last two - NATS, AMQP. Can somebody provide a hint how to test such a behavior? Thanks :)

**Comment by yuval-k** [comment]
Yes, we had NATS support (i.e. convert an http request to a NATS Pub) working in the previous iteration of gloo (versions <= 0.4), and removed it in one of the refactors as we didn't see much community interest to maintain it...  we should probably update the docs to reflect that.

Is that use case of http->NATS applies to you? would love to hear some more details.

**Comment by george-oakling** [comment]
Hi, not specifically NATS as we use RabbitMQ (AMQP) extensively, but something general for queue publishing would be great :)

**Comment by kozy** [comment]
+1 for NATS support. Maybe you give me some hints at how to restore that functionality? I see some tests are still in place.Would it involve mostly getting things up to date again?

**Comment by benallard** [comment]
It’s been more than three years, and the sentence is still in the docs. Has it been added in the meantimes, or does the doc still requires an update?
