### ISSUE TITLE
Gloo not working as expected on crc (OpenShift 4.1)

### ISSUE THREAD

**Issue by stevef1uk** [solo-io/gloo#1256]
Running crc (version: 1.0.0-beta.5+f2aa58c, OpenShift version: 4.1.14 (embedded in binary) ) on my MacBook.

Logged in using kubeadmin as crc doesn't support system:admin OOTB

Installed Gllo using: glooctl install gateway 
glooctl version
Client: 
{"version":"0.19.1"}
Server:
{"type":"Gateway","kubernetes":{"containers":[{"Tag":"0.19.1","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"0.19.1","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"0.19.1","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"0.19.1","Name":"gloo","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}

glooctl check
Checking pods... OK
Error!
gloo-system.default does not exist: settings.gloo.solo.io "default" not found

I executed that command as when following the hello-world guide I deployed the PetStore app ok to my cluster but:
glooctl get upstream 
+----------+------+--------+---------+
| UPSTREAM | TYPE | STATUS | DETAILS |
+----------+------+--------+---------+
+----------+------+--------+---------+

**Comment by yuval-k** [comment]
few commands to debug this:
do you see the settings crd in there? `kubectl get settings -n gloo-system` 
do you see any errors in the gloo logs? `kubectl logs -n gloo-system -l gloo=gloo`

**Comment by stevef1uk** [comment]
$kubectl get settings -n gloo-system
No resources found.

$kubectl get crd | grep gloo
authconfigs.enterprise.gloo.solo.io                         2019-09-25T08:41:01Z
proxies.gloo.solo.io                                        2019-09-25T08:41:01Z
settings.gloo.solo.io                                       2019-09-25T08:41:01Z
upstreamgroups.gloo.solo.io                                 2019-09-25T08:41:01Z
upstreams.gloo.solo.io                                      2019-09-25T08:41:01Z

$oc get pods -n gloo-system
NAME                       READY     STATUS    RESTARTS   AGE
example-5b58864494-8pznn   1/1       Running   1          12h
example-5b58864494-dq8kj   1/1       Running   1          12h
example-5b58864494-pgtjk   1/1       Running   1          12h

$kubectl logs -n gloo-system -l gloo=gloo
error: expected 'logs (POD | TYPE/NAME) [CONTAINER_NAME]'.
POD or TYPE/NAME is a required argument for the logs command
See 'kubectl logs -h' for help and examples.

Looking at the logs of any of the running pods (using console) as I can't be bothered to type:
'oc logs example-5b58864494-8pznn -n gloo-system'
serving on 8888
serving on 8080

**Comment by joekelley** [comment]
Hi @stevef1uk, I’ve reproduced your issue locally. Running `kubectl get deployments -n gloo-system` revealed that no gloo deployments were becoming ready. Each had a condition that looked something like: 

```
  - lastTransitionTime: "2019-09-25T23:51:45Z"
    lastUpdateTime: "2019-09-25T23:51:45Z"
    message: 'pods "gloo-6b7b57847b-" is forbidden: unable to validate against any
      security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser:
      Invalid value: 10101: must be in the ranges: [1000480000, 1000489999]]'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

And the gateway-proxy-v2 deployment had a condition:
```    
message: 'pods "gateway-proxy-v2-67bdcd655c-" is forbidden: unable to validate
      against any security context constraint: [capabilities.add: Invalid value: "NET_BIND_SERVICE":
      capability may not be added]’
```

To resolve these issues, I passed some custom values to the install command with `glooctl install gateway —values os-values.yaml` where os-values.yaml contained:

```
gloo:
  deployment:
    floatingUserId: true
gateway:
  deployment:
    floatingUserId: true
discovery:
  deployment:
    floatingUserId: true
gatewayProxies:
  gatewayProxyV2:
    podTemplate:
      floatingUseId: true
      disableNetBind: true
```

The `floatingUserId` value allows the cluster to dynamically set a user ID for the pods, and `disableNetBind` skips adding the NET_BIND_SERVICE to the pod. Documentation for our helm values can be found here https://gloo.solo.io/installation/gateway/kubernetes/.

I verified that the rest of the hello-world demo worked as expected after installing in this way. Let me know if this works for you!

**Comment by stevef1uk** [comment]
Thanks. I tried that on a new cluster instance and I also added the permissions documented for mini shift:

oc adm policy add-scc-to-user anyuid  -z glooe-prometheus-server -n gloo-system 
oc adm policy add-scc-to-user anyuid  -z glooe-prometheus-kube-state-metrics  -n gloo-system 
oc adm policy add-scc-to-user anyuid  -z default -n gloo-system 
oc adm policy add-scc-to-user anyuid  -z glooe-grafana -n gloo-system

The cluster is now showing the following errors:

a minute ago
Generated from replicaset-controller
16 times in the last 4 minutes
Error creating: pods "discovery-6cc7776f9b-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 10101: must be in the ranges: [1000470000, 1000479999]]

Error creating: pods "gateway-v2-7b4f7c57b8-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 10101: must be in the ranges: [1000470000, 1000479999]]

Error creating: pods "gloo-6b7b57847b-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 10101: must be in the ranges: [1000470000, 1000479999]]

Error creating: pods "gateway-proxy-v2-67bdcd655c-" is forbidden: unable to validate against any security context constraint: [capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added]

**Comment by joekelley** [comment]
These appear to be the same errors I encountered when installing gloo without the `--values` override. Can you verify that the content of your overrides file matches the yaml block in my previous comment, and that you installed gloo with `glooctl install gateway --values <path/to/your/overrides.yaml>`?

It's also possible to correct these errors post-install. Using 
```
oc edit deployment -n gloo-system discovery
oc edit deployment -n gloo-system gloo
oc edit deployment -n gloo-system gateway-v2
```
delete the `runAsUser: 10101` line from the pod spec's security context. This will allow the cluster to dynamically set a user ID for the pods.

Using `oc edit deployment -n gloo-system gateway-proxy-v2`, delete the same `runAsUser: 10101` line as well as the lines:
```
add:
  - NET_BIND_SERVICE
```
under `capabilities` on the security context.

**Comment by stevef1uk** [comment]
Hi,

OK, I entered the command with the file as ./file.yaml and it worked! 

Last time I missed off the ./ and it didn't pick up the values.

Thank you for your help.

Regards

Steve

**Comment by joekelley** [comment]
Awesome! I'll add this solution to our docs.
