### ISSUE TITLE
simplify jwks.remote specification using Envoy's dynamic forward proxy filter

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1265]
currently [jwt remote specification requires a url and an upstream ref](https://gloo.solo.io/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/plugins/jwt/jwt.proto.sk/#remotejwks)

This mimics the long-time behavior of Envoy regarding http_uri, but the new dynamic forward proxy filter removes this requirement.

Should we remove this constraint from Gloo to simplify `remote` specification?
Two ways to do this:
- use Envoy's new filter (requires configuration and management of an additional filter)
- have Gloo auto-populate the upstream ref, creating the static upstream if it does not already exist (auto-creation opens questions such as which namespace to use, perhaps just error if no matching upstream is found)

### Notes from slack discussion

https://solo-io.slack.com/archives/CGPHP7J1F/p1569392103082000

The url should be enough information. However, until very recently, Envoy had avoided DNS resolution and required that an explicit upstream be specified due to the performance/complexity implications.
Note that the RemoteJwks spec https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto#config-filter-http-jwt-authn-v2alpha-remotejwks requires an http_uri, which is documented as requiring both a uri and a cluster
https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/api/v2/core/http_uri.proto#envoy-api-msg-core-httpuri
This associated issue has recently been closed, which implements a MVP "dynamic forward proxy" that would enable the behavior you expect:
https://github.com/envoyproxy/envoy/issues/1606
This feature comes at the cost of additional configuration, outlined here: https://www.envoyproxy.io/docs/envoy/v1.11.1/configuration/http_filters/dynamic_forward_proxy_filter.html?highlight=forward%20proxy
@Yuval Kohavi has been following the implementation of the dynamic forward proxy and may have some insights into its best application.
@marco has been working with the Auth flow and may have some thoughts on dynamic upstream resolution

**Comment by rickducott** [comment]
Closing as stale
