### ISSUE TITLE
glooctl cannot uninstall cluster-scoped resources for specific namespaces

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1275]
from inspecting the code, it appears that `glooctl uninstall` removes cluster-wide rbac resources regardless of which installation/namespace they belong to.

https://github.com/solo-io/gloo/blob/2a31dbefc44152008cc39aa99a08bd9cfd5bf6f0/projects/gloo/cli/pkg/cmd/install/uninstall.go#L44

**Comment by rickducott** [comment]
Only if —all is passed, which is the intended behavior

**Comment by ilackarms** [comment]
what i meant to say was that `glooctl` can only either remove *all* cluster scoped resources or none. we should consider using the `{{ "gloo.rolebindingsuffix" . }}` suffix which is attached to cluster rbac by the helm chart

**Comment by rickducott** [comment]
Closing as stale since this has not been updated in 3+ months.
