### ISSUE TITLE
validate regex prior to accepting regex config specification

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1279]
Envoy's regex grammar https://en.cppreference.com/w/cpp/regex/ecmascript
does not accept `*.xyz` but it does accept the more explicit: `(a-zA-Z)*.xyz`

[envoy docs ref](https://www.envoyproxy.io/docs/envoy/latest/api-v2/type/matcher/string.proto.html?highlight=regex#envoy-api-field-type-matcher-stringmatcher-regex)

**Comment by rickducott** [comment]
CLosing as stale
