### ISSUE TITLE
merging virtual services drops cors settings

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1288]
When two virtual services have the same domain list their routes are merged and the proxy receives a single virtual host instead of two - as desired.

However, along the way, the CORS configuration is dropped.

We need to either:
- redefine how virtual service equivalence is computed (check all virtual service properties, not just domains)
- warn/error when users create multiple virtual services with the same domain list

**Comment by mitchdraft** [comment]
this issue was identified through CORS misbehavior but other virtual host fields (plugins) should be reviewed with this issue
https://gloo.solo.io/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk/

**Comment by mitchdraft** [comment]
currently, VS equivalence definition considers domains only and domain lists must match exactly
https://github.com/solo-io/gloo/blob/master/projects/gateway/pkg/translator/http.go#L45

- what is the expected behavior when domain lists partially overlap? Behavior seems to be undefined in Envoy:
https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/api/v2/route/route.proto#route-virtualhost
> Each virtual host has a logical name as well as a set of domains that get routed to it based on the incoming request’s host header. This allows a single listener to service multiple top level domain path trees. Once a virtual host is selected based on the domain, the routes are processed in order to see which upstream cluster to route to or whether to perform a redirect.

**Comment by rickducott** [comment]
VS merging has been removed.
