### ISSUE TITLE
changelogs docs referring to GlooE issues produce 404s

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1289]
need to determine a better way to surface content from changelog issues in private repos, otherwise users who are not in the org cannot view the issue content.

**Comment by mitchdraft** [comment]
also note that links such as https://gloo.solo.io/changelog/#v0-16-0 fail to resolve the GlooE target if there was a Gloo release with the same name (both use `#v0-16-0`)

**Comment by rickducott** [comment]
Known, don't think we're going to go back and try to fix, or we can reopen (this has gone stale).
