### ISSUE TITLE
clarify extauth clear route cache docs

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1309]
A user identified an ambiguous note in the docs:
https://gloo.solo.io/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/plugins/extauth/v1/extauth.proto.sk/

> Clears route cache in order to allow the external authorization service to correctly affect routing decisions. Filter clears all cached routes when: 1. The field is set to true. 2. The status returned from the authorization service is a HTTP 200 or gRPC 0. 3. At least one authorization response header is added to the client request, or is used for altering another client request header.

- [ ] update extauth docs

same comment used here https://gloo.solo.io/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/jwt/solo_jwt_authn.proto.sk/

- [ ] update jwt docs

Envoy's docs are equally ambiguous: https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto.html?highlight=route%20cache#config-filter-http-ext-authz-v2-extauthz

as we can see in the verification tests, **all three conditions must be met for clearing**:
https://github.com/envoyproxy/envoy/blob/master/test/extensions/filters/http/ext_authz/ext_authz_test.cc#L669

**Comment by rickducott** [comment]
Closing as stale.
