### ISSUE TITLE
Glooctl uninstall doesn't remove custom resources or crds

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1313]
repro:
* `glooctl install gateway`
* `glooctl uninstall`

and then

* `kubectl get gateway -n gloo-system` returns non-empty
* `kubectl get us -n gloo-system` returns non-empty
* `kubectl get vs -n gloo-system` returns non-empty

* `kubectl get settings -n gloo-system` returns non-empty? (haven't checked)
* `kubectl get proxy -n gloo-system` returns non-empty? (haven't checked)
* `kubectl get authconfig -n gloo-system` returns non-empty? (haven't checked)
* `kubectl get routetable -n gloo-system` returns non-empty? (haven't checked)
* `kubectl get upstreamgroup -n gloo-system` returns non-empty? (haven't checked)

I know `glooctl uninstall --all` can catch this by deleting the namespace itself, but this can be slow because namespace deletion is slow

**Comment by rickducott** [comment]
Not sure if this was changed to add the extra option; closing as stale.
