### ISSUE TITLE
Support for sticky sessions

### ISSUE THREAD

**Issue by gregdurham** [solo-io/gloo#132]
Hello,
I am looking at this project, and it looks really neat. Thank you for putting the time and energy of supporting it. 

I have to support some legacy applications, and need to support a ring hash loadbalancer (sticky sessions). I know that envoy supports it in the V2 spec, but was wonder if it is possible to configure this in gloo for use with envoy? https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction-hashpolicy

Thanks!

**Comment by ilackarms** [comment]
We don't currently support this config but it's trivial to add. The code that needs to be modified lives in 
https://github.com/solo-io/gloo/blob/master/pkg/coreplugins/route-extensions/spec.go#L10

and 

https://github.com/solo-io/gloo/blob/master/pkg/coreplugins/route-extensions/plugin.go#L33

I can take a look at getting a patch for this through. Or, if you're familiar with Go, we'd happily review a PR for you :smiley_cat:

**Comment by justinpa-asg** [comment]
Still not supported?

**Comment by MikeSouza** [comment]
+1 to this

**Comment by mitchdraft** [comment]
this has been implemented in: https://github.com/solo-io/gloo/pull/1047
here are the docs: https://gloo.solo.io/advanced_configuration/session_affinity/
