### ISSUE TITLE
better query parameter matching for REST-to-gRPC transformation

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1327]
currently gloo supports header and path extraction during REST-to-gRPC translation

A primitive, order-sensitive, form of query parameter extraction is supported

Since query parameter ordering is arbitrary, Gloo should should not care about parameter ordering when extracting values

**Comment by mitchdraft** [comment]
parent issue: https://github.com/solo-io/gloo/issues/845

**Comment by rickducott** [comment]
Dupe of parent issue
