### ISSUE TITLE
extend FDS config to UDS

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1329]
FDS now supports whitelist/blacklist/disable config, since https://github.com/solo-io/gloo/pull/802

This feature would be useful for UDS as well

**Comment by mitchdraft** [comment]
argument for this feature:

in multi-team clusters, it is common practice to partition teams' activities by namespace. In such cases, teams will have no interest in a large portion of the services so it would be useful from a cleanliness perspective to have tighter control of where UDS operates

**Comment by rickducott** [comment]
Closed dupe already as stale
