### ISSUE TITLE
Switch base envoy container registry from docker to quay

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#1340]
As of 1.17 envoy-gloo will no longer be hosted on docker hub, but on quay. 
The following line in the envoy init docker file needs to be switched to `FROM quay.io/solo-io/envoy-gloo:0.1.15`
https://github.com/solo-io/gloo/blob/9b548005cc03e1ce5672858ef70ba2c1bd77ce32/projects/envoyinit/cmd/Dockerfile#L1

**Comment by rickducott** [comment]
Should be done
