### ISSUE TITLE
gateway has no way to access upstream with tls

### ISSUE THREAD

**Issue by willise** [solo-io/gloo#1357]
Only doc that client accesses gloo with server-side tls can be found.
I have an upstream listening on 443 port with tls. How can gloo access the upstream? Or how can I configure gloo with the cert?

**Comment by ilackarms** [comment]
hey, sorry about the confusion on this. our docs only provide a guide for configuring *server* side ssl, not *client side*.

the config lives on the *Upstream*. you add it by setting `spec.upstreamSpec.sslConfig.name=<secret name>` and `spec.upstreamSpec.sslConfig.namespace=<secret namespace>` 

i added a doc for this that will be published on the next gloo release (source can be found here: https://github.com/solo-io/solo-docs/blob/adcb3e0651eff069c9ed3b24db99084b029653f2/gloo/docs/gloo_routing/tls/client_tls.md)

**Comment by willise** [comment]
Thanks for the docs. It helps a lot.
