### ISSUE TITLE
cannot prefixRewrite with empty string ""

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1373]
given the current code

a config of 
```
prefixRewrite: ""
```

will be a no-op. (rather than trimming the prefix)

we should change `prefixRewrite` from `string` to `google.protobuf.StringValue`

**Comment by ilackarms** [comment]
@kdorosh

**Comment by kdorosh** [comment]
This is only a problem on `feature-rc1` after we flattened the prefixRewrite proto.

We should address the same ambiguity with host rewrite

**Comment by leosunmo** [comment]
Please make sure to clearly state the behaviour of this if it changes in a release as it's a very critical feature.

**Comment by kdorosh** [comment]
@leosunmo thank you for raising your concerns, we appreciate all feedback. 

This is not a change we are releasing imminently, and it will be part of a breaking change with clear upgrade implications and documentation, both in the changelog and in our docs
