### ISSUE TITLE
Consider enabling strict resource validation by default

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1374]
The [Validating Webhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook) introduced with release 0.20.3 is now configured to always accept resource and just report errors as warnings by default. This was done to reduce the impact of potential bugs (which, in case of a webhook, can block operations on the resources). We should enable strict validation (i.e. reject resources that produced errors) when we are reasonably sure that the webhook is stable.

**Comment by rickducott** [comment]
Closing as stale
