### ISSUE TITLE
Reduce build context sent to docker daemon

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1378]
During the `compile` step of our cloudbuild we generate the binaries in the `_output` directory and run `docker build` from that directory multiple times. The whole directory is sent to the docker daemon each time, causing the build context to grow to almost 0.5GB.

```

Sending build context to Docker daemon  89.32MB
Sending build context to Docker daemon    155MB
Sending build context to Docker daemon  215.1MB
Sending build context to Docker daemon  299.7MB
Sending build context to Docker daemon  327.5MB
Sending build context to Docker daemon  388.6MB
Sending build context to Docker daemon  456.5MB
Sending build context to Docker daemon  480.2MB
```

This is an easy fix that might save us precious minutes on every build.

**Comment by marcogschmidt** [comment]
See [here](https://github.com/solo-io/solo-projects/pull/1260) for more ideas on improvements.

**Comment by rickducott** [comment]
This has become stale - I am closing out. We can revisit this, or other CI tasks, as part of ongoing stability work.
