### ISSUE TITLE
Was gloo v0.20.6 released twice?

### ISSUE THREAD

**Issue by karuppiah7890** [solo-io/gloo#1393]
I'm a contributor for https://github.com/fishworks/fish-food . 

The [soloio-bot](https://github.com/soloio-bot) recently raised a PR for the update to version v0.20.6 - https://github.com/fishworks/fish-food/pull/412  . The date and time of the PR is October 11th 2019 1:26 AM IST (Indian Standard Time). And the tests for the PR passed - which verifies checksum of the tarballs. The PR was merged too.

After that PR, [other commits](https://github.com/fishworks/fish-food/commits/master) were made to the repo, mostly other PRs getting merged. But every other commit failed the tests, starting from the commit of this PR https://github.com/fishworks/fish-food/pull/413 and PR date time is October 11th 2019 5:21 PM IST . On checking I noticed that gloo checksum validation failed in all the tests. 

Now when I check gloo's releases, I see that the release date time for gloo v0.20.6 is October 11th 2019 8:14 AM IST . This kind of clearly shows that it was released twice. Can someone tell me if this is true? I'm sure there was some reason to it. I guess soloio-bot could work appropriately in such cases, or someone could trigger it manually to fix the fish-food. 

And I'm raising the issue as I usually wouldn't expect a release coming up twice - it's either suspicious (someone hacking etc) , or may be a bad practice if the release contents are changed but the version number is the same

Aslo cc'ing @marcogschmidt the releaser

**Comment by bacongobbler** [comment]
it's quite possibly related to https://github.com/solo-io/squash/issues/220. A recent change in glooctl may be causing a rebuild of the release to change the checksum. In other words, rebuilding the release assets from the same branch twice can result in conflicting checksums.

**Comment by rickducott** [comment]
The gloo issue was unrelated. We had a release build timeout halfway through publishing artifacts and I think we triggered the build. Unlike the squash issue, our releases in gloo (and all repos) should be idempotent, and we typically wouldn’t retag at a different SHA, so the checksum difference is surprising. I will follow up to figure out what we did wrong on the process side, the release timeout has also been adjusted.

**Comment by marcogschmidt** [comment]
@karuppiah7890 @rickducott This was my mistake. After the original v0.20.6 release timed out, I merged a commit with a fix and then re-released with the same tag. I had deleted the v0.20.6 tag and what I thought were all the artifacts published by the failed release, but I missed that PR opened by our bot. Sorry about the inconvenience, we'll make adjustments on our side to avoid these kinds of errors going forward.

**Comment by bacongobbler** [comment]
It looks like the same result occurred with 1.1.0 as well: https://circleci.com/gh/fishworks/fish-food/963?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
!!! shasum verify check failed: checksums differ for /root/.gofish/glooctl-1.1.0-darwin-amd64: expected 'afcfa0e9c18ebbc05cafdec2277554b5c9946c19a8b8cc01e15e6b42f84a61f9', got '18713e72e997e70c787573e5c50ab85f35b26a93c1cfc25cd247b26792fa21af'
!!! shasum verify check failed: checksums differ for /root/.gofish/glooctl-1.1.0-linux-amd64: expected '37529da72ef95062a59e33679bacf2bb97d9dd1fe53bc662a383593de5a70fed', got '457847745c31bf7d458fd20e84b1c6da6c307eab462b015fecf09bc736171d13'
!!! shasum verify check failed: checksums differ for /root/.gofish/glooctl-1.1.0-windows-amd64.exe: expected '1d528aa2ee361e9151469e8493af7a81616511a4e34ed7d332d6839f8eee69f5', got '65a07c8728eea2c42bab0eb1bfd0230c59c9a865faf528826fb55882e4fdb9df'
Error: 3 errors encountered while linting glooctl
```

Is this due to the same situation? I cannot maintain a package for glooctl if releases continue to be re-written after they're released. @soloio-bot bot opened the PR to bump glooctl 3 days ago at https://github.com/fishworks/fish-food/pull/468. Can you please look into this?
