### ISSUE TITLE
Required change to Settings

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1394]
Somewhere along the way you required a new field in the `Settings` object be set.  Your Helm chart sets it.  But for those of us with our own `Settings` object, this broke us.  Please update the release notes accordingly.

```
gateway:
    validation:
      alwaysAccept: false
```

**Comment by ilackarms** [comment]
@derrickburns are you seeing the following error? 

```
{"level":"fatal","ts":1571054271.227769,"logger":"gateway","caller":"setuputils/main_setup.go:76","msg":"error in setup: VALIDATION_MUST_START was set to true, but no validation configuration was provided in the settings. Ensure the v1.Settings {default gateway-test-4869-1} contains the spec.gateway.validation config","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/Users/ilackarms/go/src/github.com/solo-io/gloo/pkg/utils/setuputils/main_setup.go:76\ngithub.com/solo-io/gloo/projects/gateway/pkg/setup.Main\n\t/Users/ilackarms/go/src/github.com/solo-io/gloo/projects/gateway/pkg/setup/setup.go:11\nmain.main\n\t/Users/ilackarms/go/src/github.com/solo-io/gloo/projects/gateway/cmd/main.go:19\nruntime.main\n\t/usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:200"}
```

if so, you can simply disable validation via the helm chart: `--set gateway.validation=null`

**Comment by derrickburns** [comment]
I did, yes. I modified the settings object already and reinstalled.

Derrick

**Comment by rickducott** [comment]
Sorry about this. We are working harder to call out breaking changes in the release notes, and have a much more strict SLA with Gloo around breaking changes moving forward (they will be rare so we can support 3 month stable release cycles with Enterprise gloo).
