### ISSUE TITLE
json-grpc transcoding should not escape unicode

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1417]
# problem

as a user, i cannot return the response `{"text":"<a>some link</a>"}` from an upstream.

either the json-grpc transcoder filter or the transformation filter (both of which we use) is escaping unicode characters, causing `{"text":"<a>some link</a>"}` to always be returned as `{"text":"\u003ca\u003esome link\u003c/a\u003e"}`

# solution 

expose an api flag to allow disabling this escaping mechanism

**Comment by MikeSouza** [comment]
This might be an easy fix. I believe it's happening during the encoding of the struct to JSON.

https://golang.org/pkg/encoding/json/#Marshal
>String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. So that the JSON will be safe to embed inside HTML <script> tags, the string is encoded using HTMLEscape, which replaces "<", ">", "&", U+2028, and U+2029 are escaped to "\u003c","\u003e", "\u0026", "\u2028", and "\u2029". This replacement can be disabled when using an Encoder, by calling SetEscapeHTML(false).

**Comment by jamersonchequer** [comment]
Hi ilackarms,
Did you manage to solve this problem?
