### ISSUE TITLE
Error converting YAML to JSON - Found character that cannot start any token

### ISSUE THREAD

**Issue by david-freistrom** [solo-io/gloo#1453]
**Describe the bug**
Tiller server respond with an Error while trying to convert YAML to json: 
'found character that cannot start any token' for different yaml templates

**To Reproduce**
1. helm repo add gloo https://storage.googleapis.com/solo-public-helm
2. helm fetch --untar=true --untardir=. gloo/gloo
3. helm install gloo --namespace gloo-system -f gloo/values-knative.yaml

**Expected behavior**
Deploy Knative with Gloo

**Additional context**

Error: YAML parse error on gloo/templates/1-gloo-deployment.yaml: error converting YAML to JSON: yaml: line 36: found character that cannot start any token

or

Error: YAML parse error on gloo/templates/3-discovery-deployment.yaml: error converting YAML to JSON: yaml: line 32: found character that cannot start any token

or more depend on which template comes first

**Comment by ilackarms** [comment]
following the steps above,  I was not able to reproduce:

```
helm repo add gloo https://storage.googleapis.com/solo-public-helm

"gloo" has been added to your repositories
```
```
helm fetch --untar=true --untardir=. gloo/gloo
```

test with `helm template`:
```
helm template gloo --namespace gloo-system -f gloo/values-knative.yaml
#
# manifest content omitted
#
```

install:
```
helm install gloo --namespace gloo-system -f gloo/values-knative.yaml
NAME:   binging-ladybug
LAST DEPLOYED: Wed Oct 23 08:37:27 2019
NAMESPACE: gloo-system
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                           DATA  AGE
gloo-usage                     0     1s
knative-external-proxy-config  1     1s
knative-internal-proxy-config  1     1s

==> v1/Deployment
NAME                    READY  UP-TO-DATE  AVAILABLE  AGE
discovery               0/1    1           0          1s
gloo                    0/1    1           0          1s
ingress                 0/1    1           0          1s
knative-external-proxy  0/1    1           0          1s
knative-internal-proxy  0/1    1           0          1s

==> v1/Pod(related)
NAME                                     READY  STATUS             RESTARTS  AGE
discovery-84c957ddb8-xdzxg               0/1    ContainerCreating  0         1s
gloo-66cb5564db-7n6m9                    0/1    ContainerCreating  0         1s
ingress-7b848764d7-c5257                 0/1    ContainerCreating  0         1s
knative-external-proxy-c777b5768-9spvq   0/1    ContainerCreating  0         1s
knative-internal-proxy-648996db66-tj5v7  0/1    ContainerCreating  0         1s

==> v1/Service
NAME                    TYPE          CLUSTER-IP    EXTERNAL-IP  PORT(S)                     AGE
gloo                    ClusterIP     10.7.243.197  <none>       9977/TCP,9988/TCP,9966/TCP  1s
knative-external-proxy  LoadBalancer  10.7.252.54   <pending>    80:31055/TCP,443:32607/TCP  1s
knative-internal-proxy  ClusterIP     10.7.254.216  <none>       80/TCP,443/TCP              1s

```

what version of helm are you using? my side:

```
helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Comment by pushm0v** [comment]
I've this issue on my cluster as well, my helm info :
`helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}`

**Comment by LorenzoFernando** [comment]
Make sure you're using spaces instead of tabs. 

Credit: https://github.com/moraes/config/issues/1#issuecomment-18842169

**Comment by Maduflavins** [comment]
> Make sure you're using spaces instead of tabs.
> 
> Credit: [moraes/config#1 (comment)](https://github.com/moraes/config/issues/1#issuecomment-18842169)

wow so am supposed to use four line spaces instead of tabs

**Comment by jorgonzalez** [comment]
> > Make sure you're using spaces instead of tabs.
> > Credit: [moraes/config#1 (comment)](https://github.com/moraes/config/issues/1#issuecomment-18842169)
> 
> wow so am supposed to use four line spaces instead of tabs

`cat -T yourfile.yaml | grep "^^I"`

**Comment by RorisangSitoboli** [comment]
Use two spaces instead of tab-as stated earlier.

**Comment by AdarshNaidu** [comment]
This command worked for me

`find . -name '*.yaml' ! -type d -exec bash -c 'expand -t 4 "$0" > /tmp/e && mv /tmp/e "$0"' {} \;`

src: https://stackoverflow.com/questions/11094383/how-can-i-convert-tabs-to-spaces-in-every-file-of-a-directory

**Comment by totovelo10** [comment]
> This command worked for me
> 
> `find . -name '*.yaml' ! -type d -exec bash -c 'expand -t 4 "$0" > /tmp/e && mv /tmp/e "$0"' {} \;`
> 
> src: https://stackoverflow.com/questions/11094383/how-can-i-convert-tabs-to-spaces-in-every-file-of-a-directory

This very helpful!
