### ISSUE TITLE
Allow defining unique IDs for cluster-scoped RBAC resources

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1459]
We should update the Gloo Helm chart to allow users to generate unique names for cluster-scoped RBAC resources (e.g. `ClusterRole`s), so to enable multiple Gloo installations to the same cluster if the user chooses not to use single-namespaced RBAC config.

**Comment by GrahamGoudeau** [comment]
I've found that our grafana and prometheus subcharts do not allow customization of the cluster-scoped RBAC resources that they create, so there would likely be conflicts on these if a user does another install into a different namespace. The solution for that may be to disable grafana/prometheus at install time, or just fix manually after the gloo installation.

**Comment by GrahamGoudeau** [comment]
Turns out we already had a template helper function to do this, but were applying it only to the role-bindings and not to the roles, for some reason. My PR corrects this.

**Comment by kdorosh** [comment]
@ceosbestfriend it will go out with Gloo 0.21.0 and Gloo 1.0.0-rc3
