### ISSUE TITLE
Data races in e2e tests

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1464]
**Describe the bug**
The `ginkgo` race detector fails on the e2e tests. See [this build](https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=857a48e9-f3b5-4390-a569-8b822dfeafaa).

**To Reproduce**
Run `ginkgo` with the `-race` flag in the `test/e2e` directory.

**Comment by marcogschmidt** [comment]
Another [failed build](https://storage.googleapis.com/solo-public-build-logs/logs.html?)

**Comment by marcogschmidt** [comment]
Also see #1384

**Comment by rickducott** [comment]
Seems like these were resolved
