### ISSUE TITLE
Add homebrew/fish formulas for different Gloo versions

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1478]
Akin to the example of other major projects, we should have formulas for each supported minor/major release of Gloo.

e.g., how `go` does it:
* a formula for [1.12](https://github.com/Homebrew/homebrew-core/blob/master/Formula/go@1.12.rb)
* a formula for [1.11](https://github.com/Homebrew/homebrew-core/blob/master/Formula/go@1.11.rb)
* an [alias](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/go@1.13) for `go@1.13` to `go`
* most recent [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/go.rb) under `go`

we should adopt the same pattern for `glooctl`

**Comment by rickducott** [comment]
Going to close as stale. Generally, I think we need to get better at maintaining our current integrations before adding more. Don't think we intend to prioritize this in the short term.
