### ISSUE TITLE
Release process and changelog for `feature-rc1` is broken

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1482]
**Describe the bug**
Docs changelog generation will fail on a release because the changelog files necessary to generate the markdown will not be in the expected local directory

**Relevant Codepath**
* cloudbuild tries to publish docs: https://github.com/solo-io/gloo/blob/feature-rc1/cloudbuild.yaml#L209
* we are in a release build, thus we try to publish docs: https://github.com/solo-io/gloo/blob/feature-rc1/Makefile#L434-L442
* pushing docs depends on `site-release` make target: https://github.com/solo-io/gloo/blob/feature-rc1/docs/Makefile#L87
* `site-release` make target depends on `site-common` target: https://github.com/solo-io/gloo/blob/feature-rc1/docs/Makefile#L44
* `site-common` make target generates GlooE changelogs: https://github.com/solo-io/gloo/blob/feature-rc1/docs/Makefile#L34
* the go script to generate this markdown expects files to exist that won't be there in CI: https://github.com/solo-io/gloo/blob/feature-rc1/docs/cmd/generate_changelog_doc.go#L153-L156

**Proposed Solution**
Upload changelog directory for Gloo and GlooE as part of CI to a google storage bucket, and download them before generating the changelog markdown.

This is preferable to automatically generating PRs against Gloo and hosting the files there in CI because it avoids the complication of determining which branch to open PRs against.

**Comment by kdorosh** [comment]
cc @mitchdraft confirmed that the release build would be broken, test build here: https://console.cloud.google.com/cloud-build/builds/027235a9-5b31-461b-9c94-fecad9bcba31?project=solo-public

link that will work for general public: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=027235a9-5b31-461b-9c94-fecad9bcba31

will tackle mounting the repo contents and/or uploading the changelogs to a google storage bucket tomorrow so we can fix this issue

**Comment by mitchdraft** [comment]
Thanks for verifying this. It sounded like you and Rick were leaning towards the mounted repo approach. That could be simpler than the storage bucket as it would be more similar to our dev environments and allow us to choose the solo-project branch more easily (in case we get to a state where solo-projects branches like gloo now does)

Let me know if I can help

**Comment by kdorosh** [comment]
Opted for the storage bucket because in the future I'd like to restrict the permissions of the GitHub token we decrypt during CI in OS Gloo, such that mounting a closed-source repo would be impossible.
