### ISSUE TITLE
rename gateway and gloo controllers in helm charts

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1484]
# the problem

the naming system we currently use for Gloo components can be very confusing. in particular the names `gloo` and `gateway` can be quite confusing and are heavily overloaded terms in our system to date.

i recommend we rename `gateway` to `gateway-controller` and `gloo` to `proxy|envoy|xds-controller` to clarify the roles of each in Gloo

the same can be said for renaming `ingress`to `ingress-controller`

any thoughts on this?

**Comment by kdorosh** [comment]
I like the rename, I too think the word Gloo especially is heavily overloaded

**Comment by rickducott** [comment]
Unfortunately, going to have to close as Stale. This would be a fairly extensive rename and I don't think we intend to make the change any time soon; we can reopen when we want to revisit.
