### ISSUE TITLE
use s3 or other cloud bucket for docs images

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1490]
goal is to keep the docs container images and the code repos small

will also need to make some simple utilities for making it easier to develop locally (pull, edit, add images, etc)

could be implemented in a way similar to the `protobuf` shortcode: refer to the image by some id, look up the url from a hugo `data/` file - this would make it easier to track resources and references to them

**Comment by mitchdraft** [comment]
this will also help avoid issues like this https://github.com/solo-io/gloo/pull/1538

**Comment by rickducott** [comment]
Closing as stale
