### ISSUE TITLE
Creating oauth secrets with kubectl very difficult

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#1492]
**Is your feature request related to a problem? Please describe.**
It's very difficult to create oauth secrets manually without glooctl. 

**Describe the solution you'd like**
It should be possible to utilize `kubectl create secret` for oauth secrets. 

**Describe alternatives you've considered**
Alternative is to create a text file with a secret value embedded:
```
config:
  client_secret: asdf
```

Then create a secret: 
`kc create secret generic google-kc --from-file=extension=secret.txt`

Then annotate:
`kubectl annotate secret google-kc resource_kind='*v1.Secret'`

**Additional context**
For AWS secrets, we can create them with kubectl.

**Comment by mitchdraft** [comment]
similar issue for reference, adding another secret converter shown here https://github.com/solo-io/gloo/pull/990/files#diff-2cf2b5eaf57c679ef0b2b1137a674198R181

**Comment by rickducott** [comment]
Unfortunately, this is stale and I must close. We can reopen as necessary if it remains painful.
