### ISSUE TITLE
support hot restarts for Envoy when the bootstrap config changes

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1504]
currently, if the ConfigMap loaded to envoy (with the bootstrap config) changes, users must manually restart the Envoy pod (causing downtime)

**Comment by rickducott** [comment]
Closing as stale - as an anecdote, in a recent discussion with a customer, this wasn't much of a concern. We've talked about doing this for a long time but haven't prioritized, given the backlog I'm closing stale issues.
