### ISSUE TITLE
pull over healthcheck and other missing docs

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1505]
health check docs did not make it through during the port https://gloo.solo.io/gloo_routing/gateway_configuration/health_checks/

Also cherry pick new additions since last port

**Comment by ilackarms** [comment]
https://gloo.solo.io/introduction/deployment_arch/ seems to be missing as well

**Comment by mitchdraft** [comment]
done in https://github.com/solo-io/gloo/pull/1511
