### ISSUE TITLE
Can I create two gloo in one kubernetes cluster

### ISSUE THREAD

**Issue by tony-Ma-yami** [solo-io/gloo#1508]
Can I create two gloo in one kubernetes cluster, one of its watchs several namespaces, and the anthor one watchs others namespaces.

**Comment by ilackarms** [comment]
yes! a guide on doing so is available here: https://gloo.solo.io/advanced_configuration/multiple-gloo-installs/

**Comment by ilackarms** [comment]
going to close this issue for now, please feel free to reopen if you run into any issues or this does not answer your question

**Comment by kdorosh** [comment]
Also feel free to drop us a question on slack! https://slack.solo.io
