### ISSUE TITLE
docs: fix response message in upstream tls demo

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1519]
**Describe the bug**
the response/description is wrong

**To Reproduce**
Visit the docs: https://docs.solo.io/gloo/latest/gloo_routing/tls/client_tls/#try-the-request-again

```
The response should be an error:

Hello, world!
```

The text does not match output, update to include the expected error text

**Comment by rickducott** [comment]
Still seeing this and it's a really simple fix.
