### ISSUE TITLE
Improved access logging for WAF

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#1525]
Currently the modsecurity access logs are not implemented as they are blocking, and therefore do not fit into Envoy's filter model. These logs are very helpful for debugging/auditing purposes.

**Comment by yuval-k** [comment]
as discussed internally - we can support this using dynamic metadata

**Comment by antoniotamer** [comment]
Is there any way to get the modsecurity logs inside the envoy container, for local debugging purposes?

**Comment by rickducott** [comment]
There is a path forward for improved access logging using dynamic metadata, but this issue has gone stale as it hasn't been a priority, and I am going to close for now.

**Comment by rickducott** [comment]
This can be done by setting dynamic metadata in the WAF filter so that it can be available to envoy in the access log entries.

**Comment by yuval-k** [comment]
also note that if you increase the envoy log level to debug, you will see audit logs in debug log as well
