### ISSUE TITLE
Set gloo version to install via command line glooctl 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#1533]
**Is your feature request related to a problem? Please describe.**
Unable to specify the target install gloo version via command line. For example, 0.20.5 is available but 0.20.4 is still hardcoded in glooctl so cannot install 0.20.5. 

**Describe the solution you'd like**
Be able to run 'glooctl install ... --release 0.20.5'

**Describe alternatives you've considered**
Helm. E.g. 
helm fetch glooe/gloo-ee --version "0.20.5"
glooctl install gateway -f gloo-ee-0.20.5.tgz

**Additional context**
Make this configurable:
https://github.com/solo-io/gloo/blob/master/pkg/version/enterprise.go

**Comment by ashleywang1** [comment]
This was done in: https://github.com/solo-io/gloo/issues/1863

with the --version flag, in release v1.3.0
`glooctl install gateway --version 1.2.1` should now do what you want this to do.
