### ISSUE TITLE
Question on NATS-streaming integration

### ISSUE THREAD

**Issue by andytruong** [solo-io/gloo#155]
On `source_events_from_github` example, I found the quite magic stuff:

```
# Deploy NATS and minio
# --- this command only deply the NATS-streaming server and minio server
kubectl apply -f \
 https://raw.githubusercontent.com/solo-io/gloo/master/example/source_events_from_github/kube-deploy.yaml

# Create a route for nats
# --- Route HTTP requests to NATS
glooctl route create --sort \
    --path-exact /github-webhooks \
    --upstream default-nats-streaming-4222 \
    --function github-webhooks
```

I can track that NATS-streaming server is auto discovered: https://github.com/solo-io/gloo/blob/master/pkg/function-discovery/nats-streaming/discover_nats_test.go

Can you explain where's the logic that push the event to NATS-streaming? I can't see where the logic for github-webhooks is implemented.

Thanks.

Update: I found that gloo provide TCP filter for NATS-streaming upstream via https://github.com/solo-io/envoy-nats-streaming/blob/master/source/common/nats/message_builder.cc — I think NATS-streaming integration should have better documentation. Thanks again for great integration.

**Comment by yuval-k** [comment]
Yes, this is indeed the integration point. we felt that it had to be a filter to achieve adequate performance.
I'll close this for now - feel free to reopen if know if you have any other questions!
