### ISSUE TITLE
Add Helm Hook Delete Policy to ease deleting resources

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1567]
https://helm.sh/docs/developing_charts/#hook-resources-are-not-managed-with-corresponding-releases

a lot of resources (clusterrole, serviceaccount, etc) are having a pre-install hook now

this offers many benefits, namely controlling the order of installation, however, it makes it hard to do a clean delete gloo from a namespace

ticket is to add hook-delete-policy

**Comment by rickducott** [comment]
Closing as stale
