### ISSUE TITLE
function discovery: re-discovery failing after pod deletion

### ISSUE THREAD

**Issue by begoat** [solo-io/gloo#160]
Today we tried to use gloo on kubernetes to serve gRPC service for json compatiable client, we met some problems and need some help.
1. the function-discover depends on grpc reflecting feature which is relatively new and it is missing in doc, for our python server we forgot import that package and it took sometimes to work it out.
2. when the server is started and discovered by the function-discover, we do performance testing using `wrk -t4 -c2000 -d30s -T5s  --latency http://xxxxxx` then when adding new service, it will not be discovered any more. But i can monitor the gloo-system that all the pods are running. the logs is just `attempting to ..., and no more retries`
3. all the precedure is automatically, so i am a little worried about the stability. I mean if i come across problems above in the production mode, i can do nothing but to reinstall.

Could you give me some suggestions, which kind of log file do i need to debug, Thanks in advance.

**Comment by begoat** [comment]
I installed again and it worked as expected at the first time. But when i delete the service and apply again, then the function discover pod doesn't work while the pod is still running. I don't know why.  here is the python gRPC server docker image `docker pull killercai/backend:v1.0`, 
example [python-grpc-for-gloo](https://github.com/ciiiii/python-grpc-for-gloo).

**Comment by ilackarms** [comment]
logs from `function-discovery` pod would be helpful. post in a gist as they can be rather long.

can you enumerate the steps to reproduce this bug? we will try adding a test for it on our end

**Comment by begoat** [comment]
I use `kubectl logs -l gloo=function-discovery -n gloo-system >  function-discovery.log` to get
 [function-discovery.log](https://gist.github.com/begoat/e450f94b50769ce9419bf4ec3d7ef5b9)
Or direct get it from the kubernetes node `/var/lib/docker/containers/<long_container_id>/<long_container_id>-json.log`
[logs.json](https://gist.github.com/begoat/02dc84667fa08d6b0d61d392dae52724)

---

**Comment by ilackarms** [comment]
what version of `gloo` are you running? `kubectl describe deployment -n gloo-system function discovery` ?

**Comment by ilackarms** [comment]
i'm aware of the issue. `function discovery` caches the upstream the first time it successfully discovers functions for it, but doesn't clear the upstream from the cache if it's deleted. i'm creating a patch to fix this now.

thanks for the report!
