### ISSUE TITLE
glooctl add route needs an --azure-function-name option

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#1601]
**Is your feature request related to a problem? Please describe.**
There is no way to use glooctl to create a route referencing an Azure function

**Describe the solution you'd like**

```shell
glooctl add route \
  --name='default' \
  --namespace='gloo-system' \
  --path-prefix='/helloazure' \
  --dest-name="${AZURE_UPSTREAM_NAME}" \
  --azure-function-name="${AZURE_FUNCTION_NAME}"
```

**Describe alternatives you've considered**

```shell
kubectl apply --filename - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matcher:
        prefix: /helloazure
      routeAction:
        single:
          destinationSpec:
            azure:
              functionName: ${AZURE_FUNCTION_NAME}
          upstream:
            name: ${AZURE_UPSTREAM_NAME}
            namespace: gloo-system
EOF
```

**Additional context**

**Comment by rickducott** [comment]
Going to close as stale - not convinced `glooctl add route` is that useful beyond the very initial hello world examples, so I feel like it's fine not to support everything in that way. Happy to be wrong if others have different opinions.
