### ISSUE TITLE
Extractor's documentation states the `header` source twice.

### ISSUE THREAD

**Issue by kdelorey** [solo-io/gloo#1622]
A trivial copy and paste error (probably) exists in the documentation under the [Transformations/extractors](https://docs.solo.io/gloo/latest/gloo_routing/virtual_services/routes/routing_features/transformations/#extractors) section. It states the following:

>>>
    header: extract information from a header with the given name.

    extractors:
      myExtractor:
        header: 'foo'

    header: extract information from the body. This attribute takes an empty value (as there is always only one body).

    extractors:
      myExtractor:
        body: {}
>>>

The `header` label is used twice where the 2nd instance should be `body`.

**Comment by marcogschmidt** [comment]
Hi @kdelorey, thanks for flagging this! Will fix it right away.

**Comment by marcogschmidt** [comment]
Corrected docs have been released
