### ISSUE TITLE
Move installation ID into a global variable for 1.0

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#1635]
installation ID is currently not in a global variable. In the move to 1.0, we should move the helm value into a global variable.

**Comment by kdorosh** [comment]
I would prefer `global.glooInstallId` or `global.gloo.installId` to avoid potential conflicts with other charts if they use Gloo as a subchart

**Comment by kdorosh** [comment]
Alternatively, and even cleaner, we could continue to use `gloo.installId` but then pass `.Values.gloo.installId` to the helper in Gloo and `Values.gloo.gloo.installId` in GlooE.

Then update the helm helper to just use `.`
