### ISSUE TITLE
glooctl install gateway ignores values file when using the  ' --with-admin-console' flag

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1640]
When I run `glooclt install gateway` with and without `--with-admin-console`, I get unexpected results, namely my values file is ignored in the former case.

To reproduce, do this:

```
glooctl install gateway --values foo.txt --with-admin-console --dry-run >with
glooctl install gateway --values foo.txt  --dry-run >without
diff with without
```

It appears that my values file is ignored with `--with-admin-console` is provided.

[foo.txt](https://github.com/solo-io/gloo/files/3822754/foo.txt)

This is using 
```
$ glooctl --version
glooctl community edition version 0.20.6
```

**Comment by rickducott** [comment]
I suspect a problem here is the with admin console flag actually uses a different chart that wraps the gloo chart, to ensure the versions are compatible. But then the values need to be prepended with “gloo.” We are looking at better ways to manage helm across OS and enterprise...
