### ISSUE TITLE
Warning in Gateway proxy logs

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1642]
FYI:

`[2019-11-08 03:09:22.493][10][warning][misc] [external/envoy/source/common/protobuf/utility.cc:282] Using deprecated option 'envoy.api.v2.route.HeaderMatcher.regex_match' from file route.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.`

Version:
quay.io/solo-io/gloo-envoy-wrapper:0.20.8

**Comment by yuval-k** [comment]
yes, we are aware of this and planning to fix the deprecated envoy apis shortly after kubecon. note that factionality is not impacted as envoy has long deprecation cycles

**Comment by yuval-k** [comment]
cc @marcogschmidt @kdorosh

**Comment by kdelorey** [comment]
You're probably aware, but just in case, there is a warning for the depreciation of the CORS configuration too.

>The `allow_origin` and `allow_origin_regex` fields in `CorsPolicy` have been deprecated in favor of the `allow_origin_string_match` field.

**Comment by ashleywang1** [comment]
This should actually already be fixed. I needed to make an upstream change in the envoy go-control-plane, and it was merged: https://github.com/envoyproxy/go-control-plane/pull/273
The release came out on April 1st for Envoy version 0.9.6.
We picked up this change when we updated our envoyproxy/go-control-plane dependency in v1.4.0-beta1 of open source Gloo: https://github.com/solo-io/gloo/releases/tag/v1.4.0-beta1
