### ISSUE TITLE
CI must check that Helm values doc is up-to-date

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1643]
We recently added a new `installationId` Helm value. I noticed while reviewing [this unrelated PR](https://github.com/solo-io/gloo/pull/1638) that the generated Helm values file that we include in our docs was out-of-date. CI should verify that this file - and all generated docs - is up-to-date. We have to look into why this did not happen in this case.

**Comment by kdorosh** [comment]
I believe the target that generates the helm value only gets called on release builds :/

**Comment by EItanya** [comment]
Closing this was an error, linked issue did not resolve
