### ISSUE TITLE
glooctl uninstall knative can leave orphaned resources

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1646]
**Describe the bug**
 `glooctl uninstall knative` removes the knative control plane and knative crds. this is problematic because user CRDs will have a `finalizer` that is supposed to be processed by the knative control plane. we need to ensure all those CRDs are cleaned up before removing the control plane, otherwise they can get into a bad state.

see conversation: https://knative.slack.com/archives/C9JP909F0/p1573138874123000

**To Reproduce**

```
$ glooctl install knative --install-eventing=true

$ kubectl apply -f subscription.yaml # create a subscription CRD, a finalizer will get added

$ glooctl uninstall knative
 
$ kubectl api-versions | grep knative
eventing.knative.dev/v1alpha1 # should no longer exist, but does
```

**Comment by CelsoSantos** [comment]
Adding some information to this:

According to the team at Knative, one can execute `kubectl delete knative --all --all-namespaces` to clean every Knative resource, prior to uninstallation with `glooctl`.

This also applies if the uninstallation failed, once knative has been reinstalled.
