### ISSUE TITLE
glooctl: Should error if namespace unset

### ISSUE THREAD

**Issue by Dominik-K** [solo-io/gloo#1647]
**Describe the bug**
`glooctl` doesn't give an error message saying that the namespace it's looking in is not created at all. E.g.(?) `glooctl get upstreams` returns just empty upstream list which is wrong. That's even more bad as this command is also given without the namespace flag in the [hello-world-example](https://docs.solo.io/gloo/latest/gloo_routing/hello_world/#steps).

I've installed Gloo in another namespace than the default `gloo-system`. 

**To Reproduce**
1. `glooctl install gateway -n non-default`
2. `glooctl get upstreams` just returns
```
+----------+------+--------+---------+
| UPSTREAM | TYPE | STATUS | DETAILS |
+----------+------+--------+---------+
+----------+------+--------+---------+
```
3. `glooctl get upstreams --namespace non-default` returns many upstreams.

**Expected behavior**
An error message saying sth. like `Namespace 'gloo-system' is not created. Did you install it in another namespace & forgot to add '-n NAMESPACE' flag?`

**Comment by GrahamGoudeau** [comment]
@Dominik-K have you seen our `glooctl check` command? 

```
(⎈ |manual-testing:default)~/go/src/github.com/solo-io/gloo > ./_output/glooctl check
Checking deployments... Gloo namespace does not exist
Error!
namespaces "gloo-system" not found
```

that may be what you're looking for

**Comment by Dominik-K** [comment]
@GrahamGoudeau I'm aware of `glooctl check`. However, every command must error if the namespace it's looking at doesn't exist at all. Even more not giving a success output with an empty list. That's really bad UX.
