### ISSUE TITLE
Remove log.Debug lines in three syncers

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#1679]
envoyTranslatorSyncer
fds syncer
uds syncer

Remove the `log.Debug("%v")` line, ie https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/syncer/envoy_translator_syncer.go#L59

**Comment by kdorosh** [comment]
why remove the debug line? we shouldn't be seeing this because we should be on the INFO level by default
