### ISSUE TITLE
Improve architecture docs

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1693]
The [current architecture docs](https://docs.solo.io/gloo/latest/introduction/architecture/) are a bit outdated and give only a high level abstraction of the system that makes it hard to understand which deployment/pods are actually responsible for what.

We should refactor these docs to at least explain what the inputs and outputs of each server component (i.e. `gloo`, `gateway`, etc.) are.

**Comment by marcogschmidt** [comment]
@christian-posta

**Comment by kdorosh** [comment]
public community asking for clarity again here: https://solo-io.slack.com/archives/C9L6VPAUW/p1577382012161900

**Comment by ned1313** [comment]
This is being addressed by the changes in PR #2293 

Introduction section is being rewritten and new diagrams are being created.
