### ISSUE TITLE
Add flags to create secured virtual service

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1705]
**Is your feature request related to a problem? Please describe.**
you can’t set the --ssl-secret-name & --ssl-secret-namespace on `glooctl create virtualservice`, only on `glooctl edit virtualservice`

**Describe the solution you'd like**
Add those flags to the create command

**Comment by Dominik-K** [comment]
When you're on it, then also validate the input. E.g. if the `--ssl-secret-namespace` does not exist, etc.

**Comment by GrahamGoudeau** [comment]
Can also use this issue to add flags for --all-namespaces (-A)

https://solo-io.slack.com/archives/C9L6VPAUW/p1573755619420200
