### ISSUE TITLE
Add "glooctl ui" shortcut for getting to the UI

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#1706]

**Comment by kdorosh** [comment]
perhaps `glooctl dashboard` to mirror `kubectl dashboard`?

**Comment by rickducott** [comment]
+1 from Idit on this as well

**Comment by Dominik-K** [comment]
@kdorosh 
> we should also alias it to `glooctl dashboard` to mirror `kubectl dashboard`

In which `kubectl` version does this exist? Don't have it in `v1.16.2`. Isn't the K8s dashboard somehow deprecated?

**Comment by kdorosh** [comment]
@Dominik-K ah, my mistake, I was thinking of `minikube dashboard`.

**Comment by kdorosh** [comment]
We should also consider opening the dashboard after install
