### ISSUE TITLE
Investigate High resource usage in Gloo

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#1711]
Some gloo users are experiencing high memory usage. Specifically noticed that `allocs` and `heap` keeps growing in /pprof.

@GrahamGoudeau had also noticed some strange/similar behavior in the observability pod. This issue more than anything else is meant to track the issue as it unfolds.

**Comment by StrongMonkey** [comment]
Also in gloo logs I saw unnecessary sync triggered by `gloo-usage` configmap, which is updated every 5 seconds. From cpu profiling `hashUtil.HashAll` is chewing a lot of cpus.

**Comment by GrahamGoudeau** [comment]
Note that there are both high CPU issues and high memory usage issues going on

**Comment by eko0126** [comment]
Is there a temporary solution,Our CPU has always been very high

![image](https://user-images.githubusercontent.com/35908820/69687892-6b3baf80-10ff-11ea-92ec-a3325dabd1ea.png)

**Comment by EItanya** [comment]
A fix for this is currently being worked in https://github.com/solo-io/solo-kit/pull/327.
Once this PR goes through, a Gloo PR will be created and I will update

**Comment by EItanya** [comment]
Reopening because this change has not yet made it into gloo, solo-kit merged, next is gloo
