### ISSUE TITLE
Helm configuration allowing Gateway controller to process virtual services cross-namespace

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#1716]
Behavior was changed in https://github.com/solo-io/gloo/issues/1142 but this is actually a regression for some users. We need a Helm escape hatch.

**Comment by ibuildthecloud** [comment]
Yes, it would be nice if this was configurable.  As a possible mitigation to the original issue https://github.com/solo-io/gloo/issues/1142, maybe the gateway can take a list of namespaces it will watch.

**Comment by kdorosh** [comment]
handled by https://github.com/solo-io/gloo/pull/1763
