### ISSUE TITLE
Upgrade to 1.0 documentation issues

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1728]
https://docs.solo.io/gloo/latest/changelog/open_source/

Please add documentation of the change from: 
* `plugins` to `options` in the `Gateway` object
* `corsPolicy` to `cors` in `VirtualHostOptions` field
*  `virtualHostPlugins` to `options` in VirtualService object
* `matcher` to `matchers` in `Route` object
* `apiVersion: gateway.solo.io.v2/v2` to ` gateway.solo.io/v1`
*  `routePlugins.prefixRewrite` to `options`

**Comment by GrahamGoudeau** [comment]
@derrickburns this is currently in progress as my highest priority item, although I haven't been tracking it with a github issue. I expect to get this out today or maybe tomorrow morning.

**Comment by kdorosh** [comment]
doc examples/API references have been updated, and 1.0 upgrade docs going out once we address: https://github.com/solo-io/gloo/pull/1740#discussion_r349399153
