### ISSUE TITLE
solo bot stops creating PRs recently

### ISSUE THREAD

**Issue by chenrui333** [solo-io/gloo#1729]
Relates to https://github.com/Homebrew/homebrew-core/pulls?utf8=%E2%9C%93&q=is%3Apr+glooctl

Looks like `soloio-bot` stops creating PRs recently. :)

**Comment by chenrui333** [comment]
I just added a new one for the most recent release. https://github.com/Homebrew/homebrew-core/pull/46825

**Comment by marcogschmidt** [comment]
Hi @chenrui333 , thanks for bringing this to our attention and for updating the `homebrew-core` formula. We have temporarily disabled the automatic updates to our `glooctl` formulas in the context of our recent release of Gloo 1.0 and are planning to re-enable them soon. In the meantime you can download any desired version of `glooctl` from the [release page](https://github.com/solo-io/gloo/releases) of the Gloo GitHub repository.

**Comment by chenrui333** [comment]
Thanks that is good to know, that is basically what I did.
