### ISSUE TITLE
Authetication Question

### ISSUE THREAD

**Issue by amapi** [solo-io/gloo#173]
hello, got a question, i have a new route to my monolith created with gloo "glooctl route create --path-prefix / --upstream myoldapp-8080", and i would know if i can set any kind of auth (at least basic) on this route, so user have to authenticate when then call "h t t p :// myserver /", thanks a lot

**Comment by ilackarms** [comment]
@amapi @ilevine can speak more about this feature

**Comment by rickducott** [comment]
Hi @amapi, currently open source Gloo doesn't support any kind of auth on routes, though envoy does and it would be possible to support this capability in Gloo. We welcome PRs to extend Gloo with features like this, and we are also releasing an enterprise offering for Gloo that will contain additional features for auth. If you'd like to discuss enterprise Gloo, please reach out here: www.solo.io/enterprise

**Comment by rickducott** [comment]
(Leaving a related issue open https://github.com/solo-io/gloo/issues/139 until we have more specific details)
