### ISSUE TITLE
Possibility to disable JWT auth for pre-flight requests

### ISSUE THREAD

**Issue by CarpathianUA** [solo-io/gloo#1752]
**Is your feature request related to a problem? Please describe.**
Hey guys,
I'm trying to implement JWT auth on a Gloo Gateway Enterprise.
JWT auth works like a charm, but I've reviewed all of the Gloo's docs and API ref as well and didn't find any possibility to disable JWT auth for pre-flight requests (OPTIONS).

**Describe the solution you'd like**
Configuration option for JWT auth to easily disable auth for OPTIONS requests 

**Describe alternatives you've considered**
For example, Kong has this functionality out of the box in their JWT [plugin](https://docs.konghq.com/hub/kong-inc/jwt/#parameters), see `config.run_on_preflight`

**Additional context**
-

**Comment by rickducott** [comment]
Could we support this by splitting the traffic across two routes, the first only matching on OPTIONS requests, and the second apply JWT auth?
