### ISSUE TITLE
Helm install fails

### ISSUE THREAD

**Issue by mstrYoda** [solo-io/gloo#1760]
When I try to install gloo on my local minikube it gives the following errors:

<img width="1171" alt="Screen Shot 2019-11-22 at 10 45 14" src="https://user-images.githubusercontent.com/12763626/69407563-ccd1d780-0d15-11ea-92df-f9c469a0b25c.png">

I replaced all `$image =` to `$image :=` and after that it gives the following error:

`Error: apiVersion "gloo.solo.io/v1" in gloo/templates/18-settings.yaml is not available`

Also I got error about kebabcase:

`Error: parse error in "gloo/templates/9-gateway-proxy-configmap.yaml": template: gloo/templates/9-gateway-proxy-configmap.yaml:8: function "kebabcase" not defined`

I removed `| kebabcase` from all templates.

What I'm missing here?

Minikube
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad

Helm
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Comment by GrahamGoudeau** [comment]
I followed up on slack about this, but it seems that we don't support Helm 2.9.1. I can reproduce this issue. As we are currently working on support for Helm 3, I'm not sure that a fix for this will get prioritized any time soon, so your best bet is probably to upgrade to a newer minor version of Helm 2. I'm using Helm 2.14.3 on my own system which works well for Gloo.

**Comment by mstrYoda** [comment]
Thank you for information.

**Comment by EItanya** [comment]
@mstrYoda just wanted to quickly follow up about this. Did upgrading the version of helm 2 solve the issue? Our chart requires a template function introduced in a later minor version, as mentioned in the error from your ticket `function "kebabcase" not defined`. Unfortunately we will not be able to support any version of helm 2 which does not have this function.

**Comment by mstrYoda** [comment]
I ended up with installing without helm. So I do not know does upgrading solves the issue :/

**Comment by GrahamGoudeau** [comment]
Unsure why this was moved to Prioritized Next. I think we are not committing to supporting versions of Helm that are that old unless it becomes a customer requirement. Closing for now.
