### ISSUE TITLE
Cannot access gloo UI

### ISSUE THREAD

**Issue by geloizi** [solo-io/gloo#177]
I've followed the installation instructions at https://github.com/solo-io/gloo/blob/master/docs/getting_started/kubernetes/1.md using minikube. For some reason the UI isn't available. As I understand it's provided by `control-plane` service that I exposed through "port-forward"

```
kubectl port-forward --namespace=gloo-system control-plane-<pod id> 8081:8081 
```

The port is available but instead of html it replies some binary content (to be precise, the reply is 9 bytes: `00 00 00 04 00 00 00 00 00`). 

Could you explain how to connect gloo UI? 

Also there is some minor inconsistency in your document. "Petstore" API is served by `:8080/api/pets` and not by `:8080/petstore`.  There is no `list` action, etc.

**Comment by rickducott** [comment]
Hey @geloizi, thanks for reaching out. Unfortunately the Gloo UI is not available when running open source Gloo. Please contact us at https://www.solo.io/enterprise if you'd like to discuss using the UI or other enterprise features of Gloo. 

The getting started guide you linked uses the Gloo CLI (`glooctl`) and petstore demo to interact with Gloo. Was there somewhere in the docs that referenced the UI or should be made more clear?

We are working on a large update to open source Gloo which we'll be releasing this week. This includes a refresh of the getting started guide and should clear up any inconsistencies on there. Let us know if you have any more feedback!

**Comment by rickducott** [comment]
Closing out, let us know if you have any questions.
