### ISSUE TITLE
Ensure CI tests Gloo on Consul without kube config

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1776]
At some point we introduced a mandatory requirement for an existing kube config.

This was not caught in CI consul tests, presumably because the kube config still existed, even if we weren't actively using it.

slack context: https://solo-io.slack.com/archives/C9L6VPAUW/p1574861641156900

**Comment by kdorosh** [comment]
version 0.20.2 is the last version compatible with the consul demo https://docs.solo.io/gloo/latest/installation/gateway/docker-compose-consul/

**Comment by ilackarms** [comment]
related #1777
