### ISSUE TITLE
compatibility off-kubernetes is currently broken

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1777]
**Describe the bug**

when no kube config is present, Gloo crashloops with :

`gloo             | {"level":"error","ts":"2019-11-27T10:41:11.928Z","logger":"gloo.v1.event_loop.gloo","caller":"metricsservice/metrics_handler.go:33","msg":"err starting up metrics watcher","error":"invalid configuration: no configuration has been provided","errorCauses":[{"error":"no configuration has been provided"}],"stacktrace":"github.com/solo-io/gloo/projects/metrics/pkg/metricsservice.NewConfigMapBackedDefaultHandler\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/metrics/pkg/metricsservice/metrics_handler.go:33\ngithub.com/solo-io/gloo/projects/gloo/pkg/syncer.RunGlooWithExtensions.func7\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup_syncer.go:532"}`

**To Reproduce**

follow https://docs.solo.io/gloo/latest/installation/gateway/docker-compose-consul/

**Expected behavior**

no crash :)

**Additional context**

caused by the addition here: 

https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/syncer/setup_syncer.go#L522

brought to our attention by a user trying to run consul demo: https://solo-io.slack.com/archives/C9L6VPAUW/p1574861641156900

we should fix, and consider testing Gloo when no kubeconfig is present

**Comment by EItanya** [comment]
To follow up on this. The `handler` is already an interface. So we need to add an optional non-kube storage client for the metrics data.
