### ISSUE TITLE
Enforce the use of `versioned_link_path` in docs

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1781]
Docs will render fine locally without `layouts/shortcodes/versioned_link_path.html` https://github.com/solo-io/hugo-theme-soloio#examples-1 , but may be invalid once published to the live site.

We need some kind of validation to ensure we never publish docs with broken links

**Comment by yuval-k** [comment]
tryied to use versioned_link_path i get a link with a newline; this appears to break images

**Comment by ned1313** [comment]
All links have been switched out after this PR was merged. #2413
