### ISSUE TITLE
glooctl proxy url doesn't work for ingress

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#1787]
following the ingress guides, `glooctl proxy url --name ingress-proxy` returns the IP of the host that the ingress proxy is running on, not the Load Balancer/external IP

cc @kdorosh @marcogschmidt

**Comment by rickducott** [comment]
Was this closed because it's not an issue? Note, I think I've seen for gateway the CLI to return an incorrect cluster IP initially, and only returns the correct external Load Balancer IP after some period of time.
