### ISSUE TITLE
update gloo image in docs 

### ISSUE THREAD

**Issue by bettyjunod** [solo-io/gloo#1788]
update on the following pages https://docs.solo.io/gloo/latest/
![GlooDiagram_111519](https://user-images.githubusercontent.com/10804749/69977817-53d63b00-14e0-11ea-802d-5c69c5a3c54d.png)

**Comment by mitchdraft** [comment]
fyi @scranton this format will fix it:
```
![Gloo Architecture]({{% versioned_link_path fromRoot="/introduction/gloo_diagram.png" %}})
```

I made a pr here before realizing that you may have already started Scott: https://github.com/solo-io/gloo/pull/1798
If so, feel free to close mine
