### ISSUE TITLE
Remove gogoutils conversions code

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1793]
cc @EItanya @yuval-k 

As part of go-control-plane bump https://github.com/solo-io/gloo/pull/1767 we needed to create Gloo versions of Envoy protos for solo-kit's use.

This is because:
* go-control-plane uses goproto instead of gogoproto now
* this means we no longer get generated deep equals on each object
* solo-kit depends on the the deep equals

We should:
* update solo-kit to generate its own equals functions
* remove duplicate protos generated in different go packages (e.g., outlier detection)

This was a gross hack and should be addressed in the near term

**Comment by kdorosh** [comment]
This code is problematic for a number of reasons, but most dangerously:
* The conversion code is lengthy boilerplate, any renames/type changes will not be updated if proto is changed
* The conversion code is not tested at all
* If fields are added to the proto, we need to remember to add them to the conversion code (highly unlikely) or else we will introduce bugs

**Comment by EItanya** [comment]
solo-kit issue https://github.com/solo-io/solo-kit/issues/325 to track this.

**Comment by kdorosh** [comment]
@jehawley @EItanya just following up on our recent discussion.

As part of https://github.com/solo-io/gloo/issues/2914 we wanted to add new fields to our adopted envoy protos.

This conversion code may actually be un-removeable because our Gloo APIs need to live in Gloo (and thus be versioned with Gloo). Just because these example APIs are essentially passthrough doesn't mean that in truth they aren't Gloo protos and owned by Gloo, not Envoy. Thus, we should feel free to make Gloo-specific changes to them as well.

Leaving this ticket open to improve testing here and remove misleading comments.
