### ISSUE TITLE
Static Upstream tutorial is broken

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1801]
**Describe the bug**

https://docs.solo.io/gloo/latest/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/static_upstream/, requests sent to the static upstream return with a 403 Forbidden error

**Comment by kdorosh** [comment]
I think this just needs auto host rewrite: true, will check

**Comment by kdorosh** [comment]
tested, resolved by: https://github.com/solo-io/gloo/pull/1805
