### ISSUE TITLE
Grpc tutorial has malformed YAML

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1803]
**Describe the bug**
Copy-paste of the  [gRPC tutorial](https://docs.solo.io/gloo/latest/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/grpc_to_rest/) Virtual Service has invalid indentation. 

The example needs to be modified in order to work

**Comment by kdorosh** [comment]
its possible that was addressed here: https://github.com/solo-io/gloo/pull/1790/files#diff-b7acb7d7961e0763f8b0aaeefadc4187R133

**Comment by ilackarms** [comment]
@kdorosh the `routeAction` stanzas are indented 3 spaces too far to the right
