### ISSUE TITLE
Stop auto-generating settings/gateways in controllers

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1828]
context: https://github.com/solo-io/gloo/pull/1811#discussion_r353957297

we should stop creating default settings/gateways in gloo's controllers because:
* it's confusing
* it forces us to use helm hooks in a hacky way to avoid race conditions
* we already provide default resources with each gloo installation; a user must go actively delete them

**Comment by GrahamGoudeau** [comment]
https://github.com/solo-io/gloo/pull/1983
