### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by elitegit** [solo-io/gloo#1840]
When I installed Gloo in my local cluster, I notice a very high CPU usage and takes huge resources without doing anything and just by installing the software using helm

helm install gloo-gateway gloo/gloo --namespace gloo-system

My environment:
Ubuntu 18.04 server
Microk8s (Kubernetes)

**Comment by ilackarms** [comment]
@elitegit hi, I'm sorry to hear about your issue. Can you describe more about your cluster/environment where you saw Gloo with high CPU usage? What tools/commands did you use to determine the high CPU?

Running gloo on GKE, for example:

```
 kubectl top node
NAME                                                  CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
gke-ilackarms-manual-dev-default-pool-b529c37e-chtr   436m         5%     2252Mi          8%
```

I'm only seeing 5% CPU usage for my single-node cluster (with Gloo and an example app installed).

I have not tested against MicroK8s, but I have no reason to think this would affect Gloo performance.

For additional debug info it would be helpful if you can try collecting a CPU profile from Gloo:
```
kubectl port-forward -n gloo-system deployment/gloo 9091&

wget http://localhost:9091/debug/pprof/profile && \
go tool pprof --http :8080 ./profile
```

**Comment by ilackarms** [comment]
@EItanya is working on a set of performance improvements for the Gloo control plane. i would be interested to have you try to reproduce once those changes are released

**Comment by EItanya** [comment]
The issue @ilackarms is being tracked in #1711 
Closing this in favor of that one.
