### ISSUE TITLE
1.0.0-rc1 helm chart checked into repo

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#1842]
This doesn't belong:
![image](https://user-images.githubusercontent.com/27434432/70398625-750cbf00-19eb-11ea-88d8-ba68e1bc25e3.png)

**Comment by rickducott** [comment]
Note: this is only checked into "master", aka pre-1.0.

**Comment by rickducott** [comment]
This may be fixed, if not let's clean up

**Comment by ashleywang1** [comment]
https://github.com/solo-io/gloo/pull/2012
