### ISSUE TITLE
feature-rc1 should be renamed master

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#1843]
And master can be renamed 0.21.x or something to that effect. It is very confusing that the default branch is not 1.x

**Comment by ned1313** [comment]
This will be helpful for tutorials and examples that clone the repo as part of the exercise. Currently, I have to specify feature-rc1 in the `git clone` command to ensure the correct example files are pulled. Once feature-rc1 is renamed, the docs will need to be updated as well.

**Comment by kdorosh** [comment]
leaving open until we update docs that reference `feature-rc1` and PR templates.

the switch is done though
