### ISSUE TITLE
Upstream TLS not working

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1848]
@yuval-k 
I need to route to a TLS upstream.  I followed the example (and read all the API docs). (This is NOT output from the example, however.) 

However, I am getting an Envoy error:
```
[2019-12-09 03:14:09.817][7][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) listener-::-8443: Failed to load private key from <inline>
```

I retrieved the private key using `glooctl proxy served-config` (h/t @ilackarms).  I confirmed that the key is legal:
```
$ openssl rsa -in key -check -noout
RSA key ok
```

```
$ glooctl version
Client: {"version":"1.0.0"}
Server: {"type":"Gateway","kubernetes":{"containers":[{"Tag":"1.0.0","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.0.0","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.0.0","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.0.0","Name":"gloo","Registry":"quay.io/solo-io"},{"Tag":"1.0.0","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}
```

**Comment by yuval-k** [comment]
hi @derrickburns , can I close this?

**Comment by derrickburns** [comment]
@yuval-k  thanks again for your help!

For what it is worth, when the useProxyProto is mismatched to the setting of the Aws ELB, bad things happen that are hard to understand.  It would be useful to have Gloo check and warn.
