### ISSUE TITLE
Do not print version mismatch warning on "glooctl proxy url"

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1852]
![image](https://user-images.githubusercontent.com/16148461/70442191-d1132a00-1a63-11ea-9322-b3c993a769e1.png)

This breaks all the doc guides where we have commands in the form:
```
curl $(glooctl proxy url)
```

**Comment by kdorosh** [comment]
I think we should only have this error on install/upgrade commands

**Comment by rickducott** [comment]
Same as #1841 

The warning is just wrong, it only makes sense for open source, not when using enterprise gloo

**Comment by kdorosh** [comment]
> The warning is just wrong, it only makes sense for open source, not when using enterprise gloo

We should make it easy to _programmatically determine the OS Gloo version that GlooE depends on so the warning can make sense in GlooE.

Leaving the ticket open to track this work.

**Comment by marcogschmidt** [comment]
Use #1924 to track this.
