### ISSUE TITLE
Document Gloo's Secret format

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#1856]
Need to document Gloo's Secret format such that users can use a GitOps style of deploying secrets.

Gloo's secret format changed for Gloo 1.x, and upgrade documents should also be updated to at least note that the Secret format has changed.

**Comment by kdorosh** [comment]
@GrahamGoudeau this PR updates the extauth secret examples to the new format: https://github.com/solo-io/gloo/pull/1903

**Comment by kdorosh** [comment]
This has been resolved, see https://docs.solo.io/gloo/latest/upgrading/1.0.0/#breaking-changes-commonly-requiring-manual-action
