### ISSUE TITLE
flake in rate limiting test - envoy 404

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#1864]
Haven't seen this flake before -- envoy 404'd running a rate limit test. Extremely verbose logging in the build report: https://console.cloud.google.com/cloud-build/builds/6c1086b5-1e0c-4955-a6fe-2545fc498490?project=solo-public

**Comment by GrahamGoudeau** [comment]
I think this may be a duplicate of https://github.com/solo-io/gloo/issues/1514
