### ISSUE TITLE
Update metrics server for GlooE rate limit server with more advanced metrics

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1867]
Update the rate limit metrics server, to provide stats detailing a concise summary of rate limit rule breaches and the offending requests.

Related to https://solo-io.zendesk.com/agent/tickets/83

**Comment by EItanya** [comment]
Envoy exposes some rate-limit metrics by default, this may be a good place to start. https://docs.google.com/spreadsheets/d/1EG5VjHw_Dn8PmrMubOWbmKH7dzsW0JDQ6RJnR3nHC7c/edit?usp=sharing

**Comment by kdorosh** [comment]
Awaiting response from Vonage on zendesk ticket regarding their use case, and the two proposed solutions (access logging with ETL vs. configurable metric labels)
