### ISSUE TITLE
published gloo manifests do not contain crds 

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1877]
**Describe the bug**

on a cluster with no gloo crds pre-installed:

`kubectl apply -f https://github.com/solo-io/gloo/releases/download/v1.2.4/gloo-gateway.yaml`

result:

`Error from server (NotFound): error when creating "https://github.com/solo-io/gloo/releases/download/v1.2.4/gloo-gateway.yaml": the server could not find the requested resource (post gateways.gateway.solo.io)`

**Comment by christian-posta** [comment]
This is true on latest Gloo release 1.2.6

**Comment by EItanya** [comment]
The helm chart does ship with the CRDs, they just need to be explicitly added using the `crds.create=true` value.

**Comment by EItanya** [comment]
@christian-posta closing for now because of comment above

**Comment by christian-posta** [comment]
NO. We need to fix this. We deploy artifacts that DO NOT work. The `gloo-gateway.yaml` in the assets of any of our recent releases is WRONG. Re-opening.

**Comment by christian-posta** [comment]
Example (as stated in OP): try to deploy this manifest from our release:

`https://github.com/solo-io/gloo/releases/download/v1.2.7/gloo-gateway.yaml`

**Comment by GrahamGoudeau** [comment]
I think this is an easy fix. We should just pipe the output of glooctl --dry-run into those manifests. We can't really rely on Helm template anymore, because it doesn't output what we need.

(For the record though, I just contributed a PR to Helm to help alleviate that https://github.com/helm/helm/pull/7138)

**Comment by rickducott** [comment]
Thanks!
