### ISSUE TITLE
Stats server defaults don't match in Gloo and GlooE

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1884]
Gloo has most stats servers enabled by default.

This is not true for the same components in GlooE.

We should pick sane defaults for Gloo and accept the default in GlooE (do not provide values overrides for properties that aren't specific to GlooE)

**Comment by marcogschmidt** [comment]
@kdorosh What do you think of making `stats` a global value that would apply by default to all our pods?

**Comment by EItanya** [comment]
I agree with making stats a global value, maybe with the ability to turn off on the individual deployment as well? Similar to our global image tags

**Comment by GrahamGoudeau** [comment]
https://github.com/solo-io/gloo/pull/2010 <- move settings to global

**Comment by kdorosh** [comment]
Reopening until similar changes are made in GlooE

**Comment by rickducott** [comment]
This is in gloo enterprise, afaict.
