### ISSUE TITLE
Docs typos can break CI

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#1889]
People outside of solo engineering can /skip-ci on docs PRs that contain typos, which will then break our CI. We should think about how to avoid this happening.

**Comment by rickducott** [comment]
I think we should move spell check to a different status check altogether. I can see solo engineering also skipping CI and missing a spelling error in the code review.

**Comment by rickducott** [comment]
I'm not sure this has really proven to be a problem in practice. Please reopen if I'm mistaken.
