### ISSUE TITLE
Gateway service gets into non-recoverable state on transient error condition

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1915]
@ilackarms 
The gateway service can get into a non-recoverable state on change of virtual services with a Gateway CR explicitly lists which virtual services it uses.

Consider the situation where you change the set of virtual services on a Gateway that explicitly lists which virtual services it serves.  Unless the new virtual services are added and then the Gateway is updated, the gateway service will flag an error. This situation is common in a GitOps scenario, where new CRs are presented at once.

The error condition is transient, however, the affect on the gateway service is persistent.  AFAIK, one has to restart the Gateway service manually.

**Comment by EItanya** [comment]
@derrickburns thanks for the note. I think that the initial error state is valid, as the resources that the gateway relies on are not present. However, the error should go away once the virtual services have been applied. Will investigate.

**Comment by EItanya** [comment]
Should be fixed by https://github.com/solo-io/gloo/pull/1820
