### ISSUE TITLE
Update docs to use single, tagged, petclinic app

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1916]
We should update all `kubectl apply`/`kubectl delete` references to the petclinic to a single, pinned version, that's hosted in Gloo.

We should also make sure the version chosen is k8s 1.16 compliant, and then test all referencing tutorials with the new petclinic to make sure they do in-fact work.

Would also be nice to reference this version in one place in our docs so future updates can be done in a single location.

**Comment by EItanya** [comment]
The version on feature-rc1 is valid

**Comment by kdorosh** [comment]
Updated master to be 1.16 compliant, but will be updating docs to use a tagged version to be stable.
