### ISSUE TITLE
Improve glooctl version mismatch warning logic

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1924]
This ticket originated from #1852. We need to improve the logic for the check so that actually outputs meaningful warnings when there is a real mismatch.

**Comment by GrahamGoudeau** [comment]
Comment from the linked ticket: 

> We should make it easy to programmatically determine the OS Gloo version that GlooE depends on so the warning can make sense in GlooE.

**Comment by GrahamGoudeau** [comment]
We already have a check in place that effectively does this. We're looking at the version of the discovery pod, which will work for both open source and enterprise installations
