### ISSUE TITLE
Refactor `Destination` message

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1931]
breaking change:

We should consider refactoring the `Destination` message.

```proto
message Destination {

    oneof destination_type {
        core.solo.io.ResourceRef upstream = 10;
        KubernetesServiceDestination kube = 11;
        ConsulServiceDestination consul = 12;
    }

    DestinationSpec destination_spec = 2;
    Subset subset = 3;
}
```

My concerns:
- From just looking at the API, it is not possible to understand which `destination_type`s support `DestinationSpec` and `Subsets`
- Some `DestinationSpec`s intuitively feel like they should be destination_types (e.g. `aws`, `azure`)
- `Subsets` is a pretty low-level concept that I think we can expose in more intuitive ways (e.g. `ConsulServiceDestination`s allow you to target services based on tags and data centers; behind the scenes we use subsets, but the user does not have to be aware of that).

I think we can make this central part of our APIs much more user-friendly. Such a refactor will however require vast changes to most of Gloo's components, e.g. FDS, UDS, a good number of plugins, and all the Gloo translation logic.

**Comment by rickducott** [comment]
I don't think we're planning to make this breaking change for 1.3.x, so closing this issue.
