### ISSUE TITLE
Stop duplicating HCM settings in API protos

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1932]
Move:
```proto
    // prefix for addressing envoy stats for the tcp proxy
    string stat_prefix = 3;
```
In HttpListener and TcpListener into appropriate `HttpConnectionManagerSettings` message, or up higher because they apply to all listener types

**Comment by rickducott** [comment]
Not sure current status of this; regardless, don't think we intend to track for 1.3.x, going to close.
