### ISSUE TITLE
CRDs are not deleted by glooctl

### ISSUE THREAD

**Issue by MikeSouza** [solo-io/gloo#1938]
**Describe the bug**

Since `1.2.x`, `glooctl uninstall --all` and `glooctl uninstall --delete-crds` flags no longer remove CRDs.

**To Reproduce**
1. Install the Gloo `1.2.8` Helm chart with Helm 2
2. Install `glooctl` `1.2.8` (`glooctl upgrade --release=v1.2.8`)
3. Uninstall Gloo (`glooctl uninstall --all`)
4. See that Gloo CRDs still exist (`kubectl get crds`)
5. Uninstall Gloo with `--delete-crds` (`glooctl uninstall --delete-crds`)
6. See that Gloo CRDs still exist (`kubectl get crds`)

**Expected behavior**
I expect `glooctl` to uninstall CRDs.

**Additional context**
N/A

**Comment by marcogschmidt** [comment]
Fixed by #1971
