### ISSUE TITLE
Gloo fails to install if gloo-system namespace already exists

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo#1948]
```
glooctl install gateway
Error: installing gloo in gateway mode: Gloo has already been installed to namespace gloo-system
```

**Comment by kdorosh** [comment]
Is Gloo also already installed, like the error message says? if so, the error seems appropriate.

if it's just an empty namespace, then the error is wrong

**Comment by ashleywang1** [comment]
I talked to Graham about this -> I think we should soften it to just a printed line: 
Gloo has already been installed to namespace 
and then return. An error looks a little scary here.
