### ISSUE TITLE
Failover

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#1955]
Gloo today supports outlier detection in very specific scenarios, that being on a specific upstream. However, in order to support failover to another cluster, or any external service, we are going to allow more freedom in the way clusters are configured.

This can happen in a number of ways:
1) Envoy recently added support for [aggregated clusters](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/aggregate_cluster). This would most likely be the easiest way.
2) Envoy already has support for [locality](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/endpoint/endpoint.proto#endpoint-localitylbendpoints) in it's endpoints. We could leverage this, and create a new upstream type which could possibly combine endpoints from other upstreams and load balance between them.

**Comment by ilackarms** [comment]
for reference, user request on slack: https://solo-io.slack.com/archives/C9L6VPAUW/p1576421072024700?thread_ts=1576420784.024600&cid=C9L6VPAUW

**Comment by EItanya** [comment]
Finished by #3141
