### ISSUE TITLE
Test cluster cleanup

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1957]
The e2e tests on the current `master` branch (soon to be renamed to `0.x`) do not properly clean up cluster scoped resources after the tests are done. This has not been a problem until now, since the `glooctl install ...` commands used to just `kubectl apply` the Gloo manifest, but he latest `glooctl` fails if any resource that needs to be created already exists. This means that a `master` build in CI might create and not clean up cluster scoped resources, which will cause a e2e tests on the `feature-rc1` branch (soon to be renamed to `master`) to always fail.

**Comment by marcogschmidt** [comment]
A quick solution would be to have the e2e tests for the two branches run in different clusters.

**Comment by EItanya** [comment]
I agree with that approach, it is going to be hard to support running multiple versions in the same cluster at infinitum. Unless that’s something we’re interesting in testing as well

**Comment by rickducott** [comment]
Close as old since we are past 0.x days
