### ISSUE TITLE
Document Gloo OS -> Enterprise upgrade

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1958]
We currently only have guides on how to upgrade from one version of Gloo to another. We also need to document how to move from the open source version of Gloo to the enterprise one as some non-trivial steps are involved (mainly thinking about the `gloo` prefix for the helm subchart values).

**Comment by rickducott** [comment]
Similarly,  need to look at OS -> OS + readonly UI upgrade story.
