### ISSUE TITLE
Allow users to specify which version of gloo to install

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo#1965]
We should add this also to the open source install command, it's as easy as adding another if clause [here](https://github.com/solo-io/gloo/blob/6d972a451fc15c051bf5eba51c910ea049971c1f/projects/gloo/cli/pkg/cmd/install/installer.go#L190) and interpolating using the provided flag.

**Comment by kdorosh** [comment]
@ashleywang1 please link PR that is awaiting review

**Comment by ashleywang1** [comment]
https://github.com/solo-io/gloo/pull/1968

**Comment by ashleywang1** [comment]
This was merged into gloo.
