### ISSUE TITLE
glooe: cannot install without extAuth enabled

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1977]
```
Status:                                                                                          │
│  Reason:  1 error occurred:                                                                     ││           * HttpListener Error: ProcessingError. Reason: extauth server upstream not found name:│
│"extauth" namespace:"gloo-system"
```

From the gateway

**Comment by rickducott** [comment]
We have confirmed that this was likely related to glooctl installing an old enterprise version. On 1.0.0-rc7, the following values file doesn't install `extAuth`: 
```
global:
  extensions:
    extAuth:
      enabled: false
```

That said, in investigating this extAuth is also written into settings despite not being enabled.

**Comment by kdorosh** [comment]
Use the values linked [here](https://github.com/solo-io/gloo/issues/1979#issuecomment-566700116) to repro the issue
