### ISSUE TITLE
After upgrading to Gloo 1.2.10 

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1979]
```
 [2019-12-17 10:00:27.438][10][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) listener-::-8443: Error: multiple upgrade configs with the same name: 'websocket'
```

When I run `glooctl proxy dump` I see:

```
"filters": [
          {
           "name": "envoy.http_connection_manager",
           "config": {
            "upgrade_configs": [
             {
              "upgrade_type": "websocket"
             },
             {
              "upgrade_type": "websocket"
             },
             {
              "upgrade_type": "websocket"
             }
            ],
```

**Comment by GrahamGoudeau** [comment]
Note that #1784 was included in 1.2.10. That may be the cause

```
git describe --tags --contains 4c84085db7c4bd6bc47eef8054731f5be09a9a72
v1.2.10~1
```

**Comment by yuval-k** [comment]
hi @derrickburns i'm trying to reproduce this locally; do you have any upgrade configs specified in your configuration?

**Comment by derrickburns** [comment]
I don't know what an upgrade config is.  Here are the values I passed in:


[gloo-values.yaml.txt](https://github.com/solo-io/gloo/files/3974940/gloo-values.yaml.txt)

**Comment by joekelley** [comment]
I reproduced the issue locally using the provided values. Updating the pod template under `gatewayProxy` to match 
```
        image:
          repository: gloo-ee-envoy-wrapper
          tag: 1.0.0-rc7
```
should do the trick.

**Comment by marcogschmidt** [comment]
We were not able to reproduce, but added some logic to protect against this with #1990

**Comment by derrickburns** [comment]
I am hitting this line:

https://github.com/solo-io/gloo/blob/26e6708280bf0638cd96fcd76c5807e80a82695c/projects/gloo/pkg/plugins/hcm/plugin.go#L121

I turned on validation after having it off.

**Comment by kdorosh** [comment]
[This PR](https://github.com/solo-io/gloo/pull/2507) fixes the problem reported here, which we were finally able to reproduce [here](https://github.com/solo-io/gloo/issues/2500#issuecomment-591107057)

**Comment by derrickburns** [comment]
Yay!
