### ISSUE TITLE
petstore YAML k8s annotation service spelling

### ISSUE THREAD

**Issue by DaleBingham** [solo-io/gloo#199]
When I followed 
```
kubectl apply \
-f https://raw.githubusercontent.com/solo-io/gloo/master/example/petstore/petstore.yaml 
```
it created the petstore setup in default. As I was investigating the YAML it had "sevice": "petstore" and it did not seem to matter. But I am guessing should be "service". Very small, minute thing. LOVE this tool. Learning it today.
---------------------------
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"sevice":"petstore"},"name":"petstore","namespace":"default"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"app":"petstore"}}}

**Comment by rickducott** [comment]
Oops, thanks for noticing! I pushed a fix just now #200, cheers @DaleBingham.
