### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#2005]
Currently Gloo does not have any performance (internal or external). This issue is starting the conversation around creating internal performance testing as part of our CI process, and external facing performance testing.

**Comment by rickducott** [comment]
Not clear what the action is here - going to close out in favor of more concrete issues. 

FWIW, we do have some CI-based benchmarks - notably in extauth to prevent perf regressions. 

We also do significant perf testing with customers, though those numbers are highly dependent on the environment and the routing features used, so we don't publish them as general benchmarks.
