### ISSUE TITLE
missing authconfig doesn't invalidate virtual service or proxy

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2017]
**Describe the bug**
Combination of missing authconfig, virtualservice config changes, and extauth pod restarts can cause `"error":"empty config set"`

**To Reproduce**

Please see comments for an easier way to reproduce. What's described below is how error was initially recreated. 

1.Deploy the RequiredHeader example extauth plugin with corresponding authconfig and petstore virtualservice (see below for config). 
2. Test to make sure it all works as expected
3. Delete the plugin-auth authconfig
4. Remove the virtualHostPlugins from the virtualservice and save
5. Add the virtualHostPlugins back to the virtualservice and save
6. Delete the extauth pod to force a restart. When the extauth pod is ready" ...
7. test petstore and you will see:
`{"level":"error","ts":1576807162.6038246,"logger":"ext-auth-service","caller":"service/extauth.go:58","msg":"Error while authorizing request","request":"attributes:<source:<address:<socket_address:<address:\"172.17.0.1\" port_value:54028 > > > destination:<address:<socket_address:<address:\"172.17.0.9\" port_value:8080 > > > request:<http:<id:\"8616695279338737374\" method:\"GET\" headers:<key:\":authority\" value:\"192.168.99.100:30476\" > headers:<key:\":method\" value:\"GET\" > headers:<key:\":path\" value:\"/api/pets\" > headers:<key:\"accept\" value:\"*/*\" > headers:<key:\"my-header\" value:\"blah\" > headers:<key:\"user-agent\" value:\"curl/7.64.1\" > headers:<key:\"x-forwarded-proto\" value:\"http\" > headers:<key:\"x-request-id\" value:\"3f93af59-2bdb-49d5-8677-ccdb8d2beda9\" > path:\"/api/pets\" host:\"192.168.99.100:30476\" protocol:\"HTTP/1.1\" > > context_extensions:<key:\"config_id\" value:\"gloo-system.plugin-auth\" > context_extensions:<key:\"source_name\" value:\"gloo-system.gateway-proxy-v2-listener-::-8080-gloo-system_default\" > context_extensions:<key:\"source_type\" value:\"virtual_host\" > 11:\"\" > ","error":"empty config set","stacktrace":"github.com/solo-io/ext-auth-service/pkg/service.(*Server).Check\n\t/go/src/github.com/solo-io/ext-auth-service/pkg/service/extauth.go:58\ngithub.com/envoyproxy/go-control-plane/envoy/service/auth/v2._Authorization_Check_Handler\n\t/go/src/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2/external_auth.pb.go:470\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/src/google.golang.org/grpc/server.go:1011\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/src/google.golang.org/grpc/server.go:1249\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/go/src/google.golang.org/grpc/server.go:680"}`

**Expected behavior**
Better description of error and/or better validation to catch missing authconfig. 

**Additional context**
ext-auth-service looks for the config id and when it's not found it defaults back to the EmptyConfig which results in the error above as the Empty plugin functions are not configured.

**Comment by bdecoste** [comment]
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  generation: 1
  name: plugin-auth
  namespace: gloo-system
spec:
  configs:
  ```
- pluginAuth:
      config:
        AllowedValues:
        - foo
        - bar
        RequiredHeader: my-header
      exportedSymbolName: Plugin
      name: RequiredHeader
      pluginFileName: RequiredHeader.so
```

**Comment by bdecoste** [comment]
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  creationTimestamp: "2019-12-19T17:20:03Z"
  generation: 9
  name: default
  namespace: gloo-system
  resourceVersion: "47611"
  selfLink: /apis/gateway.solo.io/v1/namespaces/gloo-system/virtualservices/default
  uid: 19239caf-9847-4656-8905-2b4d4e4a250b
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
    virtualHostPlugins:
      extauth:
        configRef:
          name: plugin-auth
          namespace: gloo-system
status:
  reported_by: gateway
  state: 1
  subresource_statuses:
    '*v1.Proxy.gloo-system.gateway-proxy-v2':
      reported_by: gloo
      state: 1
```

**Comment by bdecoste** [comment]
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2019-12-19T15:27:40Z"
  generation: 5
  labels:
    app: gloo
    gloo: extauth
    installationId: uZ70UFARCbDs68Lz1R36
  name: extauth
  namespace: gloo-system
  resourceVersion: "47820"
  selfLink: /apis/extensions/v1beta1/namespaces/gloo-system/deployments/extauth
  uid: 64765e1d-c561-40be-bf7e-251b9f831bd1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      gloo: extauth
      installationId: uZ70UFARCbDs68Lz1R36
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        gloo: extauth
        installationId: uZ70UFARCbDs68Lz1R36
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  gloo: gateway-proxy
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SERVICE_NAME
          value: ext-auth
        - name: GLOO_ADDRESS
          value: gloo:9977
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: signing-key
              name: extauth-signing-key
        - name: SERVER_PORT
          value: "8083"
        - name: USER_ID_HEADER
          value: x-user-id
        - name: START_STATS_SERVER
          value: "true"
        image: quay.io/solo-io/extauth-ee:1.0.0-rc2
        imagePullPolicy: IfNotPresent
        name: extauth
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /auth-plugins
          name: auth-plugins
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: solo-io-readerbot-pull-secret
      initContainers:
      - image: quay.io/solo-io/ext-auth-plugins:1.0.0-rc2
        imagePullPolicy: IfNotPresent
        name: plugin-my-plugin
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /auth-plugins
          name: auth-plugins
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: auth-plugins
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-19T15:27:40Z"
    lastUpdateTime: "2019-12-19T20:14:51Z"
    message: ReplicaSet "extauth-5746447c8c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-12-20T01:58:12Z"
    lastUpdateTime: "2019-12-20T01:58:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by bdecoste** [comment]
To reproduce simply:
1) Update the extauth deployment above (add volumeMounts to container and add initContainer)
2) Update the virtual service as above (add virtualHostPlugins)
3) DO NOT create the authconfig
4) Hit the service and you will see the following in the extauth logs:
`{"level":"error","ts":1576847444.4787655,"logger":"ext-auth-service","caller":"service/extauth.go:58","msg":"Error while authorizing request","request":"attributes:<source:<address:<socket_address:<address:\"172.17.0.1\" port_value:56958 > > > destination:<address:<socket_address:<address:\"172.17.0.9\" port_value:8080 > > > request:<http:<id:\"7933124618424493585\" method:\"GET\" headers:<key:\":authority\" value:\"192.168.99.100:30476\" > headers:<key:\":method\" value:\"GET\" > headers:<key:\":path\" value:\"/api/pets\" > headers:<key:\"accept\" value:\"*/*\" > headers:<key:\"my-header\" value:\"blah\" > headers:<key:\"user-agent\" value:\"curl/7.64.1\" > headers:<key:\"x-forwarded-proto\" value:\"http\" > headers:<key:\"x-request-id\" value:\"bc820803-ec13-4680-9d19-152ab8a0a691\" > path:\"/api/pets\" host:\"192.168.99.100:30476\" protocol:\"HTTP/1.1\" > > context_extensions:<key:\"config_id\" value:\"gloo-system.plugin-auth\" > context_extensions:<key:\"source_name\" value:\"gloo-system.gateway-proxy-v2-listener-::-8080-gloo-system_default\" > context_extensions:<key:\"source_type\" value:\"virtual_host\" > 11:\"\" > ","error":"empty config set","stacktrace":"github.com/solo-io/ext-auth-service/pkg/service.(*Server).Check\n\t/go/src/github.com/solo-io/ext-auth-service/pkg/service/extauth.go:58\ngithub.com/envoyproxy/go-control-plane/envoy/service/auth/v2._Authorization_Check_Handler\n\t/go/src/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2/external_auth.pb.go:470\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/src/google.golang.org/grpc/server.go:1011\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/src/google.golang.org/grpc/server.go:1249\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/go/src/google.golang.org/grpc/server.go:680"}`

**Comment by bdecoste** [comment]
Creating the authconfig fixes the problem

**Comment by bdecoste** [comment]
You get this error from the gloo pod when the authconfig is missing:

`{"level":"error","ts":1576847685.316172,"logger":"gloo-ee.v1.event_loop.setup","caller":"syncer/setup_syncer.go:554","msg":"gloo main event loop","error":"event_loop.gloo: 1 error occurred:\n\t* could not find auth config [gloo-system.plugin-auth] in snapshot\n\n","errorVerbose":"event_loop.gloo:\n    github.com/solo-io/solo-projects/vendor/github.com/solo-io/go-utils/errors.Wrapf\n        /workspace/gopath/src/github.com/solo-io/solo-projects/vendor/github.com/solo-io/go-utils/errors/utils.go:12\n  - 1 error occurred:\n\t* could not find auth config [gloo-system.plugin-auth] in snapshot\n\n","stacktrace":"github.com/solo-io/solo-projects/vendor/github.com/solo-io/gloo/projects/gloo/pkg/syncer.RunGlooWithExtensions.func7\n\t/workspace/gopath/src/github.com/solo-io/solo-projects/vendor/github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup_syncer.go:554"}`

**Comment by rickducott** [comment]
Would expect a status indicating an invalid ref, like with upstreams. Would also expect #2036
