### ISSUE TITLE
tls_context is deprecated, Gloo should move to transport_socket for upstream SSL

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2037]
as per envoy latest docs, `tls_context` is deprecated in the Envoy API. Gloo currently uses this field for outbound (upstream) ssl connections in Envoy

we should move to transport_socket when timing is appropriate

**Comment by EItanya** [comment]
As it says in the `tls_context` [section](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#cluster). "This field is deprecated. Use transport_socket with name tls instead. If both are set, transport_socket takes priority." Potentially we can keep our API the same, but convert `tls_context` to `transport_socket` in Gloo.

**Comment by yuval-k** [comment]
this is really verbose, as this happens on every CDS update.
