### ISSUE TITLE
support manual TLS configuration in Knative

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2048]
the current proposal is to do this via annotations.

currently Knative provides no way for users to configure TLS directly for their service, other than by using a feature called "Automatic TLS" which leverages cert manager.

Istio users are able to "manually" set TLS by configuring their  Istio `Gateway` CRDs. Gloo does not provide an equivalent. 

As Knative does not currently have any immediate plans to implement support for setting TLS manually, we should provide support (as it has been requested by users).

I propose that we do this by allowing users to set some custom annotations on their kservice:

```
gloo.networking.knative.dev/ssl.sni_domains = <comma separated list of sni domains>
gloo.networking.knative.dev/ssl.secret_name = <name of secret containing tls certs>
gloo.networking.knative.dev/ssl.secret_namespace = <namespace of secret containing tls certs>
``` 

I've confirmed with @tcnghia that Annotations will be propagated from user config objects (Knative-Services) to the internal API object Gloo processes (Knative Ingress)

**Comment by StarpTech** [comment]
The current implementation doesn't work anymore with latest gloo and knative.
