### ISSUE TITLE
creating glooctl upstream gives "Error: unknown flag: --kube-service

### ISSUE THREAD

**Issue by DaleBingham** [solo-io/gloo#205]
I have a service in the namespace datasvc-contacts and ran the below command which I think is correct. It is giving me an error saying --kube-service is not a valid flag?

```
glooctl create upstream kube -n gloo-datasvc-contacts \
  --kube-service datasvc-contacts-svc \
  --kube-service-namespace datasvc-contacts \
  --kube-service-port 8080
```
Error: unknown flag: --kube-service
Usage:
  glooctl create upstream kube [flags]

Flags:
  -h, --help                            help for kube
      --kube-service string             name of the kubernetes service
      --kube-service-labels strings     labels to use for customized selection of pods for this upstream. can be used to select subsets of pods for a service e.g. for blue-green deployment
      --kube-service-namespace string   namespace where the kubernetes service lives (default "defaukt")
      --kube-service-port uint32        the port were the service is listening. for services listenin on multiple ports, create an upstream for each port. (default 80)
      --service-spec-type string        if set, Gloo supports additional routing features to upstreams with a service spec. The service spec defines a set of features

Global Flags:
  -i, --interactive        use interactive mode
      --name string        name of the resource to read or write
  -n, --namespace string   namespace for reading or writing resources (default "gloo-system")
  -o, --output string      output format: (yaml, json, table)

glooctl version 0.5.0
Running on a MAC OS X with latest OS update, dark mode enabled if it matters
Latest generation 15" macbook

**Comment by ilackarms** [comment]
thanks for pointing this out! we have the fix on #207, once that's merged we can publish a new release of `glooctl`

**Comment by ilackarms** [comment]
@DaleBingham this should be fixed in the new release: https://github.com/solo-io/gloo/releases/tag/0.5.1

**Comment by DaleBingham** [comment]
@ilackarms does this mean I need to remove and then reinstall gloo with the below or is there a better way for my MAC? 
```
curl -sL https://run.solo.io/gloo/install | sh
```

**Comment by ilackarms** [comment]
the latest `curl -sL https://run.solo.io/gloo/install | sh` should get you glooctl v `0.5.1` which contains the fix

you can always go to the Releases page to download manually, but `curl | sh` defaults to the latest release

**Comment by DaleBingham** [comment]
I got the right version now thanks. 

Dale Bingham
