### ISSUE TITLE
Webhook issues; Helm changes needed

### ISSUE THREAD

**Issue by DerrickMartinez** [solo-io/gloo#2053]
Hi, I'm running multiple gloo namespaces -- one for internal and external. Ran into an issue this week with the webhook firing on the wrong namespaces and locking resources. This would cause status to get stuck in Pending etc.  For me, the fix was to add the following to the webhook manifest:

```
  namespaceSelector:
    matchLabels:
      gloo: {{ .Release.Namespace }}
```

This would watch all namespaces with the label of `gloo: gloo-internal` for example. One limitation this has is that you couldn't share CRDs between two gloo gateways. i.e. `gloo-internal` and `gloo-external`.  However, in k8s 1.17, there is a `v1` ValidatingWebhookConfiguration and this has `ObjectSelector` so you could select by object in the same shared namespace.

**Comment by kdorosh** [comment]
@DerrickMartinez was this user error? is there something Gloo could have done to make this less confusing or more convenient?

**Comment by DerrickMartinez** [comment]
Updated first post
