### ISSUE TITLE
glooctl fails to install knative due to timeout

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2055]
running `glooctl install knative` on a fresh cluster without cached images can error with a timeout:

```

Error: timed out waiting for knative apiservice to be ready

```

we either need to relax this timeout or remove the constraint, as knative pods do eventually come up (sometimes an image pull can cause this)

**Comment by kdorosh** [comment]
we can't remove the timeout or else helm 3 will error (glooctl install delegates to helm install libraries), as it tries to hit all k8s apiservices before attempting an installation.

is this something you can easily reproduce, and confirm that a longer timeout would resolve? I thought 20 seconds would be more than sufficient; would love to confirm that the timeout wouldn't hang indefinitely.
