### ISSUE TITLE
"version":"VERSION" printed on every log line

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2056]
it should be enough to print at boot time. otherwise it clutters logs for no reason (that is clear to me)

**Comment by kdorosh** [comment]
@ashleywang1 @marcogschmidt @GrahamGoudeau 

https://github.com/solo-io/gloo/issues/1745

reopening the conversation here.

**Comment by rickducott** [comment]
I disagree - typically the workflow for log investigation involves drilling down on specific lines (i.e. grep for error) not reading the entire log. This is particularly important for when users / customers are reporting back specific log messages, avoiding a round trip / cross-reference.
