### ISSUE TITLE
provide a way to enable debug logging at BOOT TIME

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2058]
currently the only way to provide debug logs on gloo/controllers is to enable stats server, port-forward, open the UI on 9091, and manually click a button to enable debug logs.

using this is very unwieldy, and it's not possible to get debug logs on boot (which are important if debugging a boot issue).

we should provide a simple `LOG_LEVEL` env var that sets the `contextutils` loglevel

**Comment by EItanya** [comment]
Should we also provide an endpoint similar to envoy?

**Comment by rickducott** [comment]
Using this issue to track log improvements: https://github.com/solo-io/gloo/issues/945
