### ISSUE TITLE
allow configuring swagger FDS to search custom paths

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2059]
currently, the http URIs that swagger fds searches for swagger documents are hard-coded: https://github.com/solo-io/gloo/blob/master/projects/discovery/pkg/fds/discoveries/swagger/swagger.go#L27
 
we should provide an option (in `settings`) that allows users to configure custom paths.

user request / slack thread: https://solo-io.slack.com/archives/C9L6VPAUW/p1577530943183300

**Comment by RichiCoder1** [comment]
I'd like this, if only to get away from the swagger naming and follow the [recommend naming](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#document-structure) (though that's subject to change afaik)

**Comment by rickducott** [comment]
This can be configured manually for a particular upstream by setting `swaggerInfo.Url` to the url of your service: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/options/rest/rest.proto#L18

**Comment by christian-posta** [comment]
I can confirm this works. Will doc it and add a link and close this.

**Comment by christian-posta** [comment]
https://github.com/solo-io/gloo/pull/2690
