### ISSUE TITLE
[docs] getting started - glooctl namespace

### ISSUE THREAD

**Issue by brandonkal** [solo-io/gloo#2060]
The flow between the [install page](https://docs.solo.io/gloo/latest/installation/gateway/kubernetes) and the [first linked routing tutorial](https://docs.solo.io/gloo/latest/gloo_routing/hello_world/) is broken.

1. The helm install section suggests using a custom namespace. The docs in this section should note `gloo-system` is preferred.
2. glooctl expects gloo-system namespace so the glooctl get upstreams returns nothing while following the tutorial.
3. `glooctl --help` doesn't appear to have a flag for using a custom namespace.

So I am not sure where to go from here.

**Comment by ilackarms** [comment]
@brandonkal most relevant `glooctl` commands support a `--namespace` flag (for example, `glooctl get upstreams -n my-namespace`

you are correct that we should note the discrepancy between the helm install instruction and `glooctl` default namespace
