### ISSUE TITLE
improve YAML-writing experience

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2061]
numerous issues have come up in community slack and elsewhere that result from the fact that writing large, nested YAML stanzas is hard and error-prone.

`glooctl` was originally designed to simplify the (safe) writing of our YAML resources, but it has not kept pace with the growth of the Gloo API. it is also not suitable for producing more complex configurations (where the likelihood of invalid syntax is increased).

i see a variety options for reducing this pain:

- improve existing glooctl commands to cover a larger (100%?) surface of Gloo's API
- add a new glooctl command to assist writing YAML based on our Protos (rather than explicitly supporting each API field / option)

**Comment by EItanya** [comment]
We do something hybrid with extauth where we open up an editor for specific stanzas of yaml, would that apply here?
