### ISSUE TITLE
SNI-routing without TLS termination: Make secretRef optional in sslConfig

### ISSUE THREAD

**Issue by brandonkal** [solo-io/gloo#2069]
I would like to route some domains without termination and terminate others as normal on the same IP. Because Envoy can do this--[see closed envoy issue](https://github.com/envoyproxy/envoy/issues/1843)--Gloo should be able to do this as well.

Based on the [Slack discussion](https://solo-io.slack.com/archives/C9L6VPAUW/p1577693968186300), it appears that allowing `secretRef` to be nil should work. That approach is quite intuitive--leave out the secret and gloo's Envoy proxy will not perform TLS termination and instead route based on the tls ClientHello.
According to the envoy issue, leaving out tls_context in Envoy config should enable this to function.

**Comment by EItanya** [comment]
This was taken care of during the failover feature work
