### ISSUE TITLE
gateway should retry its connection to gloo validation if conn closes

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2070]
currently, gateway subscribes to gloo's notification API in its setup loop and then reads from that connction forever:

https://github.com/solo-io/gloo/blob/a3f96411d3929049b98dabf4bf4f19b9177f6698/projects/gateway/pkg/validation/notification_channel.go#L11

if the transport closes for any reason, the stream needs to be retried. currently the user will see the following error:

```
{"level":"error","ts":1577745116.9219065,"logger":"gateway.v1.event_loop.gateway.validation-resync-notifications","caller":"validation/notification_channel.go:33","msg":"error reading from stream","version":"1.2.12","error":"rpc error: code = Unavailable desc = transport is closing","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/validation.MakeNotificationChannel.func1\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gateway/pkg/validation/notification_channel.go:33"}

```

repeated in the gateway logs, and gateway will no longer be receiving nofications from gloo

**Comment by DerrickMartinez** [comment]
Any progress on this one? It is absolutely killing our centralized logging.
