### ISSUE TITLE
Several references to "matcher" instead of "matchers" in doc

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2078]
https://docs.solo.io/gloo/latest/gloo_routing/virtual_services/https_redirect/
https://docs.solo.io/gloo/latest/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk/

**Comment by bdecoste** [comment]
Error from server: error when creating "STDIN": admission webhook "gateway.gloo-system.svc" denied the request: could not unmarshal raw object: parsing resource from crd spec default in namespace gloo-system into *v1.VirtualService: unknown field "matcher" in v1.Route

**Comment by bdecoste** [comment]
https://docs.solo.io/gloo/0-20/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/grpc_to_rest/

**Comment by ned1313** [comment]
Issue resolved by PR #2211

**Comment by ned1313** [comment]
Found a few spots where it's still lurking. Will address with a new PR.

**Comment by ned1313** [comment]
Resolved by PR #2307
