### ISSUE TITLE
Write glossary for docs site

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#2082]
See: https://www.consul.io/docs/glossary.html

**Comment by rickducott** [comment]
I think this is a good idea, but not clearly a priority given all the existing content. I think we're already tracking docs reorganization, revamping the intro sections, and other cleanup of the docs across a bunch of issues. Going to close this one out.

**Comment by rickducott** [comment]
For instance, this is a decent glossary: https://docs.solo.io/gloo/latest/introduction/concepts/
