### ISSUE TITLE
docs: Gloo debugging cheatsheet

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2086]
we should provide a doc with a cheat sheet of common / useful approaches to debugging gloo (as well as some useful commands, etc.)

reference where i provided some of this info on slack:
https://solo-io.slack.com/archives/C9L6VPAUW/p1578003361290800?thread_ts=1577981721.286300&cid=C9L6VPAUW

**Comment by rickducott** [comment]
https://docs.solo.io/gloo/latest/operations/debugging_gloo/
