### ISSUE TITLE
Improve OS -> OS upgrade path docs

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2090]
We have some upgrade docs here: https://docs.solo.io/gloo/latest/upgrading/

We should improve these docs by more thoroughly demonstrating how it will work, and prove that there is no downtime (e.g., by using `hey` to send traffic and ensure there are no 503s)

**Comment by kdorosh** [comment]
Additional upgrade tasks (we should do `resolvesIssue: false` until this story is complete):
- [ ] add regression test to ensure `helm upgrade` to the same version works
- [ ] add regression test to ensure `helm upgrade` from OS 1.2.x to 1.3.x works
- [ ] properly document workflows for OS -> Gloo Enterprise upgrade (`helm upgrade` won't work here as they are separate helm charts)
    - [ ] Make sure these documented workflows work for OS 1.2.x to 1.2.x GlooE upgrade
    - [ ] Make sure these documented workflows work for OS 1.2.x to 1.3.x GlooE upgrade
- [ ] test our documented upgrade workflows, including blue/green deployment, and ensure they are zero-downtime

**Comment by arianaw66** [comment]
Assigning myself just the regression tests for now

**Comment by yuval-k** [comment]
one thing to consider, we should probably instruct enabling readiness probes as part of the guide.

**Comment by yuval-k** [comment]
we'll need to see how do handle termination gracefully. this generaly means failing health checks and draining connections from the envoy that is being removed.

**Comment by rickducott** [comment]
> * [ ]  properly document workflows for OS -> Gloo Enterprise upgrade (`helm upgrade` won't work here as they are separate helm charts)
>   
>   * [ ]  Make sure these documented workflows work for OS 1.2.x to 1.2.x GlooE upgrade
>   * [ ]  Make sure these documented workflows work for OS 1.2.x to 1.3.x GlooE upgrade

These are outside the scope of this issue. Here's an issue to track OS -> Enterprise: https://github.com/solo-io/gloo/issues/1958. AFAICT, there isn't a great approach for OS -> Enterprise, so I explicitly wanted it tracked separately so we can prioritize separately

**Comment by arianaw66** [comment]
Cannot upgrade smoothly from v1.2.x to v1.3.x because the Gateways are helm hooks in 1.2.x and regular resources in 1.3.x. We need to spend more time figuring out how to handle this.

**Comment by kdorosh** [comment]
Everything but the regression tests in enterprise has already been addressed. Tracking regression test work here: https://github.com/solo-io/gloo/issues/2705
