### ISSUE TITLE
Investigate support for `helm upgrade` in Gloo

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2092]
A lot of users don't like our currently recommended upgrade path using a blue/green deployment, with multiple simultaneous installations.

Instead, it would be nice if we could support a natural `helm upgrade` path.

This ticket needs planning, as this may or may not be feasible. Particularly if we want to support both helm 2 and helm 3.

**Comment by kdorosh** [comment]
If we can, would love to leverage OS -> Enterprise via `helm upgrade` as part of this ticket

**Comment by rickducott** [comment]
Closing because we've been tackling this with other issues and have an upgrade guide for 1.3.0
