### ISSUE TITLE
Docs for AWS Load Balancer setup

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2102]
We can borrow heavily from the ambassador example: https://www.getambassador.io/reference/ambassador-with-aws/#l4-load-balancer

Should address:
- Users running into problems with proxy protocol, certs, etc. 
- Health checks on node port meaningless because it gets load balanced to a random pod
- Daemonset and host port are useful for health checking the node
- Readiness probes turned off by default because they give a bad UX
- Integrate into glooctl

**Comment by scranton** [comment]
Updated documentation on using AWS CLB and NLB with Gloo https://github.com/solo-io/gloo/pull/2150
