### ISSUE TITLE
Allow Gloo to update boostrap config without downtime

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2112]
Some of our bootstrap config cannot be pre-configured, and can only be configured after installation.

To debug some issues, this is too late.

@ilackarms can provide more detail.

**Comment by ilackarms** [comment]
this requires the addition of an agent to our envoy container with which to perform hot restarts.

implementation-wise, we should make this agent thin/transparent so it can be optional in a gloo deployment setup. 

the agent should watch the bootstrap configmap and hot restart envoy when it is changed
