### ISSUE TITLE
Improve UX for non-k8s installations

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2113]
Provide reference architectures, scripts, installs, and demos for non-k8s setups (e.g., Nomad/Consul)

Prefer building into glooctl into one-liners over docs.

Building into DNS / other infrastructure would be helpful here.

**Comment by rickducott** [comment]
Going to close this as we have a number of other issues tracking non-k8s use of gloo (consul, nomad, etc). 

#2335 
#2404 
#2024 
etc

**Comment by rickducott** [comment]
I understand this issue is also tracking automation for those things as part of glooctl -- but higher priority is fixing the bugs and docs. We can reopen if we intend to invest here.
