### ISSUE TITLE
Allow log level to be set before startup

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2115]
Allow log level to be set before startup.

Also make it easier to change (without the port forward & curl/UI click).

Update the `glooctl` command to allow setting the log level, rather than just forcing users onto debug when you call `glooctl proxy logs`

**Comment by rickducott** [comment]
Closing as a dupe of https://github.com/solo-io/gloo/issues/945 (tracking all the logging improvements on a single issue)
