### ISSUE TITLE
Update developer setup guide now that we are on go modules

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2125]
We should remove all our references to `dep` in our developer setup guide: https://docs.solo.io/gloo/latest/dev/setting-up-dev-environment/

**Comment by kdelorey** [comment]
I just came across this when I tried to `dep ensure` while going through the docs.

**Comment by kdorosh** [comment]
We are planning an override of these docs once our docker container to build Gloo has been finished, which should drastically ease development workflow.

The PR for the dev docker container is here: https://github.com/solo-io/gloo/pull/2389

cc @EItanya
