### ISSUE TITLE
gateway pod w/gloo-os-with-ui install fails with missing validation config 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2127]
"error in setup: VALIDATION_MUST_START was set to true, but no validation configuration was provided in the settings. Ensure the v1.Settings {default gloo-system} contains the spec.gateway.validation config

**Comment by bdecoste** [comment]
global:
  # create rbac rules for the gloo-system service account
  glooRbac:
    create: true
settings:
  # namespace where intermediary CRDs will be written to, e.g. Upstreams written by Gloo Discovery.
  writeNamespace: gloo-system
  # whitelist of namespaces for gloo to watch for services and CRDs. leave empty to only watch gateway namespace
  watchNamespaces:
  - foo
  - gloo-system
gateway:
  # if true, read Gateway CRDs from all watched namespaces rather than just the namespace of the Gateway controller
  readGatewaysFromAllNamespaces: true
  validation:
    alwaysAcceptResources: true
    enabled: true
    failurePolicy: Ignore
    secretName: gateway-validation-certs
gloo:
  namespace:
    # create the installation namespace
    create: false
  crds:
    # create CRDs for Gloo (turn off if installing with Helm to a cluster that already has Gloo CRDs)
    create: true
  gateway:
    # if true, read Gateway CRDs from all watched namespaces rather than just the namespace of the Gateway controller
    readGatewaysFromAllNamespaces: true
    validation:
      alwaysAcceptResources: true
      enabled: true
      failurePolicy: Ignore
      secretName: gateway-validation-certs
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        customHttpsGateway:
          virtualServiceSelector:
            gloo-setup: "true"
          virtualServiceNamespaces:
            - helix
            - gloo-system
          options:
            healthCheck:
              path: /envoy/healthz
      readConfig: false
      podTemplate:
        # label selector for nodes
        nodeSelector:
          kops.k8s.io/instancegroup: ingress
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "ingress"
            effect: "NoSchedule"
        httpPort: 9080
        httpsPort: 9443
        image: {}
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
      kind:
        deployment: null
        daemonSet:
          # whether or not to enable host networking on the gateway-proxy pod. Only relevant when running as a DaemonSet
          hostPort: true
      service:
        # gateway service type. default is LoadBalancer
        type: ClusterIP
        # static cluster IP (or None) when service type is ClusterIP
        clusterIP: None
  discovery:
    fdsMode: "WHITELIST"

**Comment by bdecoste** [comment]
Bill DeCoste 8:44 AM
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
 creationTimestamp: "2020-01-06T16:36:43Z"
 generation: 1
 name: default
 namespace: gloo-system
 resourceVersion: "6576"
 selfLink: /apis/gloo.solo.io/v1/namespaces/gloo-system/settings/default
 uid: 30d31749-fa40-4df4-947a-adf6407f9927
spec:
 devMode: true
 discoveryNamespace: gloo-system
 gloo:
  xdsBindAddr: 0.0.0.0:9977
 kubernetesArtifactSource: {}
 kubernetesConfigSource: {}
 kubernetesSecretSource: {}
 refreshRate: 60s
status: {}

**Comment by ichtestemalwieder** [comment]
I have the same problem. Does anyone know a workaround?

How can the: `v1.Settings {default gloo-system} contains the spec.gateway.validation config` , as  stated in the error message, be set? Thanks.

**Comment by RichiCoder1** [comment]
Also ran into this issue. Was able to get past it by disabling validation `gloo.gateway.validation.enabled: false`, but that's not a healthy work around.

**Comment by yokiworks** [comment]
seeing this as well

**Comment by WonderPanda** [comment]
I'm also seeing this after doing an installation:
`glooctl install gateway --with-admin-console`

**Comment by sundarseswaran** [comment]
Providing a validation configuration like below helps resolve this issue. 
`gateway.validation.alwaysAccept: false`
This will ensure gloo accepts only valid settings.
