### ISSUE TITLE
Ability to sign up for notifications of enterprise releases

### ISSUE THREAD

**Issue by keiransteele** [solo-io/gloo#2131]
It would be great to have some way of being notified when new enterprise versions are released. A release mailing list and/or a "#gloo-releases" channel in Slack.

**Comment by rickducott** [comment]
Now that we've shifted over to the 3-month cadence with a new stable release coming out next week, I think we can do something here.

**Comment by rickducott** [comment]
@bettyjunod emails customers about new stable releases, and we're also sharing them in the slack channels and blog. With patch releases, we're now listing them all in the changelog in the docs, and we're proactive about messaging when there is a critical fix. When there are minor fixes, we haven't been broadcasting those updates. I think this is a pretty good place for now, going to close the issue.
