### ISSUE TITLE
running gloo with istio

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#214]
this issue should track progress on deploying Gloo with istio sidecars. the existing Gloo deployment has been tested to work with istio `1.0.3` without any additional configuration.

gloo performs the following network functions:
- function discovery polls services for grpc reflection and openapi docs
- envoy proxies services 
- gloo (the control plane itself) listens for grpc and serves envoys who connect

**Comment by ilackarms** [comment]
to run gloo with istio: 
`kubectl apply -f <(istioctl kube-inject -f install/kube.yaml)`

**Comment by rickducott** [comment]
Doesn't look like there's any work to do here, closing out.
