### ISSUE TITLE
Move docs videos from Gloo repo to s3 bucket

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2149]
cc @bdecoste @mitchdraft 

There are still a handful of videos in our docs we could move to s3 to make our repo smaller (and thus quicker to clone in CI)

![image](https://user-images.githubusercontent.com/11008283/72018578-f8f9d700-3235-11ea-8f93-924ea9e0c452.png)

**Comment by mitchdraft** [comment]
this is in progress in https://github.com/solo-io/gloo/pull/2148

**Comment by bdecoste** [comment]
I think this has already been completed in #2148 and can be closed
