### ISSUE TITLE
breaking changes missing for settings ratelimit changes

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2151]
For older settings: spec.extensions.configs.envoy-rate-limit or spec.envoy-rate-limit

For 1.2.x settings: spec.ratelimit

**Comment by rickducott** [comment]
Not exactly sure what needs to be fixed here, so closing. Please reopen if there are any specific docs that need to be updated given this problem. The team has been increasing the emphasis on documenting breaking changes to avoid this in the future.
