### ISSUE TITLE
gloo 1.3.1 ingress cpu high

### ISSUE THREAD

**Issue by xkcp0324** [solo-io/gloo#2153]
When I installed Gloo in my local cluster, I notice a very high CPU usage and takes huge resources without doing anything and just by installing the software using helm

values-ingress.yaml
crds:
  create: false
gateway:
  enabled: false
ingress:
  enabled: true
  requireIngressClass: true

helm install gloo gloo/gloo --namespace gloo-system -f values-ingress.yaml

My environment:
centos7
tke (k8s1.14.3)

top
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 10101     20   0  249908 124300  24548 S 200.0  0.2  10:34.04 gloo
   68 root      20   0   11828   1892   1496 S   0.0  0.0   0:00.02 bash
   87 root      20   0   58280   2012   1484 R   0.0  0.0   0:00.00 top

pprof
Fetching profile over HTTP from http://localhost:9091/debug/pprof/profile?seconds=30
Saved profile in /root/pprof/pprof.gloo.samples.cpu.001.pb.gz
File: gloo
Type: cpu
Time: Jan 9, 2020 at 11:07am (UTC)
Duration: 30.15s, Total samples = 58.49s (194.00%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 31180ms, 53.31% of 58490ms total
Dropped 405 nodes (cum <= 292.45ms)
Showing top 10 nodes out of 152
      flat  flat%   sum%        cum   cum%
   10480ms 17.92% 17.92%    10480ms 17.92%  runtime.duffcopy
    5980ms 10.22% 28.14%    14040ms 24.00%  github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*Endpoint).GetMetadata
    4110ms  7.03% 35.17%    21090ms 36.06%  github.com/solo-io/solo-kit/pkg/api/v1/reconcile.findResource
    2340ms  4.00% 39.17%     2340ms  4.00%  memeqbody
    1850ms  3.16% 42.33%     4900ms  8.38%  runtime.scanobject
    1750ms  2.99% 45.32%     1750ms  2.99%  runtime.duffzero
    1610ms  2.75% 48.08%     2040ms  3.49%  runtime.(*itabTableType).find
    1120ms  1.91% 49.99%     8950ms 15.30%  github.com/gogo/protobuf/proto.(*mergeInfo).merge
     980ms  1.68% 51.67%      980ms  1.68%  cmpbody
     960ms  1.64% 53.31%     2480ms  4.24%  github.com/solo-io/solo-kit/pkg/api/v1/resources.MetadataCompare
(pprof)

heap:
Fetching profile over HTTP from http://localhost:9091/debug/pprof/heap
Saved profile in /root/pprof/pprof.gloo.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz
File: gloo
Type: inuse_space
Time: Jan 9, 2020 at 11:09am (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 25742.96kB, 74.62% of 34499.29kB total
Showing top 10 nodes out of 184
      flat  flat%   sum%        cum   cum%
 6657.23kB 19.30% 19.30%  6657.23kB 19.30%  reflect.New
 5260.38kB 15.25% 34.54%  5260.38kB 15.25%  encoding/json.(*decodeState).literalStore
 4145.21kB 12.02% 46.56%  5765.05kB 16.71%  github.com/json-iterator/go.(*Iterator).ReadString
 2170.43kB  6.29% 52.85%  4730.80kB 13.71%  github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.filterEndpoints
 1619.83kB  4.70% 57.55%  1619.83kB  4.70%  github.com/json-iterator/go.(*Iterator).readStringSlowPath
 1536.33kB  4.45% 62.00%  1536.33kB  4.45%  github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.createEndpoint
 1536.11kB  4.45% 66.45%  2048.13kB  5.94%  github.com/solo-io/gloo/projects/gloo/pkg/translator.loadAssignmentForUpstream
 1025.12kB  2.97% 69.42%  1025.12kB  2.97%  encoding/base64.(*Encoding).DecodeString
 1024.05kB  2.97% 72.39%  1024.05kB  2.97%  fmt.Sprintf
  768.26kB  2.23% 74.62%   768.26kB  2.23%  go.uber.org/zap/zapcore.newCounters
(pprof)

**Comment by rickducott** [comment]
Hi, a number of CPU / perf fixes were released over the last few weeks. Could you please upgrade and let us know if you continue to see issues. Here are some relevant PRs:
https://github.com/solo-io/gloo/issues/2277
https://github.com/solo-io/gloo/issues/1840
https://github.com/solo-io/gloo/issues/1711
https://github.com/solo-io/gloo/issues/1581
