### ISSUE TITLE
Allow specifying the log level for the Gateway from the command line

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#2161]
right now the `glootctl` cli has a great command for viewing the logs `glooctl proxy logs` and it also sets the logging level to `debug`.... I want to be able to control the log level at which I see the logs. In other words, I'd like the `glooctl proxy logs` command to be able to take an argument which sets the log level instead of just hardcode to debug. Something like:

```glooctl proxy logs --log-level=warn```

**Comment by rickducott** [comment]
Closing in favor of #945
