### ISSUE TITLE
glooctl hangs if k8s api server is unresponsive

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#2176]
my minikube's k8s api server is down/taking a long time to respond. Something in glooctl, probably at least the version check, consequently takes a long time to print anything at all to the terminal, before dying.

**Comment by kdorosh** [comment]
We should lower the timeout and improve the error message if the k8s apiserver is down

**Comment by kdorosh** [comment]
already configurable here https://github.com/kubernetes/client-go/blob/ea0a6e11838c4413b5d51574a50da6312d572658/rest/config.go#L126
