### ISSUE TITLE
git bash on windows adds wrong route in glooctl

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2179]
slack context: https://solo-io.slack.com/archives/C9L6VPAUW/p1578950718107600

ensure that tutorials work on git bash on windows

> Trying gloo for the first time, had a fun issue in the tutorial step : glooctl add route  --path-exact /all-pets  --dest-name default-petstore-8080  --prefix-rewrite /api/pets
it was resulting in the route: C:/Program Files/Git/all-pets -> gloo-system.default-petstore-8080 (upstream)
environment is windows, running command lines via git bash.
running via CMD seems to set up the proper route /all-pets -> ...

**Comment by eshepelyuk** [comment]
I think the issue should be closed as `wont fix`
Slack context
https://solo-io.slack.com/archives/C9L6VPAUW/p1578955639112300?thread_ts=1578950718.107600&cid=C9L6VPAUW

**Comment by wtatum** [comment]
I just ran into this same issue, and was lucky enough to find this issue posted. Without the post I don't think I would have even thought to try CMD instead of git bash. Any insight you can offer on why this is `wont fix` given I can't see the Slack discussion?
