### ISSUE TITLE
Better guide for how to utilize validation

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2182]
Have you thought through what happens when you have gloo installed without validation then turn validation on?

I wonder if this is caused by that sequence:
```
{"level":"error","ts":1578960651.029402,"logger":"gateway.v1.event_loop.gateway","caller":"syncer/setup_syncer.go:268","msg":"error: event_loop: 1 error occurred:\n\t* reconciling resource gateway-proxy: invalid resource version gloo-system.gateway-proxy given , expected 36642040\n\n","version":"1.3.1","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/syncer.RunGateway.func1\n\t/workspace/gloo/projects/gateway/pkg/syncer/setup_syncer.go:268"}
```

**Comment by ilackarms** [comment]
if you enable validation, gloo and gateway should do a soft in-process restart (known as restarting their *setup loop*). it shouldn't make a difference whether gloo/gateway are launched before/after the Settings crd gets updated.

maybe you are referring to some other change related to enabling validation in the helm chart?

 i still can't see any reason it would cause the above error. is there any more context for why you think these might be related?

**Comment by derrickburns** [comment]
I have not looked at the validation code, so I am just guessing.

What I can say with certainty is that *every* time that I have enabled validation on a running system with numerous virtual services I have experience frustration with trying to identify the source of problems.

One question:  if the admission/validating webhook identifies a problem, where is the problem logged?

**Comment by derrickburns** [comment]
I guess what is missing is a tutorial on how to use the validation mechanism to detect and fix issues, not simply to block bad configuration from hitting Envoy.
