### ISSUE TITLE
delegation docs should explain `/` prefix

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2200]
when setting the `match` for a `delegateAction` delegation the user can provide a `matcher` with `prefix` which forces all the routes defined in the delegated route table to begin with the given prefix.

however, when an empty (`/`) prefix matcher means the delegated route table routes can start with any prefix. this note is missing from the delegation doc at https://docs.solo.io/gloo/latest/gloo_routing/virtual_services/delegation/

**Comment by marcogschmidt** [comment]
Will include this in my docs update for #2054
