### ISSUE TITLE
GKE glooctl 1.3.1 metrics.k8s.io/v1beta1: the server is currently unable to handle the request

### ISSUE THREAD

**Issue by den-vasyliev** [solo-io/gloo#2202]
New GKE cluster. Any version from 1.13.11-gke.14

Error: installing gloo in gateway mode: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request

all installation fail

**Comment by rickducott** [comment]
Hi @den-vasyliev are you still running into issues? Sorry for the long delay on this. It looks like a problem with your GKE api server, I have been running Gloo on GKE so am assuming this was a transient issue or maybe a problem in your environment. Please let us know if I am mistaken here.
