### ISSUE TITLE
Helm hooks cause errors when running `helm upgrade`

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2212]
We need a regression test that ensures that the `helm upgrade` command works, even if we just change helm values (e.g. "upgrade" from 1.2.15 -> 1.2.15)

Currently this doesn't work in the 1.2.15 -> 1.2.15 case, and we get:

```
helm install gloo/gloo -n gloo --namespace gloo-system --version 1.2.15 --set "crds.create=true" --set "global.glooRbac.create=true"
helm upgrade gloo gloo/gloo --force --namespace gloo-system --version 1.2.15 --set "crds.create=false" --set "global.glooRbac.create=false" --set "settings.watchNamespaces[0]=foobar" --set "settings.watchNamespaces[1]=gloo-system"
UPGRADE FAILED
ROLLING BACK
Error: validatingwebhookconfigurations.admissionregistration.k8s.io "gloo-gateway-validation-webhook-gloo-system" already exists
Error: UPGRADE FAILED: validatingwebhookconfigurations.admissionregistration.k8s.io "gloo-gateway-validation-webhook-gloo-system" already exists
```

**NOTE(by marco)**: using this issue to only track the bug itself, creating separate issue for adding tests to avoid this kind of error going forward.

**Comment by marcogschmidt** [comment]
Created a new issue to track the need to add regression test for the Helm chart: #2241
