### ISSUE TITLE
glooctl proxy url version information spit out with no way to hide

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#2218]
I've seen both in the docs (and in my scripts) using a shortcut of https://$(glooctl proxy url)/foo as a quick way to access the Gloo Gateway endpoint. 

When you have a version mismatch, it spits out the version information too. This blows up the scripts. 

I like that it warns about version mismatches, but it should do them once or at least with an option to hide that warning with --ignore-version-mismatch or something.

**Comment by rickducott** [comment]
Believe this has been fixed by moving the version info to std err, and not returning it in this particular case.
