### ISSUE TITLE
glooctl uninstall --all does NOT remove CRDs

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#2219]
We've discussed this before and agreed that `glooctl uninstall --all` would remove *everything*. It currently does NOT remove CRDs.

https://github.com/solo-io/gloo/issues/433

**Comment by marcogschmidt** [comment]
@christian-posta Was unable to reproduce with both `glooctl` version `1.2.12` and `1.3.1`.

Could you provide more information, e.g. which version of `glooctl` you are using and anything else that might be useful to reproduce this?

**Comment by christian-posta** [comment]
@marcogschmidt I see what happened. I had a mismatch in server and client versions. I had server components (Gloo EE) `1.2.12` and cli of `1.3.1`

In that scenario, it didn't remove CRDs.

**Comment by marcogschmidt** [comment]
The error affects only installations of Gloo Enterprise. To reproduce, run the following commands with `glooctl` `v1.3.1`:
1. `glooctl install gateway enterprise --license-key $GLOO_LICENSE_KEY`
2. `glooctl uninstall --all`
3. `kubectl get crds`

You will see that the Gloo CRDs are still present.

I suspect the problem being that [this function](https://github.com/solo-io/gloo/blob/0300f2ade6416163f46a3da66a38f6e0ae3df9bc/projects/gloo/cli/pkg/cmd/install/uninstall.go#L71) does return an empty list when running against an enterprise chart.
