### ISSUE TITLE
alternative to extending the translator

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#223]
#220 addresses the need to add functionality to Gloo without modifying the core Gloo repo

it introduces the ability to add additional plugins to Gloo as well as provide callbacks for the Translator via `TranslatorSyncerExtension`s

just to keep track of an alternate solution, it may be prudent to add complexity to the plugins (essentially, offload the work of extending Gloo's functionality entirely to plugins). 

just something to track as we continue to build out

**Comment by ilevine** [comment]
closing as we are not working on this in the near future; Please re-open if needed or if you have a design suggestion.
