### ISSUE TITLE
Automatic glooctl homebrew-core formula update broken 

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2232]
When a release is created from the default Gloo branch (currently `master`), the build process automatically creates PRs to update `glooctl` formulas in 3 repositories:
- [x] [homebrew-core](http://github.com/Homebrew/homebrew-core)
- [x] Our own [homebrew tap](https://github.com/solo-io/homebrew-tap) -- _*this wasn't broken*_
- [x] [fish-food](https://github.com/fishworks/fish-food/pull/520) (formulas for [GoFish](https://gofi.sh/index.html)) -- _*this wasn't broken*_

Our recent switch to Go Modules caused the GitHb check for the `homebrew-core` PR to [fail](https://github.com/Homebrew/homebrew-core/pull/48599). The problem is that is still rely on `dep`. We have to fix this.

**Comment by kdorosh** [comment]
Fix for homebrew-core: https://github.com/Homebrew/homebrew-core/pull/49228

**Comment by kdorosh** [comment]
The fix for homebrew-core got merged
