### ISSUE TITLE
Provide more control on Route ordering

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2233]
We recently introduced [a feature](https://github.com/solo-io/gloo/issues/2054) to allow delegating routing decisions to multiple Route Tables (the feature replaces the deprecated _virtual service merging_ behavior). When Gloo collects the delegated routes from multiple Route Tables to create a Proxy [VirtualHost](https://docs.solo.io/gloo/latest/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk/#virtualhost), it [sorts the Routes by descending specificity](https://github.com/solo-io/gloo/blob/203314284778152ed55a0e5bd787a81b1befe9af/projects/gateway/pkg/translator/route_converter.go#L177). We do this in order to avoid short circuiting routes. 

For example, let's assume that a certain Route on a Virtual Service delegates to 2 Route Tables with the following Routes:

```
RouteTable 1 routes:
- prefix: `foo`

RouteTable 2 routes:
- prefix: `foo/bar/baz`
- prefix: `foo/bar`
```

We want to avoid creating a Virtual Host where the routes are:

```
VirtualHost routes:
- prefix: `foo`
- prefix: `foo/bar/baz`
- prefix: `foo/bar`
```

This would short-circuit the last 2 Routes.

While useful to avoid such a scenario, the sorting can mess with the user-defined ordering of routes within a Route Table.

We want to allow users to have complete control on the ordering of Routes across all of their Virtual Services. To do this, we need two changes:
1. We need a way to disable the automatic sorting behavior on specific Virtual Services. This can be achieved by adding a `preserveRouteOrder` boolean flag to the `VirtualService` object.
2. We need to allow users to define the relative priority of routes on multiple matched `RouteTables`. Without this feature, Gloo will not be able to make sensible decisions on how to compose the final route set. This can be solved by adding a `weight` to the `RouteTable` resource: when populating the Virtual Host, Gloo will select routes from `RouteTables` (preserving their order) with the highest `weight` first.

Adtr this change, the previous example would be:

```
Parent Virtual Service:
**preserveRouteOrder: true**

RouteTable 1 routes:
**weight: 20**
- prefix: `foo`

RouteTable 2 routes:
**weight: 10**
- prefix: `foo/bar/baz`
- prefix: `foo/bar`
```

And the resulting Virtual Host:

```
VirtualHost routes:
- prefix: `foo/bar/baz`
- prefix: `foo/bar`
- prefix: `foo`
```

**Comment by ilackarms** [comment]
have we considered any alternatives to `preserveRouteOrder`? in general i think we should consider alternatives to

**Comment by marcogschmidt** [comment]
@ilackarms There have been some changes to the original proposal. In particular, we realized we do not need a `preserveRouteOrder` field. Instead, users can opt in to the new feature by just adding the `weight` on the route tables they want control over.  For more info, see the description of the [corresponding PR](https://github.com/solo-io/gloo/pull/2370).

**Comment by CamelCaseNotation** [comment]
Does the warning mentioned in the changelog prevent the envoy config from being propagated as per this documentation?

https://docs.solo.io/gloo/latest/gloo_routing/validation/#warnings-and-errors
> When a resource is in Rejected or Warning state, its configuration is not propagated to the proxy.
