### ISSUE TITLE
Gloo codegen not hermetic

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2239]
We need to update Gloo codegen to be hermetic.

Two sample PRs:
- https://github.com/solo-io/gloo/pull/2237
- https://github.com/solo-io/gloo/pull/2238

Note that in the first I was able to get a PR by CI (by the codegen step). Later the same day, without making a relevant change, codegen failed. We need to figure out what changed and pin versions appropriately.

The commits with the non-hermetic diff:
- https://github.com/solo-io/gloo/pull/2237/commits/2e60ab6984f144c64c15e4c60c2d40f77cabb3a5
- https://github.com/solo-io/gloo/pull/2238/commits/ab6748f3527afc26fa7aac18868d28877a4f6328

**Comment by ashleywang1** [comment]
This happened to me as well: https://console.cloud.google.com/cloud-build/builds/5331a12a-20f8-40aa-9432-75f07e0972dc?project=solo-public

**Comment by kdorosh** [comment]
reopening after https://github.com/solo-io/gloo/pull/2265

we need to remove the `update-deps` target
