### ISSUE TITLE
Add Helm install/upgrade/uninstall e2e tests

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2241]
We currently only have unit tests for our Helm chart. We should add end-to-end tests where - at a minimum - we install, upgrade, and install the Gloo helm chart. This will help us avoid regressions like [this one](https://github.com/solo-io/gloo/issues/2212).

These tests should be performed with both Helm 2 and Helm 3.

**Comment by jenshu** [comment]
closing this as we now have [helm e2e tests](https://github.com/solo-io/gloo/blob/dd2fb438c2efb6f56926150e212594aed6e50c68/test/kube2e/helm/helm_test.go) that do installs, upgrades, and uninstalls

there is also another [issue](https://github.com/solo-io/gloo/issues/5358) for testing different helm versions
