### ISSUE TITLE
support running multiple filter chains on the same Envoy listener

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2244]
currently, Gloo hides the Envoy Filter Chain from the user. Users configure envoy Listeners with `Gateway` crds, then Gloo internally creates the filter chain internally:  https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/translator/listener.go#L26

Gloo generates the filter chain in an opinionated way which only allows either a single set of TCP-proxy filter chains (one for each destination host), or a single set of Http Connection Manager-based filter chains (one for each ssl config)

We should consider alternative mechanisms for configuring the Envoy filter chains. A user from our slack channel requested the ability to run both a Tcp Filter chain and Http on the same Listener (port): https://solo-io.slack.com/archives/C9L6VPAUW/p1579562340051100

The resultant envoy config the user wished to produce looks like: https://solo-io.slack.com/files/UC0U5QM1A/FSVTK6EN8/working_envoy.json?origin_team=T4QS4CYJG&origin_channel=C9L6VPAUW

**Comment by ilackarms** [comment]
currently, the Gateway contains room for a single `http/tcpGateway` field inside of a proto oneof: https://github.com/solo-io/gloo/blob/master/projects/gateway/api/v1/gateway.proto#L55

This means each Envoy listener only gets the filter chains generated for the specific `httpGateway` or `tcpGateway` provided.

By moving these options out of the `oneof`, we could support placing both filter chains on the same Listener (by supporting both http and tcp options on the same Gateway)

The benefit of this change is that it is a very small (non-breaking) transition from our current API to support the specific use case of running a TCP and HTTP filter chain on the same listener.

**Comment by CamelCaseNotation** [comment]
How can I make this proposed change, and then build an image which I can push to my docker hub and use in a deployment? Which of the 4 deployments do I need to change the image of with my changes?

Also, does this proposed change include adding the `application_protocols` field in the resulting envoy config's `filter_chain_matcher` for the listener?

**Comment by ilackarms** [comment]
@CamelCaseNotation the proposed solution requires the following changes:

- remove the `oneof` from the Gateway proto: https://github.com/solo-io/gloo/blob/master/projects/gateway/api/v1/gateway.proto#L55, allowing both Http and TCP options on the same Gateway (user-facing Listener object)
- remove the `oneof` from the Listener proto: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/proxy.proto#L70, allowing both Http and Tcp on the same Listener (on the proxy, the intermediary representation of Envoy config)
- re-generate Gloo's proto code (this is done by running `make install-deps generated-code -B`)
- modify or extend the Gateway translator to propagate the new option from the Gateway to the Listener here: https://github.com/solo-io/gloo/blob/master/projects/gateway/pkg/translator/translator.go#L63. 
    * note that this can either be done by refactoring the current translator such that the `tcpGateway` and `httpGateway` options are not treated as being exclusive of the other (cleaner, but more work) OR by adding a third "factory" interface which handles the special case of *both* the httpGateway and tcpGateway being set. 
- modify the Gloo translator to handle Tcp AND Http on the Gateway (where it currently only looks at one or the other): https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/translator/listener.go#L26
- fix compilation errors (as removing the `oneof` will cause some Go compilation issues)

**Comment by ilackarms** [comment]
as far as putting `application_protocols` on the `filter_chain_matcher`, it should be easy enough to add this to the spot where Gloo creates the filter chain matches for [http](https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/translator/listener.go#L225) and [tcp](https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/tcp/plugin.go#L186), respectively

**Comment by marcogschmidt** [comment]
Linked to the issue above. We should keep both use cases in mind when designing an API to allow multiple filter chains or the same Gateway/Listener.

**Comment by CamelCaseNotation** [comment]
> re-generate Gloo's proto code (this is done by running make install-deps generated-code -B)

I don't see the make target `install-deps` but I do see `update-deps`. However, I cannot get `generated-code -B` target to work. I always get this output near the end:

```
"Thu, 27 Feb 2020 17:59:45 PST: github.com/solo-io/gloo/generate.go:41" generate failed!: &errors.withStack{
  error: &errors.withMessage{
    cause: &errors.withStack{
      error: &errors.withMessage{
        cause: &exec.Error{
          Name: "protoc",
          Err:  &errors.errorString{
            s: "executable file not found in $PATH",
          },
        },
        msg: "[protoc -I/Users/joshh/go/src/github.com/solo-io/gloo/vendor_any --gogo_out=plugins=grpc,Mgoogle/protobuf/descriptor.proto=github.com/gogo/protobuf/protoc-gen-gogo/descriptor,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,Mgoogle/rpc/status.proto=github.com/gogo/googleapis/google/rpc,Menvoy/api/v2/discovery.proto=github.com/envoyproxy/go-control-plane/envoy/api/v2,gogoproto/gogo.proto=github.com/gogo/protobuf/gogoproto:/var/folders/dh/z54p11md5cz308z4q16ljh_80000gn/T/309352994 --ext_out=plugins=grpc,Mgoogle/protobuf/descriptor.proto=github.com/gogo/protobuf/protoc-gen-gogo/descriptor,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,Mgoogle/rpc/status.proto=github.com/gogo/googleapis/google/rpc,Menvoy/api/v2/discovery.proto=github.com/envoyproxy/go-control-plane/envoy/api/v2,gogoproto/gogo.proto=github.com/gogo/protobuf/gogoproto:/var/folders/dh/z54p11md5cz308z4q16ljh_80000gn/T/309352994 -o/var/folders/dh/z54p11md5cz308z4q16ljh_80000gn/T/solo-kit-gen-716657945 --include_imports --include_source_info /Users/joshh/go/src/github.com/solo-io/gloo/vendor_any/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/extauth/sanitize.proto] failed: ",
      },
      stack: &errors.stack{
        0x15a1684,
        0x15a158c,
        0x159f4f2,
        0x15a1c87,
        0x159edb4,
        0x105beb1,
      },
    },
    msg: "writing descriptors",
  }
```

I don't see `protoc` binary being installed by the `update-deps` target, nor in my `$GOPATH/bin`
```
~/go/src/github.com/solo-io/gloo(master*) » ls $GOPATH/bin
2goarray        gloo            gocode-gomod    golint          gopls           guru            protoc-gen-ext
controller-gen  go-outline      godef           gomodifytags    gorename        impl            protoc-gen-gogo
dlv             go-symbols      godoctor        gopkgs          goreturns       kustomize
fillstruct      gocode          goimports       goplay          gotests         mockgen
```

@ilackarms or @yuval-k help pls?

**Comment by CamelCaseNotation** [comment]
```
$ brew install protoc-gen-go
```
that solved my problem! 😅

**Comment by CamelCaseNotation** [comment]
`rm -rf projects/gloo/pkg/plugins/grpc/*.descriptor.go` got me past another issue where I would get a non-zero exit code after `make generated-code -B`
