### ISSUE TITLE
GrpcServer flake

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2245]
Two afflicted PRs:
- https://github.com/solo-io/gloo/pull/2236
- https://github.com/solo-io/gloo/pull/2238

And the build logs:
- https://console.cloud.google.com/cloud-build/builds/8d1650cd-da10-480b-bf2f-69eb5d614b1a?project=solo-public
- https://console.cloud.google.com/cloud-build/builds/5eae12a1-9e28-4f20-adcb-4bbefb6934ea?project=solo-public

**Comment by marcogschmidt** [comment]
Another possibly related flake: https://console.cloud.google.com/cloud-build/builds/0defa9c3-bbe0-4f6a-94cf-0e2e5b604f6f?project=solo-public

**Comment by marcogschmidt** [comment]
Ran focussed test locally with the `-untilItFails` flag and was unable to reproduce after 250+ iterations.

**Comment by kdorosh** [comment]
Was able to repeatedly reproduce using `ENVOY_IMAGE_TAG=1.3.1 ginkgo -r -trace -compilers=2 -progress -failOnPending -compilers=2 -untilItFails -seed 1580933214 test/e2e`
