### ISSUE TITLE
Unifying K8s Ingress and Gloo Gateway

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2286]
@ilackarms 

One of the challenges with current Envoy implementation is that one cannot combine data from a load balancer that supports the **proxy protocol** with data from a load balancer that does not.  This means that if I use the proxy protocol on ingress into my K8s cluster that I cannot use the same gateway proxy to route traffic that may originate inside my cluster.

So, I need two proxies.  That got me thinking about the different roles of the two proxies.

One architecture that is possible today with Gloo is to have an  **external ingress proxy** that only (optionally) does  TLS termination, proxy protocol translation, and host based routing to an **internal proxy** that does finer grain routing (using Gloo Gateways, Virtual Services, and RouteTables). One can implement this with two Gloo gateway proxies (which is problematic given your pricing model).

However, what about using the K8s standard `Ingress` resource to perform as the **external ingress proxy**. This separation unifies the K8s standard `Ingress` resource with the more powerful Gloo Gateway resource.  Moreover, if this worked, then one could use the `external-dns` project to publish DNS entries, since `external-dns` supports the K8s `Ingress` resource.

Does Gloo support this use case? Does the Gloo implementation of the K8s Ingress resource support the proxy protocol?  

I suspect that you can see ways to address your pricing model as well.

**Comment by scootweiss** [comment]
@derrickburns the gloo Ingress doesn't currently support Proxy Protocol. you can run gateway and ingress simultaneously, though i would recommend just using multiple proxies

perhaps @ilevine @christian-posta or someone from Solo.io sales can help out on pricing issue?

**Comment by christian-posta** [comment]
So let's leave the pricing model out of the discussion in this community issue tracker. As you know, we're quite flexible wrt price and your desired architecture/constraints can be taken into account. The appropriate channel for pricing model discussion is sales@solo.io and happy to have enterprise questions in the #gloo-enterprise slack channel.

**Comment by rickducott** [comment]
Going to close this one as I think we have some workarounds that scott listed above, and don't intend to invest time to expand on the ingress controller right now.
