### ISSUE TITLE
External Envoy API docs do not render correctly

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2291]
We import some of the Envoy protobuf definitions in Gloo and generate API docs for them. The Envoy protos contain formatting directives that we are not able to render correctly, which leads to ugly entries in our API docs. For example, [this](https://github.com/solo-io/gloo/blob/f113c57bb41df54d0f7f8de8aa73ff524d72ca8d/projects/gloo/api/external/envoy/api/v2/route/route.proto#L1158) comment results in [this](https://docs.solo.io/gloo/latest/api/envoy/api/v2/route/route.proto.sk/#remoteaddress) API doc.

We need to update the comments on the protos to fix this.

**Comment by kdorosh** [comment]
reopening until https://github.com/solo-io/gloo/pull/2402 is merged
