### ISSUE TITLE
Knative install from glooctl fails with Error 128

### ISSUE THREAD

**Issue by ned1313** [solo-io/gloo#2296]
When attempting to install Knative using `glooctl` the following error is received:

```
Starting Gloo installation...
Error: installing gloo in knative mode: invalid version: exit status 128
```

Knative itself appears to install successfully. I am running the following versions:

glooctl: 1.3.2
kubectl: 1.16.0
kubernetes: 1.14.8
knative: v0.10.0

**Comment by marcogschmidt** [comment]
This is a [known issue](https://github.com/solo-io/gloo/releases/tag/v1.3.2) affecting `glooctl` version `1.3.2` and has been resolved with [this PR](https://github.com/solo-io/gloo/pull/2237).

The fix will be released with version `1.3.3`.
