### ISSUE TITLE
deleting/recreating kube app with existing upstream & virtual service requires removal of vs

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2309]
1) deploy petstore app
2) wait until dynamic upstream is valid
3) create a vs referencing the upstream
4) delete petstore deployment&service
5) redeploy petstore 

All virtualservices are now invalid because of missing upstream. The vs needs to be deleted to get back to a healthly state. Also, you can run into this error which requires a restart of the discovery pod to get the dynamic upstream recreated:

`{"level":"error","ts":"2020-01-29T17:08:34.500Z","logger":"uds.v1.event_loop.uds","caller":"discovery/discovery.go:139","msg":"failed reconciling upstreams","version":"1.2.12","discovered_by":"kubernetesplugin","upstreams":32,"error":"reconciling resource default-petstore-8080: creating kube resource default-petstore-8080: the server was unable to return a response in the time allotted, but may still be processing the request (post upstreams.gloo.solo.io)","errorVerbose":"the server was unable to return a response in the time allotted, but may still be processing the request (post upstreams.gloo.solo.io)\ncreating kube resource default-petstore-8080\ngithub.com/solo-io/solo-kit/pkg/errors.Wrapf\n\t/workspace/gopath/pkg/mod/github.com/solo-io/solo-kit@v0.11.13/pkg/errors/errors.go:12\ngithub.com/solo-io/solo-kit/pkg/api/v1/clients/kube.(*ResourceClient).Write\n\t/workspace/gopath/pkg/mod/github.com/solo-io/solo-kit@v0.11.13/pkg/api/v1/clients/kube/resource_client.go:242\ngithub.com/solo-io/solo-kit/pkg/api/v1/reconcile.(*reconciler).syncResource\n\t/workspace/gopath/pkg/mod/github.com/solo-io/solo-kit@v0.11.13/pkg/api/v1/reconcile/reconciler.go:94\ngithub.com/solo-io/solo-kit/pkg/api/v1/reconcile.(*reconciler).Reconcile\n\t/workspace/gopath/pkg/mod/github.com/solo-io/solo-kit@v0.11.13/pkg/api/v1/reconcile/reconciler.go:38\ngithub.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*upstreamReconciler).Reconcile\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/api/v1/upstream_reconciler.sk.go:46\ngithub.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).Resync\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/discovery/discovery.go:135\ngithub.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).StartUds.func1\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/discovery/discovery.go:106\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nreconciling resource default-petstore-8080\ngithub.com/solo-io/solo-kit/pkg/errors.Wrapf\n\t/workspace/gopath/pkg/mod/github.com/solo-io/solo-kit@v0.11.13/pkg/errors/errors.go:12\ngithub.com/solo-io/solo-kit/pkg/api/v1/reconcile.(*reconciler).Reconcile\n\t/workspace/gopath/pkg/mod/github.com/solo-io/solo-kit@v0.11.13/pkg/api/v1/reconcile/reconciler.go:39\ngithub.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*upstreamReconciler).Reconcile\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/api/v1/upstream_reconciler.sk.go:46\ngithub.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).Resync\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/discovery/discovery.go:135\ngithub.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).StartUds.func1\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/discovery/discovery.go:106\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).Resync\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/discovery/discovery.go:139\ngithub.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).StartUds.func1\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/discovery/discovery.go:106"}`

**Comment by bdecoste** [comment]
You can also run into similar problems if you just delete and recreate the petstore service.

**Comment by bdecoste** [comment]
Also able to been able to recreate the symptoms where a stale upstream remains and envoy config has an unhealthy upsttream with no IP. When you do a deployment and change labels/selectors and the existing upstream is not deleted and recreated by discovery (to recreate scale discovery down to 0 prior to redployment and back up to 1 post deployment) then you can get no healthy upstream and the envoy config is as described (IP in kube-svc but missing in the upstream envoy config). This issue is resolved by deleting the upstream and allowing discovery to recreate.

**Comment by sjortiz** [comment]
I'm having this same issue right now
