### ISSUE TITLE
Docs for GCE Load Balancer setup

### ISSUE THREAD

**Issue by ghost** [solo-io/gloo#2310]
Following https://github.com/solo-io/gloo/issues/2102, is there any chance a documentation on how to set up Gloo behind the Google Global Load Balancer (ingress-gce) can be provided? I am having a great deal of trouble configuring health checks to gateway-proxy.

**Comment by omatsko** [comment]
It seems not to be possible to use ingress-gce with Gloo because of lacking features: https://github.com/kubernetes/ingress-gce/issues/42 https://github.com/kubernetes/ingress-gce/pull/1010
