### ISSUE TITLE
gateway should merge virtual services based on domain

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#232]
currently, gloo returns an error on the vservice if its domains conflict with any other vservices

what this feature would do is do an opinionated merge (with some kind of route sort) of one or more virtual services based on domain. if domains overlap, we will create a merged vhost with that (it would be good to LOG it for now)

**Comment by ilackarms** [comment]
we can preserve the current behavior by adding a bool field to the virtual service called `allow_merge`

**Comment by ilevine** [comment]
Closing until we receive more customer validation on this.
