### ISSUE TITLE
Gloo Enterprise changelog is missing entries

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2329]
The [changelog](https://docs.solo.io/gloo/latest/changelog/enterprise/) is missing releases `v1.2.1` through `1.2.3`.

**Comment by kdorosh** [comment]
They would exist on a rebuild of the 1.2 docs, fwiw

**Comment by kdorosh** [comment]
resolved by https://github.com/solo-io/gloo/issues/2799
