### ISSUE TITLE
Diagnose problems during installation

### ISSUE THREAD

**Issue by rettori** [solo-io/gloo#233]
Feature Request:
provide a `glooctl diagnose install` -like feature that would beforehand notify you of possible problems you will encounter during the installation
suggestion o verifications:
- version mismatch or incompatibility

- permissions

- licenses (if it is the case)

- access to bits (offline installation)

**Comment by christian-posta** [comment]
Related https://github.com/solo-io/gloo/issues/229

`glooctl install kube --test-run` or something would be nice

**Comment by rickducott** [comment]
I think we can close this now: 
* During install, we will report on errors related to the install (i.e. user doesn't have the ability to create CRDs, cluster resources, namespaces, etc). Don't have any data to suggest we need to make improvements here, but happy to track further improvement with issues as things come up. 
* CLI ensures there is a license for enterprise
* Helm chart testing should ensure the chart itself is not buggy
* `glooctl check` will report any issues once things are installed
