### ISSUE TITLE
Explicitly document Gloo/Gloo Enterprise version mapping

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2330]
It should be very easy for a user to understand which version of OS Gloo a certain version of Gloo Enterprise is based on. Right no, a user had to go to the GlooE [changelog](), look for `solo-io/gloo has been upgraded to XYZ` entries, and figure out which one is relevant (the version bump is not present on all entries). For example, it is impossible to understand what OS version corresponds to GlooE release [v1-3-0-beta1](https://docs.solo.io/gloo/latest/changelog/enterprise/#v1-3-0-beta1).

We should include a an explicit message in each GlooE release entry, specifying which OS Gloo release it is based on.

**Comment by nr-dbuckwalter** [comment]
Looking at [the current Gloo Edge Enterprise Changelog](https://docs.solo.io/gloo-edge/latest/reference/changelog/enterprise/) the OSS version is indicated in each heading.  I think this can be closed
