### ISSUE TITLE
manual creation of kube upstream results in "no healthy upstream"

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2334]
To recreate:
1) deploy petstore in default namespace
2) create and test a VS using that dynamically created upstream
3) save discovered kube upstream yaml in a file
4) change settings watchNamespaces to only watch gloo-system which causes upstream to be deleted
5) manually create upstream from previously saved file
6) test the vs ... the request will return "no healthy upstream"

A dynamically watched/created upstream creates a different envoy config than the identical manually created config. The latter envoy config is incomplete, inaccessible, and reported as unhealthy

Manually creating an upstream targeting a kube service needs to be at least documented to use a static type pointed at the resolvable service hostname and not a kube type upstream
OR ...
fix as a bug

**Comment by rickducott** [comment]
The issue is the yaml that was saved looked like it was written by discovery, because of the following label:

`discovered_by: kubernetesplugin`

That means the upstream was immediately deleted by discovery when created manually. Once you delete that label and apply, it works as expected.
