### ISSUE TITLE
envoy: gloo is incompatible with upstream envoy due to transformation filter

### ISSUE THREAD

**Issue by scootweiss** [solo-io/gloo#2338]
gloo always loads the transformation filter in the filter chain as a way of making the loading of the filter faster. however, this is problematic for users who wish to run Gloo with a version of Envoy which does not include the filter (such as Upstream Envoy)

**Comment by frederiko** [comment]
I will be following up this closely. I would like to prototype Gloo along with Redis and Kafka filter. Both backed by Consul and K8.

**Comment by scootweiss** [comment]
@frederiko we are soon upgrading our version of envoy to include those filters. we will need to expose their configuration in Gloo's API
