### ISSUE TITLE
Build bug: multiple paths in GOPATH

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#234]
This generate statement assumes the $GOPATH will be a single directory:

https://github.com/solo-io/gloo/blob/faffd00a2a01258a8cc7b72d82c3fa45b8d66796/projects/gloo/pkg/plugins/aws/plugin.go#L29

If you have multiple paths in GOPATH, it fails:

`GOPATH=/home/ceposta/gopath:/another/gopath:/foo/path`

**Comment by yuval-k** [comment]
i plan to vendor all the protos in a different way as port of us moving to go modules, so this will be solved as well

**Comment by ilevine** [comment]
closing as the long term plan is go.mod migration
