### ISSUE TITLE
support 1-way TLS auth between Gloo and custom Grafana

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2344]
Need to be able to configure CA certs for the TLS handshake to the custom grafana

**Comment by kdorosh** [comment]
The Gloo Enterprise observability pod is responsible for converting Gloo-discovered upstreams and writing grafana dashboards for each upstream. To do so, the observability pod creates an http client to hit the grafana api. We need to support https connections to the grafana instance if grafana is configured with https (e.g. https://stackoverflow.com/questions/39956790/grafana-switch-from-http-to-https).

We need to update the observability pod to properly handle the configured grafana url (via the `GRAFANA_URL` env var) if it has an https scheme.
