### ISSUE TITLE
HTTP + GRPC on same port

### ISSUE THREAD

**Issue by george-oakling** [solo-io/gloo#2349]
Hi, is it possible to configure Gloo that we can have HTTP and GRPC on the same port and backend should be chosen by the type of the traffic? Or same backend but different port.

**Comment by CamelCaseNotation** [comment]
Hi @george-oakling, this functionality *might* be enabled once #2244 is addressed

@ilackarms @EItanya does that sound right to y'all? Unsure what listeners on what ports are valid for handling gRPC traffic.

@george-oakling if it's TLS gRPC traffic, then this will not be possible AFAIK

**Comment by george-oakling** [comment]
@CamelCaseNotation understood :) thanks for info and link to addressed issue :)
