### ISSUE TITLE
UDS fails when discovering for namespaces that start with a number

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#235]
apparently, kubernetes allows **namespaces** with names that are not  DNS-1035 labels, but will not allow **upstreams** (or presumably any CRD) to be written with a non DNS-1035 name.

this means that a namespace can start with a number, but upstream may only begin with a letter.

this could be problematic if a user tries to run UDS on a namespace starting with a number, as upstreams are currently named by `namespace-servicename-port`

**Comment by rickducott** [comment]
Closing as stale.
