### ISSUE TITLE
Bring back line breaks in docs

### ISSUE THREAD

**Issue by arianaw66** [solo-io/gloo#2352]
It seems like some recent CSS change removed all the line breaks from the Gloo Docs.

For example, this page in version 1.3.0 has 3 paragraphs in the first section:
https://docs.solo.io/gloo/1.3.0/gloo_routing/

But the latest version has it all in one paragraph, ignoring the line breaks in the md file:
https://docs.solo.io/gloo/latest/gloo_routing/

**Comment by arianaw66** [comment]
@ascampos @Krief

**Comment by rickducott** [comment]
I'm not following what is the issue here. If there is still a problem can you please reopen with more details?

**Comment by kdorosh** [comment]
The formatting in our docs is wrong, and was broken in the upgrade to the new theme (with the dropdown).

Line breaks are no longer honored by our CSS, thus the markdown doesn't render as intended. This results in jumbo paragraphs that can be hard to read.
