### ISSUE TITLE
intermittent 503 when upstreams are updated

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2356]
currently, Gloo temporarily drops its EDS snapshot when Upstreams resync, which can cause a 503 "hiccup" for clients connecting to the Proxy when Gloo temporarly flushes its EDS cache

**Comment by CamelCaseNotation** [comment]
This explains my issue most likely #2368

**Comment by CamelCaseNotation** [comment]
Can this be cherry picked into 1.3.3? And/or a new patch version 1.3.4?
