### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2361]
Some customers have reported a memory leak in Gloo that rises over time.

In the meantime, they have set resource limits to prevent further growth, but we should identify the cause and address it.

**Comment by kdorosh** [comment]
I have metrics, memprofile, and heap dumps, which I put in a google cloud bucket here: https://console.cloud.google.com/storage/browser/kdorosh-mem-leak?project=solo-public

**Comment by NelsonJeppesen** [comment]
I'm seeing this as well

**Comment by kdorosh** [comment]
This has been resolved for gloo, discovery, and api-server in the following versions:
- Gloo 1.3.19
- Gloo 1.4.0-beta2
- Gloo Enterprise 1.4.0-beta2 (to be released in the next couple days)
- Gloo Enterprise 1.3.1
