### ISSUE TITLE
document using gloo gRPC upstream

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2372]
currently we have a doc on using Gloo with json-grpc transcoder, but not with a grpc client and service.

we should document how to do this - it's pretty simple (we must ensure useHTTP2 gets set on the upstream - there are various ways this can happen for example via the name of the kube svc port) as it's a common question

cc @ned1313

**Comment by kdorosh** [comment]
Ideally our docs also have an example with TLS, as requested here https://github.com/solo-io/gloo/issues/2488
