### ISSUE TITLE
Proxy stuck in pending state, test flake

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2384]
PR where it occurred: https://github.com/solo-io/gloo/pull/2380

Build: https://console.cloud.google.com/cloud-build/builds/0e9cca4c-f72f-46bd-a733-5e2c84e47f21;step=17?project=solo-public

Perhaps points to a rare race in Gloo, needs looking into

**Comment by rickducott** [comment]
We've made a few fixes that have addressed this / related issues. We aren't seeing this anymore and can open issues for problems that continue to pop up
