### ISSUE TITLE
Decouple gateway proxy service creation

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2385]
@ilackarms 

If one reinstalls the API gateway, it is possible that the Kubernetes LoadBalancer service associated the the gateway proxy will be deleted and reinstalled.  I know, I did it unintentionally on production. 

This is not good because the cycling of DNS alias can take quite a while, resulting in noticeable downtime.

With the current Helm chart, the creation of the Service is bound to the use of the gateway.  I suggest that you decouple this, so that one may have the option of NOT installing the service with the helm chart.

**Comment by ilackarms** [comment]
hey @derrickburns my thinking in this area is that, generally, the deployment components for the proxies (deployment/daemonset, configmap, service, etc) should be managed by an operator. this would also greatly simplify some workflows such as proxy upgrades, wdyt?

**Comment by derrickburns** [comment]
Agreed. This makes the most sense.

**Comment by ilackarms** [comment]
linking #2295
