### ISSUE TITLE
Validation disabled, then readiness probe is never successful

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2393]
If disabled, we should run a slightly different version of the readiness probe

**Comment by CamelCaseNotation** [comment]
Can you please include what version of Gloo this applies to? Thanks!

**Comment by kdorosh** [comment]
Discovered on Gloo 1.2.12, still an issue on master.

**Comment by CamelCaseNotation** [comment]
Are you talking about the gateway deployment? That's what I'm seeing constantly fail on 1.2.17.

**Comment by CamelCaseNotation** [comment]
Except my validation is enabled, so dunno if this is related
