### ISSUE TITLE
glooctl uninstall --all does not remove prometheus ClusterRoles and ClusterRoleBindings installed with helm

### ISSUE THREAD

**Issue by arianaw66** [solo-io/gloo#2419]
To reproduce:
- `kubectl create ns gloo-system`
- `helm install glooe glooe/gloo-ee --namespace gloo-system`
- `glooctl uninstall --all`
- `kubectl get ClusterRole | grep gloo` --> 
- `kubectl get ClusterRoleBinding | grep gloo`

These ClusterRoles and ClusterRoleBindings remain: `glooe-glooe-prometheus-alertmanager` `glooe-glooe-prometheus-pushgateway` `glooe-prometheus-kube-state-metrics` `glooe-prometheus-server`

This also means you cannot reinstall enterprise:
`helm install glooe glooe/gloo-ee --namespace gloo-system`
 --> "Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ClusterRole, namespace: , name: glooe-glooe-prometheus-alertmanager"

`glooctl install gateway enterprise --license-key $GLOO_LICENSE_KEY`
--> "Gloo failed to install! Detailed logs available at /Users/aweinstock/.gloo/debug.log.
Error: installing Gloo Enterprise in gateway mode: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ClusterRole, namespace: , name: glooe-prometheus-kube-state-metrics"

Relates to https://github.com/solo-io/gloo/issues/2219

**Comment by rickducott** [comment]
The issue here is we have installed using the release name `glooe`, but `glooctl uninstall` assumes the release name was`gloo`. When installing with this command:

`helm install gloo] glooe/gloo-ee --namespace gloo-system`

Then uninstall works as expected.
