### ISSUE TITLE
Global sslConfig (e.g. in gateway)

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2426]
So that a single secret does not have to be added to every VS

**Comment by ilackarms** [comment]
I like this suggestion. Perhaps on the gateway level? The SSL config actually lives on the filter chain level in envoy

**Comment by kdorosh** [comment]
Related, https://github.com/solo-io/gloo/issues/4285 added global sslConfig to the gloo settings. we may still want to do it at the gateway level at some point
