### ISSUE TITLE
Installing with microk8s

### ISSUE THREAD

**Issue by dantodor** [solo-io/gloo#2427]
Environment: Ubuntu 18.04 machine, microk8s 1.17, glooctl installed as per docs ( cannot view version as it bombs out )

`ubuntu@microk8s-vm:~$ glooctl version
Warning: Could not determine gloo client/server versions (is Gloo running outside of kubernetes?): Get https://127.0.0.1:16443/apis/apps/v1/namespaces/gloo-system/deployments?labelSelector=app%3Dgloo: x509: certificate signed by unknown authority
Error: Get https://127.0.0.1:16443/apis/apps/v1/namespaces/gloo-system/deployments?labelSelector=app%3Dgloo: x509: certificate signed by unknown authority`

I know that it is somehow a problem with microk8s, I get the same kind of message with kubectl , however, the last one offers the `--insecure-skip-tls-verify` escape hatch. NB, I tried to add the flag to the config, the result is :

`Warning: Could not determine gloo client/server versions (is Gloo running outside of kubernetes?): specifying a root certificates file with the insecure flag is not allowed
Error: specifying a root certificates file with the insecure flag is not allowed`

I know I can install it via Helm, but still... I would like to configure Gloo with glooctl.
I think it would be a good option to allow at least some kubectl flags in the command line, since glooctl is using its config....
Thanks!

**Comment by rickducott** [comment]
Thanks for filing! We had discussed adding this flag but hadn't heard this issue reported in awhile (#351).
