### ISSUE TITLE
Make creating the enterprise license_key optional in helm

### ISSUE THREAD

**Issue by snuggie12** [solo-io/gloo#2433]
Currently there's a value called "license_key". I'd like this changed to something like:

```
license_key:
  create:
  license_key:
```

`create` is a similar value stolen from settings. Essentially just wrap the entire license_key template with an if condition.

This allows the operator to make the secret ahead of time themselves and putting the license_key in git (should the operator do gitops CD).

**Comment by kdorosh** [comment]
Opted to add a single helm value, `create_license_secret`, which when set to false, disables this secret generation.

We opted to do this to avoid breaking previous helm users by re-nesting the `license_key` itself.

This change will go out in Gloo Enterprise 1.3.0-beta4 and Gloo Enterprise 1.2.8
