### ISSUE TITLE
allow buffer filter in gloo

### ISSUE THREAD

**Issue by yuval-k** [solo-io/gloo#2444]
Allow using the envoy buffer filter in gloo. Buffer filter should be configured on a per\vhost\route level.
cc @kdorosh

**Comment by yuval-k** [comment]
also cc @derrickburns

**Comment by derrickburns** [comment]
I am hoping to use this to track down a persistent timeout problem that we are seeing with large POSTs not completing.

**Comment by eshepelyuk** [comment]
Is this can be used to restrict file upload size ?

**Comment by derrickburns** [comment]
@kdorosh Any plans for this?

**Comment by kdorosh** [comment]
@derrickburns sorry for the late reply. this got pushed into our Q2 priorities but we should be picking up this feature request in the near future.
