### ISSUE TITLE
Double loadbalancer services when knative version >= 0.10.0

### ISSUE THREAD

**Issue by mrManner** [solo-io/gloo#2448]
When using Helm to install gloo with the knative integration, two loadbalancers are created:

```
NAME                             TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                               AGE
service/clusteringress-proxy     LoadBalancer   10.245.166.241   157.245.25.240   80:32281/TCP,443:31514/TCP            31m
service/gloo                     ClusterIP      10.245.157.18    <none>           9977/TCP,9988/TCP,9966/TCP,9979/TCP   31m
service/knative-external-proxy   LoadBalancer   10.245.142.149   157.245.25.239   80:32328/TCP,443:31320/TCP            31m
service/knative-internal-proxy   ClusterIP      10.245.228.52    <none>           80/TCP,443/TCP                        31m
```

I'm not 100% sure, but I believe it's just the `knative-external-proxy` that's supposed to be created and the issue lies in [this regex](https://github.com/solo-io/gloo/blob/f833ddf707ade6138854ba677c348278dc8153e4/install/helm/gloo/templates/16-clusteringress-proxy-service.yaml#L2)?

**Comment by ilackarms** [comment]
@mrManner that appears correct. we need to fix the regex in that line. thanks for the issue! nice work tracking this down
