### ISSUE TITLE
hide write functions from non-enterprise console 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2450]
apiServer.enterprise=false disables write functions but write capabilities (e.g. create/new buttons) are still viewable. Remove the write functionality from non-enterprise console

**Comment by rickducott** [comment]
While NTH, we have very limited bandwidth and I don't see this being a priority. Could reopen if I'm missing some context, but I'm not sure why the current implementation doesn't get the job done.

**Comment by kdorosh** [comment]
In addition, we recently added modals that give users clear errors. The user who requested this feature was on an older version of Gloo that didn't have this update.
