### ISSUE TITLE
Enhanced Inja transformation (independent CRD, override variabled, path-prefix level config)

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2463]
1) Move Inja transformation to an independent CRD so can be referenced at the route level instead of repeated
2) Support variables in Inja Tranformation code (i.e. RETURN_CODE) so a referenced Inja Transformation resource can be customized at the route level
3) Support Inja Transformation at path prefix level (i.e. Inja transform for /foo would apply to paths /foo/bar1, /foo/bar2, etc)

**Comment by yuval-k** [comment]
3 should be supported today - you can setup a transformation on the listener level with matchers to match your desired route

**Comment by chrisgaun** [comment]
anything defined in RouteOptions (https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/options.proto#L263) or VirtualHostOptions (https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/options.proto#L163) can be configured in the CRD, and transformations is one of them
