### ISSUE TITLE
How to access mutliple knative services upstreams for Gloo virtual Gateway at run time

### ISSUE THREAD

**Issue by koturwaraditi** [solo-io/gloo#2472]
I am facing an issue for updating the multple knative-serving upstream inside a virtual service at run time when we called the knative function.
 And in below Yaml formate at run time how we need to change the hostRewrite name.
For example If there is a multiple knative function which will called simultaneously one after the other than how we need to handle hostRewrite name inside virtual service.
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: domain
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'customdomain.io'
    routes:
      - matchers:
        - prefix: /
        routeAction:
          single:
            upstream:
              name: gloo-system-knative-external-proxy-80
              namespace: gloo-system
        options:
          hostRewrite: helloworld.default.example.com

**Comment by ilackarms** [comment]
hey @koturwaraditi check out #2410 i think it addresses exactly this use case?

**Comment by rickducott** [comment]
Closing in favor of the linked issue that would provide a solution here.
