### ISSUE TITLE
ingress: status is never updated properly on Ingress resources due to subresource

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2473]
When Gloo is installed in `ingress` mode, it attempts to mark ingress resources with the `status.loadBalancer` field.

it appears `status` is treated by Kubernetes as a subResource, which means the following `Write` call will fail (silently) to update the status:

https://github.com/solo-io/gloo/blob/e96ddb29dcc61b164f7f982df4fbf5849e111ca5/projects/ingress/pkg/status/status_syncer.go#L61

To fix this feature, we need to make Gloo use the `updateStatus` endpoint to update the Ingress' status.

RBAC may need to be fixed as well.

**Comment by RichiCoder1** [comment]
Just ran into this. This has the knock on effect of preventing usage with external-dns.
