### ISSUE TITLE
ability to mask sensitive data in logs

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2486]
DLP?

**Comment by yuval-k** [comment]
we need this on the access log level; 
there is a way to extend a filter to allow modifying the headers before logging. so we can add that as a type of transformation. 
we need to validate that this indeed works and that no upstream envoy changes are needed.

**Comment by jahvon** [comment]
Duplicate of https://github.com/solo-io/gloo/issues/4282
