### ISSUE TITLE
Health checks cause Gloo to temporarily retain invalid extauth endpoints 

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2489]
## Problem 
We currently configure the following active health checks on the upstream that represents the Gloo Enterprise extauth server:

```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: extauth
  namespace: gloo-system
spec:
  healthChecks:
  - grpcHealthCheck: 
      serviceName: ext-auth
    healthyThreshold: 5
    interval: 60s
    timeout: 5s
    unhealthyThreshold: 5
#...
```

An endpoint will be considered unhealthy if 5 consecutive health checks (one each 60 seconds) fail.

Active health checks - not service discovery - are the source of truth as to whether traffic should be routed to an endpoint. The [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery.html#on-eventually-consistent-service-discovery) state that if an endpoint (host) is absent from a service discovery snapshot but the corresponding health check did not fail, then
> Envoy **will route** to the target host. This is very important since the design assumes that the discovery service can fail at any time. If a host continues to pass health check even after becoming absent from the discovery data, Envoy will still route.

This is a problem when the `extauth` endpoints change (e.g. pod gets recreated during an upgrade process), because Envoy will continue sending traffic to the old endpoints (in addition to the new ones) until the health checks fail (which currently takes 5 minutes), causing 50% of requests to the extauth cluster to fail until then

## Steps to reproduce
1. [Install Gloo Enterprise](https://docs.solo.io/gloo/latest/installation/enterprise/#installing-on-kubernetes-with-glooctl)
2. Create a simple external auth setup (e.g. following the [basic auth guide](https://docs.solo.io/gloo/latest/security/auth/basic_auth/)).
3. Verify that you consistently get `200 OK` responses with 
`hey -z 5s -q 5 -c 5 -H "Authorization: basic dXNlcjpwYXNzd29yZA==" -host foo $(glooctl proxy url)/posts/1`
4. Scale `extauth` deployment to 0
`kubectl scale deployment/extauth --replicas=0 -n gloo-system`
5. Scale `extauth` deployment back to 1
`kubectl scale deployment/extauth --replicas=1 -n gloo-system`
6. Wait until the old `extauth` has been completely terminated and the new one is `Running`
7. Submit the same `hey` command again:
`hey -z 5s -q 5 -c 5 -H "Authorization: basic dXNlcjpwYXNzd29yZA==" -host foo $(glooctl proxy url)/posts/1`
8. You should get an even distribution of `403` and `200` response codes
![image](https://user-images.githubusercontent.com/16148461/75171906-67b5c580-56fa-11ea-93ca-4715c83000f8.png)

The `403` response codes represent the default response that envoy sends back when it was not able to contact the `extauth` server to make a decision.

## Further debugging of endpoint
To get more information about the `extauth` cluster endpoints, perform the following steps right after reproducing the behavior above:
1. Port forward the envoy admin port: 
`kubectl port-forward -n gloo-system deployment/gateway-proxy 19000`
2. Go to `http://localhost:19000/clusters` in your browser
3. Search for `extauth_gloo-system` on the resulting page

You should see the following:
```shell
extauth_gloo-system::default_priority::max_connections::1024
extauth_gloo-system::default_priority::max_pending_requests::1024
extauth_gloo-system::default_priority::max_requests::1024
extauth_gloo-system::default_priority::max_retries::3
extauth_gloo-system::high_priority::max_connections::1024
extauth_gloo-system::high_priority::max_pending_requests::1024
extauth_gloo-system::high_priority::max_requests::1024
extauth_gloo-system::high_priority::max_retries::3
extauth_gloo-system::added_via_api::true
# ------ This is the endpoint for the new pod
extauth_gloo-system::192.168.43.133:8083::cx_active::0
extauth_gloo-system::192.168.43.133:8083::cx_connect_fail::0
extauth_gloo-system::192.168.43.133:8083::cx_total::0
extauth_gloo-system::192.168.43.133:8083::rq_active::0
extauth_gloo-system::192.168.43.133:8083::rq_error::0
extauth_gloo-system::192.168.43.133:8083::rq_success::0
extauth_gloo-system::192.168.43.133:8083::rq_timeout::0
extauth_gloo-system::192.168.43.133:8083::rq_total::0
extauth_gloo-system::192.168.43.133:8083::hostname::
# ------ Note the "healthy" flag
extauth_gloo-system::192.168.43.133:8083::health_flags::healthy
extauth_gloo-system::192.168.43.133:8083::weight::1
extauth_gloo-system::192.168.43.133:8083::region::
extauth_gloo-system::192.168.43.133:8083::zone::
extauth_gloo-system::192.168.43.133:8083::sub_zone::
extauth_gloo-system::192.168.43.133:8083::canary::false
extauth_gloo-system::192.168.43.133:8083::priority::0
extauth_gloo-system::192.168.43.133:8083::success_rate::-1
extauth_gloo-system::192.168.43.133:8083::local_origin_success_rate::-1
# ------ This is the endpoint for the old pod (note different IP)
extauth_gloo-system::192.168.46.194:8083::cx_active::2
extauth_gloo-system::192.168.46.194:8083::cx_connect_fail::0
extauth_gloo-system::192.168.46.194:8083::cx_total::2
extauth_gloo-system::192.168.46.194:8083::rq_active::0
extauth_gloo-system::192.168.46.194:8083::rq_error::0
extauth_gloo-system::192.168.46.194:8083::rq_success::250
extauth_gloo-system::192.168.46.194:8083::rq_timeout::0
extauth_gloo-system::192.168.46.194:8083::rq_total::250
extauth_gloo-system::192.168.46.194:8083::hostname::
# ------ Note the "pending_dynamic_removal" flag
extauth_gloo-system::192.168.46.194:8083::health_flags::/pending_dynamic_removal
extauth_gloo-system::192.168.46.194:8083::weight::1
extauth_gloo-system::192.168.46.194:8083::region::
extauth_gloo-system::192.168.46.194:8083::zone::
extauth_gloo-system::192.168.46.194:8083::sub_zone::
extauth_gloo-system::192.168.46.194:8083::canary::false
extauth_gloo-system::192.168.46.194:8083::priority::0
extauth_gloo-system::192.168.46.194:8083::success_rate::-1
extauth_gloo-system::192.168.46.194:8083::local_origin_success_rate::-1
```

Note the [`pending_dynamic_removal`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/admin/v3/clusters.proto.html?highlight=pending_dynamic_removal#admin-v3-hosthealthstatus) heath flag, which indicates that the endpoint is not present in the discovery snapshot, but is being kept around due to non-failing health checks.

## Possible solutions
1. Expose the [`drain_connections_on_host_removal`](https://www.envoyproxy.io/docs/envoy/v1.13.0/api-v2/api/v2/cluster.proto#envoy-api-field-cluster-drain-connections-on-host-removal) field on the Gloo upstream resource and set it to `true` on the `extauth` upstream.
2. Update the `extauth` server to send the [`x-envoy-immediate-health-check-fail`](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#active-health-checking-fast-failure) header back to Envoy when a `SIGTERM` signal is received, at the same time initiating a gracefully shutdown process

**Comment by marcogschmidt** [comment]
## N.B.
This problem impacts the rate limiting server as well.

**Comment by yuval-k** [comment]
i think ideally we want to fix the health checks (i.e. solutin 2) as the need for this is still there (make sure no traffic drops when doing an upgrade to extauth or RL).
we can also reduce the interval to 10 seconds, so this will work within the default pod grace period.

do note that we need to keep the pod alive after it gets sigterm, long enough for envoy to perform a health check (for example, terminate the pod after 20s, if the health interval is 10s); we can let kube do that by killing the pod, or implement it ourselves in the code

**Comment by yuval-k** [comment]
I am ok with option 1 as well, as long as we guarantee / prove that there is no connection dropped in that scenario.

**Comment by ermakov-oleg** [comment]
We encountered a similar problem when enabling active health check's for our microservices. 

We are getting 503 spikes every time we rolling update a deployment, which means that without changing the code of hundreds of microservices to support the `x-envoy-immediate-health-check-fail` header, we can't enable active health check's.

Can we expect that in the near future there will be an ability to specify [drain_connections_on_host_removal](https://www.envoyproxy.io/docs/envoy/v1.13.0/api-v2/api/v2/cluster.proto#envoy-api-field-cluster-drain-connections-on-host-removal) in upstream?
