### ISSUE TITLE
Gloo and discovery very high CPU usage

### ISSUE THREAD

**Issue by vstrizaks** [solo-io/gloo#2503]
Hello. First of all, thank you for this project! 

We have a problem with gloo and discovery Pod. They have very high CPU usage:

kubectl top pod:
`gloo-7fb49d4f55-qpxr7           4447m        416Mi`

top inside pod:
```
Load average: 19.64 21.76 22.06 23/11423 148
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 10101    S    1065m   0%  40   4% /usr/local/bin/gloo
  140     0 10101    S     1640   0%  58   0% sh
  148   140 10101    R     1572   0%  61   0% top
```

kubectl top pod:
`discovery-7b8b8448f8-jx8q7      1812m        1168Mi`

top inside pod:
```
Load average: 17.58 18.94 18.97 36/11026 90
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 10101    S    1536m   0%  41   3% /usr/local/bin/discovery
   85     0 10101    S     1640   0%  36   0% sh
   90    85 10101    R     1572   0%  38   0% top

```
Settings:
    discovery:
       fdsMode: DISABLED

Gloo: v1.3.9
OS: CentOS 7
Kernel: 5.5.2-1.el7.elrepo

In attachment, you can find CPU profile from Gloo:
[gloo_profile.gz](https://github.com/solo-io/gloo/files/4256089/gloo_profile.gz)

**Comment by rickducott** [comment]
Had another report of memory pressure in Gloo and api-server pods on Gloo 1.2.18 (OS)
