### ISSUE TITLE
Child links in docs not rendering correctly 

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2506]
![image](https://user-images.githubusercontent.com/27434432/75363921-da54ab80-5888-11ea-8e11-e880f939df18.png)

I fixed in wasme with: https://github.com/solo-io/wasme/blob/cde2b3643299768854354309ffa4b0c25683c8d0/docs/docs.toml#L66

**Comment by ned1313** [comment]
It appears to be an issue with the way that the `children` shortcode is generating output. When it goes to the markdown rendered, all the HTML is being removed with a ` place holder. The markdown renderer can be explicitly told to allow unsafe HTML.

The release notes for 0.60 show the workaround: https://gohugo.io/news/0.60.0-relnotes/

We can add:

```
# fix link generation issue
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```

to the docs.toml file.
