### ISSUE TITLE
yaml in the server TLS example is not valid CRD

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2520]
https://docs.solo.io/gloo/latest/gloo_routing/tls/server_tls/

We shouldn't leave yaml that looks similar to a VS but not valid.

**Comment by arianaw66** [comment]
@rickducott Addressed this in https://github.com/solo-io/gloo/pull/2523, I believe.
Is that what you meant? To output kube-yaml instead of yaml so that the CRD is valid?
