### ISSUE TITLE
Remove duplicate Server TLS docs

### ISSUE THREAD

**Issue by arianaw66** [solo-io/gloo#2522]
These seem almost the same:
https://docs.solo.io/gloo/latest/gloo_routing/tls/server_tls/
https://docs.solo.io/gloo/latest/advanced_configuration/tls_setup/

Let's check the differences and remove one of them.

**Comment by kdorosh** [comment]
Nice find. I'm in favor of removing the one from the advanced configuration section

**Comment by arianaw66** [comment]
Great, since I just updated the Gloo Routing one. :)
I didn't investigate the other changes, but I have an inkling that it was already more up to date.
