### ISSUE TITLE
glooctl --dry-run doesn't include the creation of the gloo-system namespace

### ISSUE THREAD

**Issue by mreferre** [solo-io/gloo#2533]
I am trying to use glooctl to extract the deployment artifacts for knative/gloo as described [here](https://knative.dev/docs/install/knative-with-gloo/) using the dry-run flag. 

## Expected Behavior
When I generate the yaml file using the `--dry-run` flag (i.e. `glooctl install knative --dry-run > knative-gloo-fargate.yaml`) I expect to produce a yaml that I can apply. 

## Actual Behavior
The yaml generated apparently misses the creation of the `gloo-system` namespace so everything that is being applied in that ns fails.

## Steps to Reproduce the Problem
```
glooctl install knative --dry-run > knative-gloo.yaml
kubectl apply -f knative-gloo.yaml
```
At this point all resources that are deployed in the `gloo-system` ns fails. A quick workaround is to edit the file and add the following:
```
apiVersion: v1
kind: Namespace
metadata:
  name: gloo-system
```

**Comment by kdorosh** [comment]
You can get the namespace included in the dry run using the `helm` value `namespace.create=true`. The default is to have this off for helm 3 compatibility (but we include the extra helm value to maintain helm 2 compatibility) as helm 3 no longer creates namespaces.

**Comment by mreferre** [comment]
Thanks @kdorosh . Looking at the `glooctl` help it looks like the only way to pass this value is through a file (`--values strings` where `strings` is the name of a file which includes that setting)? Is there a way to pass that value via the CLI (other than creating the file on the fly in a chained command I mean). Thanks!

**Comment by mreferre** [comment]
Also, the `dry-run` option does spit a YAML that creates the `knative-serving` namespace (just not the `gloo-system` namespace). In fact half of the objects get created fine, whereas the other half fails. Isn't this inconsistent with the helm3 compatibility or am I missing something?

**Comment by kdorosh** [comment]
So `glooctl` doesn't allow for individual values overrides, as you point out. The `--values` flag is always parsed as the location of a helm values file.

This is inconsistent, likely stems from the fact that the knative config we grab is the fully-rendered yaml ready for `kubectl apply`.

We should keep `glooctl` consistent, either it renders or does not render namespaces in dry-runs. Will keep this open to track.

Including namespaces in dry-run output
Pros:
- can kubectl apply
- not leaking `glooctl` implementation details (`helm` affecting `glooctl` UX)
Cons:
- can be difficult to ensure namespace is created before resources that get installed to it when doing `kubectl apply`
