### ISSUE TITLE
Gloo on GKE using standalone NEGs

### ISSUE THREAD

**Issue by george-oakling** [solo-io/gloo#2536]
Hi, we would like to have blue/green deployment of clusters on GKE, so we can cleanly test the cluster and all of its features before we land in all the changes. As we use gloo, (and linkerd for service mesh), we would like to configure https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg so we can play with it more. The problem is I actually don't know how to add an annotation to the gateway service (which runs the envoy container) like `cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'`

Is it possible?

**Comment by george-oakling** [comment]
I forgot to mention that we use Helm for deployment of Gloo.

**Comment by george-oakling** [comment]
The other option would be to specify nodePort statically, which still is a modification to the original helm chart which does not support this now AFAIK.

**Comment by ilackarms** [comment]
yes @george-oakling this would require a change to the helm chart (something like `extraAnnotations` which we have elsewhere would do). cc @marcogschmidt @kdorosh

**Comment by rickducott** [comment]
Related to #2587

**Comment by rickducott** [comment]
Closing in favor of the other issue, which we're using to track exposing extraAnnotations on all services
