### ISSUE TITLE
Migrate to k8s-native sidecars once k1.19 comes out.

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo#2542]
We want to convert the following containers to the sidecar type:

https://banzaicloud.com/blog/k8s-sidecars/

All Gloo mTLS SDS and Envoy sidecars:
- gateway-proxy - sds
- gloo - sds and envoy
- extauth - sds and envoy
- rate-limiting - sds and envoy

**Comment by rickducott** [comment]
We can support this, but can’t rely on k8s 1.18+, we need to support older versions for some customers.

**Comment by ashleywang1** [comment]
https://banzaicloud.com/blog/k8s-sidecars/#:~:text=The%20sidecar%20pattern%20helps%20achieving,that%20extend%20the%20original%20functionality.&text=From%20Kubernetes%201.18%20containers%20can,all%20other%20containers%20have%20terminated.
