### ISSUE TITLE
support https for discovered consul upstreams with useTls (and possibly port 443)

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2544]
We should have the same auto-detection of https for consul upstreams as we do for static upstreams when the port is 443. We should also support `useTLS` as supported with static. Currently we need to add sslConfig to the upstream to enable an https call.

**Comment by rickducott** [comment]
Would be ideal to make the behavior consistent across different upstream types. See also #2583

**Comment by yuval-k** [comment]
amazon root CAs: https://www.amazontrust.com/repository/

**Comment by kdorosh** [comment]
consul service port detection for 443 should be sufficient -- no need to look at the consul service endpoint's ports
