### ISSUE TITLE
provide jwt to extauth for availability to custom plugins

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2548]

**Comment by rickducott** [comment]
The Gloo `jwt` filter will strip off the JWT from the request, but if it is passed through as an `Authorization` header, then it should be on the request as it reaches ext auth and accessible to custom plugins. The only other sanitizing that we do is in `sanitize` prior to rate limiting on the `x-user-id` header.

**Comment by rickducott** [comment]
Let's validate that the JWT is available to extauth
