### ISSUE TITLE
support autoHostRewrite for consul-discovered upstreams

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2552]
The host rewrite should match either the ID or Address of the Consul Service Instance

**Comment by phenixblue** [comment]
I think it's probably best to target the `address` field from the Consul service instance provided there are no undesirable side effects from using an FQDN as the address within Consul. Being able to use either would be nice, but would likely require some sort of configuration to allow for toggling.

**Comment by kdorosh** [comment]
Plan is to put hostname in discovered endpoint metadata, and use transformation to rewrite the host header

**Comment by kdorosh** [comment]
Instead added support for auto host rewrite to EDS in envoy, as noted here: https://github.com/envoyproxy/envoy/issues/10408

Trying to get those changes upstreamed, so we can pickup in Gloo. Awaiting feedback from Lyft team on proposal
