### ISSUE TITLE
have prefixRewrite wildcards match regex wildcards 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2562]
With
```
    - matchers:
      - regex: /foo/[a-zA-Z0-9]*/bar/[a-zA-Z0-9]*/
        prefixRewrite: /api/$1/pets/$2/tb12
```

Would like:
`/foo/go/bar/patriots/`
to map to:
`/api/go/pets/patriots/tb12 `

**Comment by rickducott** [comment]
We need to see if Envoy allows for this.

**Comment by bdecoste** [comment]
This is in process upstream: https://github.com/envoyproxy/envoy/issues/2092
