### ISSUE TITLE
gRPC Bidirectional Streaming Multicast w/ Gloo -> Lambda? 

### ISSUE THREAD

**Issue by tb438** [solo-io/gloo#2573]
Hi,

I have sort of a unique configuration that I'd like to get some advice on from an architecture perspective, to determine if this is even a possible configuration.

I have a large number of gRPC-enabled mobile clients that I want to establish a bidirectional streaming gRPC connection to Gloo-equipped Envoy, for AWS Lambda function routing.

Here's the problem. Each mobile client is continuously transmitting sensor data to the Envoy gRPC gateway cluster. I need to be able to multicast that stream across multiple AWS Lambda function routes (say 50), and then return via bidirectional streaming back to the mobile client the intermittent responses received by random AWS Lambda functions that respond with events to the consumed sensor stream from the mobile client.

Is this doable with Envoy Gloo?

**Comment by rickducott** [comment]
Adding the Question label - we first need to see if this is feasible.
