### ISSUE TITLE
ingress deployment chart doesn't respect ingress.deployment.resources values

### ISSUE THREAD

**Issue by sergeykonkin** [solo-io/gloo#2580]
there is no `resources` section in `10-ingress-deployment.yaml` at all, so I cannot set requests/limits via my custom `gloo-values.yaml`.

**Comment by kdorosh** [comment]
Another workaround is to leverage kustomize for any helm customizations you'd like to make to our chart until we have a chance to expose every setting that's requested. For more, read here: https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/helm_advanced/
