### ISSUE TITLE
Implement backoff for discovery

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2584]
https://github.com/solo-io/gloo/blob/master/projects/discovery/pkg/fds/discoveries/swagger/swagger.go#L35

This is filling up my logs.  Please consider implementing @yuval-k 's note.

**Comment by rickducott** [comment]
Hey @derrickburns , could you clarify the logging you want to reduce?

**Comment by derrickburns** [comment]
The logging is on my side.
