### ISSUE TITLE
Gloo security docs improvements

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2586]
- [x] Broken section at the bottom of the OPA doc: https://docs.solo.io/gloo/latest/security/opa/
![image](https://user-images.githubusercontent.com/27434432/76542906-1a588880-645c-11ea-8918-deca28e57448.png)

- [x] Server and upstream TLS docs are elsewhere: 
![image](https://user-images.githubusercontent.com/27434432/76544133-ec744380-645d-11ea-905a-32c3ebfefd87.png). They should probably live near the gloo mtls doc inside the security section. 

- [x] Clarify support for IP whitelisting

- [x] Ext auth section of security is currently all things related to ext auth, but these aren't all really security concerns. For instance, the consideration of whether to run ext auth as a sidecar or not feels somewhat orthogonal to security. 

- [x] Ext auth section contains custom auth subsection, which is confusing

- [x] Ext auth section includes stuff about JWT, which is actually an envoy filter rather than inside the extauth server

- [x] It is not clear how / when different auth configs can share context. Specifically right now it seems that the OIDC and OPA plugins are the only ones that do right now

**Comment by ned1313** [comment]
For the IP whitelisting, is this specifically in reference to the Ext Auth plugin doc? Or is there a large context we need to deal with?

**Comment by lgadban** [comment]
Hi @ned1313 -- I recently had to work through a IP whitelisting situation and took a stab at documenting a solution. I had some trouble fitting it into the rest of the WAF docs.

See: https://github.com/solo-io/gloo/pull/2964
