### ISSUE TITLE
Support extraAnnotations on all services, resource limits on all deployments in our helm charts

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2587]
These keep coming up as one-offs

**Comment by rickducott** [comment]
Related to https://github.com/solo-io/gloo/issues/2580

**Comment by kdorosh** [comment]
open-source user started the work here: https://github.com/solo-io/gloo/pull/2723, check the status of this PR before starting work.

if the PR isn't done, we should close and open our own PR (borrowing heavily from the work that has already been done), and thank the user for the contribution.
