### ISSUE TITLE
Unable to set SNI domains for petstore example

### ISSUE THREAD

**Issue by emaincourt** [solo-io/gloo#2609]
Hi,

I am currently trying to migrate some of my services to Gloo and I am facing several issues when it comes to TLS setup. My issues are easily reproducible with the [Petstore example](https://docs.solo.io/gloo/latest/gloo_routing/tls/server_tls/):

**Steps to reproduce**

```bash
$ kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml
$ glooctl add route \
    --path-exact /sample-route-1 \
    --dest-name default-petstore-8080 \
    --prefix-rewrite /api/pets
```

Up to that point, we are able to `curl $(glooctl proxy url --port http)/sample-route-1` and get a proper response from our service:

```json
[{"id":1,"name":"Dog","status":"available"},{"id":2,"name":"Cat","status":"pending"}]
```

Then, we try to setup TLS:

```bash
$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
   -keyout tls.key -out tls.crt -subj "/CN=petstore.example.com"
$ kubectl create secret tls gateway-tls --key tls.key \
   --cert tls.crt --namespace gloo-system
$ glooctl edit virtualservice --name default --namespace gloo-system \
   --ssl-secret-name gateway-tls \
   --ssl-secret-namespace gloo-system \
   # I add the line below to explicitely set SNI domains for the VS
   --ssl-sni-domains petstore.example.com 
```

Then, if we try to reach our service with `curl -k $(glooctl proxy url --port https)/sample-route-1 -H 'Host: petstore.example.com'`, we get:

```bash
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to {xxxx}-{xxxx}.eu-west-3.elb.amazonaws.com:443
```

If we remove the `--ssl-sni-domains` line when patching the `VirtualService`, everything works fine. Maybe am I missing something here but as far as I know, this example should work.

Please find below the complete `VirtualService` manifest after running all the commands:

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
spec:
  sslConfig:
    secretRef:
      name: gateway-tls
      namespace: gloo-system
    sniDomains:
    - petstore.example.com
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: /sample-route-1
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
status:
  reported_by: gateway
  state: 1
  subresource_statuses:
    '*v1.Proxy.gloo-system.gateway-proxy':
      reported_by: gloo
      state: 1
```

Could anyone give me some more details about this behaviour ? Is it expected ?

Thank you in advance

**Comment by rickducott** [comment]
Hi @emaincourt this sounds similar to an issue I was seeing: https://github.com/solo-io/gloo/issues/2534

**Comment by emaincourt** [comment]
@rickducott absolutely. Thank you for your answer. I saw this issue as well but was not sure we were both talking about the same. I'm gonna close this one and ask my question in #2534 !
