### ISSUE TITLE
Happypath test flake

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#264]
https://console.cloud.google.com/cloud-build/builds/629a091a-5c81-45ec-b224-341a485f25ae?project=solo-public&authuser=1

**Comment by rickducott** [comment]
Did not fail on another build for the same commit: https://console.cloud.google.com/cloud-build/builds/bdd94af2-71b9-498e-a83f-24ba407aa0b6?project=solo-public&authuser=1

**Comment by rickducott** [comment]
Happened on a release build: https://console.cloud.google.com/cloud-build/builds/f1d9d7fa-eaf7-4a21-a87e-9226e2ab9cf8?project=solo-public&authuser=1

**Comment by EItanya** [comment]
Happened on a branch https://console.cloud.google.com/cloud-build/builds/422e965a-1f4d-40cd-9bcf-db1a8ccbf5a7?project=solo-public

**Comment by rickducott** [comment]
Tried increasing timeout in #324 we'll see if it reduces the frequency of this flake

**Comment by marcogschmidt** [comment]
Randomly passed/failed on different commits (unrelated to the test code) on [this PR](https://github.com/solo-io/gloo/pull/424/commits). [Example of failed build](https://console.cloud.google.com/cloud-build/builds/5dc96c78-d918-4d39-a4ac-b993cd8bed9e?project=solo-public).

**Comment by ilevine** [comment]
this seems working
