### ISSUE TITLE
Allow customization of EnvoyClusterName in Grafana dashboards

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2640]
Have .EnvoyClusterName in observability code updated as serviceNamespace-serviceName-servicePort_$namespace ($namespace) will be filled dynamically through UI.

Be able to configure the elements of the following, specifically  t.upstream.Metadata.Namespace

return fmt.Sprintf("%s-%s-%d_%s", kube.ServiceNamespace, kube.ServiceName, kube.ServicePort, t.upstream.Metadata.Namespace)

**Comment by kdorosh** [comment]
Following up with customer to confirm, but current understanding is that their grafana queries make use of grafana variables, and they would like the chart name to be created/match the same `$cluster_name` variable.

**Comment by bdecoste** [comment]
The requirement is to be able to deconflict dashboards based on environment. For example, serviceNamespace-serviceName-servicePort_namespace_envId where envId is something assinable to identify the env and deconflict dashboards from multiple envs
