### ISSUE TITLE
support conditional logging 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2644]
e.g. log based on the existence of a request header&value

**Comment by rickducott** [comment]
What kind of logging are we talking about? In the envoy gateway-proxy container logs? Access logs?

**Comment by rickducott** [comment]
Seems like a duplicate of https://github.com/solo-io/gloo/issues/2461

**Comment by bdecoste** [comment]
Access logs and envoy debug logs - the ability to enable logging for individual requests based on a header. Related to https://github.com/solo-io/gloo/issues/2251
