### ISSUE TITLE
allow not specifying replicas

### ISSUE THREAD

**Issue by yuval-k** [solo-io/gloo#2650]
to use gloo with the hpa and flux, we need to be able to omit replicas from the spec

https://docs.fluxcd.io/en/1.18.0/faq.html#how-can-i-prevent-flux-overriding-the-replicas-when-using-hpa

this should be done for:

- [X] envoy
- [ ] ext auth
- [ ] rate limit
- [ ] redis (note: to scale this we'll need a variation of this: https://github.com/solo-io/solo-projects/pull/1294)

**Comment by kdorosh** [comment]
we should do this with all the commonly scaled components (including the gloo enterprise data plane ones)

**Comment by kdorosh** [comment]
fixed in glooe components, still need those changes made to the open-source gloo
