### ISSUE TITLE
Allow annotations for certgen job

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2665]
Can you please allow me to add an annotation to the certgen job?

I need this to disable sidecar injection from linkerd. 

As it stands, I cannot update gloo using helm because the certgen job is injected with a sidecar.  This means that Kubernetes never deletes the job because I am on EKS where the TTLAfterFinished  alpha feature is not enabled. So, when helm3 tries to install, it fails because the job exists. 

With an annotation, I can disable sidecar injection for the job.  Without the annotation, the job follows the configuration for the namespace, which I choose to label for sidecar injection, since all the services in it need that.

**Comment by nathan-vp** [comment]
Also hitting this issue.

Ideally, the Helm chart should allow to set labels and/or annotations on every resource, as best practice. I guess this can be covered in https://github.com/solo-io/gloo/issues/2705

For now, allowing annotations on the certgen job is the most urgent for us Linkerd users.

**Comment by kdorosh** [comment]
Another workaround is to leverage kustomize for any helm customizations you'd like to make to our chart until we have a chance to expose every setting that's requested. For more, read here: https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/helm_advanced/

**Comment by derrickburns** [comment]
Sadly, none of the k8s tools are composable. :(

**Comment by jenshu** [comment]
once the OSS PR is merged and released, we need to make the same change to the [gloo-ee-resource-rollout job](https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/templates/70-resource-rollout-job.yaml) (can just copy from the gloo-resource-rollout job and use the values from `.Values.gloo.gateway.rolloutJob`)

**Comment by jenshu** [comment]
reopening for enterprise changes
