### ISSUE TITLE
verbose discovery logs at info level

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2668]
A lot of info level logs that keep reconciling upstreams and arriving at the same number.

**Comment by kdorosh** [comment]
Is this in discovery? I think another approach here is to skip the reconcile loop if upstreams hash to the same number. (shouldn't this already be the case?)

**Comment by rickducott** [comment]
Yup exactly. Debugging an issue with a customer and they had a ton of these logs generated constantly.

**Comment by kdorosh** [comment]
fwiw, i started making changes to address that here: https://github.com/solo-io/gloo/pull/2653/files in `projects/gloo/pkg/plugins/kubernetes/uds.go`. While I think this would solve the problem, it may increase CPU use and we may want to prevent the watch from firing altogether, or catch it in the emitter instead.
