### ISSUE TITLE
Improve ux for glooctl

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#267]
Right now, upstreams created by the discovery service live in the `gloo-system` namespace. When we do `glooctl get upstream` we see these upstreams (note, this is without passing in the namespace as a param; it seems `glooctl` will automatically search that namespace. 

However, if I do the same thing for a specific upstream like:

```
glootctl get upstream default-petstorer-8080
```

It won't work unless I specify the namespace explicitly' `-n gloo-system` 

This experience is inconsistent and inconvenient.

It'd be nice if `glooctl` always looks in the `gloo-system` namespace (as that's where all the automatically discovered upstreams will go) without having to specify the namespace. It would also be intuitive for a user for them to also see the resources in their namespace. 

When we operate on resources like VirtualService/Upstream, etc that it takes into account gloo-system automatically but also the namespace specified in the kubeconfig (that the user would expect).

Thoughts?

**Comment by ilackarms** [comment]
the way i imagine the users config would look like:

```
gloo-system                default
[x]                              [x]
 |                                |
read in discovery crds     read in user crds
 |                                |
________________________________
               |
<combined user configuration>
```

the stuff in `gloo-system` is created by discovery, and has shared read access amongst users
these are mostly just kubernetes upstreams
as well as consul and any other discovery we eventually support
then, the user puts the `deployment`, `service`, `virtualservice` in their own namespace (the first 2 being their regular kubernetes resources)
the virtualservice can reference upstreams from `gloo-system`

**Comment by ilevine** [comment]
This seems to work in recent version of glooctl; please re-open if needed.
