### ISSUE TITLE
store log level as a setting

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2674]
We should have a setting to adjust log level. We need the log level to persist across restarts, otherwise the debug workflow is pretty annoying. This would be useful for all our components, though it's most likely that users would be debugging something like extauth, where a lot of the complex business logic lives.

**Comment by rickducott** [comment]
There was some feedback NOT to do this, potentially it's helpful to be able to delete the pod to be able to clear the debug state. Alternatively, we could provide a flag to the container that can start the process in debug mode.

**Comment by lgadban** [comment]
>Alternatively, we could provide a flag to the container that can start the process in debug mode.

+1 to this option
This is particularly useful for `extauth`, but would be useful for all Gloo components.
