### ISSUE TITLE
BUILD.md still talks about go dep

### ISSUE THREAD

**Issue by sandromlp** [solo-io/gloo#2676]
Gloo already uses go mod, but still has a description about dep in the BUILD.md:

Gloo uses [go dep](https://github.com/golang/dep) for dependency management. Ensure you have it installed and run `dep ensure -v` from the `gloo` src directory:

```bash
go get -u github.com/golang/dep/cmd/dep
dep ensure -v
```

**Comment by ned1313** [comment]
The `dep ensure -v` has already been removed from the BUILD.md file.

**Comment by sandrom** [comment]
> The `dep ensure -v` has already been removed from the BUILD.md file by Kevin on #2686

Hey Ned,

indeed, it has been picked up right after and I totally forgot about this issue about it. Thanks for taking care! :)
