### ISSUE TITLE
Various links broken in gateway.proto docs

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#2691]
On the [`gateway.proto`](https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk) API reference docs, the following links are broken:

- `httpGateway` (Links to type: `.gateway.solo.io.HttpGateway`)
- `tcpGateway` (Links to type `.gateway.solo.io.TcpGateway`)
- `options` (Links to type `.gloo.solo.io.HttpListenerOptions`)
- `tcpHosts` (Links to type `[]gloo.solo.io.TcpHost`)
- `options` (Links to type `.gloo.solo.io.TcpListenerOptions`)

**Comment by ned1313** [comment]
Links have been fixed.
