### ISSUE TITLE
Improve usability, reduce verbosity of rate limit config

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2695]
Currently we need to enumerate all the combinations of rate limit attributes in the configuration to better handle cases where you are dealing with attribute subsets. This can be generated, but the config becomes very verbose and the generation is left to the user.

**Comment by kdorosh** [comment]
Tasks remaining:
(In Gloo Enterprise)
- [ ] Add plugin code to translate new API to expected format, ~1/2 day to day
- [ ] Add plugin unit tests (proper translation, error on special generic key), ~1/2 day to day
- [ ] e2e test (not a k8s regression test) ~1-1.5 days
(In rate-limiter)
- [ ] write a measure benchmark test to ensure that the new code is not slower than the old code (tree-based logic) ~ 1/2 day to day
- [ ] write a benchmark test to compare the set logic speed to the tree based logic ~1/2 day to day
