### ISSUE TITLE
Expose tcp keepalive in helm chart to address 503 after node restarts

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2702]
User reported in slack:

> 
> Is Gloo supposed to survive node reboots? We are testing gloo in EKS and almost everytime we terminate node (gloo or some service restarts in another node) routing to that service fails. No errors in any logs, upstreams and virtual services seem ok but gateway-proxy returns 503 Service Unavailable.
> This gets fixed immediately if we delete gateway-proxy pod.
> 10:59
> we are using version 1.3.14

**Comment by yuval-k** [comment]
one possible way for this to happen:
restarting the node triggers a half open tcp connection. i.e. envoy thinks it is still connected to gloo.
if the target service was also moved to a different node, this will happen.
a solution is to adjust the tcp keepalive to match your environment needs (the default are somewhat conservative, at 2 hours)

**Comment by hscheib** [comment]
I also experienced this yesterday for the first time returning constant 503s on `gloo: 1.3.12` 

We identified an EKS node terminated at that time and for 15-20 minutes 503s were returned. Somehow the problem automatically resolved it self after the 15-20minutes. We did not delete any gloo pods.

Access logs show `response_flags UF`

**Comment by yuval-k** [comment]
it does sound like a similar problem. There is no way to really solve these kind problems in distributed systems. We can however tune some settings to minimize its impact - i suggest setting more aggressive tcp keep alive settings, and adding re-tries and health checks.

**Comment by kari-awake** [comment]
I modified tcpkeepalive settings and it seems that issue is now fixed.

**Comment by hscheib** [comment]
> I modified tcpkeepalive settings and it seems that issue is now fixed.

I am using the helm chart to install Gloo. Is this possible with helm install? 

I see this PR adding it https://github.com/solo-io/gloo/pull/708/files#diff-3223834406a9911afe22cb9668e6748f

But I don't see any param in template-values.yaml that I can pass to adjust the keep alive setting.

Am I missing something? or is there an example of your config to share thanks

**Comment by rickducott** [comment]
Leaving this open to address that we should improve the helm chart to expose this value.

**Comment by kdorosh** [comment]
Another workaround is to leverage kustomize for any helm customizations you'd like to make to our chart until we have a chance to expose every setting that's requested. For more, read here: https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/helm_advanced/

**Comment by tkukushkin** [comment]
@kdorosh how can I kustomize yaml inside yaml in gateway-proxy-configmap? Currently i can only rewrite config entirely, but this solution is hard to support, I have to check diff of configmap on every gloo update and apply patches to my copied config.

**Comment by kdorosh** [comment]
@tkukushkin we have documented a sample kustomize flow here: https://docs.solo.io/gloo-edge/latest/installation/gateway/kubernetes/helm_advanced/

let me know if this helps

**Comment by tkukushkin** [comment]
@kdorosh i understand, but envoy.yaml is yaml as string inside another yaml. I don't know how to kustomize it.

As a workaround we use such script in kustomize.sh:

```bash
# extract envoy.yaml to file
$yq eval 'select(.metadata.name == "gateway-proxy-envoy-config") | .data."envoy.yaml"' "$current_dir/base/all.yaml" > "$current_dir/envoy.yaml"

# add keepalive settings
$yq eval-all -i \
  '(select(fileIndex==0) | .. | select(has("tcp_keepalive")) | .tcp_keepalive) = select(fileIndex==1) | select(fileIndex==0)' \
  "$current_dir/envoy.yaml" \
  "$current_dir/tcp_keepalive.yaml"

# add tracing configuration
$yq eval-all -i \
  'select(fileIndex==0).tracing = select(fileIndex==1) | select(fileIndex==0)' \
  "$current_dir/envoy.yaml" \
  "$current_dir/tracing.yaml"

# put new envoy.yaml to ConfigMap
ENVOY_YAML=$(cat "$current_dir/envoy.yaml") $yq eval -i \
  '(select(.metadata.name == "gateway-proxy-envoy-config") | .data."envoy.yaml") = strenv(ENVOY_YAML)' \
  "$current_dir/base/all.yaml" \
```
