### ISSUE TITLE
clarify docs around Gloo on flat files

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2709]
The docs were written awhile ago when the Gloo on flat files and docker compose was mostly a dev convenience. We now have customers looking at it and we should update the docs.

**Comment by ned1313** [comment]
Docs have been updated with the following language:

> The deployment steps in this tutorial are for demonstration and learning on a local machine. If you are interested in running a production deployment of Gloo using flat files, you will likely want to change the deployment architecture from how it is described in this guide. If you are an enterprise customer, please contact us for assistance!
