### ISSUE TITLE
Support Nested Claims in JWT RBAC

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#2744]
**Enhancement request to extend the RBAC implementation to support nested claims**

Currently the JWT Principal used in the RBAC flow only supports single-level claims, i.e. non-nested claims.

```
"claims": map<string, string>
"provider": string
```
https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/rbac/rbac.proto.sk/#jwtprincipal

In some instances, a custom claim can utilize nested claims, e.g. --
```
{
  "sub": "1234567890",
  "name": "John Doe",
  "iat": 1516239022,
  "role": {
     "read": "true",
     "write": "false"
  }
}
```
This JWT can not accurately be expressed as an RBAC policy.

**Comment by chrisgaun** [comment]
List may be sufficient. Nested claims would be the superset issue that would solve all issues.
