### ISSUE TITLE
swagger.json not detected

### ISSUE THREAD

**Issue by ghost** [solo-io/gloo#2746]
I have a valid swagger.json file located at "/v1/swagger/swagger.json"

According to this file the location should be supported. https://github.com/solo-io/gloo/blob/master/projects/discovery/pkg/fds/discoveries/swagger/swagger.go

```
var commonSwaggerURIs = []string{
	"/swagger.json",
	"/swagger/docs/v1",
	"/swagger/docs/v2",
	"/v1/swagger",
	"/v2/swagger",
}
```

I have enabled discovery with 
```
kubectl label namespace apis discovery.solo.io/function_discovery=enabled
```

Swagger is not detected:

```
glooctl get upstreams apis-my-api-service-5000 --output yaml
---
discoveryMetadata: {}
kube:
  selector:
    app: my-api
  serviceName: my-api-service
  serviceNamespace: apis
  servicePort: 5000
metadata:
  annotations:
   REMOVED
  generation: "2"
  labels:
    app: my-api
    discovered_by: kubernetesplugin
  name: apis-my-api-service-5000
  namespace: gloo-system
  ownerReferences: []
  resourceVersion: "18584927"
status:
  reportedBy: gloo
  state: Accepted
```

**Comment by devkws** [comment]
I would also like to mention that the default location for the swagger.json in .netcore is "/swagger/v1/swagger.json"

It can be modified of course, but it would be nice if the default was supported by Gloo.

**Comment by devkws** [comment]
Update:

Patching your upstream with the swagger location is a workaround for this issue.

```
spec:
  kube:
    serviceSpec:
      rest:
        swaggerInfo:
          url: http://my-api-service.apis.svc.cluster.local:5000/swagger/v1/swagger.json
```

**Comment by Goend** [comment]
but the url: http://my-api-service.apis.svc.cluster.local:5000/swagger/v1/swagger.json，why envoy dont  acting for the service url?

**Comment by Goend** [comment]
![image](https://user-images.githubusercontent.com/40394339/83107494-fa4a7400-a0f0-11ea-94ba-799cb7b61f55.png)

**Comment by Goend** [comment]
@devkws

**Comment by devkws** [comment]
@Goend sorry I’m not sure what you mean. By patching the upstream function discovery will work correctly for you to reference in your virtual service.

**Comment by Goend** [comment]
k8s ipvs result no update,now it's was resolved

**Comment by Goend** [comment]
thanks a lot

**Comment by Goend** [comment]
But now there is a new question, how do I verify the parameters of custom upstream, for example, take www.google.com as upstream .but i want set some defaut parameter ，www.google.com/parameter,default parameter==1.

**Comment by Goend** [comment]
@devkws

**Comment by devkws** [comment]
@Goend For that, I would probably use prefix rewriting. Take a look and see if that does what you want. 

https://docs.solo.io/gloo/1.0.0/gloo_routing/virtual_services/routes/routing_features/prefix_rewrite/

**Comment by Goend** [comment]
That's not what I want. I  configure the io.solo.transformation to change the request path now, but the template syntax is too simple. I can't directly manipulate the corresponding parameters from the path header, which is humiliating

**Comment by Goend** [comment]
@rickducott  Oh,Can you help me about this issue, thanks a lot

**Comment by Goend** [comment]
i got it, thanks a lot
