### ISSUE TITLE
support referencing a secret for requestHeadersToAdd

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2751]
To enable sending credentials in a request header to the endpoint

**Comment by yuval-k** [comment]
do note that these won't be redacted in envoy access logs

**Comment by lgadban** [comment]
Not completely related to this enhancement, but I've also seen a desire to reference e.g. secrets or configmaps in other filters/plugins.

If implemented in a more general way, it could be useful to be able to utilize an artifact to populate e.g. dynamic metadata.

So for this specific request--populate metadata from a secret, utilize that metadata in `requestHeadersToAdd`

**Comment by rickducott** [comment]
Here's a related issue: https://github.com/solo-io/gloo/issues/2657

**Comment by kdorosh** [comment]
Another related issue (recently resolved) https://github.com/solo-io/gloo/issues/2914

We should be able to reuse the API added here: https://github.com/solo-io/solo-kit/pull/369
