### ISSUE TITLE
glooctl version discrepancy warning with most recent enterprise version

### ISSUE THREAD

**Issue by law10k** [solo-io/gloo#2769]
`glooctl` will show a version warning when using the most recent version of Gloo Enterprise.

```
% glooctl get vs
----------
glooctl binary version (1.4.0-beta2) differs from server components (v1.3.19) by at least a minor version.
Consider running:
glooctl upgrade --release=v1.3.19
----------
```

What are the options for using `glooctl` with Gloo Enterprise without seeing this warning for every command?

Seems to be related to https://github.com/solo-io/gloo/issues/1852 as well

**Comment by lgadban** [comment]
The recommended command `glooctl upgrade --release=v1.3.19` is correct, as it will set the glooctl version to match the correct server-side version, even if the server is running Gloo Enterprise

**Comment by law10k** [comment]
Not an issue
