### ISSUE TITLE
need to set securityContext on gateway proxy

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2777]
To work around networking issues, I need to set a security context on the gateway proxies. However, the current helm chart does not allow me to do that.

Can you please modify the helm chart to enable me to provide a security context on the Pod (not on the container).

Thanks!

**Comment by kdorosh** [comment]
Are the pods receiving different security policies, or the same one? We could add it to the deployment

**Comment by derrickburns** [comment]
Same policy for all pods.

**Comment by jenshu** [comment]
closing in favor of https://github.com/solo-io/gloo/issues/7473 which will cover all pods
