### ISSUE TITLE
Add loadBalancerIP field to knative-external-proxy

### ISSUE THREAD

**Issue by jvdgeest** [solo-io/gloo#2778]
The `gateway-proxy` can be configured with a `loadBalancerIP` (see: https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/8-gateway-proxy-service.yaml#L52).

It would be nice to add the same type of configuration to the `knative-external-proxy`. It currently does not allow you to define a `loadBalancerIP` (see: https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/28-knative-external-proxy-service.yaml), you have to manually patch/apply this after deployment.

Why would this be useful? If you have a static IP address (lets say, from a cloud provider), it is handy to configure a proxy service with this IP address, instead of getting a dynamic allocated IP address.

I can try to contribute and submit a merge request if you think this is a good idea.

**Comment by rickducott** [comment]
Sure, we'd welcome a pull request. Thanks!

**Comment by jvdgeest** [comment]
Thanks! I have just created a wip pull request: https://github.com/solo-io/gloo/pull/2825
