### ISSUE TITLE
Expose rate limit counters in response headers

### ISSUE THREAD

**Issue by ghost** [solo-io/gloo#2785]
Feature request to expose more rate limiting information in the response headers for clients.

Currently only a header for specifying you have been rate limited is returned.

It would be nice to have more default information provided.

Example:

```
X-RateLimit-Limit-Second: 5
X-RateLimit-Remaining-Second: 4
X-RateLimit-Limit-Minute: 10
X-RateLimit-Remaining-Minute: 9
```

**Comment by rickducott** [comment]
For future reference, one workaround is to introspect redis, for instance like this:

* `kubectl port-forward -n gloo-system deploy/redis 6379`
* `redis-cli` (requires installing tool) to login to redis
* `scan 0` to show all active counters
* `get NAME` to see value of counter

**Comment by rickducott** [comment]
convenient bash script for printing all the key-value pairs:
```
for key in $(redis-cli -p 6379 keys \*);
  do echo "Key : '$key'"
     redis-cli -p 6379 GET $key;
done
```

**Comment by yuval-k** [comment]
this will require a change to the rate limit filter; the server itself returns the limits but the envoy filter ignores them

**Comment by marcogschmidt** [comment]
Update from [this Slack conversation](https://solo-io.slack.com/archives/C9L6VPAUW/p1594674733226300): seems like the Envoy RL API [allows](https://github.com/envoyproxy/envoy/blob/7abb0e0bbed4f6b6304403b93762614ad385f80d/api/envoy/service/ratelimit/v3/rls.proto#L125) sending custom headers downstream.

**Comment by OcamsRazor** [comment]
Interested in this as well 👍

**Comment by kevin-shelaga** [comment]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto.html

```
enable_x_ratelimit_headers

    (extensions.filters.http.ratelimit.v3.RateLimit.XRateLimitHeadersRFCVersion) Defines the standard version to use for X-RateLimit headers emitted by the filter:

        X-RateLimit-Limit - indicates the request-quota associated to the client in the current time-window followed by the description of the quota policy. The values are returned by the rate limiting service in current_limit field. Example: 10, 10;w=1;name=”per-ip”, 1000;w=3600.

        X-RateLimit-Remaining - indicates the remaining requests in the current time-window. The values are returned by the rate limiting service in limit_remaining field.

        X-RateLimit-Reset - indicates the number of seconds until reset of the current time-window. The values are returned by the rate limiting service in duration_until_reset field.

```

**Comment by djannot** [comment]
We have another customer interested in this feature to be able to add a header to indicate which rate limit config has triggered this 429

**Comment by kevin-shelaga** [comment]
@djannot X-RateLimit-Limit does have the policy name it seems, or were you thinking something closer to our rateLimitConfig name?

X-RateLimit-Limit - indicates the request-quota associated to the client in the current time-window followed by the description of the quota policy. The values are returned by the rate limiting service in current_limit field. Example: 10, 10;w=1;name=”per-ip”, 1000;w=3600.

**Comment by chrisgaun** [comment]
We also need to include the standard Envoy headers

**Comment by guydc** [comment]
@chrisgaun - can this feature be ported to 1.11?
