### ISSUE TITLE
Provide a tool for resource validation

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#2798]
Currently, there is no way to get instant feedback/validation on a piece of Gloo resource configuration.

In other words, you must apply a resource to a cluster in order to "validate" the config, either through the validating webhook or `glooctl check`.

A tool should be provided that will allow instant feedback of the validity of a Gloo resource without needing to apply it to a Kubernetes cluster. This also allows for a CI/CD pipeline to enforce the validity of a resource before applying it.

Ideally, this would augment the existing `glooctl check` , possibly by being able to pass a config, e.g. `glooctl check -f my-virtual-service.yaml`

**Comment by lgadban** [comment]
Somewhat related to https://github.com/solo-io/gloo/issues/2114, although this specific request is more for "static" validation of the input object, e.g. a given YAML blob containing an `Upstream` is a valid `upstream.proto`

**Comment by kdorosh** [comment]
Not planned or designed, as the validation API accomplishes much the same thing more completely.
