### ISSUE TITLE
support additional telemetry dimensions

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2804]
Telemetry requirements:
 - Metrics:
    - [x] Request_Count; exists as `upstream_rq_total`
      - e.g. `cluster.default-petstore-8080_gloo-system.upstream_rq_total: 7`
      - in prom form, `envoy_cluster_upstream_rq_total{envoy_cluster_name="default-petstore-8080_gloo-system"} 7
`
    - [x] Downstream_Response_Time_Hist; exists as `downstream_rq_time`
      - .e.g, `http.admin.downstream_rq_time: P0(nan,0.0) P25(nan,5.03929) P50(nan,26.6076) P75(nan,29.2821) P90(nan,32.6118) P95(nan,37.075) P99(nan,53.18) P99.5(nan,65.545) P99.9(nan,112.18) P100(nan,500.0)
`
      - in prom form, `# TYPE envoy_http_downstream_rq_time histogram
envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix="admin",le="0.5"} 3 ...`
    - [x] Upstream_Response_time_Hist; exists as `upstream_rq_time`
       - e.g., `cluster.default-petstore-8080_gloo-system.upstream_rq_time: P0(nan,0.0) P25(nan,0.0) P50(nan,0.0) P75(nan,1.0125) P90(nan,1.065) P95(nan,1.0825) P99(nan,1.0965) P99.5(nan,1.09825) P99.9(nan,1.09965) P100(nan,1.1)`
       - in prom form, 
```
# TYPE envoy_cluster_upstream_rq_time histogram
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="0.5"} 5
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="1"} 5
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="5"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="10"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="25"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="50"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="100"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="250"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="500"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="1000"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="2500"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="5000"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="10000"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="30000"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="60000"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="300000"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="600000"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="1800000"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="3600000"} 7
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="default-petstore-8080_gloo-system",le="+Inf"} 7
envoy_cluster_upstream_rq_time_sum{envoy_cluster_name="default-petstore-8080_gloo-system"} 2.1000000000000000888178419700125
envoy_cluster_upstream_rq_time_count{envoy_cluster_name="default-petstore-8080_gloo-system"} 7
```

-  Dimensions/Labels:
    - [ ] Cluster.   - already in access logs, `%UPSTREAM_CLUSTER%`
    - [ ] Namespace. - can do with virtual cluster (also `%ROUTE_NAME%` may be sufficient)
    - [ ] VirtualService_Name.  - can do with virtual cluster (also `%ROUTE_NAME%` may be sufficient)
    - [ ] Base_Path.  - belongs in access logs, can do with virtual cluster
    - [ ] Route (Operation_Path).   - belongs in access logs, `%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%` is close
    - [ ] Upstream_Name (Host).    - already in access logs, `%UPSTREAM_HOST%`
    - [ ] Client_ID.   (mostly from JWT token) - be able to add any jwt claim to access logs. could use jwt `claimsToHeaders` and then log the header (also could use dynamic metadata set in the filter)
    - [ ] request/response body in access logs, can use transformation to put this in dynamic metadata and thus in access logs. in our jwt filter its actually already in dynamic metadata (as opposed to upstream jwt)
    - [ ] Response_Code, in access logs `%RESPONSE_CODE%`

see [envoy stats docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats) for reference on the metrics that already exist.

we can also leverage [virtual clusters](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#route-virtualcluster) to get additional granularity.

users can output the necessary information to access logs and then export to prometheus.

**Comment by rickducott** [comment]
Plan = augment grpc access log server to publish additional metrics based on access log.
