### ISSUE TITLE
zero downtime upgrade requires removal of settings and gateway resources

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2807]
This removes any custom config in settings and gateway resources which causes all sorts of problems including downtime.

**Comment by kdorosh** [comment]
https://github.com/helm/helm/pull/7649 looks like a promising approach to fix this, so we can adopt the old resources

**Comment by kdorosh** [comment]
there's nothing better we can do until helm merges that upstream change, and even then we will still need our currently documented steps for helm 2 users. just opted to clarify the risk of doing the upgrade wrong in the docs

**Comment by kdorosh** [comment]
the only alternative is we could tell users to NOT generate new gateways and settings via helm values, but then they will need to do this indefinitely and those resources will never be managed by helm.

further if they forget to add helm garbage collection annotations then those very important resources are at risk of being cleaned up by future versions of helm

**Comment by rickducott** [comment]
Reopening - helm 3.2.0 released and we should see if we can leverage a new feature to adopt these resources rather than require deletion.
