### ISSUE TITLE
glooctl check hangs at 'Checking secrets' when missing permissions

### ISSUE THREAD

**Issue by iisimaginary** [solo-io/gloo#2820]
I don't have RBAC access to all the secrets in the k8s cluster.  Instead of getting an error, glooctl check just hangs at Checking secrets.  I would hope at least I would get an error telling me I don't have permissions.  At best, glooctl check would try to check everything I can access, and give feedback about that portion (and still fail the check because it could be ambiguous).

**Comment by rickducott** [comment]
Thanks @iisimaginary this makes sense. I will call it a bug for now, since the hanging behavior isn't expected and we could at least return an RBAC error message.
