### ISSUE TITLE
logs spammed with this error

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2830]
```
{"level":"error","ts":1587394261.232115,"logger":"gateway.v1.event_loop.gateway.validation-resync-notifications","caller":"validation/notification_channel.go:40","msg":"error reading from stream. attempting to establish new stream.","version":"1.3.21","error":"EOF","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/validation.MakeNotificationChannel.func1\n\t/workspace/gloo/projects/gateway/pkg/validation/notification_channel.go:40"}
```

I have this message a few hundred times when I run `glooctl debug logs --errors-only`. I don't see an issue in `glooctl check` and can't tell if this is a concern and what to do about it.

**Comment by yuval-k** [comment]
this looks like gateway trying to reach gloo for validation; @ilackarms may know more

**Comment by leosunmo** [comment]
Seeing the same thing from the gateway pod.
According to the code at https://github.com/solo-io/gloo/blob/53fa986a6ea2f5a3bb695a0763c40fd188b31a9a/projects/gateway/pkg/validation/notification_channel.go#L41 it should be restarting/re-establishing a new stream/connection but I don't get any more logs about the notification channel or any webhook/validation functionality after that first `error reading from stream. attempting to establish new stream` error.

This means that invalid VirtualService configs are let through (I know I can change the webhook failure mode, will have to re-evaluate that now) which in turn seems to break the gateway.
