### ISSUE TITLE
GlooUI - VirtualService route destinations unreadable 

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#2833]
In the Gloo Dashboard, on the modal window for creating a route for a VirtualService, the "Destination" drop-down is not wide enough to see the full name of the Upstreams.

Additionally, the field does not allow for typing to filter the upstream name.

See below screenshot:
![image](https://user-images.githubusercontent.com/1161279/79775394-cada6780-82f9-11ea-95f3-ee4087148659.png)

**Comment by rickducott** [comment]
Was fixed on GlooE master and 1.3.x branches
