### ISSUE TITLE
make build on latest pull from master branch fails

### ISSUE THREAD

**Issue by PinchasLev** [solo-io/gloo#2853]
When pulling from master today and subsequently running make build, I get an error:

>> build command-line-arguments: cannot load github.com/solo-io/gloo/projects/gloo/pkg/api/v2/enterprise/plugins/ratelimit: no matching versions for query "latest"

**Comment by kdorosh** [comment]
@PinchasLev I was unable to reproduce, were you perhaps trying to download yesterday when github was experiencing downtime>? (~11am-1pm EST)

**Comment by rickducott** [comment]
Curious why "v2" is in the error message there, do you have your own API definitions?

**Comment by PinchasLev** [comment]
Evidently, I haven't been pulling from master for awhile, and when I finally pulled there were conflicts that I didn't resolve properly.  On top of that, in the interim months, the process changed slightly, requiring the installation of *protoc*.
Starting over by pulling a clean copy and following the instruction resolved the issue.
