### ISSUE TITLE
gloo-ee 1.3.3 prometheus PVC is in wrong namespace

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2860]
The namespace is missing in `gloo-ee/charts/prometheus/templates/server-pvc.yaml`:

```
{{- if .Values.server.enabled -}}
{{- if not .Values.server.statefulSet.enabled -}}
{{- if .Values.server.persistentVolume.enabled -}}
{{- if not .Values.server.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.server.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.server.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ template "prometheus.server.fullname" . }}
spec:
  accessModes:
{{ toYaml .Values.server.persistentVolume.accessModes | indent 4 }}
{{- if .Values.server.persistentVolume.storageClass }}
{{- if (eq "-" .Values.server.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.server.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.server.persistentVolume.size }}"
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

**Comment by derrickburns** [comment]
it also appears that the prometheus server and the kube-state-metrics service are not started in the proper namespace.

**Comment by kdorosh** [comment]
The latest stable prometheus chart has the same omission. https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-pvc.yaml

Where did you expect these services to start, and where did they start?

**Comment by derrickburns** [comment]
Ah. I expected them to start in the same namespave where I launched the gloo control plane, ie gloo-system.

Instead they start in the default namespace.

**Comment by derrickburns** [comment]
Yes, I do realize the omission is in the Prometheus chart.

**Comment by derrickburns** [comment]
I have dozens of packages I install. I  literally have nothing in my default namespace.

**Comment by yuval-k** [comment]
gloo pulls in the upstream chart, which doesnt have the namespace; with regular helm install it is not a problem as helm installs resources without a namespace to the release namespace.

so this problem manifests when doing helm template and kube apply separately.
i had a similar problem, and i fixed with with the help of kustomize,
i have the helm template output go into customize and i add `namespace: gloo-system` to my kustomization.yaml. kustomize will then add the namespace to all the resouces.

**Comment by derrickburns** [comment]
Yessir. That of exactly what I plan to do. Thx @yuval-k

**Comment by kdorosh** [comment]
sounds like we reached an acceptable explanation and path forward. going to close.
