### ISSUE TITLE
add missing descriptions for proto fields

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2872]
virtual host options
![image](https://user-images.githubusercontent.com/27434432/80250151-406b6e00-8641-11ea-92c4-805cdc2bc583.png)

**Comment by xuhui-lu** [comment]
@rickducott hello rick, I am interested in contributing to this project. May I pick this issue up?

**Comment by rickducott** [comment]
Hi @xuhui-lu I don't actually work in Gloo anymore, but I'm sure @kdorosh can help you out!

**Comment by kdorosh** [comment]
Hi @xuhui-lu , thanks for the interest in making a contribution! If you'd like to help us out with this, I'm happy to help review and get it through our ci process.

The docs are generated from proto comments, changes would have to be made to our protos (e.g. https://github.com/solo-io/gloo/blob/bdf0a52ddba14d959e41429e97a9b9d2469927bd/projects/gloo/api/v1/options.proto#L145). After the proto changes, we would need to run codegen and commit those changes as well.

Guide for setting up codegen: https://docs.solo.io/gloo/latest/guides/dev/setting-up-dev-environment/#enabling-code-generation
