### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by devkws** [solo-io/gloo#2881]
retryOn has a broken link (404) to envoy docs. 

https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/retries/retries.proto.sk/

It should probably match the retryOn docs listed here. 

https://docs.solo.io/gloo/latest/guides/traffic_management/request_processing/retries/

**Comment by rickducott** [comment]
I actually just ran into this and fixed it a few days ago: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/options/retries/retries.proto. We're trying to migrate all our links to versioned paths that won't break over time. However, the docs haven't been updated, will close this issue once we get the new container live.

**Comment by rickducott** [comment]
Fix is live now!
