### ISSUE TITLE
broken link to docs root

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2883]
Select 1.3.0 in version drop down, start navigating docs, then click on "Gloo" in the left-hand menu. It goes to a 404

**Comment by kdorosh** [comment]
Same problem occurs if you put in a bad url and then click "go to homepage", even on the latest version of the docs.

**Comment by kdorosh** [comment]
Also the solo.io docs label in the top left corner always redirects to the company site, which seems wrong.

**Comment by kdorosh** [comment]
closing as working as intended
