### ISSUE TITLE
upstream name validation

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#289]
when uds services generate names for the upstreams they create (consul, kubernetes) they are usually trying to do so with the names being unique. however names must be sanitized at least to be kubernetes compliant

this issue is meant to track the possibility that functions https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/kubernetes/uds.go#L171 may easily break and need improvements depending on the kind of names and labels written on kubernetes services

**Comment by ilevine** [comment]
The function referenced is now in:
https://github.com/solo-io/go-utils/blob/bb0009b14a67ee40cff9b7333de7d32fc31de3eb/kubeutils/util.go

we should add sanitization there.

**Comment by kdorosh** [comment]
The file referenced there has two sanitation functions. Is the sanitation there non-functional? Is the concern that the sanitation implementation there isn't future-proof? Or that two different supposedly unique EC2 endpoints get sanitized to the same k8s name? Please elaborate on the issue at hand a bit more -- thanks
