### ISSUE TITLE
untar mod cache flake

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2894]
seeing this sporadically on our CI, created a smaller cloudbuild to repro, logs here: https://console.cloud.google.com/cloud-build/builds/69a0598e-876f-4966-bd1a-950d9ceafe89?project=gloo-ee

happens even if its the only build running at that time

**Comment by GrahamGoudeau** [comment]
For the record, have seen this from service mesh hub CI as well

**Comment by GrahamGoudeau** [comment]
https://console.cloud.google.com/cloud-build/builds/022d7a40-47d3-46d9-aa94-3ef5b085bdbd?project=service-mesh-hub
