### ISSUE TITLE
Upgrade path with `glooctl` in docs doesn't work

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#2902]
The [docs for upgrading using glooctl](https://docs.solo.io/gloo/latest/operations/upgrading/upgrade_steps/#using-glooctl) don't work as written.

When you try to use `glooctl install` with an existing gloo installation, you get the following error:
```
% glooctl install gateway enterprise --license-key $GLOO_LICENSE_KEY --version 1.4.0-beta6
----------
glooctl binary version (1.4.0-beta6) differs from server components (v1.3.19) by at least a minor version.
Consider running:
glooctl upgrade --release=v1.3.19
----------

Error: installing Gloo Enterprise in gateway mode: Gloo has already been installed to namespace gloo-system
```

**Comment by rickducott** [comment]
Interested in improving the docs and wrapping the helm upgrade with a simple dev-oriented command via glooctl.

**Comment by rickducott** [comment]
We have seen issues with the `glooctl install gateway --dry-run` upgrade path, so we should just encourage upgrading with Helm.
