### ISSUE TITLE
Report better error when kube svc port doesn't match upstream port

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2905]
https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/kubernetes/eds.go#L191-L194

this could also be checking if the port from a single service matches the upstream.

i ran into this when configuring the extauth upstream to use port 8084 (unencrypted) but forgot to update the service port to 8084 as well.

there were no errors in the logs or on gloo resources. i would have expected both.

**Comment by arianaw66** [comment]
To reproduce:
1. Install Gloo: `glooctl install gateway`
2. Add petstore service and upstream: `kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml`
3. Create another upstream pointing to petstore: `glooctl create upstream kube --name test-upstream --kube-service petstore`

To see the problem:
- See that the service has port 8080: `kubectl get svc -A`
- But that the upstream has port 80 and is Accepted `glooctl get upstream test-upstream`
- And the gloo logs show no issues: `kubectl logs -n gloo-system deployments/gloo -f`

**Comment by arianaw66** [comment]
Closed by #3014
