### ISSUE TITLE
Requests Per Second query is wrong

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2919]
Is:

`(sum(irate(envoy_http_downstream_rq_total[1m])))`

Should be:
`(rate(envoy_http_downstream_rq_total[1m]))`
or
`(irate(envoy_http_downstream_rq_total[1m]))`

The former shows double the actual rate

**Comment by kdorosh** [comment]
>  This is something that comes out of the Envoy Statistics dashboard and I suspect there are other queries than are wrong. it's one of our built-in charts
