### ISSUE TITLE
current implementation of solo-kit doesn't permit use of the kubernetes `NamespaceAll`. 

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#292]
in order to watch all namespaces, we must watch each one individually
this requires a solo kit change as well as changes to UDS

**Comment by rickducott** [comment]
See also https://github.com/solo-io/solo-kit/issues/70

**Comment by yuval-k** [comment]
@rickducott  \ @ilackarms does the fix in solokit automatically fixes this?

**Comment by ilackarms** [comment]
in order to use `NamespaceAll`, pass `nil` into `watchNamespaces` for the eventloop

this will work for solo-kit resources, gloo may require some extra work for discovery (i believe discovery also leverages `watchNamespaces` but does not use solo-kit to do its watches)

**Comment by ilevine** [comment]
this works now
