### ISSUE TITLE
Gloo-ee: linkerd key is missing from Settings

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2930]
It appears that the settings template for `gloo-ee` 1.3.3 does not allow setting `linkerd: true`.  The one for `gloo` does.  This is the same through 1.4.0-beta5.

Is the `linkerd` key not used anymore, or this a simple oversight?

**Comment by rickducott** [comment]
This is an oversight, another casualty of duplicated settings templates in each helm chart.
