### ISSUE TITLE
Deterministic field ordering for accessLoggingService.accessLog.jsonFormat

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2931]
Currently the field ordering is non-deterministic:

```
{
  "addedHeader": "-",
  "headers": "-",
  "clientDuration": "1",
  "upstreamName": "default-petstore-8080_gloo-system",
  "remoteAddress": "75.50.123.82:64187",
  "responseCode": "200",
  "requestId": "8782e8d1-cb42-4074-a8a4-ce53b86f4c69",
  "routeAddedHeader": "-",
  "opaHeader": "-",
  "httpMethod": "GET",
  "systemTime": "2020-05-04T13:56:04.072Z",
  "targetDuration": "0",
  "path": "/api/pets",
  "protocol": "HTTP/1.1"
}
{
  "upstreamName": "default-petstore-8080_gloo-system",
  "remoteAddress": "75.50.123.82:64204",
  "responseCode": "200",
  "requestId": "51988056-14e2-478e-9b42-d0356491ebb5",
  "routeAddedHeader": "-",
  "opaHeader": "-",
  "httpMethod": "GET",
  "systemTime": "2020-05-04T13:56:12.698Z",
  "targetDuration": "1",
  "path": "/api/pets",
  "protocol": "HTTP/1.1",
  "addedHeader": "-",
  "headers": "-",
  "clientDuration": "1"
}
```

**Comment by rickducott** [comment]
The JSON spec doesn't guarantee an ordering of map elements. A solution here would most likely be some processing step in upstream Envoy to enforce an ordering on an unordered data structure, which would create some overhead and seems dubious (could be wrong - haven't been able to find discussion about this). 

We can work around this either by using string logging (the formatted string could still be json style), or by using a grpc access log service that outputs ordered json.

**Comment by yuval-k** [comment]
note that upstream envoy uses protobuf for json handling, so this an actually google/protobuf upstream PR (unless we change the way envoy handles json)

the workaround rick suggested sounds like a reasonable thing to do; can be combined with [--log-format-escaped](https://www.envoyproxy.io/docs/envoy/latest/operations/cli.html?highlight=escape#cmdoption-log-format-escaped)

**Comment by rickducott** [comment]
Discussed with Bill, closing as Won't Fix
