### ISSUE TITLE
Turning on gzip causes glooctl check to fail with 'unknown field "gzip" in v1.HttpListenerOptions'

### ISSUE THREAD

**Issue by yorudy** [solo-io/gloo#2937]
Gloo Server Version: 1.3.18 | Helm repo:  https://storage.googleapis.com/solo-public-helm
Gloo Server Platform: GKE (Google)
Gloo Client Version: 1.3.3
Gloo Client OS: Windows 10 Enterprise 1803
Kubernetes: 1.15.11-gke.1

### Summary
I enabled "gzip" compression in Gloo. The compression kicks in when a request comes in with the "Accept-Encoding: gzip" header. However, the `glooctl check` command now fails with the message: 

`converting output crd: reading crd spec on resource gateway-proxy-ssl in namespace gloo-system into v1Gateway: unknown field "gzip" in v1.HttpListenerOptions`

This is potentially, hiding any underlying problems that the gateway may have.
It may also impede abilty to use `glooctl check` in CI/CD actions for sanity checks after changes to gloo configurations -- e.g. new Virtual Service deployed.

### How to reproduce
1. Follow the instructions here to enable GZip and confirm working https://docs.solo.io/gloo/latest/installation/advanced_configuration/gzip/
2. run `glooctl check`
3. Observe error message in output related to Gateways: unknown field "gzip"

### Expected behavior
There should be no error message displayed when using glooctl check.

### Example Output
```
glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... Error!
converting output crd: reading crd spec on resource gateway-proxy-ssl in namespace gloo-system into v1Gateway: unknown field "gzip" in v1.HttpListenerOptions
```

**Comment by kdorosh** [comment]
What version of `glooctl` were you running? (i.e., what's the output of `glooctl version`?)

**Comment by yorudy** [comment]
My client is older than the gloo version in the cluster. 
```
Client: {"version":"1.3.3"}
Server: {"type":"Gateway","kubernetes":{"containers":[{"Tag":"1.3.18","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.3.18","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.3.18","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.3.18","Name":"gloo","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}
```

I'll upgrade my client and report back.

**Comment by yorudy** [comment]
I upgraded my local client (Windows 10 Enterprise 1803) version from 1.3.3 to 1.3.18 -- matching the server version.
```
glooctl version
Client: {"version":"1.3.18"}
Server: {"type":"Gateway","kubernetes":{"containers":[{"Tag":"1.3.18","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.3.18","Name":"gateway","Registry":"quay.
io/solo-io"},{"Tag":"1.3.18","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.3.18","Name":"gloo","Registry":"quay.io/solo-io"}],"namespace":"gloo-sys
tem"}}
```
Now running `glooctl check` goes past the gateways step but fails trying to connect to prometheus on localhost. Not sure if this was a dependency introduced in new versions...

```
glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... Problem while checking for out of sync proxies
Error!
timed out trying to connect to localhost during port-forward, errors: 2 errors occurred:
        * Get http://localhost:62221/stats/prometheus: dial tcp [::1]:62221: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by yorudy** [comment]
I upgraded my local glooctl to latest (v1.3.25)
Gloo in the cluster is still at v1.3.18, but everything is good now with gzip turned on.

```
glooctl version
Client: {"version":"1.3.25"}
Server: {"type":"Gateway","kubernetes":{"containers":[{"Tag":"1.3.18","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.3.18","Name":"gateway","Registry":"quay.
io/solo-io"},{"Tag":"1.3.18","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.3.18","Name":"gloo","Registry":"quay.io/solo-io"}],"namespace":"gloo-sys
tem"}}
```
```
glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... OK
No problems detected.
```

**Comment by kdorosh** [comment]
closing because everything has been addressed and fixed on the newest releases of glooctl
