### ISSUE TITLE
expose httpConnectionManager.http_protocol_options.header_key_format Gloo API

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2940]
Requirement is to preserve the case of response headers. Assume this should be added to httpGateway.options.httpConnectionManagerSettings

**Comment by ashleywang1** [comment]
The envoy ProperCaseWords HeaderKeyFormat: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#envoy-api-msg-core-http1protocoloptions-headerkeyformat

```
Formats the header by proper casing words: the first character and any character following a special character will be capitalized if it’s an alpha character. For example, “content-type” becomes “Content-Type”, and “foo$b#$are” becomes “Foo$B#$Are”. Note that while this results in most headers following conventional casing, certain headers are not covered. For example, the “TE” header will be formatted as “Te”.
```

There is no option to preserve the case of the response headers if they look like: `cONtent-tYpe`. But...that shouldn't be needed anyway.

**Comment by bdecoste** [comment]
This may also be applicable: https://github.com/envoyproxy/envoy/issues/8463
