### ISSUE TITLE
Kubernetes swagger resolver does not have capability to perform https

### ISSUE THREAD

**Issue by evilezh** [solo-io/gloo#2957]
Very short - in secure environment, usually everything is https (nothing serves or receives in plain text as even inside container).
this one will set tcp:// for all services ->
https://github.com/solo-io/gloo/blob/c2cc5096b5df2a036536c075d36a07b0d4c5cf2f/projects/gloo/pkg/plugins/kubernetes/plugin.go#L36
this one parses -> 
https://github.com/solo-io/gloo/blob/7f07c6b0d98d63da95104022c4da5124af8f2508/projects/discovery/pkg/fds/discoveries/swagger/swagger.go#L105
as we can see, result is always http. 

Before diving into code,  I tried specify sslConfig with secretRef, as I assumed that would turn ssl on :) - did not happen of course. I also assumed that in this case ca.crt would be enough, but later when I read through code, it work only for mTLS.

And here is now few things to add:
- add annotations to indicate service protocol !!!
- same tls secret work if I want to bypass ca.crt
- conditional flag for mutual tls (then we use tls.crt and tls.key from secret as well)
- tls verification mode: none, full

As quick patch just creating new annotation to specify protocol and ignore ssl verification would be good start.

**Comment by rickducott** [comment]
Thanks for filing @evilezh and the thorough analysis.
