### ISSUE TITLE
[Duplicate of #2534] VirtualService keeps using wrong certificate

### ISSUE THREAD

**Issue by efistokl** [solo-io/gloo#2958]
**Describe the bug**
When having multiple secrets with certificates the gloo keeps using the first one created for all VirtualServices even though they have different secrets specified in sslConfig.secretRef.

Also, VirtualService keeps using "old" tls certificate even if it was updated in the secret.

**To Reproduce**
1. Create tls certificate and store it in the secret in `gloo-system` namespace. (I use cert-manager)
2. Create VirtualService which references the secret via sslConfig.secretRef. It is working fine.
3. Create another tls certificate and store it in the other secret.
4. Create second VirtualService which references the other secret.
5. Second VirtualService ends up using the certificate from the first secret.

**Expected behavior**
VirtualService is expected to use the secret specified in sslConfig.secretRef.

**Additional context**
Gloo installed via
```
helm repo add gloo https://storage.googleapis.com/solo-public-helm
helm repo update
kubectl create namespace gloo-system
helm install gloo gloo/gloo --namespace gloo-system \
  --set gateway.enabled=true,gateway.validation.enabled=false,ingress.enabled=true,ingress.requireIngressClass=true
```

**Comment by efistokl** [comment]
Do you need any other info? Is the description clear enough?

**Comment by kdorosh** [comment]
sounds like a duplicate of https://github.com/solo-io/gloo/issues/2534#issuecomment-595382927

basically, as currently written, sslConfigs on virtual services that merge into the same envoy listener will share their tls certificates. we need to change this.

@efistokl are you comfortable closing this issue as duplicate, and adding 👍 to the previous issue?

**Comment by efistokl** [comment]
Sure

**Comment by efistokl** [comment]
@kdorosh also, kind of related. Do your Virtual Services also *NOT* pick up the updated certificate when it was updated in the secret?
