### ISSUE TITLE
Gloo in docker-compose env should scan or artifact (e.g. configmap) changes and reload 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2965]
**Is your feature request related to a problem? Please describe.**
Changes to docker-compose artifacts (e.g. opa policy configmap) are not picked up and require 
a change to a gloo configs resource to take effect

**Describe the solution you'd like**
Gloo container in docker-compose env should scan for configmap/artifact changes and update the envoy config accordingly

**Comment by rickducott** [comment]
Chatted with @ilackarms this is most likely a bug.
