### ISSUE TITLE
add "secrets require 'resource_kind: '*v1.Secret' annotation" to logs when secret is not found

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2974]
****Is** your feature request related to a problem? Please describe.**
If a secret does not contain the 'resource_kind: '*v1.Secret' annotation gloo will logs an error or warning saying that the secret is not found but doesn't state cause

**Describe the solution you'd like**
Make log clear why secret may not be found

**Comment by rickducott** [comment]
Docs PR merged

**Comment by ashleywang1** [comment]
The documentation will be under Reference for the Gloo CLI:
https://docs.solo.io/gloo/latest/reference/cli/glooctl_create_secret/
