### ISSUE TITLE
Update development environment setup guide

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2987]
**Describe the requested changes**
Development environment setup guide is out of date. We should update the doc and also the `BUILD.md` file.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo/latest/guides/dev/setting-up-dev-environment/

**Additional context**

**Comment by corporealshift** [comment]
Here are a few things I noticed right away:

- `mockgen` is a dependency but it isn't mentioned as one.
- `dep` is no longer required
