### ISSUE TITLE
Provide first-class integration with cert-manager ACME Issuers

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#2993]
**Is your feature request related to a problem? Please describe.**
The [cert-manager implementation of the HTTP01 ACME challenge](https://cert-manager.io/docs/configuration/acme/http01/) works by spinning up a pod which contains the correct data and an `Ingress` object which will configure routing to the correct pod.
When running Gloo in gateway mode, since we don't have `Ingress` resources automatically converted to `VirtualServices`, there is quite a bit of manual work necessary to wire up the routing. There should be a solution in place which automatically does this as the current method is not suitable for large-scale deployments.

**Describe the solution you'd like**
There are two options that I see as viable:

_Directly integrate with cert-manager ACME custom resources_
One option is to watch for the various [cert-manager custom resources (`Orders` and `Challenges`)](https://cert-manager.io/docs/concepts/acme-orders-challenges/) and build automation to automatically wire up routing as necessary based on these resources.

_Provide better support for `Ingress` resources while also running in gateway mode_
The other, broader, solution is to provide support for `Ingress` translation while running in gateway mode. This has been alluded to previously (see https://github.com/solo-io/gloo/issues/2286). Currently, the ingress mode deploys a separate instance of envoy from gateway mode, i.e. different `Proxy` objects, `gateway-proxy` vs. `ingress-proxy`.

**Describe alternatives you've considered**
A heavy-handed workaround is to have both the gateway and ingress proxies running, and have the gateway-proxy have routing rules in it's `VirtualService` to send a redirect response to the domain for the ingress-proxy when an ACME request is received. This is only an option because [Let's Encrypt will follow redirects to a certain depth](https://letsencrypt.org/docs/challenge-types/#http-01-challenge).

**Additional context**
Similar discussion here: https://github.com/solo-io/gloo/issues/2654
Let's figure out if we want to track this work in this issue or here.

**Comment by wilmardo** [comment]
The current setup described in the docs also breaks connectivity with Envoy.
When certificate request is finished, cert-manager removes the resolver pod from the namespace. From that point on the configured `VirtualService` is invalid since the upstream doesn't exist anymore. Envoy rejects the configuration and shuts the HTTP and HTTPS ports since the listener config is invalid.

At least this is what I observed and troubleshooted through Slack :)

**Comment by clemensk1** [comment]
is there any solution or suggestion for a workaround for this yet? For my use case this has to be fully automated. I really would like to use gloo, but this would be a huge drawback. Thanks

**Comment by lgadban** [comment]
There is an option outlined in the following blog from @bcollard --
https://www.solo.io/blog/tutorial-secure-the-edge-with-gloo-and-get-your-a-grade/

Basically you can utilize the `podTemplate` field and a custom `Service` to select the solver pods, providing a consistent destination for routing from Gloo Edge.

**Comment by clemensk1** [comment]
Thank you! I understand the principle. But it seems like gloo doesn't route https traffic until the certificate is valid. So the /.well-known/acme-challenge/<token> endpoint will never be available. how to solve this? thanks!

**Comment by bcollard** [comment]
@clemensk1 for the HTTP-01 challenge to work, you need to expose the solver [on an HTTP server](https://letsencrypt.org/docs/challenge-types/#http-01-challenge). HTTPS is not supported.
Regarding, Gloo, it will work as long as the TLS secret exists.
So a solution is to have 2 VS: one serving HTTP for acme challenges and the other one for HTTPS.

**Comment by bcollard** [comment]
https://github.com/solo-io/gloo/pull/4636

**Comment by RichiCoder1** [comment]
Addendum to this thread: Would something like Let's Encrypt `tls-alpn-01` be supported and potentially given first class support? That somewhat solves the https-only issue
