### ISSUE TITLE
Links in the docs point to https://gloo.solo.io/introduction/TODO

### ISSUE THREAD

**Issue by peterj** [solo-io/gloo#3]
Most of the links in the docs on e.g.https://gloo.solo.io/introduction/concepts point to: https://gloo.solo.io/introduction/TODO

**Comment by ericmand** [comment]
I fixed a few of these in https://github.com/solo-io/gloo/pull/2
I'll attempt the others now, if someone doesn't beat me to it :)

**Comment by peterj** [comment]
I am going through kubernetes.md and will fix links there

**Comment by ilackarms** [comment]
thanks for this! time crunch and other things left a lot of unfinished TODOs in the docs.

**Comment by ilackarms** [comment]
all the broken links should be fixed now. feel free to reopen if you find any
