### ISSUE TITLE
Fix healthchecks doc

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3004]
**Describe the requested changes**
Open source user reported that our documented health checks example needs to be updated, context here https://solo-io.slack.com/archives/C9L6VPAUW/p1589388920201000?thread_ts=1589387582.198900&cid=C9L6VPAUW

**Comment by eshepelyuk** [comment]
@kdorosh there's another issue with docs 
point#1 from https://solo-io.slack.com/archives/C9L6VPAUW/p1593770940473800

**Comment by EItanya** [comment]
In addition, [this link](https://github.com/solo-io/gloo/blob/a956a85f339259e561ec76abaeed6036820de209/projects/gloo/api/v1/load_balancer.proto#L22) no longer works. updated can be found here: https://www.envoyproxy.io/docs/envoy/v1.14.3/intro/arch_overview/upstream/load_balancing/panic_threshold.html?highlight=panic%20mode
