### ISSUE TITLE
support pulling data for headerManipulation from configmap

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3006]
**Is your feature request related to a problem? Please describe.**
Have to hardcode headers to add in yaml

**Describe the solution you'd like**
Would like to be able to configure headers to add based on keys/values stored in configmaps

**Comment by chrisgaun** [comment]
Reusability across multiple VS

**Comment by saiskee** [comment]
Introduced VirtualHostOption and RouteOption CRDs in v1.8.0

**Comment by chrisgaun** [comment]
Delivered with transformation as separate CRD
