### ISSUE TITLE
 *v1.VirtualService: unknown field "virtualHostPlugin" in v1.VirtualHost

### ISSUE THREAD

**Issue by suchisubhra** [solo-io/gloo#3008]
I am  seeing this error
Error from server: error when creating "petclinic-service.yaml": admission webhook "gateway.gloo-system.svc" denied the request: could not unmarshal raw object: parsing resource from crd spec petclinic in namespace gloo-system into *v1.VirtualService: unknown field "virtualHostPlugin" in v1.VirtualHost

This is the yaml file

apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petclinic
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
        - prefix: /
      routeAction:
        single:
          kube:
            ref:
              name: petclinic
              namespace: default
            port: 80
    virtualHostPlugins:
      extauth:
        config_ref:
          name: jwt-opa
          namespace: gloo-system

**Comment by kdorosh** [comment]
It looks like you are trying to apply a pre-1.0 Gloo yaml to a Gloo 1.0.0+ installation. (see the breaking change I'm talking about here: https://docs.solo.io/gloo/latest/operations/upgrading/1.0.0/#breaking-changes-commonly-requiring-manual-action , note that `virtualHostPlugins ` have been renamed to `options`)

Does this answer your question?

**Comment by suchisubhra** [comment]
That solves the issue.. is there any  change with enabling oidc on  virtualservice 
i  am  getting this error  
Error: unknown flag: --enable-oidc-auth
 glooctl create virtualservice --namespace gloo-system --name default --enable-oidc-auth
--
Where can i find document  for >1.0

**Comment by suchisubhra** [comment]
or how can I install  "1.0.0" version?

**Comment by kdorosh** [comment]
this page details the 1.0.0 upgrade flow: https://docs.solo.io/gloo/latest/operations/upgrading/1.0.0/

if you are running a dev/staging environment, I'd recommend uninstalling gloo (`glooctl uninstall --all`) and then reinstalling (`glooctl install gateway`), which should get you the newest stable version of gloo
