### ISSUE TITLE
Make a request jwt available in OPA `input.state.jwt` without having to use OIDC

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3009]
**Is your feature request related to a problem? Please describe.**
jwt is only available in OPA as `input.state.jwt `when OIDC is enabled 

**Describe the solution you'd like**
Make a request jwt available in OPA `input.state.jwt` without having to use OIDC.

**Additional context**
I think we'd just need to add logic to extauth to look specifically for the authorization header and then make that available separately

**Comment by srenatus** [comment]
Clarification question: Am I wrong to assume that with the current state of things, it would be possible to find the JWT in the request headers, somewhere in the CheckRequest structure?
