### ISSUE TITLE
move jwt ahead of ext_authz (e.g. opa) in the http filter chain

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3012]
**Is your feature request related to a problem? Please describe.**
Unable to access headers from jwt (i.e. claims) in extauth 

**Describe the solution you'd like**
Move jwt ahead of ext_authz (e.g. opa) in the http filter chain so any headers created in jwt are available in extauth

**Comment by rickducott** [comment]
Merging with https://github.com/solo-io/gloo/issues/2591
