### ISSUE TITLE
Helm chart bug for NodePort value of proxy service

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3015]
**Describe the bug**
[The template for the gateway-proxy `Service`](https://github.com/solo-io/gloo/blob/d6d293d1cc7af7ad59874656a8514b38e76efdc7/install/helm/gloo/templates/8-gateway-proxy-service.yaml#L38) has a place to specify the desired `nodePort` value of the `Service` (when using a `NodePort` over a `LoadBalancer`), however this doesn't actually set the `nodePort` field, meaning you can't specify a specific `nodePort` value in an automated fashion via helm.

**To Reproduce**
During an install use a values file similar to:
```
gatewayProxies:
  gatewayProxy:
    service:
      httpNodePort: 30000
```

**Expected behavior**
The provided node port value to be used as the `nodePort` field of the service

**Additional context**
I believe this is because the template is using a capitalized "NodePort" field name:
https://github.com/solo-io/gloo/blob/d6d293d1cc7af7ad59874656a8514b38e76efdc7/install/helm/gloo/templates/8-gateway-proxy-service.yaml#L38

**Comment by tmojlupo** [comment]
I see what you are referring to.  In that line it should be `nodePort: {{ $spec.service.httpNodePort }} `.  Will fix that.
