### ISSUE TITLE
Grpc based custom auth don't work starting with v1.3.18

### ISSUE THREAD

**Issue by tayvs** [solo-io/gloo#3023]
**Describe the bug**
I have worked gloo instance with grpc based custom auth. It work properly for gloo v1.3.17 and below. After updating to 1.3.18 custom auth don't receive requests from gloo. I were tryng too increase request timeout but still nothing is come (I have logging for income requests).
If I rollback gloo to 1.3.17 all work properly again.

Clients that tryng to make request to my internal API (frontend) receive 403 errors
In gateway-proxy I found msg like this

>nas-gloo/gateway-proxy-5c9766dc7d-4rs4n[gateway-proxy]: {"bytesSent":"0","userAgent":"curl/7.58.0","requestId":"893f759f-a416-48cd-9e23-1ab0a797dc08","code":"403 UAEX","bytesReceived":"0","authority":"*","forwardedFor":"*","path":"/fx_rate/","protocol":"HTTP/1.1","upstreamTime":"-","Cf_Ipcountry":"UA","duration":"19","upstreamCluster":"-","http_cf_connecting_ip":"****","upstreamHost":"-","start_time":"2020-04-30T08:51:19.345Z","method":"GET"}

> nas-gloo/gateway-proxy-5c9766dc7d-4rs4n[gateway-proxy]: 'content-type', 'application/grpc'
> nas-gloo/gateway-proxy-5c9766dc7d-4rs4n[gateway-proxy]: 'grpc-status', '14'
> nas-gloo/gateway-proxy-5c9766dc7d-4rs4n[gateway-proxy]: 'grpc-message', 'upstream connect error or disconnect/reset before headers. reset reason: connection termination

Is there any changes in protocol or configurations starting from 1.3.18?

**Comment by kdorosh** [comment]
Looking over the changelog, I noticed that we updated our envoy version in the v1.3.18 release. We will look into how this could have created a regression and update you with any process (or additional questions) here.

**Comment by kdorosh** [comment]
Hey @tayvs I looked into your issue. 

I tested on Gloo 1.3.25:
```
glooctl version
Client: {"version":"1.3.25"}
Server: {"type":"Gateway","kubernetes":{"containers":[{"Tag":"1.3.25","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.3.25","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.3.25","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.3.25","Name":"gloo","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}
```

The documented HTTP custom extauth workflow still works: https://docs.solo.io/gloo/latest/guides/security/auth/custom_auth/ and we test the grpc extauth workflow in our e2e tests: https://github.com/solo-io/gloo/blob/v1.4.0-beta11/test/e2e/custom_auth_test.go#L284

As such I was unable to reproduce your issue -- I'm wondering if it's some other change in envoy that is manifesting itself as extauth issues in your environment.

As a sanity check, can you run `glooctl check` against a 1.3.18 installation? Also can you provide the logs? (`glooctl proxy logs` to enable debug logging, make the request, and then `glooctl proxy logs` again to get the logs and share them here)

Also would love to look into this in our public slack with you, and figure out what changed in this patch release. Our public slack is https://slack.solo.io/ and you can message me directly at @kdorosh  to work through this more quickly

**Comment by tayvs** [comment]
@kdorosh I found source of problem. Gloo 1.3.18 start sending new http2 stream setting (0x8). My http2 library don't know such settings and not skip unknown setting but failed with error. That bug already fixed and all work fine.

![image](https://user-images.githubusercontent.com/14348912/83046932-62954900-a050-11ea-8646-b23317096ca5.png)

P.S. I use akka http library. In 1.10.12 version that issue were fixes

**Comment by kdorosh** [comment]
@tayvs thanks for your diligent debugging and sharing the answer here for others in the community!
