### ISSUE TITLE
ingress test flake reproducible locally hints at bug in ingress implementation

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3041]
**Describe the bug**
Example flake https://github.com/solo-io/gloo/pull/3032#issuecomment-631607921

Failed runs have ingress logs with:
```
{"level":"error","ts":"2020-05-20T20:47:41.703Z","logger":"ingress.v1.event_loop.ingress","caller":"setup/setup_syncer.go:277","msg":"error: ingress_status_event_loop: failed to get lb status: expected 1 ingress service, found [{kubernetes default} {gloo ingress-test-1-1} {ingress-proxy ingress-test-1-1} {testrunner ingress-test-1-1} {kube-dns kube-system} {dashboard-metrics-scraper kubernetes-dashboard} {kubernetes-dashboard kubernetes-dashboard}]","version":"kdorosh","stacktrace":"github.com/solo-io/gloo/projects/ingress/pkg/setup.RunIngress.func1\n\t/Users/kdorosh/go/src/github.com/solo-io/gloo/projects/ingress/pkg/setup/setup_syncer.go:277"}
```

appears the kube service selector didn't work?

**To Reproduce**
Run regression tests locally, eventually the flake will be hit (may take ~10 tries). We can lower the timeout from 2 minutes to 10 seconds.. it either succeeds quickly or never fails.

**Expected behavior**
Test passes, always

**Additional context**
Add any other context about the problem here, e.g.
- Tested on master Gloo build branch on minikube w/ k8s 1.17

**Comment by sam-heilbron** [comment]
This test hasn't flaked in >1 year. Closing.
