### ISSUE TITLE
Kube2e: Knative-Ingress test flake in CI

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo#3052]
**Describe the bug**
The following flake has appeared multiple times in CI:
```
Failure [122.338 seconds]
Kube2e: Knative-Ingress
/Users/ashwang/go/src/github.com/solo-io/gloo/test/kube2e/knative/knative_test.go:18
  works [It]
```
https://github.com/solo-io/gloo/runs/694210442

**To Reproduce**
1. Start a blank-state installation of minikube or kind
2. `TAGGED_VERSION=vtest make clean docker docker-push build-test-chart glooctl-darwin-amd64`
3. In the goland IDE, run the gloo/test/kube2e/knative/knative_test in debug mode.

**Expected behavior**
The end to end test should pass, but instead it usually fails on the first try. After a certain point, no matter how many times it runs, the test always passes.

This could be because it takes a long time to download the testrunner docker image.

**Comment by sam-heilbron** [comment]
Similar, though not identical flake in knative-ingress https://github.com/solo-io/gloo/runs/2688750539

**Comment by sam-heilbron** [comment]
Our knative tests were moved, and this hasn't occurred in >1 year. Closing. We can re-open if these appear again
