### ISSUE TITLE
Support Access Tokens in OIDC Flow

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3055]
**Is your feature request related to a problem? Please describe.**
For OIDC, part of the flow is receiving an access token from the token endpoint after the authentication has completed. Currently, only the `id_token` is used (and sent back to the client/end user). This means you can not use the access token for additional OIDC calls (e.g. to the UserInfo endpoint) or for further authZ decisions on subsequent calls.

**Describe the solution you'd like**
Support for returning access tokens (including _opaque access tokens_) in some form should be added to the OIDC logic.

**Describe alternatives you've considered**
Since the access token is never returned, no alternatives possible

**Comment by lgadban** [comment]
Decisions needed on:

- Where to store access token
- How to validate access token
   - JWT vs. opaque token with token introspection

**Comment by kdorosh** [comment]
Decided to store the access token in a cookie (where the ID token already is returned) so that browsers send the access token to Gloo during the OIDC callback.

Then we can do token introspection on the access token if needed and make a call to the user info endpoint, and put the result in state for use by an extauth plugin.

**Comment by kdorosh** [comment]
Reopening until the changes to our extauth service are picked up and released in Gloo Enterprise

**Comment by kdorosh** [comment]
These changes have been released with GlooE 1.5.0-beta2. Reopening the issue again until our docs have been updated with examples of the new API

**Comment by kdorosh** [comment]
resolved by https://github.com/solo-io/gloo/pull/3702 and https://github.com/solo-io/gloo/pull/3742
