### ISSUE TITLE
On static upstreams, we should automatically set the auto_host_rewrite flag

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#306]
So when we statically add new upstreams, ie:

```
glooctl create upstream static jsonplaceholder-80 --static-hosts jsonplaceholder.typicode.com:80
```

And we create a route to the upstream:

```
glooctl add route  --dest-name jsonplaceholder-80  --path-exact /api/posts --prefix-rewrite /posts
```

And we try curl the gateway:

```
curl $(glooctl gateway url)/api/posts
```

The upstream will see the `Host` header of the gateway and not the correct upstream Host. In Envoy, we can set `auto_host_rewrite` flag so that the `Host` header takes on the host of the upstream cluster: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction

In our Gloo code base, we *do* have this automatically happening for static upstreams:

https://github.com/solo-io/gloo/blob/faffd00a2a01258a8cc7b72d82c3fa45b8d66796/projects/gloo/pkg/plugins/static/plugin.go#L139

The problem is, this part of the code implements the RouteActionPlugin#ProcessRouteAction which is conspicuously missing from the translation code:

https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/translator/route_config.go#L129

I have a PR coming for this, but need someone to help me take a look

**Comment by ilackarms** [comment]
wow! nice find @christian-posta ! embarassing :sweat_smile: 
let me know if you have any questions about fixing this

**Comment by christian-posta** [comment]
This is fixed
