### ISSUE TITLE
Explicitly document trailing slash requirement for OIDC issueUrl

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3071]
**Describe the requested changes**
issuerUrl needs a trailing slash to find .well-known. Have Gloo append a missing trailing slash.

**Comment by ashleywang1** [comment]
The issuerUrl object is defined here: ext-auth-service/pkg/config/oidc/oidc.go.

It's used in solo-projects/projects/extauth/pkg/config/generator.go.
