### ISSUE TITLE
Performance improvements for Docs loading

### ISSUE THREAD

**Issue by Sodman** [solo-io/gloo#3075]
**Is your feature request related to a problem? Please describe.**
When I switch between pages on the main docs site, eg going from [Concepts](https://docs.solo.io/gloo/latest/introduction/architecture/concepts/) to [Deployment Options](https://docs.solo.io/gloo/latest/introduction/architecture/deployment_options/) - the page takes longer than expected to load. This is on a hard-wired fiber connection using modern desktop hardware, in the latest version of Chrome. According to lighthouse performance metrics, first contentful paint takes ~4 seconds, and input latency is ~7+ seconds:
![image](https://user-images.githubusercontent.com/1928125/83050862-272c5780-a01b-11ea-8fb9-84374569b73b.png)

The main culprit seems to be loading up 'index.json', which is a 1.9MB file I believe is used for client-side search autocomplete. This makes up about 2/3rds of the overall ~2.9MB network transfer of the page. Below is a screenshot of the performance profile using chrome dev tools during a page load, showing that loading index.json takes about 2.7 seconds, during which it appears to be blocking:

![image](https://user-images.githubusercontent.com/1928125/83049555-5e9a0480-a019-11ea-8479-723b5bfc4535.png)

**Describe the solution you'd like**
If the call to retrieve index.json was asynchronous and non-blocking, it wouldn't affect the user navigating the docs via the sidebar, so this may work if index.json is only used to populate the search box autocomplete.

**Describe alternatives you've considered**
Deferring the loading of index.json until a focus or input event on the search box would reduce page size for anyone not using the search box utility. Search would feel slower to active search users the first time however, so a loading spinner may need to be added the UI.

These two are not mutually exclusive to either of the above solutions, but may require more effort depending on build/infrastructure complexities:
1) If the index.json file was cached and fingerprinted every release, then it would avoid re-fetching it over the network as users click through the pages on the docs.

2) The index.json file is currently uncompressed. Adding gzip compression would change the transfer size from 1.9MB to ~500KB. Using brotli compression for modern browsers ([everything but IE](https://caniuse.com/#feat=brotli) has supported it for a while, including MS Edge) saves an additional 15-20% vs gzip, but involves more effort to set up.

**Additional context**
Caching & compressing the other static resources, such as fonts, jquery libraries, and CSS, would also help performance. The index.json download appears to be the primary performance hit right now, however.

**Comment by marcogschmidt** [comment]
Hi @Sodman , thanks for opening this issue and for the detailed description. I had noticed some lag in the rendering of the docs, but never in the orders of several seconds... We will look into.

**Comment by Sodman** [comment]
I played around with this a little bit more on my local while I was waiting for other builds to run... 

Enabling gzip does roughly half the entire page size transferred down to ~1.4MB from 2.9MB, and[ is fairly easy to implement](https://github.com/solo-io/gloo/blob/51b67ae61852e2f321dcc4fc98ae92870eb04340/docs/conf/conf.d/default.conf#L10-L15). :+1: 

Unfortunately it looks like the root cause of the browser-blocking laggy feeling wasn't the large file loading. The blocking is caused by parsing the large hugo-built `index.json` index and adding each item to a lunrJS index on every page load. See [the js that builds the index on page load](https://github.com/solo-io/hugo-theme-soloio/blob/master/static/js/search.js). It looks from the lunr docs that we could significantly reduce the blocking load time by [pre-building the index](https://lunrjs.com/guides/index_prebuilding.html) at build time, then just loading the pre-built index on the client at runtime.

This would require the build process to be tweaked to run JS to pre-build the index however, so I'm going to leave this alone for now until it becomes a higher priority. If this does get picked up at some point, it's probably also worth updating the js search library, lunrJS from 0.x to the latest 2.x version as part of this.
