### ISSUE TITLE
Unable to override registry for all images via helm value

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3081]
**Describe the bug**
There are hardcoded references to quay.io somewhere in the helm chart which prevents a simple override to use a different registry e.g. docker.io

**To Reproduce**
Install GlooE with the following values:
```
global:
  image:
    registry: docker.io/soloio
```

Most of the images will be correctly changed to use the `docker.io/soloio` registry but some will still reference quay.io:
```
% kg po -n gloo-system -o jsonpath='{range .items[*].spec.containers[*]}{.image}{"\n"}'
docker.io/soloio/grpcserver-ui:1.3.6
docker.io/soloio/grpcserver-ee:1.3.6
docker.io/soloio/grpcserver-envoy:1.3.6
quay.io/solo-io/discovery:1.3.25
docker.io/soloio/extauth-ee:1.3.6
quay.io/solo-io/gateway:1.3.25
docker.io/soloio/gloo-ee-envoy-wrapper:1.3.6
docker.io/soloio/gloo-ee:1.3.6
grafana/grafana:6.6.2
quay.io/coreos/kube-state-metrics:v1.6.0
jimmidyson/configmap-reload:v0.2.2
prom/prometheus:v2.13.1
docker.io/soloio/observability-ee:1.3.6
docker.io/soloio/rate-limit-ee:1.3.6
docker.io/redis:5
```

**Expected behavior**
The override should apply to all images, i.e. there should not be hardcoded references to registries in the charts

**Additional context**
`% helm show all glooe/gloo-ee | grep registry` should help narrow down the hardcoded registries

**Comment by jenshu** [comment]
should have been fixed via https://github.com/solo-io/gloo/issues/5622
