### ISSUE TITLE
Enable Gloo to run in a fully restricted Kubernetes environment

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3084]
**Is your feature request related to a problem? Please describe.**
Ideally the full Gloo deployment should not require any elevated privileges i.e. the gloo components can run while using a "restricted" `PodSecurityPolicy` (PSP).

There are a handful of straightforward changes we can make to ensure there are no superfluous permissions needed by Gloo (see list below)

Additionally, we should provide a PSP (via helm chart?) for all "elevated" privileges currently necessary for the Gloo installation.

- [ ] Do not run certgen container as root
- [ ] Do not run any of the 3 UI containers as root 
  - Also includes not using an nginx image that requires root, some options:
  - https://github.com/nginxinc/docker-nginx-unprivileged
  - "Running nginx as a non-root user" on https://hub.docker.com/_/nginx
  - Explicitly call out correct user/group ids in api server if sticking with docker nginx image
- [ ] Do not run extauth as root
- [ ] Create specific service account for running extauth (?)
- [ ] Do not run observability as root
- [ ] Do not run redis as root
   - Some options:
   - [Run current image as specific user id](https://github.com/docker-library/redis/issues/189) also see addition context section for a working example of this
   - use bitnami/redis image
- [ ] Do not run ratelimit as root
- [ ] Create specific service account for running ratelimit (?)
- [ ] Not require `glooe-grafana` init container to require root

**Describe the solution you'd like**
Ideally we do not need any special permissions.
If we do need any permissions, a PSP should be provided properly granting the correct service accounts permissions as needed.

**Describe alternatives you've considered**
N/A

**Additional context**
Following settings needed on UI/apiserver deployment with a restrictive PSP on by default:
```
      securityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsUser: 101
```

Settings for redis
```
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsUser: 999
```

Will add a working PSP for the current state as well as an attachment

**Comment by lgadban** [comment]
Rather than changing `Dockerfiles` to explicitly set a user, we may be able to just provide a default `runAsUser` in the PSP

**Comment by lgadban** [comment]
Easiest solution may be to explicitly add `runAsUser` (and similar) configs for every deployment

**Comment by kdorosh** [comment]
reopening until we catch some stragglers, but the default installation will be locked down as of Gloo and GlooE 1.4.0
