### ISSUE TITLE
Support integration with external OPA server

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3093]
**Is your feature request related to a problem? Please describe.**
Allow for integrating with an external OPA server for authZ (as opposed to the GlooE OPA integration)

**Describe the solution you'd like**
Some way to specify an external OPA server rather than the "inline" OPA run by GlooE ext auth service

**Comment by srenatus** [comment]
That would be great. For one thing, it would become our responsibility to pick a version (#3136) and we could make use of all features, including bundles, decision logging, etc.

**Comment by RichiCoder1** [comment]
I'm assuming this is asking for first-class support? You can do this in the OSS version via `https://github.com/open-policy-agent/opa-envoy-plugin` and ext_authz though it's a bit uglier to integrate than it needs to be imho
