### ISSUE TITLE
Gloo, Minikube and nip.io

### ISSUE THREAD

**Issue by rgreinho** [solo-io/gloo#3098]
I just started to play with Gloo to replace my nginx ingress controller. 

I wanted to start experimenting on minikube, and I followed this tutorial: https://scott.cranton.com/kubernetes-ingress-controlling-with-gloo.html. While everything described in the tutorial worked fine, it uses a special trick to connect to the API with `curl --connect-to`, and connect to the gloo proxy address.

On my own app, with the nginx controller, I use the nip.io DNS service, and I am able to curl directly using `curl http://api.192.168.99.100.nip.io`, and use the browser to reach http://www.192.168.99.100.nip.io.

I was not able to reproduce this behavior with Gloo and I was wondering if there was a trick, or simply something I missed in the setup.

**Comment by lgadban** [comment]
Hi @rgreinho -- apologies for the delayed response to your question.

You should be able to use a `nip.io` domain without any specific setup.

The [official Gloo docs for using an `Ingress` object](https://docs.solo.io/gloo/latest/guides/integrations/ingress/#basic-ingress-object-managed-by-gloo) go into a little more detail on how to configure your `Ingress`.

Ultimately you would need to set `host: gloo.example.com` to your `nip.io` domain, e.g. `host: www.192.168.99.100.nip.io.`

Please let us know if you still run into issues.

**Comment by lgadban** [comment]
I'll go ahead and close this issue for now, please reopen if you are still having trouble.
