### ISSUE TITLE
Enable probes by default

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3114]
**Is your feature request related to a problem? Please describe.**
Without probes/health checks enabled, Gloo is not "production" ready as the gateway-proxy pods having issues will not be removed from the `Endpoints` in a reasonable manner. Having to explicitly enable probes along with finding the helm value is not a great experience.

**Describe the solution you'd like**
Probes should be enabled by default, or at least in the enterprise chart.

**Describe alternatives you've considered**
Warnings in the documentation could be an alternative if the probes being off by default is determined to still be the right approach

**Comment by kdorosh** [comment]
In addition, we should change the probes to use 127.0.0.1 instead of localhost
