### ISSUE TITLE
Separate codegen and regression test into two different github actions

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3118]
**Is your feature request related to a problem? Please describe.**
In docs only PRs, we often like to skip ci (since there are no code changes). we would still like codegen to pass though (as codegen affects docs)

**Describe the solution you'd like**

Separate codegen and regression test into two different github actions

Also, it would be good if our bots would let us skip checks by name so we can comment `/skip-<check name>` to skip regression tests and rest of CI on docs PRs, if we so desired. (as we currently have no way to skip a github action)

**Comment by sam-heilbron** [comment]
We now support these as separate jobs. Also, there is a mechanism to skip tests and docs builds for docs PR: https://github.com/solo-io/gloo/tree/main/ci#special-directives-to-skip-ci
