### ISSUE TITLE
Document k8s deployment guide for sharded API gateway architecture

### ISSUE THREAD

**Issue by vipulagarwal** [solo-io/gloo#3125]
**Describe the requested changes**
Document k8s deployment guide for sharded API gateway architecture. This will benefit anyone who wants to run Gloo in production with noisy neighbors 

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo/latest/introduction/architecture/deployment_arch/#sharded-api-gateway

**Browser Information**
N/A

**Additional context**
N/A

**Comment by kdorosh** [comment]
Thank you for your feedback. We appreciate the good idea -- we will consider this in our future roadmap. We would love a community PR here as well.

**Comment by mloskot** [comment]
Although I realise I may be a necromancer here, as a rookie, I consider this an important and still under-documented topic.

That document on sharded gateway now lives at https://kgateway.dev/docs/latest/about/deployment-patterns

For the archives, today, I asked this on Slack:

> [Sharded gateway with central ingress](https://kgateway.dev/docs/latest/about/deployment-patterns/#sharded-gatway-with-central-ingress) says:
> _useful if you need a central IP address and DNS name for the gateway that serves all your traffic._
> 
> but is there any example with the manifest'ation of that deployment, especially configuring the listeners for multiple gateways having single DNS name?
> Am I understanding the article correctly that it is possible to have a central load balancer accessible e.g. via [example.com](http://example.com/) leading to multiple `kind: Gateway` resources?

and I received one answer explaining this:

> This example is for having 2 layers of gateways.
> 1 for initial routing that has 1 dns name / ip
> then a second layer for policy.
> In this case, in the front gateway, you will use the Service objects of the 2nd tier gateways as backends in the first one.

Although helpful, that is still a 10000-feet view, like the current version of the linked article. 
An example of implementation of sharded gateway deployment patter is missing.
If I ever manage to work it out, I will try submit it to the docs.
