### ISSUE TITLE
Can I get the access log behind the ext auth

### ISSUE THREAD

**Issue by weixiao-huang** [solo-io/gloo#3126]
I build a [custom auth server](https://docs.solo.io/gloo/latest/guides/security/auth/custom_auth/) in gloo and set some response headers in the custom auth server, which can make upstream service get some auth info after passing the auth server.
Now I want to write a custom grpc accesslog server following the docs in [access logging](https://docs.solo.io/gloo/latest/guides/security/access_logging/). But I find the access logs are traced in the entrypoint in the gateway. Actually, I want to get the request headers set by custom auth server in access logging. So is there any method specifying that access log behind the custom auth?

**Comment by weixiao-huang** [comment]
I'm Sorry that I forgot to set the headers set by auth-server into `additional_request_headers_to_log`. Now it works. Thanks very much.
By the way, can I get the request body in accesslogger? I have seen [an envoy issue](https://github.com/envoyproxy/envoy/issues/9950), which say we can use traffic tapping. So is this supported by gloo? Is there any method to get both the request (including body) and response info in gloo? Since we want to audit user behavior in the gateway side.

**Comment by yuval-k** [comment]
access logs does not support body.
one possible workaround in gloo today is to use the transformation filter to add the body to the envoy's dynamic metadata, and log that.
i would be careful with large bodies in this approach. consider using the buffer filter to limit max_request_bytes

**Comment by vichanse** [comment]
@weixiao-huang i'm trying to set some response headers in the custom auth server, which can make upstream service get some auth info after passing the auth server as you did but headers are not added to the upstream response. Can you show me an example of how you edited the gloo-system default settings?

Thankx for your help

**Comment by weixiao-huang** [comment]
> @weixiao-huang i'm trying to set some response headers in the custom auth server, which can make upstream service get some auth info after passing the auth server as you did but headers are not added to the upstream response. Can you show me an example of how you edited the gloo-system default settings?
> 
> Thankx for your help

You can use `allowedUpstreamHeaders`

```bash
kubectl -n gloo-system patch settings default --type merge -p "spec:
  extauth:
    extauthzServerRef:
      name: your-custom-auth-upstream
      namespace: gloo-system
    httpService:
      request:
        allowedHeaders:
        - Requst-Header-You-Want-To-Receive
      response:
        allowedUpstreamHeaders:
        - Header-You-Want-To-Add-To-Upstream
    requestTimeout: 0.5s"

```

**Comment by vichanse** [comment]
Thankx @weixiao-huang . Works like a charm👌🏾

**Comment by 1026908346** [comment]
> 

I set the `allowedUpstreamHeaders` as you did but headers are not added to the upstream request, anything else need to configure except `allowedUpstreamHeaders`?
