### ISSUE TITLE
Support new golang PluginInterface to add/edit EDS endpoints

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#3131]
**Is your feature request related to a problem? Please describe.**
Currently the EDS endpoints created by the Gloo translator are created and then immediately sent to envoy, there is no opportunity to programmatically change them like the other Plugin Interfaces allow us to do.
https://github.com/solo-io/gloo/blob/d04ff1cc9e9a1cd8cb4f9f0daaa9c6d65c547f5d/projects/gloo/pkg/translator/translator.go#L83

**Describe the solution you'd like**
A Plugin Interface should be added to allow specific options, as well as programatic access to the EDS endpoints before they are sent to envoy. The interface would be modeled on the existing ones and look like this:
```
type EndpointPlugin interface {
	Plugin
	ProcessEndpoints(params Params, in *v1.Upstream, out []*envoyapi.ClusterLoadAssignment) error
}
```
This plugin would be called after the endpoints are created, and before they are sent to envoy.

**Additional context**
This would allow extensions for Gloo which require changes or additions to the EDS endpoints sent to Envo

**Comment by kdorosh** [comment]
Design and naming looks good to me, 👍
