### ISSUE TITLE
OPA version in ExtAuth

### ISSUE THREAD

**Issue by srenatus** [solo-io/gloo#3136]
For writing a Rego policy, it would be useful to know which version of Open Policy Agent is deployed when using that ExtAuth feature.

Also: Is there any way I could find out, outside of asking directly? 😃

**Comment by rickducott** [comment]
@srenatus we currently ship with OPA 0.18.0. Leaving this open to provide an answer to your second question.

**Comment by kdorosh** [comment]
Plan is to add logging to the `Start` function in ext auth service that includes the OPA version, and then update docs to indicate you can check there for version

**Comment by kdorosh** [comment]
Reopening until the docs change and extauth service update is picked up in GlooE

**Comment by kdorosh** [comment]
GlooE has picked up the new ext-auth changes to master, and docs have been updated. Closing issue as it will be resolved in the next GlooE release

**Comment by srenatus** [comment]
@kdorosh thank you! 👏
