### ISSUE TITLE
Document how to install dev portal through glooctl

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#3146]
As title states

**Comment by srenatus** [comment]
Via slack (@marcogschmidt):

> it can be installed with glooctl by setting the `devPortal.enables` value to true:
> ```
> glooctl install gateway enterprise --license-key xxx --values values.yaml
> ```
> where `values.yaml` contains this:
> ```
> devPortal:
>   enabled: true
> ```
> It cannot be installed separately currently. You can add it to a running Gloo Enterprise installation, but only via helm upgrade (providing the above value), as glooctl currently does not have upgrade capabilities
