### ISSUE TITLE
Add annotation to control watchNamespaces

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3173]
**Is your feature request related to a problem? Please describe.**
Would like to restrict Gloo watched namespaces by an annotation on the namespace

**Describe the solution you'd like**
Gloo only watches namespaces with something like this annotation: gloo.watchNamespace: true

**Comment by murphye** [comment]
This is a good idea. Watched namespace can only be configured through the Helm install at this point.

**Comment by murphye** [comment]
gloo-system and kube-system also need to be watched

**Comment by pmichna** [comment]
@murphye Why does `kube-system` need to be watched?

**Comment by DuncanDoyle** [comment]
Since GG 1.18, watchNamespaces can be controlled using label-selectors.
