### ISSUE TITLE
soloio-bot keeps opening forbidden pull requests

### ISSUE THREAD

**Issue by SMillerDev** [solo-io/gloo#3178]
**Describe the bug**
@soloio-bot keeps trying to open beta release PRs while those are not allowed in homebrew-core.

**To Reproduce**
1. watch https://github.com/Homebrew/homebrew-core/pull/56504/files
2. read https://docs.brew.sh/Acceptable-Formulae#stable-versions

**Expected behavior**
I expected the bot to behave

**Additional context**
https://github.com/marketplace/actions/github-action-for-homebrew or https://github.com/marketplace/actions/bump-homebrew-formula might be a better solution since those have options to prevent this behaviour.

**Comment by kdorosh** [comment]
Thanks for reporting @SMillerDev , i hope to take a look in the next couple days

**Comment by SMillerDev** [comment]
https://github.com/solo-io/gloo/issues/3178

**Comment by kdorosh** [comment]
reopening until our build-bot has picked up these changes and is live

**Comment by kdorosh** [comment]
gloo has picked up these changes and should no longer be making automated pull requests on beta versions
