### ISSUE TITLE
Update google analytics tag on docs.solo.io subdomain

### ISSUE THREAD

**Issue by bettyjunod** [solo-io/gloo#3180]
**Describe the requested changes**
Update the current tag to this one below

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-101654320-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-101654320-1');
</script>

**Comment by arianaw66** [comment]
Related issue in case it's ever useful in the future: https://github.com/solo-io/solo-docs/issues/607
