### ISSUE TITLE
Make loadBalancerIP in ingress-proxy service configurable

### ISSUE THREAD

**Issue by maxbischoff** [solo-io/gloo#3184]
**Is your feature request related to a problem? Please describe.**
When configuring Gloo ingress using helm, I was missing a way to configure the loadBalancerIP for my ingress-proxy service.

**Describe the solution you'd like**
I would like the ability to provide a helm value for setting the loadBalancerIP of the ingress-proxy service.

**Describe alternatives you've considered**
I have considered https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/helm_advanced/ but felt that the loadBalancerIP is a non-advanced setting for a ingress controller.

**Comment by maxbischoff** [comment]
If you agree, that this is a valid feature request I'll gladly finish my PR :)

**Comment by kdorosh** [comment]
This is a valid feature request, would love a PR 🎉
