### ISSUE TITLE
Add E2E tests for Knative

### ISSUE THREAD

**Issue by StarpTech** [solo-io/gloo#3194]
This is a very important issue because I think it's the major reason why knative integration is currently broken in terms of:

> For the purpose of running Knative, Gloo can function as a complete replacement for Istio (supporting all documented Knative features), requiring less resource usage and operational overhead.

- https://github.com/solo-io/gloo/issues/3167
- Documentation: How to extend knative with Gloo CRD's?

This prevents me from using gloo in production.

**Comment by StarpTech** [comment]
Why was it closed? I still can't see any E2E for the knative integration.

**Comment by Sodman** [comment]
E2E tests were added to the existing suite [here](https://github.com/solo-io/gloo/tree/master/test/kube2e/knative) by #3282

**Comment by StarpTech** [comment]
Great! Thank you.

**Comment by Sodman** [comment]
No problem!
