### ISSUE TITLE
OPA: support queries returning objects for CheckResponse

### ISSUE THREAD

**Issue by srenatus** [solo-io/gloo#3201]
**Is your feature request related to a problem? Please describe.**

There seems to be no way to produce headers sent to upstream services from the OPA policy evaluation.

**Describe the solution you'd like**

This could be achieved by having the embedded OPA code check the defined query's response for whether it's a boolean or an object. If it's an object, it should be attempted to marshal it into a CheckResponse.

ℹ️ This is what `opa-istio-plugin` does: https://github.com/open-policy-agent/opa-istio-plugin/tree/f12c61a034b40f8e5fbd3463a2c30d1285e6538a#example-policy-with-object-response

**Describe alternatives you've considered**

N/A

**Comment by jmunozro** [comment]
Hi,
This would be most useful in an use case we saw in a customer. They have a lot of rego rules, and they would like to return the specific rule that has been violated in the response to the upstream.

**Comment by marcogschmidt** [comment]
This was implemented as part of https://github.com/solo-io/gloo-mesh-enterprise/issues/12608

**Comment by anessi** [comment]
@marcogschmidt : thanks for the update on the issue. Can you please give more details how this can be used in Gloo Edge?

**Comment by anessi** [comment]
I learned from Solo support that this feature is available in 1.16.0 (extauth) and implements what is documented here: https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-additional-controls
