### ISSUE TITLE
[EPIC] Add cache filter

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3206]
**Is your feature request related to a problem? Please describe.**
Add support for a caching filter, either the existing solo.io filter or upstream Envoy

**Describe the solution you'd like**
A filter that can cache responses for a given set of request attributes and serve the cached response rather than forwarding the request upstream

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kdorosh** [comment]
Some more details captured in option one listed on https://github.com/solo-io/envoy-gloo-ee/issues/254 (private due to customer context)

**Comment by chrisgaun** [comment]
More requirements are found here for Soloist https://docs.google.com/document/d/1v8ntgNEwObvPM36HCQfjcYWsOS-oESZ1dB9DCF0FPAw/edit?usp=sharing
