### ISSUE TITLE
support logical OR (vs logical AND) for multiple auth mechanisms

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3207]
**Is your feature request related to a problem? Please describe.**
I'd like to provide multiple auth mechanisms where a logical OR will pass the request. Currently Gloo only supports logical AND for multiple auth mechanisms

**Describe the solution you'd like**
Support logical OR for multiple auth mechanisms

**Comment by bdecoste** [comment]
This includes logical ORs between JWT, multiple Basic Auth (i.e. multiple passwords configured in an authconfig), and multiple extauth protocols (e.g. Basic Auth OR API Key).

**Comment by lgadban** [comment]
@kdorosh just a heads up that the existing API docs for this feature are not rendering correctly:
https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#authconfig

>How to handle processing of named configs within an auth config chain. An example config might be: ( basic1

**Comment by kdorosh** [comment]
looked into it briefly, appears to be a solokit bug 💢

**Comment by saiskee** [comment]
Fix has been implemented and backported to 1.6; closing
