### ISSUE TITLE
Appending headers from ext-auth plugins does not work when a UserID is present

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3208]
**Describe the bug**
Adding headers to the request from an ext-auth plugin (via `CheckResponse.HttpResponse`) does not work if a `UserInfo.UserID` is also set in the plugin.

**To Reproduce**
Add a header in an auth plugin along with setting the `UserInfo.UserID` and check the upstream service to see that the header is not present on the incoming request.
Example: https://github.com/lgadban/ext-auth-plugin-examples/blob/56d557d3bdcc8f7a8cbb3ed0a1610b16db8c9ac7/plugins/required_header/pkg/impl.go#L128

**Expected behavior**
The headers that are added to the the `CheckResponse` should be appended to the existing request even when the `UserID` value is being set

**Additional context**
N/A

**Comment by kdorosh** [comment]
A workaround is to remove the user ID setting from the deployment's env, with the following helm values:
```yaml
global:
  extensions:
    extAuth:
      userIdHeader:
```

However, this workaround will break any rate limiting based on authentication (the rate limit basic API, not the envoy rate limit api).

**Comment by kdorosh** [comment]
Reopening until GlooE is bumped to pick up the changes to our ext auth service
