### ISSUE TITLE
Health Check config overridden by UDS

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#3216]
**Describe the bug**
Upstream Health Check configs are overwritten by UDS. When Upstreams are Upserted by UDS there is a [function](https://github.com/solo-io/gloo/blob/v1.4.0/projects/gloo/pkg/plugins/utils/update_upstream_spec.go) which copies over the non-discovered config to the new Upstream before it is saved. However, this function was missing Health Checks and also Outlier Detection.

**Expected behavior**
No Health Check information should be overwritten when UDS updates an upstream.

**Additional context**
- Gloo version: v1.4.0

**Comment by kdorosh** [comment]
This is the relevant code: https://github.com/solo-io/gloo/blob/v1.4.0/projects/gloo/pkg/plugins/utils/update_upstream_spec.go

Other fields other than health checks and outlier detection could be missing, or could be missing in the future (if new fields are added).

The solution should be forward-thinking (should not copy enumerated fields to a desired state)
