### ISSUE TITLE
provide aggregated release notes for major releases

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3227]
**Describe the requested changes**
In order to see all of the changes between GlooE 1.3 and 1.4 I need to look at all of the community changes for all of he releases here: https://github.com/solo-io/gloo/releases
and all of the enterprise changes for all the betas here: https://docs.solo.io/gloo/latest/reference/changelog/enterprise/

**Link to any relevant existing docs**
https://docs.solo.io/gloo/latest/reference/changelog/enterprise/

**Comment by kdorosh** [comment]
reopening until the enterprise changes have been merged with changes from open source, will be resolved by https://github.com/solo-io/gloo/pull/3907
