### ISSUE TITLE
Ability to associate route tables to one or more virtual services using labels

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3237]
**Is your feature request related to a problem? Please describe.**
Requirement to modify the virtualservice yaml for each new routetable prevents complete delegation

**Describe the solution you'd like**
I'd like to be able to associate routetables to virtualservices using kube labels on the routetable instead of modifying the virtualservice yaml

**Comment by kdorosh** [comment]
this is already possible today: https://github.com/solo-io/gloo/blob/v1.5.0-beta28/projects/gateway/api/v1/virtual_service.proto#L237-L287

documented https://docs.solo.io/gloo/latest/guides/traffic_management/destination_types/delegation/#delegation-via-route-table-selector
