### ISSUE TITLE
Clarification on Upstream TLS settings/support

### ISSUE THREAD

**Issue by travisgroth** [solo-io/gloo#3238]
Most of the documentation about upstream TLS support focuses on what appears to be client certificate presentation to the upstream server.  Eg:

https://docs.solo.io/gloo/latest/guides/security/tls/client_tls/

This of course enables https protocol to the upstream implicitly but, in the case where there is no client certificate that I want to use, is there a way to just indicate that the upstream uses https?  This would be the equivalent of `nginx.ingress.kubernetes.io/backend-protocol: HTTPS` or `traefik.ingress.kubernetes.io/router.tls: "true"` annotations in ingress controller mode.

**Comment by ilackarms** [comment]
hey @travisgroth currently there is no way to configure Gloo to perform client TLS to upstreams without also providing a source for certificates. this is not an envoy limitation however; gloo can be made to support an empty `SSLConfig` on upstreams which should be translated to an empty ssl context for Envoy. cc @kdorosh
