### ISSUE TITLE
Set retries by default

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3241]
**Is your feature request related to a problem? Please describe.**
When setting up a `VirtualService`, [retries](https://docs.solo.io/gloo/latest/guides/traffic_management/request_processing/retries/) need to be explicitly configured. This means that no retries will occur and any transient network issue will manifest itself at the downstream client.

**Describe the solution you'd like**
Some retries can be provided by default and overridden by the explicit config on the `VirtualService`

**Describe alternatives you've considered**
N/A

**Additional context**
[Istio by default will provide some retries](https://istio.io/latest/docs/concepts/traffic-management/#retries)

**Comment by kdorosh** [comment]
There's an argument for not doing retries (as some requests aren't idempotent and shouldn't be retried)

It would be nice to add a global setting that adds retries across the entire gateway, but explicitly.

This may tie into our work to template our config in delegated CRDs (e.g. default template for upstreams, delegating rate limit CRDs, access logging, etc.)

**Comment by vadimi** [comment]
It seems like envoy's default `connect-failure` retries would be harmless: https://www.envoyproxy.io/docs/envoy/v1.15.0/configuration/http/http_filters/router_filter#x-envoy-retry-on

`Envoy will attempt a retry if a request is failed because of a connection failure to the upstream server`
