### ISSUE TITLE
mix of valid and invalid VS regression test flake

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3247]
**Describe the bug**
Sample logs https://console.cloud.google.com/cloud-build/builds/a13c32e3-fddf-4263-b28a-e931933d9f87;step=14?project=solo-public

**To Reproduce**
Need to try to reproduce locally and see if this is due to test pollution or not.

**Expected behavior**
No flakes

**Additional context**
Logs from this PR https://github.com/solo-io/gloo/pull/3246

**Comment by sam-heilbron** [comment]
This work has been backported to 1.8, 1.7. and 1.6 LTS branches. Since the work includes an actual bug fix that this causing this flake, I will only mark this issue as done once those releases are completed.

**Comment by sam-heilbron** [comment]
Released in 1.6.x, 1.7.x, 1.8.x and 1.9.x-beta
