### ISSUE TITLE
Issue with 1.4.0 upgrade via helm

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3250]
**Describe the bug**
`helm upgrade` does not work as the `Service` type for `apiserver-ui` was changed to `ClusterIP`.

**To Reproduce**
Install Helm 1.3.x, then upgrade to 1.4.0:
```
% helm upgrade glooe glooe/gloo-ee --namespace gloo-system \
   --set license_key=$GLOO_LICENSE_KEY \
   --version=1.4.0
Error: UPGRADE FAILED: cannot patch "apiserver-ui" with kind Service: Service "apiserver-ui" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

**Expected behavior**
Migration should happen transparently

**Additional context**
Related to https://github.com/solo-io/gloo/issues/3120
Might be worth parameterizing service type

**Comment by lgadban** [comment]
One solution is to delete `Service` `apiserver-ui` prior to upgrade

**Comment by lgadban** [comment]
Another issue with a "standard" upgrade, relating to the grafana deployment:
```
Warning  FailedAttachVolume  2m32s  attachdetach-controller                               Multi-Attach error for volume "pvc-dd3ab895-bbeb-11ea-8eb4-42010a800165" Volume is already used by pod(s) glooe-grafana-649b9fc9b4-dl7lr
  Warning  FailedMount         29s    kubelet, gke-upgrade-test-default-pool-2eccea09-3dg2  Unable to mount volumes for pod "glooe-grafana-7b99b9c6db-8swhh_gloo-system(fe516163-bbec-11ea-8eb4-42010a800165)": timeout expired waiting for volumes to attach or mount for pod "gloo-system"/"glooe-grafana-7b99b9c6db-8swhh". list of unmounted volumes=[storage]. list of unattached volumes=[config dashboards-gloo storage glooe-grafana-token-pvv96]
```

**Comment by lgadban** [comment]
The existing grafana steps from the [1.3.0+ upgrade](https://docs.solo.io/gloo/latest/operations/upgrading/1.3.0/) work to solve the grafana issues

**Comment by mlholland** [comment]
Looks like I've managed to reproduce the issue, then successfully upgrade gloo using lgadban's suggested fix with the following steps:

- Install gloo v 1.3.2 with helm: helm install gloo glooe/gloo-ee --namespace gloo-system --create-namespace --set-string license_key=$GLOO_LICENSE_KEY --version=1.3.2
- delete apiserver-ui service: kubectl delete svc apiserver-ui  --namespace gloo-system 
- upgrade gloo to v 1.4.0: helm upgrade gloo glooe/gloo-ee --namespace gloo-system --set license_key=$GLOO_LICENSE_KEY --version=1.4.0
- at this point, the apiserver-ui service is running again, and the glooctl dashboard command works as expected.

I'll add a note of this in the documentation.
