### ISSUE TITLE
Update the envoy docs for Gloo

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3263]
**Describe the requested changes**
See link to Gloo https://www.envoyproxy.io/docs/envoy/latest/start/start#other-use-cases and notice that the page it links to runs on a very old version of Gloo. we should update this

**Link to any relevant existing docs**
https://github.com/envoyproxy/envoy/blob/master/docs/root/start/distro/gloo.rst

**Comment by kdorosh** [comment]
We should add SMH and remove the dead projects from https://www.envoyproxy.io/community

**Comment by ned1313** [comment]
It looks like the other-use-cases links are gone. I have created a PR against the website repo to update the community list: https://github.com/envoyproxy/envoyproxy.github.io/pull/174

**Comment by ned1313** [comment]
Update has been merged into master.
