### ISSUE TITLE
Provide a JWT signing plugin

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3268]
**Is your feature request related to a problem? Please describe.**
A common use case for an API gateway is to sign/mint a new token based on various request attributes, auth data (e.g. OIDC UserInfo, etc.) for use upstream.

**Describe the solution you'd like**
A generic plugin that can be configured to create JWTs rather than needing to build an entire custom plugin

**Describe alternatives you've considered**
Currently this can be accomplished in an auth plugin

**Additional context**
N/A

**Comment by RichiCoder1** [comment]
Ideally this plugin would allow:
* Mounting multiple JWKs keys as secrets
* Automatically creating a signed JWT from principal details provided by previous ExtAuth filters
* Allowing the addition of claims, ideal using templates like other transform features
* Exposing a JWKS endpoint on a specific host

Example implementation: Ory Keto [JWT Authenticator](https://www.ory.sh/oathkeeper/docs/pipeline/authn#jwt) + [id_token Mutator](https://www.ory.sh/oathkeeper/docs/pipeline/mutator#id_token)

I've actually considered just using Ory, but the ExtAuth passthrough only supports gRPC (which they don't currently support) so it'd require either ditching GlooEE ExtAuth or writing a plugin

**Comment by chrisgaun** [comment]
@kevin-shelaga can you add the ticket about pulling secret that we believe is related.

**Comment by kevin-shelaga** [comment]
@chrisgaun https://github.com/solo-io/gloo/issues/4051

**Comment by sam-heilbron** [comment]
Part 1: Does http passthrough (https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/passthrough_auth/http/) resolve this? If so, write up docs outlining how to use http passthrough + ory.
