### ISSUE TITLE
Enable to open custom ports on gatewayproxy service via helm value options

### ISSUE THREAD

**Issue by aqt01** [solo-io/gloo#3301]
**Is your feature request related to a problem? Please describe.**
When opening custom ports, like 8081 for serving http or 8545 for ethereum JSON-RPC, you need to perform it manually editing the existing service created by helm instead of defining it via helm chart values. The only ports i see available for editing are `gatewayProxies.gatewayProxy.service.httpPort` and `gatewayProxies.gatewayProxy.service.httpsPort` on the [gloo helm chart values](https://docs.solo.io/gloo/latest/reference/helm_chart_values/)

**Describe the solution you'd like**
An option in the helm chart values like the [nginx-ingres-controller](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/) has `controller.service.customPorts` where you can define a list of custom ports to be opened on the service object.

**Additional context**
Currenlty i'm working with spinning up/configuring blockchains to be served using gloo and it will be very useful if this option is present

**Comment by kdorosh** [comment]
This is a reasonable request. In the meantime, you should be able to accomplish what you want using kustomize with helm 3, see our tutorial here: https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/helm_advanced/

**Comment by aqt01** [comment]
@kdorosh Thanks you!
Yeah that's currently the way we take in the meantime!
