### ISSUE TITLE
e2e test flake, appears to hit real k8s cluster when it shouldn't

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3304]
**Describe the bug**
Sample failed log https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=b20a21e0-5ccf-4386-9b5d-a8af9e4ec3d6 , from https://github.com/solo-io/gloo/pull/3300#issuecomment-655732843

**Expected behavior**
No flakes

**Additional context**
Third or fourth time I've seen in CI. Unit tests shouldn't have flakes or hit clusters, should be easy to resolve.

**Comment by kdorosh** [comment]
again https://console.cloud.google.com/cloud-build/builds/3f02c52d-4140-412f-a14a-8646d7f02cf8;step=8?project=solo-public

**Comment by sam-heilbron** [comment]
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=90d014a8-b29f-4cb4-b653-097f7ab59093

**Comment by sam-heilbron** [comment]
This test has been moved from our e2e tests to its own regression suite (to run on a kube cluster). 

PR which moved this test: https://github.com/solo-io/gloo/pull/5725
