### ISSUE TITLE
 access log %UPSTREAM_CLUSTER% is empty with failed 4xx responses

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3314]
**Describe the bug**
Access logs do not populate %UPSTREAM_CLUSTER% when upstream/cluster is matched but there is a 4xx failure

**To Reproduce**
1. Deploy route with some security enabled (e.g. jwt)
2. Configure access logs (e.g. see below)
3. curl to route without credentials (e.g. auth jwt header)
4. Access logs look like below with empty %UPSTREAM_CLUSTER%
```

  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            authority: '%REQ(:AUTHORITY)%'
            clientId: '%REQ(CUSTOM-CLIENT-ID)%'
            duration: '%DURATION%'
            error: '%DYNAMIC_METADATA(io.solo.transformation:error)%'
            host: '%REQ(:HOST)%'
            httpMethod: '%REQ(:METHOD)%'
            matcher: '%DYNAMIC_METADATA(io.solo.transformation:matcher)%'
            path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
            pod: '%DYNAMIC_METADATA(io.solo.transformation:pod)%'
            podName: '%DYNAMIC_METADATA(io.solo.transformation:pod_name)%'
            protocol: '%PROTOCOL%'
            requestDuration: '%REQUEST_DURATION%'
            requestId: '%REQ(X-REQUEST-ID)%'
            responseCode: '%RESPONSE_CODE%'
            responseDuration: '%RESPONSE_DURATION%'
            startTime: '%START_TIME%'
            upstream: '%UPSTREAM_CLUSTER%'
            wafLog: '%FILTER_STATE(io.solo.modsecurity.audit_log)%'
          path: /dev/stdout
```

`{"authority":"35.203.154.113","path":"/static-pet","protocol":"HTTP/2","requestDuration":"0","startTime":"2020-07-09T18:48:42.939Z","duration":"0","upstream":"-","error":"-","pod":"-","wafLog":"-","clientId":"-","responseCode":"401","podName":"-","responseDuration":"-","requestId":"38f69b3b-980f-9cfc-a081-65571268aa20","matcher":"-","httpMethod":"GET","host":"-"}`

There is not a `cluster 'XXX' match for URL '/xxx'` entry in the debug logs as I'd expect, but the upstream has to have been matched in order to determine the JWT config.

**Comment by kdorosh** [comment]
@bdecoste to add context explaining why this is impossible

**Comment by bdecoste** [comment]
At the extauth and rate-liomit filters the upstream has not yet been chosen (e.g. canary with multi-upstreams) so a 4xx from either of these filters cannot populate this field in the access logs
