### ISSUE TITLE
Add logout functionality to OIDC feature

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3328]
**Is your feature request related to a problem? Please describe.**
Currently there is no mechanism by which you can "log out" of an existing "session" that was established via the OIDC feature.

**Describe the solution you'd like**
An option to logout/destroy the session established via OIDC

**Describe alternatives you've considered**
If the IdP supports logout functionality, that can be used, but it still will not logout of the Gloo session

**Additional context**
OIDC spec should be used, e.g. https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

**Comment by kevinnesta** [comment]
Hi @lgadban ,
I'm really interested in that enhancement! 👍
