### ISSUE TITLE
Enable Gloo/Envoy to dynamically load WAF/mod_security rules from file mounted into pod

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3329]
**Is your feature request related to a problem? Please describe.**
Need to be able to dynamically load large mod_security rule files into Gloo/Envoy without requiring a restart. Do not want to rely on CRDs due to size concerns and format of generated rules (e.g. trustwave).

**Describe the solution you'd like**
Possibly mount a native rules file into Gloo/Envoy pod to drive mod_security config.

**Comment by PankajMoolrajani** [comment]
We are still facing this issue. We use k8s configmaps as recommended by gloo enterprise, but the modsecurity rules are not getting picked up gloo-ee proxy whenever changes are made to the configmap.

**Comment by chrisgaun** [comment]
@PankajMoolrajani I moved this into priority list

**Comment by ianmacclancy** [comment]
@PankajMoolrajani can you help me better understand the request? 

"We use k8s configmaps as recommended by gloo enterprise" - can you point me to the documentation you are using for my reference 

I understand the ask as: When you modify your ModSecurity rule files specified in your VS or Gateway you want these changes to your file to be automatically picked up by envoy. 

If so: 
- You can trigger the updates right now by versioning your file names and updating the reference to them in VS or Gateway CRDs. The changes are not picked up as there is no change to the CRDs

**Comment by PankajMoolrajani** [comment]
Yes that's the ask. Like any other config changes to VS or Gateway, these rules even though externalized in a config file should get picked up automatically.

**Comment by ianmacclancy** [comment]
Okay, I am working on API changes to separate configmap from file input as we can pick up changes from configmap dynamically. For now if you need changes picked up you can version the filename to indicate that there has been a change to the file content. That will be picked up.

**Comment by ianmacclancy** [comment]
@PankajMoolrajani - Im releasing the fix in the latest 1.13.x, what minor version are you on? I can start backports if you need it in earlier minors.

**Comment by ianmacclancy** [comment]
Released to 1.13.0-beta9 - closing with this release

**Comment by PankajMoolrajani** [comment]
@ianmacclancy i will check on what version we have and will update u here.
