### ISSUE TITLE
Gloo/GlooE images should be created as non-root user

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3346]
**Describe the bug**
Gloo/GlooE images are created as root user

**Expected behavior**
Gloo/GlooE images should be created as non-root user

**Comment by arianaw66** [comment]
Problem seen with gloo v1.3.25/glooE v1.3.6, specifically on gateway, grpcserver-ui, and gloo-ee-envoy-wrapper images.

**Comment by arianaw66** [comment]
(Needs to be in solo-projects too. I guess `resolvesIssue: false` didn't work since I added it late.)

**Comment by arianaw66** [comment]
Needs to be back-ported
