### ISSUE TITLE
Panic in rate-limit pod

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3356]
**Describe the bug**
A panic occurring when redis is unavailable:
```
{"level":"info","ts":"2020-07-03T12:49:06.593Z","caller":"redis/driver_impl.go:54","msg":"connecting to redis on tcp redis:6379 with pool size 10"}
panic: dial tcp 10.233.36.120:6379: connect: connection refused
goroutine 1 [running]:
github.com/solo-io/rate-limiter/pkg/redis.checkError(0x27ce940, 0xc0000d4dc0)
	/go/pkg/mod/github.com/solo-io/rate-limiter@v0.0.3/pkg/redis/driver_impl.go:25 +0x96
github.com/solo-io/rate-limiter/pkg/redis.NewPoolImpl(0x2816300, 0xc0002f8b40, 0xc000054052, 0x3, 0xc00005402a, 0xa, 0xa, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/rate-limiter@v0.0.3/pkg/redis/driver_impl.go:56 +0x29a
github.com/solo-io/rate-limiter/cmd/service/runner.RunWithSettings(0xc00036b560, 0x2816300, 0xc0002f8b40, 0x46a0, 0x46a1, 0x2383, 0x1f472a4, 0x4, 0x0, 0xc000054052, ...)
	/go/pkg/mod/github.com/solo-io/rate-limiter@v0.0.3/cmd/service/runner/runner.go:60 +0x90e
github.com/solo-io/rate-limiter/cmd/service/runner.Run(0xc00036b560, 0x2816300, 0xc0002f8b40, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/rate-limiter@v0.0.3/cmd/service/runner/runner.go:103 +0xc6
github.com/solo-io/solo-projects/projects/rate-limit/pkg/runner.RunWithClientSettings(0x2816300, 0xc0002f8b40, 0xc00036b560, 0xc00005408d, 0x9, 0x0, 0x0)
	/workspace/solo-projects/projects/rate-limit/pkg/runner/run.go:29 +0x65
github.com/solo-io/solo-projects/projects/rate-limit/pkg/runner.RunWithClientSettingsBlocking(0xc00005408d, 0x9)
	/workspace/solo-projects/projects/rate-limit/pkg/runner/run.go:24 +0xe8
github.com/solo-io/solo-projects/projects/rate-limit/pkg/runner.Run()
	/workspace/solo-projects/projects/rate-limit/pkg/runner/run.go:19 +0x43
main.main()
	/workspace/solo-projects/projects/rate-limit/cmd/main.go:8 +0x20
```

**To Reproduce**
Unsure on reproducibility

**Expected behavior**
No panic

**Additional context**
```
quay.io/solo-io/rate-limit-ee:1.3.8
rate-limiter@v0.0.3
```

**Comment by AlexKaiserTK** [comment]
Hi @lgadban , did you have a look into this?

**Comment by lgadban** [comment]
Hi @AlexKaiserTK,

We've done some research, and this is the current "expected" behavior when the rate-limit pod is unable to connect to redis.

We are looking at a few changes to this behavior, e.g. not panicking/crashing the pod and moving the back-off retry logic inside the app, recording a metric for when redis is unreachable, etc.

**Comment by AlexKaiserTK** [comment]
Is it an indication the redis deployment should be scaled?

**Comment by lgadban** [comment]
I would not expect it to indicate redis should be scaled.

This error is probably most likely to happen when the rate limit container has started before the redis container is fully ready, in which case rate limit will panic and error out, causing Kubernetes to restart the pod. The behavior would be similar if we coded in a back-off retry.

How frequently are you seeing this issue occur? If it is mainly happening during installation or maintenance, I would expect this to be normal.

**Comment by AlexKaiserTK** [comment]
Hi @lgadban, I will investigate this. I had the feeling it occurs during load test, but could be wrong. I will come back to you on this once more info is available from our side.

**Comment by lgadban** [comment]
Hi @AlexKaiserTK -- I will close this issue for now. If you see this behavior surface again feel free to reopen.
