### ISSUE TITLE
How can I remove x-envoy-original-path in request header added by gloo?

### ISSUE THREAD

**Issue by wyjwl** [solo-io/gloo#3379]
I'm using the prefixRewrite like this:
   routes:
      - matchers:
          - prefix: /api/
        routeAction:
          single:
            upstream:
              name: xxx
              namespace: xxx
        options:
          prefixRewrite: /
and then gloo will add the original api path into request header as **x-envoy-original-path**.

Is there some way I can suppress gloo to add any these kind of headers into my request? Many thanks~

**Comment by wyjwl** [comment]
It's not working even I use requestHeadersToRemove

**Comment by asayah** [comment]
requestHeadersToRemove will not work because these headers are added by the envoy http router. 

This feature exists on envoy but it is not exposed using Gloo API yet.
for more info https://github.com/solo-io/gloo/issues/3444
Thanks.
