### ISSUE TITLE
Enable deployment of api-server to expose over https 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3384]
**Is your feature request related to a problem? Please describe.**
Id like to expose the api-server over https instead of the hardcoded http

**Describe the solution you'd like**
Enable deployment of api-server to expose over https including via helm

**Comment by EItanya** [comment]
Reopening after discussion that the solution given was not exactly the one requested. The api server was exposed via HTTPS using the generated certs, when gloo is running in mtls mode. However, the initial request was to expose the apiserver over https using a custom cert designated in a secret.
