### ISSUE TITLE
Support Istio 1.7 with Gloo 

### ISSUE THREAD

**Issue by bettyjunod** [solo-io/gloo#3388]
**Is your feature request related to a problem? Please describe.**
Istio 1.7 is scheduled to be released Aug 10th and we need to make sure Gloo integration with Istio works with the latest release
https://github.com/istio/istio/wiki/Istio-Release-1.7

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by christian-posta** [comment]
It works, just tried on 1.7-beta.2

Next step is just to doc
