### ISSUE TITLE
Create docs dropdown for latest of each stable release (see 1.3 is 1.3.0 not `1.3.<latest>`)

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3402]
**Is your feature request related to a problem? Please describe.**
We need more updated docs for stable releases

**Describe the solution you'd like**
The 1.3 docs should be the latest 1.3 docs, not 1.3.0

**Describe alternatives you've considered**

**Additional context**

**Comment by kdorosh** [comment]
We shouldn't use the terminology "latest" without an associated version because it is unclear

**Comment by lgadban** [comment]
To add to previous comment, something like the following (for the current state) would be very useful:
-     latest (1.5.x)
-     1.4.x
-     1.3.x

Or possibly some delineation between 'latest', 'stable' and 'betas'

**Comment by lgadban** [comment]
Not sure if we are tracking it on this issue, but the following enhancements would help with other problems related to the docs version issues:

- Banner notifying when you are on an old version of the docs
- Add a dropdown on the old versions of the docs (or link in previously mentioned banner) to get to the latest docs without needing to navigate there manually through the full website)
