### ISSUE TITLE
add stat to gloo and/or gateway pod for detecting the config validation status 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3408]
**Is your feature request related to a problem? Please describe.**
I'd like a prometheus metric to detect whether there is invalid configuration (e.g. route with a missing upstream/cluster)

**Describe the solution you'd like**
add stat to gloo and/or gateway pod for detecting the config validation status

**Comment by kdorosh** [comment]
This is already calculated internally on each sync, we just need to expose this as a metric https://github.com/solo-io/gloo/blob/v1.5.0-beta19/projects/gateway/pkg/validation/validator.go#L50-L53
