### ISSUE TITLE
Helm value for setting RateLimit descriptors in Settings

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3422]
**Is your feature request related to a problem? Please describe.**
No "standard" way to add in rate limit `descriptors` during installation via `helm`

**Describe the solution you'd like**
Expose a `helm` value for rate limit `descriptors` in the gloo `Settings`

**Describe alternatives you've considered**
Post rendering customization is an option but does not fit all organizations
`RateLimitConfig` CR will alleviate this need in future versions

**Additional context**
N/A

**Comment by kdorosh** [comment]
Related issue: https://github.com/solo-io/gloo/issues/3470 As a result of this, we will need to add these overrides to both Gloo and GlooE charts, until we de-duplicate

**Comment by kdorosh** [comment]
Reopening until we backport to 1.4 and make same changes to GlooE
