### ISSUE TITLE
Remove unused `customresourcedefinitions` permissions in apiserver Role

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3424]
**Describe the bug**
When installing the Gloo UI in a namespaced installation, there are permissions for `customresourcedefinitions` in the `Role` being created. This causes RBAC issues when the installer does not have the correct permissions, as well as the fact that `customresourcedefinitions` are not namespaced resources.

**To Reproduce**
Install Gloo as a namespaced installation with a non-cluster admin type account

**Expected behavior**
This permission should be confirmed to be unused and removed from the namespaced installation, i.e. `Role`, but if it's not being used at all, should probably be removed entirely. Additionally there may be tech debt associated with this.

**Additional context**
https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/templates/36-apiserver-role.yaml#L18-L20
https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/templates/36-apiserver-role.yaml#L38-L40

**Comment by arianaw66** [comment]
Attempted to reproduce in minikube by doing the following:

- `vim gloo/install/helm/gloo/templates/100-crds.yaml` and delete first and last lines to make this apply-able
- Apply crds: `k apply -f gloo/install/helm/gloo/templates/100-crds.yaml`
- Create a client cert and a user as shown here: https://medium.com/@HoussemDellai/rbac-with-kubernetes-in-minikube-4deed658ea7b
- `k apply -f myClusterRole.yaml`
- `k create ns gloo-system`
- `k apply -f myRoleBinding.yaml`
- `kubectl config use-context user1-context`
- `helm install gloo glooe/gloo-ee --namespace gloo-system --skip-crds --values singleNamespace.yaml`

where (change these to .yaml- GitHub didn't let me upload that file type)...

myClusterRole.yaml (this is based on the built-in `admin` ClusterRole, with the addition of the `gateway.solo.io` apiGroup):
[myClusterRole.txt](https://github.com/solo-io/gloo/files/5043531/myClusterRole.txt)

myRoleBinding.yaml (should ensure user1 only has access to the gloo-system namespace):
[myRoleBinding.txt](https://github.com/solo-io/gloo/files/5043532/role-binding.txt)

singleNamespace.yaml:
[singleNamespace.txt](https://github.com/solo-io/gloo/files/5043534/singleNamespace.txt)

**BUT I found that when I `k get clusterrole myclusterrole -oyaml` (as the default user with cluster permissions), the `gateway.solo.io` apiGroup isn't present in the rules.** I'm not sure why this content isn't being accepted.
As a result, I get this error when I try to do the `helm install` step above: `Error from server (Forbidden): gateways.gateway.solo.io is forbidden: User "user1" cannot list resource "gateways" in API group "gateway.solo.io" in the namespace "gloo-system"`

To clean up and start over:
- get rid of the cert directory: `rm -rf cert`
- I've also been getting rid of the minikube certs but am not sure if this is necessary: `rm ~/.minikube/ca.key ~/.minikube/ca.crt`
- get rid of the new context and user: `k config unset contexts.user1-context`, `k config unset users.user1`
- `minikuberestart`

**Comment by kdorosh** [comment]
To reproduce:

- create the following file, called `vals.yaml`
```yaml
global:
  glooRbac:
    namespaced: true
settings:
  singleNamespace: true
```
- install GlooE, `glooctl install gateway enterprise --license-key $LICENSE_KEY --values vals.yaml --version 1.5.0-beta7`
- get the apiserver role permissions, `kg role -n gloo-system apiserver-ui -oyaml`. note the following:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2020-08-17T17:20:39Z"
  labels:
    app: gloo
    gloo: rbac
  name: apiserver-ui
  namespace: gloo-system
  resourceVersion: "985"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/gloo-system/roles/apiserver-ui
  uid: 24b3f2d0-3fc6-491d-9a53-6572888fb495
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - gloo.solo.io
  resources:
  - artifacts
  - upstreams
  - upstreamgroups
  - proxies
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gloo.solo.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - gateway.solo.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.solo.io
  resources:
  - virtualservices
  - routetables
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create      # <---  this is the problem
- apiGroups:
  - gloo.solo.io
  resources:
  - artifacts
  - settings
  - upstreams
  - upstreamgroups
  - proxies
  - secrets
  verbs:
  - create
  - update
  - delete
- apiGroups:
  - gateway.solo.io
  resources:
  - gateways
  verbs:
  - create
  - update
  - delete
- apiGroups:
  - gateway.solo.io
  resources:
  - virtualservices
  - routetables
  verbs:
  - create
  - update
  - delete
```
