### ISSUE TITLE
Document correct usage of body extractions

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3448]
**Describe the requested changes**
The main transformation docs don't specify how to use the parsed values of the request body when using a body extraction

**Link to any relevant existing docs**
https://docs.solo.io/gloo/latest/guides/traffic_management/request_processing/transformations/#extractors

The "_Extracted values can be used in two ways_" section should specify how to use the body when it's been extracted, e.g. when the body is json, you can use the fields of the body as specified here: https://docs.solo.io/gloo/latest/guides/traffic_management/request_processing/transformations/enrich_access_logs/#update-virtual-service

**Browser Information**
N/A

**Additional context**
N/A

**Comment by kdorosh** [comment]
While we're here, we should update the docs to use the new format (early vs regular transformations).

We should call out that body transformations are keyed on the body contents rather than the name of the extraction.
