### ISSUE TITLE
FEATURE: glooctl proxy log --log-level and --log-level-component

### ISSUE THREAD

**Issue by emayssat** [solo-io/gloo#3453]
**Is your feature request related to a problem? Please describe.**
I would like to debug a WASM filter and access the logs generated by that filter. 

**Describe the solution you'd like**
'glooctl proxy log' is a great command line. 
That being said it is not implemented correctly and additional option should be made available.
(1) That command should not change the log level of the underlying envoy proxy. Currently it sets everything to debug.
(2) Logs could be managed the same way they are with envoy. Use --log-level to set the log level for all sub components.
(3) To set the log level of an individual component (e.g. wasm filter), use the --log-level-component wasm=debug command line option.

**Describe alternatives you've considered**
Alternative is to kubectl proxy and reset the log levels using the envoy API, each time the 'glooctl proxy log' command is used
The most annoying part is that the 'glooctl proxy log' command reset the log level each time it is run as well.

**Additional context**
N/A

**Comment by kdorosh** [comment]
Related to https://github.com/solo-io/gloo/issues/2916
