### ISSUE TITLE
Allow users to access Dev Portal API's using Oauth

### ISSUE THREAD

**Issue by ekarlso** [solo-io/gloo#3476]
**Is your feature request related to a problem? Please describe.**
When using the developer portal currently can't use SSO integration with for example with OAUTH to consume the API's. 

**Describe the solution you'd like**
A Consumer should be able to authenticate with SSO and use that to test the API in the

**Describe alternatives you've considered**
OAUTH authentication with a token issuer or similar.

**Comment by chrisgaun** [comment]
We are currently workin on this and it should be available in next release

**Comment by chrisgaun** [comment]
Please check out Gloo Portal 0.6.0 as we now have OAuth integration for the APIs.
