### ISSUE TITLE
Clarify steps necessary for 1.4.x upgrades

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3487]
**Describe the requested changes**
Currently, the additional steps necessary for performing an upgrade to Gloo 1.4.x are part of the 1.3.x upgrade notice. This is not obvious to users and should be changed to make this more clear

**Link to any relevant existing docs**
https://docs.solo.io/gloo/latest/operations/upgrading/1.3.0/#upgrading

**Browser Information**
N/A

**Additional context**
N/A

**Comment by kdorosh** [comment]
We can just change the header name there to 1.3/1.4 upgrade guide.
