### ISSUE TITLE
glooctl rate limit interactive mode

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#349]
it ignores your choice and requires you specify a rate limit whether or not you want one

**Comment by mitchdraft** [comment]
it also ignores the name and namespace you specify in args and flags
ex:
glooctl create namespace myns -i --namespace gloo-system
-> Still prompts to enter a name and a namespace

**Comment by ilevine** [comment]
command used is `glooctl create vs myns -i --namespace gloo-system` in glooe command line

**Comment by rickducott** [comment]
```
[13:59:35] rick@Ricks-MBP-2:~/Downloads$ glooctl create virtualservice myvs -i -n gloo-system
? Add another domain for this virtual service (empty to skip)? []
? do you wish to add rate limiting to the virtual service [y/n]? y
? Limit requests over this unit of time for clients:  DAY
? how many requests per DAY? 1
? do you wish to add oidc auth to the virtual service [y/n]? n
? name of the resource:  myvs
? namespace of the resource:  gloo-system
```

**Comment by kdorosh** [comment]
I haven't been able to recreate the rate limit bug mentioned @mitchdraft any ideas here?

**Comment by mitchdraft** [comment]
I can't reproduce this anymore either, must have been fixed
