### ISSUE TITLE
Add a routing rule to a virtual service using a helm chart

### ISSUE THREAD

**Issue by vikrant82** [solo-io/gloo#3491]
This might be basic question. I wanted to check if it's possible to add a route to a virtual service via a helm chart. I want to add a new route to an existing virtual service (which might already have many routes) as part of another deployment. I don't want to use glooctl in this case.

**Comment by kdorosh** [comment]
You can use Gloo as a subchart and then add virtual services to your chart.

Adding a new route to an existing virtual service doesn't seem like a natural use case for helm to me though, as adding to a pre-existing resource feels imperative to me while helm is mostly declarative.

**Comment by kdorosh** [comment]
Closing as the question is answered. Feel free to reopen if there's followup discussion to be had
