### ISSUE TITLE
Unable to connect to upstream using TLS when using grpcui

### ISSUE THREAD

**Issue by daniel-sullivan** [solo-io/gloo#3505]
**Describe the bug**
When attempting to connect to upstream server when using grpcui, the following error occurs:

```
Failed to compute set of methods to expose: server does not support the reflection API
````

This appears to be similar to this bug:

https://github.com/envoyproxy/envoy/issues/8305

Where the responsibility for fixing this lies is hard to be sure but at the very least this issue should document the issue and solution for anyone searching in the future (I'm currently 5 hours into this damn problem)

**To Reproduce**
1. Setup a GRPC instance as per the documentation
2. Configure the VirtualService without SSL
3. Verify able to connect as expected using eg: ```grpcui -plaintext -authority api.grpc.dev.charm.internal api.grpc.dev.charm.internal:80```
4. Add SSL configuration to the VirtualService
5. See the "Failed to compute set of methods to expose: server does not support the reflection API" message.
6. Tail the logs using ```glooctl proxy logs -f```
7. Note the presence of the following:
```
977801619424] request headers complete (end_stream=false):
':method', 'POST'
':scheme', 'https'
':path', '/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo'
':authority', 'api.grpc.dev.charm.internal:443'
'content-type', 'application/grpc'
'user-agent', 'grpc-go/1.29.0'
'te', 'trailers'
'grpc-timeout', '9602108u'

[2020-08-12 11:49:13.836][18][debug][router] [external/envoy/source/common/router/router.cc:361] [C24][S1617583977801619424] no cluster match for URL '/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo'
[2020-08-12 11:49:13.836][18][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1520] [C24][S1617583977801619424] Sending local reply with details route_not_found
```
8. At this point you would expect the authority to be "api.grpc.dev.charm.internal" however it has ":443" appended to it. Whether this is correct behaviour or not I'm not sure - in the middle of a project so don't have a change to go digging into RFCs
9. Add the additional domain (api.grpc.dev.charm.internal:443) to VirtualService and confirm that the upstream is now responding correctly.

**Expected behavior**
Any of:
a) For there to be some wriggle room in the interpolation of the config (which I don't think is the best solution personally) - maybe automatically appending ":*" to any domain definitions if they don't already have a port descriptor
b) For the documentation to include a note that this is a potential gotcha with misbehaving clients

**Additional context**

Just a note: If either of the above expected behaviours sound suitable, I'm happy to code them up and put in a pull request!

**Comment by marcogschmidt** [comment]
Hi @daniel-sullivan , just to make sure I understand the issue correctly: when you add the `api.grpc.dev.charm.internal:443` domain to your Virtual Service, then the `Failed to compute set of methods to expose: server does not support the reflection API` error goes away?

**Comment by daniel-sullivan** [comment]
Hi @marcogschmidt, that's right. So basically for the following domains setting:

```
No SSL / api.grpc.dev.charm.internal - OK
SSL / api.grpc.dev.charm.internal - NG - no cluster match
SSL / [ api.grpc.dev.charm.internal, api.grpc.dev.charm.internal:443] - OK
SSL / api.grpc.dev.charm.internal* - OK
```

I've confirmed that the authority is set as ```api.grpc.dev.charm.internal:443 ``` whenever using grpcui or go grpc library using unmodified client details eg:

```
creds = credentials.NewClientTLSFromCert(< cert pool containing root cert >, "")
conn = grpc.Dial(backendAddress, grpc.WithTransportCredentials(creds), grpc.WithBlock())
```

**Comment by gavinbunney** [comment]
We've found this issue as well, and confirm that adding two domains, one with a port and one without makes it behave correctly:

```
  virtualHost:
    domains:
    - grpcservice.example.com
    - grpcservice.example.com:443
```

**Comment by ngtuna** [comment]
Today I learned domain must include port if it's non-443 🤦
