### ISSUE TITLE
Configurable ordering of JWT and EXTAUTH

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3526]
**Is your feature request related to a problem? Please describe.**
Id like to be able to configure the ordering of jwt and extauth similar to how GlooE allows the ordering of rate-limit and extauth via `rateLimitBeforeAuth`

**Describe the solution you'd like**
Configurable ordering of JWT and EXTAUTH similar to `rateLimitBeforeAuth`

**Comment by lgadban** [comment]
Related/dupe: https://github.com/solo-io/gloo/issues/2591

**Comment by kdorosh** [comment]
closing as duplicate
