### ISSUE TITLE
support configurable domain in for rate-limit config

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3537]
**Is your feature request related to a problem? Please describe.**
Currently the rate-limit domain is hardcoded to "custom": https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/ratelimit/plugin.go#L19

I'd like this to be configurable

**Describe the solution you'd like**
support configurable domain in for rate-limit config

**Comment by bdecoste** [comment]
would be great if it used the virtual service name + namespace

**Comment by pasdam** [comment]
It would be good to document this in the [rate limit guide](https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/envoy/), as I spent quite some time to understand  what was going on, as I thought I misconfigured it
