### ISSUE TITLE
gateway pod hangs if unable to connect to gloo validation

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3553]
**Describe the bug**
gateway pod hangs with `starting proxy validation client... this may take a moment` if unable to connecto to gloo validation 

**To Reproduce**
1. Deploy Gloo normally
2. Switch 9988 in gloo pod&service to 9888
3. Restart gateway pod

**Expected behavior**
Gateway pod does not hang and provides better feedback on the issue.

**Comment by kdorosh** [comment]
This is desired behavior of the `VALIDATION_MUST_START` env var is set to true.

https://github.com/solo-io/gloo/blob/v1.5.0-beta19/install/helm/gloo/templates/5-gateway-deployment.yaml#L76-L77

Is there another issue here, or can we close this one out?

**Comment by sirrapa** [comment]
The actual cause was the use of `commonLabels` in the kustomize.yml file.
The labels defined were also added to the `selector` labels in the service resources, but not to the `matchSelector` labels in the deployment resources, resulting that the service resources had no backend to route too.
