### ISSUE TITLE
Control plane should remove duplicate routes

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3564]
**Is your feature request related to a problem? Please describe.**
Duplicate routes propagate through control plane to envoy

**Describe the solution you'd like**
To remove control and data plane unnecessary overhead the control plane should remove duplicate routes.

Related: https://github.com/solo-io/gloo/issues/3334

Perhaps a settings param to either remove or warn about duplicates.

**Comment by kdorosh** [comment]
This is an intended behavior. We have recently added support for reporting warnings on duplicate routes, however, which should solve the UX ask here: https://github.com/solo-io/gloo/pull/4032
