### ISSUE TITLE
Allow setting internal redirect configurations in envoy for route(s)

### ISSUE THREAD

**Issue by jimmy-ho** [solo-io/gloo#3566]
**Is your feature request related to a problem? Please describe.**
At the moment any proxying of APIs that may be doing internal redirects (such as for with/without ending slashes) for URLs using a path prefix will fail, as the redirect omits having the original path prefix as the upstream does not know about it.

Example:
`https://test.com/api-1/v1/test -> 301 internal redirect /v1/test/ -> https://test.com/v1/test/`
as the upstream redirect is passed right through.

This is due to the default envoy internal redirect behaviour, it does nothing and one cannot apply settings for it via the VirtualService route(s) configurations.

**Describe the solution you'd like**
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#internal-redirects

There are 2 settings that should be added to be able to be set:

1. **internal_redirect_policy**, this is needed to allow different 30x codes, one needed is **301**, default is **302** only, and
2. **internal_redirect_action**, by default it is **PASS_THROUGH_INTERNAL_REDIRECT**, when one needs to set it to **HANDLE_INTERNAL_REDIRECT** for the issue described for a route

Maybe this can be all automatically set if one does prefixRewrites will be an easier solution for all.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

Do comment and let me know if there are alternatives to the above I have missed, but seems like this is something that is missing currently.

**Comment by jimmy-ho** [comment]
I do see these internal redirect settings here btw:
https://docs.solo.io/gloo/latest/reference/api/envoy/config/route/v3/route_components.proto.sk/#routeaction

but I'm not sure how one can use them?

**Comment by kdorosh** [comment]
After looking into the API, we don't expose this envoy feature. A very reasonable use case -- will talk with the team about timeline for being able to tackle this one.
