### ISSUE TITLE
Report missing secrets for OIDC AuthConfigs

### ISSUE THREAD

**Issue by law10k** [solo-io/gloo#3568]
**Is your feature request related to a problem? Please describe.**
No way to perform validation that the secret referenced in an OIDC `AuthConfig` is preset

**Describe the solution you'd like**
Status of `AuthConfig` to have a warning when it references a non-existing `Secret`
`glooctl check` to be able to warn/catch this scenario

**Describe alternatives you've considered**
N/A

**Additional context**
Related:
https://github.com/solo-io/gloo/issues/2797
https://github.com/solo-io/gloo/issues/3358

**Comment by kdorosh** [comment]
was fixed with https://github.com/solo-io/gloo/issues/3358
