### ISSUE TITLE
Document how to create the DevPortal objects with CRDs

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3576]
**Describe the requested changes**
The documentation explains how to create an API from the UI, but not from the CLI.
So, a user needs to so some reverse engineering to determine what CRDs are generated.

**Link to any relevant existing docs**
https://docs.solo.io/gloo/latest/guides/dev_portal/

**Comment by marcogschmidt** [comment]
The Gloo docs now [reference](https://docs.solo.io/gloo/latest/guides/dev_portal/) the dev portal docs, which contain a [guide](https://docs.solo.io/dev-portal/latest/guides/getting_started/part_1/) on how to create an API from the CLI.
