### ISSUE TITLE
Bump to k8s 18.x

### ISSUE THREAD

**Issue by arianaw66** [solo-io/gloo#3579]
Will include:
- [ ] changes to [reporting-client](https://github.com/solo-io/reporting-client) which uses gloo interface(s) based on k8s functions
- [ ] updating wasme to k8s 18.x (https://github.com/solo-io/wasme/issues/164)
- [ ] pulling in [solo-kit k8s 18.x changes](https://github.com/solo-io/solo-kit/pull/370/files)
- [ ] pulling in [go-utils k8s 18.x changes](https://github.com/solo-io/go-utils/pull/419/files)

**Comment by arianaw66** [comment]
This was blocked by a cyclic dependency between wasme and gloo that was making it impossible to bump the solo-kit version in either. Thus, wasme was split into 2 submodules, one that depends on gloo, and one that gloo depends on.

Work on this can now proceed. The part of wasme that gloo depends on still needs to be updated but not the part that depends on gloo.

When this is done, we should also close out https://github.com/solo-io/gloo/issues/3478 and the corresponding Asana issue.

Helpful link to k8s.io repos: https://github.com/kubernetes

**Comment by kdorosh** [comment]
reopening until enterprise is also updated
