### ISSUE TITLE
Several Gloo Ingress instances do not work in one cluster

### ISSUE THREAD

**Issue by pbchekin** [solo-io/gloo#3587]
**Describe the bug**
Several Gloo Ingress instances can be installed to the same cluster to different namespaces, but they cannot work together, because they find several ingress-proxy services and report an error.

**To Reproduce**
1. Install two Gloo Ingress instances to the same cluster to different namespaces, let's say `gloo-public` and `gloo-private`
2. Both ingress instances do not work with the following error message:
```
{"level":"error","ts":"2020-09-01T23:08:24.228Z","logger":"ingress.v1.event_loop.ingress","caller":"setup/setup_syncer.go:280","msg":"error: ingress_st
atus_event_loop: failed to get lb status: expected 1 ingress service, found [{ingress-proxy gloo-private} {ingress-proxy gloo-public}]","version":"1.4
.2","stacktrace":"github.com/solo-io/gloo/projects/ingress/pkg/setup.RunIngress.func1\n\t/workspace/gloo/projects/ingress/pkg/setup/setup_syncer.go:280
"}
```

**Expected behavior**
Several Gloo Ingress instances can be installed to the same cluster and work well as long as they installed to different namespaces.

**Additional context**
- Gloo version 1.4.2
- The root cause is in `projects/ingress/pkg/setup/setup_syncer.go:201`:
  ```
		// note (ilackarms): we must set the selector correctly here or the status syncer will not work
		// the selector should return exactly 1 service which is our <install-namespace>.ingress-proxy service
		// TODO (ilackarms): make the service labels configurable
		ingressServiceClient := service.NewClientWithSelector(kubeServiceClient, map[string]string{
			"gloo": "ingress-proxy",
		})
  ```
  This client finds several ingress-proxy services instead of one. A potential solution is to make the service label configurable, or to pick one service in the namespce where ingress controller is running.

**Comment by kdorosh** [comment]
Is this use case satisfied by the work done here? https://github.com/solo-io/gloo/pull/3053

i.e., setting the ingress class to allow multiple gloo controllers to partition ingresses?

**Comment by pbchekin** [comment]
> Is this use case satisfied by the work done here? #3053
> 
> i.e., setting the ingress class to allow multiple gloo controllers to partition ingresses?

Steps to run several Gloo Ingress instances in the same cluster:
1. Deploy these instances to separate namespaces
2. Set `ingress.requireIngressClass` to `true`
3. Set `ingress.customIngressClass` to a unique value for each instance
4. Set `ingressProxy.label` to a unique value for each instance

Doing only 1..3 without 4 is not enough, see the code snippet.
