### ISSUE TITLE
Install script should install latest stable, not beta by default

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#3589]
As the title says, I would like to propose that by default the latest stable glooctl should be installed when following the docs and not beta versions as they can contain many issues.

```
curl -sL https://run.solo.io/gloo/install | sh
```

```
https://raw.githubusercontent.com/solo-io/gloo/master/projects/gloo/cli/install.sh
```

```
https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/
```

**Comment by kdorosh** [comment]
It would also be nice to update our docs/install instructions to have 
```
curl -sL https://run.solo.io/gloo/install | GLOO_VERSION=$VERSION sh
```
where the version is auto generated when we create docs

**Comment by mlholland** [comment]
Regarding the original change, I have a simple change to the install script to ignore beta versions when it gets a list of versions to instal, which will make it instead default to the newest non-beta version. I'm less sure on how to immediately perform the second docs change.
