### ISSUE TITLE
Provide declarative istio integration option

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3646]
**Is your feature request related to a problem? Please describe.**
The new `glooctl istio inject` feature is very useful for testing out the istio integration and quickly getting started, but is a manual step that is not a great fit for declarative style approaches, i.e. a `helm` only install in a production cluster.

**Describe the solution you'd like**
Some way to have the istio integration declarative, more than likely baked into the helm charts. This obviously can cause problems with which versions of istio we want to build integration with, so pros and cons should be evaluated.

**Comment by Sodman** [comment]
Could you use `global.istioSDS.enabled=true` in helm values? This will inject the istio and sds sidecars, as well as adding the `gateway_proxy_sds` cluster to the gateway-proxy configmap.

If the default istio version provided doesn't work for you, you can override it and define your own custom sidecar(s) using `global.istioSDS.customSidecars`. ([Example from the helm tests](https://github.com/solo-io/gloo/blob/master/install/test/val_custom_istio_sidecar.yaml))

Either way this should probably be documented better, right now the values are at the bottom of the [helm values references docs](https://docs.solo.io/gloo/latest/reference/helm_chart_values/)

**Comment by lgadban** [comment]
Those values should definitely work.

I missed them initially but I think mentioning that there is a helm equivalent to `glooctl istio inject` on the [integration doc](https://docs.solo.io/gloo/latest/guides/integrations/service_mesh/gloo_istio_mtls/) would be sufficient! (And maybe link to the full helm values ref)

Side note, there is a typo in the integration doc as well:
>When we ran `glooctl inject istio` ...
