### ISSUE TITLE
Add a docs landing page

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#3655]
**Describe the requested changes**
New users of Gloo and other solo.io projects learn pretty quickly that docs are rooted at docs.solo.io.  However, if you visit http://docs.solo.io you are 404 redirected to the solo.io home page.  This violates the Principle of Least Astonishment.  The expectation is that there would be a docs landing page that allow easy navigation to the latest docs for each project.

**Comment by artberger** [comment]
I think this is resolved. Also, we'll be updating the landing page as part of the website 2.0 rehaul in Q1 2022.
