### ISSUE TITLE
support OPA bundle file format 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3671]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to deploy policies to extauth in the bundle format (e.g. bundle.tar.gz)

For example, `kubectl -n gloo-system create configmap opa-bundle --from-file=/Users/bdecoste/solo/opa/bundle.tar.gz`

**Describe the solution you'd like**
support OPA bundle file format

**Comment by RichiCoder1** [comment]
Related-ish: https://github.com/solo-io/gloo/issues/3622

Would be nice if it could also download from S3/Urls, but just being able to use bundles would also work.
