### ISSUE TITLE
Modifying configs on a TLS enabled Upstream results in 503s

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3673]
**Describe the bug**
When changing the state of an `Upstream` that is TLS enabled, or even when performing an upgrade from plaintext to TLS, envoy will start returning 503s.

**To Reproduce**
TLS upgrade example when using discovered upstreams:
1. Modify `Upstream` to contain an `sslConfig`
2. `curl` to endpoint that should work, receive a 503 for no healthy upstream
```
% curl http://localhost:8080/
no healthy upstream
```
3. Delete `gateway-proxy` pod
4. `curl` same endpoint, see correct response
```
% curl http://localhost:8080/
hello, world
```

**Expected behavior**
Modifying configuration on a TLS `Upstream` or performing a TLS upgrade should work without needing to bounce envoy

**Additional context**
GlooE 1.4.8, testing other versions (will update here)

**Comment by kdorosh** [comment]
tls config not required to reproduce -- any change to upstream may trigger (e.g. change lb config)
