### ISSUE TITLE
Using a CA cert with OIDC

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3675]
**Describe the requested changes**
It was documented previously:
https://docs.solo.io/gloo/0-20-13/gloo_routing/virtual_services/security/oauth/dex/#setup-dex-ca-in-gloo

But it's not anymore.

**Comment by ned1313** [comment]
Discussed with Marco and the CA portion was removed to simplify the deployment guide. I am going to add a separate guide that outlines how to configure extauth with an external CA.
