### ISSUE TITLE
Stop creating the Settings CRD when the api-server starts

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3677]
**Describe the bug**
When setting the Helm value `settings.create` to `false`, the `api-server` Pod shouldn't create it.
I've checked with @marcogschmidt  and it looks like it should have been done by this PR(https://github.com/solo-io/gloo/pull/1983/files) but wasn't.

**Additional context**
- Gloo version: 1.4.5

**Comment by marcogschmidt** [comment]
FOr reference, this was the original issue: #1828
