### ISSUE TITLE
Masking of sensitive logs in extauth logs

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3699]
**Describe the bug**
ExtAuth shouldn't log sensitive data

**To Reproduce**
Watch logs as requests are being sent to extauth

**Expected behavior**
Filtered/masked request attributes

**Comment by lgadban** [comment]
Related: https://github.com/solo-io/gloo/issues/2486

**Comment by kdorosh** [comment]
closing as duplicate of https://github.com/solo-io/gloo/issues/3105 , which has been resolved

`headersToRedact` is the new field. The headers are still logged, but with a redacted value

**Comment by lgadban** [comment]
@kdorosh -- where is this field supposed to be set? there's no documentation I can find for this

**Comment by lgadban** [comment]
I see that it is defined here: https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/templates/_helpers.tpl#L157

But there is no user facing documentation for this setting

**Comment by lgadban** [comment]
Also unsure on whether or not the default list contains the `authorization` header
