### ISSUE TITLE
cloud-build-local is broken 

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#370]

**Comment by rickducott** [comment]
@ilackarms

**Comment by rickducott** [comment]
`gcloud builds submit .` is a workaround but you lose some nice features of cloud build local

**Comment by yuval-k** [comment]
I tried to run it and made some progress - 
- i had to delete the vendor folder
- and to manually pull some containers (we should version the build containers for that)

it failed in
```
Step #4 - "check-code-and-docs-gen": + git clone https://github.com/solo-io/solo-kit /workspace/gopath/src/github.com/solo-io/solo-kit
Step #4 - "check-code-and-docs-gen": Cloning into '/workspace/gopath/src/github.com/solo-io/solo-kit'...                                    
Step #4 - "check-code-and-docs-gen": Host key verification failed.
Step #4 - "check-code-and-docs-gen": fatal: Could not read from remote repository.
Step #4 - "check-code-and-docs-gen": 
Step #4 - "check-code-and-docs-gen": Please make sure you have the correct access rights
Step #4 - "check-code-and-docs-gen": and the repository exists.
```
while this shouldn't fail, this will anyway be fixed when we vendor in the protos and use as part of moving to go-modules.

did you encounter another error?

**Comment by ilevine** [comment]
This should work; make sure that the default project in gcloud is set to solo-public
