### ISSUE TITLE
docs still reference homebrew-tap, which is no longer being maintained

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3707]
**Describe the requested changes**
https://docs.solo.io/gloo/latest/installation/preparation/ still references homebrew-tap, which is no longer being maintained

**Link to any relevant existing docs**
https://docs.solo.io/gloo/latest/installation/preparation/

**Comment by lgadban** [comment]
https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/#install-command-line-tool-cli also references it
