### ISSUE TITLE
OIDC flow not working on gloo 1.5

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#3716]
**Describe the bug**
Creating a simple OIDC flow using auth0 as the provider doesn't work on a newer version (1.5), switching the extauth image to v 1.4.4 fixes the problem.  

**To Reproduce**
1.create an auth0.com account 
2. configure the default application t add the callback url, and add a user to test with. 
3. add oidc secret/create gloo authconfig/ attach to vs 
```apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oidc
  namespace: gloo-system
 spec:
  configs:
  - oauth:
      appUrl: http://34.94.127.6:80
      callbackPath: /callback
      clientId: O1as7rcwlIT2X00v6bZih0oZUOzNJtYw
      clientSecretRef:
        name: auth0
        namespace: gloo-system
      issuerUrl: https://asayah.us.auth0.com/
```

**Expected behavior**
should redirect to auth0 to login then redirect to demo app  

**Additional context**
**in Gloo 1.4**
`{"level":"debug","ts":1601935688.8499622,"logger":"extauth.ext-auth-service","caller":"service/extauth.go:31","msg":"Received auth request","request":"attributes:<source:<address:<socket_address:<address:\"10.168.0.34\" port_value:52914 > > > destination:<address:<socket_address:<address:\"10.92.1.5\" port_value:8080 > > > request:<time:<seconds:1601935688 nanos:847775000 > http:<id:\"17531490943346301152\" method:\"GET\" headers:<key:\":authority\" value:\"34.94.1.48\" > headers:<key:\":method\" value:\"GET\" > headers:<key:\":path\" value:\"/\" > headers:<key:\"accept\" value:\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\" > headers:<key:\"accept-encoding\" value:\"gzip, deflate\" > headers:<key:\"accept-language\" value:\"en-US,en;q=0.9\" > headers:<key:\"cache-control\" value:\"max-age=0\" > headers:<key:\"cookie\" value:\"id_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjBKU2g4U1hubG9rZTQxbTRFenFkLSJ9.eyJpc3MiOiJodHRwczovL2FzYXlhaC51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWY3NzUxOTQ0N2IxOGIwMDc2YTYxMzg3IiwiYXVkIjoiTzFhczdyY3dsSVQyWDAwdjZiWmloMG9aVU96Tkp0WXciLCJpYXQiOjE2MDE5MzU2ODgsImV4cCI6MTYwMTk3MTY4OH0.k7u2CcJ4Sdvztd5oGwq_ODUx9oGhYwhlGDjXriBweUGMPUXevfTlcTu9PpdaTIFOsUeVGqQDqunfDfkawLQu4dYrmIY7CG4gFj4S7SBVNeTKTXIhMGcEXt66KKyVajwgQ1DSClpvIeqVldFIk0KURTXKZxys6RsVGCu6stb1EAzeME1fUvbe9F43u5zuALePKs-2P5soWjEbI7ZlsdCs7rTI1ZiwTWkntVJIdPXQVcCgVhmk4JTP4HRQJITtJ1L9tq7vyc6pFW05oqskpKmWPScsonfThq6poGFovYhll6HkYm4LkvhoPk8CFGOAyQz9hbkmcJdw-RVNv8yGOT_l2A\" > headers:<key:\"upgrade-insecure-requests\" value:\"1\" > headers:<key:\"user-agent\" value:\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36\" > headers:<key:\"x-forwarded-proto\" value:\"http\" > headers:<key:\"x-request-id\" value:\"b12f09b1-f4a6-48cf-8497-1945779a5461\" > path:\"/\" host:\"34.94.1.48\" protocol:\"HTTP/1.1\" > > context_extensions:<key:\"config_id\" value:\"gloo-system.oidc\" > context_extensions:<key:\"source_name\" value:\"gloo-system.gateway-proxy-listener-::-8080-gloo-system_petclinic\" > context_extensions:<key:\"source_type\" value:\"virtual_host\" > metadata_context:<> > "}
{"level":"debug","ts":1601935688.8504384,"logger":"extauth","caller":"healthchecker/grpc.go:72","msg":"Intercepted response: ","resp":"status:<> ok_response:<headers:<header:<key:\"x-user-id\" value:\"https://asayah.us.auth0.com/;auth0|5f77519447b18b0076a61387\" > > > "}
`
**in Gloo 1.5**
`{"level":"debug","ts":1601933667.7160926,"logger":"extauth.ext-auth-service","caller":"service/extauth.go:31","msg":"Received auth request","request":"attributes:<source:<address:<socket_address:<address:\"10.168.0.31\" port_value:52678 > > > destination:<address:<socket_address:<address:\"10.124.4.3\" port_value:8080 > > > request:<time:<seconds:1601933667 nanos:714604000 > http:<id:\"12081845739410262161\" method:\"GET\" headers:<key:\":authority\" value:\"34.94.127.6\" > headers:<key:\":method\" value:\"GET\" > headers:<key:\":path\" value:\"/\" > headers:<key:\"accept\" value:\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\" > headers:<key:\"accept-encoding\" value:\"gzip, deflate\" > headers:<key:\"accept-language\" value:\"en-US,en;q=0.9\" > headers:<key:\"upgrade-insecure-requests\" value:\"1\" > headers:<key:\"user-agent\" value:\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36\" > headers:<key:\"x-forwarded-proto\" value:\"http\" > headers:<key:\"x-request-id\" value:\"cecd99b9-cfad-4588-b47a-1bb072f9068f\" > path:\"/\" host:\"34.94.127.6\" protocol:\"HTTP/1.1\" > > context_extensions:<key:\"config_id\" value:\"gloo-system.oidc\" > context_extensions:<key:\"source_name\" value:\"gloo-system.gateway-proxy-listener-::-8080-gloo-system_petclinic\" > context_extensions:<key:\"source_type\" value:\"virtual_host\" > metadata_context:<> > "}
{"level":"debug","ts":1601933667.7172606,"logger":"extauth.ext-auth-service","caller":"oidc/oidc_request.go:188","msg":"no token present. request is not authorized"}
{"level":"debug","ts":1601933667.7173653,"logger":"extauth.ext-auth-service","caller":"oidc/oidc_request.go:418","msg":"Full Issuer request url is https://asayah.us.auth0.com/authorize?client_id=O1as7rcwlIT2X00v6bZih0oZUOzNJtYw&redirect_uri=http%3A%2F%2F34.94.127.6%3A80%2Fcallback&response_type=code&scope=openid&&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDE5MzU0NjcsImlhdCI6MTYwMTkzMzY2Nywic3RhdGUiOiIvLzM0Ljk0LjEyNy42LyJ9.X7vgpSF73eHTJ-coIHMko_ume5t7PQR99DRK1ie-8Yo"}
{"level":"debug","ts":1601933667.717407,"logger":"extauth.ext-auth-service","caller":"chain/chain.go:107","msg":"Access denied by auth authService","authService":"*oidc.IssuerImpl-0"}
{"level":"debug","ts":1601933667.7174323,"logger":"extauth","caller":"healthchecker/grpc.go:72","msg":"Intercepted response: ","resp":"status:<code:7 > denied_response:<status:<code:Found > headers:<header:<key:\"location\" value:\"https://asayah.us.auth0.com/authorize?client_id=O1as7rcwlIT2X00v6bZih0oZUOzNJtYw&redirect_uri=http%3A%2F%2F34.94.127.6%3A80%2Fcallback&response_type=code&scope=openid&&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDE5MzU0NjcsImlhdCI6MTYwMTkzMzY2Nywic3RhdGUiOiIvLzM0Ljk0LjEyNy42LyJ9.X7vgpSF73eHTJ-coIHMko_ume5t7PQR99DRK1ie-8Yo\" > > > "}
{"level":"debug","ts":1601933667.7175543,"logger":"extauth","caller":"healthchecker/grpc.go:73","msg":"Intercepted response error: "}`

**Comment by yuval-k** [comment]
i am doing some work on oidc now; so will take a look

**Comment by yuval-k** [comment]
in gloo 1.5  the cookie has to be served under ssl
