### ISSUE TITLE
Support a template for customizing discovered upstreams

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3717]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to control the default configuration (e.g. connectionConfig, loadBalanncerConfig) of discovered upstreams through a template

**Describe the solution you'd like**
Support a template for customizing discovered upstreams

**Comment by kdorosh** [comment]
another option: should not be a template but expand the annotation based stuff to respect all Upstream config options

**Comment by sam-heilbron** [comment]
Setup UDS Syncer: https://github.com/solo-io/gloo/blob/master/projects/discovery/pkg/uds/syncer/setup_syncer.go#L17

Kubernetes plugin implements Discovery: https://github.com/solo-io/gloo/blob/a9bcedb882bbb501f47f0350fb0d6abd752bd417/projects/gloo/pkg/plugins/kubernetes/plugin.go#L20

Kubernetes implementation of Upstream Discovery: https://github.com/solo-io/gloo/blob/a9bcedb882bbb501f47f0350fb0d6abd752bd417/projects/gloo/pkg/plugins/kubernetes/uds.go#L23

Relies on Kube UpstreamConverter: https://github.com/solo-io/gloo/blob/a9bcedb882bbb501f47f0350fb0d6abd752bd417/projects/gloo/pkg/plugins/kubernetes/uds_convert.go#L37

Which uses implementations of a ServiceConverter to modify the upstream further: https://github.com/solo-io/gloo/blob/a9bcedb882bbb501f47f0350fb0d6abd752bd417/projects/gloo/pkg/plugins/kubernetes/uds_convert.go#L69

UseHttp2Converter implementation: https://github.com/solo-io/gloo/blob/a9bcedb882bbb501f47f0350fb0d6abd752bd417/projects/gloo/pkg/plugins/kubernetes/serviceconverter/use_http2_annotation_converter.go#L26

**Comment by jenshu** [comment]
Currently we are hardcoding just a few supported annotations ([here](https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/kubernetes/serviceconverter/use_ssl_annotation_converter.go#L30) and [here](https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/kubernetes/serviceconverter/use_http2_annotation_converter.go#L15)). The plan is to change this to a single annotation , which contains a json string of all the fields from the upstream spec to apply to the discovered upstream, e.g. `{"useHttp2": true, "sslConfig": { "sds": { "targetUri": "blah" }}}`. For an example annotation with json value, see the k8s “last applied” annotation

**Comment by ben-taussig-solo** [comment]
To clarify some questions that came up around this feature:
 - The documentation introduced around this feature suggests that users use `snake_case` field names to configure discovered upstreams, i.e.:
   - `gloo.solo.io/upstream_config: '{"initial_stream_window_size": 2048}'`
 - This is not ideal UX, as our documentation provides these values in `camelCase`
 - Some manual testing on my part suggests that `camelCase` configuration is also valid
   - e.g.: `gloo.solo.io/upstream_config: '{"initialStreamWindowSize": 2048}'`

I am working on creating a PR that will:
 - clarify this matter in the documentation
 - introduce new testing which validates this behavior
