### ISSUE TITLE
Add support for Flagger A/B testing rollouts

### ISSUE THREAD

**Issue by law10k** [solo-io/gloo#3726]
**Is your feature request related to a problem? Please describe.**
Add support to Gloo for using [Flagger A/B deployments](https://docs.flagger.app/usage/deployment-strategies#a-b-testing)

**Describe the solution you'd like**
An option similar to existing Flagger canary deployments, but with support for A/B deployments to enable session affinity.

**Additional context**
See related discussion here: https://github.com/weaveworks/flagger/issues/707

**Comment by kdorosh** [comment]
Reopening until the flagger PR has been opened and merged. The Gloo PR to add features the flagger integration will need have been merged and released in 1.6.0-beta22

**Comment by kdorosh** [comment]
Gloo Edge 1.6 has been updated with the new `inheritableMatchers` field on route tables that was then used in [this flagger PR](https://github.com/fluxcd/flagger/pull/765) to add support to Gloo for A/B testing by switching the implementation from using upstream groups to route tables
