### ISSUE TITLE
fix broken link from old docs

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3737]
**Describe the requested changes**

https://gloo.solo.io/operator_guide/usage_statistics/ needs to work, should redirect to https://docs.solo.io/gloo/latest/reference/usage_statistics/

**Browser Information**
If the change isn't related to content, please include your browser version and any other relevant information 
(e.g., browser zoom) to help us reproduce docs-related bugs.

**Additional context**

**Comment by artberger** [comment]
That doc page was removed in https://github.com/solo-io/gloo/commit/fc201d03bff3a8c0f4a0aa904ea6df20a6b337ad, so I'm going to close this issue.
