### ISSUE TITLE
Remove some headers from any response

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3739]
**Is your feature request related to a problem? Please describe.**
`responseHeadersToRemove` (and other related header manipulations) can only be added to Route Options , Virtual Host Options and Weighted Destination Options.
To remove some headers from any response, all the VirtualServices should be edited.

**Describe the solution you'd like**
Adding an option to set `responseHeadersToRemove` (and other related header manipulations) globally.

**Comment by liorshami** [comment]
we need this especially for gw healthCheck option, right now it exposes x-envoy-upstream-healthchecked-cluster header and we need to remove it for security reasons

**Comment by ehdieunguyen** [comment]
We have the same expectation with `responseHeadersToAdd` globally.
