### ISSUE TITLE
expose envoy's cluster_header field in the gloo api

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3749]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to define the cluster_header field to dynamically control the target upstream/cluster

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-cluster-header

**Comment by kdorosh** [comment]
New config should live on `RouteOptions` proto https://github.com/solo-io/gloo/blob/bdf0a52ddba14d959e41429e97a9b9d2469927bd/projects/gloo/api/v1/options.proto#L213
