### ISSUE TITLE
Eliminate manual step in Datadog Integration

### ISSUE THREAD

**Issue by andylibrian** [solo-io/gloo#3752]
**Is your feature request related to a problem? Please describe.**
I want to setup Datadog integration to monitor envoy as described in the docs https://docs.solo.io/gloo/latest/guides/integrations/datadog/. But there is a manual step to update the configmap.

`kubectl edit configmap gateway-proxy-envoy-config -n gloo-system`
```
  route:
    prefix_rewrite: "/stats" # instead of "/stats/prometheus"
    cluster: admin_port_cluster
```

**Describe the solution you'd like**
It would be great if the modification can be done via Helm values.

**Describe alternatives you've considered**
None

**Additional context**
Setting the prefix_rewrite with helm values can help with automation.

Ref: #2412

**Note**
I'm interested to send a PR, but need suggestion on the variable name.
[The code](https://github.com/solo-io/gloo/blob/a1c855be2fa47588eeb84dd69f2405178c32b8dc/install/helm/gloo/templates/12-ingress-proxy-configmap.yaml#L78) is inside this if block:

```
{{- if .Values.ingressProxy.deployment.stats }}
```

So, what about something like:
`{{ .Values.ingressProxy.deployment.statsRoutePrefixRewrite }}`

**Comment by kdorosh** [comment]
Hi @andylibrian ! Thanks for opening the ticket and looking into making a contribution.

I think the helm value should be something like `{{ .Values.gatewayProxy.$GATEWAYPROXYNAME.configMap.stats.routePrefixRewrite }}` and live in the already existing `{{- $statsConfig := coalesce $spec.stats $global.glooStats }}` in the configmap

**Comment by andylibrian** [comment]
Sounds good, @kdorosh 🙂

I've just opened a draft PR for this. Regarding the remaining item (tests), I don't see any existing test covering the modified line. Any suggestion / pointer to an existing test that is similar to this?

**Comment by kdorosh** [comment]
a similar helm test is https://github.com/solo-io/gloo/blob/dcce5e2e133070d0155f2804e1cd8ebf7fd3f945/install/test/helm_test.go#L201
