### ISSUE TITLE
Knative gloo install fails

### ISSUE THREAD

**Issue by techBeck03** [solo-io/gloo#3757]
**Describe the bug**
When attempting to install gloo using `glooctl` with knative, I keep getting the following error:

`Error: timed out waiting for knative apiservice to be ready: context deadline exceeded`

**To Reproduce**
1. `kubectl apply --filename https://github.com/knative/serving/releases/download/v0.18.0/serving-crds.yaml`
2. `kubectl apply --filename https://github.com/knative/serving/releases/download/v0.18.0/serving-core.yaml`
3. `glooctl install knative --install-knative=false`

I've also tried:
1. `glooctl install knative`

But the results are the same

**Expected behavior**
Glooctl install completes

**Additional context**
Add any other context about the problem here, e.g.
- Glooctl version: 1.5.1
- Kubernetes version: v1.17.6
- Knative version: v0.18.0

**Comment by kdorosh** [comment]
I think that glooctl error occurs when knative itself doesn't come up healthy. What errors do you see on the installed knative resources?

**Comment by techBeck03** [comment]
> I think that glooctl error occurs when knative itself doesn't come up healthy. What errors do you see on the installed knative resources?

All of the pods are running without any restarts

```
❯ k get pod -n knative-serving                         
NAME                          READY   STATUS    RESTARTS   AGE
activator-56cf848f9d-v6wn7    1/1     Running   0          4m43s
autoscaler-67c75d8566-vvzxq   1/1     Running   0          4m43s
controller-6568f84b8b-j2qk7   1/1     Running   0          4m43s
webhook-785c5879fb-hk48m      1/1     Running   0          4m42s
```

I looked through the logs of each of these pods and the only error type message i could find was the following from the activator pod:

```
{"level":"error","ts":"2020-10-16T19:19:44.328Z","logger":"activator","caller":"websocket/connection.go:162","msg":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"0a890ef","knative.dev/controller":"activator","knative.dev/pod":"activator-56cf848f9d-v6wn7","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/websocket/connection.go:162"}
{"level":"error","ts":"2020-10-16T19:19:47.106Z","logger":"activator","caller":"websocket/connection.go:116","msg":"Websocket connection could not be established","commit":"0a890ef","knative.dev/controller":"activator","knative.dev/pod":"activator-56cf848f9d-v6wn7","error":"dial tcp 10.103.78.119:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/websocket/connection.go:116\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/websocket/connection.go:195\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/websocket/connection.go:192\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/websocket/connection.go:133"}
```

**Comment by techBeck03** [comment]
I was able to get this working after a fresh cluster install.  Not really sure what was causing the knative install to become unhealthy.  Thanks for the help!
