### ISSUE TITLE
Allow configuring socket_options on gateway proxy listeners for downstream TCP keepalive

### ISSUE THREAD

**Issue by gigi-at-zymergen** [solo-io/gloo#3758]
**Is your feature request related to a problem? Please describe.**

We believe we're seeing increased client errors related to silent TCP connection reset using an NLB in front of our gateway-proxy. 
https://medium.com/tenable-techblog/lessons-from-aws-nlb-timeouts-5028a8f65dda

We run an AWS NLB in front of our Gloo gateway proxy. We also have a lot of scientist scripters and lab robot automation engineers who write clients of our services, so don't have much control over how those clients handle connection resets and pooling.

In particular, we have a lot of Python clients using requests/urllib3, whose connection pooling and session implementations do not appear to handle the underlying socket timeout and RST packet gracefully or automatically retry, ie:
https://github.com/psf/requests/issues/4937

Since putting many of our services behind the gateway, we've been receiving many more reports of 503/504 and cascading timeouts at the edge. 

Services are migrating from traditional k8s ingress and the ALB ingress controller, to behind the gateway, so we're changing from ALB -> NLB. We are also seeing a high rate of LB resets in the AWS metrics. Many of the symptoms align with the NLB 350s timeout and reset as described in several articles like the one linked above. 

To try to eliminate some variables from various reported symptoms, I wrote a very simple Python test client to test this hypothesis: 
- As long as the client recreated the connection each time, I was able to make thousands of requests against a couple endpoints for a service, and received only 200 responses within a couple hundred ms response times, over the course of 10 minutes.
- I then added a session which would reuse the underlying connection. As long as I kept a steady stream of requests going, I also had no issues getting successful responses from the endpoints.
- I then sent 50 requests, then slept for 350s, and then used the same session to start sending requests again. This immediately resulted in a connection reset error. Sleeping for 300s encountered no connection reset.
- I removed the session, and went back to recreating the connection each time. I sent 50 requests, slept for 350s, and then resumed sending requests. This also encountered no connection reset error.

**Describe the solution you'd like**

This is a problem with the AWS LB technology in front of the gateway, not a problem with the gateway. 

However, the gateway could allow us to configure downstream keepalives centrally, by allowing listener `socket_options` configuration as described in this Envoy feature request: 
https://github.com/envoyproxy/envoy/issues/3634 

We would like to keep the flexibility of running an L4 LB in front of the gateway. We would be constrained and not be able to take full advantage of the Gloo Gateway L7 capabilities , if we had to switch to an ALB in front of the gateway.

Some of our services run Envoy sidecars themselves. I am going to confirm that `socket_options` and downstream keepalive configuration on an Envoy sidecar, behind the NLB, alleviates the reset symptoms as observed in my simple reproduction test client.

**Describe alternatives you've considered**

Setting downstream keepalives on the gateway proxy would be far more centralized and easier for us, but we could take the approach of overriding the linux 7200s default at a container sysctl level. It would require us to do the following: 
-  Modify our clusters' kubelet options to allow unsafe sysctl
- Go through all our service helm charts to add security context to all our service deployment templates.

We could also try to coach everyone who writes clients on handling connection resets and retries, but this would likely not be very successful with those outside the software engineering department. 

**Additional context**

**Comment by ediezh** [comment]
We would love this feature as well. 

I tried to use EnvoyFilter to apply socket options on ingress gateway but no success. The listeners on ingress gateway are only for OUTBOUND traffic which doesn't apply to downstream connections.
