### ISSUE TITLE
Simplify the syntax of an OAuth secret

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3760]
**Is your feature request related to a problem? Please describe.**
When creating an OAuth secret using kubectl, the value is a base64 encoding of the following YAML:
```
client_secret: secretvalue
```

**Describe the solution you'd like**
It's confusing and would be simpler if the value was simply a base64  encoding of the secret value.

**Comment by wilmardo** [comment]
This would change would be inline with this change already done for the API keys:
https://github.com/solo-io/gloo/pull/3473

**Comment by marcogschmidt** [comment]
Whoever picks up this task should also verify whether they can reproduce the error on the TLS secret reported here: https://github.com/solo-io/gloo/issues/3652.
