### ISSUE TITLE
Expose `server_header_transformation` envoy HCM configuration

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3769]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to remove the `server` header that is added by envoy, which is insufficient for some organization's security posture.

**Describe the solution you'd like**
Expose the [`server_header_transformation` envoy HCM configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto) which would enable users to set this to `PASS_THROUGH`. This _should_ be enough to prevent the `server` header being added (as long as it isn't being set upstream)

**Comment by vinodsr** [comment]
@law10k @kdorosh  @sam-heilbron 

Can you provide some insights on how this configuration can be done. I looked in to the documentation but can't find anything useful.

Thanks

**Comment by sam-heilbron** [comment]
Hi @vinodsr, the API for the HttpConnectionManager can be found [here](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk/#httpconnectionmanagersettings). An example configuration of HCM settings can be found [here](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/listener_configuration/http_connection_manager/#advanced-listener-configuration). You would add the `serverHeaderTransformation` to the httpConnectionManagerSettings. Let me know if that works for you.

**Comment by vinodsr** [comment]
@sam-heilbron  It worked. Thanks for the help. 

👍
