### ISSUE TITLE
Adding an Upstream into Docker-Compose Installation of Gloo API Gateway

### ISSUE THREAD

**Issue by jnsrikanth** [solo-io/gloo#3788]
Hi

The default installation setup of Gloo with Docker-Compose.yaml comes with a petstore API example. 
However, if I want to add my own API services onto this Gloo Gateway, how do I do it?
Do I need to use the glooctl command? Can someone point me in the right direction regarding this?

**Comment by kdorosh** [comment]
Hi @jnsrikanth , you should be able to add them by running the service in docker, and then add routes to the service using `glooctl add route .. --any-flags`

A simple example (with the initial service already built into the docker compose) can be seen here https://docs.solo.io/gloo/latest/installation/gateway/development/docker-compose-consul/
