### ISSUE TITLE
gateway-validation-certs/webhook caBundle should not be regenerated everytime when not using first-party installation tooling

### ISSUE THREAD

**Issue by oboukili** [solo-io/gloo#3790]
**Describe the bug**
Updating the gateway `gateway-validation-certs` and "gloo-gateway-validation-webhook-gloo-system" `caBundle` attribute can lead to a gateway denial of service since the gateway pods do not automatically restart upon certificate rotation (the secret name being static) **if** a gateway version or configuration change is not scheduled **at the same time**.

While this behaviour could not be reproduced using officially supported methods (Helm and Glooctl), this may be of interest to some users that deploy Gloo using 3rd party methods (Kustomized Helm being one of them)

**To Reproduce**
(Please note that this is a very specific setup)
- Helm template the chart to render upstream manifests
- Kustomize some parts (example: Gloo settings)
- Apply using any other third party Kubernetes delivery tool (in our case ArgoCD)

**Expected behavior**
Do not update gateway/validating-webhook secret certificate if it is still valid.

**Additional context**
Gloo 1.5.1
Running Kustomized-Helm chart through ArgoCD.

**Proposed solution**
Make the certgen job a no-op operation if the certificate bundle is still valid. Valid meaning it has not expired and the other attributes (Usage, SANs, etc) are identical to what's to be expected, allowing for certificate rotation in case of scope change.

**Comment by kdorosh** [comment]
Thank you for reporting! Someone from Solo will be taking a look at this soon.

**Comment by kdorosh** [comment]
Initial plan is to update the certgen job and gateway such that:
- certgen job only creates/updates new secret, no longer patches the ValidatingWebhookConfiguration
- Gateway is now responsible for accepting both the new/old cert on rotation, until it does the patch to the caBundle on the VWH
  - Gateway will have to watch the mounted secret for changes, and only update the VWH when it realizes changes
