### ISSUE TITLE
Is there any golang sdk for gloo ?

### ISSUE THREAD

**Issue by mjaow** [solo-io/gloo#3795]
Is there any golang sdk for gloo ?

**Comment by Sodman** [comment]
We continued the conversation on this question in slack.

Ultimately the answer is that most of the changes you're going to want to make to Gloo will be edits to the various Gloo CRDs in k8s.

For example - you can use the k8s API and edit the VirtualService resource to add/edit routes. 

In terms of a Go SDK, if you want to edit these resources in go, we do auto-generate go structs from our protobuf objects, so you can re-use ours if you want to edit these resources in go - https://github.com/solo-io/solo-apis/blob/master/pkg/api/gateway.solo.io/v1/virtual_service.pb.go
