### ISSUE TITLE
Gloo extractor fails to match headers containing semicolons

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#3813]
**Describe the bug**
I am working with a new user who needs to extract a value from a header that contains a semicolon delimited string, like this...
`Original-Header: foo=bar; id_token=eyJraWQi; hello=world`
...and synthesize one of those values into a new header like this...
`New-Header:  eyJraWQi`
Note that the value to be extracted may be terminated by a semicolon or the end of the string.  The regex patterns I've been using match on external regex testing sites like regex101.com, but Gloo extractors fail to match on them.

**To Reproduce**
1. Deploy the httpbin service.  [All yaml files are attached](https://github.com/solo-io/gloo/files/5478978/bug.zip).
`kubectl apply -f httpbin-svc.yaml`
2. Deploy a virtual service with an extractor that matches on `.*id_token=(.*)`.  This works as expected in matching everything from `id_token` through the end of the string.
`kubectl apply -f vs-1.yaml`
3. Curl this VS endpoint.  Observe that it matches everything from `id_token` through the end of the string.
```
% curl -H "host: mydomain2.com" -H "original-header: foo=bar; id_token=eyJraWQi; hello=world" $(glooctl proxy url)/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "mydomain2.com",
    "New-Header": "eyJraWQi; hello=world",
    "Original-Header": "foo=bar; id_token=eyJraWQi; hello=world",
    "User-Agent": "curl/7.64.1",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  },
  "origin": "10.68.1.7",
  "url": "http://mydomain2.com/get"
}
```
4. Modify the VS to match the semicolon using `.*id_token=(.*);`.  This should handle the case where the value is semicolon-terminated.
`kubectl apply -f vs-2.yaml`
5. Curl this VS endpoint.  Observe that `New-Header` is not produced.
```
% curl -H "host: mydomain2.com" -H "original-header: foo=bar; id_token=eyJraWQi; hello=world" $(glooctl proxy url)/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "mydomain2.com",
    "Original-Header": "foo=bar; id_token=eyJraWQi; hello=world",
    "User-Agent": "curl/7.64.1",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  },
  "origin": "10.68.1.7",
  "url": "http://mydomain2.com/get"
}
```
6. Modify the VS to try other patterns that should match Original-Header:
- escape the semicolon: `.*id_token=(.*);`
- another pattern:  `.*id_token=(.*?)(;|$)`
- yet another pattern (vs-3.yaml): `.*id_token=([^;]*)`

Note that all of these patterns match as expected using regex101.com, but none of them match on Original-Header with Gloo.
<img width="1633" alt="Screen Shot 2020-11-02 at 9 22 34 PM" src="https://user-images.githubusercontent.com/52334260/97940907-c9323780-1d51-11eb-9a86-592af804f28f.png">

**Expected behavior**
The VS in steps 4 and 6 should produce a `New-Header` that matches the id_token value `eyJraWQi` in `Original-Header`.

**Additional context**
- Gloo version
```
% glooctl version
Client: {"version":"1.5.3"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.5.4","Name":"grpcserver-ui","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"grpcserver-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"grpcserver-envoy","Registry":"quay.io/solo-io"},{"Tag":"1.5.3","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.3","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```
- Kubernetes version v1.16.13-gke.401

**Comment by djannot** [comment]
@jameshbarton I think I found one that works: `.*id_token=([^;]*).*`

**Comment by jameshbarton** [comment]
@djannot found a workaround for this issue, using regex `.*id_token=([^;]*).*`.  Note that the `New-Header` is produced as expected using this regex:
```
% curl -H "host: mydomain2.com" -H "original-header: foo=bar; id_token=eyJraWQi; hello=world" $(glooctl proxy url)/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "mydomain2.com",
    "New-Header": "eyJraWQi",
    "Original-Header": "foo=bar; id_token=eyJraWQi; hello=world",
    "User-Agent": "curl/7.64.1",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  },
  "origin": "10.68.1.7",
  "url": "http://mydomain2.com/get"
}
```
