### ISSUE TITLE
Applying response transform triggers 413 Payload Too Large response

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#3830]
**Describe the bug**
I'm unsure if this is a bug or just behavior that violates the Principle of Least Astonishment.

There is a Gloo user who needs to handle some large response payloads, potentially up to 10MB.  In a route without response transforms, this works fine.  However, adding a response transform triggers a 413 Payload Too Large response.

**To Reproduce**
1. Deploy httpbin - yaml files in attached [zip](https://github.com/solo-io/gloo/files/5503402/bug.zip)
`kubectl apply -f httpbin-svc.yaml`
2. Deploy simple VS to expose httpbin
`kubectl apply -f httpbin-vs-1.yaml`
3. Curl the httpbin drip endpoint with small and large responses.  There should be no errors and the output files should match the expected sizes.  (The 10M test will take a few minutes.)
```
% curl -v -X GET "$(glooctl proxy url)/drip?duration=0&numbytes=100&code=200&delay=0" > out100
% curl -v -X GET "$(glooctl proxy url)/drip?duration=0&numbytes=1000000&code=200&delay=0" > out1m
% curl -v -X GET "$(glooctl proxy url)/drip?duration=0&numbytes=10000000&code=200&delay=0" > out10m
% ls -l out*
-rw-r--r--  1 jibarton  staff  1000 Nov  6 14:38 out100
-rw-r--r--  1 jibarton  staff  1000000 Nov  6 14:39 out1m
-rw-r--r--  1 jibarton  staff  10000000 Nov  6 14:39 out10m
```
4. Apply the modified VS that adds a response transform.
`kubectl apply -f httpbin-vs-2.yaml`
5. Curl the httpbin drip endpoint as before.  Any `numbytes` of 1m or less should succeed.  Anything 2m or larger should fail with a 413 Payload Too Large error.

Why does the addition of a response transform cause these larger requests to fail consistently?
Is this Envoy [issue](https://github.com/envoyproxy/envoy/issues/2919) part of the answer?

**Expected behavior**
Large payloads should be handled without error whether or not there is a response transform attached to the Virtual Service.

**Additional context**
- Gloo version
```
% glooctl version
Client: {"version":"1.5.5"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.5.4","Name":"grpcserver-ui","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"grpcserver-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"grpcserver-envoy","Registry":"quay.io/solo-io"},{"Tag":"1.5.3","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.3","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.4","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```
- Kubernetes version v1.16.13-gke.401
- Potentially related Envoy [issue](https://github.com/envoyproxy/envoy/issues/2919)

**Comment by jameshbarton** [comment]
For this user's situation, it is possible that using the [passthrough](https://docs.solo.io/gloo/latest/guides/traffic_management/request_processing/transformations/#passthrough) option on the `transformationTemplate` will allow us to work around this issue, since these endpoints are primarily used for serving large static files and the only transform activity is based on headers.

**Comment by jameshbarton** [comment]
Closing this issue. It is expected behavior when a request exceeds configured buffer limits. [Envoy Docs](https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/why_is_envoy_sending_413s)

**Comment by gektor0856** [comment]
@jameshbarton hi, i have the same problem. I'm using stagedTransformations in RouteTable and configured buffer.maxRequestBytes in gateway option. Where stagedTransformations is enabled  i got 413 error with Payload Too Large,  but if i disable transform it work fine. Any idea about how avoid that? I still think it's a bug...

```
...
stagedTransformations:
          regular:
            responseTransforms:
              - matchers:
                  - name: ':status'
                    value: '200'
                responseTransformation:
                  transformationTemplate:
                    parseBodyBehavior: DontParse
                    headers:
                      my-header:
                        text: 'header-value'
...
```

**P.S.**
The only solution i found is skip transform for requests with large payload, but this is not the best solution

**Comment by jameshbarton** [comment]
@gektor0856 Check out this blog pos for a solution:
https://www.solo.io/blog/handling-super-sized-requests-with-gloo-edge/

**Comment by gektor0856** [comment]
> @gektor0856 Check out this blog post for a solution: https://www.solo.io/blog/handling-super-sized-requests-with-gloo-edge/

Thanks!
