### ISSUE TITLE
Why does glooctl have a process for a command that ran before? Memory leak?

### ISSUE THREAD

**Issue by marcellodesales** [solo-io/gloo#3836]
**Describe the bug**

I had executed the command to add a route that worked... 

**To Reproduce**

* Executed the command, and I probably canced with ^C

```console
glooctl add route --path-exact /calculate-distance --dest-name distance-matrix-service-distance-matrix-service-8080 --prefix-rewrite /distancematrix
```

There's a huge spike taking taking 99% of CPU usage on my MacOS Catalina `10.15.7` from Gloo... I ran this command 

<img width="960" alt="Screen Shot 2020-11-09 at 2 26 34 PM" src="https://user-images.githubusercontent.com/131457/98575895-85cb5200-2298-11eb-89fe-8a0269742114.png">

```console
$ ps aux | grep glooctl
marcellodesales  14236 100.0  0.0  5135332     32 s005  R     6:14PM 417:58.25 glooctl add route --path-exact /calculate-distance --dest-name distance-matrix-service-distance-matrix-service-8080 --prefix-rewrite /distancematrix
marcellodesales  16967   0.0  0.0  4278580    772 s005  S+    2:25PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn glooctl
```

**Expected behavior**

* The process should have been stopped... 
* No glooctl process should be running.

**Additional context**

- Gloo version: 

```console
$ glooctl version
Client: {"version":"1.5.3"}
Server: {"type":"Gateway","kubernetes":{"containers":[
    {"Tag":"1.5.3","Name":"discovery","Registry":"quay.io/solo-io"},
    {"Tag":"1.5.3","Name":"gateway","Registry":"quay.io/solo-io"},
    {"Tag":"1.5.3","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},
    {"Tag":"1.5.3","Name":"gloo","Registry":"quay.io/solo-io"}
], "namespace":"gloo-system"}}
```

- Kubernetes version: 1.18.6

**Comment by kdorosh** [comment]
Hi @marcellodesales , thanks for reporting an issue to Gloo.

I tried to reproduce (both in letting the `glooctl add` command terminate as well as cutting it short) and was unable to reproduce on MacOS Catalina 10.15.6. Can you add any more details to help us reproduce?
