### ISSUE TITLE
gloo ui refresh will cycle through routetables with same name

### ISSUE THREAD

**Issue by blairham** [solo-io/gloo#3888]
**Describe the bug**
if you have a routetable with the same name as another routetable but in a different namespace, the UI will just cycle through each routetable on every refresh.

**To Reproduce**
1. create two routetables with the same name, in two different namespaces
2. open the UI and then open one of the routetables
3. You should see that on each refresh it will cycle through the route tables with the same name

**Expected behavior**
Opening a routetable that has the same name as another routetable does not cycle through them

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: 1.5.1
- Kubernetes version 1.15

**Comment by chrisgaun** [comment]
Moved to new UI in 1.7
