### ISSUE TITLE
Tracing Docs Incorrect

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3896]
**Describe the requested changes**
The tracing docs show adding the tracing provider to the prom listener only, and do not work for a real setup

Not sure how this changes with https://github.com/solo-io/gloo/issues/3762 as well

**Link to any relevant existing docs**
https://docs.solo.io/gloo-edge/latest/guides/observability/tracing/

**Comment by jameshbarton** [comment]
I've worked through these docs myself recently to configure DataDog tracing.  In the tracing provider config [docs](https://docs.solo.io/gloo-edge/latest/guides/observability/tracing/#1-specify-a-tracing-provider-in-the-bootstrap-config), both options 1 and 2 are broken.  It would also be nice if we could provide a DataDog example; I can help with that.
