### ISSUE TITLE
The x-user-id header is removed during JWT authentication

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3902]
**Describe the bug**
When a client sends a request with a JWT token and a `x-user-id` header, the `x-user-id` header is removed by Gloo Edge.

**Expected behavior**
The `x-user-id` should be preserved

**Additional context**
- Gloo Edge version: 1.5.8

**Comment by saiskee** [comment]
Closing, no code change needed.
The extauth plugin creates a filter which removes the `x-user-id` header by default. The recommended course of action is to set a customer `userIdHeader` in the listener settings. If `x-user-id` is needed, then a separate auth header can be set in the extauth settings, and `x-user-id` is not removed.
