### ISSUE TITLE
Support istio revisions (multi-control plane upgrades) in helm

### ISSUE THREAD

**Issue by snuggie12** [solo-io/gloo#3908]
**Is your feature request related to a problem? Please describe.**
Right now the discovery address is statically set to `istio-pilot.istio-system.svc:15012` when enabling istio. Not only should this be changed to `istiod.istio-system.svc` but on top of that this doesn't support istio revisions.

**Describe the solution you'd like**
In helm I would add a `revision` field under `istioSDS`. Then for the discovery address I'd set it to `istiod-$revision.istio-system.svc:15012`. If no `revision` is set the `Service` is simply called `istiod` (i.e. drop the hyphen and $revision is an empty string).

**Describe alternatives you've considered**
For now I'll need to use kustomize to edit this field.

**Additional context**

**Comment by Sodman** [comment]
Hi @snuggie12 , thanks for raising this issue! It looks like we will have to make the change to update istio-pilot to be istiod for the discovery address. We'll probably tackle this at the same time when we make the change to bump the version of the default sds istio-proxy included with the helm install (currently v1.6.8 in the latest Gloo Edge).

As you've mentioned, kustomize is a workaround here, but it's worth noting that we also have a helm values field `istioSDS.customSidecars` which can be used to override the default istio SDS sidecar deployed by our helm chart. This is an option for anyone else running into this issue who does not have kustomize set up. It's formatted as a yaml array of containers.

**Comment by npolshakova** [comment]
Hi, we changed Istio’s default discoveryAddress used by the glooctl istio commands and helm installations when istioSDS is enabled to be istiod. A new ticket has been opened (https://github.com/solo-io/gloo/issues/3967) to to bump the version of the default sds istio-proxy included with the helm install. With respect to support for revisions, we’d welcome a community PR. For now kustomize and istioSDS.customSidecars can be used as a workaround.

**Comment by snuggie12** [comment]
Actually, while doing other istio stuff I came across this for prometheus: https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings

Is there any downside to this approach? This allows istio to auto inject the sidecar onto gateway-proxy including the correct settings for revision.

The downside I see is if you enable `istioSDS` you would need to mark other pods in the namespace to not inject the sidecar (or perhaps some pods could use it like `observability`??)

**Comment by Sodman** [comment]
This approach is basically the same as what the istioSDS setting does under the hood - Attaches an Istio proxy sidecar to the gateway-proxy pod, does not make it receive any request traffic, and simply uses it to generate and mount the certs onto a shared volume. In addition though, it also starts up a local SDS server, which then servers these certs from the shared volume into the data-plane envoy used by gateway-proxy.

In terms of downsides, I don't believe the annotation-only approach would work, as you still need the SDS server to serve the certs into Envoy - or more specifically, update the certs on rotation. If you try to simply mount the volume with the certs directly onto Envoy, it's not smart enough to pick up the updates when the certs are rotated on disk.

Going back to the original ask of running 2 different Istios here for a canary-style Istio upgrade/rollout... Right now with the `istioSDS.customSidecars` helm value, you can run multiple istio proxies as sidecars to the gateway-proxy (with different istio versions, if needed) - but we'll need to make a change to our SDS configuration logic to have it pick up both certs. Right now it assumes specific cert names, so we just need to make that configurable and then we should be able to support this use case.
