### ISSUE TITLE
Add `customEnv` and `extraVolumeHelper` support to extauth deployment

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3922]
**Is your feature request related to a problem? Please describe.**
Users are unable to use the `customEnv[]` and `extraVolumeHelper` helm chart functionality for the extauth deployment.
This is impactful when attempting to write extauth plugins that rely on environment variables or mounted data.

**Describe the solution you'd like**
Access to the standard `customEnv[]` and `extraVolumeHelper` values, or an equivalent

**Comment by kdorosh** [comment]
Similar examples: https://github.com/solo-io/gloo/blob/0f1a4e909915f23bbfc5e5f9ce678498e86ebf4b/install/helm/gloo/templates/10-ingress-deployment.yaml#L44-L46

and https://github.com/solo-io/gloo/blob/f9c57f2a92d36eb49b90331c54f1f0551d1e3d53/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L431-L433

**Comment by kdorosh** [comment]
Example tests: https://github.com/solo-io/gloo/blob/9b065bb1582238a8786c0d7e2c68eab25d0df507/install/test/helm_test.go#L1596

**Comment by kdorosh** [comment]
helm docs https://helm.sh/docs/
