### ISSUE TITLE
Publish metrics for invalid resources

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#3964]
**Is your feature request related to a problem? Please describe.**
When Gloo isn't able to process an object (a Virtual Service, ...), it updates its status to provide information about the error, but there's no way to be alerted

**Describe the solution you'd like**
Publish metrics in Prometheus to allow users to create alerts when it occurs

Metrics that show if a configuration is ok/missing/wrong that can be consumed using Prometheus for example. 
use case: Alerting based on these metrics 

**Additional Context**
Duplicate of: https://github.com/solo-io/gloo/issues/3866

**Comment by asayah** [comment]
Metric per CRD type, for example 
virtualservice.foo = 1 
upstream.bar=0
...

**Comment by sam-heilbron** [comment]
I think the ask here is straightforward (publish metrics for resources so users can alert on those metrics) and useful (automate alerting on out of sync resources instead of relying on glooctl). I think we should start by Spiking out a solution, gaining feedback from field engineers and clients before implementing.

**Comment by elcasteel** [comment]
Write up of options for formatting metrics: https://soloio.slab.com/posts/metrics-for-invalid-resources-spike-o9b4u7xg
@djannot @asayah do either of you have thoughts on whether a count of the invalid resources of each type would work for our expected use cases?

**Comment by bcollard** [comment]
quick notice on this other contribution https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/dashboards/gloo-overview.json (internal ref) which exposes many control-plane metrics in a new Grafana dashboard. It's a good start to set up alerting on invalid resources. It doesn't answer the request made here.
