### ISSUE TITLE
Transformation removes the content-type

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#3966]
When adding a don't parse behavior in the transformations, it is removing the content-type, T mobile has a lot of scenarios around the content-type field, I'm assuming it is a bug?
```
#    options:
#      stagedTransformations:
#        early:
#          requestTransforms:
#          - requestTransformation:
#              transformationTemplate:
#                parseBodyBehavior: DontParse
```

**Comment by asayah** [comment]
content is passed in the method is POST/PUT.
content-type is removed if GET, content-type should not be specified on a GET call in the first place, this issue is to confirm if the content-type removal is intentional.

**Comment by bcollard** [comment]
Content-type is also removed on a POST but with an empty payload.
It's not removed with payload = `{}`
