### ISSUE TITLE
Any redirectAction leads to errors from validation for AWS lambdas

### ISSUE THREAD

**Issue by tkukushkin** [solo-io/gloo#3975]
**Describe the bug**
After #3942 any `VirtualService` with `redirectAction` leads to errors in Proxy:

```
reason: "4 errors occurred:\n\t* route destination type <nil> not supported with
    AWS Lambda\n\t* route destination type <nil> not supported with AWS Lambda\n\t*
    route destination type <nil> not supported with AWS Lambda\n\t* route destination
    type <nil> not supported with AWS Lambda\n\n"
```

On [this line](https://github.com/solo-io/gloo/pull/3942/files#diff-6889591de58279e09f13775dd29722474f1ae4bddce67eda35916e47436a1fa7R258) there is check, that route is not `directResponse`, but there is no check for `redirectAction`. Maybe need to check that route is exactly `routeAction`?

**To Reproduce**
Create any `VirtualService` with `redirectAction`.

**Expected behavior**
No errors.

**Additional context**
- Gloo Edge version: 1.5.13

**Comment by kdorosh** [comment]
@tkukushkin thank you for reporting, the fix is merging and will be backported to the 1.5 branch

**Comment by kdorosh** [comment]
@saiskee reopening until the backport has merged
