### ISSUE TITLE
How can I set the allow_cross_schemes_redirect setting in envoy using gloo?

### ISSUE THREAD

**Issue by ermakov-oleg** [solo-io/gloo#3989]
Now we are in the process of moving to k8s and faced the problem that when passing a request with the `X-Forwarded-Proto` header installed, which differs from the actual request scheme via gloo gateway-proxy, envoy sends a redirect to the same location.

Example:

```
curl -H "X-Forwarded-Proto:https" http://foo.bar.com/ 2>&1 | grep -v "^[*{}]"
> GET / HTTP/1.1
> accept: */*
> user-agent: curl/7.73.0
> accept: */*
> x-forwarded-proto:https
>
< HTTP/2 301
< location: http://foo.bar.com
< date: Tue, 15 Dec 2020 10:25:19 GMT
< server: envoy
<

```

In the envoy documentation we found a parameter responsible for this behavior [https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-internalredirectpolicy-allow-cross-scheme-redirect](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-internalredirectpolicy-allow-cross-scheme-redirect), but it is not clear how to install it using gloo.

**Comment by kdorosh** [comment]
Thanks for reporting @ermakov-oleg . This should be a simple task of adding support to our API for this flag, and passing it through to envoy; I've marked the ticket as help wanted.
