### ISSUE TITLE
Custom pod antiAffinity on helm chart

### ISSUE THREAD

**Issue by christophemorio** [solo-io/gloo#3995]
**Is your feature request related to a problem? Please describe.**
In a multi AZ K8s setup with Helm, replicas are not automatically spread on different AZ.

**Describe the solution you'd like**
Next to the current value antiAffinity,
Create values `gatewayProxies.NAME.customAntiAffinity` and `gatewayProxies.gatewayProxy.customAntiAffinity`, to allow such a flexibility.

**Describe alternatives you've considered**
Create a second predefined PodAntifinify based on `topologyKey: topology.kubernetes.io/zone`

**Additional context**
- ref: https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesiozone
- `topologyKey: failure-domain.beta.kubernetes.io/zone` is deprecated in v1.17

**Comment by kdorosh** [comment]
Thanks for reporting @christophemorio . Kustomize or https://docs.solo.io/gloo-edge/latest/installation/gateway/kubernetes/helm_advanced/ can be good options for you today. We'd also love a contribution here to add this to our chart.
