### ISSUE TITLE
Allow loading wasm filter from file path

### ISSUE THREAD

**Issue by Sodman** [solo-io/gloo#4025]
**Is your feature request related to a problem? Please describe.**
Sometimes loading wasm filters over HTTP might not be desirable, eg in environments with locked down or unreliable networks. As an alternative to loading the wasm filter an an OCI image over HTTP, we should be able to load a `.wasm` file directly from disk.

**Describe the solution you'd like**
Expose the Envoy fields to allow loading a filter from disk. The path can then be set in config. The filter can be loaded onto disk any way you want, for example using an InitContainer that already has the filter, which then loads the filter.wasm file into a shared directory.

**Describe alternatives you've considered**
More robust retry logic might help with spotty network connections or temporary server outages, but it doesn't solve for the locked-down-network use case.

**Comment by Sodman** [comment]
Re-opening, need Gloo Edge Enterprise Release

**Comment by eshepelyuk** [comment]
This is quite sad that Wasm was silently removed from Gloo Edge OSS version.
Is it possible to raise a voice for returning WASM support back as at least one way to extend Envoy ?
