### ISSUE TITLE
CI/CD: On PR, publish the gloo helm chart to a temporary helm repo

### ISSUE THREAD

**Issue by Sodman** [solo-io/gloo#4029]
**Is your feature request related to a problem? Please describe.**
When building projects which depend upon the Gloo Edge helm chart, we want to run through all of our tests in CI/CD in both Gloo Edge and the dependent repo. Today, that involves a lot of manual steps, such as building & upload `.tgz` helm files and index.yaml files to a publicly available repo, and then subsequently depending on them in other repos.

**Describe the solution you'd like**
Ideally, as part of CI/CD, when a PR in Gloo Edge is opened, or committed to, a version `1.n.0-betabranchname` should be published to a helm chart which can be depended upon by other repositories. This would make cross-repository integration testing much easier and less error prone.

**Describe alternatives you've considered**
Manually building Gloo Edge locally, uploading the index & .tgz files, updating other projects to depend on that version. Then, manually repeating this process on every commit.

**Comment by sam-heilbron** [comment]
This is now supported.

We publish to [solo-public-tagged-helm](https://github.com/solo-io/gloo/blob/main/Makefile#L604) and there is documentation in Enterprise to explain how to consume this chart: https://github.com/solo-io/solo-projects/tree/main/test/kube2e#using-an-unreleased-gloo-oss-branch
