### ISSUE TITLE
Fix bad assumption with endpoints

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4030]
**Describe the bug**
If there's no endpoints, just assign an empty cluster: [this](https://github.com/solo-io/gloo/blob/2755720ef6f65999c15d0cb9044e8ad856848d76/projects/gloo/pkg/translator/translator.go#L103) is a bad assumption that no longer holds. it also makes it difficult to run DNS resolution on the control plane (like we do in consul EDS and failover)

**Expected behavior**
Gloo should have a "warming" period while we wait for control plane DNS resolution to finish. Additionally, we can leverage a warming timeout in envoy (that we didn't have when the original code/assumption was made) to ensure that envoy proceeds if endpoints aren't provided for a specific cluster. (e.g. DNS resolution failure)

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version
- Kubernetes version

**Comment by yuval-k** [comment]
https://github.com/solo-io/gloo/blob/2755720ef6f65999c15d0cb9044e8ad856848d76/projects/gloo/pkg/translator/translator.go#L103
