### ISSUE TITLE
What are the different gloo features between the different installation modes ingress/gateway

### ISSUE THREAD

**Issue by kkapelon** [solo-io/gloo#4038]
**Describe the requested changes**
The page at https://docs.solo.io/gloo-edge/latest/installation/ingress/ describes **how** to install gloo as ingress but it doesn't explain **why** one would do that compared to the "gateway" installation mode.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/installation/ingress/

**Additional context**
I installed gloo using both `glooctl install ingress` and `glooctl install gateway` and in both cases all the simple commands I tried (adding routes and checking virtualservices) worked equally fine.

It would be great if you would document what features/limitations are present in each installation mode and when each installation mode is recommended.

**Comment by kdorosh** [comment]
Per the bottom of https://docs.solo.io/gloo-edge/latest/guides/integrations/ingress/

> If you want to take advantage of greater routing capabilities of Gloo Edge, you should look at Gloo Edge in gateway mode, which complements Gloo Edge’s Ingress support, i.e., you can use both modes together in a single cluster.

Ingress plays nicely with getting started demos and people who are already familiar with kubernetes `Ingress` resources, while also requiring several fewer resources and deployments. Most users install in gateway mode to leverage our more rich API for routing. This is also hinted at [here](https://docs.solo.io/gloo-edge/latest/introduction/architecture/deployment_arch/#simple-ingress-to-kubernetes).
