### ISSUE TITLE
Switching VS from CSRF Enabled to Shadow mode fails to disable enforcement

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#4053]
**Describe the bug**
Switching a VirtualService's CSRF mode from Enabled (which enforces CSRF policy) to Shadow (which should only log violations) does not disable enforcement as expected.  Instead, it continues blocking requests with 403 Forbidden errors.

**To Reproduce**
1. Deploy httpbin service - yaml files in attached [zip](https://github.com/solo-io/gloo/files/5766319/csrf.zip).
`kubectl apply -f httpbin-svc.yaml`

2. Deploy simple VS to expose httpbin with CSRF `filterEnabled` turned on.
`kubectl apply -f httpbin-vs-3.yaml`

3. Curl the httpbin `post` interface to show this blocking foreign request (as expected).  Note that this example was done with Gloo installed in Kind, thus the localhost curls.
```
% curl -X POST "http://localhost:31600/post" -H "Origin: http://example.com" -i
HTTP/1.1 403 Forbidden
content-length: 14
content-type: text/plain
date: Mon, 04 Jan 2021 18:43:33 GMT
server: envoy

Invalid origin
```

4. Curl the httpbin `post` interface to show valid request working (as expected).
```
% curl -X POST "http://localhost:31600/post" -H "Origin: http://localhost:31600" -i
HTTP/1.1 200 OK
server: envoy
date: Mon, 04 Jan 2021 18:45:13 GMT
content-type: application/json
content-length: 373
access-control-allow-origin: http://localhost:31600
access-control-allow-credentials: true
x-envoy-upstream-service-time: 6
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "localhost:31600",
    "Origin": "http://localhost:31600",
    "User-Agent": "curl/7.64.1",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  },
  "json": null,
  "origin": "10.244.0.17",
  "url": "http://localhost:31600/post"
}
``` 

5. Apply a one-line change to the VS to switch from Enabled mode to Shadow mode.  This should cause failure statistics to be updated, but should not block foreign requests.
`kubectl apply -f httpbin-vs-4.yaml`

6. Curl the httpbin `post` interface to show this still blocking the foreign request.
```
% curl -X POST "http://localhost:31600/post" -H "Origin: http://example.com" -i
HTTP/1.1 403 Forbidden
content-length: 14
content-type: text/plain
date: Mon, 04 Jan 2021 18:43:33 GMT
server: envoy

Invalid origin
```

**Expected behavior**
In [Shadow mode](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/csrf), the final request should have been processed with no errors, with the exception noted in the `http.http.csrf.request_invalid` metric.

**Workaround**
Deleting and re-creating the VS works as expected; only modifying it in-place fails.  For example, before step 5 above, execute this:
`kubectl delete -f httpbin-vs-4.yaml`
The rest of the example will then work as expected.

**Additional context**
- Gloo Edge version
```
% glooctl version
Client: {"version":"1.6.0"}
Server: {"type":"Gateway","kubernetes":{"containers":[{"Tag":"1.6.0","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.6.0","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.6.0","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.6.0","Name":"gloo","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}
```
- Kubernetes version v1.18.2 (Kind)

**Comment by npolshakova** [comment]
Will need https://github.com/solo-io/protoc-gen-ext/issues/11 fix to avoid collision when switching between enabled and shadow mode.
