### ISSUE TITLE
External protobuf definitions cause namespace conflicts in solo-apis

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#4068]
**Describe the problem**
The Gloo Edge APIs are published to the [solo-apis](https://github.com/solo-io/solo-apis) repository so that other modules can depend on them without having to pull in all the dependencies from this repo. This includes the [external protobuf definitions](https://github.com/solo-io/gloo/tree/master/projects/gloo/api/external) that our own ones depend on.

Some of these external APIs can cause [protobuf namespace conflicts](https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict) in modules that depend on `solo-apis`:

```
2021/01/06 17:53:58 WARNING: proto: file "github.com/solo-io/solo-apis/api/gloo/gloo/external/udpa/annotations/migrate.proto" has a name conflict over udpa.annotations.FileMigrateAnnotation
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/01/06 17:53:58 WARNING: proto: file "github.com/solo-io/solo-apis/api/gloo/gloo/external/udpa/annotations/migrate.proto" has a name conflict over udpa.annotations.FieldMigrateAnnotation
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

These conflicts currently only generate warnings, but - as mentioned in the warnings - future releases of the Go protobuf runtime will panic. We should fix these conflicts now, before being forced to by a necessary upgrade.

**To Reproduce**

To reproduce the behavior, create the following files in an empty directory (or unzip [this archive](https://github.com/solo-io/gloo/files/5778692/proto-conflict-example.zip)):
- `go.mod`
```
module github.com/solo-io/test-proto-conflict

go 1.14

require (
	github.com/cncf/udpa/go v0.0.0-20200313221541-5f7e5dd04533
	github.com/solo-io/solo-apis v0.0.0-20210104203558-daaaf507aaf9
)
```

- `main.go`
```go
package main

import (
	udpa_annotations "github.com/cncf/udpa/go/udpa/annotations"
	"github.com/solo-io/solo-apis/pkg/api/gloo.solo.io/external/udpa/annotations"
)

func main() {
	_ = annotations.MigrateAnnotation{}
	_ = udpa_annotations.MigrateAnnotation{}
}
```

No run `go run main.go` and you should see the warnings.

**Expected behavior**
There should be no conflict warnings in the program output.

**Additional context**
The cause of the problem is that the original messages and the ones we copy over have the same proto package name. When a Go package containing protobuf-generated types is initialized, the types are registered with the protobuf runtime using the package name and the message name. You can see that [here](https://github.com/cncf/udpa/blob/cc1b757b3eddccaaaf0743cbb107742bb7e3ee4f/go/udpa/annotations/migrate.pb.go#L195) and [here](https://github.com/solo-io/solo-apis/blob/daaaf507aaf9fba6f8414e7093a17af2dd619794/pkg/api/gloo.solo.io/external/udpa/annotations/migrate.pb.go#L339) (differences in the way the types are registered are due to different versions of `protoc-gen-go`).

The quickest solution is to prefix the package name of all the protobufs we copy over with `solo.io.` (like we [already do](https://github.com/solo-io/gloo/blob/fc35aeb4c62279198190c4d150608fd73a0dfc87/projects/gloo/api/external/envoy/config/core/v3/address.proto#L3) for most of them).

**Comment by Sodman** [comment]
Re-opening until https://github.com/solo-io/solo-kit/pull/402 is merged

**Comment by marcogschmidt** [comment]
Issue has been addressed and fix has been verified.
