### ISSUE TITLE
Memory leak in Gloo pod

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4078]
**Describe the bug**
Following a migration to 1.6.0, Gloo pod is being OOMKilled several times an hour.
The monitoring could show a kind of memory leak. Memory is going from 250MB to +800MB in a few minutes.

**Additional context**
The customer just migrated from Gloo 1.5.11 to v1.6.0
They have their own Ext Auth plugin.
- Kubernetes version: 1.16.11

More details in our task planner.

**Comment by marckamerbeek** [comment]
![image](https://user-images.githubusercontent.com/7521474/104006013-35904380-51a6-11eb-9d63-a81e508fd6bf.png)

**Comment by kdorosh** [comment]
The memory leak affected enterprise gloo only; it will be fixed in 1.7.0-beta4 and 1.6.2 of enterprise (releases anticipated today)

**Comment by kdorosh** [comment]
The releases are out now

**Comment by Goend** [comment]
version 1.2.10  :I think it has this question,discovery pod 
![image](https://user-images.githubusercontent.com/40394339/112247624-969cc300-8c8f-11eb-8f5c-5b9fc95e6c0f.png)

**Comment by Goend** [comment]
![image](https://user-images.githubusercontent.com/40394339/112247923-0c089380-8c90-11eb-8085-606892386c66.png)

**Comment by Goend** [comment]
![image](https://user-images.githubusercontent.com/40394339/112248119-5ee24b00-8c90-11eb-81a2-f5bf4bff2a0e.png)

**Comment by kdorosh** [comment]
Yes @Goend , older versions may be affected. Can you see if this persists after an upgrade?
