### ISSUE TITLE
Glooctl install always installs latest gloo edge version, should match glooctl version

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4089]
**Describe the bug**
Glooctl install seems to default install the latest stable gloo edge version instead of installing the matching glooctl version. I would need to test further, but this could be related to rolling back the glooctl version.

**To Reproduce**

1.
 ```sh
curl -sL https://run.solo.io/gloo/install | sh
export PATH=$HOME/.gloo/bin:$PATH
```
2.
```sh
glooctl upgrade --release=v1.5.14
```
3.
```sh
 glooctl install gateway enterprise --license-key ...
```
4.
```
glooctl version
----------
glooctl binary version (1.5.14) differs from server components (v1.6.1) by at least a minor version.
Consider running:
glooctl upgrade --release=v1.6.1
```

**Expected behavior**
Glooctl install should install the equivalent gloo edge version

**Additional context**
The downgrading of glooctl could be unrelated

more:
Looks like the latest version is retrieved no matter what the glooctl version is. This probably needs some internal discussion, but i am of the opinion that the glooctl version should be used and not the latest.

https://github.com/solo-io/gloo/blob/8c16a579766ce58d580ac891b87e80b2d25b17e6/projects/gloo/cli/pkg/cmd/install/installer.go#L327

**Comment by kdorosh** [comment]
fixed by https://github.com/solo-io/gloo/pull/4554
