### ISSUE TITLE
Broken link to Gloo Edge Installation from datadog integration docs

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4100]
https://docs.solo.io/gloo-edge/latest/guides/integrations/datadog/ 

![image](https://user-images.githubusercontent.com/65769106/104459267-81facb00-557a-11eb-846d-135c04865ec7.png)

Broken link: https://www.solo.io/installation/gateway/kubernetes

**Comment by kdorosh** [comment]
fixed on latest master docs
