### ISSUE TITLE
Clusters sometimes don't warm with endpoints if upstream changes

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo#4151]
**Describe the bug**

If an upstream is modified (e.g. via failover), the envoy cluster will sometimes lose its endpoints, resulting in no way to curl that upstream.

**To Reproduce**
In one terminal, run:
```
k port-forward -n gloo-system deploy/gateway-proxy 19000
```
And view localhost:19000/clusters

The petstore upstream should look something like this on that page:
```
default-petstore-8080_gloo-system::default_priority::max_connections::1024
default-petstore-8080_gloo-system::default_priority::max_pending_requests::1024
default-petstore-8080_gloo-system::default_priority::max_requests::1024
default-petstore-8080_gloo-system::default_priority::max_retries::3
default-petstore-8080_gloo-system::high_priority::max_connections::1024
default-petstore-8080_gloo-system::high_priority::max_pending_requests::1024
default-petstore-8080_gloo-system::high_priority::max_requests::1024
default-petstore-8080_gloo-system::high_priority::max_retries::3
default-petstore-8080_gloo-system::added_via_api::true
default-petstore-8080_gloo-system::10.244.0.19:8080::cx_active::0
default-petstore-8080_gloo-system::10.244.0.19:8080::cx_connect_fail::0
default-petstore-8080_gloo-system::10.244.0.19:8080::cx_total::0
default-petstore-8080_gloo-system::10.244.0.19:8080::rq_active::0
default-petstore-8080_gloo-system::10.244.0.19:8080::rq_error::0
default-petstore-8080_gloo-system::10.244.0.19:8080::rq_success::0
default-petstore-8080_gloo-system::10.244.0.19:8080::rq_timeout::0
default-petstore-8080_gloo-system::10.244.0.19:8080::rq_total::0
default-petstore-8080_gloo-system::10.244.0.19:8080::hostname::
default-petstore-8080_gloo-system::10.244.0.19:8080::health_flags::healthy
default-petstore-8080_gloo-system::10.244.0.19:8080::weight::1
default-petstore-8080_gloo-system::10.244.0.19:8080::region::
default-petstore-8080_gloo-system::10.244.0.19:8080::zone::
default-petstore-8080_gloo-system::10.244.0.19:8080::sub_zone::
default-petstore-8080_gloo-system::10.244.0.19:8080::canary::false
default-petstore-8080_gloo-system::10.244.0.19:8080::priority::0
default-petstore-8080_gloo-system::10.244.0.19:8080::success_rate::-1.0
default-petstore-8080_gloo-system::10.244.0.19:8080::local_origin_success_rate::-1.0
```

However, sometimes that page get into a state with no endpoints:
```
default-petstore-8080_gloo-system::default_priority::max_connections::1024
default-petstore-8080_gloo-system::default_priority::max_pending_requests::1024
default-petstore-8080_gloo-system::default_priority::max_requests::1024
default-petstore-8080_gloo-system::default_priority::max_retries::3
default-petstore-8080_gloo-system::high_priority::max_connections::1024
default-petstore-8080_gloo-system::high_priority::max_pending_requests::1024
default-petstore-8080_gloo-system::high_priority::max_requests::1024
default-petstore-8080_gloo-system::high_priority::max_retries::3
default-petstore-8080_gloo-system::added_via_api::true
```
After it gets into this state, the endpoints are never updated unless the pod with the upstream is restarted, or some other configuration changes.

To reproduce.
```
kind create cluster
glooctl install gateway
kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml
glooctl add route \
  --path-exact /all-pets \
  --dest-name default-petstore-8080 \
  --prefix-rewrite /api/pets

```

Run the endpoint_discovery_flake.sh for several minutes:
https://gist.github.com/ashleywang1/ab9832604985dd00a42f0ce03ea6f3bd

If there is a returned value of 36, then that means the endpoints were not discovered.

**Expected behavior**
The endpoints should always show up, even if the upstream changes.

**Additional context**

~ glooctl version
Client: {"version":"1.7.0-beta8"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.7.0-beta8","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.7.0-beta8","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.7.0-beta4","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.7.0-beta4","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.7.0-beta4","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
- Kubernetes version
 kind version
kind v0.8.1 go1.14.4 darwin/amd64
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ashleywang1** [comment]
One temporary fix changing the settings to enable Rest EDS:
```
kubectl patch settings -n gloo-system default --type=merge -p '{"spec":{"gloo":{"enableRestEds": true}}}'
```

**Comment by kdorosh** [comment]
We re-enabled rest EDS which fixes this issue, and added regression test to ensure this doesn't happen again

**Comment by yuval-k** [comment]
may be related https://github.com/envoyproxy/envoy/pull/15269

**Comment by kdorosh** [comment]
confirmed, was not related https://github.com/solo-io/gloo/issues/4151#issuecomment-790983642
