### ISSUE TITLE
GlooE api-server deployment contains hardcoded runAsUser

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4196]
**Describe the bug**
The `api-server` deployment contains a hardcoded `runAsUser` --
```
          securityContext:
            runAsUser: 101
```

https://github.com/solo-io/solo-projects/blob/v1.5.15/install/helm/gloo-ee/templates/33-apiserver-deployment.yaml#L106-L107

This causes problems when running in an environment that expects to have control over the user, e.g. openshift

**To Reproduce**
Attempt to deploy Gloo Edge v1.5.14 on OCP

**Expected behavior**
I believe the envoy container in the `api-server` pod should respect the `runAsUser` settings for the pod:
https://github.com/solo-io/solo-projects/blob/v1.5.15/install/helm/gloo-ee/templates/33-apiserver-deployment.yaml#L48-L50

**Additional context**
This was not a problem in Gloo Edge Enterprise 1.4.x but I haven't tracked down the differences specifically

**Comment by chrisgaun** [comment]
Should be able to use the custom YAML override https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/#helm-chart-kuberesourceoverrides We also adding this to the Fed UI work as well.
