### ISSUE TITLE
Improve metrics reporting by allowing configurable labels to all gloo metrics

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4253]
**Is your feature request related to a problem? Please describe.**
A common request from users is to able to partition all gloo/envoy metrics.

For example, across teams or "API groups". Each team then owns alerting for metrics related to their services, rather than a core/admin gloo team.

**Describe the solution you'd like**
Configurable global labels to be applied to all gloo/envoy metrics (envoy may be tougher, needs to be looked into).

Also docs that explicitly list the risks of adding too many labels / increasing their cardinality.

**Describe alternatives you've considered**
N/A, fill out as we dig into more

**Comment by cowboygneox** [comment]
We would like to add information from the JWT to custom metrics. Basically, it would be awesome to specify headers that come in from a request and add them as labels to the Prometheus metrics.

The initial driving thought would be to measure customerId interactions with their upstreams. We don't have more than thousands of customers, so cardinality is not a problem. We would just extract the customerId from the JWT, make it a header, and hopefully there would be magic to just make it part of the Prometheus metrics.
