### ISSUE TITLE
support upstream groups in CLI

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#426]
Right now, doing a canary release involves a bit too much YAML. would be nice if we could:

`glooctl canary svc-1=0.90 svc-2=0.10` 

or 

`glooctl weighted-routing svc-1=0.90 svc-2=0.10` to make it more generic... though I think I prefer the first example

to make it easier to manage traffic to new versions, and easily roll them back For example, we could have a `Canary` CRD that knows what the current canary thresholds are and can be driven by automation tools like Jenkins X or by a UX tool like the website or CLI.

Thoughts @scranton @ilevine @rickducott ?

**Comment by scranton** [comment]
Certainly need more support. To move from header based routing to new version to routing all traffic to new version requires 3+ glooctl calls versus one YAML apply. Maybe that's preferred path - YAMl - and if so we need docs to better reflect that then emphasizing glooctl like we do today...

For example, moving from

`
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: coalmine
  namespace: gloo-system
spec:
  displayName: coalmine
  virtualHost:
    domains:
    - '*'
    name: gloo-system.coalmine
    routes:
    - matcher:
        headers:
        - name: x-canary
          regex: true
          value: "true"
        prefix: /findPets
      routeAction:
        single:
          destinationSpec:
            rest:
              functionName: findPets
              parameters: {}
          upstream:
            name: default-petstore-v2-8080
            namespace: gloo-system
    - matcher:
        prefix: /findPetWithId
      routeAction:
        single:
          destinationSpec:
            rest:
              functionName: findPetById
              parameters:
                headers:
                  :path: /findPetWithId/{id}
          upstream:
            name: default-petstore-v1-8080
            namespace: gloo-system
    - matcher:
        prefix: /findPets
      routeAction:
        single:
          destinationSpec:
            rest:
              functionName: findPets
              parameters: {}
          upstream:
            name: default-petstore-v1-8080
            namespace: gloo-system
    - matcher:
        prefix: /petstore
      routeAction:
        single:
          upstream:
            name: default-petstore-v1-8080
            namespace: gloo-system
      routePlugins:
        prefixRewrite:
          prefixRewrite: /api/pets/
`

to 

`
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: coalmine
  namespace: gloo-system
spec:
  displayName: coalmine
  virtualHost:
    domains:
    - '*'
    name: gloo-system.coalmine
    routes:
    - matcher:
        prefix: /findPets
      routeAction:
        single:
          destinationSpec:
            rest:
              functionName: findPets
              parameters: {}
          upstream:
            name: default-petstore-v2-8080
            namespace: gloo-system
    - matcher:
        prefix: /findPetWithId
      routeAction:
        single:
          destinationSpec:
            rest:
              functionName: findPetById
              parameters:
                headers:
                  :path: /findPetWithId/{id}
          upstream:
            name: default-petstore-v1-8080
            namespace: gloo-system
    - matcher:
        prefix: /petstore
      routeAction:
        single:
          upstream:
            name: default-petstore-v1-8080
            namespace: gloo-system
      routePlugins:
        prefixRewrite:
          prefixRewrite: /api/pets/
`

requires at least an `glooctl add route` and 2 careful `glooctl remove route`. Careful in that you need to check route rule indexes after each add & remove as they can resort. Hard to think how I'd automate this change with just command line...

**Comment by ilevine** [comment]
we now support upstream groups so that weights can be changed at one place, for multiple routes.
I'll keep this open as we don't have cli support.

**Comment by rickducott** [comment]
This is done, remaining work in #894
