### ISSUE TITLE
Changelog Improvments

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4274]
**Describe the requested changes**

- The changelog entries don't have anchors so you can't link to individual releases
- The sort by release option on the changelog is useful but no way to jump between minor versions (e.g. 1.7.x -> 1.6.x) which is especially useful to skip all the beta releases

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/reference/changelog/enterprise/

**Comment by chrisgaun** [comment]
believe our new Changelog improvements gets to broader issue trying to address here.
