### ISSUE TITLE
Global Upstream SslParameter Config

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#4285]
**Is your feature request related to a problem? Please describe.**
I would like to be able to specify default configurations for my Gloo Upstreams SslParameters, which individual upstreams can override. 

**Describe the solution you'd like**
A global setting with some default upstream options. These options can be overridden by upstream specs.

**Comment by kdorosh** [comment]
Closely related to https://github.com/solo-io/gloo/issues/2426, keeping the one linked here open in case we want to add gateway level granularity
