### ISSUE TITLE
if TLS termination at load balancer, do not expose https port in gateway-proxy svc

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#4286]
if a customer wants to do TLS termination at the NLB, he needs to set up the gateway-proxy svc to serve http on the port 443 and no https. 

e.g. add a flag like disableHttps: true in helm chart.

**Comment by kevin-shelaga** [comment]
@asayah Does the following issue and PR fix this for you?

https://github.com/solo-io/gloo/issues/3450
https://github.com/solo-io/gloo/pull/4276

**Comment by asayah** [comment]
@kevin-shelaga it does! thanks

**Comment by law10k** [comment]
This should probably also remove the relevant port from the `Service`

**Comment by kevin-shelaga** [comment]
@lgadban yes, good point. The corresponding port should not be set. Though interestingly `disableGeneratedGateways` doesnt seem to affect the service as well.
