### ISSUE TITLE
VirtualService not retrieving Proxy CRD Status correctly

### ISSUE THREAD

**Issue by apshaughnessy** [solo-io/gloo#4290]
**Describe the bug**
When making a change to one of my VirtualServices, (ex: Changing the prefix from /api to /api/pets, I find that the `glooctl get virtualservices` output reports that there is a problem with with gateway-proxy resource that may be blocking future updates.

`Accepted
*v1.Proxy.gloo-system.gateway-proxy is in a Pending state. Updates to this resource may be blocked by problems with another resource.`

When I take a look at the VirtualService output, it seems like Gloo is not reporting the status of the Proxy CRD, even though the Proxy CRD is healthy.

VirtualService:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
...
...
status:
  reportedBy: gateway
  state: 1
  subresourceStatuses:
    '*v1.Proxy.gloo-system.gateway-proxy': {}
```

Proxy:
```
apiVersion: v1
items:
- apiVersion: gloo.solo.io/v1
  kind: Proxy
...
...
  status:
    reportedBy: gloo
    state: 1
```

If I revert the change (/api/pets to /api ), the Proxy issue does not clear up. 

I have found that if I kill the gateway Pod, then the error output from `glooctl get virtualservice` clears up when the new gateway pod launches. Additionally, if I scale the deployment of the `gateway` up, the issue will clear (which indicates the new pod that is spun up can handle the issue), but when I scale back down to the original pod, the issue returns.

**To Reproduce**
1. Change the prefix on a VirtualService
2. Execute `glooctl get virtualservices` and check for the gateway-proxy output.

**Expected behavior**
Update a VirtualService, and an alert is not given for the gateway-proxy if there is no issue.

**Additional context**
Additional details can be found in the Slack conversation: https://solo-io.slack.com/archives/C9L6VPAUW/p1613141505213300

Add any other context about the problem here, e.g.
- Gloo Edge version: 1.6.7
- Kubernetes version: K3s 1.19.7+k3s1

**Workaround**
Perform a rolling restart of the gateway deployment.

**Comment by kdelisle-cs** [comment]
I have the same issue on Gloo EE 1.5.20, and the workaround also resolves the issue (until the next change, of course).
