### ISSUE TITLE
CI Test Flake: Kubernetes uses json keys when serializing

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#4292]
**Describe the bug**
The kubernetes plugin test errors with the following message:
```
Kubernetes kubernetes [It] uses json keys when serializing 
/workspace/gloo/projects/gloo/pkg/plugins/kubernetes/kubernetes_test.go:151

  Expected
      <v1.UpstreamList | len:0, cap:0>: nil
  to have length 2
```

This has been occurring intermittently in CI, will comment on issue when it occurs again

**To Reproduce**
Logs: https://console.cloud.google.com/cloud-build/builds/262697be-3097-470a-af56-5871cca9e595;step=9?project=solo-public

**Comment by saiskee** [comment]
Happened twice in a row in CI for me

Logs: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=e52fb89c-b5e7-49b3-90b1-4ad60fd0c2b4

**Comment by sam-heilbron** [comment]
This hasn't happened in >1 year. Closing. We can re-open if it happens again
