### ISSUE TITLE
Build Operator for Gloo to simplify runtime

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#430]
* scaling
* connecting to management systems
* upgrade of control plane, add new plugins, etc
* rollback of control plane

**Comment by rickducott** [comment]
Related - CLI command to make it easier to redeploy with new helm values

**Comment by kdorosh** [comment]
Related, support feature requests such as automatically discovered and routable upstreams based on request metrics other than hostname/SNI (such as request path prefix), see https://github.com/solo-io/gloo/issues/2308#issuecomment-586426845

**Comment by Boes-man** [comment]
Use [Operator Hub's capabilities documentation](https://operatorframework.io/operator-capabilities/) for Gloo Edge operator roadmap to maturity and documentation requirements.

**Comment by dinukxx** [comment]
Can we please bump up the priority of this one , we are evaluating GE atm and having an operator that could reduce the installation and upgrades efforts will significantly improve our ability to manage things k8s way.
operator should be able to accept a config element which will enable us to  enhance any internal construct mapping that may be required.
based on the [Operator Hub's capabilities documentation](https://operatorframework.io/operator-capabilities/) minimum of level 2  would be ideal for managing gloo deployments and its dependencies initially.
