### ISSUE TITLE
Running gloo in kubernetes not using CRD, but with consul+vault backend

### ISSUE THREAD

**Issue by a-b-v** [solo-io/gloo#4303]
Whats the best way to run gloo-edge in kubernetes, not using CRD, with consul & vault as a backend?

**Comment by sam-heilbron** [comment]
Conversation in Slack: https://solo-io.slack.com/archives/C9L6VPAUW/p1613553286273500. Will close this once we have a resolution.

**Comment by a-b-v** [comment]
Has been configured using consul as kv store, vault as secret store. crd as gloo config store

**Comment by cliveseldon** [comment]
Is there a link/docs to details about this as the Slack link seems to have gone out of scope?
