### ISSUE TITLE
Make the access_token available in the State

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#4318]
**Is your feature request related to a problem? Please describe.**
A customer wants to access it from an extauth Go Plugin

**Describe the solution you'd like**
Add it to the state as we do for the id and refresh tokens

**Comment by kdorosh** [comment]
@jahvon reopening until it's in a stable 1.6 Gloo Edge Enterprise release

**Comment by jahvon** [comment]
This change has been backported to v1.6 so I'll close this now.
