### ISSUE TITLE
ExtAuth - OIDC - allow a Client to pass a code_verifier (PKCE) to Gloo

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4329]
Given a SPA using OIDC + PKCE,
When this SPA Client is returned an  authorization `code`,
Then, the Client might want to go through Gloo Edge to make the final request to `/token` (OAuth2 code exchange)
In this case, the Client will pass the `code_verifier` to Gloo, then Gloo must pass this parameter to the OAuth server
See the last parameter here: https://pkg.go.dev/golang.org/x/oauth2/#Config.Exchange

**Comment by kdorosh** [comment]
This can be done today: https://github.com/solo-io/gloo/blob/9b057bf8cf6bb9524471cb5e351593542c6d5a63/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto#L408-L409 just set `code_challenge` and `code_challenge_method` appropriately

more references:
- https://www.oauth.com/oauth2-servers/pkce/authorization-request/
- https://github.com/dexidp/dex/blob/v2.28.1/server/server_test.go#L579-L627

**Comment by kdorosh** [comment]
will be released in 1.8.0-beta3 enterprise
