### ISSUE TITLE
extauth upstream grpcHealthCheck incorrect serviceName

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4331]
**Describe the bug**
The upstream `extauth` has an incorrect grpcHealthCheck service name value. The value is `extauth` and should be `ext-auth`.

**To Reproduce**
1. kubectl get upstream extauth -n gloo-system -oyaml
2. 
```spec:
  healthChecks:
  - grpcHealthCheck:
      serviceName: extauth
```
3. Should be `ext-auth`

**Expected behavior**
The service name is the extauth upstream should be `ext-auth`

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version `1.6.8`
- Kubernetes version

**Comment by sam-heilbron** [comment]
duplicate of: https://github.com/solo-io/gloo/issues/4324
