### ISSUE TITLE
Allow trafficshift using Gloo Federation

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#4333]
**Is your feature request related to a problem? Please describe.**
Currently, Gloo Federation allows a user to create a Failover, but several customers want to have a trafficshift to:
- allow a service on one cluster to send requests to a services in another cluster (using the mTLS channel between the Gloo Edge gateway)
- allow a service to send a percentage of the requests locally and a percentage on a different cluster (bursting)

**Comment by jameshbarton** [comment]
@djannot suggests this workaround:  The workaround is to create an Upstream with a fake target.  If user wants to use the Federated objects, then they can create a FailoverScheme with this upstream as primary and the service of the other cluster in a failover group.
If user doesn't need any other capability of Gloo Federation, then it's possible to directly add the failover section in the upstream (after configuring the mTLS gateway).
