### ISSUE TITLE
OIDC - don't url-encode the original URL to redirect (state)

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4339]
Given an upstream protected with OIDC, 
When the end-user hits this kind of URL, with an exclamation mark (legacy app):
`https://legacy-app/!page?param=value`
Then, the final URL to redirect, stored in the OAuth state param, is URL-encoded like that:
`https://legacy-app/%21page?param=value`

The goal is to help the customer to deploy OIDC on top of their legacy apps with **exclamation marks** in the URI.

**Comment by kdorosh** [comment]
we also found that when you use the oauth flow and append some query parameters, e.g reach an app like http://app.com/?key=value that has oauth extauth configured in gloo, then the gloo callback will redirect browser after authentication to http://app.com/%3Fkey=value, with the ? url encoded.

**Comment by kdorosh** [comment]
reopening @jahvon until changes are pulled into and released in enterprise

**Comment by jahvon** [comment]
The fix has been backported to v1.6.17
