### ISSUE TITLE
CPU Utilization on the Gloo Deployment 

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4343]
**Describe the bug**
The Gloo Deployment uses a lot of CPU during churn in configuration, but normally releases CPU after configuration changes. The problem is that it is *not* releasing CPU. We are seeing the CPU stay at a constant.

![image](https://user-images.githubusercontent.com/1096507/109315744-d8fdec00-7818-11eb-8065-f19d6abc52a0.png)

```
NAME                           CPU(cores)   MEMORY(bytes)
api-server-5d7546bf4b-tvzmm    5m           82Mi
discovery-58b5dcfb6d-phf6g     56m          148Mi
extauth-66fcdb5547-2tfbs       2m           24Mi
extauth-66fcdb5547-5v5ds       2m           26Mi
flagger-fc957c4f4-ld4xr        3m           9Mi
gateway-65868445b9-w2c4d       5m           33Mi
gateway-proxy-6sx4j            24m          68Mi
gateway-proxy-9nwsj            21m          69Mi
gateway-proxy-f8xdk            35m          69Mi
gateway-proxy-internal-5brkq   20m          63Mi
gateway-proxy-internal-ccgbd   19m          62Mi
gateway-proxy-internal-gcvnp   32m          63Mi
gateway-proxy-internal-lzzl2   37m          63Mi
gateway-proxy-internal-vzvzb   42m          62Mi
gateway-proxy-ksshx            19m          69Mi
gateway-proxy-nt44d            18m          68Mi
gloo-6868c8ccf-qhz5g           2512m        252Mi
rate-limit-86578b956d-gt2pr    1m           17Mi
redis-5bf4677f97-qgqk8         1m           2Mi
```

**To Reproduce**
1. `k top pods -n gloo-system`

**Expected behavior**
I expect the Gloo Deploymen to release CPU after changes in config.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version `1.6.12` `1.6.18`

**Comment by jpke** [comment]
Not sure if this is relevant, but clusters that see the highest cpu utilization have all persisted through GlooEE upgrades from 1.4 -> 1.6. Fresh clusters starting out with 1.6 show ~1-2.5 cpu utilization.
(Not entirely apples to apples though, the persistent clusters see more traffic passing through gateway proxies, and have more gateway proxies.) But all have the same gloo-ee config.
