### ISSUE TITLE
Expose Gloo Enterprise License Information

### ISSUE THREAD

**Issue by ianrudie-tmus** [solo-io/gloo#4362]
**Is your feature request related to a problem? Please describe.**
We would like a way to use alert manager to alert about the license status and expiration of licenses for Gloo Enterprise.

**Describe the solution you'd like**
Expose prometheus metrics with the current license state and the date of license expiration.

**Describe alternatives you've considered**

1. Building a custom container image to run along side Gloo installations to try to query this information and expose it's own prometheus metrics.
2. Building pre-install or post-install checks for license expiration dates into our deployment pipelines.

**Additional context**

**Comment by kevin-shelaga** [comment]
@ianrudie-tmus I am pretty sure "production" enterprise licenses do not expire, so that environments dont crash. Trial enterprise licenses definitely expire though.

**Comment by chrisgaun** [comment]
There are two related issues
