### ISSUE TITLE
Strict Validation fails for `/` in label key

### ISSUE THREAD

**Issue by phenixblue** [solo-io/gloo#4378]
**Describe the bug**

When applying a VirtualService resource that has a label with a `/` character in the label key, validation will fail.

**To Reproduce**
1. Create VirtualService resource with a label like this:

```yaml
labels:
  some/label: "value"
```

1. Apply VirtualService with Strict Validation enabled.

You should get an error similar to this:

```
Error from server: error when creating "/tmp/vs.yaml": admission webhook "gateway.gloo-system.svc" denied the request: resource incompatible with current Gloo snapshot: [Validating v1.VirtualService failed: validating *v1.VirtualService name:"test-vs1"  namespace:"gloo-system": failed to validate Proxy with Gloo validation server: VirtualHost Error: ProcessingError. Reason: invalid virtual host [gloo-system_test-vs1]: envoy validation mode output: error initializing configuration '': Failed to parse response template on response matcher: Failed to parse body template [json.exception.parse_error.101] parse error at line 2, column 0: syntax error while parsing value - invalid string: control character U+000A (LF) must be escaped to \u000A or \n; last read: '"ERROR:<U+000A>'
, error: exit status 1]
```

**Expected behavior**

The VirtualService should be applied successfully

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: 1.6.10
- Kubernetes version: 1.16

**Comment by kevin-shelaga** [comment]
Could you provide a sample label of what you're trying to set? I don't think "some/label" is a valid key. 

https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

**Comment by phenixblue** [comment]
That should be a 100% valid label key in practice and according to the same doc you linked to:

>Valid label keys have two segments: an optional prefix and name, separated by a slash (/).

**Comment by kevin-shelaga** [comment]
@phenixblue If you set some.is/label as a key I believe it would be valid. 

Valid label keys have two segments: an optional prefix and name, separated by a slash (/)
...
If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots (.), not longer than 253 characters in total, followed by a slash (/).

**Comment by kevin-shelaga** [comment]
@phenixblue  Apologies I just tried in K8s, you're right

**Comment by kevin-shelaga** [comment]
@phenixblue  I just created a VS with the following label and everything works as expected. Could you share your whole VS or a reproducible VS?

```yml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test
  namespace: gloo-system
  labels:
    test/test: two 
...
```
