### ISSUE TITLE
Changelog bot does not fail when the directory includes an unexpected zero

### ISSUE THREAD

**Issue by jahvon** [solo-io/gloo#4392]
**Describe the bug**
The changelog bot that runs with CI does not fail if a version directory is prepended by a zero (e.g. v01.6.17 instead of v1.6.17). This broken pattern does not play nicely when creating a new release for that version.

**To Reproduce**
1. Create a new version directory & file under `/changelog` with a version that has the leading zero
2. After running the changelog bot with that change, you should observe that the changelog is accepted despite the pattern mismatch.

**Expected behavior**
The changelog bot should fail since the pattern in Solo repos are to drop the leading zero if the value itself if not zero.

**Additional context**
An example of a PR that made it through with this bug: https://github.com/solo-io/solo-projects/pull/2120/files

**Comment by nfuden** [comment]
Closing as we plan to migrate changelog logic
