### ISSUE TITLE
Document the fact that a CPU request is needed for HPA to works properly.

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#4404]
**Describe the requested changes**
For the new HPA in Gloo Edge 1.7 to work "out of the box" with the autoscaling/v1 API (i.e. CPU usage percentage), the `gateway-proxy` Deployment in the Helm chart also needs to define a resource request for CPU.
The difficulty here may be that a CPU resource request can only be specified in "absolute CPU cores", like "0.1".
It  needs to be documented.

**Comment by stippi2** [comment]
With "difficulty" I mean that the value that will work well for a deployment of Gloo Edge depends on the available CPUs of the nodes. In order to bind one gateway-proxy pod per node, it needs to be greater 50%, whatever that is in absolute CPU core units for the given cluster.
For example, I've been able to get it to work on a cluster with "2 CPU" nodes with a value of "1.1". This then made the additional pod "unschedulable", thus triggering the cluster auto-scaler to provide additional nodes.

**Comment by kevin-shelaga** [comment]
@djannot @stippi2 I added a warning in the helm values, but i guess that isn't brought down into the docs. Is the current warning sufficient if it was correctly listed in the helm docs? Or would you like something more detailed?

```
`json:"horizontalPodAutoscaler,omitempty" desc:"HorizontalPodAutoscaler for the GatewayProxy. 
Used only when Kind is set to Deployment. 
Resources must be set on the gateway-proxy deployment for HorizontalPodAutoscalers to function correctly"`
```

**Comment by stippi2** [comment]
It is fresh on my mind what stuff I had to look into before gaining anything that resembles a sufficient understanding on the topic. As such, this note would not be helpful enough for me. Maybe there should be a dedicated topic for this in the Gloo Edge documentation, for example under Operations. The following points are important:

* Envoy makes very efficient use of all the available CPU cores on the node that it runs on. This means there is no point in scheduling additional pods, *unless* these pods are scheduled on new nodes. This means the HPA needs to work in combination with a cluster autoscaler.
* For the cluster autoscaler to have the desired effect, the Pod resource request needs to be designed in such a way, that only one gateway-proxy pod fits onto a single node. How this is achieved would be cluster specific.

That much information can probably not be included in the Helm values alone. (Actually, I am not sure *where* the above would even appear.)

**Comment by kevin-shelaga** [comment]
@stippi2 Thanks for the detailed response. I do however disagree with the need to run 1 gateway per node. I currently run 2 or more on a single node, and this would be quite variable based on the node size and node count. I do agree however that a more detail guide should be added.

@djannot To the original ticket comment, im wondering where the restriction on absolute cpu cores is.
You should be able to set resources as follows (as an example):

```yml
            limits:
              cpu: 250m
              memory: 0.5Gi
            requests:
              cpu: 150m
              memory: 0.4Gi
```

and with autoscaling/v1 the following (as an example)

```yml
  targetCPUUtilizationPercentage: 75
```
