### ISSUE TITLE
Allow users to set gzip compression in helm chart values

### ISSUE THREAD

**Issue by stevejr** [solo-io/gloo#4405]
**Is your feature request related to a problem? Please describe.**
Helm chart values do not allow you to set GZIP compression and its options

**Describe the solution you'd like**
Ability to set GZIP compression and its options in the helm chart values.

**Describe alternatives you've considered**
Apply as a postRender option in helm or use kustomize.

**Additional context**

**Comment by kdorosh** [comment]
as noted in https://github.com/solo-io/gloo/pull/4424 , custom http gateway helm value can be used for this
