### ISSUE TITLE
OAuth token validation additional parameters

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4407]
**Is your feature request related to a problem? Please describe.**
When using access token validation there is no way to provide additional parameters to the introspection request

**Describe the solution you'd like**
An option to provide additional parameters (or headers)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sam-heilbron** [comment]
This was handled by https://github.com/solo-io/gloo/issues/4418.
