### ISSUE TITLE
change default extauth timeout to sane value

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4409]
**Is your feature request related to a problem? Please describe.**
the default extauth timeout is 200ms which is almost never enough for a real world OIDC flow

**Describe the solution you'd like**
a higher default value to save troubleshooting time and improve UX of the OIDC flow

**Describe alternatives you've considered**

**Additional context**

**Comment by sam-heilbron** [comment]
Very similar to https://github.com/solo-io/gloo/issues/4140.

**Comment by jmunozro** [comment]
Found this same problem twice this week

**Comment by sam-heilbron** [comment]
@lgadban Now that we support configuration of multiple ext auth filters (https://github.com/solo-io/gloo/issues/4874) is this still necessary?

**Comment by lgadban** [comment]
So the primary motivation here was the default timeout is very short when using our OIDC plugin with an external OIDC server.

The multiple ext auth filters seems very useful but not really sure it would help alleviate the problems with OIDC.
In other words, users would still need to configure/change the timeout value, and now would need to define a different extauth filter just for OIDC?
