### ISSUE TITLE
OIDC - logout - call the OP end_session_endpoint

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4410]
Here is a workflow that a customer would like to implement:
- end-user calls the `logoutPath`
- Gloo builds a request to call the OP's `end_session_endpoint` to invalidate tokens on the OP side
- Gloo destroys the session
- Gloo redirects to an alternative post-logout path (see #4391 )

That allows invalidating session tokens on the OP side.

OIDC spec drafts about this `end_session_endpoint` param:
https://openid.net/specs/openid-connect-discovery-1_0.html
https://openid.net/specs/openid-connect-rpinitiated-1_0.html

**Additional context**
Gloo Edge v1.6.19

**Comment by inFocus7** [comment]
There's an issue with us not setting the EndSessionParameters in enterprise. To not break user experiences (if any have it set, and have environments working) we're going to release the fix in 1.15 enterprise as part of [this enterprise issue](https://github.com/solo-io/solo-projects/pull/5167). If any objections or anyone reports the issue in our LTS releases, then we'll look into backporting the fix. 👍🏼
