### ISSUE TITLE
X-Forwarded-For address not being passed to modsecurity rules

### ISSUE THREAD

**Issue by saiskee** [solo-io/gloo#4433]
Slack thread: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1615498320149900

The client address retrieved from the X-forwarded-for header sets the `remoteAddress` field. However, in the modsecurity plugin, (https://github.com/solo-io/envoy-gloo-ee/blob/master/source/extensions/filters/http/modsecurity/filter.cc#L164), we pass in the `directRemoteAddress`, which is not affected by the x-forwarded-for header. So if the x-forwarded-for header is set, the wrong client address is passed into modsecurity.

# Expected Behaviour

if `x-forwarded-for` header is `192.168.2.1`, I should expect the modsec rules to see `192.168.2.1` as the client IP.

**Comment by kdorosh** [comment]
fix merged into our enterprise envoy, will be picked up in the next dependency bump of envoy-gloo-ee (v1.18.0-rc4 or v1.18.0-patch1)
