### ISSUE TITLE
Gloo admin control to manually kill active sessions

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4446]
As a Gloo platform admin,
Given OIDC sessions stored in Redis,
I want to be able to delete active sessions manually.

**Comment by kdorosh** [comment]
Beginning guide to walk through our OIDC implementation in our enterprise extauth server: https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/oauth/

configured by this filter in envoy: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html

the implementation for this service lives here: https://github.com/solo-io/ext-auth-service/tree/master/pkg/config/oidc
