### ISSUE TITLE
Trivy scan not working on backported branches

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4453]
**Describe the bug**
sample logs https://github.com/solo-io/gloo/runs/2135798020?check_suite_focus=true

we should re-evaluate how it works in a multi branch environment. also, work towards a single source of truth (hard to maintain current implementation because there are two sources of truth on the list of docker containers and because it's hard to run the GH action locally since it's so complex)

**Comment by kdorosh** [comment]
Also, the formatting here is a little off https://docs.solo.io/gloo-edge/master/reference/security-updates/open_source/ 

Looks like we forgot newlines after the "No vulnerabilities found ..."

**Comment by kdorosh** [comment]
Other ideas:
- could run the scans entirely from master, check out the version of the release and `make docker`, scan the containers built by that
- could run a cronjob once per week to update scans in google bucket (might take a while; even though scans are fast, pulling large and numerous docker containers is slow). docs could then get this update once per week

**Comment by saiskee** [comment]
We now run a cronjob once per week that scans previous branches and updates the docs.
https://docs.solo.io/gloo-edge/master/reference/security-updates/enterprise/
