### ISSUE TITLE
OIDC - possiblity to select the token type that will trigger the refresh flow

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4456]
Looks like the default behavior is to trigger the refresh flow when the `id_token` is expired.
Is there a special reason for that choice?
Can we provide an option to rather select the `access_token` expiration date as the trigger for refreshing tokens?

**Comment by marcelsigner** [comment]
Backends typically use only the access_token for access_control.
It makes sense to have a shorter expiration time for access_tokens. 
It would probably make sense to also have an option to check expiration of both id_token and access_token to trigger refresh flow.
