### ISSUE TITLE
possible issue with `labels.AreLabelsInWhiteList`

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#446]
there are a few places where we use `labels.AreLabelsInWhiteList(spec.Selector, podLabels)`

specifically in `kube/eds.go` and `kube.uds.go`

while working on supergloo, i noticed that this function was failing to properly assess if pod labels matched a selector. switching to 

`labels.SelectorFromSet(spec.Selector).Matches(labels.Set(podLabels))` fixed the issue. we should add a unit test and possibly switch from one to the other to confirm if this is an issue

**Comment by kdorosh** [comment]
Reading over the code, the two implementations are indeed different. `labels.AreLabelsInWhiteList(spec.Selector, podLabels)` returns true if the provided whitelist (`podLabels` in our case) is empty, meanwhile `labels.SelectorFromSet(spec.Selector).Matches(labels.Set(podLabels))` would return false if `podLabels` were empty and `spec.Selector` were non-empty.

I'm not sure if this explains the behavior you were seeing (I wouldn't expect `podLabels` to be empty in most cases in `kube/eds.go` or `kube/uds_convert.go`).

Do you have more details on how to reproduce, or a set of sample pod labels that didn't validate the way you were expecting?

**Comment by rickducott** [comment]
Closing as stale
