### ISSUE TITLE
Create metrics per API with per client/user dimension

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4461]
**Is your feature request related to a problem? Please describe.**
When using gloo edge, there's not out-of-the-box metric for API requests etc.
Additionally, when using API keys (or another form of authn) there's no dimension to the metrics per client/user

**Describe the solution you'd like**
Out-of-the-box API metrics with client/user dimension

**Describe alternatives you've considered**
custom access logging with custom prom metrics driven from access logs

**Additional context**
related: https://github.com/solo-io/gloo/issues/3678

**Comment by jmunozro** [comment]
I got some more interest in this feature. Specifically about the ability to get metrics for the number of request per hostname/authority.
It will be very nice to have this feature @chrisgaun

**Comment by chrisgaun** [comment]
Metrics is major initiative for v1.10
