### ISSUE TITLE
Docs: glooctl add route command missing autoHostRewrite option

### ISSUE THREAD

**Issue by rvennam** [solo-io/gloo#4463]
**Describe the requested changes**
https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_selection/path_matching/#exact

Under "Exact matching" section, the docs provide two ways to create the VS....either kubectl or glooctl. The kubectl way works, but the glooctl does not. I think it's because the glooctl add route command is missing the autoHostRewrite option. 

```
glooctl create vs --name test-exact-2 --namespace gloo-system --domains foo
glooctl add route --name test-exact-2 --path-exact /posts --dest-name json-upstream
```

![image](https://user-images.githubusercontent.com/5502967/111890794-5f928d00-89c3-11eb-9bde-d514be26f791.png)

I was receiving a 403 after running these two commands. However, I edited the VS and added the autoHostRewrite option and it started working

**Link to any relevant existing docs**
https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_selection/path_matching/#exact

**Comment by rvennam** [comment]
Same issue with the next section:
```
glooctl create vs --name test-regex --namespace gloo-system --domains foo
glooctl add route --name test-regex --path-regex /[a-z]{5} --dest-name json-upstream
```

**Comment by kevin-shelaga** [comment]
https://github.com/solo-io/gloo/issues/4368
