### ISSUE TITLE
Publish a dedicated Security Update RSS feed

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#4469]
**Is your feature request related to a problem? Please describe.**
The AppSec team of a Gloo Edge subscriber asks for a dedicated RSS feed for CVEs and security updates.  

**Describe alternatives you've considered**
We communicated that this information is available by client filtering of the full Solo blog [feed](https://www.solo.io/blog/feed/) or to subscribers via email updates.  Their AppSec team would still prefer a dedicated feed.

**Comment by kevin-shelaga** [comment]
Requested from another customers AppSec team due to the recent Envoy CVEs.

**Comment by antonioberben** [comment]
similar topic https://github.com/solo-io/gloo-portal-issues/issues/149
