### ISSUE TITLE
Expose `customPort` interface on the gateway helm chart value

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4475]
**Is your feature request related to a problem? Please describe.**
There isn't a helm value override where one can expose the Gateway pod's already exposed port (9091) on the service. The pod already exposed a port that has metrics on it, but the managing service doesn't have  a matching port exposed. This creates a problem for people who predominately use the Prometheus operator's `ServiceMonitor`  CRD, which expects to target a port on a service. Currently, in this specific case, the customer requesting this feature doesn't support `PodMonitor` resources, which would allow for targeting ports directly.

**Describe the solution you'd like**
Exposing a `customPort` interface like that of `gatewayProxies.gatewayProxy.service.customPorts[]` on the gatewayProxy, but for the `gateway` object.

**Describe alternatives you've considered**
Replace the `gateway` deployments's service with a template. This feel inherently risky, especially when helm values that we have already are so useful.

**Comment by rustrial** [comment]
This affects `gloo`, `gateway` and `discovery` deployments, which all do not expose stats (metrics) port `9091` as named port in the `Pod` resp. `Service`. `PodMonitor` and `ServiceMonitor` only work if a (named) port is exposed by the `Pod` resp. `Service`.
