### ISSUE TITLE
Helm chart does not properly handle tracing providers in v1.6.x

### ISSUE THREAD

**Issue by tmojlupo** [solo-io/gloo#4483]
**Describe the bug**
In the 1.5.x helm charts, we could specify the tracing provider and it would add the settings to the gatewayProxy configmap.  This functionality was lost in the move to 1.6.x.

https://github.com/solo-io/gloo/blob/v1.5.x/install/helm/gloo/templates/9-gateway-proxy-configmap.yaml#L303

**To Reproduce**
1. Create a values.yaml file with the following contents:
```gatewayProxies:
  gatewayProxy:
    tracing:
      provider:
        name: envoy.tracers.zipkin
        typed_config:
          "@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig"
          collector_cluster: zipkin
          collector_endpoint: "/api/v2/spans"
          collector_endpoint_version: HTTP_JSON
      cluster:
      - name: zipkin
        connect_timeout: 1s
        type: STRICT_DNS
        load_assignment:
          cluster_name: zipkin
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: otel-collector.gloo-system.svc.cluster.local
                    port_value: 9411
```
2. Use the helm template command using that values file and compare the output from 1.5.17 to 1.6.18.
`helm template gloo solo-public-helm/gloo --version 1.6.18 --values values.yaml`
`helm template gloo solo-public-helm/gloo --version 1.5.17 --values values.yaml`
3. The 1.5.17 version will create a configMap called gateway-proxy-envoy-config with the following text in it:
```data:

  envoy.yaml: |
    layered_runtime:
   ...
    tracing:
      http:
        name: envoy.tracers.zipkin
        typed_config:
          '@type': type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
          collector_cluster: zipkin
          collector_endpoint: /api/v2/spans
          collector_endpoint_version: HTTP_JSON # if $spec.tracing.provider # if $spec.tracing
```
   The 1.6.18 version will not have that section.

**Expected behavior**
I expect that Gloo 1.6.x would properly create the envoy.yaml configMap including the tracing provider settings as it used to.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.6.x

**Comment by sam-heilbron** [comment]
Followed up on slack, but here's the context for those interested:

Envoy deprecated the bootstrap configuration for a tracing provider (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto) . Envoy recommends configuring the tracing at the listener level, instead of the bootstrap level. These docs (https://docs.solo.io/gloo-edge/latest/guides/observability/tracing/#2-configure-a-tracing-provider) should outline how to configure a tracing provider on a listener,
