### ISSUE TITLE
observability pod - unable to use the caBundle to point to an existing Grafana instance, over https

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4486]
**Describe the bug**
Given an existing Grafana instance, serving requests over HTTPS
When the observability pod tries to sync to this Grafana instance, 
It needs a caBundle to trust the remote peer
But the caBunde is read as a file, not as a plain PEM value.
So we either need a way to mount an additional volume and to copy this PEM value into a new file
Or, to change the code, so that is read bytes, instead of a file
See https://github.com/solo-io/solo-projects/blob/master/projects/observability/pkg/syncer/setup_syncer.go#L169

**To Reproduce**
```yaml
prometheus:
  enabled: false
grafana:
  defaultInstallationEnabled: false
observability:
  customGrafana:
    enabled: true
    password: "password"
    url: "https://grafana.mycorp.net"
    username: "gloo"
    apiKey: "foo"
    caBundle: |
      -----BEGIN CERTIFICATE-----
      MIIDLTCCAhWgAwIBAgIUVLBYmdFzE1KmyrOqtI33JgmceQMwDQYJKoZIhvcNAQEL
      BQAwJjEkMCIGA1UEAwwbazhzLWdyYWZhbmEtbm9zc28uZ2ZzcnYubmV0MB4XDTIx
      MDMyNTExMDI1MVoXDTIyMDMyNTExMDI1MVowJjEkMCIGA1UEAwwbazhzLWdyYWZh
      bmEtbm9zc28uZ2ZzcnYubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
      AQEAqZAdMdvy/3DyY/hX7rD+1dKhfs3+aTw6BVBjc40ubAchM7OK9jd4c5olNKPN
      TBHPZpmEBdTRuxGx47hQek64BVH/Z9UYA4UWa1LWRCM8vP+OnwZq+AocIYaQm6dR
      kaFZnzlI6JUwdnPWyVWiFrqjO/p5bIY3nGNj9x9nyyDDU06pHNMhl+O2k8pqMzGc
      tWEuh0eL2NTvhoD/pP4pvgcU+lIoZvxzVNnesWwDT57byuj7ojUa7FtCT0LoYSog
      7xoQsMwCOmX81Z18+yJQOSQt4YPPiS2NjB5ZdKDuYvFnqW+wh190sODzqDvVI8an
      hlydnjxuOnB7rvdw4a6Qo5ZTswIDAQABo1MwUTAdBgNVHQ4EFgQUCHHxuZlwwhHx
      TZwl0/J+fHylfSEwHwYDVR0jBBgwFoAUCHHxuZlwwhHxTZwl0/J+fHylfSEwDwYD
      VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAMVevIM+nkMq4QavTZSvB
      Kzh3PuNwa+lsZM0YEQ+oAfcXcGlklr3Xdk861oskYw7cSrLEw8NLkvjmAvQag8cJ
      uQL1dzODVR1dJ3Hzb+T7ug1yfGFx18aMgR20u0WnBPGSfqMIWl4gaWruFSdjOmZ7
      LqHEarkX3ymPp7uxx5XPAKrvDqu2CL7mTzb1Q2fJoThOryZoSz3j9u89v7Z0bVWl
      s0nzECwF0brTBd6U0R4Ork6mWFlSf1WgagpzxMKkNxclG8n9jAT+j89aE7jabY5Y
      oKXUHF6+3OsbL9O36IvF2ow6mMW3guzLTo1cr4Z9wo4s1bfhR06yOFUFbIxOP3bS
      fw==
      -----END CERTIFICATE-----
```

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.6.21

**Comment by bcollard** [comment]
Additional issue there: the helm chart only consumes that `caBundle` property if the `apiKey` property exists. That doesn't make sense in the case above, where credentials are used.

**Comment by jad-solo** [comment]
We are using a custom Grafana with the required caBundle parameter, and there’s no good way to pass the certificate file. For us, it would be great if this parameter is made optional (as we use AWS managed Grafana, there’s no need for a specific CA). Adding an extraVolume + extraVolumeMount helm chart params to the observability would potentially work as well.

**Comment by bcollard** [comment]
now blocking another customer
