### ISSUE TITLE
Changelogs not rendering in the docs

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4522]
**Describe the bug**
Changelogs are not rendering in the docs

**To Reproduce**
see https://docs.solo.io/gloo-edge/latest/reference/changelog/open_source/

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version
- Kubernetes version

**Comment by kevin-shelaga** [comment]
@kdorosh 2 hours ago they were rendering fine, maybe a recent commit?

<img width="915" alt="image" src="https://user-images.githubusercontent.com/65769106/113170844-f0b00200-9214-11eb-8f7f-1c04376cec3f.png">

**Comment by kdorosh** [comment]
@kevin-shelaga yes, I'm thinking https://github.com/solo-io/gloo/pull/4521 caused it, looking into now

**Comment by kdorosh** [comment]
fixed by https://github.com/solo-io/gloo/pull/4523
