### ISSUE TITLE
Transformation validation takes a very long time with many transformations

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#4526]
**Describe the bug**
When using many transformations, validation can take a long time as a result of how transformations are validated.

**To Reproduce**
1. Have many transformations throughout a given Proxy's config. These can be in many `VirtualServices`, or `RouteTables`.
2. Attempt to apply new gloo config

**Expected behavior**
The config should be applied in a reasonable amount of time

**Comment by sam-heilbron** [comment]
With transformation caching introduced (https://github.com/solo-io/gloo/issues/4593), validation should no longer take a long time.
