### ISSUE TITLE
Docker question

### ISSUE THREAD

**Issue by andye2004** [solo-io/gloo#453]
I am interested in using Gloo as a control plane between Envoy and Consul but for reason I can't / won't go into I have to use the dockerised installation. However, in the official docs it states the docker install is for testing only. Are there any plans for this to become an 'official' release / install?

Thanks, Andy.

**Comment by ilackarms** [comment]
we are currently working on official support for running Gloo inside a VM (without kubernetes). i'm not sure if this solution will include support for Docker compose + consul but we have supported this in past releases of Gloo. @rickducott @yuval-k

**Comment by andye2004** [comment]
@ilackarms Thanks Scott!

**Comment by andye2004** [comment]
@ilackarms Actually, if the VM version was supported on different Linux flavours and one fo those was a RHEL7 flavour that would probably suit our purposes better - at least at this stage.

**Comment by ilevine** [comment]
We are working on it now. I believe it will be ready in 3-4 weeks.

**Comment by yuval-k** [comment]
related to #557

**Comment by yuval-k** [comment]
I'm closing htis as answer, further updates will be in #557.
please re-open if needed.
