### ISSUE TITLE
How many intermediate CAs can Gloo Edge support?

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4537]
Large orgs leverage many (100 or more) intermediate CAs. How many intermediate CAs can Gloo Edge support?

**Comment by kdorosh** [comment]
@cmwylie19 @mlholland to be clear, you're actually asking about the number of intermediate certs allowed on the cert chain in envoy?

**Comment by mlholland** [comment]
Hi, Gloo Edge supports as many intermediate CA's as envoy, so I dug around their docs to try finding out what their cert chain maxes are. I found a couple references, including the main certificate api, which contains a cert chain array, and the http connection manager, which has a flag that determines whether or not to include the entire encoded cert chain in a request. Neither of these mention any enforced maximum, which suggests that Envoy has no hard limit on intermediate CAs.
References: 
 - https://www.envoyproxy.io/docs/envoy/latest/api-v3/admin/v3/certs.proto.html?highlight=certificates#envoy-v3-api-msg-admin-v3-certificatedetails
 - https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html?highlight=http_connection_manager

**Comment by cmwylie19** [comment]
> @cmwylie19 @mlholland to be clear, you're actually asking about the number of intermediate certs allowed on the cert chain in envoy?

That is correct.
