### ISSUE TITLE
Code generation is slow

### ISSUE THREAD

**Issue by npolshakova** [solo-io/gloo#4559]
**Describe the bug**
GlooE code generation now also generates gloo-fed code, which has slowed down code-gen. 

**To Reproduce**
`go mod tidy; make update-all-deps generate-all -B` has slowed down (takes ~15min+)

GlooOS also takes ~8min+ to run, maybe can be sped up? 

**Expected behavior**
Speed up code generation.

**Comment by sam-heilbron** [comment]
The above PR's speed up the solo-kit (and skv2) portion of codegen. The specific improvements are outlined in each of those PRs. The remaining codegen duration is based on `//go:generate` references in the code. 

Gloo OS [`make -B install-go-tools generated-code`]: ~2min 16s

After GlooOS is released, I can get specific measurements for GlooE, but it has increased dramatically as well. After the solo-kit and skv2 optimizations have made it to master in gloo and glooE, I will close this issue.

**Comment by sam-heilbron** [comment]
Using https://github.com/solo-io/solo-projects/pull/2346, codegen in Gloo Enterprise is decreased dramatically:

`go mod tidy; make update-all-deps generate-all -B`: ~4min 30s
