### ISSUE TITLE
error enabling proxy compression using the helm chart

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#4591]
in the documentation it is mentionned to set the compression using gloo.gatewayProxies.gatewayProxy.gatewaySettings.options.compressed_proxy_spec=true 

this result in an error in the gateway pod: 

```l in namespace gloo-system into v1Gateway: unknown field \"compressed_proxy_spec\" in gloo.solo.io.ListenerOptions","version":"1.6.21","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:89\ngithub.com/solo-io/gloo/projects/gateway/pkg/setup.Main\n\t/workspace/gloo/projects/gateway/pkg/setup/setup.go:13\nmain.main\n\t/workspace/gloo/projects/gateway/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}```

**Comment by saiskee** [comment]
@asayah This can now be set as `gateway.compressedProxySpec` in the helm values.

**Comment by imraulkays** [comment]
Could you megre it to 1.6. version?
