### ISSUE TITLE
Speed up transformation validation via caching

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#4593]
**Is your feature request related to a problem? Please describe.**
Currently validating transformations can take a very long time since we do them every single time, even if they have not changed.

**Describe the solution you'd like**
We can cache the previous results of transformation validations, and if the transformations has not changed, we can just use the existing result.

**Comment by sam-heilbron** [comment]
Resolved by https://github.com/solo-io/gloo/pull/6047.
