### ISSUE TITLE
Support --kubeconfig in glooctl

### ISSUE THREAD

**Issue by ewbankkit** [solo-io/gloo#461]
Like `kubectl` and `istioctl`, it would be good for `glooctl` to support `--kubeconfig` to be able to specify a non-default Kubernetes configuration file location.

**Comment by ilackarms** [comment]
this is a good suggestion. at the moment you can set the kubeconfig path via the `KUBECONFIG` env var

**Comment by EItanya** [comment]
resolved by #1198
