### ISSUE TITLE
Swagger/OpenAPI spec files with REF files will not have functions discovered by FDS

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4616]
**Describe the bug**
Swagger/OpenAPI spec files with REF files will not have functions discovered by FDS.

https://swagger.io/docs/specification/using-ref/

```yml
    responses:
      '200':
        description: The response
        schema: 
          $ref: '#/components/schemas/User'
```

**To Reproduce**
1. kube apply '...'
2. curl '....'
3. See error

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version v1.7.0
- Kubernetes version

**Comment by Todai88** [comment]
👋 

I raised this issue, and can easily be contacted within my working hours (8am-6pm GMT). 

Happy to assist in any way. 👍
