### ISSUE TITLE
Glooctl check throttling warning - v1.7.2

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4620]
**Describe the bug**
glooctl check with gloo v1.7.2 will produce throttling warnings. Possibly only enterprise related as the throttling happens after the regular gloo checks.

```sh
glooctl check              
                                      
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... OK
Checking rate limit server... OK
No problems detected.
I0420 06:54:26.190389   80208 request.go:645] Throttling request took 1.029122056s, request: GET:https://1.1.1.1/apis/admissionregistration.k8s.io/v1?timeout=32s

Detected Gloo Federation!
```

**To Reproduce**
1. install glooctl and gloo ee 1.7.2
2. glooctl check
3. See error

**Expected behavior**
Expected no throttling warning

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version - v1.7.2
- Kubernetes version - 1.18.17-gke.100

**Comment by DuncanDoyle** [comment]
Outdated. Can't reproduce on latest (1.16.6) release. Closing.
