### ISSUE TITLE
WAF - upgrade the dependency to CoreRuleSet

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4632]
We need to upgrade our dependency to CRS from 3.2.0 to 3.3.0
See https://github.com/solo-io/solo-projects/blob/51b46531f13ce91e5efabf08fa54280e206ea5ca/cmd/envoyinit/Dockerfile.envoyinit#L20

**Comment by chrisgaun** [comment]
Related to https://github.com/solo-io/gloo/issues/5698
