### ISSUE TITLE
gateway-proxy-envoy-config configmap is hard to edit

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4645]
**Describe the bug**
When you need to update the envoy config, you naturally edit the `gateway-proxy-envoy-config` configmap in the `gloo-system` namespace. The only problem is that it is extremely difficult to tell if you have formatted the envoy config correctly.

![image](https://user-images.githubusercontent.com/1096507/115784631-63cc1480-a38c-11eb-8a66-e941c1756ad5.png)

**To Reproduce**
1. `kubectl get cm -n gloo-system gateway-proxy-envoy-config -oyaml `

**Expected behavior**
`.data.envoy.yaml` to be formatted so if you need to edit it you can verify that you have formatted the yaml correctly

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version `1.7.2` but i think this affects all versions
- Kubernetes version

**Comment by mohanchoudary** [comment]
how can we display yaml well-formatted for config map. I did not install gloo-edge with helm.

**Comment by MitchAman** [comment]
> how can we display yaml well-formatted for config map. I did not install gloo-edge with helm.

@mohanchoudary I was able to do display the config map with the following steps:

Creating a local cluster:
```
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋
```
I'll be installing on 1.8.0:
```
$ glooctl version
Client: {"version":"1.8.0"}
Server: version undefined, could not find any version of gloo running
```
Install:
```
$ glooctl install gateway
Creating namespace gloo-system... Done.
Starting Gloo Edge installation...
...
Gloo Edge was successfully installed!
```
Getting the config map:
```
$ kubectl get cm -n gloo-system gateway-proxy-envoy-config -oyaml
... (some output omitted) ...
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: gloo
    meta.helm.sh/release-namespace: gloo-system
  creationTimestamp: "2021-07-12T15:10:32Z"
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gateway-proxy-id: gateway-proxy
    gloo: gateway-proxy
  name: gateway-proxy-envoy-config
  namespace: gloo-system
  resourceVersion: "801"
  uid: 94624670-8319-4d78-ba73-fdf4f85e2a71
```
