### ISSUE TITLE
changelog diff tool in docs

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4653]
**Is your feature request related to a problem? Please describe.**
@saiskee to add more detail to ticket

UX for upgrading can be painful, when determining changes between versions.

**Describe the solution you'd like**
we want to update the changelog docs to allow users to take any two versions and diff the changelogs,

**Additional context**
Implementing this would require adding javascript to hugo, which is possible.

**Comment by saiskee** [comment]
this done.
