### ISSUE TITLE
Cookies remain after logout when cookie options are defined

### ISSUE THREAD

**Issue by jahvon** [solo-io/gloo#4657]
**Describe the bug**
OIDC session cookies are not being deleted by a user's browser upon logout when Auth Config cookie options (like domain) are defined. I suspect that this is because the `set-cookie` header that we pass when handling a logout does not include those options so the existing cookie is unable to be overwritten. (A quick google search suggested that those field must match in order for a cookie to be updated)

**To Reproduce**
1. Setup an OAuth integration with a [logout path](https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/oauth/#logout-url) and a [cookie option](https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/oauth/#cookie-options), like domain.
2. Log in to the application and then log out
3. Observe the cookies that still exist. You should still see the id/access token cookies after logging out in your browser.

**Expected behavior**
Session cookie is set to expired (and consequently deleted by the browser) when logging out

**Additional context**
Tested with Gloo v1.7.2
[Relevant code](https://github.com/solo-io/ext-auth-service/blob/c848d626d8ae96cb2def6c960d4ae4d42bd7acdc/pkg/session/session.go#L64)

**Comment by kdorosh** [comment]
Per @jahvon , adding those cookie options should resolve the issue and is likely a very small change to the Gloo extauth service.
