### ISSUE TITLE
`glooctl proxy served-config` difficult to maintain in current state, prone to breaking

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4665]
**Describe the bug**
`glooctl proxy served-config` is a useful debugging tool to see what XDS config Gloo is currently serving. To do this, it needs to marshal and unmarshal any potential envoy type, which means the marshaller needs every possible type registered.

Right now, the imports are manual and statically defined. As envoy adds / moves around types, these imports need to be updated. 

We can update the code to mirror the codegen approach that we followed in envoyinit in Gloo, to marshal and unmarshal the bootstrap config. We need to make sure we update that approach to be shared (DRY) and to ensure it handles Gloo types as well, not just envoy types.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version
- Kubernetes version

**Comment by kdorosh** [comment]
The generated file in envoyinit https://github.com/solo-io/gloo/blob/master/projects/envoyinit/cmd/utils/filter_types.gen.go

how we generate it: https://github.com/solo-io/gloo/blob/master/projects/envoyinit/cmd/utils/filter_types.go#L15-L31

The PR where we fix served config, but in a way that's prone to breaking again (hence this ticket): https://github.com/solo-io/gloo/pull/4662

**Comment by jahvon** [comment]
Reopening this since the merged fixes don't take into account that the types in `go-control-plane` may not align with the types in the Envoy version that `envoy-gloo` is built on (i.e. the API imported could be different than the Envoy we support)
