### ISSUE TITLE
glooctl could provide more context about what is causing an error

### ISSUE THREAD

**Issue by ianrudie-tmus** [solo-io/gloo#4668]
**Is your feature request related to a problem? Please describe.**
When running `glooctl check` we received the following error:

```
* Listener Error: SSLConfigError. Reason: Tried to apply multiple filter chains with the same FilterChainMatch. This is usually caused by overlapping sniDomains in virtual services: {}
```

It is difficult to diagnose with this result what virtual service(s) gloo has found to be causing the issue.

**Describe the solution you'd like**
Would be great if this result included the name(s) of virtual service(s) which should be checked because they are causing the issue.

**Describe alternatives you've considered**
Alternatives would be writing our own script or utility that can be used after getting an error from glooctl to try to diagnose the issue glooctl has detected. This is what our support team suggested as a quick fix but they also requested we open an issue in github.

**Additional context**
Error was received from glooe v1.6.25 using glooctl v1.6.21

**Comment by kdorosh** [comment]
This error message is misleading but correct. It's telling you the list of overlapping SNI domains rather than the virtual services they are coming from. We will update the error message to be clearer.
