### ISSUE TITLE
Broken docs templating on kubernetes installation docs page

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4682]
**Describe the requested changes**
The Kubernetes installation docs have several instances of template syntax not being rendered correctly

**Link to any relevant existing docs**
https://docs.solo.io/gloo-edge/latest/installation/gateway/kubernetes/

Search for `{{% notice note %}}` for example.

Additionally, in the "Special Instructions to Install Gloo Edge on Kind" section, this is being rendered out:
"If you followed the cluster setup instructions for Kind [here]({{< versioned_link_path fromRoot="/installation/platform_configuration/cluster_setup/#kind" >}})"

**Browser Information**
N/A

**Additional context**
There may be additional instances on this page than the ones called out in this issue

**Comment by saiskee** [comment]
Fixed in https://github.com/solo-io/gloo/pull/4688; closing

**Comment by kdorosh** [comment]
there’s still a broken link in the “special instructions to install gloo edge on kind” section

**Comment by saiskee** [comment]
*This issue still exists in 1.7 and older versions. Shouldn't happen in master
