### ISSUE TITLE
Offer a HTTP REST based ExtAuth extension system

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4685]
Some customers would like to avoid the pain of implementing their authN/authZ service over gRPC.

The idea is to ship a generic service adapter from gRPC to REST for ExtAuth plugins. 

See option "2c" below:

![image](https://user-images.githubusercontent.com/9626829/116692475-b3c65f00-a9bc-11eb-9dfb-dbe6b1ff90e8.png)

This service could be an additional deployment - OR - being part of our ExtAuthz server, as an alternative option for the passthrough policy.

Additionally, this generic service should be able to pass the content of the ExtAuth `State` (sometimes containing info like the `jwt`), and also filter metadata (like `envoy.filters.http.jwt_authn` and `solo.auth.passthrough`)

**Comment by chrisgaun** [comment]
We need to discuss if no code solution would work with our existing ExtAuth passthrough. If not we will pick this up soon.
