### ISSUE TITLE
X-forwarded-proto header it's incorrectly set when terminating TLS at the loadbalancer

### ISSUE THREAD

**Issue by lzaldivarkt** [solo-io/gloo#4690]
**Describe the bug**
Following [these instructions](https://docs.solo.io/gloo-edge/master/guides/integrations/aws/), when you terminate TLS at the loadbalancer, hitting the https endpoint produces an incorrect x-forwarded-proto header, as follows:

`X-Forwarded-Proto: http`

This makes impossible to use `httpsRedirect`, you get a redirect loop, because the backend always see the same headers
And you can't enforce https in the backend either.

**To Reproduce**
deploy gloo-edge behind a tls terminated ELB
Both HTTP and HTTPs endpoints produce the same x-forwarded-proto headers, set as http

**Expected behavior**
`X-Forwarded-Proto: https` when hitting an https endpoint

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version
- 1.6.22
- Kubernetes version
- 1.16

**Comment by pmichna** [comment]
I can confirm the issue exists with NLB, Gloo Edge Enterprise 1.8.12, Kubernetes 1.19.
