### ISSUE TITLE
Add an option to set the value of the `prometheus.io/port` annotation in the Gloo Fed Helm chart

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#4700]
**Is your feature request related to a problem? Please describe.**
Currently, the `prometheus.io/port` annotation is hard coded to `9091` in several places.

**Describe the solution you'd like**
Add an option to set the value of the `prometheus.io/port` annotation in the Gloo Fed Helm chart.

**Comment by kuperiudazn** [comment]
Do you have any update on it ?
