### ISSUE TITLE
expose k8s "affinity:" on each deployment

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4706]
It would be convenient to control where exactly Gloo Edge pods are scheduled.
K8s offers different ways of doing that: `nodeSelector`, `affinity` or `nodeName` 
The most complete one being `affinity`, it would be nice to expose it in our helm chart, for each deployment.

**Comment by saiskee** [comment]
Resolved by https://github.com/solo-io/gloo/pull/4754
