### ISSUE TITLE
disable route API and CLI

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#473]
For the typical developer workflows, we don't want to force them to yaml if we don't have to. We need a way to manage routes (sort is there) like to mark them enabled, delete them, update/replace them, edit them, etc.

**Comment by christian-posta** [comment]
cc @rickducott

**Comment by ilevine** [comment]
deleting a route is now available. `glooctl remove route`;
disabling a route will require a change to gloo to support it
