### ISSUE TITLE
Install script broken

### ISSUE THREAD

**Issue by 205g0** [solo-io/gloo#4730]
on Ubuntu 20.04
```
# curl -sL https://run.solo.io/gloo/install | sh
Python is required to install glooctl
# python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
```

Some context: I mean I know what to do but like most, first, I want to get a (good) first impression of Gloo and if even the installer has such an obvious flaw which is apparently present for quite some time I'm not really motivated or positive to go any further...

**Comment by lgadban** [comment]
Hi @205g0 -- thanks for opening this issue

We're working on making the install script more robust; the changes should be ready shortly.

As a side-note, the `glooctl` binary is available for download directly from our Github releases, e.g. https://github.com/solo-io/gloo/releases/tag/v1.7.7

**Comment by lgadban** [comment]
closing via https://github.com/solo-io/gloo/pull/4751

please reopen if you still see issues!
