### ISSUE TITLE
Support SPNEGO/Kerberos for ExtAuth

### ISSUE THREAD

**Issue by murphye** [solo-io/gloo#4765]
For our Enterprise ExtAuth service, I could see adding support for SPNEGO/Kerberos. I have personally seen Kerberos in use at large customers for authentication for back-office types of applications.

This article, while focusing on Spring implementation, offers a nice explainer and links for reference: https://www.baeldung.com/spring-security-kerberos

This Envoy issue offers hints on how this can be implemented for ExtAuth: https://github.com/envoyproxy/envoy/issues/3876

What would be interesting is if Envoy can act as the Kerberos client, and be a 2nd stage of authentication for a request. The first step would be to authenticate the real client via OIDC, and then create the SPNEGO token afterwards. This would support modernization of legacy apps that use Kerberos with APIs that use OIDC.

Keycloak supports SPNEGO/Kerberos so the documentation would be helpful and could act as the Kerberos provider: https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/authentication/kerberos.html

**Comment by murphye** [comment]
I should add more context around this. First read this article: https://www.quora.com/What-are-the-differences-and-common-points-between-the-oauth-protocol-and-Kerberos

SPNEGO/Kerberos is fine for "back-office" types of applications running on a single LAN together in a data center. You can even set up a web browser to support Single Sign-On with Kerberos when running on this Intranet LAN.

This solution fits in where a company is trying to modernize back-office applications while also moving to the cloud. The concept of a single intranet LAN with consolidated application deployments goes away at that point. Something (i.e. Gloo Edge) needs to become the gateway and also the glue from a security perspective for both SPNEGO/Kerberos and OIDC.

**Comment by overbum** [comment]
What is about strong FQDN requirement for MIT Kerberos RFC.
Any hostname change via proxy means MITM. You will never get a TGS with changed destination host when you ask proxy with another ip (host). There is no way to go around. It is protocol thing.
Proxy is good for 2-ways mTLS (CN=username) or OpenID authentication. 
But UPN goes to specific SPN that has name service/fqdn@REALM asking KDC who will deny that request.
