### ISSUE TITLE
Hitting DuplicateNameError when adding BasicRateLimit to VS

### ISSUE THREAD

**Issue by willowmck** [solo-io/gloo#4769]
**Describe the bug**
Customer has several VS with domain '*:' and is attempting to apply a BasicRateLimit to one of the VirtualServices. The VS looks like the following (shows the error encountered):

- apiVersion: gateway.solo.io/v1
  kind: VirtualService
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.solo.io/v1","kind":"VirtualService","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"2"},"labels":{"app.kubernetes.io/instance":"b2b-uat"},"name":"uat-general-services-virtualservice","namespace":"b2b-sandbox-gloo-system"},"spec":{"sslConfig":{"secretRef":{"name":"secret-tls","namespace":"b2b-sandbox-gloo-system"}},"virtualHost":{"domains":["*:23101"],"routes":[{"matchers":[{"prefix":"/"}],"options":{"timeout":"0s"},"routeAction":{"single":{"upstream":{"name":"uat-general-services-upstream","namespace":"b2b-sandbox-gloo-system"}}}}]}}}
    creationTimestamp: "2021-05-17T04:35:35Z"
    generation: 8
    labels:
      app.kubernetes.io/instance: b2b-uat
    name: uat-general-services-virtualservice
    namespace: b2b-sandbox-gloo-system
    resourceVersion: "272708"
    selfLink: /apis/gateway.solo.io/v1/namespaces/b2b-sandbox-gloo-system/virtualservices/uat-general-services-virtualservice
    uid: 15faa7b6-eb39-494a-af77-cc89d1e999c6
  spec:
    sslConfig:
      secretRef:
        name: secret-tls
        namespace: b2b-sandbox-gloo-system
    virtualHost:
      domains:
      - '*:23101'
      routes:
      - matchers:
        - prefix: /
        name: b2b-sandbox-gloo-test-ratelimit
        options:
          ratelimitBasic:
            anonymousLimits:
              requestsPerUnit: 5
              unit: MINUTE
            authorizedLimits:
              requestsPerUnit: 5
              unit: MINUTE
          timeout: 0s
        routeAction:
          single:
            upstream:
              name: uat-general-services-upstream
              namespace: b2b-sandbox-gloo-system
  status:
    reason: "1 error occurred:\n\t* Route Error: ProcessingError. Reason: *ratelimit.Plugin:
      1 error occurred:\n\t* Basic rate limit already configured for resource with
      name [vs:uat-general-services-virtualservice_route:b2b-sandbox-gloo-test-ratelimit];
      routes and virtual hosts must have distinct names if configured with basic ratelimits.\n\n\n\n"
    reportedBy: gateway
    state: 2
    subresourceStatuses:
      '*v1.Proxy.b2b-sandbox-gloo-system.gateway-proxy':
        reportedBy: gloo
        state: 1
```

Other VirtualServices look very similar but do not have a rate limit set. Could this be a cache issue?

**To Reproduce**
Unable to reproduce this in my local environment so not sure if this is a Redis issue.

**Expected behavior**
Rate limit should be applied.

**Additional context**
Using Gloo 1.6.27.

**Comment by jenshu** [comment]
fixed
