### ISSUE TITLE
Consul Plugin Data Race

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#4782]
**Describe the bug**
Our consul tests failed due to a data race in the plugin

**Expected behavior**
The tests should be deterministic

**Additional context**
- Logs: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=ea748eb3-e3eb-497d-af75-23ffecc1bb4b

**Comment by sam-heilbron** [comment]
again: https://console.cloud.google.com/cloud-build/builds/68b4d46c-8c82-4bbb-9a79-0b9044788e0a;step=10?project=solo-public

**Comment by bewebi** [comment]
Another: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=361cd574-baeb-4768-a5aa-1bc6200f0e9c

**Comment by MitchAman** [comment]
https://console.cloud.google.com/cloud-build/builds;region=global/45008eda-a17e-4e47-9a8d-4329599eacdb;step=10?project=solo-public

**Comment by MitchAman** [comment]
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=667629e8-8e98-4c36-a38c-954f24bc6950

**Comment by MitchAman** [comment]
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=bc6703ab-904f-4716-a90e-cccf8a6a2cfe

**Comment by jenshu** [comment]
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=ec11eae1-f791-492b-b4d0-68413617dfd1

**Comment by sam-heilbron** [comment]
This has been merged into 1.12 -> 1.9.
