### ISSUE TITLE
glooctl proxy debug is changing the log level to debug (and not reverting it back)

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4788]
**Describe the bug**
`glooctl proxy debug` will change the log level to debug on the gateway-proxy. While handy, this can lead to log overflow in a production environment if you don't change the log level back to warn

**Expected behavior**
Revert the log level to its original value

**Comment by jameshbarton** [comment]
Internal reference: https://solo-io.slack.com/archives/G01MKQQ0Q3W/p1622100779042800
