### ISSUE TITLE
OIDC - redis TTL is not set by default

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4804]
**Describe the bug**
Probably related to #4766 
Given an AuthConfig CR configured with Redis as the session store,
If the `cookiesOptions > maxAge` is not set,
Then no TTL is set on the Redis entry for the user session

Should we consider this as a security issue? or at least as a memory leak?

**Additional context**
- Gloo Edge version 1.7.7

**Comment by sam-heilbron** [comment]
As part of the work for https://github.com/solo-io/gloo/issues/4766, we default the cookieOptions.maxAge. Now all redis entries will have a ttl.
