### ISSUE TITLE
OIDC - error 500 when maxAge is not set and when using Redis

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4805]
**Describe the bug**
Given an AuthConfig CR with Redis as the session store
When the `cookiesOption > maxAge`  is not set,
When the `id_token` is set to 30 sec,
Then the nominal login workflow is OK
But if I wait for the `id_token` to expire (after 30 sec) and, after that, I reload the web page,
Then I get a 500 error

Logs: https://gist.github.com/bcollard/e8e6eec5b6fea1086628bfddbff286af

**Additional context**
- Gloo Edge version 1.7.7

**Comment by kevinnesta** [comment]
I can notice this behavior too! Interested in fix! Thanks @bcollard

**Comment by sam-heilbron** [comment]
We confirmed that the work done to support https://github.com/solo-io/gloo/issues/4766 (setting a default cookie MaxAge) resolved this. Now even when the cookieOptions.maxAge is not set, it will default to a value, preventing this 500 error.
