### ISSUE TITLE
Solo-apis backport merges into master

### ISSUE THREAD

**Issue by saiskee** [solo-io/gloo#4836]
**Describe the bug**
When a backport is created in gloo, the gloo github automation creates a pull request against solo-apis master branch. This happens, for example, in this PR: https://github.com/solo-io/solo-apis/pull/103.

**Expected behavior**
We want backports to be based off their respective backport branches. So if I were creating a 1.7.5 backport, it would first checkout v1.7.x, then create the commit off of that. This will prevent massive diffs in PRs as well as make the repo cleaner.

**Additional context**
The appropriate code lives [here](https://github.com/solo-io/gloo/blob/64b70c9ce98a809d695b3c02c335ef43e6dea52d/.github/workflows/update-solo-apis.yaml#L46) and would need to be changed so we base new commits off of the respective release v1.7.x branch.

**Comment by jenshu** [comment]
[This file](https://github.com/solo-io/solo-apis/blob/master/.github/workflows/tag_gloo_apis.yaml) in solo-apis might also need to be updated to automatically create tags when there is a push to the release branches
