### ISSUE TITLE
Docs generation failing from rate limiting

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#4850]
**Describe the bug**
In CI, we are more frequently seeing:

```
Error: GET https://api.github.com/repos/solo-io/gloo/releases?page=5&per_page=100: 403 API rate limit of 60 still exceeded until 2021-06-06 20:45:28 +0000 UTC, not making remote request. [rate reset in 4m01s]
```

example: https://github.com/solo-io/gloo/pull/4843/checks?check_run_id=2758817249

Theory:
We are more frequently seeing this error in CI. Each docs generation makes requests to github to pull metadata about previous releases. At the moment, we do not configure an upper limit for the number of releases to request:
https://github.com/solo-io/gloo/blob/master/docs/cmd/generate_docs.go#L128

Without this upper limit, we default to MaxInt64 (https://github.com/solo-io/go-utils/blob/master/changeloggenutils/minor_release.go#L35) which means we will request release notes 100 at a time for all releases. We should specify the max version we need to avoid unnecessary requests to the github api.

**Comment by saiskee** [comment]
Fixed in https://github.com/solo-io/gloo/pull/4913.

We updated the go-utils changeloggen library in this PR: https://github.com/solo-io/go-utils/pull/453
