### ISSUE TITLE
Using weighted round robin in a static upstream

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#4872]
Using weighted round-robin in a static upstream
see: https://www.envoyproxy.io/docs/envoy/v1.18.2/intro/arch_overview/upstream/load_balancing/load_balancers.html#weighted-round-robin

**Comment by juli-vert** [comment]
Giving more insights. There are 2 levels of weighting: Locality and Endpoint. The basic scenario is a single locality with multiple endpoints and each of them with a specific weight:
"If weights are assigned to endpoints in a locality, then a weighted round robin schedule is used"
Having multiple endpoints (hosts) in this example ep01-03 and expecting a load distribution like 25-25-50%:
{
  "endpoint": "ep01",
  "load_balancing_weight": "1"
}
{
  "endpoint": "ep02",
  "load_balancing_weight": "1"
}
{
  "endpoint": "ep03",
  "load_balancing_weight": "2"
}
We want to use WRR within a single locality:
{
  "locality": "l01",
  "lb_endpoints": [ep01, ep02, ep03]
 }
