### ISSUE TITLE
glooctl -o kube-yaml format is not respected for some types

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#4881]
**Describe the bug**
`glooctl create secret ... --dry-run -o kube-yaml` is missing the `kind` and `apiVersion` in the output. It currently does the same thing as  `-o yaml`.

**Expected behavior**
The command should output valid k8s yaml that can be applied.

Need to fix this for `secret`, `authconfig`, and `ratelimitconfig`.

**Comment by nfuden** [comment]
This was brought up again with regards to unexpected output formats.
As part of this issue we should also attempt to enforce failing noisily on glooctl commands when asked for an output type that is not supported by the given command.

For example we could make a package that contains the unsupported output type errors and then output it anywhere needed. 
A bigger lift could combine with a checker to make sure that either all output types are mentioned in a file or a test that runs the same command with different output types and checks that the output is different (ie truly a different format)
