### ISSUE TITLE
Validation stops working under some circumstances

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4887]
**Describe the bug**
Something caused the validation component to stop performing validation:
`validation is disabled due to an invalid resource which has been written to storage. Please correct any Rejected resources to re-enable validation.","version":"1.5.14","error":"3 errors occurred:\n\t* invalid resource ns-conv.v1-user-policy\n\t* invalid route: route must specify an action\n\t* on sub route table ns-conv.v1-user-policy: invalid route: route must specify an action\n\n"`

Then, when another case of improper config was pushed:
`4 errors occurred:\n\t* invalid resource ns-conv.v1-user-policy\n\t* invalid route: route must specify an action\n\t* on sub route table ns-conv.v1-user-policy: invalid route: route must specify an action\n\t* WARN: \n [no route table matches the given selector]\n\n`

This caused envoy to crash because of the missing `routeAction`, which was not caught or rejected by validation, resulting in a full data-plane outage.

This is a log that possibly shows the original reject resource (e.g. the duplicate domains issue), however, there are NOT duplicate domains present. Note that the duplicate hosts are the same virtual service -- 
`Proxy resource gloo-system-internal.gateway-proxy is rejected with reason: 1 error occurred: * VirtualHost Error: DomainsNotUniqueError. Reason: domain ria-contactcenter.foo.com is shared by the following virtual hosts: [gloo-system-internal.ria-contactcenter.foo.com-virtualservice gloo-system-internal.ria-contactcenter.foo.com-virtualservice]; VirtualHost Error: DomainsNotUniqueError. Reason: domain ria-contactcenter.foo.com is shared by the following virtual hosts: [gloo-system-internal.ria-contactcenter.foo.com-virtualservice gloo-system-internal.ria-contactcenter.foo.com-virtualservice] warning: Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-test-helm-overwrite-48196 api-comm} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-techdebt-35331 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-rolebasedintents-36346 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-init-51065 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-perf-conversant-init ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-test-helm-overwrite-48196 api-comm} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-techdebt-35331 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-masking-35340 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-rolebasedintents-36346 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-review-init-51065 ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v1-perf-conversant-init ns-conv} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v4-review-all-the-metrics-33656 inf-pilot} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v4-review-metrics-timeouts-33656 inf-pilot} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v4-review-optimize-member-update-33656 inf-pilot} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {v4-review-test-old-tag-33656 inf-pilot} not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {inf-pres-test-ws-upstream inf-pres} not found`

Invalid Route replacement is enabled

**To Reproduce**
Not clear, how exactly can the validation component be disabled?

**Expected behavior**
Under no circumstances should the validation piece become disabled due to user configuration (?)

**Additional context**
GlooEE 1.5.14

**Comment by lgadban** [comment]
How is this possible?

`VirtualHost Error: DomainsNotUniqueError. Reason: domain ria-contactcenter.foo.com is shared by the following virtual hosts: [gloo-system-internal.ria-contactcenter.foo.com-virtualservice gloo-system-internal.ria-contactcenter.foo.com-virtualservice];`

These are the same virtual hosts

**Comment by kdorosh** [comment]
perhaps caused by https://github.com/solo-io/gloo/issues/4136

**Comment by lgadban** [comment]
very likely, backport: https://github.com/solo-io/gloo/pull/4141
fixed in 1.5.15

**Comment by lgadban** [comment]
closing due to no additional feedback
