### ISSUE TITLE
what license

### ISSUE THREAD

**Issue by MarkAtwood** [solo-io/gloo#489]
there is no LICENSE file, and there is no license declaration in the README

What license is gloo under?  Apache 2.0?

**Comment by rickducott** [comment]
Sorry about that @MarkAtwood, will fix today.

**Comment by rickducott** [comment]
Fixed in #494, thanks for flagging. 

Yes, we are licensed under Apache 2.0.

**Comment by MarkAtwood** [comment]
Thank you!
