### ISSUE TITLE
New transformationTemplate for queryParams 

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#4891]
**Is your feature request related to a problem? Please describe.**
It is a bit complicted to create transformations about queryParams

Probably a new `transformationTemplate` would be interesting.

The US would be something like:
Me, as an ops, I can create a transformation to handle my queryParams 
so that I can move, either a key or a value, from header to the query parameters, and vice-versa.

**Describe the solution you'd like**

For example:
```
GET /endpoint -H header1:value1
```
To become:
```
GET /endpoint?header1=value1
```

And:
```
GET /endpoint?header1=value1
```
To become:
```
GET /endpoint?header1=value1 -H header1:value1
```
Or:
```
GET /endpoint -H header1:value1
```

**Describe alternatives you've considered**
There were two possible alternatives:
- Try it with header transformations and `header(":path")`
- Create a wasm filter

Both are not quite handy

**Additional context**

**Comment by bcollard** [comment]
What about adding a new `addQueryParam` param under [TransformationTemplate](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk/#transformationtemplate) 
with `map<string, .envoy.api.v2.filter.http.InjaTemplate>`
This new option would check if there is a question mark in the path and append if it's not the case.
