### ISSUE TITLE
no CONTRIBUTING file

### ISSUE THREAD

**Issue by MarkAtwood** [solo-io/gloo#490]
the README has a link to CONTRIBUTING, but the file does not exist.

What is the CONTRIBUTING policy for gloo?

**Comment by rickducott** [comment]
Sorry about that, @MarkAtwood, the file got moved here: https://gloo.solo.io/dev/contributing/ during a docs migration. I'm going to move it back to the repo and refresh it.

**Comment by rickducott** [comment]
Fixed in #492
