### ISSUE TITLE
Dynamic Routing

### ISSUE THREAD

**Issue by newtack** [solo-io/gloo#4908]
Can I implement the scenario below and if so how?

- There can be many applications in our system
- Each application identified by a UUID and url has this UUID, e.g. https://mykubernetescluster.com/UUID/rest_of_url.
- Some applications are assigned to a master pod. If it is a put/post/delete or similar it should be routed to that pod.
- Some applications are assigned to slave pods. If it is not a write request, it should go to slave pod if it exists. If only a master exists, route it to the master.
- Some applications are not yet assigned to any pod. We should route it to a pod large enough to handle that request (each application has a size category). How can I route it to a pod with sufficient free resources?

**Comment by chrisgaun** [comment]
Hey, thanks for your question. Will get someone on it. Our community Slack is also a great place to ask questions

**Comment by chrisgaun** [comment]
Hey, Do you want to join the Slack and ask community at large there?
