### ISSUE TITLE
update glooctl demo federation

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#4917]
**Describe the bug**
`glooctl demo federation` needs to be updated to work with the latest release

This includes removing the hardcoded version number in the script
https://github.com/solo-io/gloo/blob/master/projects/gloo/cli/pkg/cmd/demo/federation.go#L83

**Comment by artberger** [comment]
Restore the `gloo demo federation` docs after this is updated.
* Commit that removed the docs: https://github.com/solo-io/gloo/pull/5521/commits/43df4161464a00c1b220234043a6bce882ad8013
* Discussion thread: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1635530712054300
