### ISSUE TITLE
delete user session data in Redis if the refresh grant type fails with invalid_grant

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4927]
On the IdP side, a user session can be revoked at any time. In this case and when the Refresh flow is triggered by the ExtAuth service, the IdP will return an `invalid_grant` error (to the Refresh grant query).
We would like Gloo to handle this particular error and delete the user session in this case.
Gloo would then fall back with a redirection to the `afterLogoutUrl` for instance.

**Comment by chrisgaun** [comment]
I need to talk to user and get relative priority

**Comment by sam-heilbron** [comment]
OIDC refresh flow if token expired: https://github.com/solo-io/ext-auth-service/blob/master/pkg/config/oidc/oidc_request.go#L455

recent PR around refresh flow: https://github.com/solo-io/ext-auth-service/pull/244 by Ben.

**Comment by kevinnesta** [comment]
Hi Team!
Will this enhancement be also part of 1.8 and 1.9?

We are using 1.8.19 in PROD and are observing that exact issue, leading the end user to 500 Http error loop.

Thanks

**Comment by sam-heilbron** [comment]
Remaining work: Backport and release this to GlooE 1.8 and 1.9

**Comment by sam-heilbron** [comment]
Released with gloo enterprise 1.8.22 and 1.9.4

**Comment by kevinnesta** [comment]
Just tested 1.8.22 and it works as intended!
Thanks for Backporting the fix!
