### ISSUE TITLE
Discrete control and data plane upgrades 

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4929]
**Is your feature request related to a problem? Please describe.**
Ability to perform upgrades to the data plane and control plane separately
Allow data planes to connect to different control plane versions etc.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrisgaun** [comment]
Duplicate of https://github.com/solo-io/gloo/issues/5037

**Comment by kdorosh** [comment]
another way to accomplish this decoupling of lifecycle: https://docs.solo.io/gloo-edge/master/operations/production_deployment/#xds-relay

**Comment by lgadban** [comment]
Not sure where else to add this but for operational control of upgrades it would be useful to be able to install control-plane and data-plane components as separate helm releases.

**Comment by kdorosh** [comment]
Makes sense. In the interim, xds relay can play a similar role as control plane and it has its own helm release
