### ISSUE TITLE
Github issue links in Changelog docs are broken - extra parenthesis at end

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#4939]
**Describe the requested changes**
Github issue links in Changelog docs are broken.  There is an extra parenthesis at the end of each link that causes link traversal to fail.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/reference/changelog/open_source/
Note that the closing parenthesis at the end of each github link is blue (i.e., part of the link itself).
Example: `https://github.com/solo-io/gloo/issues/4556)`

<img width="1188" alt="Screen Shot 2021-06-25 at 3 35 23 PM" src="https://user-images.githubusercontent.com/52334260/123476838-38071e00-d5cb-11eb-88df-a154f992cddc.png">

**Comment by jenshu** [comment]
we probably need to set [excludeTrailingPunctuationFromURLs](https://github.com/showdownjs/showdown/wiki/Showdown-options#excludetrailingpunctuationfromurls) to true in the converter options [here](https://github.com/solo-io/hugo-theme-soloio/blob/master/static/changelog/Renderers.js#L64)

**Comment by artberger** [comment]
Related Hugo theme issue https://github.com/solo-io/hugo-theme-soloio/issues/37 / PR https://github.com/solo-io/hugo-theme-soloio/pull/38/

**Comment by artberger** [comment]
All the docs should be picking up the hugo theme with this change, so closing this issue. Thanks for reporting!
