### ISSUE TITLE
Github Bot to Automatically Put New Issues into Project

### ISSUE THREAD

**Issue by chrisgaun** [solo-io/gloo#4964]
Internally we need a way to add Issues automatically to Github Projects. 

Every new Issue should be added to Gloo Edge Github Project under Triage. There are potentially bots that have already been designed to do this. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sam-heilbron** [comment]
Is there still work to be done here @chrisgaun ? Now that we have the beta project board, this is handled via default workflows.

**Comment by chrisgaun** [comment]
@sam-heilbron still not handled by default unfortunately
