### ISSUE TITLE
1.7.8, 1.7.9, 1.7.10 security releases missing. also docs show each release twice in dropdown

### ISSUE THREAD

**Issue by saiskee** [solo-io/gloo#4974]
**Describe the bug**
1.7.8, 1.7.9, 1.7.10 security releases missing. also docs show each release twice in dropdown on this page:

https://docs.solo.io/gloo-edge/master/reference/security-updates/open_source/

**Comment by kevin-shelaga** [comment]
https://github.com/solo-io/gloo/issues/4944

The scan doesnt go back and scan old versions it seems (https://github.com/solo-io/gloo/actions/runs/1001209443) just the latest
