### ISSUE TITLE
Built-in observability tools should be explicitly discouraged for production

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#4991]
**Describe the requested changes**
The built-in observability tools are good for demos and for non-prod, but they should not be recommended for production. The customers should use their own installation for production. 

subcharts like grafana or prometheus are shown as interface in the helm values documentation, so we found customers with the default values in prod. For example prometheus is installed with 16Gi PVC and 15days of retention. 

**Link to any relevant existing docs**
https://docs.solo.io/gloo-edge/master/guides/observability/
https://docs.solo.io/gloo-edge/master/reference/helm_chart_values/enterprise_helm_chart_values/

**Comment by chrisgaun** [comment]
@jmunozro If you want to submit this doc change.
