### ISSUE TITLE
Concurrent builds are unreliable right now

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#500]
The regression tests manage cluster-wide resources and are prone to fail if there are multiple builds running. We need to either come up with an isolated Kubernetes environment for testing, or use some simple locking in the cluster. 

- Investigated creating new clusters dynamically. This takes 3-3.25 minutes to create, even with a single node. Deleting takes longer, ~6+ minutes. 
- Investigate getting kind working in CI (@yuval-k )
- Implement simple mutex using a resource in the cluster.

**Comment by yuval-k** [comment]
we don't have to wait for deletion :) 
starting a kind cluster also takes a few minutes.. on my laptop its about 8-9 minutes
what tests use cluster resources? knative?
if it's just that the one knative test, maybe locking the cluster just for that test would be enough.

**Comment by yuval-k** [comment]
i believe this is solved by the cluster lock
