### ISSUE TITLE
stop using the Proxy CRD

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5003]
**Is your feature request related to a problem? Please describe.**
The Proxy CRD gathers all the routes used by the Gateways bound to an Envoy proxy.
Its size can be a problem in large deployment contexts (hundreds or thousands of Routes)

**Describe the solution you'd like**
Store this object in memory?

**Comment by chrisgaun** [comment]
This is a decent of work so we would need to talk about this more in Planning.

**Comment by chrisgaun** [comment]
We're not going to completely remove the proxy CRD but we are going rely on objects in memory for the gateway use case when we merge the gloo and gateway pods

**Comment by sam-heilbron** [comment]
Since the merge of the gloo/gateway pods, users no longer need to rely on a Proxy CR being persisted in etcD. You can opt into this behavior with the setting: `persistProxySpec=true`, but if you set it to false, the Proxy will only be stored in memory
