### ISSUE TITLE
Helm template support for rateLimitBeforeAuth

### ISSUE THREAD

**Issue by cmars** [solo-io/gloo#5015]
**Is your feature request related to a problem? Please describe.**
We're using gloo-ee and I want to enable rateLimitBeforeAuth on my API gateway, to protect an external auth service from a denial-of-service attack with invalid requests. The option also doesn't seem to work with ratelimitBasic, so I also need to define rate limit descriptors in the gloo Settings resource.

Gloo supports this, but the Helm templates currently do not.

rateLimitBeforeAuth needs to be set on the `ratelimitServer` extension, but this option does not exist in the current gloo-ee template.

Also, there is a bug in `gloo-ee/charts/gloo/templates/18-settings.yaml` preventing rate limit settings from working because the property is camel-cased `rateLimit` when it should be `ratelimit`. The camel-cased `rateLimit` option crashes gloo with:
```
$ kubectl -n gloo-system logs deployment.apps/gloo
{"level":"info","ts":1626180808.6554165,"logger":"gloo-ee.v1.event_loop","caller":"v1/setup_event_loop.sk.go:57","msg":"event loop started","version":"1.7.9"}
"Tue, 13 Jul 2021 12:53:28 UTC: /workspace/solo-projects/projects/gloo/cmd/main.go:12"  err in main: "starting snapshot watch: initial Settings list: converting output crd: reading crd spec on resource default in namespace gloo-system into v1Settings: unknown field \"rateLimit\" in gloo.solo.io.Settings"
```

**Describe the solution you'd like**
This patch to the gloo-ee templates fixes rate limiting settings error above, and the rateLimitBeforeAuth option:

```
diff -U5 -br gloo-ee/charts/gloo/templates/18-settings.yaml gloo-ee.orig/charts/gloo/templates/18-settings.yaml
--- gloo-ee/charts/gloo/templates/18-settings.yaml      2021-07-12 19:31:15.000000000 -0500
+++ gloo-ee.orig/charts/gloo/templates/18-settings.yaml 2021-06-04 13:45:18.000000000 -0500
@@ -96,11 +96,11 @@
   extensions:
 {{- toYaml .Values.settings.extensions | nindent 4 }}
 {{- end }}

 {{- if .Values.settings.rateLimit }}
-  ratelimit:
+  rateLimit:
 {{- toYaml .Values.settings.rateLimit | nindent 4 }}
 {{- end }}

 {{/* extauth have specified yaml in Enterprise (as opposed to generic yaml insertion for third party configs here) */}}
 {{- if .Values.global.extauthCustomYaml }}
diff -U5 -br gloo-ee/templates/_helpers.tpl gloo-ee.orig/templates/_helpers.tpl
--- gloo-ee/templates/_helpers.tpl      2021-07-12 21:54:37.000000000 -0500
+++ gloo-ee.orig/templates/_helpers.tpl 2021-06-04 13:45:18.000000000 -0500
@@ -251,11 +251,10 @@
   {{- end }}
 {{- end}}
 {{- end}}
 {{- if $.Values.global.extensions.rateLimit.enabled }}
   ratelimitServer:
-    rateLimitBeforeAuth: {{ .Values.global.extensions.rateLimit.beforeAuth | default "false" }}
     ratelimit_server_ref:
       name: rate-limit
       namespace: {{ .Release.Namespace }}
 {{- end }}
 {{- end -}}
```

**Describe alternatives you've considered**
Only alternative I can think of for this would be to post-process Helm output with something like kustomize to patch in the fixes. Hoping we can fix the Helm templates upstream and avoid additional complexity in our deployment.

**Additional context**

**Comment by chrisgaun** [comment]
This should be doable with either Kustomize or with https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/#helm-chart-kuberesourceoverrides

**Comment by cmars** [comment]
@chrisgaun For the `rateLimitBeforeAuth` feature, I can accept that as a workaround, if this is not a feature you want to expose in the Helm chart.

However I do think there is still a capitalization mistake in the gloo-ee template that prevents rate limiting from working as advertised in Helm.

```
diff -U5 -br gloo-ee/charts/gloo/templates/18-settings.yaml gloo-ee.orig/charts/gloo/templates/18-settings.yaml
--- gloo-ee/charts/gloo/templates/18-settings.yaml      2021-07-12 19:31:15.000000000 -0500
+++ gloo-ee.orig/charts/gloo/templates/18-settings.yaml 2021-06-04 13:45:18.000000000 -0500
@@ -96,11 +96,11 @@
   extensions:
 {{- toYaml .Values.settings.extensions | nindent 4 }}
 {{- end }}

 {{- if .Values.settings.rateLimit }}
-  ratelimit:
+  rateLimit:
 {{- toYaml .Values.settings.rateLimit | nindent 4 }}
 {{- end }}

 {{/* extauth have specified yaml in Enterprise (as opposed to generic yaml insertion for third party configs here) */}}
 {{- if .Values.global.extauthCustomYaml }}
```

This seems like an actual defect in the Helm template, the mis-capitalized attribute will just get ignored. Am I missing something here? Should I open a separate issue to track it better?

Also, do you have round-trip tests to ensure that your templates are producing expected results? Seems like such a test would have caught this issue.
