### ISSUE TITLE
I hava Upstream，but use glooctl check tell me I have not get this Upstream

### ISSUE THREAD

**Issue by allenjol** [solo-io/gloo#5023]
snapshot ：
![image](https://user-images.githubusercontent.com/28972707/125754433-b29bdf11-782d-494c-ac51-0ff5d7be0ee9.png)

I want to know what's wrong about that.

**Comment by sam-heilbron** [comment]
Hi @allenjol thanks for reaching out. Generally our [public slack channel](solo-io.slack.com) is the best place to get some help with this question. If you post there, with the relevant configuration (ie Upstream and Settings config), we can work to get to the bottom of it!

**Comment by allenjol** [comment]
I'm sorry for long delay，I go to public slack channel，but it;s not found。and recently，this happens to me all the time. My Gloo version is 1.5.1,can you help me ?
![image](https://user-images.githubusercontent.com/28972707/127142466-502bd3c8-57f2-4366-849b-4fe32512637a.png)
