### ISSUE TITLE
add selectors as an option on UDS

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5025]
Today, UDS is configurable on a per namespace basis (`watchNamespaces`) 
We had a request to control upstream discovery via selectors (labels on k8s services)

**Comment by antonioberben** [comment]
It would be very interesting to have same approach for any resource gloo might handle. Case of UDS but also for EDS.

Scenario: I would like to configure by labels the namespaces which `gloo` can watch on for any kind of resource.

**Comment by sam-heilbron** [comment]
DicoveryPlugin definition: https://github.com/solo-io/gloo/blob/4c22a38a6c10feb0ce7f87b91596f47c62593834/projects/gloo/pkg/discovery/discovery.go#L28

UDS is configured with the following `watchOpts` and `discoveryOpts`: https://github.com/solo-io/gloo/blob/4c22a38a6c10feb0ce7f87b91596f47c62593834/projects/discovery/pkg/uds/syncer/setup_syncer.go#L78

WatchOptions right now are only set to the defaults: https://github.com/solo-io/gloo/blob/4c22a38a6c10feb0ce7f87b91596f47c62593834/projects/discovery/pkg/uds/syncer/setup_syncer.go#L19

WatchOptions already support selectors: https://github.com/solo-io/solo-kit/blob/master/pkg/api/v1/clients/client_interface.go#L122

**Comment by sam-heilbron** [comment]
We are going to pick this up next grooming. Right now we've had a range (S -> L) or sizes.

**Comment by jgrossmac** [comment]
I'd like to request this as well.  Perhaps an annotation on the service itself such that UDS "skips" it.

Something like:
`gloo.solo.io/uds_enabled: false`
