### ISSUE TITLE
Investigate Canary Arch

### ISSUE THREAD

**Issue by chrisgaun** [solo-io/gloo#5037]
# Description
Investigate Canary Architecture (spike)

# Context
We want to enable customers to canary the Gloo installation. 

We started this work here: https://github.com/solo-io/gloo/issues/5018

However, there will likely be other challenges to a canary installation. Notably, we ran into https://github.com/solo-io/gloo/issues/5030. We need to play around with a canary installation and identify the components that are affected.  

Output:
- Documentation outlining what components are affected
- Design docs outlining ways to resolve these affected components
- Guides for installing multiple Gloo installations at once

**Comment by MitchAman** [comment]
Existing guide on installing gloo edge to multiple namespaces that is relevant here: https://docs.solo.io/gloo-edge/latest/installation/advanced_configuration/multiple-gloo-installs/

**Comment by chrisgaun** [comment]
@MitchAman @sam-heilbron we should talk to Lawrence before starting. The primary use case is a user who wants to have multiple versions of a data plane for a single control plane so they can have more control over upgrading Edge by having a mix of old and new data planes.

**Comment by chrisgaun** [comment]
More information here https://github.com/solo-io/gloo/issues/4929

**Comment by kdorosh** [comment]
Affected components:
- [ ] VWH (missing fields on old version)
- [ ] the controllers (missing fields on old version)
