### ISSUE TITLE
Remove dependency on k8s.io/kubernetes

### ISSUE THREAD

**Issue by abursavich** [solo-io/gloo#5041]
**Is your feature request related to a problem? Please describe.**

I'm working on a feature in external-dns and gloo's dependency on `k8s.io/kubernetes` is preventing me from being able to import gloo's API.

**Describe the solution you'd like**

The dependency headaches from importing `k8s.io/kubernetes` are vast and gloo's usage of it is small. It can easily be removed.

**Describe alternatives you've considered**

The current solution in external-dns is to use a dynamic Kubernetes client, re-implement the gloo API internally, and marshal the necessary objects from unstructured data. It's brittle and causing problems with newer versions of the Kubernetes test/mock client.

**Comment by chrisgaun** [comment]
Thanks for this and the PR. Will track on our side as well to make sure eng is helping the PR.

**Comment by pawelaugustyn** [comment]
Merging this PR would be a great improvement while working with this code. Currently, if I want to import `gloo` in my go code, I have to repeat all of the replace clauses related to packages from `k8s.io`.
