### ISSUE TITLE
templatized AuthConfig parameters

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5059]
In a multi-tenant environment, we can have many AuthConfig CRs, like 1 per tenant.
The callback URIs can differ, same for client ID, etc.
It would be nice to have a template system to build these parameters, based on headers. OIDC options are the first target here.

**Comment by marcelsigner** [comment]
Templating is a valid and very flexible option and would solve the issue. However it could result in security concerns.

Another option is to rely on the initial request. In some cases the path of the initial request is the same as the callbackPath. This is for example the case for deeplinks.
Here a generic description:

1. Initial request to a resource
The request is intercepted by Gloo and the user_agent redirected to an OAuth Server. The initial request URL is passed to the OAuth Server as redirect_uri
2. After successful authorization/authentication the OAuth Server redirects the user_agent back to the redirect_uri with code and state.
Gloo has to intercept now again. It uses the callbackPath. If there is no callbackPath configured, Gloo could use the path of the initial request to the resource as callbackPath.
3. After the tokens have been retrieved from the OAuth Server via the token_endpoint, Gloo once again redirects back to the same redirect_uri.
Note: the redirect_uri corresponds to the initial request and its is validated in the OAuth Server.

This option makes the config simpler for several use cases. But it is by far not as powerful as config templates (for example regular expressions as callbackPath).

**Comment by marcelsigner** [comment]
@chrisgaun can we still expect it in Dec on a 1.10 Beta ? As you remember we declared this as most important for CREALOGIX in order to support multi-tenancy.

**Comment by sam-heilbron** [comment]
Remaining work:
- [ ] Release Gloo Edge Enterprise 1.11 with this feature
- [ ] Release Gloo Edge Enterprise 1.10 with this feature
