### ISSUE TITLE
Support glooctl installer on Windows

### ISSUE THREAD

**Issue by Ravenwater** [solo-io/gloo#5062]
**Is your feature request related to a problem? Please describe.**
Trying to use the Gloo Edge proxy on Docker on Windows, but glooctl only supports Linux and Mac.

**Describe the solution you'd like**
I would like to be able to work on Windows desktops and laptops with Gloo Edge

**Describe alternatives you've considered**
Our dev environment is based on Windows, so we need our tools to run on/from Windows environments. Our own software is cross-platform Windows/Linux/Mac. We use Docker on Desktop for Windows and Mac for local K8s dev environments.

**Comment by kevin-shelaga** [comment]
Hi @Ravenwater We do provide windows builds of glooctl (https://github.com/solo-io/gloo/releases/download/v1.8.2/glooctl-windows-amd64.exe)

**Comment by chrisgaun** [comment]
We can potentially have some more documentation on this
