### ISSUE TITLE
Gloo as default ingress controller

### ISSUE THREAD

**Issue by Kami-no** [solo-io/gloo#507]
It would be great to have an option to use Gloo as default Ingress controller for Ingress resources.

I've a cluster where Gloo is the only Ingress controller. It makes sometimes difficult to explain user that they always have to add `kubernetes.io/ingress.class: gloo` for Ingress definitions.

Option to apply non-annotated Ingress definitions would be perfect for cases when Gloo is the only ingress in cluster.

For @christian-posta

**Comment by ilevine** [comment]
see more user feedback here: https://github.com/solo-io/gloo/issues/598#issuecomment-476210582
