### ISSUE TITLE
Requests dropping during load test on gateway-proxy

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#5091]
**Describe the bug**
A customer is testing their Gloo Edge environment. They are performing a cluster roll and replacing all nodes.

They are sending their logs to datadog. 

Their cluster is in AWS: NLB -> Gloo.

During the load test we are consistently seeing the requests drop intermittently. 

**with ALB** (These are the expected results)
![image (1)](https://user-images.githubusercontent.com/1096507/127660971-e79cd1c5-cb07-4fd9-9cb6-3a026829ada5.png)
 
**NLB+Gloo**
![image](https://user-images.githubusercontent.com/1096507/127660826-6bfcff22-5ca5-4a34-a5cd-d3acb78686e8.png)

When reviewing the access logs, we are **not capturing the failed requests**, in fact, we are only aware of them from  reviewing the logs in datadog. 

**Datadog logs**
![image (2)](https://user-images.githubusercontent.com/1096507/127661156-e75d18ad-8f9d-4e63-8c42-9d07fd8ad884.png)

![image (3)](https://user-images.githubusercontent.com/1096507/127661254-1afcf5b8-8bf9-4a9d-a95a-750d90a71d9b.png)

To remedy the dropped requests, we have extending the timeouts on the virtual service to 4x15s perTryTimeout and a timeout of 60s. On the healthCheck, 5s intervals and a 5s timeout with an unhealthyThreashold of 3s. This has made no noticeable difference. 

The stats show a few failures:
```
cluster.helix_load.health_check.failure: 19
cluster.helix_load.health_check.healthy: 10
cluster.helix_load.health_check.network_failure: 19
``` 

The `gateway-proxy` pod has a bazel error:
![image (4)](https://user-images.githubusercontent.com/1096507/127661344-c1926754-1b3e-4208-9b97-60b9995c5da0.png)

** This is a high priority for our client.**

**To Reproduce**
1. kube apply '...'
2. curl '....'
3. See error

**Expected behavior**
Expect to retain the request and if they drop catch the error in the access los

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version `1.8`
- Kubernetes version

**Comment by chrisgaun** [comment]
Sai looked into this for a little bit was not able to get to bottom of it.

**Comment by juli-vert** [comment]
What's the error message you get?
May it be something like: upstream connect error or disconnect/reset before headers...?
