### ISSUE TITLE
Adding SameSite to the available CookieOptions

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#5123]
**Is your feature request related to a problem? Please describe.**
Currently, a complex response transformation is needed to set it

**Describe the solution you'd like**
Adding a `SameSite` option to the options already available (https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#cookieoptions)

**Comment by kdorosh** [comment]
High level steps:
- update our Gloo Api here to support same site: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto#L340-L354
- release Gloo open source so we can have solo-apis (our public api repo mirror) also reflect this change
- update extauth service to honor this new api, [here](https://github.com/solo-io/ext-auth-service/blob/master/pkg/session/session.go#L19-L29)
- update enterprise Gloo to pick up the extauth changes once released (in the go.mod)
