### ISSUE TITLE
Add support for enabling Envoy x-ratelimit reporting headers

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#5141]
**Is your feature request related to a problem? Please describe.**
An Edge Enterprise user wants to enable the Envoy rate-limit reporting option `enable_x_ratelimit_headers` described [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto.html). They is currently now way to enable them in the Edge rate limiting filter.

**Additional context**
Related to #4316

**Comment by kevin-shelaga** [comment]
https://github.com/solo-io/gloo/issues/2785

**Comment by jameshbarton** [comment]
Duplicate of #2785 - Closing this.
