### ISSUE TITLE
EKS Pricing

### ISSUE THREAD

**Issue by chrisgaun** [solo-io/gloo#5150]
Add the following links to this docs page https://docs.solo.io/gloo-edge/latest/installation/platform_configuration/cluster_setup/#amazon-elastic-container-service-for-kubernetes-eks
Add the EKS Pricing link https://aws.amazon.com/eks/pricing/ 
Add the EKS IAM Management doc https://docs.aws.amazon.com/eks/latest/userguide/security-iam.html

**Comment by sam-heilbron** [comment]
Resolved by: https://github.com/solo-io/gloo/pull/5159
