### ISSUE TITLE
snake_case is still in documentation instead of camelCase

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5151]
**Describe the requested changes**
After version 1.8.0+, snake_case won't work anymore

**Link to any relevant existing docs**
1. opa_auth in https://docs.solo.io/gloo-edge/master/guides/security/auth/extauth/opa/
2. opa_auth in https://docs.solo.io/gloo-edge/master/guides/security/rate_limiting/envoy/
3. lb_endpoints in several places

**Comment by artberger** [comment]
I updated the Edge docs in this PR: https://github.com/solo-io/gloo/pull/5198

Let me know if this resolves the issue. Thanks!
