### ISSUE TITLE
Link to Edge metrics context is broken in observability docs

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#5171]
**Describe the requested changes**
The "Help strings" link to see what metrics Gloo Edge publishes is broken [here](https://docs.solo.io/gloo-edge/latest/guides/observability/prometheus/metrics).

This is the broken link target:
https://docs.solo.io/gloo-edge/latest/guides/observability/prometheus/metrics/#metrics-context

**Comment by artberger** [comment]
Thanks for raising this issue. The link should be fixed now: https://docs.solo.io/gloo-edge/master/guides/observability/prometheus/metrics/#metrics-context
