### ISSUE TITLE
Envoy Listeners Do Not Restart with Incorrect Configuration

### ISSUE THREAD

**Issue by chrisgaun** [solo-io/gloo#5189]
**Is your feature request related to a problem? Please describe.**
Currently Envoy listners do not restart when there is an incorrect configuration 

Replicate:

deploy invalid route , with incorrect destination
restart control plane
restart envoy pods

**Describe the solution you'd like**
When  restart control plane pods the older config is should recreate the config in control plane in cache

**Comment by sam-heilbron** [comment]
This will be resolved by: https://github.com/solo-io/gloo/issues/4839

**Comment by chrisgaun** [comment]
@sam-heilbron closing this dupe. LMK if error
