### ISSUE TITLE
AuthN, Z for Gloo on VMs

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#519]

**Comment by yuval-k** [comment]
depends on #557

**Comment by ilevine** [comment]
this is to replace the current reliance on kubernetes RBAC.
when we support VMs gloo will have a gRPC interface; we need to be able to plug an RBAC model in there.

**Comment by rickducott** [comment]
Closing as stale / not specific. We do have plans around identity and user RBAC for Gloo, but tracked elsewhere.
