### ISSUE TITLE
`oneof` docs do not show all possible fields in descriptions

### ISSUE THREAD

**Issue by saiskee** [solo-io/gloo#5193]
**Describe the bug**
In fields where there are more than two possible values in a `oneof`, some values are left out.
For example, under `upstream.proto`, the `upstreamType` comment is 
"Only one of kube, static, pipe, aws, azure, or awsEc2 can be set."

When it should be 
"Only one of kube, static, pipe, aws, azure, consul, or aws_ec2 can be set"

**Comment by sam-heilbron** [comment]
This has been merged into gloo 1.9.x and 1.8.x
