### ISSUE TITLE
Error encountered on create/update with enum values

### ISSUE THREAD

**Issue by ianrudie-tmus** [solo-io/gloo#5200]
When using `"github.com/solo-io/solo-apis/pkg/api/gateway.solo.io/v1"` to perform create/updates from a golang program we encounter errors with OpenAPI V3 Schema validation by k8s admissions on enumerated fields. One example is `spec.sslConfig.parameters.minimumProtocolVersion` shown below but fields like `spec.virtualHost.options.stagedTransformations.early.requestTransforms.requestTransformation.transformationTemplate.parseBodyBehavior` also exhibit the same behavior.

```text
spec.sslConfig.parameters.minimumProtocolVersion: Invalid value: \"integer\": spec.sslConfig.parameters.minimumProtocolVersion in body must be of type string: \"integer\", spec.sslConfig.parameters.minimumProtocolVersion: Unsupported value: 3: supported values: \"TLS_AUTO\", \"TLSv1_0\", \"TLSv1_1\", \"TLSv1_2\", \"TLSv1_3\"], could not create virtual service
```

I believe this is related to JSON marshalling/unmarshalling into the protobuf enumerations. Sometimes instead of the correct string value you end up getting the index of that string in the enum. This has happened for quite some time but had not been a disruptive issue since the index integer value could be successfully unmarshalled by the gloo controllers and the correct string would be provided in the envoy configuration.

version details:
```text
github.com/solo-io/go-utils v0.16.6
github.com/solo-io/solo-apis v0.0.0-20210104203558-daaaf507aaf9
```

At this point I'm uncertain if this is just a library version issue or an actual unresolved bug so assistance would be appreciated looking into possible resolutions.

**Comment by chrisgaun** [comment]
currently using 1.8.4

**Comment by ianrudie-tmus** [comment]
Not sure if it matters but it's gloo-ee v1.8.4 which I believe builds on top of oss gloo v1.8.6
