### ISSUE TITLE
Add unit tests to glooctl to match tests in Homebrew Formula

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#523]
glooctl HomeBrew formula performs 3 unit tests on glooctl to ensure it build it correctly from source

* checks that first help line contains `glooctl is the unified CLI for Gloo.`
* checks that `--version` tags matches pattern `glooctl community edition version <version number>`
* checks that attempting to run `glooctl get proxy` will fail (no k8s cluster) with error containing string `failed to create proxy client`

Ruby snippet from Homebrew Formula showing tests follows. Full formula https://github.com/Homebrew/homebrew-core/blob/master/Formula/glooctl.rb.

```ruby
test do
    run_output = shell_output("#{bin}/glooctl 2>&1")
    assert_match "glooctl is the unified CLI for Gloo.", run_output

    version_output = shell_output("#{bin}/glooctl --version 2>&1")
    assert_match "glooctl community edition version #{version}", version_output

    # Should error out as it needs access to a Kubernetes cluster to operate correctly
    status_output = shell_output("#{bin}/glooctl get proxy 2>&1", 1)
    assert_match "failed to create proxy client", status_output
end
```

**Comment by rickducott** [comment]
Adding the regression label since this was linked to a regression caused by changing the version text

**Comment by rickducott** [comment]
Closing as stale - we can open issues to track specific items.
