### ISSUE TITLE
Tracing headers are not sent to the custom grpc passthrough extauth server

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#5234]
**Describe the bug**
Tracing headers are not sent to the custom grpc passthrough extauth server.
They are only sent in the grpc message itself under http request headers field.

**Comment by kdorosh** [comment]
We want to add support for allowed headers to pass through to the downstream passthrough extauth grpc service, akin to what we already support for http extauth passthrough: https://github.com/solo-io/ext-auth-service/blob/62a80dcc172ce592a2a91747a6357ab5db259e41/pkg/config/passthrough/http/http_auth_service.go#L250

The grpc implementation largely passes through the grpc request with the same headers on the grpc _message_ itself, which is sent over http/2: https://github.com/solo-io/ext-auth-service/blob/9fdda2ce3359470ee787c4d3ee76f0e0e4ea51c0/pkg/config/passthrough/grpc/grpc_request_adapter.go#L56

The fix here should ensure that the http headers on the containing connection can also be propagated in a way that tracing can pick up. This is assuming grpc doesn't act in a stream here, which I believe extauth does not (worth confirming)

**Comment by sam-heilbron** [comment]
Ideas for this:
Implement echo passthrough auth service. This way we can verify headers that are passed to the custom server.
We might not even need to install gloo, and we don't need to actually verify tracing as part of this work.

**Comment by bewebi** [comment]
Been working on replicating the behavior and gaining visibility into how and where headers are propagated.
That said, I'm not entirely clear on what the exit criteria are for this issue. @djannot, is it a matter of the headers needing to be present elsewhere in the gRPC message? or present on the underlying HTTP request to the passthrough server? or on the HTTP response from the gateway?
@kdorosh if you have insight that would be helpful as well

**Comment by kdorosh** [comment]
> is it a matter of the headers needing to be present elsewhere in the gRPC message? or **present on the underlying HTTP request to the passthrough server?** or on the HTTP response from the gateway?

we need to headers present on the http/2 request that the grpc message is sent across, so that tracing can pick up the required headers

**Comment by bewebi** [comment]
Glooe [1.9.0-beta8](https://github.com/solo-io/solo-projects/releases/tag/v1.9.0-beta8) contains a fix that we believe will resolve the issue
The customer should try out the fix and report back

**Comment by bewebi** [comment]
Customer confirmed the fix works for them
