### ISSUE TITLE
Update envoy-gloo to 1.19.1 rather than 1.19.0

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#5237]
We updated our envoy builds to include the CVE fixes, but on top of 1.19.0 rather than 1.19.1 due to some breaking changes in envoy made in the 1.19.1 release.

We will eventually need to sort these out and update to the latest version.

The utility that breaks: https://github.com/solo-io/envoy-gloo/blob/master/source/extensions/filters/http/transformation/transformation_filter.cc#L164-L166

We can't use the envoy version of said function, as it has breaking behavior and fails our unit tests.

We also need to fix our implementation, since it depends on code that has been since removed from envoy in https://github.com/envoyproxy/envoy/pull/17602

**Comment by npolshakova** [comment]
The latest envoy-gloo has the fix here that Yuval made: https://github.com/solo-io/envoy-gloo/blob/master/source/extensions/filters/http/transformation/transformation_filter.cc#L164-L166 Will need to backport  to 1.19
