### ISSUE TITLE
Improve clarity on internal documentation for CVE releases

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#5239]
**Describe the requested changes**
We could improve the docs for engineers running through the CVE guide for the first time, as they assume a fair bit of implicit knowledge about the moving components.

- [ ] Include fixes that indicate candidate releases vs patch releases
- [ ] perhaps follow template that indicates before each step what the resulting assets (private) should be, and why

**Additional context**

**Comment by bewebi** [comment]
[All set](https://soloio.slab.com/posts/envoy-cve-prep-and-release-guide-7dan53fc)!
