### ISSUE TITLE
Add Ability for Passthrough Auth Configurations to Fail "Open"

### ISSUE THREAD

**Issue by jameyhammock** [solo-io/gloo#5255]
**Is your feature request related to a problem? Please describe.**
We are using a passthrough auth configuration to tie in validation against our own WAF.  We want this to fail "open" if the call to the WAF service times out or errors.

**Describe the solution you'd like**
We would like to be able to specify that this specific passthrough auth should not error if the call times out.  Something similar to the ext auth failureModeAllow setting, but scoped to a specific passthrough auth configuration.

**Describe alternatives you've considered**
We looked at the global extauth failureModeAllow setting, but it affects all of our extauth configs, not just the particular one we want to function this way.

**Comment by nfuden** [comment]
Should this be a fail open or fail open on some set of responses, statuses or timeout. I think we should consider if a timeout versus a 500 coming back from the passthrough should be handled

**Comment by sam-heilbron** [comment]
Remaining work for this:
- [ ] Tests to validate that when multiple stages are defined (passthrough and opa for example), a failed connection to the passthrough server still executes the other stages (and doesn't just auto accept)
- [ ] Tests to validate that response set-cookie headers are set properly (https://github.com/solo-io/ext-auth-service/pull/419)
- [ ] Documentation around the failure mode feature, as well as some way for users to triage issues (what metrics, logs or other tooling can be used to diagnose failures)

**Comment by inFocus7** [comment]
Released in **Gloo EE `v1.12.29`**
