### ISSUE TITLE
Remove TODO and document default namespaces for watched and discovered services in settings.proto.

### ISSUE THREAD

**Issue by rettori** [solo-io/gloo#526]

**Comment by rickducott** [comment]
Also remove TODOs here: 

http://localhost:1313/v1/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk/#redirectaction

http://localhost:1313/v1/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk/#directresponseaction

File issues if TODO work should be done still.
