### ISSUE TITLE
compressedProxySpec create an empty proxy object impacting envoy (no config) in 1.8.x

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5287]
Steps to reproduce: 
 - install 1.8.x 
 - create vs + us to demo 
 - check that proxy is created correctly
 - set compressedProxySpec = true in settings 
 - proxy is now empty 
 
Desired behavior: 
 - A proxy is created with compressed data

**Comment by kdorosh** [comment]
perhaps related to new schema validation work

**Comment by asayah** [comment]
https://github.com/solo-io/gloo/pull/5290
