### ISSUE TITLE
ExtAuth metrics for passthrough_check_response are showing only errors

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5296]
**Describe the bug**
Metrics extauth_solo_io_passthrough_check_response and extauth_solo_io_passthrough_check_error and both linked to the same source, so they always show identical values.

**To Reproduce**
1. passthrough auth with GRPC protocol.
2. generate traffic
3. Check metrics

![image (8)](https://user-images.githubusercontent.com/35881711/132191804-f837ae0c-172f-4c48-8d3d-e7b30f4683bb.png)

**Comment by pmichna** [comment]
@jmunozro How should I understand closing this issue? Is the problem fixed?

**Comment by jmunozro** [comment]
Yes, and it will be included in the next release
