### ISSUE TITLE
Allow configuration of jwt option at the route level

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#5305]
**Is your feature request related to a problem? Please describe.**
Currently, it can only be set in the global options of a virtual service.
A user can disable jwt at the route level, but can't set different configurations for different routes.

**Describe the solution you'd like**
Allow a use to define a jwt configuration at the route level

**Comment by chrisgaun** [comment]
@barmaiost1 I put it in the v1.11 time frame for now. That will be Q1 of 2022

**Comment by chrisgaun** [comment]
Update. Still in 1.11 timeline

**Comment by antonioberben** [comment]
@chrisgaun , another user has requested this feature

**Comment by DuncanDoyle** [comment]
Dupe of https://github.com/solo-io/solo-projects/issues/6541, which has been fixed.
