### ISSUE TITLE
Docs for namedExtauth setting

### ISSUE THREAD

**Issue by artberger** [solo-io/gloo#5316]
**Describe the requested changes**
just discovered this option Settings > namedExtauth do we have doc (plans) on that?
> Kevin Shelaga  8 minutes ago. Curious about this too. I always expected the delay to be equal to the amount of time a new virtual service takes to be recognized, for example.

**Link to any relevant existing docs**
* Proto API generated doc: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk/
* namedExtAuth example: https://github.com/solo-io/scripts/blob/main/customers/vonage/20211115094652-custom-authz-rt-override/run.sh#L65

**Additional context**
Background issue: is there any delay when a TLS secret is updated and referenced in an Upstream CR?

**Comment by bcollard** [comment]
a few notes from Sam, through Antonio:

1- defined a namedExtauth map in settings (https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk/#settings)
2- on a route, where you would normally have a customAuth extauthextension (https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#extauthextension), Include the name field, which needs to map the key in the settings you defined in step 1

**Comment by bcollard** [comment]
done in https://docs.solo.io/gloo-edge/master/guides/security/auth/multi_authz/
