### ISSUE TITLE
1.9 beta releases have image pull errors

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#5318]
**Describe the bug**
In the latest gloo-ee releases, a bunch of pods (extauth, gateway-proxy, gloo, gloo-fed-console, observability) are erroring with ImagePullBackOff.  Example error message from gateway-proxy: `Back-off pulling image "quay.io/solo-io/gloo-ee-envoy-wrapper:1.9.0-beta7"`

**To Reproduce**
```
helm repo add gloo-ee https://storage.googleapis.com/gloo-ee-helm
helm repo update
helm install -n gloo-system gloo-ee gloo-ee/gloo-ee --create-namespace --set-string license_key=$GLOO_LICENSE_KEY --set gloo-fed.enabled=false --devel
```

**Comment by sam-heilbron** [comment]
This starts occuring with gloo-ee 1.9.0-beta5 (when FIPS was introduced)
