### ISSUE TITLE
Disabling gloo-fed in Helm values should disable gloo-fed-apiserver

### ISSUE THREAD

**Issue by tmojlupo** [solo-io/gloo#5327]
**Describe the bug**
When deploying 1.8.10 of the gloo-ee chart, we've got the gloo-fed.enabled: false entry set in our values file which should disable the gloo-fed subchart entirely.  Instead, it still allows the gloo-fed apiserver to be installed.

**To Reproduce**
1. Create a values-nofed.yaml file with the entry.
```
gloo-fed:
  enabled: false
```
2. Create render the template to see what is created with the command.
    `helm template glooe/gloo-ee -f values-nofed.yaml`
3. Review the output.  It will include the gloo-fed-apiserver deployment.
4. Create a values-nofedapi.yaml with these contents:
```
gloo-fed:
  enabled: false
  glooFedApiserver:
    enable: false
```
5. Render the templates with the command: `helm template glooe/gloo-ee -f values-nofedapi.yaml`
6. You'll find this disables the gloo-fed deployment as well as the gloo-fed apiserver.

**Expected behavior**
Disabling gloo-fed should cover the entire gloo-fed helm chart so we don't have to keep searching and destroying.

And while you are at it, if there is a separate field to disable the glooFedApiserver, shouldn't it be "enabled" rather than "enable" for consistency?

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge helm chart for gloo-ee 1.8.10.

**Comment by kevin-shelaga** [comment]
Looks like this change was intentional to allow installing the gloo-fed ui without gloo-fed

https://github.com/solo-io/solo-projects/commit/acfe38e6d3ba54db5523aed18bbc68eb1b10bac4

**Comment by jenshu** [comment]
Yep, this was a temporary workaround to allow installing the UI without gloo-fed.  Currently the way to disable the apiserver is to set `glooFedApiserver.enable` to false as you have in your steps. 

We plan to do some further helm cleanup to move the apiserver out of the Gloo Fed chart and make the helm flags and deployment names more clear.

Also, agree with the `enable`/`enabled` inconsistency :)

**Comment by tmojlupo** [comment]
Thank you.  I will close this issue.
