### ISSUE TITLE
Rename Settings CRD to Gloo to match Kubernetes Operator convention

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#534]
Gloo already includes Controllers following the Red Hat / CoreOS Operator pattern convention. We should consider renaming `Settings` CRD to `Gloo` to follow convention used by other operators.

We should also consider adding a `version` field to the spec, and include the ability to upgrade Gloo just by changing version spec.

examples:
* https://github.com/coreos/prometheus-operator
* https://www.operatorhub.io/operator/redis-enterprise-operator.v0.0.1

**Comment by yuval-k** [comment]
Another option is to use a ConfigMap instead of a CRD

**Comment by rickducott** [comment]
We don't have this on the roadmap. Going to close as stale, can reopen if priorities change.
