### ISSUE TITLE
Kubernetes validation webhook to reject deletion of Secrets and ConfigMaps used by Gloo Edge

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#5366]
**Is your feature request related to a problem? Please describe.**
Deletion of these Kubernetes objects will prevent Gloo Edge to create valid snapshots until they are recreated.

**Describe the solution you'd like**
A validation webhook could intercept all the deletion requests for ConfigMaps and Secrets and reject them if they are used by Gloo Edge.

**Comment by MitchAman** [comment]
https://github.com/solo-io/gloo/pull/5470 only implements delete validation for secrets. See the parent issue (https://github.com/solo-io/gloo/issues/2797#issuecomment-947642937) for state of ConfigMap work.
