### ISSUE TITLE
gloo helm chart does not create rate limit descriptors when configured to

### ISSUE THREAD

**Issue by cmars** [solo-io/gloo#5377]
**Describe the bug**
When defining a rate limit descriptor for the gloo helm chart, the Helm templates mis-capitalize the rate limit section, resulting in the option being silently dropped.

**To Reproduce**

Define a rate limit descriptor for gloo in `values.yaml`:

```
  gloo:
...
    settings:
...
      rateLimit:
        descriptors:
          - key: auth
            rateLimit:
              requestsPerUnit: 180
              unit: MINUTE
```

**Expected behavior**
Rate limit descriptor **should have been defined** in Settings and reference-able from rate limit options in virtual services, route tables, etc.

**Actual behavior**
Rate limit descriptor **is not defined** in Settings and as a result, rate limiting does not actually work when configured with gloo Helm charts at all.

**Fix**
It's caused by a mis-capitalization in `templates/18-settings.yaml`, which can be fixed by applying this patch:

```
diff -U5 -br gloo-ee/charts/gloo/templates/18-settings.yaml gloo-ee.orig/charts/gloo/templates/18-settings.yaml
--- gloo-ee/charts/gloo/templates/18-settings.yaml      2021-07-12 19:31:15.000000000 -0500
+++ gloo-ee.orig/charts/gloo/templates/18-settings.yaml 2021-06-04 13:45:18.000000000 -0500
@@ -96,11 +96,11 @@
   extensions:
 {{- toYaml .Values.settings.extensions | nindent 4 }}
 {{- end }}

 {{- if .Values.settings.rateLimit }}
-  ratelimit:
+  rateLimit:
 {{- toYaml .Values.settings.rateLimit | nindent 4 }}
 {{- end }}
```

**Additional context**
- Gloo Edge version: 1.7.17, 1.8.13
- Originally raised in #5015, but as this issue was combined there with another, it may have been lost in communication. It is still a problem in 1.8.13 (as we're in the process of evaluating for an upgrade).

**Concerns**
Given that YAML is so forgiving (too forgiving) of mistakes such as the one discovered above, what kind of validation can be done in these Helm charts (or the Gloo product) to ensure that values are actually being expressed correctly and accepted by the CRDs they configure? Running without rate limits when they were configured puts a service in a potentially vulnerable situation, if those limits were intended to protect from abuse. Is there some kind of schema linting check that can be done to know a Helm chart's configuration is correct?

**Comment by sam-heilbron** [comment]
This should be resolved by the most recent releases: 
Gloo OSS 1.10.14, 1.11.0-beta18
Gloo EE 1.10.12, 1.11.0-beta13

In addition, we added some more rigorous e2e testing to help prevent bugs like this

**Comment by cmars** [comment]
CC @genslein @todai88
