### ISSUE TITLE
Expose extensions.request_id.uuid.v3.UuidRequestIdConfig

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#5405]
**Is your feature request related to a problem? Please describe.**
Customer would like to use UuidRequestIdConfig in the hcm.proto

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/request_id/uuid/v3/uuid.proto#envoy-v3-api-msg-extensions-request-id-uuid-v3-uuidrequestidconfig

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by inFocus7** [comment]
Hey Kevin! Quick update:

I currently have a draft PR set up with some changes to expose `UuidRequestIdConfig` in `hcm.proto`. 

Looking at Envoy's HCM filter docs, I saw that the [request_id_extension](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-request-id-extension) in hcm defaults to the UuidRequestIdConfig config. So my approach is to expose `UuidRequestIdConfig`, and then use that config in the `request_id_extension` field. 

Wondering if you have any objections, or if all sounds good! I'm still trying to test this out locally before getting it reviewed & merged.

**Comment by kevin-shelaga** [comment]
@inFocus7 That sounds good to me!
