### ISSUE TITLE
Support the envoy.retry_priorities.previous_priorities priority predicate

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#5427]
**Is your feature request related to a problem? Please describe.**
A customer wants retries to be performed on a remote service on failure.
Today, the only option to do that is by using outlierDetections, but it redirect all the traffic to the remote service for a period of time and it's not acceptable.

**Describe the solution you'd like**
The `envoy.retry_priorities.previous_priorities` priority predicate does the following (see https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#arch-overview-http-retry-plugins)
```
This will keep track of previously attempted priorities, and adjust the priority load such that other priorities will be targeted in subsequent retry attempts.
```

**Comment by chrisgaun** [comment]
Related to https://github.com/solo-io/gloo/issues/5361
