### ISSUE TITLE
expose more Envoy HCM properties

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5437]
## Part 1

Expose HCM [codec_type](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager)

## Part 2

We already have `connectionConfig` on the Upstream object
https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk/

We don't have it exposed on the downstream side.
Expected options are listed here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-httpprotocoloptions

Particularly under `common_http_protocol_options` :
- [max_requests_per_connection](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto.html?highlight=max_requests_per_connection#config-core-v3-httpprotocoloptions) 
- [max_headers_count](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-httpprotocoloptions)

**Comment by nfuden** [comment]
Unfortunately for the final part max_requests_per_connection we will either have to make some larger changes, commit to some breaking changes, or fork a repo.
Best but slowest path forward captured here: https://github.com/solo-io/gloo/issues/5520

**Comment by bcollard** [comment]
follow-up issue: https://github.com/solo-io/gloo/issues/5762
