### ISSUE TITLE
CRD compression not working when upgrading from 1.8.0 to 1.8.14

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#5440]
**Describe the bug**
When I deploy a fresh Gloo Edge Enterprise 1.8.14 and enable CRD compression, it works well.
But when I deploy Gloo Edge Enterprise 1.8.0, upgrade to 1.8.14 and enable CRD compression, it doesn't work:

```
apiVersion: gloo.solo.io/v1
kind: Proxy
metadata:
  annotations:
    gloo.solo.io/compress: "true"
  creationTimestamp: "2021-10-06T12:14:03Z"
  generation: 4
  labels:
    created_by: gateway
  name: gateway-proxy
  namespace: gloo-system
  resourceVersion: "16184"
  selfLink: /apis/gloo.solo.io/v1/namespaces/gloo-system/proxies/gateway-proxy
  uid: ffcb8d3d-dc49-4aea-be39-aca299d2ddcd
spec: {}
status:
  reportedBy: gloo
  state: 1
```

**To Reproduce**
Install Gloo Edge Enterprise 1.8.0
Upgrade to 1.8.14
Enable CRD compression
Delete the existing proxy object

**Comment by djannot** [comment]
The issue is on the doc side in fact.

The doc in 1.8 (https://docs.solo.io/gloo-edge/1.8.18/operations/upgrading/1.8.0/) is telling the user to run the following commands:

```
helm pull gloo/gloo --version 1.8.8 --untar
kubectl apply -f gloo/crds/gloo.solo.io_v1_Settings.yaml
```

While the doc in 1.9 (https://docs.solo.io/gloo-edge/latest/operations/upgrading/1.8.0/):

```
helm pull gloo/gloo --version $GLOO_VERSION --untar
kubectl apply -f gloo/crds
```

So we simply need to update the 1.8 version of the doc.

**Comment by artberger** [comment]
This is updated in the [doc](https://docs.solo.io/gloo-edge/1.8.19/operations/upgrading/1.8.0/#crd-field-updates) now.
