### ISSUE TITLE
Expose regex_rewrite in RedirectAction

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#5448]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way in Gloo Edge to perform similar than what the `regex_rewrite` option provide.

**Describe the solution you'd like**
Expose the `regex_rewrite` (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-redirectaction) option in Gloo Edge `RedirectAction` (https://docs.solo.io/gloo-edge/master/reference/api/envoy/api/v2/route/route.proto.sk/#redirectaction)

**Comment by nfuden** [comment]
Whats the difference of this and  functionality seen here https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/regex_rewrite/

It may be in a better location for setting but it sure seems like this covers it?

**Comment by mkazin** [comment]
/kick
Timeout in test:
`Step #10 - "test": Gateway in memory hybrid gateway http traffic ssl [It] should work with ssl if ssl config is present in matcher
Step #10 - "test": /workspace/gloo/test/e2e/gateway_test.go:1059`
