### ISSUE TITLE
glooctl secret fixes and improvements

### ISSUE THREAD

**Issue by yuval-k** [solo-io/gloo#546]
RootCA is optional as it is only used when client cert is required. The cli requires it regardless

**Comment by rickducott** [comment]
Other improvements:
- Add validation that the arguments are in the right order, and the key and cert match.

**Comment by mitchdraft** [comment]
notes:

require root_ca when verify_subject_alt_name is included in `SslConfig` or `UpstreamSslConfig`

`github.com/solo-io/gloo/projects/gloo/api/v1/ssl.proto`
```proto
    // Verify that the Subject Alternative Name in the peer certificate is one of the specified values.
    // note that a root_ca must be provided if this option is used.
    repeated string verify_subject_alt_name = 5;
```
