### ISSUE TITLE
Expose overload_manager envoy config

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5482]
**Is your feature request related to a problem? Please describe.**
As stated [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#best-practices-edge) it would be convenient to expose [overload manager: Global downstream connection limits](https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager#config-overload-manager) setting.

**Describe the solution you'd like**
I'd like the overload_manager to be exposed in Settings and also available in Helm.

**Describe alternatives you've considered**

**Additional context**
This field should be configured in the presence of untrusted upstream/downstreams, to protect the envoy instances. We should even consider setting a default config for it.

**Comment by nfuden** [comment]
Question: Is this issue to expose overload manager in general? Namely to allow for configuration of things like the fixed_heap levels to stop accepting keep alives? Or is this in particular to manage the downstream limits?

The ability to set global downstream connections via helm is already supported via https://github.com/solo-io/gloo/blob/3e68cf23095811a71a70bbbbd4d1b2fc18df23b4/docs/content/reference/values.txt#L570

**Comment by jmunozro** [comment]
Hi,
the issue is to expose the overload manager, and the underlying goal is to follow the best practices [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#best-practices-edge)

If we can somehow provide a good set of production values for those settings, then we don't even need to expose the settings.

**Comment by nfuden** [comment]
If this is purely on non-custom gateways we set a default. We could extend that default to custom gateways as well if that is sufficient?

The linked best practices for running as an edge proxy have quite a few things outside of the overload manager. 
Just trying to understand the request set here.

**Comment by nfuden** [comment]
Closing per out of github chat due to a default existing on non-custom gateways!
