### ISSUE TITLE
Build flake: Data race

### ISSUE THREAD

**Issue by bewebi** [solo-io/gloo#5490]
Observed a Data Race failure on three builds for #5488 before the fourth passed. The failures occurred in a different test suite each time

- In the [e2e suite](https://console.cloud.google.com/cloud-build/builds;region=global/ee640bb5-1c16-40a1-911d-5228ed3653eb;step=10?authuser=1&project=solo-public)
- In the [setup suite](https://console.cloud.google.com/cloud-build/builds;region=global/143d05d1-e1b7-4912-ba2b-effd7e032eda;step=10?authuser=1&project=solo-public)
- In the [validation suite](https://console.cloud.google.com/cloud-build/builds;region=global/eb1585d0-8fe5-4203-8d24-023353634444;step=10?authuser=1&project=solo-public)

**Comment by ben-taussig-solo** [comment]
Experienced the data race failure in the validation suite a couple of times today

**Comment by sam-heilbron** [comment]
The associated issue has the PRs linked to it which resolved this bug. This has been merged into 1.12 -> 1.9.
