### ISSUE TITLE
documentation regarding how canary deployment behaves with different API version of the resources 

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#5499]
From 1.9.0 we can have canary deployments.

It would be interesting to document how API versioning could be affected by canary deployment.

When performing a canary deployment, you will have a minimum of one pair of each component:
- 2 gloo deployments
- 2 gateway deployment
- 2 proxy resource
- 2 gateway proxy

But only one custom resources (i.e. VirtualService, RT, AuthConfig, ...) as you had it before running the deployment.

What would happen if the new release brings a change in the CRDs? How do the canary deployments (old version and new version) behave? can there be a possible conflict?

thank you

![image](https://user-images.githubusercontent.com/5262332/138744920-ef6ba34e-a240-4c3f-b768-59cde1377c74.png)

**Comment by Rachael-Graham** [comment]
Working on this in https://github.com/solo-io/gloo/issues/5499
