### ISSUE TITLE
Using an existing Ingress

### ISSUE THREAD

**Issue by apobbati** [solo-io/gloo#55]
Is it possible to use an existing Ingress that's deployed? I have an nginx-ingress already wired up to a loadbalancer on my K8s cluster.

**Comment by ilackarms** [comment]
gloo is designed to use [Envoy](https://github.com/envoyproxy/envoy) as its proxy. You can run both gloo and nginx-ingress side by side. nginx reads [kubernetes ingress objects](https://kubernetes.io/docs/concepts/services-networking/ingress/) to get its configuration.
Gloo reads [virtualhost](https://gloo.solo.io/v1/virtualhost/) and [upstream](https://gloo.solo.io/v1/upstream/) objects for its config. 

*Note that Gloo also supports using kubernetes ingress objects to get its config (this happens through the `kube-ingress-controller` pod that you'll see running if you run `kubectl get pods -n gloo-system`).*

However, as I said you can run NGINX and Gloo side-by-side without issue. Simply send requests to the ip of the loadbalancer created for Gloo to go through Gloo. check the external ip of he load balancer with `kubectl get svc -n gloo-system` to know which ip to talk to.

**Comment by yuval-k** [comment]
@apobbati any particular reason for using nginx? 
reason for asking is to understand if a smooth transition path would work for you? or if you are relying on nginx specific features?

**Comment by ilackarms** [comment]
closing this issue @apobbati feel free to reopen if you want to continue this discussion
