### ISSUE TITLE
Support request without query formatter extension 

### ISSUE THREAD

**Issue by ShimiT** [solo-io/gloo#5503]
**Is your feature request related to a problem? Please describe.**
We need to use the access logs to send request "path" data. 
Using the fields `%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%' will print the query data if it exists, including some sensitive/personal data that we cannot send to the access log.

**Describe the solution you'd like**
Support `ReqWithoutQuery` formatter extension.
See: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/req_without_query/v3/req_without_query.proto

Checked with  version v1.9.0  and
Client: {"version":"1.10.0-beta2"}
`Server: {"type":"Gateway","kubernetes":{"containers":[{"Tag":"1.10.0-beta2","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.10.0-beta2","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.10.0-beta2","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.10.0-beta2","Name":"gloo","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}`

**Comment by kdorosh** [comment]
https://docs.solo.io/gloo-edge/latest/guides/security/data_loss_prevention/#dlp-for-access-logs

**Comment by gunnar-solo** [comment]
@ShimiT, can you confirm if this existing [dlp-for-access-logs](https://docs.solo.io/gloo-edge/latest/guides/security/data_loss_prevention/#dlp-for-access-logs) method is sufficient for the above use case?  It looks like, on the face of it, that the customer wants to have _some_ but not _all_ of a specific header scrubbed from access logs

**Comment by ShimiT** [comment]
@gunnar-solo  - We are already using it as a quick workaround. 
It seems that it's not sufficient as the data needs to be processed by the upstream services, which requires additional processes on the backend side.

**Comment by gunnar-solo** [comment]
> data needs to be processed by the upstream services

IIUC, you've got the setting `options.dlp.enabledFor` currently configured to scrub PII from both access logs _and_ queries. 
 If this _is_ the case...

can you attempt adjusting this field in your VirtualService(s)?
```
spec.options.dlp.enabledFor: "RESPONSE_BODY"    # default setting.  Scrubs data from _only_ responses
spec.options.dlp.enabledFor: "ACCESS_LOGS"      # what I'm suggesting:  scrubs data from _only_ access logs
spec.options.dlp.enabledFor: "ALL"              # what I _think_ you currently have.  Scrubs from _both_ access logs _and_ responses.
```

looking to get you quickly unstuck, if possible

**Comment by ShimiT** [comment]
We have a workaround for now, so it isn't a blocker. 
As Envoy is already supporting it, Is it possible to add `%REQ_WITHOUT_QUERY(X?Y):Z%` to the upstream?

**Comment by gunnar-solo** [comment]
Heads up!  This is currently blocked by a [breaking upgrade](https://github.com/solo-io/gloo/issues/5520)
