### ISSUE TITLE
Kubernetes 1.22 has dropped support for extensions/v1beta1 APIs

### ISSUE THREAD

**Issue by pseudonator** [solo-io/gloo#5523]
**Describe the bug**
Kubernetes 1.22 has [dropped support](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/) for both `extensions/v1beta1` and `networking.k8s.io/v1beta1`. APIs have been migrated to `networking.k8s.io/v1`.

When Gloo Edge is deployed in Ingress mode it fails due to the error,
```
{"level":"fatal","ts":"2021-10-30T08:41:08.653Z","logger":"ingress","caller":"setuputils/main_setup.go:73","msg":"error in setup: starting snapshot watch: initial Ingress list: listing ingressObjs in : the server could not find the requested resource (get ingresses.extensions)","version":"1.9.1","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:73\ngithub.com/solo-io/gloo/projects/ingress/pkg/setup.Main\n\t/workspace/gloo/projects/ingress/pkg/setup/setup.go:12\nmain.main\n\t/workspace/gloo/projects/ingress/cmd/main.go:9\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```

**To Reproduce**
1. Run kube2e tests for ingress with `CLUSTER_NAME=solo-test-cluster CLUSTER_NODE_VERSION=v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047 VERSION=v1.0.0-solo-test ci/deploy-to-kind-cluster.sh && KUBE2E_TESTS=ingress make run-ci-regression-tests`
This should produce the error,
```
Fail handler msg Unexpected error:
    <*errors.StatusError | 0xc000596000>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "the server could not find the requested resource (post ingresses.extensions)",
            Reason: "NotFound",
            Details: {
                Name: "",
                Group: "extensions",
                Kind: "ingresses",
                UID: "",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "404 page not found",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    the server could not find the requested resource (post ingresses.extensions)
```

Also confirming API version,
```
❯ k api-resources | grep ingress
ingressclasses                                 networking.k8s.io/v1                   false        IngressClass
ingresses                         ing          networking.k8s.io/v1                   true         Ingress
```

**Expected behavior**
Should be able to run in Kubernetes `1.22` and also be backwards compatible since most providers have not moved to `1.22` as a stable release yet.

**Additional context**
- Gloo Edge version *1.9*
- Kubernetes version *1.22*

**Comment by pseudonator** [comment]
Also impacts manifests in https://docs.solo.io/gloo-edge/latest/guides/integrations/ingress/

**Comment by sam-heilbron** [comment]
`extensions/v1beta1` references: https://github.com/solo-io/gloo/search?q=extensions%2Fv1beta1&type=code

**Comment by chrisgaun** [comment]
Related issue https://github.com/solo-io/gloo-mesh-enterprise/issues/1853

**Comment by sam-heilbron** [comment]
> Affects extauth and ratelimit

I don't think this does. THat linked issue refers to the CRDs produced by extauth and ratelimit. Gloo Edge generates its own CRDs and those services have been shown to function properly on kube 1.22.
