### ISSUE TITLE
provide go type for solo apis 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5531]
something similar too: https://github.com/jetstack/cert-manager/tree/master/pkg/apis/certmanager/v1

**Comment by asayah** [comment]
https://github.com/solo-io/solo-apis/blob/81a712d752f0f38e95b529a864460f8199a2614b/pkg/api/gloo.solo.io/v1/types.go

**Comment by jwilner** [comment]
Just pointing out that you have Go types for _some_ of your CRDs (the link there is just for some core ones), but a lot of them you don't. I was specifically looking for a `FederatedVirtualService` type which implements `runtime.Object`, which doesn't exist -- although the proto-gen type `FederatedVirtualServiceSpec` does.

**Comment by sam-heilbron** [comment]
@jwilner have you seen https://github.com/solo-io/solo-apis/issues/106? Can you let me know if the changes introduced to resolve that issue cover your use case?

**Comment by jwilner** [comment]
@sam-heilbron those changes look great -- definitely the types I need -- but I'm hitting a lot of grief with dependencies trying to pull them in -- stuff like:

```
	github.com/solo-io/solo-apis/pkg/api/fed.gateway.solo.io/v1 imports
	k8s.io/client-go/kubernetes/scheme imports
	k8s.io/api/admissionregistration/v1alpha1: module k8s.io/api@latest found (v0.22.3), but does not contain package k8s.io/api/admissionregistration/v1alpha1
```

Or

```
	github.com/solo-io/solo-apis/pkg/api/fed.gateway.solo.io/v1 imports
	sigs.k8s.io/controller-runtime/pkg/client imports
	k8s.io/client-go/metadata: package k8s.io/client-go/metadata provided by k8s.io/client-go at latest version v0.22.3 but not at required version v8.0.0+incompatible
```
