### ISSUE TITLE
Expose Envoy merge_slashes setting

### ISSUE THREAD

**Issue by DoroNahari** [solo-io/gloo#5532]
**Is your feature request related to a problem? Please describe.**
Envoy [recommends](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#best-practices-edge) to Enable [merge_slashes](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-merge-slashes) when using it as an edge proxy.

**Describe the solution you'd like**
Expose this envoy setting.

**Comment by sam-heilbron** [comment]
Add this field to our HCM settings definition: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/options/hcm/hcm.proto#L18

https://github.com/solo-io/gloo/pull/4728 is a PR that introduces functionality to the HCM and provides a template for the types of changes required. 

@DoroNahari would you be comfortable putting up a PR to introduce this? I'm happy to answer any questions if you have them.
