### ISSUE TITLE
Expose Envoy path_with_escaped_slashes_action setting 

### ISSUE THREAD

**Issue by DoroNahari** [solo-io/gloo#5533]
**Is your feature request related to a problem? Please describe.**
Envoy [recommends](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#best-practices-edge) to enable [path_with_escaped_slashes_action](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-path-with-escaped-slashes-action) when using it as an edge proxy.

**Describe the solution you'd like**
Expose this envoy setting.

**Comment by bcollard** [comment]
we have this option in the HCM settings, right here: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk/#pathwithescapedslashesaction

The full config path is under the Gateway CR: `httpGateway > options > httpConnectionManagerSettings > pathWithEscapedSlashesAction`

**Comment by bcollard** [comment]
feel free to reopen if needed
