### ISSUE TITLE
Upgrade k8s libraries to v0.21.6

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#5543]
**Is your feature request related to a problem? Please describe.**
Upgrade to resolve issues due to https://github.com/kubernetes/kubernetes/issues/91913

**Describe the solution you'd like**
Gloo, Solo-Apis and Solo-Projects rely on v0.21.x k8s libraries

Start with Gloo first, if successful let's make sure to inclue solo-kit as well.

**Context**
https://github.com/vmware-tanzu/octant/pull/2678 is a PR that claims this upgrade resolves the aforementioned issue

**Comment by gunnar-solo** [comment]
at present, version bumps have been accomplished in `gloo`.  It would be _optimal_ to also bump them in
- [ ] solo-apis
- [ ] solo-projects
- [ ] solo-kit

**Comment by gunnar-solo** [comment]
closing, as the relevant (important) updates are complete
