### ISSUE TITLE
Upgrade 1.8->1.9

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5544]
**Describe the bug**
Rate-limit server is not reading the new redis secret, probably the deployment is created before the secret is populated with the final value, or redis is never getting the new config

**To Reproduce**
1. install gloo 1.8.x
2. update to v1.9.x

```
❯ kgp
NAME                                      READY   STATUS    RESTARTS   AGE
aws-privateca-issuer-6c4d76588d-rcc64     1/1     Running   0          17d
cert-manager-6b99bb89fb-9m4bx             1/1     Running   0          17d
cert-manager-cainjector-f6c8694c6-5dzdn   1/1     Running   0          17d
cert-manager-webhook-84fd4487c9-2hhst     1/1     Running   0          17d
gateway-5fb4fbd657-6h8zz                  1/1     Running   1          8d
gateway-proxy-665b76f5c9-4kpgr            1/1     Running   0          8d
gateway-proxy-665b76f5c9-6d6w2            1/1     Running   0          8d
gateway-proxy-665b76f5c9-qkdv2            1/1     Running   0          8d
gloo-57578d44c-ldv79                      1/1     Running   0          8d
gw-sanity-service-7d55467c65-9sz9g        1/1     Running   0          17d
gw-sanity-service-7d55467c65-m4qdx        1/1     Running   0          17d
gw-sanity-service-7d55467c65-v287v        1/1     Running   0          17d
rate-limit-59dc499bfc-fldvm               0/1     Error     19         72m
rate-limit-6bc4dc79f9-jccf5               1/1     Running   2          8d
rate-limit-6bc4dc79f9-qgkdp               1/1     Running   0          8d
redis-5cc96bb698-92w4m                    1/1     Running   0          8d
❯ klf rate-limit-59dc499bfc-fldvm
{"level":"info","ts":"2021-11-05T16:37:35.677Z","caller":"redis/driver_impl.go:51","msg":"connecting to redis on tcp redis:6379 with pool size 10","version":"1.9.1"}
{"level":"warn","ts":"2021-11-05T16:37:35.679Z","caller":"redis/driver_impl.go:60","msg":"failed to authorize redis client, WRONGPASS invalid username-password pair or user is disabled.","version":"1.9.1"}
"Fri, 05 Nov 2021 16:37:35 UTC: github.com/solo-io/solo-projects/projects/rate-limit/pkg/runner/run.go:18"	server stopped with unexpected error: "WRONGPASS invalid username-password pair or user is disabled."
```

**Expected behavior**
The upgrade is done in a clean way.

**Additional context**
If you manually restart of the redis deployment, then it works again.

**Comment by sam-heilbron** [comment]
I see in the example provided that there are 3 instances of the rate-limit server running. Why are 2 of them working? 

Is this just an issue introduced in the 1.8 -> 1.9 upgrade or is this an issue with any upgrade?

https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments may be useful. @bcollard raised this in a similar issue: https://github.com/solo-io/gloo/issues/4955

**Comment by jmunozro** [comment]
The issue is only happening when going from 1.8 to 1.9, as in 1.9 it is the first time redis has a password. Any other upgrade should be fine.

there are 2 instances running because they were connected to redis without a password. Redis server was never restarted, so it did not get the changes properly.
