### ISSUE TITLE
InvalidDestinationWarning even though Upstream exists

### ISSUE THREAD

**Issue by jannes** [solo-io/gloo#5554]
**Describe the bug**
On a fresh Gloo installation (v1.9.0/v1.9.1) on K8s v1.20.8) with one VS and one Upstream, glooctl check showed the VS to be invalid. 
The Upstream is correctly referred to in the VS's route actions (there are a couple of routes with exactly the same route action), including its namespace. 
```
      routeAction:
        single:
          upstream:
            name: my-upstream
            namespace: my-namespace
```
However, the error  `*v1.Upstream { my-namespace.my-upstream } not found)` appears (multiple times, for each route).

Then I took the following steps:

1. I edited the VS and changed one route action's upstream namespace to non-existing `my-namespace-b`. As a result all the errors for the other route actions disappeared and I had a single expected `*v1.Upstream { my-namespace-b.my-upstream } not found)` error
2. I reverted that change in the VS, so the VS configuration was again in the starting state. As a result, there were no errors anymore.

No other changes were made.
I can't post the full VirtualService and Upstream objects here, sorry.

**To Reproduce**
~~I couldn't reproduce this so far. I'm going to keep trying and will update.~~ (see below update)
The upstream was created shortly before the VS, both are created programmatically.

**Expected behavior**
There should be no errors.

**Comment by chrisgaun** [comment]
Thanks. If you are able to reproduce let us know

**Comment by jannes** [comment]
the error message gloo logs when the upstream is created: 
```
upstream my-upstream-8080: port 8080 not found for service my-service
```
the service is created shortly before the upstream, and it defines port 8080

**Comment by jannes** [comment]
Update:

We are constantly running into this on one of our CI clusters. In our system tests we frequently remove/create a whole set of deployment/service/upstream/virtualservice at the same time (in that order) and we often get the above warning, but most of the time it reconciles. some times (~1/10) it doesn’t though and the virtualservice is left in an error state.

On cluster A with identical Gloo version (1.9.0) this error would always reconcile, while on cluster B (differing only by a few more gloo configuration options, like disabled function discovery) the permanent error state as described above occurs (the `InvalidDestinationWarning` is logged 2000 times per hour until manually resolved.

 I have been trying to recreate this scenario with an example application on a local kind cluster, but no success so far.

**Comment by nfuden** [comment]
The functionality has been implemented and additional tests against regressions in this space are being handled in https://github.com/solo-io/solo-kit/issues/499
