### ISSUE TITLE
SDS container missing readiness probe

### ISSUE THREAD

**Issue by snuggie12** [solo-io/gloo#5557]
**Describe the bug**
We had a misconfiguration during an upgrade where our istio-proxy was not receiving its certificates. The SDS server does not have a readiness probe and was in a crash loop. When both envoy and istio became ready but the backoff timer was still waiting the cert was now present. When SDS starts there is no readiness probe so it was immediately ready but took around 25 seconds to actually work correctly. We had normal log verbosity so not sure what would have caused this (see timeline.)

Timeline:
1. 09:51:36.296 - A single pod (new deployment) is reporting 503's to prometheus which uses istio mTLS to communicate
2. Nov 11, 2021 @ 09:51:41.404 - initializing config
3. Nov 11, 2021 @ 09:51:41.404 - config loaded
4. Nov 11, 2021 @ 09:51:41.404 - checking for existence of secrets
5. Nov 11, 2021 @ 09:51:41.404 - secrets confirmed present, proceeding to start SDS server
6. Nov 11, 2021 @ 09:51:41.404 - sds server listening on 127.0.0.1:8234
7. Nov 11, 2021 @ 09:51:41.404 - Updating SDS config. sdsClient is gateway-proxy-9c889d85b-hsqq2.gloo-system.Snapshot version is 13974182827697272484
9. Nov 11, 2021 @ 09:51:41.404 - watcher started
10. 09:52:01.052 - Last 503 appears

I think this is typically not an issue since the other two containers have readiness probes and must take longer than SDS to startup? Either way, it seems defensive to guard against this just in case.

**To Reproduce**
1. See above. We were pointing a 1.8.6 istio-proxy client at a 1.7.4 istiod so something like that or anything that prevents `/etc/istio-certs` from being populated.

**Expected behavior**
SDS is marked as ready when it is actually ready

**Additional context**
- Gloo Edge version 1.6.34 to 1.7.22 upgrade
- Kubernetes version 1.19
- Istio: both 1.7.4 and 1.8.6 control planes. Problem was 1.8.6 client talking to 1.7.4 server.

**Comment by chrisgaun** [comment]
Seems like a straight forward ask to add readiness probe and also probably pretty easy if that is the case so marking it as good first issue.
