### ISSUE TITLE
AWS Lambda gets Envoy logging wrong

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5560]
**Describe the bug**
During Lambda invocation the inital request data (Http method and path) are totally lost:
Example: `GET https://<api>/<path>` -> in the logs gets represented as -> `httpMethod: POST , path: <weird_path>/<lambda_name>` 

**Expected behavior**
Log the initial request elements

**Additional context**
- Gloo Edge version 1.9.2 EE

**Comment by nfuden** [comment]
The functionality is now in our code base 
Need to update docs to represent the recommended usage.
A new flag needs to be toggled in the proxy and then access logs must be explicitly set rather than using the defaults.

```
access_log: 
            - name: envoy.file_access_log
              typed_config: 
                "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"             
                path: /dev/stdout 
                format: '[%START_TIME%] "%REQ(X-ENVOY-ORIGINAL-METHOD?:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%"
%RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%"
"%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"\n'
```
