### ISSUE TITLE
"NOAUTH Authentication required" after introduction of ACL for Redis 

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5563]
**Describe the bug**
Given a route configured with OIDC extauth
And redis is set as the session store
When I curl the route
Then I get a 500 and the extauth pods log the following error:
```json
{"level":"warn","ts":1636745421.680908,"logger":"ext-auth.ext-auth-service","msg":"failed saving session","version":"undefined","error":"NOAUTH Authentication required."}
```

**Expected behavior**
The redis client should use the REDIS_PASSWORD that is set on the extauth pod as an env var

**Additional context**
- Gloo Edge version EE 1.9.2

**Comment by jmunozro** [comment]
As a temporary workaround, you can disable redis acl:
