### ISSUE TITLE
Route level extauth doesn't override VS-level customAuth

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5566]
**Describe the bug**
Given Gloo Edge EE configured with both default ExtAuth server and also one namedExtAuth (using HTTP mode)
When I apply the customAuth (ref to the namedExtAuth) at the VirtualService level
And when I apply a standard AuthConfig at the route level
Then, the route level extauth option is not applied (it should!), but the VS level customAuth is applied

**To Reproduce**
See gist: https://gist.github.com/bcollard/698f0fea299ce3c0abca5433981bb3c1

Generated Envoy route config:
```json
   "dynamic_route_configs": [
    {
     "version_info": "7362977873355489563",
     "route_config": {
      "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
      "name": "listener-::-8080-routes",
      "virtual_hosts": [
       {
        "name": "gloo-system_httpbin",
        "domains": [
         "*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "default-httpbin-8000_gloo-system"
          },
          "typed_per_filter_config": {
           "envoy.filters.http.ext_authz": {
            "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute",
            "check_settings": {
             "context_extensions": {
              "config_id": "gloo-system.api-key-ac",
              "source_name": "",
              "source_type": "route"
             }
            }
           }
          },
          "name": "gloo-system_httpbin-route-0-matcher-0"
         }
        ],
        "typed_per_filter_config": {
         "io.solo.filters.http.sanitize": {
          "@type": "type.googleapis.com/envoy.config.filter.http.sanitize.v2.SanitizePerRoute",
          "custom_auth_server_name": "customHttpAuthz"
         },
         "envoy.filters.http.ext_authz": {
          "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute",
          "check_settings": {}
         }
        }
       }
      ]
     },
     "last_updated": "2021-11-15T10:35:10.055Z"
    }
   ]
  },
```

No logs appeared in the ExtAuth server, with the log level set to debug.

**Expected behavior**
The route level extauth options should override the VS level extauth options

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version EE 1.9.2

**Comment by chrisgaun** [comment]
Related to https://github.com/solo-io/gloo/issues/5517

**Comment by sam-heilbron** [comment]
PR which introduced multiple ext auth filters: https://github.com/solo-io/solo-projects/pull/2371

Code responsible for configuring multiple ext_authz filters: https://github.com/solo-io/solo-projects/blob/master/projects/gloo/pkg/plugins/extauth/config_generator.go#L109

Tests that (theoretically) validate vhost+route configuration: https://github.com/solo-io/solo-projects/blob/master/test/e2e/extauth_multiple_filters_test.go#L436

**Comment by bcollard** [comment]
Reopening because the issue is still there.

The gist shared in the first post is still valid to reproduce the issue. I'll add more notes to it.

**Comment by bcollard** [comment]
updated the gist: https://gist.github.com/bcollard/698f0fea299ce3c0abca5433981bb3c1

**Comment by bcollard** [comment]
retested with Gloo v1.9.7 and 1.10.0
