### ISSUE TITLE
support Gloo on VMs

### ISSUE THREAD

**Issue by yuval-k** [solo-io/gloo#557]
use cases:
- hashi stack: nomand \ consul.
- bare metal
- regular VMs
- Specifically storage and discovery outside of Kubernetes, deferring auth to a follow up
    Referenced here: #453

**Comment by andye2004** [comment]
@yuval-k Can you please tell me if there has been any progress on this?

**Comment by rickducott** [comment]
Basic version of this is now working and there's a guide with using Consul/Vault instead of Kube for storage here: https://gloo.solo.io/user_guides/setup_options/consul_kv/
