### ISSUE TITLE
Reconcile Orphaned Gateways

### ISSUE THREAD

**Issue by guydc** [solo-io/gloo#5578]
**Is your feature request related to a problem? Please describe.**
A Gateway which is orphaned from Virtual Services is not being reconciled. As a result, it can show stale errors, as discussed here: https://github.com/solo-io/gloo/issues/5079. This can lead to false alerts, fail `glooctl check`, and so on. 

**Describe the solution you'd like**
Orphaned Gateway should present a correct status. This can be achieved by always reconciling gateways or gateways that are in error state, or some other option.

**Comment by kdorosh** [comment]
@gunnar-solo this problem can also probably manifest as orphaned route tables as well

**Comment by pseudonator** [comment]
Injecting the following custom GW leads to missing validation and thus no `status` field appears in the CRD.

```
  bindAddress: '::'
  bindPort: 8080
  #httpGateway: {}
  proxyNames:
  - gateway-proxy
  ssl: false
  useProxyProto: false
```

Not here that the commented (and required) `httpGateway` key-value should've triggered a validation here.
But it does not,

Heres the complete yaml output for reference,

```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  creationTimestamp: "2022-01-07T00:50:26Z"
  generation: 1
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
  resourceVersion: "219819"
  uid: 3ad18c85-8e38-4c0b-acf6-87492c83d6a1
spec:
  bindAddress: '::'
  bindPort: 8080
  proxyNames:
  - gateway-proxy
  ssl: false
  useProxyProto: false
```
