### ISSUE TITLE
Support Extended HTTP Methods

### ISSUE THREAD

**Issue by guydc** [solo-io/gloo#5579]
**Is your feature request related to a problem? Please describe.**
Envoy does not support extended HTTP methods. This limitation is related to the envoy http parser: https://github.com/envoyproxy/envoy/issues/5155#issuecomment-957814532. Several protocols use extended HTTP methods, like WebDAV. The [IANA http method registry](https://www.iana.org/assignments/http-methods/http-methods.xhtml) mentions several methods that are not supported by envoy, like `LABEL`, `UPDATE`, `CHECKIN`, etc. 

**Describe the solution you'd like**

* Support for all IANA registry methods
* Support for custom (arbitrary) HTTP methods

**Describe alternatives you've considered**
Exposing HTTP services that use custom HTTP methods with a TCP Gateway. This is not ideal, since HTTP request processing features cannot be applied to such services. 

**Additional context**

* https://github.com/nodejs/http-parser/issues/92
* https://github.com/nodejs/llhttp/issues/11
* list of supported methods in http-parser: https://github.com/nodejs/http-parser/blob/ec8b5ee63f0e51191ea43bb0c6eac7bfbff3141d/http_parser.h#L165

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207435393311532) by [Unito](https://www.unito.io)

**Comment by nfuden** [comment]
@ashishb-solo  this needs a backport to 1.17
