### ISSUE TITLE
Should be able to set ExternalTrafficPolicy on Gateway Proxy

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#558]
This is needed to preserve the client ip through the load balancer in the AWS setting.

**Comment by yuval-k** [comment]
I'm assuming you opened this issue for the changelog; you can also use the PR itself as an issue for the changelog (if there is no existing issue) to save you the effort next time.

**Comment by yuval-k** [comment]
and of-course, thank you for your contribution!

**Comment by derrickburns** [comment]
Does this page need to be modified?

https://gloo.solo.io/installation/kubernetes/quick_start/

**Comment by yuval-k** [comment]
yes please, its not auto generated yet.
