### ISSUE TITLE
Add a shortname to VS crd to not collide with Istio's one

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#5591]
**Is your feature request related to a problem? Please describe.**
When having installed Istio and Gloo Edge, both offers a CRD with name VirtualService and shortname `vs`.

It is annoying to use the full name to read the resource.

**Describe the solution you'd like**
Add another shortname to the resource to avoid the colision. i.e. `gvs`

**Comment by antonioberben** [comment]
@sam-heilbron which test should I add for this?

**Comment by kdorosh** [comment]
@antonioberben see https://github.com/solo-io/gloo/pull/5592#pullrequestreview-811421676

i'm a little surprised this passed codegen

**Comment by kdorosh** [comment]
https://github.com/solo-io/gloo/pull/5592#issuecomment-975668068

**Comment by kdorosh** [comment]
implemented in https://github.com/solo-io/gloo/pull/5592
