### ISSUE TITLE
Bump Gloo Edge 1.9 envoy dep to 1.20

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#5597]
**Describe the bug**
Bump Gloo Edge 1.9 envoy dep to 1.20

We should also bump our default branch to 1.21 dev envoy.

This needs to be done in open source and enterprise

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version
- Kubernetes version

**Comment by ben-taussig-solo** [comment]
https://github.com/solo-io/gloo/pull/5903 and https://github.com/solo-io/solo-projects/pull/3088 resolve this issue.
