### ISSUE TITLE
[Helm] multiple containers break block 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5604]
**Describe the bug**

Anything in this block breaks if you also have multiple containers enabled: https://github.com/solo-io/gloo/blob/88a16c5218a6c8a03ba3271a6c0f9480e791fade/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L302-L323
```
7-gateway-proxy-deployment.yaml
      {{- if $spec.kind.daemonSet }}
      {{- if $spec.kind.daemonSet.hostPort }}
      hostNetwork: {{ ne "false" ($spec.kind.daemonSet.hostNetwork | toString) }} {{/* defaults to true if undefined */}}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end}}
```

**Comment by inFocus7** [comment]
Hi Adam! 👋 I have a few quick questions!

- What exactly is meant by having multiple containers enabled?
- Do you happen to remember how you pinpointed the errors to those block of codes?
