### ISSUE TITLE
gateway-proxy gradual increased memory usuage

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#5611]
**Describe the bug**
With a fairly vanilla deployment of gloo edge, memory use of the gateway-proxy slowly increases over time. 

14 days (0 to little traffic)
![image](https://user-images.githubusercontent.com/65769106/142905202-490f324a-86fc-41f5-9d26-ecda8ab8c5dd.png)

7 days (medium traffic)
![image](https://user-images.githubusercontent.com/65769106/142906292-1d58776d-98e6-43b5-8cdd-df4188909915.png)

14 days (medium traffic)
![image](https://user-images.githubusercontent.com/65769106/142905396-90ff0c55-a67d-4ac8-b187-987f171d5ede.png)

internal link: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1637336474225400

**To Reproduce**
1. kube apply '...'
2. curl '....'
3. See error

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version
- Kubernetes version

**Comment by Jimmmz** [comment]
Customer has deemed this issue as closed
