### ISSUE TITLE
wasm filter gradual memory increase over time

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#5612]
**Describe the bug**
wasm filter causes gradual memory increase for the gateway-proxy from 300mb to 3gb over time

internal link: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1637336474225400

**To Reproduce**
1. kube apply '...'
2. curl '....'
3. See error

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version
- Kubernetes version

**Comment by kdorosh** [comment]
see https://github.com/solo-io/proxy-runtime/issues/40 which might be related per @yuval-k

**Comment by kdorosh** [comment]
based on testing, https://github.com/solo-io/proxy-runtime/pull/61 should help significantly

some test config: https://gist.github.com/kdorosh/99a39c4772d5edda014ac9c7a93d135c

memory usage test results, memory % as % of total 8GiB allocated to envoy:

| time | v0.14 mem % | v0.19 mem%  | 
|---|---|---|
| 12:00pm  | 0.66 | 0.54 |
|  12:15pm | 1.23 | 0.56 | 
| 12:30pm  | 2.0 | 0.57 |
| 12:50pm  | 2.66 | 0.58 |
| 1:20pm  | 3.72 | 0.58 |
