### ISSUE TITLE
AWS Lambdas - handle Lambda-side timeout / errors

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5618]
**Describe the bug**
There are two different places where you can define timeout upstream side:
- AWS lambda configuration
- the timeout option on the route

If the lambda timeout triggers before the Envoy timeout, then we return a 200 HTTP code with an error message
Example:
```json
{"errorMessage":"2021-11-23T10:12:51.182Z f803ab70-cec2-4fc1-b200-d06984ae9f53 Task timed out after 3.00 seconds"}
```

More generally, can we handle these error messages in the AWS Lambda response? we probably need to find the AWS spec at first.

**To Reproduce**
- Create a new AWS Lambda with the Python runtime and the following code:
```python
import json
import time

def lambda_handler(event, context):
    # TODO implement
    time.sleep(20)
    
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }
```

- the default timeout on the AWS Lambda is 3 seconds

- configure an Upstream type AWS and a VS routing to that Lambda
- curl it
`curl -X POST $(glooctl proxy url)/sleep -v`

**Expected behavior**
return 504 Gateway Timeout, run the retries if configured, etc.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.9.3
- Kubernetes version eks k8s 1.21

**Comment by bcollard** [comment]
Note: it looks like Lambdas will produce a 200 HTTP response with the header `X-Amz-Function-Error` in case of an error or a timeout.

sources:
- https://docs.aws.amazon.com/lambda/latest/dg/nodejs-exceptions.html#nodejs-exceptions-how
- https://docs.aws.amazon.com/lambda/latest/dg/python-exceptions.html#python-exceptions-how

**Comment by nfuden** [comment]
Merged in envoy-gloo

Is there an urgency for a release cut with this? If so we can bump dependencies and cut a release for this now otherwise this issue has been implemented.

**Comment by bcollard** [comment]
no urgency, thank you!
