### ISSUE TITLE
 Use generated Clone() functions for Snapshopt clone

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#5620]
Currently when cloning snapshots, Gloo uses `proto.Clone()`. However, generated Clone() functions were recently added to [`protoc-gen-ext`](https://github.com/solo-io/protoc-gen-ext/blob/0d0ed8040ffdf7902f7f7a13a3420274e04a0cd9/extproto/ext.proto#L24) so we should test that those are faster, and if so use them instead.

**Comment by kdorosh** [comment]
some helpful steps for profiling control plane components can be found in the pr description [here](https://github.com/solo-io/gloo/pull/2658)

**Comment by sam-heilbron** [comment]
re-open for backports

**Comment by chrisgaun** [comment]
Putting In Progress until we backport
