### ISSUE TITLE
Investigate using faster hashing for routes

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#5621]
Recently changes were made to the translator hashing method to speed it up. However, these changes were not applied to routes.
The old style `hashstructure.Hash` is always used. https://github.com/solo-io/gloo/blob/24c2c36a4ba8f5bc15975ef6f7aa2bb9d12d3437/projects/gloo/pkg/translator/translator.go#L328

We should swap this out for the translator struct member hasher impl instead.

**Comment by sam-heilbron** [comment]
No work to be done.

**Comment by elcasteel** [comment]
We need to backport to 1.9 and 1.8.
