### ISSUE TITLE
Invalid Settings when extauthCustomYaml is provided 

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5629]
**Describe the bug**
In glooee, the `18-settings.yaml` file is generated incorrectly if extauthCustomYaml is provided 

**To Reproduce**
```
cat <<EOF > values.yaml
global:
  extauthCustomYaml: true
  extensions:
    extAuth:
      extauthzServerRef:
        name: external-auth-server
        namespace: kube-gloo-system
      httpService:
        pathPrefix: /envoy/verify-params-header
        request:
          allowedHeaders:
          - cookie
          - x-forwarded-host
          - x-forwarded-method
          - x-forwarded-proto
          - x-forwarded-uri
EOF

helm template gloo glooe/gloo-ee --devel --namespace gloo-system --version=1.9.3\
  --create-namespace \
  --set-string license_key=mylicense \
  -f values.yaml \
  --dry-run --output-dir ./dist

k apply -f ./dist/gloo-ee/charts/gloo/templates/18-settings.yaml --dry-run=client

# Error: error validating "./dist/gloo-ee/charts/gloo/templates/18-settings.yaml": error validating data: [ValidationError(Settings.spec.extauth): unknown field "deployment" in io.solo.gloo.v1.Settings.spec.extauth, ValidationError(Settings.spec.extauth): unknown field "enabled" in io.solo.gloo.v1.Settings.spec.extauth, ValidationError(Settings.spec.extauth): unknown field "envoySidecar" in io.solo.gloo.v1.Settings.spec.extauth, ValidationError(Settings.spec.extauth): unknown field "service" in io.solo.gloo.v1.Settings.spec.extauth, ValidationError(Settings.spec.extauth): unknown field "serviceName" in io.solo.gloo.v1.Settings.spec.extauth, ValidationError(Settings.spec.extauth): unknown field "signingKey" in io.solo.gloo.v1.Settings.spec.extauth, ValidationError(Settings.spec.extauth): unknown field "standaloneDeployment" in io.solo.gloo.v1.Settings.spec.extauth, ValidationError(Settings.spec.extauth): unknown field "tlsEnabled" in io.solo.gloo.v1.Settings.spec.extauth]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Expected behavior**
Generic yaml insertion for third party configs is supported in OSS and should work in Enterprise too.

**Additional context**
- Gloo Edge version = 1.9.3

**Comment by jmunozro** [comment]
This could be fixed moving the config block `global.extensions.extAuth` in the `values.yaml` of enterprise version to another variable, so it is not propagated to the child charts.

**Comment by nrjpoddar** [comment]
Do we need to preserve any backwards compatibility? I'm assuming no since this wasn't working to begin with but it's always good to ask before moving Helm values.

**Comment by jmunozro** [comment]
I don't think so, this bug has been present in the code for some time and it is not a common use case for enterprise customers (as gloo provides an extauth server OOTB that is the common choice)

**Comment by pseudonator** [comment]
This is only useful for OSS customers with a custom ext auth at this point. @jmunozro is right that it existed in code for sometime.

**Comment by pseudonator** [comment]
Even one of us can create a PR for this cc @jmunozro

**Comment by jmunozro** [comment]
I believe this is a valid use case for Enterprise customer who have a better (or with any feature we don't have) ExtAuth server than the one we provide.

**Comment by jmunozro** [comment]
closing as a valid solution is given here: https://github.com/solo-io/gloo/pull/5641#discussion_r758214491
