### ISSUE TITLE
Allow configuration of where upstreams are created when discovered.

### ISSUE THREAD

**Issue by rettori** [solo-io/gloo#563]
As an application owner, I'd like my discovered upstreams to be created on the same namespaces they were found because I extensively use namespaces to organize and control access to resources in my cluster.

**Comment by yuval-k** [comment]
amen!

**Comment by rickducott** [comment]
I don't think this is a priority. More likely, customers will ultimately store the upstreams in a Git repo and write them to whatever namespace is desired, rather than rely on discovery.
