### ISSUE TITLE
Kubernetes validation webhook to reject creation of gloo object with invalid references

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5630]
**Is your feature request related to a problem? Please describe.**
A new VirtualService that references an invalid (or not existing) secret is not rejected.

**Describe the solution you'd like**
It would be useful to have a generic check for referenced object in the gloo apis, secrets are the common case.

**Describe alternatives you've considered**
As an alternative, checking for secrets would cover most use cases.

**Additional context**
[Deletion of secrets implementation](https://github.com/solo-io/gloo/issues/5366)
[Related milestone](https://github.com/solo-io/gloo/issues/2797)

**Comment by MitchAman** [comment]
Notes from a little investigating:

So our current implementation for secrets is that we only validate on deletions. This is to ensure that no resources are still referencing that secret. I do not believe that we have validation against creating a resource which references a non-existent secret (I've only tested with an upstream). It would have be up to each gloo/gateway resource type to handle validating that their secret reference exists during a CREATE.

It's possible we already do this validation for some resources, but it would be on a case-by-case basis. There's obviously some logic which detects a missing secret when it's deleted, so there must be a way to tie into that when resources are being created.

**Comment by nfuden** [comment]
This has been solved in https://github.com/solo-io/gloo/issues/8001
