### ISSUE TITLE
AWS Lambdas - create a new "AWS ALB mode" for response payloads

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5635]
**Is your feature request related to a problem? Please describe.**
Some of our clients migrate from ALB to Gloo Edge. They used to have AWS ALBs to call their AWS Lambdas. There is a pre-defined response format that is expected by the ALB.
More info here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#respond-to-load-balancer

The idea is to create a new mode for Upstream type AWS Lambdas where, the following JSON payload is expected and parsed by Gloo:
```json
{
    "isBase64Encoded": false,
    "statusCode": 200,
    "statusDescription": "200 OK",
    "headers": {
        "Set-cookie": "cookies",
        "Content-Type": "application/json"
    },
    "body": "Hello from Lambda (optional)"
}
```

The expectation is Gloo Edge to be able to translate this into a valid response to the client where:
response status = statusCode
response headers = headers
response body = body

This could be an option enabled by a flag, like `albMode` on the Upstream CR.

**Comment by nfuden** [comment]
@bcollard so to clarify this is purely about the decoding of lambda response.

Secondly do you have an opinion on the naming of the field? 
I am currently thinking of "decode_as_alb" do you think that would be sufficiently clear for the use case?

**Comment by bcollard** [comment]
agree on the purpose and the name.
