### ISSUE TITLE
AWS Lambdas - multi AWS account support with the IAM role authentication method

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5639]
Gloo Edge should be able to discover and invoke lambdas across several AWS accounts.
Today it's possible using [AWS security credentials](https://docs.solo.io/gloo-edge/master/guides/traffic_management/destination_types/aws_lambda/) (access key + secret key), but not with the [IAM role binding method](https://docs.solo.io/gloo-edge/master/guides/traffic_management/destination_types/aws_lambda/eks-service-accounts/).

**Comment by nfuden** [comment]
Our current supported auth via IAM binding uses the eks built in ability to link to a given token.
The trust relationships between serviceaccount and roles it can assume is detailed under the section for Cross-account IAM permissions here:
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

If you are using lambda from EKS then you can annotate the pod with the source arn and then make sure that your upstreams have the desired role set.

**Comment by krisMembeVia** [comment]
@nfuden 
```You can configure cross-account IAM permissions either by creating an identity provider from another account's cluster or by using chained AssumeRole operations. In the following examples, Account A owns an Amazon EKS cluster that supports IAM roles for service accounts. Pods running on that cluster need to assume IAM permissions from Account B.```
From this snippet in the docs I deduce the following:
Cross account actions using services account can work in either of the following cases:
1. For each separate account you need access to you’d need to have an eks cluster with OIDC (so this is a no go)
2. You need to use chained AssumeRole (this is not supported by your current implementation)

**Comment by nfuden** [comment]
Update: after doing further trust policies in a true cross account and not just cross region we have a pattern we will add to get allow for chaining as long as the trust relationships are correct in source and target accounts.
