### ISSUE TITLE
Remove script since it is not maintained

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#5640]
**Describe the requested changes**
At this page: https://docs.solo.io/gloo-edge/master/guides/security/opa/
The offered script is not maintained and can cause customers to get confused.

![image](https://user-images.githubusercontent.com/5262332/143479496-d2f72058-f86e-4783-8afa-e812cc6774b9.png)

It would be interesting to offer only the official tutorial as it is stated in the following line as the only source of truth.

**Link to any relevant existing docs**
https://docs.solo.io/gloo-edge/master/guides/security/opa/

Thank you

**Comment by artberger** [comment]
Thanks for raising this issue. Here is a doc PR: https://github.com/solo-io/gloo/pull/5656
