### ISSUE TITLE
Support PDB and AntiAffinity for all data-plane components

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#5648]
**Is your feature request related to a problem? Please describe.**
The `gateway-proxy` deployment has [optional support for anti-affinity rules](https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L105-L114) as well as a [`PodDisruptionBudget` resource](https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/8-gateway-proxy-pod-disruption-budget.yaml).

However neither of these of features are available for other components in the data-plane, such as `extauth` and `ratelimit`. 

**Describe the solution you'd like**
Anti-affinity and PDB for the other data plane components

**Describe alternatives you've considered**

**Additional context**
Necessary to have a robust deployment with multiple replicas of the data-plane components

**Comment by chrisgaun** [comment]
Possible Dupe

**Comment by chrisgaun** [comment]
FYI. We should also document this.

**Comment by ben-taussig-solo** [comment]
Reopening the issue while I add some documentation around these behaviors.

**Comment by lgadban** [comment]
Can we backport this to 1.9.x?

**Comment by lgadban** [comment]
CC: @chrisgaun @sam-heilbron 
This feature was requested to be backported to 1.9.x; can add more context in Slack

**Comment by gunnar-solo** [comment]
(the docs thread was mis-linked, FYI)

**Comment by ben-taussig-solo** [comment]
This functionality is now available in Gloo Edge Enterprise release [v1.9.10](https://github.com/solo-io/solo-projects/releases/tag/v1.9.10). Closing the issue for now.

**Comment by chrisgaun** [comment]
@lgadban fyi
