### ISSUE TITLE
Provide security posture tagging for Solo's envoy extensions

### ISSUE THREAD

**Issue by Spoonbender** [solo-io/gloo#5650]
**Describe the requested changes**
The Gloo documentation should include a security posture tagging for each of Solo's envoy extensions.

Envoy's own extensions have a security posture tagging, which explains if the extension is hardened against untrusted downstreams and/or upstream. The security posture is assessed according to Envoy's guidelines as explained in the [Envoy Extension Policy](https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md#extension-stability-and-security-posture).

We'd like to have Solo's own extensions assessed under the same guidelines, and have the information documented.
Ideally, we'd be glad to get the information using the same YAML format which Envoy itself provides (see below).

**Link to any relevant existing docs**
The extension security posture data is available in the following locations:
1. Envoy's [Threat Model documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/threat_model#core-and-extensions)
2. [/source/extensions/extensions_metadata.yaml](https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_metadata.yaml) which provides the security posture data for each of Envoy's extensions in a structured, machine-friendly manner.
3. [/contrib/extensions_metadata.yaml](https://github.com/envoyproxy/envoy/blob/main/contrib/extensions_metadata.yaml) which provides the security posture data for each of Envoy's contributed extensions in the same format as above.

**Additional context**
The security posture data helps us determine which extensions we can use, as our usage of Gloo Edge is that of an API gateway with untrusted downstreams.
By using the same YAML format as used by Envoy, we'll be able to integrate Solo's metadata with our existing tooling which checks the envoy configuration against this metadata and ensures only hardened extensions are used.

Some _examples_ of Solo extensions listed in our envoy config dump includes:
```
io.solo.filters.http.sanitize 
io.solo.filters.http.solo_jwt_authn_staged
io.solo.filters.http.transformation_ee
io.solo.transformation
io.solo.envoy.listener.proxy_protocol
```

**Comment by nfuden** [comment]
The security postures are now generated and checked in CI for both our OSS and Enterprise envoy extensions.
The final question here is if we wish to make the discovery easier for the enterprise extensions as it currently can be delivered on request.

**Comment by kcbabo** [comment]
Thanks, Nathan. I will spin up a separate issue for how we will generate and publish this as part of public documentation moving forward.

**Comment by nfuden** [comment]
Keith I will make a general ticket for it as there are a few other bits that we want to see about pulling into the edge docs from our envoy repos.
