### ISSUE TITLE
Add boolean setting for `httpOnly` in extauth cookie settings

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#5678]
**Is your feature request related to a problem? Please describe.**
A user asks this:
> The OIDC login flow returns some cookies (id-token and access-token) which are set as httpOnly (so not accessible from javascript code). This means the tokens can't be reused with some microservices calls (from the page) which would also use Gloo Edge to just validate the token. Is there a way to remove the httpOnly flag (yes, I know the risks), or is there another way one is supposed to achieve this flow - site uses OIDC to get some token, further uses that token to call microservices, let Gloo do all of these? Since the webapp and microservices are different domains, can't use directly the cookies...

In the current code, `httpOnly` is hardcoded to true [here](https://github.com/solo-io/solo-projects/blob/master/projects/extauth/pkg/config/translator.go#L500-L505).

**Describe the solution you'd like**
Add boolean `httpOnly` defaulted to true in extauth CookieOptions [here](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#cookieoptions).

**Additional context**
Internal [discussion](https://solo-io.slack.com/archives/C02KABQFD0A/p1638889533097400).

**Comment by kdorosh** [comment]
reopening as ID token and access token appear to be unusable from javascript after this change @yuval-k

**Comment by yuval-k** [comment]
need to understand this scenario better, as e2e test confirm that this work as expected.

**Comment by yuval-k** [comment]
after talking with the customer, this is solved
