### ISSUE TITLE
Upgrade `google.golang.org/grpc` to `v1.42.0`

### ISSUE THREAD

**Issue by gunnar-solo** [solo-io/gloo#5719]
**Describe the bug**
As part of performing a [k8s dependency bump](https://github.com/solo-io/gloo/issues/5543), `google.golang.org/grpc` was naturally upgraded to `v1.42.0` from `v1.40.0` as a transitive dependency.  This upgrade in particular cases a test failure:

```
------------------------------
• Failure [10.008 seconds]
RetryOnUnavailableClientConstructor
/Users/gunnar/.gvm/pkgsets/go1.16.3/global/src/github.com/solo-io/gloo/projects/gateway/pkg/validation/robust_client_test.go:52
  creates a new client and closes the old one [It]
  /Users/gunnar/.gvm/pkgsets/go1.16.3/global/src/github.com/solo-io/gloo/projects/gateway/pkg/validation/robust_client_test.go:54

  Expected an error to have occurred.  Got:
      <nil>: nil

  /Users/gunnar/.gvm/pkgsets/go1.16.3/global/src/github.com/solo-io/gloo/projects/gateway/pkg/validation/robust_client_test.go:82
------------------------------
```

A goodly amount has been looked _into_ the failure:
* [employee slack thread #1](https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1639583488107700)
* [employee slack thread #2](https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1639669308152900)
...but no solution was ultimately reached.

Thus, the issue was sidestepped by pinning `google.golang.org/grpc` to version `v1.40.0`.  This is considered "bad", and should eventually be removed.  Ultimately, it looks like one of the failing unit tests assumptions "a client with an existing server connection cannot connect to a new (identical) server on original server crash" is wrong.  Not _guaranteed_ to be the issue, but that is what investigation led to at the time.  Feel free to reach out to @gunnar-solo if you (instead of me) get assigned to this in the future!

**Comment by sam-heilbron** [comment]
I came across https://github.com/istio/istio/pull/36516 and was reminded that we may be able to leverage other open source projects performing similar changes. Leaving a comment here for whoever takes on this challenge

**Comment by nfuden** [comment]
1.13.24
