### ISSUE TITLE
listen unix /usr/share/shared-data/.sock: bind: address already in use

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#5728]
**Describe the bug**
Deploying extAuth as a sidecar throws an error from time to time.

```
server stopped with unexpected error: failed to announce on network: listen unix /usr/share/shared-data/.sock: bind: address already in use
```

**To Reproduce**
1. Deploy gloo with minimum and default configuration
1. Apply deployment.yaml attached to the issue:   [deploy.yaml.zip](https://github.com/solo-io/gloo/files/7746372/deploy.yaml.zip)
  This will deploy gateway-proxy with extauth as sidecar and sharing the `.sock`
1. Check the pod logs and keep it open
1. Access the node
1. kill the extauth container: To do this go to the node/machine/vm/container(for the case of kind) where the environment runs and kill the container. If the runtime is containerd you can use `ctr task ls`. In k3s `k3s crictl ps`. find out which is the container based on the name and the pod id diplayed in the running containers list and kill it or force kill it: `rm` or `rm -f`
1. Check the logs and you should be able to see:
```
server stopped with unexpected error: failed to announce on network: listen unix /usr/share/shared-data/.sock: bind: address already in use
```

**Expected behavior**
When the container is killed by whichever reason, socket is killed gracefully.
This link might help: https://stackoverflow.com/questions/5106674/error-address-already-in-use-while-binding-socket-with-address-but-the-port-num

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: 1.9.6

**Comment by sam-heilbron** [comment]
@antonioberben Does this happen consistently?

**Comment by antonioberben** [comment]
Yes, quite often

**Comment by jackstine** [comment]
Rolling the pods does fix the problem.

I can get the ext-auth container to fail, when I send two `kill 1` commands. 

When sending one `kill 1` command, the container will fail gracefully and within 15 seconds it will restart a new container that will work fine.  When two commands are sent, the container will fail to restart and every time after that.

**Comment by nfuden** [comment]
While the manual tests prove out the efficacy here we are reopening this issue to rework the included test as it has been very flakey.
