### ISSUE TITLE
Helm chart supports multiple services/deployments for gateway-proxy

### ISSUE THREAD

**Issue by dieterdemeyer** [solo-io/gloo#573]
Hello,

I've been experimenting with gloo and it looks quite good.
For our use case, it would be nice to have both an "external" service with corresponding gateway proxy for public facing URLs and an "internal" service (with internal load balancer) with corresponding gateway proxy for internal URLs.
Is it possible to have this feature added ?

As a reference, the Helm Chart for istio support providing multiple gateways which can be used like this: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values-istio-gateways.yaml#L27

cc @christian-posta

**Comment by ilevine** [comment]
this is fixed.
