### ISSUE TITLE
Extauth plugin sample does not load plugin 

### ISSUE THREAD

**Issue by willowmck** [solo-io/gloo#5736]
**Describe the bug**
In Gloo Edge Enterprise 1.9.7, extauth will not load the plugin that is defined at https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/plugin_auth/.  Also, there is a missing log statement in extauth 

```
{"level":"info","ts":1573574476.3579354,"logger":"extauth.header_value_plugin","caller":"pkg/impl.go:39","msg":"Parsed RequiredHeaderAuthService config","requiredHeader":"my-header","allowedHeaderValues":["foo","bar"]}
```

**To Reproduce**
Follow the steps at https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/plugin_auth/ to install Gloo Edge and load the extauth plugin for petstore.  After creating the AuthConfig and referencing it from the VirtualService, you will still get a 200 response.

**Expected behavior**
The request should get a 401 Unauthorized response.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version - 1.9.7 (Enterprise)
- Kubernetes version - 1.20

**Comment by saiskee** [comment]
after some investigation, I believe that the plugin is being loaded correctly. The sample plugin we publish is not correct currently. Closing in favor of https://github.com/solo-io/gloo/issues/5737
