### ISSUE TITLE
Rate limiting doesn't work with grpc Transcoder 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5742]
**Describe the bug**
Rate limiting doesn't work, when using the grpc transcoder, in gloo EE 1.7.20

**To Reproduce**
- install gloo EE 1.7.20 
- Follow this tutorial to expose a grpc service using the transcoding: https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/grpc_to_rest_advanced/
- create a route that matches the grpc service explicitly (this is important, and I think this is causing the bug)
for example
if in your gateways you have exposed the grpc service + protobin: 
```
        services:
        - solo.api.v1.StuffService
````
add also a route to a route table: 
```
    - prefix: /solo.api.v1.StuffService
```
that route to the grpc upstream 
        
- add a basic rate limiting policy to the vs
- curl the service through the transcoder  `localhost:8080/v1/stuffs`, this will never be rate limited even if the correct rt policy is attached, grpc will be rate limited, and rest will be too, but not the transcoder path 

**Expected behavior**
Rate limiting work in all scenarios

**Comment by kdorosh** [comment]
does this reproduce on the newly released solo-projects:v1.10.0-rc1?

**Comment by asayah** [comment]
@kdorosh same issue with v.10.0-rc1

**Comment by sam-heilbron** [comment]
@asayah Any update on this?

**Comment by asayah** [comment]
@ben-taussig-solo @sam-heilbron can you please let me know which option needs to be exposed in envoy to make this work?

**Comment by sam-heilbron** [comment]
@asayah @chrisgaun We believe this issue has been resolved and the relevant documentation was introduced with https://github.com/solo-io/gloo/pull/5833. We are closing this issue as there has not been any movement on it.
