### ISSUE TITLE
Lets add the ability to associate VirtualService with specific gateway

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#575]
Multiple examples from the community slack suggest we should improve the user experience around how a virtual service gets attached to a gateway.

Right now you can do two things:

1) convention based on the presence of SSL config
2) explicit mapping by patching the YAML

it would be preferable to be able to do this from the CLI as well, as an example:

`glooctl create virtualservice --name foo --gateway foo-gateway`

**Comment by ilevine** [comment]
This may require a breaking API change. or a new API - potentially the kube ingress v2.

**Comment by leosunmo** [comment]
This is something I'm coming up against now that I need a public and private Gloo instance/Load-balancer. Having to list out all the VS' I need in a specific Gateway object makes it harder for me to bundle routing config with application config.

**Comment by ilackarms** [comment]
does not require a break in the API. we can add a `gateway` selector to the `virtualservice` spec, allowing easier self service for users

**Comment by rickducott** [comment]
Going to close as stale -- I think the API exposes a few more options now, such as using a selector instead of a fixed list. 

https://github.com/solo-io/gloo/blob/50ed85917a70cc6ee3f957886b12c603aa734a80/projects/gateway/api/v1/gateway.proto#L93
