### ISSUE TITLE
Allow Direct Response to happen after extauth and rate limiting

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#5761]
### Version

1.9.x (latest stable)

### Is your feature request related to a problem? Please describe.

Currently, the only way to achieve that is to have a dummy service (like httpbin) instead of using a Direct Response.

### Describe the solution you'd like

It looks like Envoy has this option (and could even be the new default): https://github.com/envoyproxy/envoy/pull/17546

But not sure we use a version of Envoy with this change and also I don't think it applies rate limiting.

**Comment by jmunozro** [comment]
This is available in 1.20: [release notes](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.20.0)
