### ISSUE TITLE
Expose all the HCM properties

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5762]
### Version

1.10.x (beta)

### Is your feature request related to a problem? Please describe.

We have customer requests to expose the following HCM properties:

- `headers_with_underscores_action`
- `max_requests_per_connection`

It sounds like they are now available on the go-control-plane version we use.

EDIT: additional note: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html?highlight=httpconnectionmanager#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-common-http-protocol-options

**Comment by lgadban** [comment]
Another request for: `allow_chunked_length` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-http1protocoloptions

**Comment by csabakollar** [comment]
Thanks for opening this issue.
We are following this best practice guide https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge and we also wish to set somehow in the envoy bootstrap config the following settings:

- listener buffer limits: `per_connection_buffer_limit_bytes` - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-per-connection-buffer-limit-bytes
- cluster buffer limits: `per_connection_buffer_limit_bytes` - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-per-connection-buffer-limit-bytes
- maximum concurrent streams limit for HTTP/2 (for HTTP/3 it's already 100) - `max_concurrent_streams` - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-http2protocoloptions-max-concurrent-streams
- HTTP/2 initial stream window size: `initial_stream_window_size` - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-http2protocoloptions-initial-stream-window-size
- HTTP/2 initial connection window size limit: `initial_connection_window_size` - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-http2protocoloptions-initial-connection-window-size
- headers_with_underscores_action setting: `headers_with_underscores_action` - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-headers-with-underscores-action

I saw that the merge_slashes and normalize_path settings are available in Envoy 1.10, so for that we must upgrade.

Thank you in advance.

**Comment by chrisgaun** [comment]
Related to https://github.com/solo-io/gloo/issues/5792
