### ISSUE TITLE
Hybrid Gateway resourceRef option

### ISSUE THREAD

**Issue by bewebi** [solo-io/gloo#5767]
### Version

1.10.x (beta)

### Is your feature request related to a problem? Please describe.

We've introduced Hybrid Gateways, which consist of any number of MatchedGateway members, each of which must contain a complete HttpGateway or TcpGateway definition
Therefore Gateway CRs are liable to grow to unwieldy sizes

### Describe the solution you'd like

We should consider adding a new CRD for "single" gateway members of Hybrid Gateways
These would serve the exclusive purpose of being referred to by reference in Hybrid Gateways, adding a third option for MatchedGateways that bypasses the need for complete in-line Gateway definitions within the Gateway CR

### Describe alternatives you've considered

The current solution is functional, but may get out of hand for large numbers of MatchedGateways

### Additional Context

[Original issue](https://github.com/solo-io/gloo/issues/5324)
[Original feature PR](https://github.com/solo-io/gloo/pull/5623)

**Comment by guydc** [comment]
Also relevant here: https://github.com/solo-io/gloo/issues/5549. With this improvement, it would be easier to scope HCM settings to specific virtual services without increasing the size of the gateway resource.

**Comment by sam-heilbron** [comment]
Plan of action:

- [x] Introduce API, go types, CRD, simplify rbac, add basic helm tests (https://github.com/solo-io/gloo/pull/5844)
- [ ] Reporting
  -  [ ] Make it easier to aggregate resourceReports on a ProxyReport, regardless of Gateway type. This will allow our translators to not have to distinguish reports for each of the gateway types.
  - [ ] Introduce suport for new http gateway.
  - [ ] Proxy reconciliation support.
  - [ ] Tests
- [ ] Gateway translation:
  - [ ] make http translator more generic so it can handle HttpGateway on a Gateawy, HttpGateway on a HybridGateway and HttpGateway on a DelegatedGatweay.
  - [ ] Make our logic around merging sslConfig (or which ssl config to aggregate) more explicit. We should easily be able to understand the behavior of translators
  - [ ] HybridTranslator needs to support new type
  - [ ] Tests
- [ ] Gateway validation:
  - [ ] validate new hybrid gateway type
  - [ ] Tests, test, test
- [ ] Internal API changes:
  - [ ] Define Proxy API. This is the shape of data that Gloo will consume
  - [ ] Define LIstenerReport for new type. This is the type that is consumed by the validation webhook(and gloo plugins write to)
- [ ] Gloo translation
  - [ ] The name of the game here is re-use. We have a couple different ways of configuring HttpGateways, but at the end of the day they do the same thing with some slight modifications. The goal is to make the differences clear and obvious, and allow them to share the same code to reduce chances of drift
  - [ ] The exact work here will depend on whether code re-use is possible. I'm hopeful it is.
  - [ ] Extauth/ratelimit translators need to validate enterprise config
- [ ] End to end / regression tests
  - [ ] I think most functionality can/should be validated locally with specific logic we're adding, but I want some high level smoke tests that config is being processed the way we would expect. We can rely heavily on shared code not needing to be re-tested.
- [ ] CLI support
  - [ ] We'll likely need to update the CLI to support his new feature. At the very least for printing the proxy. Potentially other use cases.
- [ ] External docs outlining the feature, with the changelog including the NEW_FEATURE label
