### ISSUE TITLE
glooctl check fails with disabled default gateway proxies

### ISSUE THREAD

**Issue by NelsonJeppesen** [solo-io/gloo#5768]
### Gloo Edge Version

1.9.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

```
Glooctl check fails on proxies

❯ ./glooctl-linux-amd64 check -x pods -x upstreamgroup -x secrets -x gateways -x deployments
Checking deployments... OK
Checking upstreams... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking virtual services... OK
Checking proxies... Problem while checking for out of sync proxies
1 Errors!
Error: 1 error occurred:
        * timed out trying to connect to localhost during port-forward, errors: 120 errors occurred:
        * Get "http://localhost:34711/stats/prometheus": dial tcp [::1]:34711: connect: connection refused
        * Get "http://localhost:34711/stats/prometheus": dial tcp [::1]:34711: connect: connection refused
        * Get "http://localhost:34711/stats/prom
```

We don't deploy the default gateway proxies, use it only as a template for other gateway proxies using yaml anchors

relevant helm configuration that disables the default gateway proxy
```
...
  gatewayProxies:
    gatewayProxy: &gatewayRoot

      gatewaySettings: &gatewaySettings # yaml merge only works depth of 1
        disableGeneratedGateways: true
...
```

I can see it try and start a gateway proxy to a deployment that has zero pods
```
> ps axuf |grep kub
nelson     33566  0.3  0.2 752376 40944 pts/0    Sl+  14:39   0:00  |   |   |       \_ kubectl port-forward -n gloo-system deploy/gateway-proxy 34711:19000
```

### Steps to reproduce the bug

1. Dont have any default gateway proxies deployed
2. run glooctl check

### Expected Behavior

`glooctl check` should not try and connect to non-existent gateway pods

**Comment by Implausiblyfun** [comment]
I wonder if this is a case which would be best served by adding an option to glooctl check to ignore certain types of errors or skip certain checks.
In the most common case glooctl check detecting a lack of gateway implies that gloo is in a bad state.

Therefore it might be interesting if one could provide an optional flag denoting a glooctl component (proxy, upstream etc...) with which to treat all errors as warnings or perhaps to skip the check entirely. 

Something of the form: 
`glooctl check --ignore="proxy,auth"` (string slice flag for cobra https://github.com/spf13/pflag/blob/master/string_slice.go)

Could be interesting to consider how any signature / flag change could impact the following issues:
https://github.com/solo-io/gloo/issues/5462
https://github.com/solo-io/gloo/issues/5638

*Disclaimer*: This post was just off the cuff and may be non-useful.

**Comment by NelsonJeppesen** [comment]
> In the most common case glooctl check detecting a lack of gateway implies that gloo is in a bad state.

Could it be something like if desired size of statefulset/deployment == 0, simply flag a warning and move on to the other gateway?
