### ISSUE TITLE
GraphQLSchema resource client: list check failed: the server could not find the requested resource

### ISSUE THREAD

**Issue by jrauschenbusch** [solo-io/gloo#5771]
### Gloo Edge Version

1.10.x (beta)

### Kubernetes Version

1.20.x

### Describe the bug

```
{
  "level": "fatal",
  "ts": "2022-01-11TXX:XX:XX.XXXZ",
  "logger": "gloo",
  "caller": "setuputils/main_setup.go:73",
  "msg": "error in setup: creating base GraphQLSchema resource client: list check failed: the server could not find the requested resource (get graphqlschemas.graphql.gloo.solo.io)",
  "version": "1.10.0",
  "stacktrace": "github.com/solo-io/gloo/pkg/utils/setuputils.Main/workspace/gloo/pkg/utils/setuputils/main_setup.go:73\n\tgithub.com/solo-io/gloo/projects/gloo/pkg/setup.startSetupLoop/workspace/gloo/projects/gloo/pkg/setup/setup.go:22\n\tgithub.com/solo-io/gloo/projects/gloo/pkg/setup.Main/workspace/gloo/projects/gloo/pkg/setup/setup.go:14 \n\tmain.main/workspace/gloo/projects/gloo/cmd/main.go:14\n\truntime.main/usr/local/go/src/runtime/proc.go:225"
}
```

### Steps to reproduce the bug

Image update from `quay.io/solo-io/gloo:1.9.7` to `quay.io/solo-io/gloo:1.10.0`
Image update from `quay.io/solo-io/discovery:1.9.7` to `quay.io/solo-io/discovery:1.10.0`

### Expected Behavior

Pods are starting properly

**Comment by saiskee** [comment]
Hi @jrauschenbusch , thank you for opening a ticket.

You most likely have a typo in your schema crd, and we did change the api a bit in 1.10. Could you post the graphql schema crd? You can omit the schema definition, but I'm mostly interested in the structure and resolvers

**Comment by jrauschenbusch** [comment]
Hi @saiskee,

i'm using the Helm chart without that much modifications. You can load it from here:
https://storage.googleapis.com/solo-public-helm/charts/gloo-1.10.0.tgz

**Comment by saiskee** [comment]
Hi @jrauschenbusch ,
My misreading, I had mistaken the issue for another one.

iirc, helm upgrade does not install new CRDs, in this case the missing `graphqlschema` CRD. In order to do so, you'll have to manually install the crd, by running

```bash
kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.10.0/install/helm/gloo/crds/graphql_schema.yaml
```

**Comment by jrauschenbusch** [comment]
Thanks @saiskee. Install missing CRDs solved my issue.

**Comment by saiskee** [comment]
Sounds good @jrauschenbusch , I'll be adding this to the [gloo edge 1.10+ upgrade guide](https://docs.solo.io/gloo-edge/master/operations/upgrading/1.10.0/)
