### ISSUE TITLE
create debug images with the required options for profiling Envoy

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5779]
### Version

1.10.x (beta)

### Is your feature request related to a problem? Please describe.

Some users would like to profile Envoy, as explained on this page: https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md

### Describe the solution you'd like

enable "debug symbols and gperftools in the Envoy binary"

**Comment by chrisgaun** [comment]
This is more of a product issue because the debug image exposes Enterprise code.

**Comment by saiskee** [comment]
> Source code isn't obtainable from debug symbols. A skilled programmer could rewrite an application's logic given the debug symbols and a lot of time. 
https://stackoverflow.com/questions/5532415/obtain-source-using-debugging-symbols#:~:text=The%20easy%20answer%20is%20No%2C%20you%20can't.

**Comment by chrisgaun** [comment]
Oh. Got it. This should not be problem

**Comment by bewebi** [comment]
We are currently running into issues trying to create and release the debug image in Cloudbuild due too the increased space requirements of the debug issue (~2.4GB vs ~200MB)
Potential paths forward are:
- Attempt to modify the CI script to use fewer resources
- Allocate the required resources to the Cloudbuild

I'm not sure what the total requirements of the job are/will be, what the resource limit currently is, or how to modify it

**Comment by bewebi** [comment]
solo-io/envoy-gloo-ee#405 is open under review 
It adds steps in CI to build and release debug images that can be profiled for tagged releases

**Comment by nfuden** [comment]
Reopening to also provide envoy-wrapper images by default.

**Comment by nfuden** [comment]
We will only be backporting to 1.11 and only publishing on new releases

**Comment by gunnar-solo** [comment]
debug images are now available in `v1.12.18+`

**Comment by nfuden** [comment]
This should be available 1.11.41
