### ISSUE TITLE
Allow ability to set release in helm values for custom grafana / prometheus installation

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#5815]
### Version

1.11.x (beta)

### Is your feature request related to a problem? Please describe.

When global.glooStats.serviceMonitor=true it creates the PodMonitor gloo-component-podmonitor and ServiceMonitor gloo-component-servicemonitor. The metadata.labels.release defaults to prom. There needs to be a way to specify the release to match the release label on the external grafana/prometheus installation.

### Describe the solution you'd like

Ability to pass in the release label in the helm override values.

**Comment by sam-heilbron** [comment]
Per @kdorosh the ServiceMonitor doesn't yet support kube resource overrides: https://github.com/solo-io/solo-projects/blob/948ef569a36af64f99be2171ae57fba44220b2d1/install/helm/gloo-ee/templates/40-control-plane-servicemonitor.yaml#L24

Here's an example of a template that does: https://github.com/solo-io/solo-projects/blob/948ef569a36af64f99be2171ae57fba44220b2d1/install/helm/gloo-ee/templates/21-extauth-deployment.yaml#L139

It's probably worth it to expose this field directly as it could be a commonly used feature, but we may want to consider adding the kubeResourceOVerride for the ServiceMonitor to make our config more extensible.

**Comment by bewebi** [comment]
Is it sufficient to allow the user to specify a release name for the Pod and Service Monitors as opposed to having it populated automatically?
