### ISSUE TITLE
Ability to set location of where the custom dashboards are created for custom grafana / prometheus installation

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#5816]
### Version

1.11.x (beta)

### Is your feature request related to a problem? Please describe.

The custom dashboards are created in the General folder (defaultDashboardFolderId 0) with no way of setting it from helm values

### Describe the solution you'd like

Allow ability to specify the location of where the custom dashboard are create via helm override values.

**Comment by sam-heilbron** [comment]
@pszeto  This seems very related to: https://github.com/solo-io/gloo/issues/3920

The way you can configure this is using the [observability settings in our Settings CR](https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/settings.proto#L365). That allows you to define a custom folder.

You should then be able to specify as an annotation on individual upstreams, the subfolder: `observability.solo.io/dashboard_folder_id` I found this value here: https://github.com/solo-io/solo-projects/blob/84e7034ae086bd5b70b65877004a926eedb2bfe3/projects/observability/pkg/syncer/grafana_dashboard_syncer.go#L40

**Comment by pszeto** [comment]
@sam-heilbron Thanks.  I was able to verify #3920 should solve this issue.
