### ISSUE TITLE
glooctl: global flags not showing up in --help or docs

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#582]
https://github.com/solo-io/gloo/pull/579#discussion_r267594257

example:
`-n` (namespace shorthand) is a global, but it is not shown in the auto-gen docs:
https://gloo.solo.io/cli/glooctl_proxy/#options-inherited-from-parent-commands

**Comment by rickducott** [comment]
I tried moving -n to a top-level (so it would show up in `glooctl -h`) but realized:
- The flag should be described slightly differently for install/uninstall
- The flag isn't relevant to upgrade (which just upgrades the CLI)

#585

**Comment by rickducott** [comment]
(The linked PR will at least include it in the help for every subcommand)
