### ISSUE TITLE
Add a way to create or edit a gateway using glooctl

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#584]
Often enough, users will want to create new, non-standard listeners (other than port 80/443) for their TCP or HTTP traffic. In Gloo, Gateways are used to declare listeners in Envoy and specify bindPort. Additionally, they may want to change the default ports after deployment. We should support a `glooctl edit gateway ... ` and `glooctl create gateway --name foo --bindPort 8081` etc.

**Comment by ilevine** [comment]
related #209 #473 #470

**Comment by rickducott** [comment]
Closing as stale.
