### ISSUE TITLE
Gloo edge + istio expects istiod to be under istio-system

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#5848]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

It would be interesting to allow the chart to define where istiod is installed.

So far is it hardcoded to `istio-system` namespace.

Some of the customers have istio deployed in a different namespace

In the chart, at: `charts/gloo/templates/7-gateway-proxy-deployment.yaml`

You can find some place where istiod addess is hardcoded:
```
[...]
        - --discoveryAddress
        - istiod.istio-system.svc:15012
[...]
```
and:
```
[...]
          - name: CA_ADDR
            value: istiod.istio-system.svc:15012
[...]
```

### Describe the solution you'd like

A solution could be to add placeholders to the namespace as follows:
```
[...]
        - --discoveryAddress
        - istiod.{{ .Values.global.istioSDS.istioNamespace }}.svc:15012
[...]
```
and:
```
[...]
          - name: CA_ADDR
            value: istiod.{{ .Values.global.istioSDS.istioNamespace }}.svc:15012
[...]
```

That could be interpolated by a value like:
```
global:
  istioSDS:
    istioNamespace: istio-system # This value as default
```

**Comment by DuncanDoyle** [comment]
This has already been fixed: https://github.com/solo-io/gloo/blob/main/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L412-L420

Can be configured on the Gateway as such (example to connect to GME 2.5.5 IstioD):

```
gloo:
  gatewayProxies:
    gatewayProxy:
      istioDiscoveryAddress: "istiod-1-20.istio-system.svc:15012"
      istioMetaClusterId: gm-demo-single
```
