### ISSUE TITLE
Add hybridGateway values to the helm chart

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#5852]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

Right now you can only patch or edit a gateway to add a hybridgateway 

### Describe the solution you'd like

Expose helm values for the hybridGateway

### Additional Context

https://docs.solo.io/gloo-edge/latest/guides/traffic_management/listener_configuration/hybrid_gateway/

**Comment by chrisgaun** [comment]
@kevin-shelaga can you try out kubeoverrides

**Comment by kevin-shelaga** [comment]
I cannot get the kubeOverrides for these to work
