### ISSUE TITLE
go types missing for FederatedRateLimitConfigSpec and FederatedRateLimitConfigStatus

### ISSUE THREAD

**Issue by amiramw** [solo-io/gloo#5858]
It seems that FederatedRateLimitConfigSpec and FederatedRateLimitConfigStatus go types are not generated.

When using go client version: 
```
github.com/solo-io/solo-apis v0.0.0-20220103190243-814d851abdb0
```
I can see their protobuf def here: https://github.com/solo-io/solo-apis/blob/master/api/rate-limiter/v1alpha1/ratelimit.proto#L13

**Comment by jenshu** [comment]
this code is merged and backported to 1.10 and will be available in the next gloo 1.10 release
