### ISSUE TITLE
Support Proxy-Authorization HTTP Header on HTTP Connect Proxy 

### ISSUE THREAD

**Issue by pwoelfle** [solo-io/gloo#5859]
### Version

1.7.x

### Is your feature request related to a problem? Please describe.

We use the `httpProxyHostname` property on the Gloo `Upstream` to use a forward proxy, which works as expected (#3664).

Now, we need to also send the `Proxy-Authorization` HTTP Header during the HTTP Connect phase to access a secured forward proxy.

### Describe the solution you'd like

According to the [Envoy extensions.filters.network.tcp_proxy.v3.TcpProxy.TunnelingConfig](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#extensions-filters-network-tcp-proxy-v3-tcpproxy-tunnelingconfig) it would be possible by setting `headers_to_add`.

The Gloo `Upstream` resource would need to provide an according configuration which configures the mentioned Envoy configuration.

### Additional Context

**Example curl having no `Proxy-Authorization` HTTP header during HTTP Connect -> fail**
```
$> curl -v -x proxy.e2e-egreaytunnel6759f6b4dd65d7f7854d-36.svc.cluster.local:8080 http://test.e2e-egreaytunnel6759f6b4dd65d7f7854d-38.192.168.59.126.nip.io
*   Trying 10.108.118.77:8080...
* Connected to proxy.e2e-egreaytunnel6759f6b4dd65d7f7854d-36.svc.cluster.local (10.108.118.77) port 8080 (#0)
> GET http://test.e2e-egreaytunnel6759f6b4dd65d7f7854d-38.192.168.59.126.nip.io/ HTTP/1.1
> Host: test.e2e-egreaytunnel6759f6b4dd65d7f7854d-38.192.168.59.126.nip.io
> User-Agent: curl/7.76.1
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 407 Proxy Authentication Required
< Server: squid/4.13
< Mime-Version: 1.0
< Date: Tue, 01 Feb 2022 14:23:24 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 1963
< X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
< Vary: Accept-Language
< Content-Language: en
< Proxy-Authenticate: Basic realm="proxy"
< X-Cache: MISS from proxy-5774868874-7ts6j
< X-Cache-Lookup: NONE from proxy-5774868874-7ts6j:8080
< Via: 1.1 proxy-5774868874-7ts6j (squid/4.13)
< Connection: keep-alive
< 
...
``` 
**Example curl having a `Proxy-Authorization` HTTP header during HTTP Connect -> success**
```
$> curl -v -x test:secret123@proxy.e2e-egreaytunnel6759f6b4dd65d7f7854d-36.svc.cluster.local:8080 http://test.e2e-egreaytunnel6759f6b4dd65d7f7854d-38.192.168.59.126.nip.io
*   Trying 10.108.118.77:8080...
* Connected to proxy.e2e-egreaytunnel6759f6b4dd65d7f7854d-36.svc.cluster.local (10.108.118.77) port 8080 (#0)
* Proxy auth using Basic with user 'test'
> GET http://test.e2e-egreaytunnel6759f6b4dd65d7f7854d-38.192.168.59.126.nip.io/ HTTP/1.1
> Host: test.e2e-egreaytunnel6759f6b4dd65d7f7854d-38.192.168.59.126.nip.io
> Proxy-Authorization: Basic dGVzdDpzZWNyZXQxMjM=
> User-Agent: curl/7.76.1
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 01 Feb 2022 14:18:10 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 2
< X-Cache: MISS from proxy-5774868874-7ts6j
< X-Cache-Lookup: MISS from proxy-5774868874-7ts6j:8080
< Via: 1.1 proxy-5774868874-7ts6j (squid/4.13)
< Connection: keep-alive
< 
* Connection #0 to host proxy.e2e-egreaytunnel6759f6b4dd65d7f7854d-36.svc.cluster.local left intact
ok/ $ 
```

**Comment by chrisgaun** [comment]
Will talk to engineering.

**Comment by gsustek** [comment]
any news about that?

**Comment by gsustek** [comment]
Hi, any progress on that topic?

**Comment by kdorosh** [comment]
this is an easy feature to add / support by expanding this translation to include the `headers_to_add` field https://github.com/solo-io/gloo/blob/a0a2c016cbf9dbe56b910c1f8b0e42eca9de0f21/projects/gloo/pkg/plugins/tcp/plugin.go#L250

will mark this as a good first issue for new engineers we are onboarding. @gsustek would also be happy to work with you on a community contribution if you need this before product can prioritize this internally.

**Comment by pwoelfle** [comment]
Thanks for implementing HTTP proxy header support on TCP Config.

We also need to have the HTTP proxy headers on the `Upstream`.  I've just opened a pull-request for it: https://github.com/solo-io/gloo/pull/6946
