### ISSUE TITLE
Use opencensus tracer

### ISSUE THREAD

**Issue by snuggie12** [solo-io/gloo#5863]
### Version

1.9.x

### Is your feature request related to a problem? Please describe.

Due to the backend that was chosen we would like to output traces in W3C context. I noticed that the opencensus filter is on gloo so I was wondering if we could add a feature to the `Gateway` that allows us to use it.

### Describe the solution you'd like

Here is the envoy config that istio sets up. I'll comment on one thing where, if possible, I think it could be better:
```
        "tracing": {
            "http": {
                "name": "envoy.tracers.opencensus",
                "typedConfig": {
                    "@type": "type.googleapis.com/envoy.config.trace.v3.OpenCensusConfig",
                    "traceConfig": {
                        "constantSampler": {
                            "decision": "ALWAYS_PARENT"
                        },
                        "maxNumberOfAttributes": "200",
                        "maxNumberOfAnnotations": "200",
                        "maxNumberOfMessageEvents": "200",
                        "maxNumberOfLinks": "200"
                    },
                    "ocagentExporterEnabled": true,
                    "ocagentAddress": "dns:otel-collector.default.svc.cluster.local:55678",
                    # according to envoy documentation if you list multiples it is whatever is "found first"
                    # it'd be great if gloo offered the option to list different lists for incoming vs outgoing
                    # for instance, we'd like to have TRACE_CONTEXT and the zipkin ones for incoming
                    # but only the one currently listed for outgoing.
                    "incomingTraceContext": [
                        "TRACE_CONTEXT"
                    ],
                    "outgoingTraceContext": [
                        "TRACE_CONTEXT"
                    ]
                }
            }
        },
```

### Describe alternatives you've considered

One argument against this is supposedly people are working on getting open telemetry into envoy. honestly it's been like 2 years so I'm not sure we should keep waiting.

**Comment by murphye** [comment]
Related issue from Envoy:
https://github.com/envoyproxy/envoy/issues/9958

**Comment by jeffalder** [comment]
Yeah, I'd like to be able to use w3c trace_context instead of the zipkin headers as well; it would integrate better into our environment.

**Comment by snuggie12** [comment]
I believe this is completed and can be closed.
