### ISSUE TITLE
Envoy extension information in Edge docs

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#5905]
### Version

master

### Describe the requested changes

Gloo Edge currently does not display (leak?) information about Solo's envoy extensions in our docs.

This issue MUST decide a final location for the new security posture docs which are generated and validated in our repositories.

This issue MAY decide if there is anything else that should be brought in (underlying envoy version being relied on?)

Envoyproxy itself exposes their security posture yaml in a docs view like the following: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/threat_model 
which is based off a similar yaml
https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_metadata.yaml

### Link to any relevant existing docs

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/threat_model 

### Additional Context

This may not be purely a docs issue and there has been some discussion started in the gloo-edge group internally. 

Yuval has a PDF.

**Comment by Rachael-Graham** [comment]
For:
> This issue MAY decide if there is anything else that should be brought in (underlying envoy version being relied on?)

see discussion in https://github.com/solo-io/gloo/pull/5906/files#r803052638 about whether to add the underlying version of Envoy to the supported versions reference page in the docs

**Comment by chrisgaun** [comment]
@sam-heilbron is there a reason we couldn't mirror this Envoy security posture to a public repo?

**Comment by nfuden** [comment]
We could mirror it over it just means that we are segmenting the posture from the code which means it is more easily able to become unsynced. 
Either way this issue is not just for linking and publicizing our private extensions but also the extensions that we have in envoy-gloo (OSS extensions)

**Comment by kcbabo** [comment]
@Nadine2016 this came up again in a customer call today to get the security posture documentation at a public (or private if needed) URL. Do we plan on publishing this in our docs and updating it with each release?

**Comment by artberger** [comment]
OSS: https://github.com/solo-io/envoy-gloo/blob/master/security_posture.yaml
EE: https://github.com/solo-io/envoy-gloo-ee/blob/master/security_posture.yaml

**Comment by kcbabo** [comment]
Confirmed with Yuval that we are good to publish this info in our docs.

**Comment by artberger** [comment]
Right now, we manually combined the OSS and Enterprise files together to publish in the doc. We might want a follow-up issue to look into automating the update of these for future releases. https://docs.solo.io/gloo-edge/master/reference/security-posture/
