### ISSUE TITLE
v1.10.4 - missing Gloo ACK/NACK metrics

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5910]
### Gloo Edge Version

1.10.x (latest stable)

### Describe the bug

With Gloo EE v1.10.4 and a valid enterprise license, I cannot see the prometheus metrics starting with:
- `glooe_solo_io_xds_insync`
- `glooe_solo_io_xds_total_entities`

### Steps to reproduce the bug

```shell
cat > values.yaml <<EOF
gloo:
  gloo:
    logLevel: debug
EOF

# GLOO EDGE
GLOO_VERSION=1.10.4
helm upgrade -i gloo glooe/gloo-ee --namespace gloo-system --version ${GLOO_VERSION} \
  --create-namespace --set-string license_key="$LICENSE_KEY" -f values.yaml

```

### Expected Behavior

these metrics exposed

### Additional Context

works with v1.10.3 and before

**Comment by sam-heilbron** [comment]
Thanks for raising this! The linked PRs should resolve this behavior. They are not yet released, but the fix will be included in v1.10.5
