### ISSUE TITLE
Support Envoy "Dynamic forward proxy" HTTP filter

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5920]
### Version

1.11.x (beta)

### Is your feature request related to a problem? Please describe.

The goal is to expose this HTTP filter: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/dynamic_forward_proxy/v3/dynamic_forward_proxy.proto
 
The context is running Gloo Edge as a forward proxy.

_EDIT_: additional documentation: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter

**Comment by kdorosh** [comment]
on LTS branch 1.10 and 1.11 beta, will be picked up in next regular release
