### ISSUE TITLE
Changing log levels in control plane pods returns ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#5934]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.21.x

### Describe the bug

Changing log levels in control plane pods via either curl or from web console appears to fail with an empty reply from server message. I tested this with gloo, discovery, and gateway deployments. It appears that the changes were applied, but the response is quite confusing. Contrast this with performing the same operation on `gateway-proxy`, which returns a reasonable message with a `200 OK` response code.

### Steps to reproduce the bug

1. Set up port-forward for any of these control plane pods:
```
kubectl port-forward -n gloo-system deploy/gloo 9091:9091
kubectl port-forward -n gloo-system deploy/discovery 9091:9091
kubectl port-forward -n gloo-system deploy/gateway 9091:9091
```
2. Attempt a curl to change log level on any of above pods. Observe the error response. Note that the log level change actually took effect.
```
% curl -X PUT http://localhost:9091/logging -d '{"level":"debug"}' -H "Content-Type: application/json" -i
curl: (52) Empty reply from server
```
3. Observe the same behavior from the web console at http://localhost:9091:
![Screen Shot 2022-02-16 at 9 58 55 AM](https://user-images.githubusercontent.com/52334260/154299898-8d8df613-f982-4525-937b-1fb289a44cea.png)

### Expected Behavior

Respond like the same operation on `gateway-proxy`, which returns a reasonable message with a `200 OK` response code.

**Comment by sam-heilbron** [comment]
Related to: https://github.com/solo-io/gloo/issues/6449
