### ISSUE TITLE
certgen waits for cert to be expired for renewing it

### ISSUE THREAD

**Issue by dguihal** [solo-io/gloo#5944]
### Gloo Edge Version

1.10.x (latest stable)

### Describe the bug

We are facing some issues about gloo internal cert being expired ...

Looking at code, looks like certgen is waiting the cert to be effectively expired before renewing it 

https://github.com/solo-io/gloo/blob/a6e02607c5d6c9a458388f707c881345a0554eab/jobs/pkg/run/run.go#L72

https://github.com/solo-io/gloo/blob/a6e02607c5d6c9a458388f707c881345a0554eab/jobs/pkg/kube/secret.go#L59

As it is run as a cronjob, it means that during a timeframe (depending on cronjob frequency) cert is effectively expired .....

### Steps to reproduce the bug

1. Instanciate a cert using certgen as a cronjob
2. Wait for expiration date
3. Enjoy having an expired cert while waiting for the cronjob to run

### Expected Behavior

I would expect such tool to renew cert before expiration (at least one day before but preferably a configurable date as it will also depend on cronjob run frequency)

**Comment by DiegoLelis** [comment]
+1
