### ISSUE TITLE
Federation of HTTP Gateways

### ISSUE THREAD

**Issue by guydc** [solo-io/gloo#5948]
### Version

1.10.x 

### Is your feature request related to a problem? Please describe.

Use Gloo Federation to manage `MatchableHTTPGateway` resources across multiple clusters. 

### Describe the solution you'd like

Introduce relevant federated Protos, CRDs, K8s Client Go types and Gloo Fed placement logic.

**Comment by sam-heilbron** [comment]
Released in Gloo Enterprise 1.11.8. The 1.12 beta release will be out tomorrow.
