### ISSUE TITLE
customEnv is not working for rateLimit deployment

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5954]
### Gloo Edge Version

1.11.x (beta)

### Kubernetes Version

1.21.x

### Describe the bug

In the helm documentation, it is said that you can define [customEnv](https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/enterprise_helm_chart_values/) in rateLimit.

Inspecting the Chart, this was probably removed at some point, causing a regression issue.

### Steps to reproduce the bug

Render gloo chart with these defined:
```
rateLimit.deployment.customEnv[].name
rateLimit.deployment.customEnv[].value
```

And in the result you can see they are ignored

### Expected Behavior

I would like `customEnv` to be introduced back in the ratelimit deployment.

**Comment by sam-heilbron** [comment]
This should be resolved by the most recent Gloo EE releases: 1.10.12, 1.11.0-beta13
