### ISSUE TITLE
allow gloo ingress ctl to read ingresses without annotation

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#598]
currently all ingresses require the k8s ingress class annotation `gloo`

we should enable providing a flag to disable the annotation requirement. this feature has been requested at least twice in our slack channel

**Comment by rettori** [comment]
What's the disadvantage of doing this?

**Comment by sauber** [comment]
My preference is for gloo by default to process all ingress objects. A flag, presences of selectors or rbac access rules can limit selection. Logging justification for processing or discarding ingress objects would help troubleshooting.

**Comment by christian-posta** [comment]
This is a dup of https://github.com/solo-io/gloo/issues/507

**Comment by ilevine** [comment]
closing as duplicate
