### ISSUE TITLE
Update helm apiVersion to v2

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#5984]
### Version

1.9.x 1.10.x

### Is your feature request related to a problem? Please describe.

Update helm apiVersion to v2

### Describe the solution you'd like

The apiVersion field should be v2 for Helm charts that require at least Helm 3. Charts supporting previous Helm versions have an apiVersion set to v1 and are still installable by Helm 3.

### Additional Context

https://helm.sh/docs/topics/charts/#the-apiversion-field

**Comment by nrjpoddar** [comment]
@chrisgaun should we backport this to 1.9/1.10?

**Comment by chrisgaun** [comment]
no need to backport
