### ISSUE TITLE
AWS Lambda filter does not pass headers to function as expected

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#5985]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.21.x

### Describe the bug

The AWS Lambda filter does not pass headers to the function as expected, even with `requestTransformation` enabled on the Lambda `DestinationSpec`.

### Steps to reproduce the bug

1. Unpacked attached [zip](https://github.com/solo-io/gloo/files/8145002/lambda-fail.zip).
2. Install httpbin upstream
`kubectl apply -f httpbin-us.yaml`
3. Install aws upstream (supply credentials in secret `aws-creds`)
`kubectl apply -f upstream-aws.yaml`
4. Install VS with 3 routes: one with `requestTransformation: true`, one with `requestTransformation: false`, and one that routes to httpbin.
`kubectl apply -f vs-lambda-test.yaml`
5. Verify by curling httpbin route that both `foo` and `hdr1` headers are being passed from Edge to upstream (as expected).
```
% curl -H "hdr1: val1" $(glooctl proxy url)/get | jq
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Foo": "bar",
    "Hdr1": "val1",
    "Host": "35.185.51.108",
    "User-Agent": "curl/7.77.0",
    "X-Amzn-Trace-Id": "Root=1-62194e2d-24361aa956187c865025bedf",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  },
  "origin": "35.229.21.123",
  "url": "http://35.185.51.108/get"
}
```
6. Verify by curling no-transform route that both `foo` and `hdr1` headers are NOT being passed from Edge to upstream (as expected).
```
% curl -H "hdr1: val1" $(glooctl proxy url)/noxdump | jq
{
  "statusCode": 200,
  "eventDump": "{}",
  "body": "null",
  "headers": "null"
}
```
7. Verify by curling `requestTransform` route that both `foo` and `hdr1` headers are NOT being passed from Edge to upstream (NOT as expected). The `httpMethod`, `path`, and `queryString` are present as expected.
```
% curl -H "hdr1: val1" $(glooctl proxy url)/dump | jq
{
  "statusCode": 200,
  "eventDump": "{\"httpMethod\": \"GET\", \"path\": \"/dump\", \"queryString\": \"\"}",
  "body": "null",
  "headers": "null"
}
```

### Expected Behavior

Request headers are passed to the Lambda function.

### Additional Context

```
% glooctl version
Client: {"version":"1.10.0"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.10.1","Name":"discovery-ee","Registry":"quay.io/solo-io"},{"Tag":"1.10.1","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.10.1","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.10.1","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.10.1","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.10.1","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"1.10.1","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"6.2.4","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```

**Comment by ben-taussig-solo** [comment]
Update: 
After debugging this with @jameshbarton, we discovered that the issue seems to only occur on enterprise. In other words, the feature works as expected on Gloo OSS v1.10.1, but does not work on Gloo Enterprise (tested on Enterprise v1.10.4).

**Comment by kdorosh** [comment]
we suspect we may want another transformation stage for lambda itself since it uses transformations, thus configured transformations may override the ones lambda uses

we should be able to validate with e2e. it only appears to happen in enterprise
