### ISSUE TITLE
gloo eds only watches upstreams in the configured writeNamespace

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#599]
currently `StartEds` takes a namespace argument, which begins a separate watch for upstreams for which gloo will do EDS

need to change this to `""` 
very tiny change, but should be e2e tested

relevant line: 

https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/syncer/setup_syncer.go#L262

**Comment by yuval-k** [comment]
fixed by #600
