### ISSUE TITLE
discovery missing service

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#5990]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

We expose ports for serviceMonitor but we do not have a service for discovery

### Steps to reproduce the bug

https://github.com/solo-io/gloo/blob/f9ee6d90dd9e1f1a3a4ffe2a35966be21d400742/install/helm/gloo/templates/3-discovery-deployment.yaml#L92

### Expected Behavior

We should have a service

**Comment by sam-heilbron** [comment]
This should be resolved by the most recent releases:
Gloo OSS 1.10.14, 1.11.0-beta18
Gloo EE 1.10.12, 1.11.0-beta13
