### ISSUE TITLE
Use ServiceMonitors without exposing envoy metrics externally

### ISSUE THREAD

**Issue by guydc** [solo-io/gloo#5992]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

When service monitors are enabled, the gateway-proxy service exposes port 8081 for scraping purposes: https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/8-gateway-proxy-service.yaml#L76

As a result, the metrics endpoint is also exposed externally. It should be possible to scrape envoy metrics using Prometheus scraping best practices, without exposing metrics externally. 

### Describe the solution you'd like

Create a dedicated ClusterIP service for gateway-proxy which is used for scraping, instead of exposing additional ports in the LB service. 

### Describe alternatives you've considered

Use pod monitors instead of service monitors. Enablement of Service and Pod Monitors should be decoupled with dedicated helm chart flags.

**Comment by chrisgaun** [comment]
Related issue https://github.com/solo-io/gloo/issues/6041

**Comment by sam-heilbron** [comment]
This should be resolved by the most recent releases:
Gloo OSS 1.10.14, 1.11.0-beta18
Gloo EE 1.10.12, 1.11.0-beta13
