### ISSUE TITLE
support merging config for discovered upstreams 

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#6005]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

Currently the feature that allows customizing discovered upstreams via the `gloo.solo.io/upstream_config` annotation (#3717 ) only supports overwriting top-level upstream fields.

e.g., providing the following annotation
```
 annotations:
    gloo.solo.io/upstream_config: |
      {
        "kube": {
          "service_spec": {
            "rest": {
              "swagger_info": {
                "url":"http://example.com"
              }
            }
          }
        }
      }
```
causes the whole `kube` field in the resulting upstream to be replaced with the above, essentially removing all the other kube fields and resulting in an invalid upstream.

### Describe the solution you'd like

We should support merging the provided config with the existing upstream fields instead of overwriting. Perhaps we can provide an option for whether to overwrite or merge?

### Additional Context

code for the [general annotation converter](https://github.com/solo-io/gloo/blob/eecf63a93c19303886dd1fa827cdb6c11ca716bf/projects/gloo/pkg/plugins/kubernetes/serviceconverter/general_annotation_converter.go)

**Comment by nrjpoddar** [comment]
Talked with @ben-taussig-solo and the comment above is inaccurate as he hadn't escaped the annotation key with quotes.

This is working as expected. cc @chrisgaun

**Comment by nrjpoddar** [comment]
@ben-taussig-solo should this be closed?

**Comment by ben-taussig-solo** [comment]
@nrjpoddar No -- The issues with the original implementation of the feature have been resolved [here (master)](https://github.com/solo-io/gloo/pull/6094) and [here (v1.10.x)](https://github.com/solo-io/gloo/pull/6096), but I am going to add a couple of kube2e tests so we can be confident that the issue will not reappear in the case that expected  annotation keys change in the future.

**Comment by sam-heilbron** [comment]
@ben-taussig-solo lets regroup around this on Wednesday and make a plan
