### ISSUE TITLE
Cannot use trusted mode upstream tls with only rootca

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#6021]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

When setting up upstream tls with trusted mode if you follow the docs, only the rootca should be required. But this causes the following error:

```
* Found upstream with warnings by 'gloo-system': gloo-system upstream-esb-monolith (Reason: warning: 
  1 error occurred:
	* name:"globalsign-s3-ca"  namespace:"gloo-system" is not a valid TLS secret: tls: failed to find any PEM data in certificate input
```

### Steps to reproduce the bug

https://docs.solo.io/gloo-edge/latest/guides/security/tls/client_tls/#trusted-mode

### Expected Behavior

you should only need to create the secret with the rootca

### Additional Context

work around: create the secret with rootca and privatekey and certchain

**Comment by sam-heilbron** [comment]
Some hopefully helpful slack context: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1647557352349749?thread_ts=1647550047.305449&cid=CEDCS8TAP

**Comment by chrisgaun** [comment]
Another customer is also experiencing this
