### ISSUE TITLE
AWS Lambda invocations intermittently fail with 403 Forbidden errors

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#6023]
### Gloo Edge Version

1.10.x (latest stable)

### Describe the bug

A customer is experiencing intermittent `403 Forbidden` failures in Virtual Services that delegate to AWS Lambda functions.

This occurred on a 1.10.6 pod that was running for many hours, started intermittently not sending the token and getting an AWS missingToken error. Cleansed customer logs from this episode are [attached](https://github.com/solo-io/gloo/files/8187133/d14e-lambda-token-fail.txt).

From @nfuden : "It's a new error and still in the realm of eks specific authentication.  ... This one is our envoy code seems to sometimes be sending without an auth token which might actually reproducible and also may point to an implementation error which could plausibly be caught with integration tests."

### Steps to reproduce the bug

See attached logs.

### Expected Behavior

Auth token shouldn't be dropped. Properly credentialed Lambda requests should always succeed.

### Additional Context

Internal Slack References:
https://solo-io.slack.com/archives/G0133U4GUP5/p1645797195466269
https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1645796595381049

**Comment by nfuden** [comment]
Merged into 1.11.0-beta15 as part of the envoy bump
