### ISSUE TITLE
Docs: Expand GraphQL section

### ISSUE THREAD

**Issue by Rachael-Graham** [solo-io/gloo#6057]
### Version

master

### Describe the requested changes

Continue expansion of GraphQL docs to include more examples; info about stitching, caching, and other features; debugging; UI; and more.

### Link to any relevant existing docs

Placeholder files:
[graphql_ui.md](https://github.com/solo-io/gloo/files/8216456/graphql_ui.md)
[debugging.md](https://github.com/solo-io/gloo/files/8216458/debugging.md)
[caching.md](https://github.com/solo-io/gloo/files/8216459/caching.md)
[observability.md](https://github.com/solo-io/gloo/files/8216460/observability.md)
[stitching.md](https://github.com/solo-io/gloo/files/8216461/stitching.md)

Requests for doc/doc outline: https://docs.google.com/document/d/1gnmwVYXC7iBGJf-NGA8c4cEdG42jykVs96z0LTSPCFk/edit#

Introduction talk slides, for adding more conceptual info and deployment patterns: https://docs.google.com/presentation/d/1RPLXW5_1MKqltpQXQCT1z1qsp2lCF-OEH1AkN4w2l0o/edit#slide=id.g10a8760f3dd_24_181

Hands-on talk slides, for expanding stitching and examples: https://docs.google.com/presentation/d/1ArxEdVVAOowz4wYcXIYlg4Wd-psadUTrOYH9DPPWwpk/edit#slide=id.g10a8760f3dd_24_181

Hand-on demo recording: https://drive.google.com/file/d/1tMiOCecshV69aYOaV_ZKnKD8R-greeG3/view

UI demo: https://drive.google.com/drive/folders/1RnHCx1diNebjZ2nShFjstTe_Xord56hE

**Comment by artberger** [comment]
Follow-up issue for stitching: https://github.com/solo-io/gloo/issues/6246
