### ISSUE TITLE
Expose local rate limit filter in gloo

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#6076]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

A found a case with a customer that wants to implement RL based on capacity, not time.

Having a token approach is preferable on some use cases because it allows us to handle bursts regardless of how fast they show up, while still preventing resource exhaustion. We can then tune how much we let through, and how much we fail, unlike the normal rate limit which is a set amount per time unit.

### Describe the solution you'd like

I would like to have [Local rate limit](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#local-rate-limit) exposed in gloo.

**Comment by bcollard** [comment]
got a new demand for this capability, where the client is doing some sort of reverse exponential back-off and overflowing the gateway. Having a local rate-limiter would help protect the proxy and upstream services.
+1 for exposing the Envoy local rate-limiter.

**Comment by guydc** [comment]
Local rate limit is a resource-efficient and performant mechanism for protection against client misbehavior (as opposed to global rate limiting with all of its requirements). 
I'm also interested in this capability.

**Comment by davidjumani** [comment]
Added as part of OSS gloo [v1.16.0-beta8](https://github.com/solo-io/gloo/releases/tag/v1.16.0-beta8)
Merged into enterprise and will be released as part of v1.16.0
