### ISSUE TITLE
vendor and generate protobufs

### ISSUE THREAD

**Issue by yuval-k** [solo-io/gloo#608]
we need to find a way to vendor protobufs:
- we currently need to checkout other repos in the go path for our proto generation with solokit to work
- prevents us from using Any for envoy config as our filter protos are vendoring in manually
- #234 

I started working on a solution in the gomod branch of gloo and solo-kit. hoping to have something soon-ish.

**Comment by ilevine** [comment]
We can use a similar approach as was used in loop:
create a 'fake' go path and use solo-kit to generate code as before.

closing as solved.
