### ISSUE TITLE
Randomly getting upstream connect error or disconnect/reset before headers. reset reason: overflow

### ISSUE THREAD

**Issue by benishak** [solo-io/gloo#609]
Hi

I retested Gloo today again with 3.6M+ rpm and after a while I noticed our application started logging less requests but it was going up and down

Start time: 14:40
![Screen Shot 2019-03-26 at 16 34 11](https://user-images.githubusercontent.com/5909357/55010774-17634e80-4fe5-11e9-8777-979c0d67c177.png)

I checked if there are errors or packets being dropped in the network but everything looked ok
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 12:b4:49:66:4c:38 brd ff:ff:ff:ff:ff:ff
    RX: bytes  packets  errors  dropped overrun mcast   
    94216675441 289621682 0       0       0       0       
    TX: bytes  packets  errors  dropped carrier collsns 
    103489900003 281006582 0       0       0       0     
```

so I used curl to send request via Gloo/Envoy and it was flickering between valid response and this error
```
upstream connect error or disconnect/reset before headers. reset reason: overflow
```

I couldn't see anything in the logs of gloo or gateway-proxy

**Virtual Services**

```
glooctl get vs -o yaml
---
metadata:
  name: default
  namespace: gloo-system
  resourceVersion: "29529432"
sslConfig:
  secretRef:
    name: my-tls
    namespace: gloo-system
status:
  reportedBy: gateway
  state: Accepted
  subresourceStatuses:
    '*v1.Proxy gloo-system gateway-proxy':
      reportedBy: gloo
      state: Accepted
virtualHost:
  domains:
  - '*'
  name: gloo-system.default
  routes:
  - matcher:
      prefix: /request.adapter.php
    routeAction:
      single:
        upstream:
          name: incoming-mediation
          namespace: gloo-system
  - matcher:
      prefix: /requestadapter
    routeAction:
      single:
        upstream:
          name: incoming-mediation
          namespace: gloo-system
  - matcher:
      prefix: /
    routeAction:
      single:
        upstream:
          name: default-auctioncore-8081
          namespace: gloo-system

---
displayName: http
metadata:
  name: http
  namespace: gloo-system
  resourceVersion: "29529433"
status:
  reportedBy: gateway
  state: Accepted
  subresourceStatuses:
    '*v1.Proxy gloo-system gateway-proxy':
      reportedBy: gloo
      state: Accepted
virtualHost:
  domains:
  - '*'
  name: gloo-system.http
  routes:
  - matcher:
      prefix: /request.adapter.php
    routeAction:
      single:
        upstream:
          name: incoming-mediation
          namespace: gloo-system
  - matcher:
      prefix: /requestadapter
    routeAction:
      single:
        upstream:
          name: incoming-mediation
          namespace: gloo-system
  - matcher:
      prefix: /
    routeAction:
      single:
        upstream:
          name: default-auctioncore-8081
          namespace: gloo-system
```

**Upstreams**

```
---
discoveryMetadata: {}
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"auctioncore"},"name":"auctioncore","namespace":"default"},"spec":{"ports":[{"name":"auctioncore","port":8081,"protocol":"TCP"}],"selector":{"app":"auctioncore"},"type":"NodePort"}}
  labels:
    app: auctioncore
    discovered_by: kubernetesplugin
  name: default-auctioncore-8081
  namespace: gloo-system
  resourceVersion: "22700664"
status:
  reportedBy: gloo
  state: Accepted
upstreamSpec:
  kube:
    selector:
      app: auctioncore
    serviceName: auctioncore
    serviceNamespace: default
    servicePort: 8081

---
metadata:
  name: incoming-mediation
  namespace: gloo-system
  resourceVersion: "26771579"
status:
  reportedBy: gloo
  state: Accepted
upstreamSpec:
  static:
    hosts:
    - addr: nvirginia-my-xxxxxxx.us-east-1.elb.amazonaws.com
      port: 80
```

After I switched off the traffic from Envoy/Gloo and retested with curl, they stopped being flickering, all requests were OK

so this seems to happen only on heavy load.

CPU usage was around 20%
Load was around 8.0
Machines: 4 x (36 CPU, 96 GB RAM)

**Comment by yuval-k** [comment]
Overflow means `The stream was reset because of a resource overflow` essentially I believe you tripped the envoy circuit breakers on the upstream cluster.
These circuit breakers are built in envoy to helm prevent cascading failures - the default value for the limit that you hit `maximum pending requests`, is 1024.  and when that limit hits, its starts to shed load (i.e. returning reset reason overflow). see more info [here](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/circuit_breaker.proto#envoy-api-msg-cluster-circuitbreakers)

IIRC, you need this limit to be customizable to a higher value?
Do you think this setting is something you would configure globally, or set this per upstream?

**Comment by benishak** [comment]
that makes sense!
we need to configure globally

**Comment by benishak** [comment]
is there a way for now to configure it with Gloo? it is cluster configuration, so this information need to be provided by the xDS (gloo in this case)

**Comment by yuval-k** [comment]
yes it is via xDS - I am actually doing some work in that area, so i think can add an ability to configure that today\tomorrow;
any other things that you think you might need to fine tune?

**Comment by benishak** [comment]
sounds good, thanks!
allowing configuring tls/ssl ciphers and versions if this is not implemented
add docs for configuring the HCM (#pull/596)

**Comment by yuval-k** [comment]
just created a PR for the settings.
I've made it so you can specify a global default and override it in the upstream.
we plan to have a docs effort soon, so the docs will improve in general very soon.

**Comment by yuval-k** [comment]
@benishak feel free to look at the PR and let me know if there's anything missing

**Comment by benishak** [comment]
great! thank you, looking forward for the new release

**Comment by yuval-k** [comment]
[v0.13.3](https://github.com/solo-io/gloo/releases/tag/v0.13.3) was released that contains the circuit breaker settings.
to configure a global policy, use settings similar to this:
```
kind: Settings
metadata:
  name: default
  namespace: gloo-system
spec:
  bindAddr: 0.0.0.0:9977
  circuitBreakers:
    maxConnections: 2048
    maxPendingRequests: 2048
    maxRequests: 2048
```
(note the **circuitBreakers** part on the bottom; will add this to the official docs shortly)

**Comment by rettori** [comment]
Hi @benishak, while talking to Yuval about this, we think that it will be a good addition for you if you can place an alert on based on a header presence.

Envoy sets the header ```x-envoy-overloaded``` on the downstream response if a request was dropped due to either maintenance mode or upstream circuit breaking, which was your case.

This feels like a decent enough alert to have which indicates that the system might not be operating at an optimal level and might require attention.

**Comment by benishak** [comment]
@rettori good hint! thank you
