### ISSUE TITLE
OIDC - mark the client_secret as optional to support OAuth2 for native apps

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6095]
### Is your feature request related to a problem? Please describe.

When using public client apps (mobile apps, SPA, etc.) there is no notion of `client_secret` since it cannot be safely stored. The client is identified with its `client_id`. Also, to protect the client App from [authorization code interception, it is recommended](https://datatracker.ietf.org/doc/html/rfc8252#section-8.1) to implement [PKCE](https://datatracker.ietf.org/doc/html/rfc7636).

With an API Gateway in the mix and from what we've seen in the field, client Apps will initiate the flow with the authorization request and the `code_challenge` (PKCE) directly to the Authorization Server.

Once the Authz server returns an `authorization code`, then the Client app will go through Gloo Edge and hook into the callback function with the `authorization code` and also the `code_verifier` (PKCE). In this case, the ExtAuth server should not try to use the `client_secret` but only the `client_id` and also the `code_verifier` sent by the Client app, to reach the Authorization server on the token endpoint.

I don't have details on this technique and I don't know if hooking into this callback function at the gateway/extauth level is really possible and if there are any other side effects (perhaps with the `state` JWT?)

Does this seem reasonable?

_EDIT: the goal was to have Gloo store the tokens in Redis, instead of having the tokens in the Client app / browser.
Another valid flow would be the Client app to call both the authz endpoint and the token endpoint (with PKCE parameters) and to store the `access_token` + `id_token` on local storage. Our customer wanted to avoid that from a security standpoint, by leveraging the Redis cache.

**Comment by elcasteel** [comment]
Blocked by the fact that I can't configure oauth2 on ToT: https://github.com/solo-io/solo-projects/issues/5072

**Comment by elcasteel** [comment]
This is merged to 1.15 and 1.14
