### ISSUE TITLE
[ci test flake] Gateway in memory hybrid gateway tcp ssl [It] should work with ssl 

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#6108]
### Gloo Edge Version

1.11.x (beta)

### Describe the bug

example logs:

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=f7ae4c3f-cdcb-40ef-8fbf-3ffef13923d8

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=9f775840-517a-460f-aa92-1484e6904a25

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=4dd7e49e-7782-4d7f-a6e8-2d60ce747b52

failure on different ssl test but possibly related?

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=89162e79-f7b5-40d5-88e7-cfaf3b4ad3ae

### Steps to reproduce the bug

This often occurs during test runs in ci

### Expected Behavior

Tests should pass consistently

**Comment by sam-heilbron** [comment]
[Fail] Gateway in memory hybrid gateway http traffic ssl [It] should work with ssl if ssl config is present in matcher

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=b8084cee-0ab4-4813-b3bc-ede82a332f8a

**Comment by sam-heilbron** [comment]
[Fail] Gateway in memory hybrid gateway http traffic ssl [It] should work with ssl if ssl config is present in matcher

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=fbb1c719-930b-43b4-883b-475b13b4199c

**Comment by MitchAman** [comment]
[Fail] Gateway in memory hybrid gateway http traffic ssl [It] should work with ssl if ssl config is present in matcher

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=cc98c058-a286-486d-b0a1-ef900bdc76e6

**Comment by inFocus7** [comment]
[Fail] Gateway in memory hybrid gateway http traffic ssl [It] should work with ssl if ssl config is present in matcher

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=d1cbc61a-edad-42de-9987-31b4113e9433

**Comment by inFocus7** [comment]
[Fail] Gateway in memory hybrid gateway http traffic ssl [It] should work with ssl if ssl config is present in matcher

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=d5ac559c-a5db-489c-bcc1-fa5f416c4dc1

**Comment by jackstine** [comment]
[Fail] Gateway in memory hybrid gateway tcp ssl [It] should work with ssl 
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=36c82413-9143-4df5-a1bb-d7ce79844fdd

**Comment by jackstine** [comment]
[Fail] Gateway in memory tcp gateway ssl [It] should work with ssl 
https://storage.googleapis.com/solo-public-build-logs/log-766853cb-0e77-4199-8d0e-ac9d8f418294.txt

**Comment by ashishb-solo** [comment]
hit this again here: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=1ecbeefc-2bf9-4d56-8173-d6626880f33e

```
Step #10 - "test": Gateway in memory tcp gateway ssl [It] should work with ssl 
Step #10 - "test": /workspace/gloo/test/e2e/gateway_test.go:696
Step #10 - "test": 
Step #10 - "test":   Unexpected error:
Step #10 - "test":       <*errors.resourceVersionErr | 0xc00cb66940>: {
Step #10 - "test":           namespace: "gloo-system",
Step #10 - "test":           name: "gateway-tcp",
Step #10 - "test":           given: "2",
Step #10 - "test":           expected: "3",
Step #10 - "test":       }
Step #10 - "test":       invalid resource version gloo-system.gateway-tcp given 2, expected 3
Step #10 - "test":   occurred
Step #10 - "test": 
Step #10 - "test":   /workspace/gloo/test/e2e/gateway_test.go:734
Step #10 - "test": 
Step #10 - "test":   Full Stack Trace
Step #10 - "test":   github.com/solo-io/gloo/test/e2e_test.glob..func14.3.3.5.5()
Step #10 - "test":   	/workspace/gloo/test/e2e/gateway_test.go:734 +0xcc5
Step #10 - "test":   github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc000a2b020)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113 +0xf6
Step #10 - "test":   github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc000a2b020)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64 +0x158
Step #10 - "test":   github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc0000ff5e0)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/it_node.go:26 +0x95
Step #10 - "test":   github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc0017f5b30, 0x0?, {0x7085f60, 0xc0002d2640})
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:215 +0x35a
Step #10 - "test":   github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc0017f5b30, {0x7085f60, 0xc0002d2640})
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:138 +0x1ac
Step #10 - "test":   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc000c76b00, 0xc0017f5b30)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:200 +0x15b
Step #10 - "test":   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc000c76b00)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:170 +0x256
Step #10 - "test":   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000c76b00)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:66 +0x137
Step #10 - "test":   github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0002cba40, {0x7fb4101e9028, 0xc000d031e0}, {0x63bee71, 0x9}, {0xc0012f3100, 0x2, 0x2}, {0x70c72f0, 0xc0002d2640}, ...)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79 +0x6f6
Step #10 - "test":   github.com/onsi/ginkgo.runSpecsWithCustomReporters({0x7093a40?, 0xc000d031e0}, {0x63bee71, 0x9}, {0xc0012f30e0, 0x2, 0x63e96ee?})
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245 +0x213
Step #10 - "test":   github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters({0x7093a40, 0xc000d031e0}, {0x63bee71, 0x9}, {0xc0000eee88?, 0x1, 0x1})
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:228 +0x258
Step #10 - "test":   github.com/solo-io/gloo/test/e2e_test.TestE2e(0x0?)
Step #10 - "test":   	/workspace/gloo/test/e2e/e2e_suite_test.go:47 +0x2fb
Step #10 - "test":   testing.tRunner(0xc000d031e0, 0x650fef0)
Step #10 - "test":   	/usr/local/go/src/testing/testing.go:1439 +0x214
Step #10 - "test":   created by testing.(*T).Run
Step #10 - "test":   	/usr/local/go/src/testing/testing.go:1486 +0x725
Step #10 - "test": ------------------------------
Step #10 - "test": [BeforeEach] Gateway
Step #10 - "test":   /workspace/gloo/test/e2e/gateway_test.go:51
Step #10 - "test": [BeforeEach] in memory
Step #10 - "test":   /workspace/gloo/test/e2e/gateway_test.go:65
Step #10 - "test": [BeforeEach] tcp gateway
Step #10 - "test":   /workspace/gloo/test/e2e/gateway_test.go:621
```

**Comment by sam-heilbron** [comment]
I haven't seen this in a while. We've done some recent work to the in memory e2e tests so my hope is that this has been resolved. Closing.

If we encounter this again, we can re-open
