### ISSUE TITLE
Unable to configure Gloo to connect correctly with Prometheus

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#612]
Ran through doc (https://gloo.solo.io/operator_guide/observability/) and installed Gloo using Helm with `--set discovery.deployment.stats=true` for discovery, gateway, and gloo. Prometheus (installed using `helm install stable/prometheus`) auto discovered gloo (good), but failed to connect. It got connection refused errors in Prometheus console. Looked like gloo services may be binding to localhost.

Also not seeing gateway-proxy/envoy config to expose prometheus stats from Envoy, like in GlooE (https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/values-template.yaml#L60).

**Comment by ilevine** [comment]
solved by https://github.com/solo-io/gloo/pull/710
related to https://github.com/solo-io/gloo/pull/822
