### ISSUE TITLE
Highlight breaking changes when upgrading from 1.7 to 1.8

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#6130]
### Version

1.7.x

### Describe the requested changes

A Setting config validationServerGrpcMaxSize was introduced in 1.7 but renamed to validationServerGrpcMaxSizeBytes in 1.8 

when upgrading from 1.7 to 1.8 we need to make sure the values.yaml got updated to reflect this change, if not it will set the default values of 4mb and will break large environments 

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/master/operations/upgrading/1.8.0/#crd-field-updates

**Comment by chrisgaun** [comment]
@sam-heilbron another example of change that makes upgrading harder.
