### ISSUE TITLE
Envoy is double-escaping quoted string output in access logs

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#6141]
### Gloo Edge Version

1.11.x (beta)

### Kubernetes Version

1.21.x

### Describe the bug

Envoy appears to be double-exscaping quoted string output in access logs

### Steps to reproduce the bug

when configuring waf rules in configmap:
```
wafrules-core.conf: |
    SecRuleEngine On
    SecRequestBodyAccess On
    #SecResponseBodyAccess On
    SecAuditLogFormat JSON
    SecDebugLogLevel 0
    #SecRuleRemoveById 949110
    SecAction "id:900000, phase:1, nolog, pass, t:none,setvar:tx.paranoia_level=2"
    SecAction "id:900990, phase:1, nolog, pass, t:none,setvar:tx.crs_setup_version=310"

    SecAction "id:900220, \
    phase:1, nolog, pass, t:none, \
    setvar:'tx.allowed_request_content_type= |application/x-www-form-urlencoded|
    |multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|
    |application/octet-stream|application/csp-report|application/xss-auditor-report|text/plain|application/grpc-web+proto|'"
```

with the logging format set
```
options:
  accessLoggingService:
    AccessLog:
    - fileSink:
        jsonFormat:
          waf: '%FILTER_STATE(io.solo.modsecurity.audit_log)%'`
```
The waf field in access logs is not valid JSON and difficult to parse with all the extra quoted strings. 
```
{\"transaction\":{\"response\":{\"http_code\":401,\"headers\":{\":status\":\"401\",\"www-authenticate\":\"API key is missing or invalid\"}},\"client_port\":65523,\"messages\":[],\"request\":{\"http_version\":2,\"body\":\"\",\"headers\":{\"sec-fetch-dest\":\"empty\",\"user-agent\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36\",\"cookie\":\"OAMAuthnHintCookie=1; X-DOIT-Accept=Y; crowd.token_key.DOIT=ZlBMhNvHZUHqasJtZx6lUQAAAAAACQACemRhbHh2MQ\",\"sec-fetch-mode\":\"cors\",\"sec-ch-ua\":\"\\\" Not A;Brand\\\";v=\\\"99\\\", \\\"Chromium\\\";v=\\\"98\\\", \\\"Google Chrome\\\";v=\\\"98\\\"\",\"accept-encoding\":\"gzip, deflate, br\",\"origin\":\"https://developers-devl.cbp.dhs.gov\",\"x-forwarded-proto\":\"https\",\":scheme\":\"https\",\"accept-language\":\"en-US,en;q=0.9\",\"accept\":\"*/*\",\":path\":\"/uip-data-ingest/v1/api/health\",\"referer\":\"https://developers-devl.cbp.dhs.gov/\",\"sec-ch-ua-mobile\":\"?0\",\"sec-fetch-site\":\"same-site\",\"host\":\"api-devl.cbp.dhs.gov\",\":authority\":\"api-devl.cbp.dhs.gov\",\":method\":\"GET\",\"x-request-id\":\"33947cb4-a5ed-4b93-b7ab-4b1f8f0b1440\",\"sec-ch-ua-platform\":\"\\\"Windows\\\"\"},\"uri\":\"/uip-data-ingest/v1/api/health\",\"method\":\"GET\"},\"unique_id\":\"164616793936.351945\",\"server_id\":\"116993e35852ba7b2f15829e8bfde693bed53c47\",\"host_port\":0,\"client_ip\":\"10.186.173.167\",\"time_stamp\":\"Tue Mar  1 20:52:19 2022\",\"host_ip\":\"\",\"producer\":{\"connector\":\"envoy v0.1.0\",\"secrules_engine\":\"Enabled\",\"modsecurity\":\"ModSecurity v3.0.4 (Linux)\",\"components\":[\"OWASP_CRS/3.2.0\\\"\"]}}}
```
Some fields like user agent and platform fields are double or triple escaped. 
`\"sec-ch-ua\":\"\\\" Not A;Brand\\\";v=\\\"99\\\", \\\"Chromium\\\";v=\\\"98\\\", \\\"Google Chrome\\\";v=\\\"98\\\"\"`

### Expected Behavior

I would expect the output string to be quoted properly and wrapped in valid json

### Additional Context

This issue is specific to the double-escaped strings output but may also be related to https://github.com/solo-io/gloo/issues/5689

**Comment by asayah** [comment]
yes this is related to https://github.com/solo-io/gloo/issues/5689
if using datadog, there is a workaround: 
https://docs.datadoghq.com/logs/log_configuration/parsing/?tab=matchers#nested-json 

but a proper solution would be better.

**Comment by ben-taussig-solo** [comment]
At the moment, the suspicion is that this issue is the result of a misconfigured `jsonFormat` format string. I am working on updates to documentation which will clarify how to configure this properly (currently [the WAF guide in our documentation](format) only provides an example which uses a `stringFormat` format string).

I suspect that the user who experienced the issue configured their gateway with the `jsonFormat` format string `waf: %FILTER_STATE(io.solo.modsecurity.audit_log)%\n` (the `stringFormat` format string provided in our WAF guide). Doing so will cause the sort of mangled JSON audit logs as are shown above to be written. Instead, using `%FILTER_STATE(io.solo.modsecurity.audit_log)%` will cause modsecurity audit logs to be parsed properly.
