### ISSUE TITLE
Create a new unwrapAsApiGateway option to transform response payloads from AWS Lambdas

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#6143]
### Is your feature request related to a problem? Please describe.

Some of our clients want to migrate from AWS API Gateway to Gloo Edge. They currently have API Gateway to call a number of AWS Lambdas. There is a pre-defined response format that is expected by API Gateway, as described [here](https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html#apigateway-types-transforms).

### Describe the solution you'd like

Create a new AWS `DestinationSpec` option similar to `unwrapAsAlb`, where the following JSON payload is expected and parsed by Gloo Edge:
```
{
      "statusCode": 200,
      "headers": {
        "Content-Type": "application/json"
      },
      "isBase64Encoded": false,
      "multiValueHeaders": { 
        "X-Custom-Header": ["My value", "My other value"],
      },
      "body": "{\n  \"TotalCodeSize\": 104330022,\n  \"FunctionCount\": 26\n}"
}
```

The expectation is Gloo Edge to be able to translate this into a valid response to the client where:
response status = statusCode
response headers = headers / multiValueHeaders
response body = body

This could be an option enabled by a flag `unwrapAsApiGateway` on this [DestinationSpec](https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk/#destinationspec).

### Describe alternatives you've considered

1. User-space transformations
2. Custom WebAssembly filters

### Additional Context

Related to #6162

**Comment by jameshbarton** [comment]
The customer provided us [this generic Golang Lambda function](https://github.com/solo-io/gloo/files/8374645/test-lambda.zip) as an example we can use in our test suite to verify that this change satisfies their requirements.

**Comment by chrisgaun** [comment]
Sync with @nrjpoddar and @sam-heilbron if the work on this issues goes into second week of April (week of April 11th).

**Comment by nrjpoddar** [comment]
@ben-taussig-solo if you're stuck/need help please reach out to @yuval-k

**Comment by Rachael-Graham** [comment]
Tracking doc changes in https://github.com/solo-io/gloo/issues/6764
