### ISSUE TITLE
Unable to use Lambda Upstreams with RoleArn

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#6149]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

When using a lambda upstream with just RoleArn, gloo accepts but shows "no credentials present for AWS upstream" for glooctl check and the upstream does not work.

### Steps to reproduce the bug

1. https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/aws_lambda/eks-service-accounts/#configuring-an-eks-cluster-to-use-an-iam-role 

### Expected Behavior

You should be able to create and use lambda upstream with only specifying role arn

### Additional Context

https://solo-io.slack.com/archives/GLHNC87RN/p1646253731376549

**Comment by nfuden** [comment]
Is gloo installed with
enableServiceAccountCredentials: true

Also did you put the region on your lambda?

**Comment by ben-taussig-solo** [comment]
Tested on the latest v1.10.x release, and confirmed that this works properly, so the issue as written appears to be the result of a misconfiguration. The setup is definitely a little tricky, so I'm going to list out some potential gotchas here:
1. Make sure the `sts:AssumeRoleWithWebIdentity` statement in the IAM role's trust policy has `Principal.Federated` set to exactly the following:
  `arn:aws:iam::<ACCOUNT ID>:<OIDC PROVIDER URL>`, where `<OIDC PROVIDER URL>` is the output of `aws eks describe-cluster --name my-cluster --query "cluster.identity.oidc.issuer" --output text` without the `https://` prefix
2. Make sure that the same statement has `Condition.StringEquals.<OIDC PROVIDER URL>:sub` set to 
   ```json
    [
        "system:serviceaccount:gloo-system:discovery",
        "system:serviceaccount:gloo-system:gateway-proxy"
    ]
   ```
3. Make sure that the IAM Role created in step 3 includes the IAM Policy created in step 2 in its Permissions Policies
