### ISSUE TITLE
Edge Docs for Upgrading have multiple broken links for older product versions

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#6152]
### Version

1.10.x (latest)

### Describe the requested changes

All links to Upgrade Notice documents for versions of Gloo Edge <= 1.7 are broken (404 errors)

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/latest/operations/upgrading/
<img width="1458" alt="Screen Shot 2022-03-24 at 1 06 06 PM" src="https://user-images.githubusercontent.com/52334260/159971523-a8a84a5e-de39-4dce-a63d-6e90b086d8e6.png">

<img width="1300" alt="Screen Shot 2022-03-24 at 1 08 16 PM" src="https://user-images.githubusercontent.com/52334260/159971833-6120f28e-b842-4474-82b4-90e758195f76.png">

**Comment by artberger** [comment]
Updated redirect matching in: https://github.com/solo-io/docs-prod/commit/c6d21739f1e506de41a0e044f38a8cf21d16522f

File name updates to remove patch versions so this doesn't happen if we have to regex match these again: https://github.com/solo-io/gloo/pull/6157
