### ISSUE TITLE
Create a new wrapAsApiGateway option to transform request inputs for AWS Lambdas

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#6162]
### Version

1.11.x (beta)

### Is your feature request related to a problem? Please describe.

Some of our clients want to migrate from AWS API Gateway to Gloo Edge. They currently have API Gateway to call a number of AWS Lambdas. [Here](https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html#apigateway-types-transforms) is a pre-defined request format that API Gateway requests generate to upstream Lambdas.

### Describe the solution you'd like

Create a new AWS DestinationSpec option similar to `unwrapAsAlb`, except for adapting inbound requests into the event format that API Gateways generate for Lambdas:
```
{
      "resource": "/",
      "path": "/",
      "httpMethod": "GET",
      "requestContext": {
          "resourcePath": "/",
          "httpMethod": "GET",
          "path": "/Prod/",
          ...
      },
      "headers": {
          "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
          "accept-encoding": "gzip, deflate, br",
          "Host": "70ixmpl4fl.execute-api.us-east-2.amazonaws.com",
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
          "X-Amzn-Trace-Id": "Root=1-5e66d96f-7491f09xmpl79d18acf3d050",
          ...
      },
      "multiValueHeaders": {
          "accept": [
              "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
          ],
          "accept-encoding": [
              "gzip, deflate, br"
          ],
          ...
      },
      "queryStringParameters": null,
      "multiValueQueryStringParameters": null,
      "pathParameters": null,
      "stageVariables": null,
      "body": null,
      "isBase64Encoded": false
  }
```

So the request body would be adapted into this event as `body` (potentially with `isBase64Encoded` for binary content), request headers as either `headers` or `multiValueHeaders`, request query string parameters as `queryStringParameters`, etc.

This could be an option enabled by a flag `wrapAsApiGateway` on this [DestinationSpec](https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk/#destinationspec).

### Describe alternatives you've considered

1. User-space transformations
2. Custom WebAssembly filters

### Additional Context

Related to #6143

**Comment by jameshbarton** [comment]
The customer provided us [this generic Golang Lambda function](https://github.com/solo-io/gloo/files/8374645/test-lambda.zip) as an example we can use in our test suite to verify that this change satisfies their requirements.

**Comment by chrisgaun** [comment]
Sync with @nrjpoddar and @sam-heilbron if the work on this issues goes into second week of April (week of April 11th).

**Comment by chrisgaun** [comment]
Please make Enterprise Feature

**Comment by chrisgaun** [comment]
@ben-taussig-solo reach out to @nfuden and @yuval-k for help on this and the other Lambda issue
