### ISSUE TITLE
Transformation caching logic crashes gloo pod

### ISSUE THREAD

**Issue by saiskee** [solo-io/gloo#6163]
### Gloo Edge Version

1.11.x (beta)

### Kubernetes Version

1.22.x

### Describe the bug

https://github.com/solo-io/gloo/blob/c2e025728df3c66c67275ac718e251a275d32bd3/projects/gloo/pkg/plugins/transformation/plugin.go#L309

`err` may be nil here so this is causing a nil interface conversion panic.

### Steps to reproduce the bug

na

### Expected Behavior

it does not crash

**Comment by sam-heilbron** [comment]
This was introduced in Gloo Edge OSS 1.11.0-beta18. It will affect anyone using transformations. This will be resolved in Gloo Edge 1.11.0-rc3
