### ISSUE TITLE
Allow configuration of the "root" path for Hashi Vault Integration

### ISSUE THREAD

**Issue by solodamon** [solo-io/gloo#6184]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

The use of "/secret" is hard-coded.  It is possible to specify a root key through the "--vault-root-key" option to **glooctl**, however this is added after "/secret" to form a complete path.  Vault itself will allow the use of virtually any path and you can specify the backend engine, e.g. key-value.  Many large organizations use multiple roots to separate by team, by business unit, etc.

### Describe the solution you'd like

Users should be able to specify the root path used when querying vault.

### Describe alternatives you've considered

The only alternative is to use "/secret" as the root path, however this isn't possible in most cases; other tools and apps rely on the custom root path and updating all of these to use a single namespace isn't viable.

**Comment by chrisgaun** [comment]
Currently they are using Nomad

**Comment by sam-heilbron** [comment]
Remaining steps:
- [ ] Support configuration in solo-kit resource client factory
- [ ] Expose configuration in gloo edge (https://github.com/solo-io/gloo/pull/6283)
