### ISSUE TITLE
Warn: deprecated field 'envoy.config.route.v3.HeaderMatcher.safe_regex_match'

### ISSUE THREAD

**Issue by Bslabe123** [solo-io/gloo#6199]
Using `sanitiseRequestHeader` customer [#607](https://solo-io.zendesk.com/agent/tickets/607) ran into this warning: 
Deprecated field: type envoy.config.route.v3.HeaderMatcher Using deprecated option 'envoy.config.route.v3.HeaderMatcher.safe_regex_match' from file route_components.proto.

_Originally posted by @totallyGreg in https://github.com/solo-io/gloo/issues/5472#issuecomment-1082147154_

**Comment by jmunozro** [comment]
I found this in another customer today

**Comment by antonioberben** [comment]
@chrisgaun , there is a customer interested in this topic but concerning gloo. Should we move this to gloo project? or create an equivalent? Please, let me know how to proceed. thanks
