### ISSUE TITLE
Enable strict validation requires gateway.validation.enabled: true

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#6234]
### Version

master

### Describe the requested changes

https://docs.solo.io/gloo-edge/latest/guides/traffic_management/configuration_validation/admission_control/

States `--set gateway.validation.alwaysAcceptResources=false` will enable strict validation. 

the gloo/templates/18-settings.yaml has an if condition for 
93: {{- if .Values.gateway.validation.enabled }}

The PR that added this feature https://github.com/solo-io/gloo/pull/1710 states that enabled: true is the default value

It is still necessary to `--set gateway.validation.enabled=true` or define in it values file
```yaml
gloo:
  gateway:
    validation:
      enabled: true
      alwaysAcceptResources: false
```
 on install for it to properly reject the reject-me.yaml 

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/latest/guides/traffic_management/configuration_validation/admission_control/

**Comment by artberger** [comment]
Thanks for raising this; I updated this on our `doc-fixes` branch in this commit: https://github.com/solo-io/gloo/commit/f6d533451944d44f6e032adca88afe88cd15be92
