### ISSUE TITLE
DLP ALL_CREDIT_CARDS mask not masking correct characters

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#6257]
### Gloo Edge Version

1.11.x (beta)

### Kubernetes Version

1.21.x

### Describe the bug

Following [this docs guide](https://docs.solo.io/gloo-edge/latest/guides/security/data_loss_prevention/), the ALL_CREDIT_CARDS DLP mask should mask all but the last 4 digits of the credit card. Instead, it masks 7 characters in the middle of the string.

Example from docs:
Raw value: 4397945340344828
Expected masked value: XXXXXXXXXXXX4828
Actual masked value: 4397945XXXXXXX28

### Steps to reproduce the bug

1. Fresh install of 1.11.0 Edge Enterprise
2. Follow instructions [here](https://docs.solo.io/gloo-edge/latest/guides/security/data_loss_prevention/)
3. Observe the bad mask error on `fakevisa` response:
```
% curl $(glooctl proxy url)/ssn/123-45-6789/fakevisa/4397945340344828

{
   "fakevisa": "4397945XXXXXXX28",
   "ssn": "XXX-XX-X789"
}
```

### Expected Behavior

`fakevisa` is reported as XXXXXXXXXXXX4828

**Comment by chrisgaun** [comment]
Guessing this is error in the regex and not the filter?
