### ISSUE TITLE
CI Test Flake: e2e - error writing proxies in ratelimit_test

### ISSUE THREAD

**Issue by elcasteel** [solo-io/gloo#6261]
### Gloo Edge Version

1.11.x (beta)

### Describe the bug

Discussion here: https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1649345068387959
Failure logs: https://console.cloud.google.com/cloud-build/builds;region=global/13835d7d-a73e-4b06-940d-79952843d622;step=10?project=solo-public
The ratelimit e2e test fails with the error
``` 
<*url.Error | 0xc0069f5b90>: {
Step #10 - "test":         Op: "Get",
Step #10 - "test":         URL: "http://localhost:8081/1",
Step #10 - "test":         Err: <*net.OpError | 0xc006d5f4a0>{
Step #10 - "test":             Op: "dial",
Step #10 - "test":             Net: "tcp",
Step #10 - "test":             Source: nil,
Step #10 - "test":             Addr: <*net.TCPAddr | 0xc005efe5d0>{
Step #10 - "test":                 IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 127, 0, 0, 1],
Step #10 - "test":                 Port: 8081,
Step #10 - "test":                 Zone: "",
Step #10 - "test":             },
Step #10 - "test":             Err: <*os.SyscallError | 0xc006173080>{
Step #10 - "test":                 Syscall: "connect",
Step #10 - "test":                 Err: <syscall.Errno>0x6f,
Step #10 - "test":             },
Step #10 - "test":         },
Step #10 - "test":     }
```
There is a message in the logs about an invalid destination 
```
ERROR	gloo.setup.gloosnapshot.event_loop.envoyTranslatorSyncer	proxy default.proxy was rejected due to invalid config: 2 errors occurred:
	* invalid resource default.proxy
	* WARN: 
  [Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream { default.local-test-upstream-53 } not found Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream { default.local-test-upstream-53 } not found]
``` 
That looks suspicious and our initial thoughts were that this was caused by test pollution, which we ruled out when we saw that the proxy is constructed within the test: https://github.com/solo-io/gloo/blob/master/test/e2e/ratelimit_test.go#L231

I also ran the test locally with -v and the logs from a successful run have the same error message so it's possible that it's a red herring.

**Comment by sam-heilbron** [comment]
We haven't seen this issue in ~1 year. Closing

**Comment by elcasteel** [comment]
I think this was fixed when we fixed the upstream client
