### ISSUE TITLE
Edge 1.11.0 Upgrade Guides missing change to Settings CRD

### ISSUE THREAD

**Issue by dhawton** [solo-io/gloo#6267]
### Version

1.11.x (latest)

### Describe the requested changes

https://docs.solo.io/gloo-edge/latest/operations/upgrading/v1.11/ is missing information about the change to the Settings CRD (around consoleOptions -- https://github.com/solo-io/gloo/pull/6123). This causes upgrade failures if the CRD is not applied.

For example:

```shell
kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.11.0/install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
```

### Link to any relevant existing docs

1. https://docs.solo.io/gloo-edge/latest/operations/upgrading/v1.11/

### Browser Information

Content Related

### Additional Context

N/A

**Comment by jenshu** [comment]
@dhawton there is a section on that page telling you to apply all the crds
```
Apply the new and updated CRDs.
---
helm pull gloo/gloo --version 1.11.0 --untar
kubectl apply -f gloo/crds
```
we thought it was safer to apply all rather than calling out every individual CRD that had a change, since we could miss one

although maybe we should list the settings change in the 'new and updated crds' section

**Comment by dhawton** [comment]
Good point. Adding to the list would be helpful to point out the change.
