### ISSUE TITLE
CI test flake: grpc_json_test "Route matching assumptions..."

### ISSUE THREAD

**Issue by elcasteel** [solo-io/gloo#6280]
### Gloo Edge Version

1.11.x (beta)

### Describe the bug

CI fails with an error making a request/routing traffic:
```
 Timed out after 5.000s.
Step #10 - "test":   Error: Unexpected non-nil/non-zero extra argument at index 1:
Step #10 - "test":   	<*url.Error>: &url.Error{Op:"Post", URL:"http://localhost:11310/test", Err:(*net.OpError)(0xc00ca8dae0)}
Step #10 - "test": 
Step #10 - "test":   /workspace/gloo/test/e2e/grpc_json_test.go:140
```
Logs from failure: https://console.cloud.google.com/cloud-build/builds;region=global/96ec5a7a-7c65-42df-a948-9c3b14256f82?project=solo-public

I can't find anything obvious that went wrong.

### Steps to reproduce the bug

run ci

### Expected Behavior

tests should pass on a docs only change

**Comment by sam-heilbron** [comment]
We haven't seen this in ~1 year, closing
