### ISSUE TITLE
ci test flake: Staged Transformation with auth [It] should transform response code details

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#6356]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

```
Step #10 - "test": [Fail] Staged Transformation with auth [It] should transform response code details 
Step #10 - "test": /workspace/gloo/test/e2e/staged_transformation_test.go:345
```

example logs:
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=15c11eec-37ec-4ebf-b00a-47ccf7fa17b7
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=addc9a7c-01cb-4df9-a0b6-dfa88b119503

### Steps to reproduce the bug

run gloo ci

### Expected Behavior

test should pass

**Comment by sam-heilbron** [comment]
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=11731a4e-f341-4226-82f6-c2ce3eac25fb

**Comment by sam-heilbron** [comment]
The error I see earlier in the logs:

````
Step #10 - "test": Proxies:[listeners:{name:"listener"  bind_address:"::"  bind_port:11102  http_listener:{virtual_hosts:{name:"virt1"  domains:"*"  routes:{route_action:{single:{upstream:{name:"local-test-upstream-14"  namespace:"default"}}}}  options:{extauth:{custom_auth:{}}  staged_transformations:{early:{response_transforms:{response_code_details:"ext_authz_error"  response_transformation:{transformation_template:{body:{text:"early-transformed"}  parse_body_behavior:DontParse}}}}}}}}}  namespaced_statuses:{statuses:{key:"gloo-system"  value:{state:Rejected  reason:"1 error occurred:\n\t* HttpListener Error: ProcessingError. Reason: extauth server upstream not found name:\"extauth-server\"  namespace:\"default\"\n\n\nwarning: \n  Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream { default.local-test-upstream-14 } not found"  reported_by:"gloo"}}}  
```

To me this means we're not applying resources in the proper order or waiting long enough for resources to be available.

**Comment by jenshu** [comment]
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=b6409ec5-e5b9-4d90-89df-001d3698b12b

**Comment by elcasteel** [comment]
https://console.cloud.google.com/cloud-build/builds;region=global/8cbfae3e-f1a3-41b6-9167-f94d40e9446b?project=solo-public

I have seen this several times today.

**Comment by elcasteel** [comment]
I have reproduced this locally when I focus "Staged Transformation" but not when I focus "Staged Transformation with auth" so this looks like test pollution

**Comment by elcasteel** [comment]
I suspected that this check: https://github.com/solo-io/gloo/blob/master/test/e2e/staged_transformation_test.go#L130 succeeds when it is actually accessing an upstream created for a previous test. To test this I tried adding a check before we created and set the Proxy to demonstrate that requests to the upstream failed (meaning the envoy config had successfully been cleaned up). That didn't solve the flake so my suspicion may be wrong. 
I tried moving the "with auth" block first and that does solve the flake locally, which makes test pollution look even more likely.

**Comment by elcasteel** [comment]
This flake from a different test seems very similar: https://github.com/solo-io/gloo/issues/6307
The pattern is creating test upstreams, creating proxies within the test, using `TestUpstreamReachable()` as a way to verify that the new proxy is synced and then finding that envoy behaves inconsistently.

**Comment by jenshu** [comment]
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=5b906368-3ec7-4cc4-887d-5b9fbb2ea397
