### ISSUE TITLE
LDAP - improve log verbosity around search results and membership

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6366]
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

We can do better at logging events on the LDAP search call and looking for membership.

See https://github.com/solo-io/ext-auth-service/blob/df1de0fe3f610244057391f165b0a922c1fd84f2/pkg/config/ldap/auth_service.go#L183-L193

If the result set is empty, there is no log

### Describe the solution you'd like

debug or warn logs if no user is found

**Comment by Jimmmz** [comment]
The customer no longer uses LDAP so am closing this issue
