### ISSUE TITLE
LDAP - configurable scope in the search request

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6368]
### Is your feature request related to a problem? Please describe.

When looking for membership, the ExtAuth server will execute an LDAP query with options like the `userDnTemplate`.
One of the options is the scope. It's frequent for companies to search down the child nodes. In this case, the scope should be set to `subtree`.
The ask is to expose a new parameter to configure the `scope` in the search query.
Possible values are:
- base (which is the default in our current implementation)
- subtree
- single level

**Comment by Jimmmz** [comment]
The customer no longer uses LDAP so am closing this issue
