### ISSUE TITLE
LDAP - disable group checking

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6369]
### Is your feature request related to a problem? Please describe.

Sometimes, it's enough to check for the user credentials. There is no need to check for group membership.
The ask is to expose a new flag to disable the group checking (**no** use of `allowedGroups` and `membershipAttributeName`)

**Comment by chrisgaun** [comment]
@ashsolo Can you put the version we need to backport to.

**Comment by ashsolo** [comment]
@chrisgaun 1.11 and 1.7
