### ISSUE TITLE
Annotate extauth logs with request ID

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6370]
### Is your feature request related to a problem? Please describe.

Users asked to improve extauth logs so that we can correlate events with client requests.
For example, when an extauthz request is denied for some reason, the extauth server will log the following:
```json
{"level":"debug","ts":1650622228.1456635,"logger":"ext-auth.ext-auth-service","msg":"Access denied by auth authService","version":"undefined","authService":"config_1"}
```

A quick win could be to log the request ID (if available at this stage of the filter chain?)

Even with reasonable traffic, it's hard to associate extauth logs with client requests.

**Comment by chrisgaun** [comment]
Done
