### ISSUE TITLE
Redact specific headers in access logs via DLP

### ISSUE THREAD

**Issue by jbohanon** [solo-io/gloo#6377]
### Is your feature request related to a problem? Please describe.

Redacting based on header name would be very difficult in situations where it isn't trivial to construct a regex for the value. As determined in [Gloo issue 5807](https://github.com/solo-io/gloo/issues/5807), at the time the regex is being evaluated against headers it is only looking at the value of the key-value pair that constitutes an HTTP header. 

### Describe the solution you'd like

A method of configuring header values to be redacted would be helpful. This might be an optional list of header keys in the customAction definition.

### Describe alternatives you've considered

The only alternative I can think of is ensuring header values have a consistent marker in them that can be matched against. For example, auth tokens passed via `Authorization: Bearer <token>` can be redacted by matching on `(.*)(Bearer )(.*)` with subgroup 3. This falls apart if something like `X-Api-Key: <uuid>` is passed since matching on uuid would probably mask things that didn't need masked. 

Another possible alternative is to concatenate header/value pairs in the filter when determining if masking should occur. This could possibly break existing usages however.

### Additional Context

This was not explicitly requested by a customer yet, but the confusion in the issue linked above suggests that this is functionality the customer implicitly understood.

**Comment by chrisgaun** [comment]
This is likely a dupe
