### ISSUE TITLE
ci test flake: CSRF defined on listener defined on listener with shadow mode config [It] should succeed with allowed origin, unsafe request

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#6389]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

```
Expected 
  <bunch of envoy stats>
to match regular expression
  <string>: http.http.csrf.request_valid: 1
```
https://console.cloud.google.com/cloud-build/builds;region=global/e999b579-33f5-47cd-a8e9-e6efdd5e1e16?project=solo-public

### Steps to reproduce the bug

run ci build-bot

### Expected Behavior

should pass consistently

**Comment by mkazin** [comment]
another instance: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=c787594d-4347-4a94-9ce7-1142422f75e8

**Comment by elcasteel** [comment]
again: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=a21da721-ddfc-4f37-8889-36a0e41c8ce7

**Comment by mkazin** [comment]
again: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=0add4b23-9e84-4bb2-967e-7e27a8be06d0

**Comment by ashishb-solo** [comment]
Different test but also in the same module

https://console.cloud.google.com/cloud-build/builds;region=global/018b512c-9d1b-4c03-8cd4-22352b6ab708?project=solo-public

**Comment by elcasteel** [comment]
https://console.cloud.google.com/cloud-build/builds;region=global/6364a108-b74f-4e2b-b482-c7e360ff7461?project=solo-public 
Same csrf module

```
Step #10 - "test": [Fail] CSRF defined on listener defined on listener with shadow mode config [It] should succeed with un-allowed origin and update invalid count 
Step #10 - "test": /workspace/gloo/test/e2e/csrf_test.go:267
```
