### ISSUE TITLE
Expose respect_dns_ttl for STRICT_DNS cluster type

### ISSUE THREAD

**Issue by nickrobledo** [solo-io/gloo#6402]
### Version

1.10.x

### Is your feature request related to a problem? Please describe.

We know that clusters are using STRICT_DNS by default.  In order to avoid problems such as endpoint flapping we would like to match the refresh time to the record TTL by enabling [respect_dns_ttl](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-respect-dns-ttl).

### Describe the solution you'd like

Would like to have respect_dns_ttl exposed in Gloo.

**Comment by sam-heilbron** [comment]
This feature is included in the most recent Gloo Enterprise beta release: `1.14.0-beta9`
