### ISSUE TITLE
Tracing Document uses deprecated v2 API

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#6444]
### Version

1.10.x

### Describe the requested changes

docs/content/guides/observability/tracing.md should either be excised or overhauled.

Currently it references the v2 zipkin api which is no longer supported as of Envoy 1.18 there are working examples in the code base using v3 so we can either update it or drop it if it is not working correctly.

### Link to any relevant existing docs

docs/content/guides/observability/tracing.md

### Additional Context

Affects 1.10 and up

**Comment by Nadine2016** [comment]
https://github.com/solo-io/gloo/pull/6502/files
