### ISSUE TITLE
Expose various HTTP/2 settings

### ISSUE THREAD

**Issue by guydc** [solo-io/gloo#6466]
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

According to the envoy docs, certain HTTP/2 settings should be configured, based on the envoy deployment mode, trustworthiness of upstreams and downstreams and required support for protocol upgrades and downgrades. These settings include:

1. [Upstream HTTP/2 Protocol Options](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto.html?highlight=http2protocoloptions): 
- initial_connection_window_size
- initial_stream_window_size
- override_stream_error_on_invalid_http_message

2. [Downstream HTTP/2 Protocol Options](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html?highlight=http2protocoloptions): 
- initial_connection_window_size 
- initial_stream_window_size
- max_concurrent_streams
- override_stream_error_on_invalid_http_message

3. Timeout settings: 
- request_headers_timeout 
- stream_idle_timeout

Gloo edge should expose these settings and provide secure defaults that are appropriate for an edge proxy deployment mode.

**Comment by chrisgaun** [comment]
Needs to be backported to 1.11

**Comment by ianmacclancy** [comment]
Removing [Upstream HTTP Protocol Options](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#envoy-v3-api-msg-extensions-upstreams-http-v3-httpprotocoloptions) from the issue - this will be addressed in https://github.com/solo-io/gloo/issues/6604

**Comment by ianmacclancy** [comment]
override_stream_error_on_invalid_http_message (added to upstream as an http2 option)
override_stream_error_on_invalid_http_message (added to http1ProtocolOptions)
request_headers_timeout (added to HttpConnectionManager)

initial_connection_window_size (already exists)
initial_stream_window_size (already exists)
stream_idle_timeout (already exists - HttpConnectionManager)

Protocol Selection was added in part by https://github.com/solo-io/gloo/issues/6521
