### ISSUE TITLE
Create unique virtual services in regression tests

### ISSUE THREAD

**Issue by elcasteel** [solo-io/gloo#6472]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

In the gateway regression tests, we have a lot of tests that create virtual services and then verify that curl works in various circumstances. 
We have a helper function to create a virtual service that uses a hard coded name and the domain "*". https://github.com/solo-io/gloo/blob/master/test/kube2e/gateway/gateway_test.go#L2630

The hardcoded name and domain mean that only one virtual service at a time can be created with this helper and therefore tests need to defensively clean up resources and wait for resources from previous tests to be deleted or the tests are flaky. 

We should replace the hardcoded names and domains with uniquely generated ones. 

### Steps to reproduce the bug

Run CI. 

### Expected Behavior

CI should be deterministic.

**Comment by Nadine2016** [comment]
Some logs where I could not pass this test for my doc PR https://github.com/solo-io/gloo/runs/6756308289?check_suite_focus=true. This was the PR that I tried to merge in https://github.com/solo-io/gloo/pull/6522

**Comment by ianmacclancy** [comment]
Hitting this on - https://github.com/solo-io/gloo/pull/6653

**Comment by ianmacclancy** [comment]
Hitting this on - https://github.com/solo-io/gloo/runs/7235963658?check_suite_focus=true#step:11:163

**Comment by elcasteel** [comment]
saw this here: https://github.com/solo-io/gloo/runs/7394019423?check_suite_focus=true

**Comment by elcasteel** [comment]
happens  frequently still: https://github.com/solo-io/gloo/runs/7775959992?check_suite_focus=true
