### ISSUE TITLE
Incompatible solo-apis on gloo 1.11.10

### ISSUE THREAD

**Issue by DoroNahari** [solo-io/gloo#6473]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

After fixing the [issue](https://github.com/solo-io/gloo/issues/6406) that blocked us from upgrading gloo to 1.11.x, We have another issue while trying to upgrade to the version with the fix (1.11.10):

Our controller is consuming [solo-apis](https://github.com/solo-io/solo-apis) in order to get gloo resources such as [gloo instance](https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/solo-apis/api/gloo-fed/fed/v1/instance.proto.sk/).

After the upgrade, our controller can't get the gloo instance anymore because of unknown fields. log for example:
`failed to list *v1.GlooInstance: unknown field "matchableHttpGateways" in fed.solo.io.GlooInstanceSpec.Check`
`failed to list *v1.GlooInstance: unknown field "rateLimitConfigs" in fed.solo.io.GlooInstanceSpec.Check`

These fields are not even exist in the [api reference](https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/solo-apis/api/gloo-fed/fed/v1/instance.proto.sk/#check).

While inspecting gloo instance resource in our cluster, we saw the above fields:
```yaml
apiVersion: fed.solo.io/v1
kind: GlooInstance
metadata:
  managedFields:
    - apiVersion: fed.solo.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
...
          f:check:
...
            f:matchableHttpGateways: {}
...
            f:rateLimitConfigs: {}
...
      manager: gloo-fed
      operation: Update
      time: '2022-05-19T05:51:02Z'
  name: dev-gateway-apigw-gloo-ee
  namespace: gloo-fed
spec:
...
  check:
...
    matchableHttpGateways: {}
    pods:
      total: 3
    proxies: {}
    rateLimitConfigs: {}
...
```

Our controller is consuming the corresponding version of solo apis (1.11.10)

**Comment by jenshu** [comment]
Hi @DoroNahari , the [gloo-v1.11.12 tag](https://github.com/solo-io/solo-apis/releases/tag/gloo-v1.11.12) of solo-apis has this fix

In addition, we are working on releasing GlooEE v1.11.12 (should be available within the next hour) to consume that version of solo-apis - although I think you should be able to pull in the latest solo-apis without upgrading GlooEE

**Comment by jenshu** [comment]
GlooEE v1.11.12 is released now

please reopen if still having issues
