### ISSUE TITLE
Expose extensions.wasm.v3.PluginConfig.fail_open

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#6474]
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

Envoy has a configuration for plugins called "fail_open", but its not exposed in gloo WasmFilter

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/wasm/v3/wasm.proto#extensions-wasm-v3-pluginconfig

**Comment by bewebi** [comment]
This feature is implemented in Gloo EE 1.12.0-beta8, 1.11.17, and 1.10.26
