### ISSUE TITLE
allow configuring "lb_policy"

### ISSUE THREAD

**Issue by benishak** [solo-io/gloo#652]
Hi

This is a feature request/question more than a bug

I noticed that when using gloo, that traffic is not evenly distributed on all pods, some pods got more traffic and got exhausted and became unhealthy. 
I'm not sure what lb policy is being used as default by envoy or gloo when none is specified, but I assume it is not round robin.
I know that round robin in envoy is not that perfect based on this link, but it should not deviate that much and cause pods to get overloaded.
https://www.envoyproxy.io/docs/envoy/latest/faq/concurrency_lb

it is useful to allow configuring this somewhere globally or in the upstream level.

**Comment by yuval-k** [comment]
@benishak  I think i can have this ready in the next few days. 
BTW the default for envoy is round robin (see here: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#enum-cluster-lbpolicy)
You might want to try LeastRequest or Random. i will make both available as configuration on an upstream

**Comment by benishak** [comment]
great, thanks! 
could you make these settings available
max_requests_per_connection
connect_timeout
upstream_connection_options
close_connections_on_host_health_failure
health_checks (or are you auto taking this config from ReadinessProbe and LivenessProbe?)

**Comment by mjaow** [comment]
@yuval-k  how can I specify a LB policy for a upstream, as I didn't see any related settings in https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/,  should I create an upstream and set the lb policy by my self

**Comment by yuval-k** [comment]
yea this setting is per-upstream; so it wouldn't be in the helm chart

**Comment by mjaow** [comment]
thanks

**Comment by yuval-k** [comment]
multi destination allows you to select an upstream in a certain probability;
once an upstream is selected; lb policy will be used on the upstream's endpoints.

for example, let's say you have 2 kube services with 10 pods each. Multi desitination will chose one of these services according to the weights; once a service was selected, the lb policy will be used to select a pod

**Comment by mjaow** [comment]
nice and clear, thanks
