### ISSUE TITLE
Provide webhook validation for RateLimitConfig

### ISSUE THREAD

**Issue by krisztianfekete** [solo-io/gloo#6533]
### Is your feature request related to a problem? Please describe.

Currently, we don't have validation for `RateLimitConfig` objects, therefor invalid configs can make it into production.

### Describe the solution you'd like

Validation web hooks should cover `RateLimitConfig` objects as well.

### Additional Context

The parent issue for tracking web hook validation is https://github.com/solo-io/gloo/issues/2797.

**Comment by zf-roose** [comment]
For example, someone could forget to set a descriptor or setDescriptor, resulting in a reject RateLimitConfig 

`
  "spec": {
    "raw": {
      "rateLimits": [
        {
          "setActions": [
            {
              "requestHeaders": {
                "descriptorKey": "some-key",
                "headerName": "x-some-key"
              }
            }
          ]
        }
      ],
      "setDescriptors": null
    }
  },
`


with following status:

`
  "status": {
    "message": "1 error occurred:\n\t* raw config must define at least one descriptor or setDescriptor\n\n",
    "observedGeneration": 1,
    "state": "REJECTED"
  }
`

**Comment by krisztianfekete** [comment]
Closing due to https://github.com/solo-io/gloo/issues/6777#issuecomment-1325529601.
