### ISSUE TITLE
docs on zsh completion

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#654]
bash completion was enabled by https://github.com/solo-io/gloo/issues/460

zsh completion does not seem to be working for me

There seems to be a feature gap between cobra's support for bash and zsh: https://github.com/spf13/cobra/issues/107

**Comment by ilevine** [comment]
add a help text in the cli to explain how to do zsh completion like in #460

**Comment by rickducott** [comment]
Closing as stale
