### ISSUE TITLE
Istio Compat: Support Sidecar Injection on Gateway Proxies for Revision Istio

### ISSUE THREAD

**Issue by bgottfried91** [solo-io/gloo#6594]
### Gloo Edge Version

1.12.x (beta)

### Kubernetes Version

1.23.x

### Describe the bug

The new Helm value `global.istioIntegration.enableIstioSidecarOnGateway` that should apply a label to any `gatewayProxies` created during Edge install currently only applies the `istio-injection: enabled` label. This label, when applied to a Pod directly (as opposed to applied to a namespace), will only work for Istio installations that are not using revisions. For revisioned Istio, you must use the label `istio.io/rev: <revision>`.

### Steps to reproduce the bug

1. Install Istio with revisions
2. Install Gloo Edge with the `global.istioIntegration.enableIstioSidecarOnGateway` value set to true.
3. Confirm that the gateway proxy/proxies does/do not have sidecars injected

### Expected Behavior

When using that Helm value, it should inject sidecars whether Istio is revisioned or not.

### Additional Context

I'd think we could fix this pretty quickly just by changing the chart behavior so that if another value exists, like `global.istioIntegration.enableIstioSidecarOnGateway.revision`, the chart instead generates the `istio.io/rev` label instead of `istio-injection` label.

**Comment by elcasteel** [comment]
@bgottfried91 should we be able to override the revision tag on a per-proxy basis? Also should we be able to specify a different revision for discovery vs gateway proxies?

**Comment by bgottfried91** [comment]
I'm struggling to think of a scenario where you'd want to support more than one revision simultaneously, honestly, especially since this is in regards to a Mesh integration. However, I'd think we'd want to use the pod label and only label the gateway proxy pods (I'm actually not sure if the discovery pods need to be in the Mesh? Let me know if you can think of a case where they would) to avoid any weirdness with putting the rest of the GE pods in the mesh when it's not needed. But I would say that all gateway proxy pods in a GE install would expect the same Istio revision.
