### ISSUE TITLE
Grpcmaxvalidation not respecting all sizes that it claims

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#6596]
### Gloo Edge Version

1.9.x

### Describe the bug

It was determined that along with the known reload issue for grpcmaxvalidation going from 1.8 to 1.9's grpcmaxvalidationbytes breaks for larger values. 

For example 16 MiB does not actually get set when requested. 

### Steps to reproduce the bug

Set grpcmaxvalidation bytes send a large request (scale testing scripts can help populate a large proxy) 
Error logs indicate that the max is not as large as the requested new max

### Expected Behavior

The size set is always respected up to the max int32 as defined in our CRD

**Comment by nfuden** [comment]
Converting to a full issue as everything on the late 1.8 branch to 1.9 branch seemed the same which made tracking this harder.

**Comment by bewebi** [comment]
I've reproduced the issue and used `git bisect` to identify #5301 as the PR in which the bug was introduced

**Comment by nfuden** [comment]
This has been backported and is on all affected branches
