### ISSUE TITLE
Unmatched AuthConfigs at both VS and RT level cause extauth to loop loading config 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#6598]
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

When there are unmatched AuthConfigs at both the VS and route level of an RT then the extauth pod will get stuck in a loop loading the config:

`{"level":"info","ts":"2022-06-21T19:00:10.831Z","caller":"runner/xds.go:106","msg":"got 3 new configs","version":"1.11.17"}`

### Steps to reproduce the bug

1. Create 2 AuthConfigs
2. Create a VS with AuthConfig1 at the virtualHost level
3. Create a RouteTable with AuthConfig2 at the route level
4. Add the RouteTable to the VS

Every minute or so, the extauth pod will log that the confiog has been reloaded 

### Expected Behavior

Unchanged config is not reloaded

**Comment by sam-heilbron** [comment]
I believe we could solve this as part of: https://github.com/solo-io/solo-projects/issues/3558. The underlying challenge has to do with how we process configuration that we propagate to the extauth and ratelimit servers. The linked issue draws out a more efficient and safer way to propagate those changes.

cc @chrisgaun @bdecoste
