### ISSUE TITLE
Failure when integrating with Consul instance with a high number of services and endpoints 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#6599]
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

gloo throws error when integrating with a Consul instance with a high number of services (e.g. 5000) and endpoints (e.g. 75000):

`{"level":"error","ts":"2022-06-17T23:21:39.701Z","logger":"gloo.v1.event_loop.setup.v1.event_loop.syncer.consul_eds","caller":"consul/eds.go:183","msg":"write error channel is full! could not propagate err: Get \"http://172.17.0.1:8500/v1/catalog/service/raas-xiaowei-name-test-redis?consistent=&dc=sitetest3\": context canceled","version":"1.12.0-beta17","stacktrace":"[github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.refreshSpecs](http://github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.refreshSpecs)\n\t/workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:183\[ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints.func2](http://ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints.func2)\n\t/workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:99"}`

### Steps to reproduce the bug

1. Deploy Consul with high number of services and endpoints
2. Disable discovery 
3. Configure GE for Consul-based eDS

### Expected Behavior

Handle high service& endpoint processing

**Comment by kdorosh** [comment]
we may also want to explore using caching / filtering options available here https://github.com/solo-io/gloo/blob/7da575b8b13b2371d0b6ec60285a11fb0d9ddf68/projects/gloo/pkg/upstreams/consul/consul_client.go#L115

**Comment by willowmck** [comment]
@chrisgaun and @nrjpoddar - this one is high priority.  Can we get someone assigned?

**Comment by nrjpoddar** [comment]
Is this higher compared to https://github.com/solo-io/gloo/issues/6594 ?

**Comment by willowmck** [comment]
looks like a dependency

**Comment by kdorosh** [comment]
we may want to swap to https://www.consul.io/docs/dynamic-app-config/watches#services or https://www.consul.io/docs/dynamic-app-config/watches#service
