### ISSUE TITLE
line can cause a panic if `upstreamSpec` is nil

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#661]
https://github.com/solo-io/gloo/blob/e3f97a0667398a52f5485a893ecda74fdf40b4d9/projects/gloo/pkg/translator/clusters.go#L58

user reported a panic caused by this line as we do not validate a non-nil `upstreamSpec` anywhere

**Comment by yuval-k** [comment]
yes, that is a pretty strong assumption we make in the code.
perhaps we should just do a review on all the code and use Get* functions instead, they work with nil receivers.

**Comment by yuval-k** [comment]
the following search flags all the uses of upostream spec being null:
`rg '\.UpstreamSpec\.' -g  "**/*.go"`

How did we get to the spec being null? It might be a fair assumption to have - and in that case the code can continue assuming that it is not null, and maybe not pass it to the rest of the code if it is.

**Comment by rickducott** [comment]
Closing as stale
