### ISSUE TITLE
Gloo Fed needs to stop using clusterName field in k8s 1.24

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#6611]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

Currently Gloo Fed uses the `metadata.clusterName` field to store registered cluster names.
Kubernetes has deprecated the field and changed its name as of [1.24](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md) and will remove it in [1.25](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#api-change)

We will need to store the cluster name in a different field.

### Steps to reproduce the bug

N/A

### Expected Behavior

N/A

**Comment by bcollard** [comment]
linked to https://github.com/solo-io/skv2/issues/362?

**Comment by Ido-Itz** [comment]
Which resource do you store the `metadata.clusterName` field on?

**Comment by jenshu** [comment]
> Which gloo-fed resource uses the `metadata.clusterName` field?

It's only used in memory to keep track of which resources came from which cluster. It's not written to storage.

**Comment by Ido-Itz** [comment]
> > Which gloo-fed resource uses the `metadata.clusterName` field?
> 
> It's only used in memory to keep track of which resources came from which cluster. It's not written to storage.

In this case, it's safe for us to upgrade to Kubernetes 1.24.  Am I right?

**Comment by jenshu** [comment]
Gloo Fed does not yet work on 1.24, i would not upgrade until this is resolved

**Comment by jenshu** [comment]
fix will be available in GlooEE v1.12.41, v1.13.0, and v1.14.0-beta2
