### ISSUE TITLE
Expose tls allow_renegotiation in Gloo api 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#6621]
### Is your feature request related to a problem? Please describe.

Need to support an upstream that may request tls renegotiation 

### Describe the solution you'd like

Envoy supports this so need ego expose allow_renegotiation in Gloo api 

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#extensions-transport-sockets-tls-v3-upstreamtlscontext

**Comment by sam-heilbron** [comment]
@bdecoste @asayah Now that this has merged into the main branch, what version do we expect to backport this to?

Leaving this issue open until we have completed the necessary backports, if there are any

**Comment by sam-heilbron** [comment]
This feature is supported in the following Gloo Edge versions:

1.11.x:
GlooEE: 1.11.25 
Gloo OSS: 1.11.18

1.12.x (beta)
Gloo OSS: 1.12.0-beta25
Gloo EE: Not yet released, likely in 1.12.0-beta12
