### ISSUE TITLE
glooctl istio inject does not work in Enterprise

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#6623]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

glooctl istio inject is getting the wrong sds image, from the enterprose version and not from OSS.

```
 k -n gloo-system get po -l gloo=gateway-proxy
NAME                             READY   STATUS             RESTARTS   AGE
gateway-proxy-5b6b4d4677-s4tj6   1/1     Running            0          34m
gateway-proxy-7d98bbcb56-6f457   2/3     ImagePullBackOff   0          33m
```

### Steps to reproduce the bug

1. Install Istio (no revisions)
2. Install gloo-ee 1.11.23
3. glooctl istio inject

### Expected Behavior

.

### Additional Context

It is working fine in helm:
```
helm upgrade --install gloo glooe/gloo-ee --namespace gloo-system \
  --create-namespace --version 1.11.23 --set-string license_key=$LICENSE_KEY -f - <<EOF
global:
  istioSDS:
    enabled: true
EOF
```

**Comment by elcasteel** [comment]
This is out in the 1.12 release
