### ISSUE TITLE
Delete helm upgrade e2e tests once those gloo versions are no longer supported

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#6661]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

There are certain tests in the [kube2e helm test suite](https://github.com/solo-io/gloo/blob/d4cd6a26680ecf2d4b67952ea13163c48aee9a20/test/kube2e/helm/helm_test.go) that test upgrading from specific gloo edge versions to the most recent version (see any tests referencing 1.11.x)

This is just a reminder to delete those tests once the versions are no longer supported.

### Steps to reproduce the bug

N/A

### Expected Behavior

N/A

**Comment by sam-heilbron** [comment]
This has been resolved in Gloo 1.17 in both open source and enterprise
