### ISSUE TITLE
default docker-comspose-file installation fails

### ISSUE THREAD

**Issue by huzlak** [solo-io/gloo#6674]
### Version

1.11.x (latest)

### Describe the requested changes

following our [docs](https://docs.solo.io/gloo-edge/latest/installation/gateway/development/docker-compose-file/) fails to start gloo with:

```
gloo_1           | {"level":"fatal","ts":"2022-07-04T07:03:55.307Z","logger":"gloo","caller":"setuputils/main_setup.go:73","msg":"error in setup: starting snapshot watch: initial Proxy list: reading file into *v1.Proxy: unknown field \"metadataStatic\" in gloo.solo.io.Route","version":"1.10.0","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:73\ngithub.com/solo-io/gloo/projects/gloo/pkg/setup.startSetupLoop\n\t/workspace/gloo/projects/gloo/pkg/setup/setup.go:22\ngithub.com/solo-io/gloo/projects/gloo/pkg/setup.Main\n\t/workspace/gloo/projects/gloo/pkg/setup/setup.go:14\nmain.main\n\t/workspace/gloo/projects/gloo/cmd/main.go:14\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```
After defining newer than default `1.10.0` image it works. Docs should be corrected so the default installation steps work. also version should be aligned with at least current minor release number so 1.11.x should not point to 1.10 by default. The best would be to point to latest stable release and add a test to make sure docker compose works.

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/latest/installation/gateway/development/docker-compose-file/

**Comment by nfuden** [comment]
Likely it should not point to newest release it should just point to the glooversion variable that exists in the makefile if at all possible.

That way if one clones an LTS branch for example then the docker-compose will still work as expected.

**Comment by sam-heilbron** [comment]
We have updated this implementation: https://github.com/solo-io/gloo/tree/main/install/docker-compose-file. We now default to a more recent version, and also allow users to inject the custom Gloo Edge version that they want to run, using the [GLOO_VERSION env variable](https://github.com/solo-io/gloo/blob/main/install/docker-compose-file/docker-compose.yaml#L5). I believe this is now resolved so I am closing the issue. 

If you find other gaps, please feel free to re-open
