### ISSUE TITLE
Ratelimiting not working 

### ISSUE THREAD

**Issue by Akhil-ZF** [solo-io/gloo#6675]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.20.x

### Describe the bug

We are facing an strange issue with Ratelimiting in Gloo. We have been following https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/crds/ approach to apply ratelimiting, initially it was working but now it has stopped working for all projects, even though system seems to be in valid state - C:\Windows\system32>glooctl get proxies
+------------------------+-----------+---------------+----------+
|         PROXY          | LISTENERS | VIRTUAL HOSTS |  STATUS  |
+------------------------+-----------+---------------+----------+
| external-gateway-proxy | :::8080   | 102           | Accepted |
|                        | :::8443   |               |          |
| gateway-proxy          | :::8080   | 36            | Accepted |
|                        | :::8443   |               |          |
| internal-gateway-proxy | :::8080   | 48            | Accepted |
|                        | :::8443   |               |          |
+------------------------+-----------+---------------+----------+

C:\Windows\system32>kubectl logs -n gloo-system deploy/rate-limit -f
Found 2 pods, using pod/rate-limit-767f4675bf-wzw6l
{"level":"info","ts":"2022-06-14T15:17:00.581Z","caller":"redis/driver_impl.go:51","msg":"connecting to redis on tcp redis:6379 with pool size 10","version":"1.11.0-rc3"}
{"level":"info","ts":"2022-06-14T15:17:00.583Z","caller":"server/server.go:82","msg":"Listening for HTTP readiness checks at [:18080/ready]","version":"1.11.0-rc3"}
{"level":"info","ts":"2022-06-14T15:17:00.583Z","caller":"server/server.go:92","msg":"Listening for gRPC on [:18081]","version":"1.11.0-rc3"}
{"level":"info","ts":"2022-06-15T07:30:24.799Z","caller":"xds/module.go:131","msg":"closed grpc connection","version":"1.11.0-rc3","address":"gloo:9977"}
{"level":"info","ts":"2022-06-27T11:33:42.056Z","caller":"xds/module.go:131","msg":"closed grpc connection","version":"1.11.0-rc3","address":"gloo:9977"}
{"level":"info","ts":"2022-06-29T07:28:16.702Z","caller":"xds/module.go:131","msg":"closed grpc connection","version":"1.11.0-rc3","address":"gloo:9977"}
{"level":"info","ts":"2022-06-29T16:55:10.357Z","caller":"xds/module.go:131","msg":"closed grpc connection","version":"1.11.0-rc3","address":"gloo:9977"}

### Steps to reproduce the bug

Deploy several Ratelimits based on https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/crds/ then do some configuration error on one of the RatelimitingConfigs, then fix the issue, ensure that the Proxy are in Accepted state, and the check logs of deploy/rate-limit to ensure no errors

### Expected Behavior

The APIs should throw 429 when the ratelimit is exceeded

**Comment by bcollard** [comment]
can we close this issue?

**Comment by Akhil-ZF** [comment]
Yes..
