### ISSUE TITLE
TLS handshake failure when using isolateVirtualHostsBySslConfig=true property  

### ISSUE THREAD

**Issue by avizov** [solo-io/gloo#6677]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

Using the "isolateVirtualHostsBySslConfig" option together with hybrid gateways and matchable gateways leads to tls handshake failures. 
In the envoy configuration dump we saw that all the filter chains were duplicated for all sni domains (appears twice).
After enabling this option, we saw that the tls inspector filter was added. 

### Steps to reproduce the bug

configure environment as described above

### Expected Behavior

ssl handshake should work

**Comment by nrjpoddar** [comment]
@sam-heilbron should this be closed?

**Comment by gunnar-solo** [comment]
the newest addition to this feature (helm chart updates) has been released with `v1.11.39`
