### ISSUE TITLE
Breaking changes when importing solo-apis for custom operators

### ISSUE THREAD

**Issue by pseudonator** [solo-io/gloo#6688]
### Gloo Edge Version

`1.7.x`/`1.8.x`/`1.9.x`/`1.10.x`

### Kubernetes Version

`1.22.x`

### Describe the bug

It seems like the `status` stanza has changed between versions which is causing some pain for consumers of solo-apis. We have a number of customers consuming solo-apis for custom operators.

In the case of `1.7.x`/`1.8.x`,
```
'status': {'reportedBy': 'gateway',
            'state': 1,
            'subresourceStatuses': {'*v1.Proxy.gloo-system.gateway-proxy': {}}}}
```
`1.9.16`  (subgrouping introduced)
```
'status': {'statuses': {'gloo-system': {'reportedBy': 'gateway',
                                         'state': 1,
                                         'subresourceStatuses': {'*v1.Proxy.gloo-system.gateway-proxy': {'reportedBy': 'gloo',
                                                                                                         'state': 1}}}}}}
```
`1.10.26` (`*v1.Proxy.gloo-system.gateway-proxy` renamed)
```
'status': {'statuses': {'gloo-system': {'reportedBy': 'gateway',
                                         'state': 1,
                                         'subresourceStatuses': {'*v1.Proxy.gateway-proxy_gloo-system': {'reportedBy': 'gloo',
                                                                                                         'state': 1}}}}}}
```

This is further reported in [customer ticket](https://solo-io.zendesk.com/agent/tickets/802).

### Steps to reproduce the bug

NA

### Expected Behavior

Have consistent behaviour between version upgrades.
If not we need to have some recommendation in place.

**Comment by nrjpoddar** [comment]
@pseudonator from an API point of view we can't make the status API backwards compatible so what we do in our controller is to ignore an existing status object if an controller cannot understand it and just start updating it with your schema. Does that work for this customer as they have their own controller?

cc @nfuden @sam-heilbron

**Comment by pseudonator** [comment]
Some how i missed this reply. Are you saying just ignore any diffs in status ?
cc @nfuden @sam-heilbron @nrjpoddar

**Comment by nrjpoddar** [comment]
yes

**Comment by pseudonator** [comment]
I have given this feedback to the customer and they are happy with the response. Closing
