### ISSUE TITLE
Default value missing for validationServerGrpcMaxSizeBytes

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#6697]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

A default value is missing for validationServerGrpcMaxSizeBytes in case not provided in the setting crd, validationServerGrpcMaxSizeBytes is not a mandatory field, so anyone upgrading from a prior version that doesn't have a default in the setting will face the following bug in the gateway pod: 

```
{"level":"error","ts":"2022-07-07T22:25:45.651Z","logger":"gateway.v1.event_loop.gateway","caller":"syncer/setup_syncer.go:343","msg":"error: event_loop: 1 error occurred:\n\t* failed to add proxy validation results to reports: internal err: communication with proxy validation (gloo) failed: All attempts fail:\n#1: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (397 vs. 0)\n\n","version":"1.11.20","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/syncer.RunGateway.func1\n\t/workspace/gloo/projects/gateway/pkg/syncer/setup_syncer.go:343"}

```

### Steps to reproduce the bug

- Install Gloo edge 1.11.20 ( or EE 1.11.24)
- Create a demo vs + upstream 
- Modify the setting CR to remove the value validationServerGrpcMaxSizeBytes
- Restart the gateway and gloo pod
- check the gatway pod log 
 

### Expected Behavior

A default value is provided

**Comment by bewebi** [comment]
A fix has been merged into all Gloo LTS branches and will be released the next time those branches are released and eventually trickle to EE versions as well
If this fix urgently needs to be released in a particular version please reopen and say which version (and OSS or EE) and we will prioritize that
