### ISSUE TITLE
Backport ValidatingWebhookConfiguration helm hook to 1.11.x

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#6699]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

A customer is not able to make changes in `gloo-gateway-validation-webhook-gloo-system` because of helm settings, I see it is fixed in 1.12.x
`https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml#L12`

Can you please backport?

### Steps to reproduce the bug

`https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml#L12`

### Expected Behavior

You cannot change for instance the `gloo.gateway.validation.failurePolicy` through the helm chart after initial install, and you have to manually edit the object.

**Comment by jenshu** [comment]
this should already be there on Gloo OSS v1.11.10 / Gloo EE v1.11.9 or later.
@jmunozro can you ask customer to try on a more recent version?

**Comment by jenshu** [comment]
closing, as it should already be in 1.11.x
please reopen if you still see any issues
