### ISSUE TITLE
Updating to newer versions of knative serving

### ISSUE THREAD

**Issue by TommyM** [solo-io/gloo#673]
I was wondering if it is possible to leverage Gloo while staying up to date with the 6 week release cycle of knative serving. 0.4.0 and 0.5.0 introduced some features that I would like to leverage, but I am not sure if and how I can easily update knative serving and still have the Gloo integration work properly.

Also, are there plans to have a `glooctl update` command in the future that will update gloo and knative in the cluster?

**Comment by ilackarms** [comment]
@TommyM if you have intsalled Knative on your own, it should work (unless there were any breaking changes to the ClusterIngress CRD, which I don't see looking over the Knative docs).

We'll have a release of `glooctl` soon that will install the latest version of Knative

**Comment by ilackarms** [comment]
`glooctl install knative` has been updated
