### ISSUE TITLE
glooctl install knative fails

### ISSUE THREAD

**Issue by trusch** [solo-io/gloo#677]
When I install gloo + knative on a fresh cluster the activator is constantly throwing errors:

```
{"level":"error","ts":"2019-04-15T10:15:02.893Z","logger":"activator","caller":"activator/revision.go:147","msg":"Failed to activate the revision.{error 25 0  Unable to get revision: resource name may not be empty}","commit":"4d198db","knative.dev/controller":"activator","knative.dev/key":"/","stacktrace":"github.com/knative/serving/pkg/activator.(*revisionActivator).ActiveEndpoint\n\t/usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/activator/revision.go:147\ngithub.com/knative/serving/pkg/activator.(*dedupingActivator).activate\n\t/usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/activator/dedupe.go:85"}
{"level":"error","ts":"2019-04-15T10:15:02.893Z","logger":"activator","caller":"handler/handler.go:52","msg":"Error getting active endpoint: Unable to get revision: resource name may not be empty","commit":"4d198db","knative.dev/controller":"activator","stacktrace":"github.com/knative/serving/pkg/activator/handler.(*ActivationHandler).ServeHTTP\n\t/usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/activator/handler/handler.go:52\ngithub.com/knative/serving/pkg/activator/handler.(*EnforceMaxContentLengthHandler).ServeHTTP\n\t/usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/activator/handler/enforce_length_handler.go:32\ngithub.com/knative/serving/pkg/activator/handler.(*RequestEventHandler).ServeHTTP\n\t/usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/activator/handler/requestevent_handler.go:64\ngithub.com/knative/serving/pkg/activator/handler.(*FilteringHandler).ServeHTTP\n\t/usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/activator/handler/filtering_handler.go:36\ngithub.com/knative/serving/vendor/golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP\n\t/usr/local/google/home/mattmoor/go/src/github.com/knative/serving/vendor/golang.org/x/net/http2/h2c/h2c.go:98\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/google-golang/src/net/http/server.go:2740\nnet/http.(*conn).serve\n\t/usr/lib/google-golang/src/net/http/server.go:1846"}
```

I did not deploy anything on top of it. Just a raw `glooctl install knative`. I also used the most recent released version of glooctl.

Also there are no revisions installed in the cluster, so I dont get how this error can happen.

**Comment by ilackarms** [comment]
hey @trusch 

the error you're seeing can be ignored. Gloo runs an optimistic function discovery service in the `discovery` pod. one thing this service does is [attempt to query discovered services for an OpenAPI specification](https://github.com/solo-io/gloo/blob/master/projects/discovery/pkg/fds/discoveries/swagger/swagger.go#L27). this is what's causing the "error" (and thus it can be ignored). i believe that knative can still function normally.

what we aim to do is enable the use of annotations to give the user control of which namespaces and services are probed by `fds`, I just opened an issue to track it #678 . we will make sure that knative is installed with the correct annotation to prevent `fds` from probing those services.

until then you should be able to ignore this error, sorry if it provides any inconvenience.

please let us know if knative itself is not working as expected. if so, i think we could close this issue and track with #678

**Comment by rickducott** [comment]
Closing per the above comment.
