### ISSUE TITLE
support for AWS upstream with secure IAM role access

### ISSUE THREAD

**Issue by akitekt** [solo-io/gloo#680]
In some organizations, AWS keys and secrets are considered not secure and therefore disallowed. Same for us, we have to use IAM roles(Instance profiles)

More context:
IAM roles are attributed through instance profiles and are accessible by services through the transparent usage by the aws-sdk of the ec2 metadata API; 
Tools like kube2iam works as a DaemonSet on every VM and intercept the EC2 metadata API from every pod. Therefore, we have pod level IAM role control.
Later, the metadata api will return the temp credentials for future AWS API calls such as Lambda API calls in this scenario(AWS upstream)

**Comment by yuval-k** [comment]
For references, this is how AWS were planning to add IAM fetch for envoy (wasn't merged yet): https://github.com/envoyproxy/envoy/pull/5546

**Comment by ilevine** [comment]
needed envoy code was merged.
