### ISSUE TITLE
grpc passthrough connection retries configurable

### ISSUE THREAD

**Issue by huzlak** [solo-io/gloo#6804]
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

Basically the flow is:
1) Gloo comes online, configured with ExtAuth to connect to an unavailable grpc Passthrough upstream.
2) Gloo complains about possibly being unable to establish the connection
3) Auth upstream service comes online, grpc is exposed
4) 100 requests over N minutes, sent against Gloo, which goes through grpc auth upstream. 401: extauthz_denied
5) Make small configuration change to AuthConfig to make Gloo’s Envoy’s ExtAuthz grpc client to reconnect to grpc server
6) Connection established
7) requests now working.

### Describe the solution you'd like

Have the retry configurable, similar to: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/retries/retries.proto.sk/#retrypolicy , I can see adding someting like perTryDelay could also be useful in this scenario.

## Related Issues

- [ ] https://github.com/solo-io/ext-auth-service/issues/705

**Comment by davidjumani** [comment]
Added in [v1.16.2](https://github.com/solo-io/solo-projects/releases/tag/v1.16.2) && [v1.15.13](https://github.com/solo-io/solo-projects/releases/tag/v1.15.13)

Note : This new feature only retries auth requests once the initial connection has been made to the passthrough service.
If the passthrough auth service is unavailable during the initial dial itself, the connection can not be established and all subsequent auth requests will fail. This can be mitigated by adding a longer connection_timeout with the hope that the passthrough service becomes available within the timeout.
