### ISSUE TITLE
Support Consul Service and Endpoint Allowlisting

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#6815]
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

Gloo currently discovers and tracks all Consul Services and Endpoints within a datacenter. This causes scalability and performance problems when a datacenter contains large number of each. 

### Describe the solution you'd like

I'd like to be able to configure a whitelist of services that Gloo will discover

**Comment by kdorosh** [comment]
this will help and is useful, but may not be necessary to scale once we implement https://github.com/solo-io/gloo/issues/6599#issuecomment-1215887115

**Comment by kdorosh** [comment]
I think the idea is to explore consul filter api and support flexible and powerful accept / deny list
