### ISSUE TITLE
CI Test Flake: [It] Should be able to rotate a secret referenced on a sslConfig on a kube upstream 

### ISSUE THREAD

**Issue by inFocus7** [solo-io/gloo#6819]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

Test flake in during CI's `CI / k8s regression tests (gloo, false)` job.

```
• Failure [280.034 seconds]
GlooResourcesTest rotating secrets on upstream sslConfig [It] Should be able to rotate a secret referenced on a sslConfig on a kube upstream 
/home/runner/work/gloo/gloo/test/kube2e/gloo/gloo_resources_test.go:253

  Expected
      <string>: no healthy upstream
  to contain substring
      <string>: Hello, world!

  /home/runner/work/gloo/gloo/test/kube2e/gloo/gloo_resources_test.go:284
```

### Steps to reproduce the bug

Run CI tests on a PR.

### Expected Behavior

It should pass.

### Additional Context

- [suite log](https://github.com/solo-io/gloo/runs/7563853161?check_suite_focus=true)

**Comment by elcasteel** [comment]
another instance of this https://github.com/solo-io/gloo/runs/8005352415?check_suite_focus=true
