### ISSUE TITLE
Lambda requestTranformation not sending headers or querystring

### ISSUE THREAD

**Issue by jaymiracola** [solo-io/gloo#6838]
### Gloo Edge Version

1.10.x

### Kubernetes Version

1.20.x

### Describe the bug

According to documentation, we should be able to set requestTransformation: true to "Include headers, querystring, request path, and request method in the event payload sent to aws lambda." In version GE 1.11 / k8s 1.22 I see everything but querystring being passed to the Lambda. In GE 1.10/ k8s 1.20 I see no querystring and very few headers. Both in EKS using CLB with identical deployment manifests and lambda functions.

### Steps to reproduce the bug

1. Create a Lambda to log
2. Create the AWS secret
3. Create the AWS upstream
4. Create the VS including `requestTransformation: true` 
5. Curl gloo proxy 

### Expected Behavior

When setting this option, I expect the headers, querystring, request path, and request method in the event payload sent to aws lambda.

**Comment by ben-taussig-solo** [comment]
The current status of this issue is:
 - the bug is present on Gloo Edge Enterprise v1.10.x
    - headers and the request body are not in the payload sent to the upstream lambda on this branch
 - The bug has been fixed on Gloo v1.11.x+
 - The bug can be resolved on Gloo Edge enterprise v1.10.x by backporting [this fix](https://github.com/solo-io/gloo/pull/6068)

**Comment by ben-taussig-solo** [comment]
Closing for now as this is fixed in v1.11.x+
