### ISSUE TITLE
validate Gloo Edge runs OK on k8s v1.23 and v1.24

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6842]
### Is your feature request related to a problem? Please describe.

Customers asking for official support of GE on the latest versions of Kubernetes.
Our [release support](https://docs.solo.io/gloo-edge/latest/reference/support/) web page is stuck on v1.22

### Describe the solution you'd like

Please review CI pipelines and amend the doc.

**Comment by alex-berger** [comment]
Any news on this? The documentation at https://docs.solo.io/gloo-edge/master/reference/support/ is a bit confusing as it says that gloo-edge 1.11 and 1.12 are supported on Kubernetes versions 1.21 to 1.24, but at the same time it also states that gloo-edge is only tested against Kubernetes versions 1.21 to 1.22.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1087375/199698370-1a5e4b5f-48cf-4cac-b7b3-9b9d65479589.png">

Now, I am wondering is this a documentation bug, or how do I have to interpret that information?

**Comment by sam-heilbron** [comment]
We now support weekly runs of our tests suites, using the oldest and newest version of the Kubernetes versions that we support: https://github.com/solo-io/gloo/blob/main/.github/workflows/nightly-tests.yaml#L34
