### ISSUE TITLE
support AWS NLB and ALB for Gloo gateway

### ISSUE THREAD

**Issue by akitekt** [solo-io/gloo#686]
Currently, only ELB is supported. Unfortunately, AWS is considering ELB as a classic/legacy solution. Some features like WAF only support ALB.

**Comment by akitekt** [comment]
@christian-posta

**Comment by ilevine** [comment]
this involves testing, helm chart changes, and docs.

**Comment by scranton** [comment]
Added documentation on how to use AWS NLB with Gloo https://github.com/solo-io/gloo/pull/2150
