### ISSUE TITLE
bindAddr: 0.0.0.0 not working anymore in clusters that don't support ipv6 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#6860]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

Creating a gateway with bindAddr: 0.0.0.0 results in the following error in clusters where ipv6 is not supported: 

```
"details": "malformed IP address: ::ffff:0.0.0.0"
     }
    },
    {
     "name": "listener-0.0.0.0-8443",
     "error_state": {
      "failed_configuration": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "listener-0.0.0.0-8443",
       "address": {
        "socket_address": {
         "address": "::ffff:0.0.0.0",
         "port_value": 8443,
         "ipv4_compat": true
        }
```

### Steps to reproduce the bug

Install Gloo 1.12 on a cluster with ipv4 deactivated  
create/modify a gateway CR to change `:: -> 0.0.0.0`

### Expected Behavior

Working

**Comment by nfuden** [comment]
Reopening until released in ee
