### ISSUE TITLE
Automatically add l5d-dst-override

### ISSUE THREAD

**Issue by rettori** [solo-io/gloo#692]
According to Linkerd docs:

> If you’re planning on injecting Linkerd into your ingress controller’s pods there is some configuration required. Linkerd discovers services based on the :authority or Host header. This allows Linkerd to understand what service a request is destined for without being dependent on DNS or IPs.

this request is to add a global and virtualservice scoped configuration that allows the `l5d-dst-override` to be automatically added.

the value of the header should be `$upstreamService.$upstreamNamespace.svc.cluster.local:$upstreamPort`

**Comment by rettori** [comment]
When this gets implemented, changes also need to be made here: https://linkerd.io/2/tasks/using-ingress/ to reflect the new configuration options.

**Comment by yuval-k** [comment]
resolved by https://github.com/solo-io/gloo/pull/703
