### ISSUE TITLE
Helm template for settings  CRD renders incorrectly

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#694]
We set the content of the `.Values.settings.watchNamespaces` value, which is an array, into a single entry:
```yaml
{{- with .Values.settings.watchNamespaces }}
  watchNamespaces:
  - {{ . }}
{{- end }}
```
and helm’s template engine renders it to this:
```yaml
watchNamespaces:
  - [devopsks3 devopsks2]
```

Which results in this value in the spec CRD:
```yaml
watchNamespaces:
    - - devopsks3 devopsks2
```
which is valid YAML, but causes all namespaces to be watched.

**Comment by akitekt** [comment]
This is my expected input format in values.yaml, is this the right assumption?
settings:
  create: true
  watchNamespaces:
    - devopsks2
    - devopsks3
