### ISSUE TITLE
Offer option on Lambda upstreams to assume web identity directly instead of using credential chaining

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#6941]
### Is your feature request related to a problem? Please describe.

An enterprise customer is facing issues with Lambda delegation failing, probably due to AWS credential chaining. They would like to have an option per Lambda upstream to decide if it chains or assumes via the webidentity directly.

AWS context:
https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html

### Describe the solution you'd like

Add an option per Lambda upstream to decide if it chains or assumes via the webidentity directly.

### Additional Context

Internal Slack thread:
https://solo-io.slack.com/archives/G0133U4GUP5/p1658182337612769

**Comment by nfuden** [comment]
This is handled via the disableRoleChaining on an upstream
