### ISSUE TITLE
Validation: Auto accept status only updates

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#6990]
### Is your feature request related to a problem? Please describe.

Status writes cause validation requests that kick off a sample translation which adds lots of overhead especially at scale.
We should accept status writes by default along with a future piece of work to make persisting statuses optional.

**Comment by nfuden** [comment]
Relates to https://github.com/solo-io/gloo/issues/6936

**Comment by sam-heilbron** [comment]
This has been introduced into 1.13 (merged, not released) and 1.12 (released).
