### ISSUE TITLE
glooctl proxy url not working on kind cluster

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#701]
When using the kind (https://github.com/kubernetes-sigs/kind) cluster, glooctl proxy url does not appear to work correctly. Identical deployment on minikube does work.

**Comment by scranton** [comment]
Looks like `glooctl proxy url` correctly returns gateway-proxy Pod NodeIP and service http port, but no content is returned from that connection.

**Comment by derrickburns** [comment]
Did you get Gloo to work with `kind`.  I did not.

**Comment by ilevine** [comment]
duplicate of #730 
this is most likely a Mac issue as gloo is tested to work on kind on linux.
