### ISSUE TITLE
E2e upgrade from last minor version

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#7022]
### Is your feature request related to a problem? Please describe.

Today we try best effort upgrade testing and attempt to verify that any given change doesnt break.

### Describe the solution you'd like

To ensure that in a reasonable kubernetes environment we can upgrade without fail we should add a new kube2e test that attempts to upgrade from the previous minor and a reasonable subset of current minor's patch versions.
This means that any upgrade steps would be codified in the test itself.

**Comment by sam-heilbron** [comment]
This is introduced here: https://github.com/solo-io/gloo/tree/main/test/kube2e/upgrade
