### ISSUE TITLE
Gateway robustness e2e Test Cleanup

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#7038]
### Gloo Edge Version

1.12.x (latest stable)

### Describe the bug

Recent flake count is high for  Robustness tests Updates Envoy endpoints, even if proxy is invalid works, even with deleted services [It] works, even with deleted services 

This makes all CI and therefore all work take much longer.

### Steps to reproduce the bug

Run a pr through CI on 1.12 or 1.13 post leader election. 

### Expected Behavior

No subtest fails

**Comment by elcasteel** [comment]
We have a separate issue open for this, but I'm seeing the domain conflict issue relatively frequently during robustness test runs: https://github.com/solo-io/gloo/runs/8078063464?check_suite_focus=true
