### ISSUE TITLE
Helm unit tests don't work locally 

### ISSUE THREAD

**Issue by elcasteel** [solo-io/gloo#7063]
### Gloo Edge Version

1.13.x (beta)

### Describe the bug

When you have the gloo repo cloned (not from a fork) helm unit tests fail on a setup step in this method: https://github.com/solo-io/gloo/blob/master/install/test/helm_suite_test.go#L111

I'm not sure if there's a more consistent way to check the version or if we need additional branching for fork/non-fork somewhere.

### Steps to reproduce the bug

Run the tests

### Expected Behavior

CI should work from a fork and from a cloned repo

**Comment by sam-heilbron** [comment]
Resolved on latest branches by the above PR.
