### ISSUE TITLE
CP gets stuck reporting missing resources at scale w/multiple namespaces

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#7076]
### Gloo Edge Version

1.12.x (latest stable)

### Describe the bug

With 100s/1000s of VirtualServices, Upstreams, RateLimitConfigs, and AuthConfigs deployed to 3+ namespaces the CP gets stuck reporting missing resources that exist.

The attached state has persisted for over an hour.

### Steps to reproduce the bug

Run the attached script in 3+ namespaces and run `glooctl check`

### Expected Behavior

No hang

**Comment by bdecoste** [comment]
[state.log](https://github.com/solo-io/gloo/files/9478352/state.log)

**Comment by bdecoste** [comment]
Bouncing the pods results in exactly the same state

**Comment by bdecoste** [comment]
[create_vs.tar.gz](https://github.com/solo-io/gloo/files/9507790/create_vs.tar.gz)

**Comment by kdorosh** [comment]
perhaps related https://github.com/solo-io/gloo/issues/7148

**Comment by elcasteel** [comment]
We identified two bugs that we think were the primary problem here and opened issues to track them:
Sometimes leader changes leave us with incomplete statuses https://github.com/solo-io/gloo/issues/7148
Glooctl reports resources without statuses as "missing": https://github.com/solo-io/gloo/issues/7153
