### ISSUE TITLE
Validation is slow (15-30mins) for config updates to data plane 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#7105]
### Gloo Edge Version

1.12.x (latest stable)

### Describe the bug

With config at scale (1000s of VirtualServices, Upstreams, RateLimitConfigs, AuthConfigs, etc.) it takes 15-30 mins for a valid config change to be validated and updated in the data plane 

### Steps to reproduce the bug

TBD

### Expected Behavior

Better performance at scale

**Comment by elcasteel** [comment]
In parallel with the work to optimize writing statuses, I'm going to take on removing our remaining uses of proto.Clone: https://github.com/solo-io/gloo/issues/7139

**Comment by elcasteel** [comment]
I'm taking reducing the number of times we clone proxies (within the memory proxy client): https://github.com/solo-io/gloo/issues/7166

**Comment by nfuden** [comment]
Closing out this pseudo epic as many of the sub issues have been resolved/made
