### ISSUE TITLE
Statuses can get stuck if no leader elected and no more changes

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#7148]
### Gloo Edge Version

1.13.x (beta)

### Kubernetes Version

1.24.x

### Describe the bug

this check https://github.com/solo-io/gloo/blob/55c6d1a295e429cac986f182a65bc34edcec2e0d/projects/gloo/pkg/syncer/translator_syncer.go#L105 also serves to prevent status updates (good) but when there is no leader currently elected all updates to statuses are stalled until the election is complete

### Steps to reproduce the bug

was cycling the gloo pod while debugging, saw statuses get stuck

### Expected Behavior

statuses always get applied. when a new leader is elected it should immediately write it's state of the world to CR statuses for debugging

**Comment by sam-heilbron** [comment]
This well need to go into 1.12 as well
