### ISSUE TITLE
Remove all Panics from the control plane

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#7174]
### Is your feature request related to a problem? Please describe.

Panic is generally dangerous and causes unexpected code paths to crash.
We can replace it with context dpanic as it will still crash in dev mode and be caught during testing but will not bring down the cp.
https://go.dev/blog/defer-panic-and-recover
See the discussion here as to the pitfalls of panic in long running code such as servers or in our example the control plane.

**Comment by gunnar-solo** [comment]
explicitly calling out that was _also_ want to remove references to `log.Fatal`
