### ISSUE TITLE
unable to set nodeselector, resources or pod affinity when deploying using helm

### ISSUE THREAD

**Issue by ostmike** [solo-io/gloo#720]
There doesn;t seem to be anything in the helm manifests to facilitate these bits. I've created a branch and am happy to push and raise a PR, just need permissions to push if possible please.

**Comment by ilevine** [comment]
feel free to create a PR - we would love to review it.

**Comment by rickducott** [comment]
Closing as stale - let us know if you'd still like to contribute this change! We can support fork gitflows in CI.
