### ISSUE TITLE
Virtual host name is ignored 

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#721]
The title says it all

**Comment by ilackarms** [comment]
the name of the virtual host can be ignored when working with the virtual service

the same field cannot be ignored when used in the proxy object

is there something you need it for?

**Comment by derrickburns** [comment]
I'm sorry. I was not clear.

What I mean is that if I supply a virtual host name, it is ignored and replaced by one generated by Gloo.

To see this, create a virtual service and read it back. Compare the virtual host names.

**Comment by ilevine** [comment]
we should probably remove the name field in the docs \ schema for VirtualService.
We are adding support for CRD Schemas soon, so should be part of that effort.

**Comment by rickducott** [comment]
The API has been updated
