### ISSUE TITLE
Need easy way to get version info for installed gloo

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#722]
`glooctl --version` provides a version of the glooctl binary and the version of gloo that it would install. If gloo was installed independently, e.g., helm, then it may be a different version then the glooctl on the users desktop.

Ideal if we modeled after `kubectl version` that reports both client and server version

**Comment by xpepermint** [comment]
If possible add support also for displaying the version of the installed `knative`.

**Comment by rickducott** [comment]
AFAIK this will break our homebrew/go-fish formulas so we need to be careful with the change.

**Comment by scranton** [comment]
It could potentially break the test code in the homebrew glooctl formula (https://github.com/Homebrew/homebrew-core/blob/master/Formula/glooctl.rb#L36). We'd need to coordinate this feature enhancement with an update to the homebrew glooctl formula.

The other package managers do NOT do tests against the `glooctl --version` output.

**Comment by ilevine** [comment]
we probably need to add a api endpoint that returns the gloo version; so we have a consistent solution that works with VMs as well.

**Comment by mitchdraft** [comment]
perhaps using something like `--version-deployed` if we don't want to upset the package managers or overload the flag

**Comment by scranton** [comment]
We'd only need to fix homebrew-core/glooctl, and we can be proactive around adjusting its version test code. Let's figure out right approach, and then we can manage around changes. I like the idea of an API for server component versions - gloo, knative, etc. and having this summarized in a glooctl --version feels consistent with other k8s tooling so something most users would expect and "know" where to look for it.
