### ISSUE TITLE
Upgrade Unit tests to Ginkgo v2

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#7222]
### Is your feature request related to a problem? Please describe.

Our current ginkgo is deprecated and does not have the same functionality as the newer variant.

### Describe the solution you'd like

Upgrade the unit tests to use the new version of ginkgo.

### Describe alternatives you've considered

Do a big bang change to ginkgov2 (but thats alot of changes)

### Additional Context
Big bang approach was pretty overwhelming. Over 350 files changed and it wasnt even fully fixed https://github.com/solo-io/gloo/pull/6172

**Comment by sam-heilbron** [comment]
The following tasks are required:
- [ ] Upgrade k8s-utils to use ginkgo v2 (https://github.com/solo-io/k8s-utils/pull/32)
- [ ] Release k8s-utils
- [ ] Upgrade go-utils to use ginkgo v2 (https://github.com/solo-io/go-utils/pull/506)
- [ ] Release go-utils
- [ ] Upgrade solo-kit to use ginkgo v2 (https://github.com/solo-io/solo-kit/pull/537)
- [ ] Release solo-kit
- [ ] Upgrade gloo to use ginkgo v2
- [ ] Release gloo
- [ ] Upgrade ext-auth-service to use ginkgo v2
- [ ] Release ext-auth-service
- [ ] Upgrade rate-limiter to use ginkgo v2
- [ ] Release rate limiter
- [ ] UPgrade GlooE to use ginkgo v2
- [ ] Release GlooE

**Comment by sam-heilbron** [comment]
This has been merged into our main branches of Gloo OSS and Gloo Enterprise.
