### ISSUE TITLE
Create static upstream with swagger url via command line

### ISSUE THREAD

**Issue by eddiechihyi** [solo-io/gloo#723]
There're 2 issues I noticed while trying to create static REST based upstream. Let me know if you can shed some light on this issue.

I was able to create the upstream via Gloo enterprise UI but I have to copy/paste the whole swagger text into the "swagger Doc" field in the UI which is not great. There's no other option to put in the URL only.

When I tried to use the command line to create upstream (see below). There's also no argument allow me to specify the swaggerInfo as url.

_`glooctl create upstream static activity --static-hosts xxx.xxx.xxx.xxx:80 --namespace gloo-system`_

**Comment by rickducott** [comment]
I'm going to close this as stale -- we'd welcome a contribution to update the CLI to support this flag!
