### ISSUE TITLE
static REST upstream to support path prefix? 

### ISSUE THREAD

**Issue by eddiechihyi** [solo-io/gloo#724]
Our application is consisting of multiple microservices running in Docker containers. All the microservices are REST based and exposed via the same domain name with different URIs. For example, we have services serviceA and serviceB are

   Service A:    www.myApp.com/dev-serviceA/
   Service B:    www.myApp.com/dev-serviceB/

I can't seem to find a way to create independent static upstream for each REST service. The current command ("glooctl create upstream static") only takes host & port while creating static upstream. Is there any way to put in URI/prefix as part of the command?

**Comment by yuval-k** [comment]
the prefix comes in the routing part, not in the upstream. see here: https://gloo.solo.io/user_guides/advanced_route_plugins/#base-example

**Comment by ilevine** [comment]
hopefully this answers your question - feel free to reopen if needed
