### ISSUE TITLE
Fed canary upgrades: docs

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#7240]
### Version

1.13

### Is your feature request related to a problem? Please describe.

Once the feature is completed, we should add a page in the docs detailing Gloo Fed canary upgrades.
* See Milestone: https://github.com/solo-io/gloo/milestone/35

### Describe the solution you'd like

* We would need to update this page with a new section for how to do a canary upgrade w fed: https://docs.solo.io/gloo-edge/latest/operations/upgrading/canary/
* And then maybe we would need to update this page w fed info too..? https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/canary/

### Additional Context

Slab doc: https://soloio.slab.com/posts/gloo-fed-canary-upgrades-3r5fowf6

**Comment by Nadine2016** [comment]
https://soloio.slab.com/posts/gloo-fed-canary-upgrades-3r5fowf6
