### ISSUE TITLE
Excluded Body Params Being Sent To Services

### ISSUE THREAD

**Issue by jshartar** [solo-io/gloo#7246]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

gloo-edge-1.12.22
EKS: v1.22.12

I am using the schema stitching feature to return grpc to json/rest response for our api. With the latest patch, I was testing the stitching. I noticed that the params sent in via the body of the request will always send in some default value. (ie: string: ""). I would like for the excluded params to not be included in the requests to the grpc services. 

### Steps to reproduce the bug

sent body: 
`{
  "getFacilitiesRequest": {
    "params": {
      "limit": {
        "value": 1
      }
    }
  }
}`

results in every possible param being sent in with default value. 

### Expected Behavior

When I send a request I want only the params included in the body to be populated and sent to the grpc services. 

### Additional Context

Please contact. Jordan Shartar in the "parkmobile" slack channel for any questions.

**Comment by saiskee** [comment]
this was fixed by changing configuration to not include every field when configuring the outgoing response, only the parent field.
