### ISSUE TITLE
Failover only if all the hosts are not available 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#7258]
### Version

1.13.x (beta)

### Is your feature request related to a problem? Please describe.

Today, if we have an upstream with multiple hosts, and 1 failover endpoint, it will call the failover endpoint if one of the hosts are not available. 

Provide an option (or fix current behavior) to failover only if all the hosts are not available.

**Comment by asayah** [comment]
overprovisioning_factor can help here

**Comment by kdorosh** [comment]
resolved in https://github.com/solo-io/solo-projects/pull/4141 and already released in 1.12 enterprise
