### ISSUE TITLE
Enable OTel tracer

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#7269]
### Version

1.13.x (beta)

### Is your feature request related to a problem? Please describe.

A user is interested in having this tacer so that is can leverage context in the traces.

So far we offer zipkin tracer and datadog configuration. But there is also [OTel tracer](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opentelemetry.proto#envoy-v3-api-msg-config-trace-v3-opentelemetryconfig) which would be very interesting for users.

### Describe alternatives you've considered

There are no alternatives since the zipkin tracer does not offer context propagation.

**Comment by sam-heilbron** [comment]
@antonioberben 

In the Envoy docs, this feature is flagged with:
```
This extension is work-in-progress. Functionality is incomplete and it is not intended for production use.

This extension has an unknown security posture and should only be used in deployments where both the downstream and upstream are trusted.
```

We can flag this as well in our public facing docs. Is introducing this to the 1.13 beta alone (and not 1.12) reasonable?

**Comment by antonioberben** [comment]
@sam-heilbron , makes totally sense. I will share it with the user. the point of the doumentation is great, thanks!
