### ISSUE TITLE
Add option to log to file for ExtAuth

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#7299]
### Version

1.12.x (latest stable)

### Is your feature request related to a problem? Please describe.

Add an option for extAuth to log to a file instead of std out

**Comment by chrisgaun** [comment]
This may be a dupe

**Comment by sam-heilbron** [comment]
Extauth, like all Gloo Edge components will log output to a stream. A logging agent can be configured to persist those logs in a file.

**Comment by kevin-shelaga** [comment]
unfortunately this is not possible due to the use of fargate with this customer

**Comment by sheidkamp** [comment]
@kevin-shelaga - can you provide some more context about how Fargate necessitates logging to a file?

Also, are we expected to "just" log to file, or do we need to think about things like log rotation and adjusting pod lifecycles to try to make sure the log file is consumed before we delete it?

Thanks!

**Comment by sheidkamp** [comment]
Best info I can find comes from here (July 2020):
https://aws.amazon.com/blogs/containers/how-to-capture-application-logs-when-using-amazon-eks-on-aws-fargate/ 

```
For pods running on Fargate, you need to use the sidecar pattern. You can run a Fluentd (or Fluent Bit) sidecar container to capture logs produced by your applications. This option requires that the application writes logs to filesystem instead of stdout or stderr. 

....

We have heard from customers that this is undesirable and we are working to create a solution that doesn’t need application refactoring.
```

Can't find any updates on that last line even though it was from 3 years ago. One change is that Fluentd is no longer required to run in a sidecar container.

**Comment by kevin-shelaga** [comment]
@sheidkamp Fargate doesnt support running a daemonset, so they cant run a DS fluentbit. This leaves us with the only option to run fluentbit as a sidecar, which is unable to process stdout logs.

**Comment by sheidkamp** [comment]
Thanks @kevin-shelaga - Do you know if those tools handle the extra ops kind of concerns that arise with file based logging, like log rotation, local deletion, and container/lifecycle issues (eg, don't delete the pod until all logs have been pulled)?

It also looks like Fargate has supported non-sidecar Fluentbit log collection for a while: `Where previously you had to run a sidecar to route container logs from Amazon EKS pods running on AWS Fargate, you can now use a built-in log router.` ([Blog post](https://aws.amazon.com/blogs/containers/fluent-bit-for-amazon-eks-on-aws-fargate-is-here/))

**Comment by sheidkamp** [comment]
Take-aways from meeting:

- Make it work like gateway: https://docs.solo.io/gloo-edge/latest/guides/security/access_logging/#file-based-access-logging
- They won't be handling like rotation, but see "make it work like gateway"
- We are not expected to expose/implement anything for pod lifecycle concerns

**Comment by sheidkamp** [comment]
Will be in GlooEE v1.14.7, v.1.13.21, and 1.15.0-beta-4.

If we need to fast track one of those releases, I am happy to do that.
