### ISSUE TITLE
Gateway proxy failure when using kind

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#730]
See https://github.com/kubernetes-sigs/kind/issues/577

I suspect that this is an Envoy/Kind issue.  However I discovered it with Gloo.

Key line in logs?:

```
[2019-05-31 01:54:13.790][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, no healthy upstream

```

**Comment by yuval-k** [comment]
I am able to use kind and gloo in my linux laptop; this log line seems to indicate that envoy cannot connect to gloo.
It could be a networking issue, or it could be a resource related issue (I believe that on a mac kind is invoked in the docker VM that may be resource constrained).

is the `gloo` pod alive and well?

**Comment by rickducott** [comment]
Going to close this as stale for now, though we would very much like to support Gloo/Envoy with Kind. Let us know if there are additional issues with Gloo and Kind on Mac.
