### ISSUE TITLE
Lambda wrapAsApiGateway causing Envoy segfault

### ISSUE THREAD

**Issue by jaymiracola** [solo-io/gloo#7307]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.24.x

### Describe the bug

Adding `wrapAsApiGateway: true` in aws.proto without any other specifications will cause Envoy to segfault. It appears adding `requestTranfomation: true` alleviates the issue. 

### Steps to reproduce the bug

Apply the VS matching any Lambda
```apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  annotations:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /helloworld
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: sam-app-HelloWorldFunction-B1nbbA6IRAjq
              wrapAsApiGateway: true
          upstream:
            name: my-aws-upstream
            namespace: gloo-system
```

Attempt to curl the address and observe an Envoy segfault. 

### Expected Behavior

No segfault or make the requirement to include other specs.

**Comment by sam-heilbron** [comment]
Is it a valid use case to set `wrapAsApiGateway` and not set `requestTransformation`?

I think we need to prevent the crash in Envoy, but also this seems like a control plane enhancement to ensure that we properly configure the transformation if it's necessary, even if a user hasn't defined it explicitly.

**Comment by ben-taussig-solo** [comment]
@jaymiracola Could you post the source of the Lambda being used to test this issue and the requests that are being sent to test it?

**Comment by ben-taussig-solo** [comment]
This is resolved with the release of https://github.com/solo-io/solo-projects/releases/tag/v1.12.30
