### ISSUE TITLE
Virtual Services are not composable, despite obvious intention to make them so

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#731]
@yuval-k @rickducott 

After banging my head against the wall trying to figure out why my Gloo API Gateway configuration was not working, I decided to do what all good programmers do.  I read the code.  I discovered that the current Gateway translator in:

https://github.com/solo-io/gloo/blob/master/projects/gateway/pkg/translator/translator.go

has a few major flaws that prevent the VirtualServices from being composable (if your customers want to terminate SSL).  This is not just a design issue, but a practical problem for your customers.

Let me explain.

A Virtual Service is a collection of routes, a list of (SNI) domains, an optional binding to a sslConfig, and some other less important objects.

1. If I want to split my Virtual Service into two pieces for my own convenience, I can do so, but only if there is no sslConfig. 

1. If I want to create two Virtual Services, one that supports SSL and another that does not, then they cannot share a common domain.

Why does the implementation impose these constraints?  I can think of no reason.

Correct me if I am wrong, but I suspect that the actual constraints imposed by Envoy are :

1. at most one mapping from (SNI) domain -> sslContext.  

1. exactly one Envoy listener per port.

1. at least one Envoy virtual service per listener

1. at most one match from an incoming hostname/port to an envoy virtual service, where match means that the hostname matches a the set of SNI domains and SNI regexes associated with the virtual service.

The current translator imposes unnecessary constraints that limit composability in the presence of any SSL termination. A new translator that supports composability would do the following:

1. Partition all virtual services by namespace and whether they support SSL or not.  Associate each (namespace, ssl flag) with a different Gateway. If a Gateway for that namespace already exists and has an explicit list of virtual services, then ignore the partition and use the explicit list.  This must be done **before** the following step. 
1. For each Gateway, create a map from domain to sslConfig (if any) for all virtual services associated with the Gateway.  Confirm that no conflict exists, where a conflict is when there are two  mappings for the same domain to different sslConfigs, where different means different **values**. **The current implementation assumes that any two sslConfigs are presumed different**.
1. For each Gateway, virtual services destined for the same **set** of domains in a single virtual service. This is done properly today.

In my specific case, I want to support both http and https access to my services simultaneously. I cannot do so because I use host-based routing.  

Second, I would prefer that each sub-service define a subset of routes within its own virtual service. If I were not doing SSL, I could do this.  With the way SSLConfigs are handled above, I cannot. I must aggregate all sub-service routes into a single Virtual Service. 

Third, even with the constraints, I need to generate twice as much Gloo yaml configuration code than is necessary.

Please address these issues so that I may use your product in production.

**Comment by yuval-k** [comment]
hi @derrickburns thank you for this feedback!
Overall this makes sense. You suggest to partition virtual services by their ssl config. so you can have groupings per service. That should be relatively easy to accomplish (need to give some thought if we can do it in a backwards compatible way).

The other part is the the  "generate twice configuration code" - One possible solution is to merge all routes both with and without ssl, but in some cases ssl may be a requirement - so need think what's the best way to do this.

we will discuss this internally and should have a plan of attack shortly

**Comment by derrickburns** [comment]
@yuval-k Great! I am glad that the suggestions make sense.

I had not considered merging routes both with and without (using a single config).  However, this probably fine because the actual LoadBalancer service can simply not pass HTTP traffic to the Gateway Proxy if SSL is required. 

How would one implement an HTTP -> HTTPS? redirect with Gloo?
