### ISSUE TITLE
Allow circuitBreakers settings via Helm value 

### ISSUE THREAD

**Issue by danielfablius** [solo-io/gloo#7316]
### Version

1.13.x (beta)

**Comment by danielfablius** [comment]
Expose the circuitBreakers [setting](https://github.com/solo-io/gloo/blob/master/install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml#L359) in the Helm values.

**Comment by danielfablius** [comment]
@gunnar-solo will this changes applied to release ver v1.11.xx ?

**Comment by ashishb-solo** [comment]
@danielfablius we can support that. I'm happy to take care that backport and will do so now
