### ISSUE TITLE
Upgrade Testing: Releases

### ISSUE THREAD

**Issue by ianmacclancy** [solo-io/gloo#7333]
### Is your feature request related to a problem? Please describe.

We can miss breaking changes that make upgrades difficult

### Describe the solution you'd like

We will add a complex test suite run on releases that will aim to capture customer use cases and states of the world that best represent our functionality and upgrade from the current patch to the new patch version

**Comment by kdorosh** [comment]
related https://github.com/solo-io/gloo-ref-arch . we may want to borrow ideas / code from here

**Comment by sam-heilbron** [comment]
This was introduced with the linked PR. While there are likely iterations we can make on this suite, there is no outline for that currently
