### ISSUE TITLE
Need support for CORs for directResponseActions

### ISSUE THREAD

**Issue by salmanrafique-soloio** [solo-io/gloo#7336]
### Is your feature request related to a problem? Please describe.

 Implemented CORs in EWP and observing errors during the deployment.

The resource level route table has two separate matchers. One matcher is for the actual verb i.e., POST which has the routing to the upstream, and the other matcher is for CORs verb i.e., OPTIONS which does not have any routing but has a direct response of 200.

Following are the details:

Error while deployment:

reason: "1 error occurred:\n\t* Route Error: ProcessingError. Reason: *cors.plugin:
cannot use CORs plugin on non-Route_Route route actions.

Can we have the CORs implementation without defining the upstream routing?

### Describe the solution you'd like

The consumer being browser-based initiates the API call and the first call being pre-flight, an OPTIONS call is made to the gateway.

The OPTIONS method is not the functional method from the provider and hence the gateway is handling the OPTIONS method to send the required CORs related headers allowedOrigin, allowedMethods etc., to the consumer with a direct response action.

 
**Hence, the capability to add CORs as part of direct response action without any upstream is required.**

 

### Additional Context

Reference of Zendesk support case:
https://solo-io.zendesk.com/agent/tickets/953

**Comment by ben-taussig-solo** [comment]
Requesting some more information on this issue -- if possible, do you think you could share the configuration with me?

It seems like you are trying to configure the CORS plugin on the OPTIONS matcher. This is explicitly disallowed by gloo and also I think a bit of a step in the wrong direction

I think the ideal path forward is to:
 - Remove the matchers/directResponse actions intended to handle OPTIONS requests
 - Specify the CORS plugin configuration on the matchers that route to the upstream
   - This will handle OPTIONS preflight requests for requests which interact with these matchers

**Comment by ben-taussig-solo** [comment]
I provided a working config during a meeting yesterday afternoon, closing this issue for now

**Comment by bdecoste** [comment]
User requesting that we reopen as this is still a desired feature
