### ISSUE TITLE
Memory leak in GraphQL discovery when enabling gRPC reflection

### ISSUE THREAD

**Issue by pseudonator** [solo-io/gloo#7343]
### Gloo Edge Version

`1.12.21`. This behaviour was also noticed in `1.12.30`

### Kubernetes Version

`1.22.x`

### Describe the bug

We recently diagnosed an issue with a customer on why the discovery controller keeps crashing due to out of memory.

Customer exclusively uses gRPC reflection for gRPC -> REST mapping. In the process of debugging we realized that discovery was trying to create GQL schemas based on the discovered gRPC endpoints.

`{"level":"warn","ts":"2022-10-19T23:32:18.363Z","logger":"fds.v1.event_loop.fds.function-discovery-updater","caller":"grpc-graphql/grpc_reflection.go:128","msg":"Unable to create GraphQLApis from gRPC reflection for upstream redacted-api-8080 in namespace gloo-system: name:\"redacted-api-8080\" namespace:\"gloo-system\" exists","version":"undefined"}`

Further investigation may be required to find out why there is a leak here.

**As a quick and temp fix we switched to using the OSS discovery controller**

### Steps to reproduce the bug

As far as discovery is concerned we limited the number of namespaces via `watchNamespaces` and used the discovery config (in WHITELIST mode) below.

```
  discovery:
    enabled: true
    ## Whitelist mode for FDS polling
    fdsMode: WHITELIST
    udsOptions:
      enabled: false
```

### Expected Behavior

Have the ability to disable GraphQL discovery through gRPC reflection

### Additional Context

This issue ticket is for investigation the actual cause of the memory leak. Further FER tickets will be raised to have better guard rails when creating gRPC -> GQL schemas.
Theres also further information in [customer ticket](https://solo-io.zendesk.com/agent/tickets/969) including logs and heap dump.

**Comment by pseudonator** [comment]
There may be related issues causing instability such as https://github.com/solo-io/solo-projects/issues/4171.

**Comment by saiskee** [comment]
awaiting backport to 1.12.x

**Comment by saiskee** [comment]
closed by https://github.com/solo-io/solo-projects/pull/4226
