### ISSUE TITLE
extend Gateway to support multiple gateway proxy configurations

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#736]
currently the `gateway` controller merges all gateways & virtual services into a single proxy. it's therefore not possible to create proxies with different configurations unless the user is interacting with the low-level proxy api.

we should extend the `gateway` crd to include a field such as `proxy`, indicating a different target proxy on which to apply the gateway + its virtual services.

this feature should also be backed by changes to the helm chart, permitting users to deploy proxies with an arbitrary role (so they can be linked to the corresponding proxy objects)

use cases outlined by @derrickburns and others require this feature

**Comment by marcogschmidt** [comment]
Related to #575

**Comment by EItanya** [comment]
Added with addition of `gatewayProxyName` in the Gateway CRD
