### ISSUE TITLE
GlooSnapshot Error

### ISSUE THREAD

**Issue by fabioaraujopt** [solo-io/gloo#7381]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

Gloo is showing a bunch of errors which are not comprehensive, after the update to the latest stable [v1.12.31](https://github.com/solo-io/gloo/releases/tag/v1.12.31).

The errors are the following:
```
E1027 10:35:19.196408       1 leaderelection.go:330] error retrieving resource lock gloo-system/gloo: leases.coordination.k8s.io "gloo" is forbidden: User "system:serviceaccount:gloo-system:gloo" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "gloo-system"
{"level":"debug","ts":"2022-10-27T10:35:20.374Z","logger":"gloo.v1.event_loop.setup.gloosnapshot.event_loop","caller":"kube/opaque_secret.go:31","msg":"resource client could not convert secret","version":"1.12.12","error":"not kube secret resource"}
```

### Steps to reproduce the bug

Helm install gloo.

### Expected Behavior

Gloo should not show this error.

**Comment by elcasteel** [comment]
What version were you on before? Did you apply the latest CRDs manually before the upgrade?

**Comment by dshackith** [comment]
I am seeing this same issue with a fresh install of chart v1.11.21 as well. We are preparing to upgrade but are attempting to start fresh in a test environment. Our other installs are at v1.11.21, but were upgraded in-place without issue. When we perform a fresh install, gloo pod crashes with above error, and gateway and gateway-proxy pods also continuously restart.

This is the final error:
```"level":"fatal","ts":"2023-03-22T20:51:29.266Z","logger":"gloo","caller":"setuputils/main_setup.go:93","msg":"error in setup: creating validating webhook: loading TLS certificate provider: stat /etc/gateway/validation-certs/tls.crt: no such file or directory","version":"1.12.41","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:93\ngithub.com/solo-io/gloo/projects/gloo/pkg/setup.startSetupLoop\n\t/workspace/gloo/projects/gloo/pkg/setup/setup.go:26\ngithub.com/solo-io/gloo/projects/gloo/pkg/setup.Main\n\t/workspace/gloo/projects/gloo/pkg/setup/setup.go:18\nmain.main\n\t/workspace/gloo/projects/gloo/cmd/main.go:16\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}```
