### ISSUE TITLE
Support the latest knative vesion

### ISSUE THREAD

**Issue by xpepermint** [solo-io/gloo#739]
The documentation at https://knative.dev/docs/install/knative-with-gloo/ does not mention that `glooctl install knative` installs knative `v0.5.0`. The documentation is targeting `v0.6.0`. I also see old versions of `istio` in this repo. Please consider supporting the latest knative version.

**Comment by ilevine** [comment]
This is resolved: current CLI installs with any version of Knative and defaults to 0.7.0
