### ISSUE TITLE
expose jwt clockskew

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#7398]
### Version

1.12.x (latest stable)

### Is your feature request related to a problem? Please describe.

expose jwt clockskew so that jwts can remian valid longer than 60s after expiry

### Describe the solution you'd like

expose jwt clockskew

### Describe alternatives you've considered

passthrough auth

### Additional Context

done in mesh https://github.com/solo-io/gloo-mesh-enterprise/issues/4235

**Comment by sam-heilbron** [comment]
Envoy API: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-jwtprovider

Gloo API: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/enterprise/options/jwt/jwt.proto#L49

Definition of Done: `clock_skew_seconds` exposed in the Gloo API

**Comment by nfuden** [comment]
It seems reasonable to me that this issue should actually be to add all likely relevant fileds from the jwt_authn proto to be configurable in gloo. 
It MUST have a way to configure clock_skew_seconds, it MAY have other options configurable and it MUST have a rationale for each extant field and why it should or shouldnt have a bespoke toggle in gloo.

**Comment by irateswami** [comment]
@nfuden Something I'm not understanding: [jwts are only in the enterprise version](https://docs.solo.io/gloo-edge/latest/guides/security/auth/jwt/). Does the entire `jwt` proto need to be implemented?

**Comment by irateswami** [comment]
Whoops! Didn't mean to close

**Comment by nfuden** [comment]
Reopening until this is released in enterprise
