### ISSUE TITLE
Support W3C Trace Context

### ISSUE THREAD

**Issue by guydc** [solo-io/gloo#7406]
### Version

1.12.x (latest stable)

### Describe the solution you'd like

Support the [W3C Trace Context](https://www.w3.org/TR/trace-context/): The `traceparent` header should be handled according to the [processing model](https://www.w3.org/TR/trace-context/#processing-model). 

Gloo Edge should support the following:

- Enable/Disable W3C Trace Context processing on a the `Gateway` and `HTTPGateway` Gloo resources. This can be implemented with a simple flag or by providing explicit tracing extension configuration. 
- Enable W3C Trace Context without providing a trace collector backend. 

### Describe alternatives you've considered

Currently, there are two envoy tracing extensions that provide this functionality:
- [OpenCensus](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opencensus.proto)
- [OpenTelemetry](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opentelemetry.proto)

The OpenTelemetry extension is currently not intended for productive use, it does not have a security posture and requires an OTEL collector. 

The OpenCensus extension is ready for production, robust against untrusted downstreams and does not require a tracing backend. So, OpenCensus appears to be more appropriate for this purpose. 

If implemented as an additional tracing provider, the OpenCensus config can be exposed in the gloo [tracing interface](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/tracing/tracing.proto.sk/). The `incoming_trace_context` and `outgoing_trace_context` attributes should be configurable and the `TRACE_CONTEXT` value supported.

**Comment by ashishb-solo** [comment]
reopening so we can update gloo-ee to depend on this revision
