### ISSUE TITLE
oidc example - glooctl create secret does not work

### ISSUE THREAD

**Issue by nmnellis** [solo-io/gloo#744]
The OIDC example found here does not work with creating secrets.
https://gloo.solo.io/enterprise/authentication/oidc/

version 0.13.30

```sh
glooctl create secret --namespace gloo-system --name google oauth --client-secret $CLIENT_SECRET
Error: unknown flag: --client-secret
Usage:
  glooctl create secret [flags]
  glooctl create secret [command]

Aliases:
  secret, s, secret

Available Commands:
  aws         Create an AWS secret with the given name
  azure       Create an Azure secret with the given name
  tls         Create a secret with the given name

Flags:
  -h, --help   help for secret

Global Flags:
      --dry-run            print kubernetes-formatted yaml rather than creating or updating a resource
  -i, --interactive        use interactive mode
      --name string        name of the resource to read or write
  -n, --namespace string   namespace for reading or writing resources (default "gloo-system")
  -o, --output string      output format: (yaml, json, table)

Use "glooctl create secret [command] --help" for more information about a command.
```

**Comment by yuval-k** [comment]
it's a bit confusing, but you need to use the enterprise glooctl, from here: https://gloo.solo.io/enterprise/installation/install_glooctl/

**Comment by nmnellis** [comment]
Thanks, although it's disappointing that its not a part of the open source features.

**Comment by yuval-k** [comment]
I understand it is disappointing, but at we had to draw a line somewhere between open source and paid features... We do plan of extending open source gloo to support bring-your-own auth server, so hopefully that will cover your use-case.
please let us know if you have any more feedback!
