### ISSUE TITLE
Lambda wrapAsApiGateway not populating QueryStringParameters 

### ISSUE THREAD

**Issue by jaymiracola** [solo-io/gloo#7446]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

When using the aws.proto field "wrapAsApiGateway" the QueryStringParameters are not populating the give query strings. 

### Steps to reproduce the bug

Using the following vs I am mirroring traffic internally and capturing the traffic on httpbin.
```apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /helloworld
      options:
        shadowing:
          percentage: 100
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: netcore
              requestTransformation: true
              wrapAsApiGateway: true
          upstream:
            name: my-aws-upstream
            namespace: gloo-system
```
Curling the address with a generic query string shows nothing populated in the queryStringParameters path
`curl http://<url>/helloworld?foo=bar`

```
Member: queryStringParameters
    Object
        Member: Qualifier
            [Path with value: /queryStringParameters/Qualifier:$LATEST]
            [Member with value: Qualifier:$LATEST]
            String value: $LATEST
            Key: Qualifier
            [Path: /queryStringParameters/Qualifier]
    Key: queryStringParameters
    [Path: /queryStringParameters]
```

### Expected Behavior

We should see the `queryStringParameters` populated in the same way `queryString` is populated in order to enable applications expecting this value.

```
Member: queryString
    [Path with value: /queryString:foo=bar]
    [Member with value: queryString:foo=bar]
    String value: foo=bar
    Key: queryString
    [Path: /queryString]
```

**Comment by bdlilley** [comment]
@SirNexus FYI

**Comment by bensolo-io** [comment]
closing this in favor of https://github.com/solo-io/solo-projects/issues/4353 which includes the querystring params
