### ISSUE TITLE
Upstream grpc config is missing parameters that are available on the Gateway

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#7480]
### Is your feature request related to a problem? Please describe.

All of the parameters available here should also be available on the Upstream grpc config: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/grpc_json/grpc_json.proto.sk/

### Describe the solution you'd like

Support all grpc_transcoder filter params on the Upstream

**Comment by chrisgaun** [comment]
Other gRPC issues
https://github.com/solo-io/gloo/issues/7479
https://github.com/solo-io/gloo/issues/7478
https://github.com/solo-io/gloo/issues/7477

**Comment by elcasteel** [comment]
The upstream and gateway configurations use the same API as of the 1.14 beta
