### ISSUE TITLE
Add docs for Aerospike integration

### ISSUE THREAD

**Issue by artberger** [solo-io/gloo#7489]
### Version

master / 1.13.0

### Describe the requested changes

- [x] Review the Portal doc
- [x] Review the Portal storage CR API doc
- [x] Probably don't focus on External Auth, but might have to set up the config
- [x] Main focus on Rate Limiting, especially the Helm config for the RL server (Similar to DynamoDB)
- [x] Review the ref docs: not sure if it's in API or just in Helm
- [x] Tech rev of changes, posted in Slack [here](https://solo-io-corp.slack.com/archives/C035Y6QAUPJ/p1670257629909329) and see related PRs
- [x] Confirm with Field the use cases

### Link to any relevant existing docs

- Rate limit: https://soloio.slab.com/posts/aerospike-ratelimit-nbymoo62
- Extauth/Portal: https://soloio.slab.com/posts/aerospike-api-keys-srnfy436
- Field’s notes from installing: https://soloio.slab.com/posts/aero-spike-api-key-storage-integration-notes-ru1q276o
- Docs in main: https://docs.solo.io/gloo-portal/main/guides/portal_features/apikey_storage/
- Nina and Jacob's [lightning talk at all-hands](https://docs.google.com/presentation/d/1LrvuOQoPPW4lFZ0V-1qEWhxkBZyveCTBL5zl-VhlpOE/edit?usp=sharing)
- Similar DynamoDB doc: https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/enterprise/#dynamodb-backed-rate-limit-service

### Additional Context

* Jake's RL Helm issue: https://github.com/solo-io/solo-projects/issues/3945#issuecomment-1329456077
* Portal doc PR: https://github.com/solo-io/dev-portal/pull/2506/
* Edge doc PR: https://github.com/solo-io/gloo/pull/7510
* Edge Helm values update PR: https://github.com/solo-io/solo-projects/pull/4347

**Comment by artberger** [comment]
Docs are up for this, and posted in Slack [here](https://solo-io-corp.slack.com/archives/C035Y6QAUPJ/p1670359946250369?thread_ts=1670257629.909329&cid=C035Y6QAUPJ)

* Edge [rate limit server for Aerospike](https://docs.solo.io/gloo-edge/master/guides/security/rate_limiting/enterprise/#aerospike)
* Edge ext auth [API reference](https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#aerospikeapikeystorage)
* Portal [Storage guide](https://docs.solo.io/gloo-portal/main/guides/portal_features/apikey_storage/)
* Portal [Storage API doc](https://docs.solo.io/gloo-portal/main/reference/api/storage/#storagespec-apikeystorage)

**Comment by thebarshablog** [comment]
> Docs are up for this, and posted in Slack [here](https://solo-io-corp.slack.com/archives/C035Y6QAUPJ/p1670359946250369?thread_ts=1670257629.909329&cid=C035Y6QAUPJ)
> 
> * Edge [rate limit server for Aerospike](https://docs.solo.io/gloo-edge/master/guides/security/rate_limiting/enterprise/#aerospike)
> * Edge ext auth [API reference](https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#aerospikeapikeystorage)
> * Portal [Storage guide](https://docs.solo.io/gloo-portal/main/guides/portal_features/apikey_storage/)
> * Portal [Storage API doc](https://docs.solo.io/gloo-portal/main/reference/api/storage/#storagespec-apikeystorage)

https://docs.aerospike.com/server/operations/configure : Please add this doc on the slack channel incase of trouble configuring Aerospike. Unless aerospike is configured, it may trouble the integration.

**Comment by artberger** [comment]
Hi @thebarshablog, I updated my post with a link to this doc. We also link to the Aerospike install and config docs as the first two steps in the Portal Storage guide referenced. Was there another place you also want me to post this? Thanks.

**Comment by thebarshablog** [comment]
@artberger I appreciate it.
