### ISSUE TITLE
Endpoint data missing in config after configuring Gloo Edge gateway with an Istio sidecar 

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#7491]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.24.x

### Describe the bug

Following the guide here: https://docs.solo.io/gloo-edge/atest/guides/integrations/service_mesh/istio/

After enabling istio integration, the gloo pod starts up with the following environment variable:

```
      ENABLE_ISTIO_INTEGRATION:  true
```

This causes it run through some extra logic to determine the endpoints       
https://github.com/solo-io/gloo/blob/2fe93ebe31ec62f2cbbbb8ba2da1c1f1a8085e7b/projects/gloo/pkg/plugins/kubernetes/eds.go#L326-L339

The resulting config served to the gateway-proxy has some `endpoint_config` clusters with missing endpoint data.

```
{
  "endpoint_config": {
   "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
   "cluster_name": "gloo-system-gateway-proxy-443_gloo-system-14508863120638499970",
   "policy": {
    "overprovisioning_factor": 140
   }
  }
 }
```

Normally it should be this:
```
    {
     "endpoint_config": {
      "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
      "cluster_name": "kube-svc:gloo-system-gateway-proxy-443_gloo-system-12948939780041189621",
      "endpoints": [
       {
        "locality": {},
        "lb_endpoints": [
         {
          "endpoint": {
           "address": {
            "socket_address": {
             "address": "10.19.242.63",
             "port_value": 8443
            }
           },
           "health_check_config": {}
          },
          "health_status": "HEALTHY",
          "metadata": {
           "filter_metadata": {
            "envoy.lb": {
             "app": "gloo",
             "app.kubernetes.io/managed-by": "Helm",
             "gateway-proxy-id": "gateway-proxy",
             "gloo": "gateway-proxy"
            }
           }
          },
          "load_balancing_weight": 1
         }
        ]
       }
      ],
      "policy": {
       "overprovisioning_factor": 140
      }
     }
    },
``` 

This causes the gateway-proxy to flood the logs with the following message:

```
[warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment rejected: malformed IP address: None. Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'
```

### Steps to reproduce the bug

I haven't been reproduce this in a vanilla install.  It looks to be something related to the services on the customer's environment.

### Expected Behavior

The `endpoint_config` should have the endpoint data.

**Comment by bdecoste** [comment]
Related: https://github.com/solo-io/gloo/issues/6195

**Comment by inFocus7** [comment]
Temporarily updating status to `Blocked` as we wait for <user> to update us with new logs. 

Context: We currently don't have a way to reproduce locally, so built a test image with extra logs and sent to <user>.

**Comment by inFocus7** [comment]
# Release Information
Using this to keep track of the versions they're merged in and if they've been released - will be checked off if so. This fix should be getting merged & released throughout this upcoming week.

## Edge OSS
- [ ] 1.14.0-beta10
- [ ] 1.13.X
- [ ] 1.12.X

## Edge Enterprise
- [ ] 1.14.0-betaX
- [ ] 1.13.X
- [ ] 1.12.X

**Comment by inFocus7** [comment]
Closing the issue, as it's been release (see above for release versions)
