### ISSUE TITLE
gRPC to Rest - use ConfigMap for protoDescriptorBin

### ISSUE THREAD

**Issue by byrdog55** [solo-io/gloo#7495]
### Version

1.12.x (latest stable)

### Is your feature request related to a problem? Please describe.

Allow users to reference protoDescriptorBin from a remote URL or configmap for the httpGateway opttions in the grpcJsonTranscoder configuration.

### Describe the solution you'd like

The protoDescriptorBin can become unwieldy especially if you have more than one application that needs transcoding.  I would like to be able to use list of configmaps or remote URL for each application that need transcoding. The size of the protoDescriptorBin is also is causing issues with our current helm upgrade of Gloo Edge https://github.com/solo-io/gloo/issues/7060

### Additional Context

relates to https://github.com/solo-io/gloo/issues/7060

**Comment by jenshu** [comment]
Available in:
- Gloo OSS 1.14.0-beta7, 1.13.3, and 1.12.41, and
- Gloo EE 1.14.0-betaX (TBD), 1.13.4 and 1.12.45

See https://github.com/solo-io/gloo/issues/7060#issuecomment-1382608235 for usage
