### ISSUE TITLE
policy/v1beta1 api deprecation in K8s 1.25

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#7518]
### Version

None

### Is your feature request related to a problem? Please describe.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125

**Comment by nfuden** [comment]
https://github.com/solo-io/gloo/commit/a3e5552d9164bb2ca84f0ca6e8b721e72632cbb9 
Resolved in 1.14. @kevin-shelaga is there request for this in 1.13?

**Comment by kevin-shelaga** [comment]
This should be for 1.14. Thank you @nfuden
