### ISSUE TITLE
Extauth requires restart if the target grpc passthrough service moves

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#7528]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

None

### Describe the bug

I have grpc passthrough configured in extauth. The grpc passthrough service is auth.foo.com. The auth.foo.service went down temporarily and was recreated on a different k8s node. At that point, all extauth requests timed out (`context deadline exceeded`) until the extauth pod was restarted. 

Appears that there is an issue with the extauth connection pooling or endpoint resolution. 

Suspected incorrect handling in https://github.com/solo-io/ext-auth-service/blob/master/pkg/config/passthrough/grpc/grpc_client_manager.go#L46

### Steps to reproduce the bug

1. Create an AuthConfig with grpc passthrough 
2. Test extauth
3. Restart the grpc passthrough so that the target grpc passthrough service is recreated on a different IP(s)
4. Test. You will see extauth `context deadline exceeded` failures

### Expected Behavior

extauth grpc passthrough recovers from a change in the target auth service

**Comment by DuncanDoyle** [comment]
Can't reproduce on 1.15.14 ...... When completely removing Passthrough service, seeing the following in the logs:
```
{"level":"warn","ts":"2024-02-26T12:21:11Z","logger":"ext-auth.ext-auth-service","msg":"failed to execute check request","version":"undefined","x-request-id":"4602e4a6-69cd-4a2d-885e-a82fa8e0d398","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup example-grpc-auth-service.default.svc.cluster.local: no such host\""}
```
And when accessing the VS, 403s are returned.

Redeploying the grpc-passthrough-service deployment and service restores correct behaviour.
