### ISSUE TITLE
Expose Envoy's connection_balance_config through the Gloo API

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#7530]
### Version

1.12.x (latest stable)

### Is your feature request related to a problem? Please describe.

I'd like to be able to control Envoy's connection balancing behavior through the Gloo API. We're seeing unbalanced worker thread to connection behavior. 

### Describe the solution you'd like

Expose Envoy's `connection_balance_config` through the Gloo API:

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/intro/threading_model
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-connection-balance-config

### Describe alternatives you've considered

Adjusting Envoy's concurrency

**Comment by chirag0002** [comment]
Hey I want to work on this, also I am very new to the project can you please drop me a few resources from where I can learn and contribute? 
I have joined the slack community to get more involved.

**Comment by kdorosh** [comment]
@chirag0002 I recommend you start here https://docs.solo.io/gloo-edge/latest/guides/dev/ to get initial concepts and dev environment ready to go.

I imagine the new envoy config added here will end up going here in our APIs (for you to add) https://github.com/solo-io/gloo/blob/e71325cbbc04cb675dc09012ceb934fe33ce846d/projects/gloo/api/v1/options.proto#L61-L83

and then we will translate it into envoy config here https://github.com/solo-io/gloo/blob/e71325cbbc04cb675dc09012ceb934fe33ce846d/projects/gloo/pkg/plugins/listener/plugin.go#L34-L43

Hope this helps! Feel free to reach out again here or in slack with any other questions. Thank you for considering a contribution and happy holidays!!

**Comment by nfuden** [comment]
https://github.com/solo-io/gloo/pull/7797 in 1.14
