### ISSUE TITLE
One off arm64 for 1.13

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#7540]
Slack for more comments  but one off for https://github.com/solo-io/gloo/issues/3486

**Comment by jackstine** [comment]
- Checking in with @birkland to get information on manually generated images for Edge to use to generate `arm64` images.
- investigate all images that are currently not `arm64` and see what requirements are needed to do so.

**Comment by nfuden** [comment]
@chrisgaun if the goal is for using gloo locally on arm machines maybe we can get one of our devs who has gloo running locally to work with the customer to unblock them?

**Comment by nfuden** [comment]
one off was too painful so we can attack this with the full pipeline
