### ISSUE TITLE
Cluster name hardcoded in plugins

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#755]
The cluster name is hardcoded to `cluster.local` in the [Kubernetes](https://github.com/solo-io/gloo/blob/fe5d3a4e0cc0888c5cedd941faeb38f2749cb11f/projects/gloo/pkg/plugins/kubernetes/plugin.go#L28) and [Linkerd](https://github.com/solo-io/gloo/blob/fe5d3a4e0cc0888c5cedd941faeb38f2749cb11f/projects/gloo/pkg/plugins/linkerd/plugin.go#L136) plugins.

We should have the new `k8s.cluster-name` value propagate to the settings CRD, where itcan be picked up by the plugins.

**Comment by ilackarms** [comment]
the only issue i'm concerned with here is multi-cluster

when we may have to support multiple dns suffixes

**Comment by ilackarms** [comment]
however until then i think this solution should work

**Comment by marcogschmidt** [comment]
Good point @ilackarms, hadn't thought about it. I think there is value is solving this for the current use case and then revisit it once we support multicluster.

**Comment by ilevine** [comment]
Resolved by https://github.com/solo-io/gloo/pull/757
