### ISSUE TITLE
Auto Pass tests in certain circumstances eg docs

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#7562]
### Version

None

### Is your feature request related to a problem? Please describe.

Docs prs and the like shouldnt have to go through ci if they have no functional changes

### Describe the solution you'd like

on github actions lets skip if a pr meets a given condition such as docs only where no code is actually changed

**Comment by sam-heilbron** [comment]
This was resolved by https://github.com/solo-io/gloo/pull/8307
