### ISSUE TITLE
Support topologySpreadConstraints in deployments

### ISSUE THREAD

**Issue by Kostavro** [solo-io/gloo#7582]
### Version

1.11.x

### Is your feature request related to a problem? Please describe.

Not related to a problem.

### Describe the solution you'd like

I would like the chart to support https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/ for deployments.

**Comment by Kostavro** [comment]
Could we backport this to v1.11.x please?

**Comment by Kostavro** [comment]
Thank you once more for your efforts @sam-heilbron & @ianmacclancy :) . Would really like to propagate this to 1.12 and 1.13 as well, and release new Helm Charts for all 3 versions. Please let me know if I can do something more towards that purpose.

**Comment by jenshu** [comment]
fix will be available in Gloo OSS versions 1.11.48, 1.12.41, 1.13.3, 1.14.0-beta4
and Gloo EE versions 1.12.45 and 1.13.4

**Comment by Kostavro** [comment]
@jenshu I can't see the 1.11.48 version, could you please check as well? Thank you.

**Comment by jenshu** [comment]
> @jenshu I can't see the 1.11.48 version, could you please check as well? Thank you.

looks like we haven't yet released 1.11.48, do you need that version? if so, we can likely release it today

**Comment by jenshu** [comment]
sorry github was having some issues this morning and the release didn't go through.
we'll release again tomorrow (1.11.49 this time)

**Comment by jenshu** [comment]
1.11.49 is released now
