### ISSUE TITLE
Support AWS auth to Vault as a secret store

### ISSUE THREAD

**Issue by jbohanon** [solo-io/gloo#7640]
### Version

None

### Is your feature request related to a problem? Please describe.

A user requires the ability to authenticate to Vault using [AWS auth method](https://developer.hashicorp.com/vault/docs/auth/aws).

### Describe the solution you'd like

The Vault integration should be modified to allow authenticating via AWS ([vault AWS api](https://github.com/hashicorp/vault/blob/main/api/auth/aws/aws.go))

### Additional Context

This is a required feature to fulfill https://github.com/solo-io/gloo/issues/7342

**Comment by pseudonator** [comment]
Just confirming here that only IAM auth is required, cc @jbohanon @SantoDE

**Comment by jbohanon** [comment]
This is released in Gloo Edge Enterprise v1.14.0-beta8
