### ISSUE TITLE
Discovery and generation for existing GraphQL APIs

### ISSUE THREAD

**Issue by jackstine** [solo-io/gloo#7685]
### Version

None

### Is your feature request related to a problem? Please describe.

We currently support discovery and generation of GraphQLApi CRs for REST and gRPC APIs. We should consider whether we can automatically generate a remote executor GraphQLApi CR for these existing GraphQL APIs. This saves the user the trouble of creating a CR on their own with the schema and upstream API details.

### Describe the solution you'd like

Assuming we support generation, we should add support for:

1. Discovering GraphQL APIs that are already deployed using a standard path attributes (e.g. introspection endpoint available on /graphql)
2. Use the introspection endpoint to generate a schema definition and create a GraphQLApi CR with the corresponding destination details.

### Describe alternatives you've considered

Users can create the CR on their own, but this is a bit of pain, particularly when there are large number of existing GraphQL APIs you want to stitch together.

**Comment by kcbabo** [comment]
We should consider making the introspection endpoint path configurable as some GraphQL services may have it on an alternate path from /graphql

**Comment by jackstine** [comment]
Found that we can use GraphQL introspection to produce the schema.  There is an open source module that we can use to produce this schema as well.  We were able to find a go solution.
[graphql-go-tools](zhttps://github.com/wundergraph/graphql-go-tools) is the Go Solution
[Javascript solution](https://graphql.org/graphql-js/utilities/#buildclientschema) 

Using the graphql-go-tools produces the native type schemas as well, something that clients would not like to see in the GraphQLAPI schemaDefinitions.
Here is an example of this
```
In some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.
"""
type __Directive {
    args: [__InputValue!]!
    description: String
    locations: [__DirectiveLocation!]!
    name: String!
    onField: Boolean! @deprecated(reason: "Use `locations`.")
    onFragment: Boolean! @deprecated(reason: "Use `locations`.")
    onOperation: Boolean! @deprecated(reason: "Use `locations`.")
}
```

For now the goal is to write the schema as it is generated in the `graphql-go-tools`. Some future steps can be taken to filter out the introspection results so that we do not define schemas for private types native to GraphQL.

**Comment by kcbabo** [comment]
Shouldn't we just exclude all type definitions that begin with double underscores? That naming convention is reserved for the introspection system in GraphQL, so dropping these from the schema generated from introspection seems reasonable. 

If we're saving that work for the second part, then that's fine, but we should not have this be a user-facing feature including all the internal type definitions in the generated schema.

**Comment by jackstine** [comment]
The above comment](https://github.com/solo-io/gloo/issues/7685#issuecomment-1423295779) no longer applies. The schema definition should be what the client's server represents.
