### ISSUE TITLE
New version notification in glooctl

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#769]
It would be nice if `glooctl` would notify the user when a new version is available, like `minikube` does:
![image](https://user-images.githubusercontent.com/16148461/60021192-82add280-965f-11e9-83a3-786f0e8cc66b.png)

**Comment by ilevine** [comment]
depends on https://github.com/solo-io/gloo/issues/722
we can also do it via the checkpoint api, and output to gloo logs a notification of a new version.

**Comment by rickducott** [comment]
We need some way to filter because currently we release too frequently for this to be useful and not annoying.
