### ISSUE TITLE
ci broken (gke and aws)

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#7702]
### Gloo Edge Version

1.14.x (beta)

### Kubernetes Version

None

### Describe the bug

CI build-bot currently dying due to gke changes. Creating for tracking the resolution

### Steps to reproduce the bug

run ci

### Expected Behavior

build bot completes without error

**Comment by jenshu** [comment]
gke issues have been resolved in portal and solo-projects
aws tests are still failing in gloo which is blocking merge

**Comment by nfuden** [comment]
last bit to be tackled in https://github.com/solo-io/solo-projects/issues/4515 for ec2
