### ISSUE TITLE
Label value with more than 63 characters

### ISSUE THREAD

**Issue by TomerJLevy** [solo-io/gloo#7716]
### Gloo Edge Version

1.12.x

### Kubernetes Version

1.23.x

### Describe the bug

The controller tries to set a label value by concatenating the resource name and namespace and by that can possibly create label longer than 63 characters which isn't allowed.

### Steps to reproduce the bug

1. kubectl apply `FederatedVirtualService` in which its name + namespace is longer than 63 characters
2. Look at the Gloo-fed logs and you should see error logs such as: 
`metadata.labels: Invalid value: \"..............\": must be no more than 63 characters`

### Expected Behavior

K8S set a limit of 253 for resource names and namespaces, and a limit of 63 for label values. And so, trying to concatenate them in order to set a label value is a bug.

### Additional Context

{"level":"error","ts":1674402055.76091,"logger":"gloo-fed.controller.federatedVirtualService","msg":"Reconciler error","version":"1.12.44","name":"ugw-configuration-1","namespace":"technologyinnovation-unified-frontend-development","error":"handler error. retrying: 4 errors occurred:\n\t* 1 error occurred:\n\t* VirtualService.gateway.solo.io \"ugw-configuration-1\" is invalid: metadata.labels: Invalid value: \"technologyinnovation-unified-frontend-development.ugw-configuration-1\": must be no more than 63 characters\n\n\n\t* 1 error occurred:\n\t* VirtualService.gateway.solo.io \"ugw-configuration-1\" is invalid: metadata.labels: Invalid value: \"technologyinnovation-unified-frontend-development.ugw-configuration-1\": must be no more than 63 characters\n\n\n\t* 1 error occurred:\n\t* VirtualService.gateway.solo.io \"ugw-configuration-1\" is invalid: metadata.labels: Invalid value: \"technologyinnovation-unified-frontend-development.ugw-configuration-1\": must be no more than 63 characters\n\n\n\t* 1 error occurred:\n\t* VirtualService.gateway.solo.io \"ugw-configuration-1\" is invalid: metadata.labels: Invalid value: \"technologyinnovation-unified-frontend-development.ugw-configuration-1\": must be no more than 63 characters\n\n\n\n","errorVerbose":"handler error. retrying\n\tcontroller.(*Controller).processNextWorkItem:/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253\n\tcontroller.(*Controller).reconcileHandler:/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:298\n\treconcile.(*runnerReconciler).Reconcile:/go/pkg/mod/github.com/solo-io/skv2@v0.26.1/pkg/reconcile/runner.go:208\n4 errors occurred:\n\t* 1 error occurred:\n\t* VirtualService.gateway.solo.io \"ugw-configuration-1\" is invalid: metadata.labels: Invalid value: \"technologyinnovation-unified-frontend-development.ugw-configuration-1\": must be no more than 63 characters\n\n\n\t* 1 error occurred:\n\t* VirtualService.gateway.solo.io \"ugw-configuration-1\" is invalid: metadata.labels: Invalid value: \"technologyinnovation-unified-frontend-development.ugw-configuration-1\": must be no more than 63 characters\n\n\n\t* 1 error occurred:\n\t* VirtualService.gateway.solo.io \"ugw-configuration-1\" is invalid: metadata.labels: Invalid value: \"technologyinnovation-unified-frontend-development.ugw-configuration-1\": must be no more than 63 characters\n\n\n\t* 1 error occurred:\n\t* VirtualService.gateway.solo.io \"ugw-configuration-1\" is invalid: metadata.labels: Invalid value: \"technologyinnovation-unified-frontend-development.ugw-configuration-1\": must be no more than 63 characters\n\n\n\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214"}

**Comment by nfuden** [comment]
https://github.com/solo-io/solo-projects/blob/master/projects/gloo-fed/pkg/api/fed.enterprise.gloo.solo.io/v1/federation/federation_reconcilers.go#L95

**Comment by jenshu** [comment]
a few issues:
- we can't move to annotations because we query on it
- truncating could also cause problems because multiple resources could have the same name/namespace prefix
- splitting owner label into separate name/namespace labels might still run into character limits because names can be longer than 63 char

wonder if maybe we could hash the owner label to a shorter string?

**Comment by TomerJLevy** [comment]
I would raise a suggestion. You can truncate it or hash it if you want, but
anyhow I would add 2 more annotations, owner namespace and owner name,
since its value has the same limitation as name and namespace.
So, you can query by these label/s and verify you got the right resource by
reading these annotations (if got more than 1 matches), just to handle
cases of collisions

**Comment by jenshu** [comment]
we have a util function [here](https://github.com/solo-io/k8s-utils/blob/767d2c9c81718c41e06d5b190a7ae34cfe36a40f/kubeutils/util.go#L30) that we can perhaps use

**Comment by shahar-h** [comment]
There a similar issue when creating `FederatedMatchableHttpGateway` where its name + namespace length >= 63 characters: `gloo-fed` tries to label `MatchableHttpGateway` resource with `fed.solo.io/owner: <fed-ns>.<fed-name>` and fails.

**Comment by SantoDE** [comment]
Not only label value but also resource names. Which other places might be affected when we create labels / resource names in Gloo-fed? We would probably need to prevent that in all places in Gloo-fed, where we create resources / add labels.

**Comment by jenshu** [comment]
Fix will be available in GlooEE v1.15.8 and v1.16.0-beta3
We now hash+truncate the owner label, and additionally add the full owner label as an annotation for verification purposes
