### ISSUE TITLE
reporter.go prints warnings about unexpected number of namespaces in input resource: 2

### ISSUE THREAD

**Issue by bkuzmic** [solo-io/gloo#7731]
### Gloo Edge Version

1.12.x

### Kubernetes Version

1.23.x

### Describe the bug

gloo pod incorrectly (and excessively) reports warnings when trying to update status on upstreams.

Here is the log message:
"failed to write status state:Accepted  reported_by:\"gloo\" for resource {upstream_name}: error getting status json patch data: unexpected number of namespaces in input resource: 2"

I've checked the source code for reporter and found `GetJsonPatchData` which somehow gets two statuses fields even though there is only one (previously reported by gloo).

### Steps to reproduce the bug

Log warnings in reporter/reporter.go:305

### Expected Behavior

There is only one status.statuses field, so the check in the `GetJsonPatchData`  should pass and report no error

**Comment by jenshu** [comment]
@bkuzmic can you see if this is resolved with the latest releases?
Gloo OSS 1.12.42 / 1.13.4 or Gloo EE 1.12.46 / 1.13.5

**Comment by bkuzmic** [comment]
@jenshu Thanks, I will check it today.

**Comment by bkuzmic** [comment]
@jenshu Issue is resolved! Thanks again for the quick patch
