### ISSUE TITLE
Contributing Doc is out of date and misses a few steps for local setup

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#7758]
### Version

master

### Describe the requested changes

https://github.com/solo-io/gloo/blob/v1.13.x/docs/content/guides/dev/setting-up-dev-environment.md
Running gloo main.go file does not work as is with these intstructions.
As pointed out by https://github.com/SuperAayush @SuperAayush when following this the settings cr is not found as it does not specify filesystem and does not detail setting up a kubernetes environment.

**Comment by nfuden** [comment]
@sam-heilbron @sheidkamp as you did some testing with minimal dockerized setups recently

**Comment by SuperAayush** [comment]
I was getting this error while setting up the gloo project after running `go run projects/gloo/cmd/main.go` in the terminal:
<img width="1409" alt="screenshot_2023-01-30_at_7 12 48_pm" src="https://user-images.githubusercontent.com/78820926/215504242-39964c58-ccb9-4f74-b16c-2846203a9485.png">

I did run a Minikube but even after that while repeating the steps I am facing this error:
<img width="1424" alt="screenshot_2023-01-30_at_7 21 50_pm" src="https://user-images.githubusercontent.com/78820926/215504811-e27afdc0-22c6-4f68-a57e-d1aa2ec2af2a.png">

Regarding this I will attach a PR to update the docs: https://github.com/solo-io/gloo/blob/v1.13.x/docs/content/guides/dev/setting-up-dev-environment.md
