### ISSUE TITLE
Enhance Docker Images to support more pre-build and layered images

### ISSUE THREAD

**Issue by jackstine** [solo-io/gloo#7773]
### Version

None

### Is your feature request related to a problem? Please describe.

Building images can take too long, also reading the Makefile is chaotic.  Needs a refactor of the makefile and reduce the complexity around building different types of images.

A nice refactoring of the docker builds can have improvements on the makfile. This can also add complexity as well, but I think the benefits out way the costs.  

Benefits
reduced high level code complexity
reduced size of Makefiles
base images are known
less Dockerfiles
a build path to build any go executable in an image

Costs:
knowledge around the complexity of a reusable build cycle
Low level code complexity of docker builds
Complexity added with a configuration of flags to control building images

### Describe the solution you'd like

Ideally I am looking for a series of images to layer on top of each other, and a single docker build file

1. base images
2. image to builid off gloo and gloo mod
3. image to build the g++ and gcc compiler options
4. image to build the golang executables
5. image to run the image in

Some images in Gloo do not need CGO, so those would have a different layer of images.

Building the go mod would also be a great benefit as well, and reduce the amount of time spent on downloading the go.mod and go modules that Gloo uses.

**Comment by nfuden** [comment]
This issue is a bit all over the place can we scope it more tightly? Can you split out the makefile statements from dockerfiles.
