### ISSUE TITLE
Denial Of Service vulnerability in Golang

### ISSUE THREAD

**Issue by TomerJLevy** [solo-io/gloo#7843]
### Gloo Edge Version

any

### Kubernetes Version

any

### Describe the bug

Denial Of Service vulnerability in Golang. https://github.com/advisories/GHSA-69cg-p879-7622 requires upgrading Go version to version >= 1.18.6 or go >= 1.19.1
Suggested [this PR](https://github.com/solo-io/gloo/pull/7841) which obviously isn't enough

### Steps to reproduce the bug

will work in any version

### Expected Behavior

avoid the denial of service vulnerability

**Comment by nfuden** [comment]
This has been fixed in the newest 1.12 and 1.13. Write up for 1.11 and 1.10 as to the threat scope and what if any minimal vectors to come. 

Namely stats server or validation webhook. Final write up for webhook is pending due to how an actor may access the webhook
