### ISSUE TITLE
Retrieve JWT from user in portal to be used seamlessly in API requests

### ISSUE THREAD

**Issue by ky-rafaels** [solo-io/gloo#7858]
### Version

None

### Is your feature request related to a problem? Please describe.

Fitch wants an external customer developer portal with the intent of eventually monetizing their APIs. They'd like to use OAuth2 to log users in to the developer portal and then use a user access_token to make calls to API endpoints. When using a basic-oauth usagePlan, they do NOT want to have customers use a clientId and clientSecret to connect to OAuth provider, then provide username and password to retrieve a JWT token. Their preference is to have a more effective way and increased user experience for a customer to retrieve a JWT when using Gloo Portal.

### Describe the solution you'd like

A user that logs into the portal using OAuth2 or OIDC can then seamlessly use the JWT returned from Redis 
Flow

1. Portal is configured to use OAuth2Auth 
2. Customer logs into developer portal with username and password
3. access_token and refresh_token is stored in redis 
4. User can then retrieve token from their account in developer portal to be used to make calls to API endpoints (similar to how with a basic usage plan a customer can do this with an apiKey)

### Describe alternatives you've considered

We attempted driving customer towards using the standard basic-oauth usagePlan but the requirement of having client_id and client_secret did not meet their needs

### Additional Context

Wrote a possibility of two options here: https://soloio.slab.com/posts/gloo-portal-o-auth-feature-improvements-o14cvqci

Solo Versions in use:

- portal version - 1.3.0-beta17
- Edge version - 1.12.26
- Gloo Mesh version - 2.0.2
- istio version - 1.13.7

**Comment by bewebi** [comment]
Opened in the wrong project repo, a new issue will be opened in the appropriate location
