### ISSUE TITLE
Docs: GraphQL query hashing

### ISSUE THREAD

**Issue by Rachael-Graham** [solo-io/gloo#7906]
### Version

master

### Describe the requested changes

Need GraphQL docs on query hashing. Include CDN cache control headers capability.

### Link to any relevant existing docs

- GG caching - we dont use the same CRs in Edge of course, but helpful conceptual info: https://docs.solo.io/gloo-gateway/main/graphql/graphql-persisted-query-cache/
- Automatic persisted queries: https://github.com/solo-io/envoy-gloo-ee/issues/272
- Response Caching: This is basically piggybacking on the general response caching support we’re doing for Edge https://github.com/solo-io/envoy-gloo-ee/issues/260
- CDN cache control headers PR: https://github.com/solo-io/envoy-gloo-ee/pull/288

**Comment by DuncanDoyle** [comment]
Outdated. Closing
