### ISSUE TITLE
Centralize where we specify go versions in code

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#7926]
### Version

None

### Is your feature request related to a problem? Please describe.

Currently when we upgrade go, we need to update it in a bunch of places: go.mod, all the github actions, cloudbuild.yaml... (see https://github.com/solo-io/gloo/pull/7873 for example)

### Describe the solution you'd like

We can simplify this process by:
- using [go-version-file](https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file) with setup-go in our github actions, and
- coming up with a way to use a dynamic golang image tag (possibly by retrieving the version from go.mod and storing it in a variable) in cloud-builders

**Comment by nfuden** [comment]
This is being tackled to some degree in the current action work that @Bslabe123 is tackling. 

As a quick follow up lets use this issue to check if we are missing it anywhere.
