### ISSUE TITLE
Add ability to use a wildcard for the value in key/value pair for rate limiting config

### ISSUE THREAD

**Issue by georgefridrich** [solo-io/gloo#7941]
### Version

1.12.x

### Is your feature request related to a problem? Please describe.

Our customer is attempting to rate limit based on a path ideally from a prefix perspective where e.g. api/pets could match anything that would come after, e.g. api/pets* or api/pets/*.
They are using GE to route to their backend applications so options like using inja (for json payloads only) won't work well here. 

### Describe the solution you'd like

Ideal solution we allow in the value (string) to allow wildcards. 
https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/solo-apis/api/rate-limiter/v1alpha1/ratelimit.proto.sk/#descriptor
`# 5 requests per min for any request to api/pets
    - key: path
      value: "/api/pets/*"
      rateLimit:
        requestsPerUnit: 5
        unit: MINUTE`

### Describe alternatives you've considered

Kevin S. suggested injecting a custom header which is a great idea, but it causes a lot of housekeeping to accomplish.  First, we need to modify the virtualservice so each desired path is defined instead of using prefix: /.  Second, we need a routetable for each of those paths that will inject the desired header.  Then we can rate on that header in our ratelimitconfig.  I'm testing this now, but it will be a hard sell.

### Additional Context

Code for this should be rather simple.

**Comment by nfuden** [comment]
for the header based approach this should be able to be injected via a transformation extractor
