### ISSUE TITLE
Add option to set redis db

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#7959]
### Version

None

### Is your feature request related to a problem? Please describe.

Currently redis for rate limit (packaged or external) will use db 0. Customer has requested the ability to define the db.

### Describe the solution you'd like

Allow setting db for all redis interactions.

### Additional Context

https://github.com/solo-io/rate-limiter/blob/master/pkg/cache/redis/driver_impl.go#L46 and https://github.com/solo-io/ext-auth-service/blob/master/pkg/redis/redis_client.go#L36

**Comment by Bslabe123** [comment]
This feature will be added in the following releases:
- 1.15.0-beta2
- 1.14.3
