### ISSUE TITLE
Slow Proxy generation when IstioIntegration is enabled on gloo

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#7960]
### Gloo Edge Version

1.14.x (beta)

### Kubernetes Version

1.24.x

### Describe the bug

Slow Proxy generation when IstioIntegration is enabled on gloo

### Steps to reproduce the bug

1. Enable IstioIntegration https://docs.solo.io/gloo-edge/latest/guides/integrations/service_mesh/istio/

### Expected Behavior

The proxy generation should take about the same time as when IstioIntegration is disabled.

**Comment by elcasteel** [comment]
From slack, we think the use of `UpstreamClient` in the plugin is likely the problem and have been discussing ways to get the upstream names and service types from the snapshot.

**Comment by jenshu** [comment]
fix available in GlooEE v1.14.0-beta11, v1.13.13, v1.12.51
