### ISSUE TITLE
Lambda requests 413 Payload Too Large when attachment is greater than ~1.3MB 

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#8059]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

Request that goes through routeTable with aws block gets 413 when payload is greater than ~1.3MB
```
            routeAction:
              single:
                destinationSpec:
                  aws:
                    logicalName: cxd-help-service-development-createGeneralCase
                    unwrapAsApiGateway: true
                    requestTransformation: true
                    # wrapAsApiGateway: true
                    # responseTransformation: false
                upstream:
                  name: gloo-lambda-integration
                  namespace: gloo-system
```

It is not clear where this limit is coming from nor how to adjust it. 

Hitting the lambda directly 

### Steps to reproduce the bug

1. Configure VirtualService 
2. Configure RouteTable with aws
3. Send form with attachment > 1.3MB

### Expected Behavior

It would be useful to know what is the limit being imposed and how to adjust this limit.  

### Additional Context

- 1.3Mb seems to be upper limit for single file
- 8mb image directly to lambda worked fine.
- Removed auth filter and still seeing 413's
- Only request transform sending headers to lambda now

debug logs from gateway proxy

```
[2023-03-28 18:36:25.433][20][debug][jwt] [external/envoy/source/extensions/filters/http/jwt_authn/filter.cc:141] Called Filter : decodeData
[2023-03-28 18:36:25.433][20][debug][http] [external/envoy/source/common/http/filter_manager.cc:901] [C140][S7869348186028788777] Sending local reply with details transformation_filter_error
[2023-03-28 18:36:25.433][20][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1525] [C140][S7869348186028788777] encoding headers via codec (end_stream=false):
':status', '413'
'ingress', 'sogo'
'content-length', '17'
'content-type', 'text/plain'
'access-control-allow-origin', '[https://development-support.carfax.com](https://development-support.carfax.com/)'
'access-control-allow-credentials', 'true'
'date', 'Tue, 28 Mar 2023 18:36:25 GMT'
'server', 'envoy'
'connection', 'close'
```

**Comment by SantoDE** [comment]
Ask is to be able to configure that limit

**Comment by ben-taussig-solo** [comment]
- The default max-connection size in Gloo Edge is 1,048,576 bytes (~1.1 MB)
   - This is the limit that is being hit in the issue as described above
   - You can increase this by setting the [`perConnectionBufferLimitBytes`](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk/#listeneroptions) listener option
   - See [here](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/buffering/#gateway-listener) for an example configuration
   - Making this change locally allows me to succesfully send 5.9 MB requests to a lambda upstream
 - AWS Lambda still has a maximum request/response payload size of 6 MB for synchronous invocations
   - See [here](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html) for more information -- the specific limit is under "Invocation payload (request and response)"

**Comment by kevin-shelaga** [comment]
Initial testing looks good that the suggested setting could resolve this issue. Waiting for the dev team to return today to confirm.

**Comment by kevin-shelaga** [comment]
Confirmed setting fixed the issue! Thank you all.
