### ISSUE TITLE
Trivy scan stopped scanning 1.14

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#8070]
### Gloo Edge Version

1.14.x (beta)

### Kubernetes Version

None

### Describe the bug

We have been fixing cves on 1.14 as we discover them on 1.13 but it seems that issue creation in oss has stopped.

### Steps to reproduce the bug

Run scheduled scans when there are known local issues.

### Expected Behavior

See an issue created and see 1.14 in the map of releases generated in the action.

**Comment by sam-heilbron** [comment]
[Internal clack context](https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1680784800063289)

We do not include beta images in our weekly scans. The linked conversation explains how we could introduce this if we want to in the future.

We agreed to close the current issue as scanning of betas was never supported and we can open a feature request in the future should they be necessary.
