### ISSUE TITLE
Provide Documentation on the Validation API

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8086]
### Version

master

### Describe the requested changes

There is currently no documentation on the usage of the Validation API. Requesting documentation on the usage with examples.

Will provide samples in comments

**Comment by bdecoste** [comment]
```
$ k -n gloo-system port-forward service/gloo 8443:443
Forwarding from 127.0.0.1:8443 -> 8443
Forwarding from [::1]:8443 -> 8443
Handling connection for 8443
```


```
$ curl -k -XPOST -d '{"request":{"uid":"1234","kind":{"group":"gateway.solo.io","version":"v1","kind":"VirtualService"},"resource":{"group":"","version":"","resource":""},"name":"update-response-code","namespace":"gloo-system","operation":"CREATE","userInfo":{},"object":{ "apiVersion": "gateway.solo.io/v1", "kind": "VirtualService", "metadata": { "name": "update-response-code", "namespace": "gloo-system" }, "spec": { "virtualHost": { "domains": [ "foo.com" ], "routes": [ { "matchers": [ { "prefix": "/" } ], "routeAction": { "single": { "upstream": { "name": "postman-echo", "namespace": "gloo-system" } } }, "options": { "autoHostRewrite": true } } ], "options": { "transformations": { "responseTransformation": { "transformationTemplate": { "headers": { ":status": { "text": "{% if default(data.error.message, \"\") != \"\" %}400{% else %}{{ header(\":status\") }}{% endif %}" } } } } } } } } }}}' -H 'Content-Type: application/json' https://localhost:8443/validation
{"response":{"uid":"1234","allowed":false,"status":{"metadata":{},"message":"resource incompatible with current Gloo snapshot: [Validating *v1.VirtualService failed: 1 error occurred:\n\t* Validating *v1.VirtualService failed: validating *v1.VirtualService name:\"update-response-code\"  namespace:\"gloo-system\": Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream { gloo-system.postman-echo } not found\n\n]","details":{"name":"update-response-code","group":"gateway.solo.io","kind":"VirtualService","causes":[{"message":"Error Validating *v1.VirtualService failed: 1 error occurred:\n\t* Validating *v1.VirtualService failed: validating *v1.VirtualService name:\"update-response-code\"  namespace:\"gloo-system\": Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream { gloo-system.postman-echo } not found\n\n"}]}}}}
```

**Comment by Rachael-Graham** [comment]
Plan to revise these guides, plus also provide example curl requests (bc this customer is using yamls formatting into json for the curl, instead of directly applying a yaml file). we actually do not have any docs at all on doing the request in the style that they are doing it. maybe we should give a curl example for the most common crds, like virtual service, upstream, and gateway maybe? theoretically, if they had one example that should be enough as well.

**Comment by Nadine2016** [comment]
draft PR https://github.com/solo-io/gloo/pull/8555/files

**Comment by Nadine2016** [comment]
after running tests we found inconsistencies between using the webhook via `kubectl apply --dry-run=server` and running the request against the validation API directly. for now, we decided to hide the requests to the validation API until a decision is made for this issue https://github.com/solo-io/gloo/issues/8566. 

depending on the outcome, we either fix the validation API or document what works/ what does not work in a new PR

**Comment by jswinner09** [comment]
Re-opening the ticket with feedback after sharing the updated doc.

The example in the link shows an upstream resource. A further ask is to include examples of other resources as well. Suggestions and questions are included in this diagram attached. Seeing if this could be added?
![image001](https://github.com/solo-io/gloo/assets/116743312/d9e1e367-b8b0-4ae1-9a14-cee4a0f44b6b)

**Comment by jswinner09** [comment]
Hi @Nadine2016 Amex brought this up in our weekly call yesterday. I know it was in the process of being triaged. Is there any sort of timeframe or ETA we can share for when this might be picked back up? Thank you! cc: @jaymiracola

**Comment by Nadine2016** [comment]
I added this PR https://github.com/solo-io/gloo/pull/9038. Note that we need to wait until Sam is back on 1/10 to validate a couple of things that I noticed during my testing.

**Comment by Nadine2016** [comment]
in prod https://docs.solo.io/gloo-edge/main/guides/traffic_management/configuration_validation/admission_control/#validation-api-reference closing
