### ISSUE TITLE
Gloo validation leaks invalid regexRewrite to Envoy 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8091]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

The following route regexRewrite is leaked by Gloo validation and is rejected by Envoy:

`^/proxy/v1/store/[^/]*/xyz/order/status/[^/]*)`

`[2023-04-13 19:43:03.888][8][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:126] gRPC config for [type.googleapis.com/envoy.config.route.v3.RouteConfiguration](http://type.googleapis.com/envoy.config.route.v3.RouteConfiguration) rejected: unexpected ): ^/proxy/v1/store/[^/]*/xyz/order/status/[^/]*)`

### Steps to reproduce the bug

Deploy a VirtualService with a Route with the regexRewrite above

### Expected Behavior

Invalid route regexRewrite are caught by Gloo validation and do not leak to Envoy

**Comment by ianmacclancy** [comment]
Envoy docs: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-regex-rewrite

Gloo edge docs: https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/regex_rewrite/
- I figure adding regex spec to the docs will be helpful to customers - I will be updating the description of regexRewrite and will see if I can update the guide as well. 

Edge code location: https://github.com/solo-io/gloo/blob/5994ce1005a74a7e5d990ecc5abd1af5c9b3e3fb/projects/gloo/pkg/plugins/basicroute/plugin.go#L106

**Comment by ianmacclancy** [comment]
CFA example link for long regex - https://solo-io-corp.slack.com/archives/C04EBE250E9/p1681996879842649?thread_ts=1681993929.222929&cid=C04EBE250E9

**Comment by bdecoste** [comment]
Can we get this back-ported to 1.12.x?

**Comment by ianmacclancy** [comment]
Link to the conversation that pertains to @bdecoste ask - https://solo-io.slack.com/archives/GPG5SMLH1/p1683133066309609?thread_ts=1681417024.839469&cid=GPG5SMLH1
