### ISSUE TITLE
[Generated Kube Types Suite] 1.13-1.14 Generated Kube Code

### ISSUE THREAD

**Issue by jackstine** [solo-io/gloo#8099]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

Generated Kube Code [It] can read and write a gloo resource as a typed kube object 
"upstreams.gloo.solo.io \"petstore-static\" already exists"

/workspace/gloo/projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go:97
Failing on Line generated_kube_types_test.go:139

We may want to move this to kube e2e tests so that it is tested there and not in the regressions tests suites.

[Logs are here](https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=4450e4d8-4532-49db-9625-6c67f6882084)
[Experienced in this PR](https://github.com/solo-io/gloo/pull/8098)

### Steps to reproduce the bug

N/A

### Expected Behavior

Should work

**Comment by sheidkamp** [comment]
Seeing it here too: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=d9c6d8c6-0c67-4fa7-9c6a-9e90a421f624 on a backport to 1.13.x

**Comment by Bslabe123** [comment]
Here as well
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=e3581623-0bc4-48a3-aa91-5ab9cab2b8a4

**Comment by artberger** [comment]
Saw this [here](https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=7826b58e-684d-423f-82c7-9e2455cc7546), from this docs 1.14 backport [PR](https://github.com/solo-io/gloo/pull/8119).

**Comment by ben-taussig-solo** [comment]
Been seeing this a lot the last two days:
 - https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=1d9f9301-ed0a-4aed-92f8-ad6a8280b3a8
 - https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=76f158f5-fdc8-4bd8-ad04-e15aec98b0f7
 - https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=e182c3f1-d62f-46e2-84cb-410180c0cbb7

**Comment by ianmacclancy** [comment]
unable to get this pr to build because of this - https://github.com/solo-io/gloo/pull/8183

**Comment by ashishb-solo** [comment]
Reopening, as the fix for this is not yet on master

**Comment by bewebi** [comment]
As of #8235 we no longer use the long-running k8s cluster in cloudbuild as part of CI
Therefore this flake should not occur
