### ISSUE TITLE
Supporting application specified cookies for session affinity

### ISSUE THREAD

**Issue by pseudonator** [solo-io/gloo#8106]
### Version

1.13.x (latest stable)

### Is your feature request related to a problem? Please describe.

Currently, Envoy supports session affinity for backend systems via a session cookie that is generated within the proxy. This session cookie includes a hash of the upstream host information.

_A typical problem description where this could not fit would be:_

_The application has a concept of login which starts a user session of a known period, lets say e.g. 8 hours for a typical session lasting for a workday. The application instance keeps the user session data in memory for that period. User closes the browser and re-opens. The request is re-initiated. However, this time the request reaches another instance of the service. User would be prompted to go through the same login process._

Without changes to the cookie to support this behaviour the proxy will never know where the session originated from. So the question is would it be possible for the proxy to attach the hash of the host info to the generated cookie ? 

This is certainly not possible to do in Envoy but potentially a custom filter could solve this.

[HAProxy has a concept](https://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/#using-application-session-cookie-for-persistence) where it modifies the cookie to keep track of the session origination.

### Additional Context

Refer to the [issue ticket](https://solo-io.zendesk.com/agent/tickets/1756) for further context.

**Comment by pseudonator** [comment]
@kdorosh This is something that isnt acceptable by the team who owns the service (that generates the said session cookie). I guess they want to able to track the session internally in the apps.

**Comment by bensolo-io** [comment]
From apac sync - further details from customer are required - session will be set up before this work starts

**Comment by AkshayAdsul** [comment]
As confirmed by the customer they have a working solution in Production and this is no longer needed. Thanks.
