### ISSUE TITLE
Access logs

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#814]
@bettyjunod @ilackarms For HIPAA, we need access logs.  

My preliminary research suggests that we can get these from envoy.  Like the author of [this GitHub Issue] (https://github.com/heptio/contour/issues/624), I too would prefer JSON structured logs. 

What appears missing is the identity of the requestor. This would come from an oauth
Token.

In any case, this is a BLOCKER for my production deployment.  

[Amazon API Gateway](https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-api-gateway-supports-access-logging/) appears to offer something also.

**Comment by EItanya** [comment]
envoy documentation about access logging: https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log

**Comment by ilevine** [comment]
we are started to work on this, and you will get this soon

**Comment by yuval-k** [comment]
@derrickburns do you expect to use file based access logging, or gRPC Access Log service?

**Comment by derrickburns** [comment]
I don't see a need for gRPC access unless that provides me data that I need that the file based access does not.

As I mentioned above, I need some headers from the input (related to user identity/authentication) to be added to the log entries.  If the files have that data or allow me to specify which headers I want, then I can use files.

**Comment by rickducott** [comment]
We're preparing a release with this feature now, should be available in v0.18.1 @derrickburns

**Comment by derrickburns** [comment]
Awesome!!
