### ISSUE TITLE
Regex Max Program size is too small for customers

### ISSUE THREAD

**Issue by ianmacclancy** [solo-io/gloo#8184]
### Version

1.13.x

### Is your feature request related to a problem? Please describe.

Customers are getting hit with regex issues when their program size is too small
We allow them to specify a max program size through helm values - gloo.settings.maxRegexProgram size 
This will default to the enovy max of 100 if not set and often this causes issues

Solution: we are changing the default to 1024

**Comment by inFocus7** [comment]
# Release information

## Released in...
- Gloo OSS `v1.15.0-beta6`

## To-be-released in...
- Gloo EE `v1.15.0-beta2`
