### ISSUE TITLE
Support K8s 1.27

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#8214]
### Version

1.15.x (beta)

### Is your feature request related to a problem? Please describe.

I want Gloo Edge to use the latest stable Kubernetes version

### Describe the solution you'd like

- [ ] Read 1.27 release notes, and focus on breaking changes. Given those findings, work with the leads to determine if there are features we should consider supporting (and can create relevant issues)
- [ ] Enable our tests to use k8s 1.27 (PRs and weekly tests) on Edge 1.15, and update our support docs to reflect this
- [ ] Update our main branch to use kube 1.27 library

**Comment by sheidkamp** [comment]
Will be in GlooEE v1.14.7, v.1.13.21, and 1.15.0-beta-4.

If we need to fast track one of those releases, I am happy to do that.

**Comment by sheidkamp** [comment]
Tracking some work in this doc: https://docs.google.com/document/d/10JJDpwPzssSBDlj2B_eTisqZqtoHZPqdt-jmQyrneKU/edit
