### ISSUE TITLE
Header Manipulation Validation

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#8225]
### Gloo Edge Version

1.14.x (latest stable)

### Kubernetes Version

None

### Describe the bug

header manipulation currently does not validate scheme manipulation.

As a part of this issue we MUST determine if headers to append is correct for scheme or if we need a different field and if we need any additional checks on header manipulation fields.

For this issue we MUST support validating that if scheme is set it is valid. This means minimally validating http /https https://github.com/envoyproxy/envoy/blob/06f5991bb171b1f79c8488f2e0ef49708439ae62/api/envoy/config/core/v3/protocol.proto#L626

As part of this issue we MUST determine if setting https on an http vs is treated as invalid https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html#scheme

### Steps to reproduce the bug

Apply 
`      headerManipulation:
        responseHeadersToAdd:
          - header:
              key: ":scheme"
              value: "https"`

To an http virtual service

### Expected Behavior

Envoy does not reject configuration bad header manipulation as we catch it in the control plane.

### Additional Context

From the Envoy docs:
An invalid (not “http” or “https”) scheme, or an https scheme over an unencrypted connection will result in Envoy 
rejecting the request. This is the only scheme validation Envoy performs as it avoids a HTTP/1.1-specific privilege escalation attack for edge Envoys [1]
(https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#id3) which doesn’t have a comparable vector for HTTP/[2]
(https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#id4) and above 2.

**Comment by sheidkamp** [comment]
Talking with Ethan, it looks like we can't directly set the `:scheme` header to ANY value, and have to use [scheme_header_transformation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-scheme-header-transformation) instead (see also https://github.com/solo-io/gloo/issues/8254) so there is an extra translation piece as well

**Comment by sheidkamp** [comment]
Will be released with `v1.13.20` and `v1.14.7`
