### ISSUE TITLE
Additional logging for Transformations | Graphql Transformations

### ISSUE THREAD

**Issue by afro-coder** [solo-io/gloo#8232]
### Version

1.13.x

### Is your feature request related to a problem? Please describe.

Currently we support a variety of options for logs, however, we don't log things such as entire requests/responses before and after transformation for logging, this also applies for GraphQL, due to this the Customer isn't able to debug Transformations and Transformations done via GraphQL.

### Describe the solution you'd like

- Ability to switch to a  more verbose logging and turn it off when needed.
- Request/Response logging with body pre/post transformations.
- Request/Response logging with body with Graphql for each Requests/Responses.

### Describe alternatives you've considered

Dynamic Metadata, however it doesn't have a good UX and needs changes to be made to the VirtualService

**Comment by ben-taussig-solo** [comment]
The issue describes three requirements for completion:
 - Ability to switch to a more verbose logging and turn it off when needed.
 - Request/Response logging with body pre/post transformations.
 - Request/Response logging with body with Graphql for each Requests/Responses.

The first two of these are introduced in Gloo Edge enterprise [v1.14.5](https://github.com/solo-io/solo-projects/releases/tag/v1.14.5), as well as the most recent beta release, and can be enabled using the `logRequestResponseInfo` [transformation setting](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk/#filtertransformations)

The latter has been present in Gloo Edge enterprise for some time, and can be enabled with the `logSensitiveInfo` [graphql setting](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1beta1/graphql.proto.sk/#graphqlapioptions)
