### ISSUE TITLE
Enhanced transformation Logging

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#8266]
### Version

None

### Is your feature request related to a problem? Please describe.

Today Transformations can fail or act in ways that are not entirely intuitive to new users of edge. It would be nice to enable easier full debug dumps of logs under certain conditions to allow for easier debugging of transformation logic in Dev/Staging level environments along with the possibility for guarded enablement in production.

### Describe the solution you'd like

For now I would like to see this act like the sensitive logging that was introduced in Grapqhl filter.

Namely we MUST log the pre Transform request body + headers and the post Transform response body + headers.
On the response we MAY choose to truncate on some sizes
These logs MUST be opt in like with graphql
The control plane toggle SHOULD be nullable to safe guard against the inevitable inheritance logic we will add.

Post Transform logs are NOT in scope for this issue and will be tackled in a separate issue as this should mainly be for turning on sensitive logging but should be considered for the toggle data type (namely is it one field many fields or even things that may be located on different objects in the control plane)

### Describe alternatives you've considered

Wasm filter for logging.

### Additional Context

This is useful for new customers but also more importantly for new team members to an application team.
Too often writing transformations on a more complex data set can be painful if you miss some piece of syntax so this should help mitigate that pain.

https://github.com/solo-io/gloo/issues/8232

**Comment by ben-taussig-solo** [comment]
This feature is in solo-projects [v1.14.5](https://github.com/solo-io/solo-projects/releases/tag/v1.14.5), as well as the most recent beta release.

**Comment by nfuden** [comment]
Overrides from the settings level are not being respected

**Comment by ben-taussig-solo** [comment]
Backport PRs to resolve the issue with the global setting in Gloo Edge Enterprise are up here:
v1.15.x: (beta): https://github.com/solo-io/gloo/issues/8266
v1.14.x: https://github.com/solo-io/solo-projects/pull/5110

**Comment by ben-taussig-solo** [comment]
These fixes were released in [v1.14.6](https://github.com/solo-io/solo-projects/releases/tag/v1.14.6). Closing the issue
