### ISSUE TITLE
Helm variable name should not contain a hyphen

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#827]
Your default first gateway proxy is named "gateway-proxy".  Unfortunately, Helm does not like this name if used directly, as in `.Values.gloo.gatewayProxies.gateway-proxy`.

See

https://helm.sh/docs/chart_best_practices/#naming-conventions

**Comment by rickducott** [comment]
hey @derrickburns just wanted you to know, we renamed this in v0.17.2

**Comment by derrickburns** [comment]
Yessir thx!

Derrick

**Comment by kdorosh** [comment]
fyi, we are moving back to a map based structure in this PR https://github.com/solo-io/gloo/pull/859

because of issues with providing overrides in helm values files reported here: https://github.com/solo-io/gloo/issues/857

The new PR will use proper helm naming conventions
