### ISSUE TITLE
Build test release Github action in OSS

### ISSUE THREAD

**Issue by jbohanon** [solo-io/gloo#8294]
### Version

None

### Is your feature request related to a problem? Please describe.

Currently there is a GHA in solo-projects that allows devs to build a test release from a branch (using a OSS commit if desired). This handily builds & pushes the images, and builds a test chart, logging commands that can be copied and pasted to install that release anywhere. 

Currently to achieve this I create a branch in solo-projects, bump gloo to the latest commit on my branch, then run the Action, cancelling it after the OSS build completes.

### Describe the solution you'd like

It would be nice to have an equivalent Action in this repo so we could build OSS test releases directly instead of having to tie it in to solo-projects. 

### Describe alternatives you've considered

Alternatives:
- Leave it how it is. It's a workable system if a bit clunky
- Add a toggle to the solo-projects action which disables the EE build, similar to the gloo fed toggle we have currently
  - This still requires a solo-projects branch which must be manually kept up with the latest commit on the gloo branch

**Comment by sam-heilbron** [comment]
I'm not sure this is necessary actually.In Gloo OSS, we publish assets on PRs (to enable them to be picked up in Enterprise).

If you open a PR, we run https://github.com/solo-io/gloo/blob/main/ci/cloudbuild/publish-artifacts.yaml and you can find assets after this job completes. I agree the UX can be better and we're hoping to build nightly builds in the coming weeks.
