### ISSUE TITLE
Support External Processing Filters in Gloo

### ISSUE THREAD

**Issue by Ido-Itz** [solo-io/gloo#8320]
### Version

1.14.x (latest stable)

### Describe the solution you'd like

Envoy supports filters of type [External Processing Filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_proc_filter).
I would like to be able to register generic External Processing filters, pointing to an upstream of my choice through the Gloo control plane. Similar to how Gloo allows the configuration of a Custom Auth Server filter.

I would also like the ability to specify to Gloo where I want this filter to run, i.e.  downstream request / upstream response / both.

Thanks!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207327219083815) by [Unito](https://www.unito.io)

**Comment by sam-heilbron** [comment]
Confirmed with @SantoDE that this is still high priority and we are working on it, but it is not a blocker for the 1.15 release

**Comment by jenshu** [comment]
The initial ExtProc control plane support (using only what's currently available in envoy) has been released into GlooEE v1.15.0-rc2. Leaving this issue open for the envoy enhancements.

**Comment by jbohanon** [comment]
@nfuden @sam-heilbron I am unclear what this issue is tracking at this point. Can this be closed?

**Comment by nfuden** [comment]
This should not have been added to the github project. This is a public facing tracking for the rest of our internal milestone to adopt your upstream contributions and the transition guide for cutting over.

**Comment by nfuden** [comment]
@jbohanon https://github.com/solo-io/solo-projects/milestone/36

**Comment by nfuden** [comment]
This has been completed in 1.16 with some migration caveats for 1.17 on the server side of the definition.
