### ISSUE TITLE
Possible Upstream Name collisions on short names

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#836]
In [uds_convert_test.go](https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go#L40-L44) we can see that the expected contract is that uds_convert.go's `UpstreamName` function will handle name collisions.

The test (linked above) works fine, but only because it's leveraging the hash appended to the upstream name because of its length:
```go
It("should handle colisions", func() {
	name := UpstreamName(strings.Repeat("y", 120), "gloo-system", 12, nil)
	name2 := UpstreamName(strings.Repeat("y", 120)+"2", "gloo-system", 12, nil)
	Expect(name).ToNot(Equal(name2))
})
```

A similar test that should pass (but fails) is:
```go
It("should handle collisions when name is short", func() {
	name := UpstreamName("ns*", "gloo-system", 12, map[string]string{"test": "label"})
	name2 := UpstreamName("ns.", "gloo-system", 12, map[string]string{"test": "label"})
	Expect(name).ToNot(Equal(name2))
})
```
This happens because both `*` and `.` get rewritten to `-`.

Issue here is to fix the behavior so the second test passes. Some possible solutions here are:
* always append a hash
* increment a counter and append when sanitized names are duplicates

**Comment by ilevine** [comment]
a counter may yield non deterministic results over time as upstreams come and go.
