### ISSUE TITLE
Split watch and service discovery namespaces

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#841]
The `Settings` proto contains the following TODO:

```proto
message Settings {
    // namespace to write discovered data
    string discovery_namespace = 1;
    // namespaces to watch for user config as well as services
    // TODO(ilackarms): split out watch_namespaces and service_discovery_namespaces...
    // namespaces to watch for user config
    repeated string watch_namespaces = 2;

    // ...
}
```

@ilackarms Could you provide some detail about what you had in mind with this?

**Comment by ilackarms** [comment]
@marcogschmidt gloo and its components do a lot of watching.
each crd type gets its own watch
services, endpoints, and pods each get their own watch (by uds/eds)

the idea here is to split functioning of watchNamespaces, so the namespaces we watch for crds are not tied to the namespaces we watch for services
