### ISSUE TITLE
Supported versions inconsistent 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8418]
### Version

main

### Describe the requested changes

This doc looks inconsistent. It states that 1.10 is supported but then says that we support N-3 so 1.10 is not supported. Thanks! https://docs.solo.io/gloo-edge/latest/reference/support/

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/latest/reference/support/

**Comment by artberger** [comment]
Doc updates:
* On main, removed references to 1.10 https://github.com/solo-io/gloo/commit/38da05268495215f9b0d827fcb780fc999813bb5

**Comment by Nadine2016** [comment]
this had been fixed earlier. and now got updated to reflect the latest supported versions as part of the doc fixes branch. closing
