### ISSUE TITLE
Ability to specify which gateway to sidecar the extauth in multi-gateway deployment

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#8430]
### Version

1.14.x (latest stable)

### Is your feature request related to a problem? Please describe.

Currently you are able to sidecar the extauth into the gateway proxy with the `global.extensions.extAuth.envoySidecar` option.  For a multi gateway deployment https://docs.solo.io/gloo-edge/latest/installation/advanced_configuration/multi-gw-deployment/ it will side car all gateways with the extauth container.

### Describe the solution you'd like

It would be nice to have the ability to specify which gateway to sidecar the extauth container in multi-gateway deployment.

**Comment by davidjumani** [comment]
Added in https://github.com/solo-io/solo-projects/pull/5503 and will be part of v1.16.0-beta3 when released
