### ISSUE TITLE
Duplicated proto definition from transformation filter

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#844]
We currently manually copy the proto definition for the transformation filter from [envoy-gloo](https://github.com/solo-io/envoy-gloo/blob/master/api/envoy/config/filter/http/transformation/v2/transformation_filter.proto) over to [`gloo`](https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/plugins/transformation/transformation.proto). We should find a solution to automate this process.

**Comment by yuval-k** [comment]
related to https://github.com/solo-io/gloo/issues/608
