### ISSUE TITLE
Pod disruption budget is not exposed in enterprise helm chart values for Gloo Pod 

### ISSUE THREAD

**Issue by AkshayAdsul** [solo-io/gloo#8445]
### Version

None

### Is your feature request related to a problem? Please describe.

Pod disruption budget is not exposed in enterprise helm chart values for Gloo Pod .
Need to add this.

### Describe the solution you'd like

Currently we do not have a way to set the PDB for the Gloo Pod from the helm charts. We would like a way to expose this.

**Comment by bewebi** [comment]
The issue was closed prematurely

The PR has merged for this feature and will be released in v1.16.0-beta5, however backports to 1.15 and 1.14 have not been completed

**Comment by bewebi** [comment]
Backports have now been merged

The new values will be available in v1.16.0-beta5, v1.15.2, and v1.14.19
