### ISSUE TITLE
Support query/form params in transformation plugin

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#845]
Placeholder to keep track of these removed TODOs in `transformation/parameters.proto`:

```
//TODO: support query params
//TODO: support form params
```

@ilackarms @yuval-k Do you think this is still relevant?

**Comment by yuval-k** [comment]
i believe it is still relevant

**Comment by MikeSouza** [comment]
Yes, this is relevant to our use cases as well.
