### ISSUE TITLE
remove devMode from settings

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#848]
not sure if it's still in use anywhere but i think it can be removed.

doesn't look great

**Comment by marcogschmidt** [comment]
@ilackarms It's currently used only [here](https://github.com/solo-io/gloo/blob/ad6d2077d071b31f5f94aa0eec6cd6e434af05f7/projects/gloo/pkg/syncer/translator_syncer.go#L49).

**Comment by yuval-k** [comment]
this is actually a good use for it as it allows debugging the snapshot with a rest interface
we should probably add some form of REST bridge to the envoy XDS before removing this
