### ISSUE TITLE
Docs: Verify Envoy/ Kubernetes versions

### ISSUE THREAD

**Issue by Nadine2016** [solo-io/gloo#8481]
### Version

main

### Describe the requested changes

We have bumped versions, such as the Envoy version for 1.15. Add 1.15 to the supported versions here https://docs.solo.io/gloo-edge/latest/reference/support/ and verify that the supported versions that we currently list are correct.

**Comment by Nadine2016** [comment]
Envoy got bumped from 1.25.x to Envoy 1.26.x

**Comment by Rachael-Graham** [comment]
Added commit here: https://github.com/solo-io/gloo/pull/8497/commits/aa5593d046c523862b12a06a6260f95f37970c1f

Verified w Sam that this looks correct, and we do not need to add envoy info here, as we added it in the upgrade page PR.

Note to self: Will keep this issue open to track backporting this version page once 1.15 is released to the other LTS branches, as we need to show the same table across all versions.
