### ISSUE TITLE
1.15 upgrade docs need info from Envoy 1.26 changelog

### ISSUE THREAD

**Issue by jbohanon** [solo-io/gloo#8486]
### Version

main

### Describe the requested changes

Include the following information in the upgrade docs and/or changelog for 1.15.0 which includes a dependency bump from Envoy 1.25.x onto Envoy 1.26.x

### Header validation
Envoy changelog:
```
http: Validate upstream request header names and values. The new runtime flag envoy.reloadable_features.validate_upstream_headers can be used for revert this behavior.
```
Effect: 
Envoy will now validate header names and values before a request is made to the upstream. This is done after _any_ transformations and thus could affect any users which have transformations that alter header names or values into an invalid form.

### `x-envoy-original-path` sanitization
Envoy changelog:
```
http: Fixed a bug where x-envoy-original-path was not being sanitized when sent from untrusted users. The header is only removed when sent from untrusted users, and not also before being sent to an upstream server. This behavioral change can be temporarily reverted by setting envoy.reloadable_features.sanitize_original_path to false.
```
Effect:
Envoy previously had a bug where `x-envoy-original-path` was not stripped from untrusted requests. This is a crucial bugfix to prevent malicious actors from injecting this value to alter Envoy behavior, however it is possible that some users had been abusing this ability deliberately as a feature. 

### gRPC invalid protobuf fix
Envoy changelog:
```
grpc: When Envoy was configured to use ext_authz, ext_proc, tap, ratelimit filters, and gRPC access log service and an http header with non-UTF-8 data was received, Envoy would generate an invalid protobuf message and send it to the configured service. The receiving service would typically generate an error when decoding the protobuf message. For ext_authz that was configured with failure_mode_allow: true, the request would have been allowed in this case. For the other services, this could have resulted in other unforseen errors such as a lack of visibility into requests (eg request not logged). Envoy will now by default sanitize the values sent in gRPC service calls to be valid UTF-8, replacing data that is not valid UTF-8 with a ! character. This behavioral change can be temporarily reverted by setting runtime guard envoy.reloadable_features.service_sanitize_non_utf8_strings to false.
```
Effect:
This will not negatively affect users at all, however we should celebrate this fix. Previously the failure mode of this was very obtuse and hard to debug. Now Envoy will sanitize these values sensibly.

**Comment by Nadine2016** [comment]
added this commit to our upgrade guide https://github.com/solo-io/gloo/compare/main...docs-upgrade
