### ISSUE TITLE
Expose custom request headers with GrpcHealthCheck 

### ISSUE THREAD

**Issue by AkshayAdsul** [solo-io/gloo#8490]
### Version

None

### Is your feature request related to a problem? Please describe.

Gloo Edge v1.14.2  does not support custom request headers with [GrpcHealthCheck] (https://github.com/solo-io/gloo/blob/cbd4129accd5f5059903f840585a98a0c4689726/projects/gloo/api/external/envoy/api/v2/core/health_check.proto#L171) where as the version of Envoy (v1.25.6) it uses does support the feature in the config API [config.core.v3.HealthCheck.GrpcHealthCheck](https://www.envoyproxy.io/docs/envoy/v1.25.6/api-v3/config/core/v3/health_check.proto#config-core-v3-healthcheck-grpchealthcheck)
Could you please help expose those configurations in Upstream CRD? 

### Additional Context

This is a blocker for customer  to onboard gRPC applications

**Comment by sam-heilbron** [comment]
@SantoDE and I spoke on slack (https://solo-io-corp.slack.com/archives/C03L190TQDA/p1689844521806349) and agreed this is not a release blocker.

**Comment by davidjumani** [comment]
Added to 1.15 via https://github.com/solo-io/gloo/pull/8511 and part of [v1.15.0-beta24](https://github.com/solo-io/gloo/releases/tag/v1.15.0-beta24)
Added to 1.14 via https://github.com/solo-io/gloo/pull/8530 and will be part of v1.14.14 when released

**Comment by davidjumani** [comment]
I'd like to add some tests in enterprise and will do so when raising a bump PR. Keeping this open until then

**Comment by davidjumani** [comment]
Added in enterprise 1.14 via and will be part of v1.14.8 when released
Waiting on https://github.com/solo-io/solo-projects/pull/5200 to get into enterprise 1.15
