### ISSUE TITLE
Support json formatting for rate-limit and extauth logging

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8502]
### Version

1.13.x

### Is your feature request related to a problem? Please describe.

The current simple formatting for rate-limit and extauth logging is not properly consumed by out enterprise logging system

### Describe the solution you'd like

Gloo supports json formatting for rate-limit and extauth logs 

### Describe alternatives you've considered

None

**Comment by bdecoste** [comment]
The basic conversion of our zap / logrus (libraries we use) to emit as json is very doable but we emit logs from a few different sub libraries that are more of a challenge. Will start with the former.

**Comment by nfuden** [comment]
context https://solo-io-corp.slack.com/archives/C0289JZGV8R/p1687550662436819

**Comment by DuncanDoyle** [comment]
Closing. No longer required.
