### ISSUE TITLE
k8s 1.28 (edge 1.16)

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#8515]
### Version

None

### Is your feature request related to a problem? Please describe.

Part of maintaining a solid product and avoiding breaking changes or massive backports over the life of an LTS branch we must keep our deps in check. In this case its kubernetes

**Comment by sam-heilbron** [comment]
https://github.com/solo-io/gloo/issues/8164#issuecomment-1550281628

**Comment by sam-heilbron** [comment]
https://github.com/solo-io/skv2/blob/main/go.mod#L3

**Comment by nfuden** [comment]
@Sodman we are looking at picking this soon lets chat

**Comment by Sodman** [comment]
No issues from a GP perspective with bumping skv2. GME repo is already on k8s 1.28 dependencies, so I recommend we just bump the minor version of skv2 release and hold off on the next "major" bump until 1.29.

**Comment by sheidkamp** [comment]
Documents from the 1.27 update that may be of use:

solo-projects PR that references all of the other PRs: https://github.com/solo-io/solo-projects/pull/5200
google doc for tracking the repositories and their statuses (mostly the same information as the PR): https://docs.google.com/document/d/10JJDpwPzssSBDlj2B_eTisqZqtoHZPqdt-jmQyrneKU
