### ISSUE TITLE
Allow specification of the proxy resource

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#856]
Currently the proxy resource name is hardcoded [here](https://github.com/solo-io/gloo/blob/1b57d977f67eeae377e622c18c578e21581dabd0/projects/gateway/pkg/translator/translator.go#L47). In order to support additional proxies within a single namespace we will have to do away with this limitation

**Comment by yuval-k** [comment]
we will also need something like an installation id for the deployment

**Comment by rickducott** [comment]
These are resolved
