### ISSUE TITLE
Istio 1.18

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#8621]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.15.0

### Is your feature request related to a problem? Please describe.

k8s 1.27 is used in Gloo Edge 1.15, but that is not a [supported version](https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases) with Istio 1.17. As a result, for anyone to use Istio with Kubernetes 1.27, Gloo Edge needs to support Istio 1.18.

### Describe the solution you'd like

Support Istio 1.18, with automated testing and updated documentation. Add this to GE 1.15 as well.

### Additional Context

Internal slack context: https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1692896717278849

**Comment by bewebi** [comment]
PRs have merged in OSS for 1.16-beta and 1.15 which include a fix for Istio support, additional testing to verify the Istio integration functions as intended, and documentation of the preferred usage pattern
This has been released in OSS 1.16.0-beta14 and will be included in OSS 1.15.10, EE 1.15.5, and EE 1.16.0-beta1
