### ISSUE TITLE
priorityClassName specified for gateway proxy in helm values not working

### ISSUE THREAD

**Issue by bawk3** [solo-io/gloo#8677]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.14.9

### Kubernetes Version

1.27.4

### Describe the bug

I specify priorityClassName as described in [documentation](https://docs.solo.io/gloo-edge/v1.14.x/reference/helm_chart_values/open_source_helm_chart_values/)
gatewayProxies.NAME.kind.deployment.priorityClassName

But it is not applied to the deployment

Template file of gateway proxy deployment has neither `priority:` field nor include `gloo.podSpecStandardFields` defined in _helpers.tpl and containing priority.

### Expected Behavior

Priority class name is applied to the deployment.

### Steps to reproduce the bug

1. Deploy gloo chart with described gateway proxy
2. Set in values file priorityClassName 
for example `gatewayProxies.gatewayProxy.kind.deployment.priorityClassName: system-node-critical`
3. Run helm diff - it will show no diff
4. Apply helm - gateway proxy has no priority

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1207635280052738/1208161573889002) by [Unito](https://www.unito.io)

**Comment by sam-heilbron** [comment]
See https://github.com/solo-io/gloo/issues/8025#issuecomment-2312984558 for more context. This was resolved in GG Enterprise 1.17.1 and will be in 1.18.0-beta1
