### ISSUE TITLE
Glooctl Add Route repeats prompt when you use arrow keys 

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#868]
e.g.:
```zsh
{⎈ |minikube:default} ➜  gloo git:(glooctl_interactive_vs_message) ✗ glooctl add r --name test -i
? Choose a Virtual Service to add the route to: (empty to add to a default virtual service. the default virtual service matches the '*' domain and will be created if it does not exist)   
? Choose a Virtual Service to add the route to: (empty to add to a default virtual service. the default virtual service matches the '*' domain and will be created if it does not exist)  
? Choose a Virtual Service to add the route to: (empty to add to a default virtual service. the default virtual service matches the '*' domain and will be created if it does not exist)   
[Use arrows to move, type to filter]
> create a new virtualservice
  gloo-system.kdorosh-test
  gloo-system.kdorosh-test2
  gloo-system.test
```

Note that every time you hit an arrow key to toggle between virtual services to add a route to, the prompt is repeated back to you.

**Comment by kdorosh** [comment]
This is a bug (or setting?) in my terminal that happens if the prompt being displayed is longer than the width of my terminal (at its current size). The keystrokes leading to a re-render of the prompt are most noticeable on the `cliutil.ChooseFromList` function.

I'm curious if this happens on other people's terminals, or if it's just limited to mine.

**Comment by ashleywang1** [comment]
This is a bug with the renderer: https://github.com/AlecAivazis/survey/issues/101
