### ISSUE TITLE
Transform to replace a portion of a header value via regex

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8706]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.13.x

### Is your feature request related to a problem? Please describe.

We need to be able to replace a portion of a request header (e.g. cookie) that is sent to the upstream

### Describe the solution you'd like

Inja transform to replace a portion of a header value via regex

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1206790715303129) by [Unito](https://www.unito.io)

**Comment by bdecoste** [comment]
https://github.com/solo-io/gloo-mesh-enterprise/issues/11794

**Comment by edubonifs** [comment]
Customers asking for replace function to be available in inja

**Comment by edubonifs** [comment]
Use case of the client:

At this moment, if you have hundreds of RouteTables and you have different headers reaching each matcher in every RouteTable, if you want to define a RateLimitConfig, you should:

Create RateLimitConfig specifying a a different header for each RouteTable or the same header but different values for each RouteTable.

This would grow a lot as we would need many different RateLimitConfigs for each RouteTable. In summary:

They want to start applying rate limits PER tenant (HTTP header) PER operation. There are two ways to do this:
(1) using a distinct rate limit per operation (hundreds of RateLimitConfig with hundreds of distinct Route (s))
(2) using a reusable rate limit for all operations where the operation id is part of the rate limit descriptor (single Route per service, single RateLimitConfig per service)
---
Solution (1) has a relevant maintenance and development effort as they’ll need to create individual objects for each single operation. It also has a huge toll on the system as they’ll have hundreds of routes to apply each different rate limit to different operations
Solution (2) is elegant and simple - they can have a single Route per service and a single RateLimitConfig per service. It requires less maintenance from their engineering teams and doesn’t have as much an impact on GE.

If they would be able to use replace function in inja, they would only need one RateLimitConfig for every RouteTable, as they could manipulate headers using regex.

**Comment by nfuden** [comment]
Sorry had made a duplicate internal issue. Formally assigning this oss issue as well.

**Comment by ben-taussig-solo** [comment]
Update: I have a nearly ready-for-review PR up here: https://github.com/solo-io/envoy-gloo/pull/301
As discussed in that PR's description, there are a couple of things I need to evaluate before this is ready for review, namely how the new functionality interacts with:
 - `mergeExtractorsToBody`
 - the `extraction` inja callback (which lets a user reference an extraction by name)
