### ISSUE TITLE
Add docs to install Edge via ArgoCD 

### ISSUE THREAD

**Issue by davidjumani** [solo-io/gloo#8724]
### Version

main (1.16.x beta)

### Describe the requested changes

There's already a blog on [From Zero to Gloo Edge in 15 Minutes: ArgoCD GitOps Edition](https://www.solo.io/blog/from-zero-to-gloo-edge-in-15-minutes-gitops-edition/)
As of now, this is just a blog, but there are customers who install Edge via Argo. Having this in the docs will be a good reference, and grow to include best practices specific to this topic.

### Link to any relevant existing docs

https://www.solo.io/blog/from-zero-to-gloo-edge-in-15-minutes-gitops-edition/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1207635280052738/1207994530449008) by [Unito](https://www.unito.io)

**Comment by davidjumani** [comment]
Worth mentioning https://github.com/solo-io/gloo/pull/8738/files#r1341595379 as well

**Comment by Nadine2016** [comment]
there is another blog about this https://github.com/ably77/gloo-edge-argo-rollouts-blog

**Comment by davidjumani** [comment]
Thanks @Nadine2016, that blog is on argo rollouts to trigger changes. The docs that need to ba added here should detail how to install edge via argo

**Comment by Nadine2016** [comment]
this was presented in the enablement session https://drive.google.com/drive/folders/1hq0_AQq7DnJNh1PgMVDo1jwYQijmcf2V .

**Comment by Nadine2016** [comment]
We should also show an example for how to use the Argo Rollouts plugin

**Comment by Nadine2016** [comment]
done for Gloo Gateway https://docs.solo.io/gateway/latest/installation/argocd/

**Comment by Nadine2016** [comment]
edge PR https://github.com/solo-io/gloo/pull/10173

**Comment by Nadine2016** [comment]
in prod https://docs.solo.io/gloo-edge/main/installation/gateway/argo/ closing
