### ISSUE TITLE
Rate limiting not working in gloo-edge open source. 

### ISSUE THREAD

**Issue by MeghaGeo** [solo-io/gloo#8727]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.15.6

### Kubernetes Version

v1.23.0

### Describe the bug

Rate limiting not working in gloo-edge open source. 

I have set up ratelimiting server as per https://github.com/envoyproxy/ratelimit
Changed settings  and virtualservice accordingly.
ref: https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/
https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/setup/#implement-separate

But rate limiting is not working. Any instructions will be helpful

### Expected Behavior

curl `<path-to-service>`  for multiple times will get Too many requests in response

### Steps to reproduce the bug

kubectl edit settings default -n gloo-system
kubectl edit virtualservice default -n gloo-system

**Comment by manuasir** [comment]
Were you able to get this to work? I'm facing the same thing.

**Comment by Peelz** [comment]
How to solve this ?
