### ISSUE TITLE
Export allowMissing field for Gloo Edge

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#8728]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

Hi, 

We have a customer that wants their clients to navigate through the same Upstreams given that the are authenticated or not, authentication is optional.

If users are authenticated, they would like to perform JWT validation, but if they are not authenticated, this JWT validation shouldn't be done.

The only possible way that I have found of doing this in Gloo Edge is having allowMissing field exported.

As it has been exposed on Gloo Gateway I suppose it would be more or less the same procedure.

### Describe alternatives you've considered

A possible workaround for this would be duplicating every matcher in our RouteTables, checking if the header "Cookie" is present, if it is present continue with JWT Validation, if it is not present, don't do JWT validation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1208137921423962) by [Unito](https://www.unito.io)

**Comment by nfuden** [comment]
What does https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/jwt/jwt.proto.sk/#vhostextension not cover for this? 
is it some combo check thing that we are looking for?

**Comment by huzlak** [comment]
@nfuden There's only allowMissingOrFailed where we need to not allow failed, only allow missing. Something like a [validation policy](https://docs.solo.io/gloo-mesh-gateway/latest/reference/api/jwt_policy/#jwtpolicyspec-config-validationpolicy) in GMG, or expose allowMissing option next to already available allowMissingOrFailed.
