### ISSUE TITLE
Flake: Kube2e gateway test failing to delete a secret that is in use

### ISSUE THREAD

**Issue by inFocus7** [solo-io/gloo#8826]
### Which tests failed?

- main regression tests (gateway)
- test/kube2e/gateway/gateway_test.go

```
• [FAILED] [20.306 seconds]
Kube2e: gateway Validation Configuration when allowWarnings=false secret validation [It] should act as expected with secret validation
/home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2109

  Timeline >>
  STEP: failing to delete a secret that is in use @ 10/19/23 05:19:38.689
  [FAILED] in [It] - /home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2112 @ 10/19/23 05:19:43.375

  Attempt #1 Failed.  Retrying ↺ @ 10/19/23 05:19:43.399

  STEP: failing to delete a secret that is in use @ 10/19/23 05:19:44.457
  [FAILED] in [It] - /home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2112 @ 10/19/23 05:19:48.999

  Attempt #2 Failed.  Retrying ↺ @ 10/19/23 05:19:49.229

  STEP: failing to delete a secret that is in use @ 10/19/23 05:19:50.28
  [FAILED] in [It] - /home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2112 @ 10/19/23 05:19:54.669
  << Timeline

  [FAILED] Expected an error to have occurred.  Got:
      <nil>: nil
  In [It] at: /home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2112 @ 10/19/23 05:19:54.669

  Full Stack Trace
    github.com/solo-io/gloo/test/kube2e/gateway_test.glob..func1.15.4.5.2()
    	/home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2112 +0x228

  There were additional failures detected.  To view them in detail run ginkgo -vv
```

### Initial Investigation

Unsure of cause behind the flake. I did a previous investigation and were not able to figure out _why_ the flake occurred, as well as couldn't reproduce it locally after 50+ runs.

The flake is due to [this permalinked line of code](https://github.com/solo-io/gloo/blob/a39fb91c2fb122d5a34353dff891e0b0044bf1dc/test/kube2e/gateway/gateway_test.go#L2112). Because the testRunnerVS references the secret, and since validation is on, we _should_ be receiving an error when trying to delete the secret, but do not.

Maybe relevant: I have only seen this flake regularly occur during nightlies, not in CI runs.

### Additional Information

- Did an initial investigation with no findings [here](https://github.com/solo-io/gloo/pull/8795), so resorted with retrying flakes 3 times. May need more.
- [flake instance 1](https://github.com/solo-io/gloo/actions/runs/6622564897/job/17988295699#step:3:371)
- [flake instance 2](https://github.com/solo-io/gloo/actions/runs/6570099261/job/17847014136#step:3:370)

**Comment by sheidkamp** [comment]
Attempting to mitigate and also adding logging:
https://github.com/solo-io/gloo/pull/9250

Next step if flakes still occur and all settings look correct will be to put the secret delete in an `Eventually` and instead of rerunning the test with `FlakeAttempts`, re-create the secret and attempt to delete until validation/propagation kicks in.

**Comment by sheidkamp** [comment]
Hopeful fix applied to 1.17, 1.16, 1.15.

Will monitor

**Comment by sheidkamp** [comment]
Still happening:
https://github.com/solo-io/gloo/actions/runs/8684845144/job/23813158970
https://github.com/solo-io/gloo/actions/runs/8684161285/job/23811280334

**Comment by sheidkamp** [comment]
Seems to be fixed in main by https://github.com/solo-io/gloo/pull/9119,

Backporting:
* 1.16 - https://github.com/solo-io/gloo/pull/9376
* 1.15 - https://github.com/solo-io/gloo/pull/9376

**Comment by sam-heilbron** [comment]
Nightly tests failure
Logs: https://github.com/solo-io/gloo/actions/runs/9297264763/job/25587142060
Failed Test:
```
  [FAIL] Kube2e: gateway Validation Configuration when allowWarnings=false secret validation [It] should act as expected with secret validation
  /home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2143
```
Error:
```
  STEP: waiting for the modified VS to be accepted @ 05/30/24 05:14:09.372
  STEP: failing to delete a secret that is in use @ 05/30/24 05:14:10.39
  No resources found in gloo-system namespace.
  No resources found in gloo-system namespace.
  [FAILED] in [It] - /home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2143 @ 05/30/24 05:14:12.772
  << Timeline

  [FAILED] Expected an error to have occurred.  Got:
      <nil>: nil
  In [It] at: /home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2143 @ 05/30/24 05:14:12.772

  Full Stack Trace
    github.com/solo-io/gloo/test/kube2e/gateway_test.init.func1.15.4.5.2()
    	/home/runner/work/gloo/gloo/test/kube2e/gateway/gateway_test.go:2143 +0x2e8
```

**Comment by npolshakova** [comment]
This flake should be resolved with https://github.com/solo-io/solo-projects/pull/6648 and haven't been hit recently
