### ISSUE TITLE
FIPS SDS required for FedRAMP compliance

### ISSUE THREAD

**Issue by Jimmmz** [solo-io/gloo#8909]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.14.12

### Kubernetes Version

1.25

### Describe the bug

SDS container cannot run in a FedRAMP cluster because it is not FIPS compliant. SDS fails the customers FedRAMP compliance scans. The customer has a workaround but it involves additional hops so adds latency.

### Expected Behavior

SDS needs to be FIPS compliant

### Steps to reproduce the bug

FedRAMP scan

**Comment by sheidkamp** [comment]
@Jimmmz - want to check in on how far back this needs to get backported. The description text says `1.14` and the labels say `1.15`. Does it still need to go into 1.14? Thanks!

**Comment by sheidkamp** [comment]
@SantoDE - The description reference `v1.14` and the tags reference only `v1.15` and `v1.16`. I would like to confirm how far this will need to be backported. Thanks!

**Comment by Jimmmz** [comment]
@sheidkamp 1.15 is great, thank you

**Comment by sheidkamp** [comment]
Backported into `v1.15` and ready for `v1.15.12` release
Backported into `v1.16` and ready for `v1.16.1` release
