### ISSUE TITLE
Glooctl Edit Command upstream groups

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#894]
We added glooctl support to get, create, and delete upstream group objects in https://github.com/solo-io/gloo/pull/893.

We should loop back and allow users to modify existing upstream groups, e.g.:
- remove an existing destination
- add a new destination
- modify the weight of an existing destination

**Comment by fmedery** [comment]
Hello do you have a target date for this new CLI feature ?
Tx

**Comment by kdorosh** [comment]
Hello @fmedery . We don't have a target date for this feature or plans to address it in the immediate term, but it is on our radar to address soon.

If this is something you would really like to have, feel free to draft a PR yourself and we'd be happy to review it with you.

**Comment by rickducott** [comment]
Going to close as stale -- can edit the upstream groups from kubectl and, in newest versions, the UI. We would welcome contributions to glooctl to add more features like this.

**Comment by rickducott** [comment]
Actually, found this: https://github.com/solo-io/gloo/pull/893
