### ISSUE TITLE
Kubernetes 1.29

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#8978]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.17

### Is your feature request related to a problem? Please describe.

I want Gloo Edge to use the latest stable Kubernetes version

### Describe the solution you'd like

- [ ] Walk through the Kubernetes release notes, understanding what has changed since K8s 1.28 (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md#changelog-since-v1280)
- [ ] Write up a document that outlines the changes (including field deprecations, new features, breaking changes) that are relevant to the Gloo Edge product. In this document, propose which of these changes we will incorporate in this feature request, and perhaps a set of features that we should consider supporting in the future.
- [ ] Schedule a review of this plan, inviting members of the Edge team, @solo-io/gloo-edge-leads , and a lead/member of the GME team to review the findings, get buy in on the plan.
- [ ] Execute the plan, following https://github.com/solo-io/gloo/issues/8515 and previous upgrades as inspiration for the order of libraries
- [ ] Work with @solo-io/solo-docs to update our support matrix and any other relevant user-facing docs that are impacted by this change

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207286804399389) by [Unito](https://www.unito.io)

**Comment by davidjumani** [comment]
This should be handled if possible
skv2 : codegen - Deprecate generate*groups.sh -> kube_codegen.sh. We can not use this new script yet as kube_codegen.sh only works when the repo is in the sigs.k8s folder. Ref: https://github.com/kubernetes/code-generator/issues/165

**Comment by davidjumani** [comment]
Breaking changes :
TODO

Affected repos :
- k8s-utils
- solo-kit
- skv2
- solo-apis
- gloo
- gloo-mesh-enterprise
- go-utils
- caching-service
- ext-auth-service
- external-apis
- rate-limiter
- solo-projects
- wasm-kit

**Comment by davidjumani** [comment]
This is incorporated in OSS [v1.17.0-beta33](https://github.com/solo-io/gloo/releases/tag/v1.17.0-beta33) and Enterprise v1.17.0-rc1
