### ISSUE TITLE
Go 1.22

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#8981]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.17

### Is your feature request related to a problem? Please describe.

I want Gloo Edge to use the latest stable Go version

### Describe the solution you'd like

- [x] Walk through the Go release notes, understanding what has changed since 1.21 (https://tip.golang.org/doc/go1.22)
- [ ] Write up a document that outlines the changes (including field deprecations, new features, breaking changes) that are relevant to the Gloo Edge product. In this document, propose which of these changes we will incorporate in this feature request, and perhaps a set of features that we should consider supporting in the future.
- [ ]  Schedule a review of this plan, inviting members of the Edge team, @solo-io/gloo-edge-leads , and a lead/member of the GME team, get buy in on the plan.
- [ ] Execute the plan, following https://github.com/solo-io/gloo/issues/8474 and previous upgrades as inspiration
- [ ] Identify additional tests/tools that will improve the stability of our Go integration, or provide a rationale for why that is not necessary
- [ ] Work with @solo-io/solo-docs to update our support matrix and any other relevant user-facing docs that are impacted by this change (likely none)
- [ ] Determine which versions of Gloo Edge this can safely be backported to
- [ ] Determine which versions of Gloo Edge should be backported to 1.21
- [ ] 

### Additional Context

- Per https://tip.golang.org/doc/go1.22: `Go 1.22 is not yet released. These are work-in-progress release notes. Go 1.22 is expected to be released in February 2024.`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207058481216228) by [Unito](https://www.unito.io)

**Comment by sam-heilbron** [comment]
This issue is blocked by the Go release:
- [ ] Per https://tip.golang.org/doc/go1.22: `Go 1.22 is not yet released. These are work-in-progress release notes. Go 1.22 is expected to be released in February 2024.`

**Comment by sam-heilbron** [comment]
This has been identified as a blocker for https://github.com/solo-io/solo-projects/pull/5850.

**Comment by inFocus7** [comment]
Current plan-of-attack:
1. Upgrade our CI to use on go1.22.
2. Update the cloud-builders version on the blocked issue as we want it out soon. (we need CI to be on the same version so it passes)
3. Complete upgrade requirements listed above & do upgrades in all our repos.

**Comment by inFocus7** [comment]
I _think_ this will be re-assigned to others while I focus on other efforts related to [this](https://github.com/solo-io/gloo/issues/8981#issuecomment-2015773609).

If so, I have this (internal) document with some things we need to look into while upgrading + the current state of this: [**doc**](https://docs.google.com/document/d/1QvYx9K1AAkv8fBKaJxK8_BP7i20EfDJxhiV43g466UA)

**Comment by inFocus7** [comment]
Expecting this to take until about mid-to-late next week for everything on the task list + reviews/merges, releases, and back-ports to be done. (dependent on if/how much on-call duties occur this week.)

**Comment by inFocus7** [comment]
Un-assigning myself of the repo(s) relevant for our other milestone are now using Go 1.22. I have updated the **[go1.22 upgrade notes docs](https://docs.google.com/document/d/1QvYx9K1AAkv8fBKaJxK8_BP7i20EfDJxhiV43g466UA/edit)** with any relevant information.

**Comment by davidjumani** [comment]
Go 1.22.2 has been added in OSS [v1.17.0-beta21](https://github.com/solo-io/gloo/releases/tag/v1.17.0-beta21) and will be part of Enterprise v1.17.0-beta1
