### ISSUE TITLE
Implement Upstream Selector for the gateway proxy

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#8993]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

From one of our clients, we got the request of having an UpstreamSelector as we do for the VirtualServices, for the gateway proxy to have visibility on specific Upstreams.

At this moment, every Upstream that exists in the cluster, is added to the gateway-proxy config dump, even when having discovery disabled. If we are able to specify an UpstreamSelector, we should be able to make the config of the gateway-proxy cleaner

**Comment by sam-heilbron** [comment]
This seems to be a duplicate of https://github.com/solo-io/gloo/issues/7288. Can you consolidate these two issues into a single request that captures the requirements?

**Comment by edubonifs** [comment]
Hi @sam-heilbron , that's right sorry, I will close this one then
