### ISSUE TITLE
Helm Flag for setting log level on sds container

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#9006]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

When we enable mtls for Gloo components: https://docs.solo.io/gloo-edge/latest/guides/security/tls/mtls/
Envoy and sds containers get attached to the gloo pod.
Currently, there is a way of changing the verbosity of the gloo container but not for sds.
We have a request from one of our customer for being able to configure the log verbosity to warning or error levels on sds container also, as they are seeing many "info" messages from the sds container

**Comment by sam-heilbron** [comment]
Re-opening to backport this to 1.16 as well.

**Comment by sam-heilbron** [comment]
This has been merged into the Gloo OSS 1.16 branch, and will be available in Gloo OSS v1.16.5. It will be pulled into an upcoming Enterprise release.

**Comment by sam-heilbron** [comment]
The fix was merged into Gloo OSS 1.16.5 (https://github.com/solo-io/gloo/pull/9176):

GlooE 1.16.4 will contain this fix.
