### ISSUE TITLE
Decouple dry-run and output format flags in glooctl, -oyaml is wrong anyways

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#904]
Before anyone starts using the new --yaml flag, I propose removing the new top level flag and instead adding it as an output format (`-o yaml, json, table` currently, proposing `-o yaml, json, table, kube-yaml`

Related PRs: https://github.com/solo-io/gloo/pull/897

I'm proposing this "breaking change" because it is already broken. For example:

```bash
glooctl create us static test --static-hosts host1 --dry-run
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  creationTimestamp: null
  name: test
  namespace: gloo-system
spec:
  upstreamSpec:
    static:
      hosts:
      - addr: host1
        port: 80
status: {}
```

vs 

```bash
glooctl create us static test --static-hosts host1 -oyaml
---
metadata:
  name: test
  namespace: gloo-system
  resourceVersion: "152436"
status: {}
upstreamSpec:
  static:
    hosts:
    - addr: host1
      port: 80
```
Note that the second is in fact not proper kubernetes yaml. It lacks:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
```
at the top level.

Further, the current --yaml implementation is nearly identical to our current -oyaml behavior:
```bash
glooctl create us static test --static-hosts host1 --yaml
metadata:
  name: test
  namespace: gloo-system
status: {}
upstreamSpec:
  static:
    hosts:
    - addr: host1
      port: 80
```

Thus we should be able to safely drop the --yaml flag before its used, since it is duplicate behavior.

Finally, it makes no sense to have two different dry run flags, which is the new behavior (with the --yaml flag and --dry-run flag). Instead, we should have a dry-run flag and an output flag, and you should be able to render your dry-run output in any format you desire. They should not be coupled.

cc @ilackarms @yuval-k

**Comment by yuval-k** [comment]
i agree that this is a bit confusing. One note is that `-oyaml` flag is not meant to be used by kubernetes, but rather for other gloo storage like file and consul

**Comment by rickducott** [comment]
I would like to get to this soon, so we can properly reference this flag in our user guides
