### ISSUE TITLE
Provide pprof enabled envoy image for glooe 1.15.7

### ISSUE THREAD

**Issue by huzlak** [solo-io/gloo#9093]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.15.7

### Is your feature request related to a problem? Please describe.

Facing an intermittent issue during load tests, we will need a pprof enabled image to troubleshoot

### Describe the solution you'd like

I'd like to get pprof enabled image together with instructions on how we can use it to gather cpu profiles during load tests.

### Additional Context

https://solo-io.zendesk.com/agent/tickets/3155

## Child issues:
- [x] https://github.com/solo-io/solo-projects/issues/5763

**Comment by DuncanDoyle** [comment]
Image provided to customer. Closing.

**Comment by LevyTomer** [comment]
@DuncanDoyle  As also confirmed by @nfuden, the Alpine version isn't working the same as in the Ubuntu version that it was initially tested with. So this issue should be reopened until a working Alpine version is provided
