### ISSUE TITLE
Upgrade link is broken in changelog

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#910]
Broken link: https://gloo.solo.io/upgrading/0.18.0/

**Comment by rickducott** [comment]
I'll fix that, we pulled the 0.18.0 release and will have a 0.18.1 release shortly, then I'll update the link. Here's the draft: https://github.com/solo-io/solo-docs/pull/401

**Comment by rickducott** [comment]
This is now fixed, thanks for flagging
