### ISSUE TITLE
`global.extensions.dataplanePerProxy` and `redis.clientSideShardingEnabled` cannot be set to true at the same time

### ISSUE THREAD

**Issue by Nadine2016** [solo-io/gloo#9101]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.16.0 (and earlier)

### Kubernetes Version

1.27

### Describe the bug

When setting `global.extensions.dataplanePerProxy` and `redis.clientSideShardingEnabled` to true at the same time, the rate limiting server results in an error similar to this: 
```
ERROR   rate-limiter    Could not execute Redis pipeline: no upstream host      {"version": "undefined"
}                                                                                                                                                                                              
ERROR: [core] [Server #1] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: err
or while marshaling: proto: Marshal called with nil  
```

Setting one of those fields to false fixes this issue. 

Using both settings at the same time is useful for clients who want to isolate gateways per tenant or who use multiple gateways to isolate external and internal workloads. 

### Expected Behavior

It should be possible to use both options at the same time. 

### Steps to reproduce the bug

1. Install GE and enable set  `global.extensions.dataplanePerProxy` and `redis.clientSideShardingEnabled` to true in the Helm chart. 
2. Send requests to an app that trigger the rate limiter. 
3. View the logs of the gateway proxy rate limiting server. 

### Related issues
Related issues discovered during investigation of this ticket:
- [ ] #9137
- [ ] solo-io/solo-projects#5788
- [ ] solo-io/solo-projects#5789

**Comment by bewebi** [comment]
A fix for this has been released in v1.16.3 and will be released in v1.17.0-beta1 as well
e2e testing will be completed as a fast follow
