### ISSUE TITLE
Add support for regex `watchNamespaces`

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#9113]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

Customer would like regex support for watch namespaces so that new PR named namespaces are automatically watched without a config change to gloo.

### Describe the solution you'd like

regex based watch namespaces

**Comment by chrisgaun** [comment]
Can potentially solve req w labels.

**Comment by kcbabo** [comment]
@kcbabo @DuncanDoyle follow up on this

**Comment by DuncanDoyle** [comment]
Superseded by https://github.com/solo-io/gloo/issues/9274

**Comment by prithvikavuri** [comment]
@kevin-shelaga @DuncanDoyle is this feature available ? if so what release version ?

**Comment by supalp** [comment]
Please share - why this ticket was closed? It says its closed because its completed on 27th March. Which release this feature is part of and also please share some documentation on how we can use it

**Comment by kevin-shelaga** [comment]
@supalp a new ticket was created as a a milestone of sorts https://github.com/solo-io/gloo/issues/9274
