### ISSUE TITLE
GraphQL - validate schema in the control plane so envoy doesn't NACK on invalid gql schema

### ISSUE THREAD

**Issue by saiskee** [solo-io/gloo#9129]
### Do you have a suggestion for code improvement or tracking existing technical debt? Please describe.

This came up in a customer scenario where:
```gRPC config for [type.googleapis.com/envoy.config.route.v3.RouteConfiguration](http://type.googleapis.com/envoy.config.route.v3.RouteConfiguration) rejected: error parsing graphql schema: Unknown field type: BigDecimal line: 84 column: 3```

the big decimal type was not defined in the schema. While this was an invalid schema, it caused a bad UX because it caused envoy to NACK, causing multiple failures across the system.

### Describe the solution you'd like

Validate schemas / maybe other potential envoy graphql nacks in CP before sending config to Envoy.

**Comment by DuncanDoyle** [comment]
Outdated. Closing
