### ISSUE TITLE
Envoy 1.31

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#9144]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.18

### Is your feature request related to a problem? Please describe.

I want Gloo Edge to use the latest stable Envoy version

### Describe the solution you'd like

- [] Walk through the Envoy release notes, understanding what has changed since 1.30 (https://www.envoyproxy.io/docs/envoy/v1.31.0/version_history/v1.31/v1.31.0)
- [] Write up a document that outlines the changes (including field deprecations, new features, breaking changes) that are relevant to the Gloo Edge product. In this document, propose which of these changes we will incorporate in this feature request, and perhaps a set of features that we should consider supporting in the future. This MUST include all versions since the last version of envoy used in edge. This MUST include the risk of adopting the changes.
- [ ] Schedule a review of this plan, inviting members of the Edge team, @solo-io/gloo-edge-leads , get buy in on the plan.
- [ ] Execute the plan, following https://github.com/solo-io/gloo/issues/8514 and previous upgrades as inspiration
- [ ] Schedule a post overview of new features to add with CS / Product
- [ ] Identify additional tests that will improve the stability of our Envoy integration, or provide a rationale for why that is not necessary. These should be scoped to new features, feature changes or pieces of functionality that broke in manual testing.
- [ ] Work with @solo-io/solo-docs to update our support matrix and any other relevant user-facing docs that are impacted by this change

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1208297082377647) by [Unito](https://www.unito.io)

**Comment by andy-fong** [comment]
The upgrade evaluation is completed and the following issues has been created to account for changes in envoy 1.31:

Documentation Update:
https://github.com/solo-io/gloo/issues/10146

New Features:
https://github.com/solo-io/solo-projects/issues/6999
https://github.com/solo-io/solo-projects/issues/7000

Blockers:
https://github.com/solo-io/solo-projects/issues/6997
https://github.com/solo-io/gloo/issues/10145

Closing this ticket and will start on the Blockers tickets.
