### ISSUE TITLE
Missing access log examples 

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#916]
https://gloo.solo.io/user_guides/setup_options/access_logging/#json-formatted

**Comment by yuval-k** [comment]
Hi @derrickburns , we have a slight formatting error which will be fixed shortly - thank you for bringing it to our attention. In the mean time, you can look at the source of the doc to see the examples: https://github.com/solo-io/solo-docs/blob/master/gloo/docs/user_guides/setup_options/access_logging.md

**Comment by yuval-k** [comment]
fixed by https://github.com/solo-io/solo-docs/pull/425
