### ISSUE TITLE
Add name option for glooctl command

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#9163]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

Customer runs Gloo with a different name, would like the add a glooctl name flag for commands. 

### Describe the solution you'd like

Glooctl get proxy -name my-gloo 

### Describe alternatives you've considered

Kubectl commands where possible

# Related Issues

- [ ] https://github.com/solo-io/gloo/issues/8700

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207718118867769) by [Unito](https://www.unito.io)

**Comment by nfuden** [comment]
by name do you mean the gloo-pod's name? namespace? or label?

**Comment by kevin-shelaga** [comment]
@nfuden Gloo pod name, though potentially this could include pointing Glooctl to different proxy names as well

**Comment by nfuden** [comment]
Clarification: iS there a standard rename or a per pod situation? 

It sounds like its just a way to rename each of our default pod names.

If we decide to add this functionality we MUST add this to our glooctl configuration file.

**Comment by DuncanDoyle** [comment]
@kevin-shelaga Can we ask the customer for an example of what they need? I check the Zendesk ticket, and that mentions the `glooctl get proxy` command .... but `glooctl get proxy` already accepts a `--name` parameter ... so I'm a bit confused ...

I.e.,  just tried this out in a sample environment with 3 GW deployments:

```
glooctl get proxy --name public-gw
```

... and that works fine.

**Comment by jswinner09** [comment]
After upgrading the "glooctl" tool and adding labels (app: gloo, gloo: gloo) to "gloo" everything looks fine. The ZD ticket has been closed and we should be able to close this GH issue as well.

**Comment by htech7x** [comment]
Hello @DuncanDoyle,
it doesn't work in my case:
```
kubectl get deploy -n gloo-system|grep gloo
gloo-deploy                              1/1     1            1           23m
gloo-fed                                 1/1     1            1           174m
gloo-fed-console                         1/1     1            1           174m
glooe-grafana                            1/1     1            1           174m
glooe-prometheus-kube-state-metrics-v2   1/1     1            1           174m
glooe-prometheus-server                  1/1     1            1           174m

kubectl get pod -l gloo=gloo -n gloo-system                                                                                        
NAME                           READY   STATUS    RESTARTS   AGE
gloo-deploy-58756d5458-pftcl   1/1     Running   0          7m32s
```
```
glooctl check -p gloo=gloo
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... Error from server (NotFound): deployments.apps "gloo" not found
Error from server (NotFound): deployments.apps "gloo" not found
^C

glooctl get proxy --name gloo-deploy                                                                                               
Error from server (NotFound): deployments.apps "gloo" not found

glooctl version
Client: {"version":"1.16.10"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"latest","Name":"discovery-ee","Registry":"quay.io/solo-io"},{"Tag":"latest","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"latest","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"latest","Name":"gloo-ee","Registry":"quay.io/solo-io","OssTag":"1.16.12"},{"Tag":"latest","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"latest","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"7.0.11","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```

**Comment by davidjumani** [comment]
This will be in OSS v1.13.39, v1.14.32, v1.15.30, v1.16.18, v1.17.0 and Enterprise [v1.13.35](https://github.com/solo-io/solo-projects/releases/tag/v1.13.35), v1.14.20, v1.15.20, v1.16.12, v1.17.0
