### ISSUE TITLE
Links in generated docs don't work

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#919]
For example, on this API:

https://gloo.solo.io/v1/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk/#virtualhost

Click on "routes" link and it doesn't take you anywhere.

**Comment by rickducott** [comment]
@christian-posta I'm not getting this behavior. 

![image](https://user-images.githubusercontent.com/27434432/62151176-b79bed80-b2cd-11e9-8641-0ec28fb084e8.png)

![image](https://user-images.githubusercontent.com/27434432/62151186-bec2fb80-b2cd-11e9-87ca-6a5f65cc3a34.png)

What browser? Does it still happen in an igcognito window?

**Comment by rickducott** [comment]
Closing this as we could not repro, let's reopen if we can.
