### ISSUE TITLE
When creating a new vs glooctl picks a name with an invalid character

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#920]
This guide documents a basic flow for creating a virtual service, which results in a VS that has an invalid virtual host name and requires sanitizing during translation to proxy config. This gets logged in the gloo logs. We should pick a virtual host name that doesn't require sanitization...

https://gloo.solo.io/user_guides/gateway/getting_started/

**Comment by ashleywang1** [comment]
The link points to a nonexistent page now.

**Comment by TheEvilCoder42** [comment]
Same issue, installed with knative integration and gateway.

There's a namespace `tenant-1` with a service `example-app` and a virtual service `entry route`.

The knative service gets added as `tenant-1.example-app-0` and the virtual service as `tenant-1.entry-route`

When I sequentially add 100 tenants, gloo pod has a high load (1700m) and constantly logs):
```
{"level":"warn","ts":1572600310.3313935,"logger":"gloo.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer.translator.compute_route_config.http-routes","caller":"utils/sanitize.go:19","msg":"illegal character(s) '.' in virtual host name [tenant-1.example-app-0] will be replaced by '_'"}
...
{"level":"warn","ts":1572600324.6679225,"logger":"gloo.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer.translator.compute_route_config.listener-::-80-routes","caller":"utils/sanitize.go:19","msg":"illegal character(s) '.' in virtual host name [tenant-1.entry-route] will be replaced by '_'"}
...
{"level":"info","ts":1572600879.1981657,"logger":"gloo.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:122","msg":"Setting xDS Snapshot","key":"gloo-system~knative-external-proxy","clusters":524,"listeners":1,"routes":1,"endpoints":524}
{"level":"info","ts":1572600879.4428105,"logger":"gloo.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:122","msg":"Setting xDS Snapshot","key":"gloo-system~knative-internal-proxy","clusters":524,"listeners":0,"routes":0,"endpoints":524}
{"level":"info","ts":1572600879.4731371,"logger":"gloo.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:135","msg":"end sync 15070998972998164608"}
```

**Comment by rickducott** [comment]
In the associated issue (and it's associated issues), I see some product updates to the logging as well as general perf issues. Going to mark as closed.
