### ISSUE TITLE
Add Extensions CRD to ApiSnapshot

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#922]
We should update the ApiSnapshot struct to support a generic `Extensions` CRD here: https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/api/v1/api_snapshot.sk.go#L12-L19

The idea is to allow plugins to add their own CRDs in the future, and make the current gloo watch/emit/sync code reusable for these newly added types.

Clients would fetch generic CRDs and unmarshal them (possibly failing to do so on the wrong type) into their protos.

Pros:
* extensible, allows reuse of gloo code

Cons:
* watch may trigger too often on CRDs we don't care about

This could also prove useful as a way to support testing new features (as plugins) before we decide to implement them as fully supported APIs.

cc @ilackarms if you have anything else to add here please do

**Comment by rickducott** [comment]
Is the idea for each plugin to create it's own CRD type, or for there to be a single Extensions CRD type and allow plugins to add fields to it?

**Comment by kdorosh** [comment]
The idea is for there to be a single Extensions CRD type and plugins add their proto definitions to it as custom fields under `spec`

**Comment by rickducott** [comment]
Cool!

**Comment by rickducott** [comment]
Unclear if this is a desirable direction, since we also have autopilot for a new take on building controllers. Going to close as stale.
