### ISSUE TITLE
Gloo Gateway v2 does not expose Envoy access logs

### ISSUE THREAD

**Issue by jcrowthe** [solo-io/gloo#9269]
### Gloo Edge Product

Open Source

### Gloo Edge Version

gloo-proxy:2.0.0-beta1

### Is your feature request related to a problem? Please describe.

Debugging the applications which are fronted by Gloo Gateway v2 is very difficult because there are no per-request access logs which would typically be exposed by a proxy.

### Describe the solution you'd like

Expose envoy's access logs, similar to what is available today for Gloo Edge (https://docs.solo.io/gloo-edge/1.7.23/guides/security/access_logging/). Of note, Gloo Edge's access log customization is rather feature filled today and not all of these features are immediately needed. Just having access logs would be most valuable right now.

**Comment by EItanya** [comment]
This has been solved in the meantime, you should be able to use the `ListenerOptions` resource
