### ISSUE TITLE
Provide pprof enabled envoy image for glooe 1.16.2-alpine

### ISSUE THREAD

**Issue by DuncanDoyle** [solo-io/gloo#9272]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.16.2-alpine

### Is your feature request related to a problem? Please describe.

Facing an issue with dynamic metadata performance, we will need a pprof enabled image to troubleshoot

### Describe the solution you'd like

I'd like to get pprof enabled image together with instructions on how we can use it to gather cpu profiles during load tests.

### Additional Context

https://solo-io.zendesk.com/agent/tickets/3155

## Child issues:

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1206944088198758) by [Unito](https://www.unito.io)

**Comment by ashishb-solo** [comment]
referring to [these instructions](https://github.com/solo-io/solo-projects/issues/5763) for how to build this

**Comment by ben-taussig-solo** [comment]
The steps to build an image suitable for collecting CPU profiles are:
 1. build envoy(-gloo-ee) with debug symbols and gperftools
    - debug symbols: pass the `-c dbg` flag to bazel
    - tcmalloc: pass `--define tcmalloc=gperftools` to bazel
    - note: we should kick this off this afternoon, so that we will have the binary ready by tomorrow afternoon
    - note: we must build from the version of envoy-gloo-ee used in the version of gloo EE that the client has installed. In this case, the client is using [v1.16.2-alpine](https://github.com/solo-io/solo-projects/blob/v1.16.2-alpine/), which [maps to](https://github.com/solo-io/solo-projects/blob/v1.16.2-alpine/Makefile#L45) envoy-gloo-ee v1.27.3-patch1
 2. build envoy(-gloo-ee) docker image
    - note that I'm referring to the docker images built from the envoy-gloo/envoy-gloo-ee repos, not the *-wrapper images built in our control plane repos
        - for example, the enterprise Dockerfile can be found [here (envoy-gloo-ee/ci/Dockerfile)](https://github.com/solo-io/envoy-gloo-ee/blob/main/ci/Dockerfile)
    - We need to update this Dockerfile to use alpine as a base image -- at the time of writing, [the most recent commit targeting this Dockerfile updated it to use ubuntu as a base image](https://github.com/solo-io/envoy-gloo-ee/commits/main/ci/Dockerfile), so you can just revert to the prior commit to get a valid alpine-based Dockerfile
    - We need to update this Dockerfile to set the `CPUPROFILE` environment variable to a location to dump CPU profiles to. I used `CPUPROFILE=/tmp/mybin.cpuprof`, so I think we should probably leave that as-is for this build
        - more info here, although YMMV with this doc: https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md
        - we can probably also set this in the wrapper image, but doing it here is useful in case we want to test this "base image"
 3. build envoy(-gloo-ee) wrapper docker image
    - I am not sure about the state of the `v1.16.2-alpine` tag in solo-projects, but I imagine we should just be able to update the `ENVOY_GLOO_IMAGE_VERSION` variable in the Makefile and then do `make gloo-ee-envoy-wrapper-docker` to build the wrapper image
 4. validate that you can collect profiles from the image, and that the profiles contain meaningful data
    - make sure to collect the profiles by toggling the admin interface endpoint
    - make sure you can easily copy the profiles out of the docker container
    - make sure that when you view the profiles in pprof, there are references to lots of different function calls (and not just a single entry for envoy or something like that)
    - we should follow the steps here (please note -- specifically the steps in my LAST comment on the issue) to do this validation: https://github.com/solo-io/solo-projects/issues/5763#issuecomment-1957912003
        - I think a lot of the information here around persistent volumes etc. is not necessary -- before I figured out that we needed to use the admin interface, I was having a lot of trouble generating profiles and most of those instructions are left over from that process
    - feel free to reach out/pair with me on this step -- I think I have a pretty good grasp on it at this point
 5. publish wrapper docker image
    - When we delivered the last image, I just manually pushed the wrapper image to the `gcr.io/solo-test-236622` registry, as `gcr.io/solo-test-236622/gloo-ee-envoy-wrapper:1.15.7-gperftools-tcmalloc-alpine`
    - We also can probably publish the image using the test release action in solo-projects

**Comment by ben-taussig-solo** [comment]
I linked this in the above comment, but it is worthwhile to be aware of the upstream envoy documentation around this functionality: https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md

I have found that it's pretty incomplete, so take anything you read there as a half-truth, but it does have a lot of useful information

**Comment by ben-taussig-solo** [comment]
Another important point, related to step 1:
 - Our support for debug builds is broken in envoy-gloo/envoy-gloo-ee LTS version 1.26 and greater, as a consequence of the steps we took to do the v1.25 -> v1.26 bump
 - Here is the PR I used to build the last image for this purpose: https://github.com/solo-io/envoy-gloo-ee/pull/731/
   - the PR is old, so the files view is not particularly useful, but the commits will show the steps I took in order to create a working build of envoy with debug symbols
   - We should be able to apply similar steps to create this binary, although they will possibly be slightly different, as we are compiling a 1.27 binary instead of 1.26

**Comment by ashishb-solo** [comment]
@ben-taussig-solo On step #2 in [this comment](https://github.com/solo-io/gloo/issues/9272#issuecomment-2023599672), do we just run `make docker-local && make docker-release` from the envoy-gloo-ee Makefile?

**Comment by ashishb-solo** [comment]
This is complete and was [sent to SAP via slack](https://solo-io-corp.slack.com/archives/C02E7LCHSKG/p1712171827165889?thread_ts=1710962598.345079&cid=C02E7LCHSKG).

To outline how I did this, I started from the v1.16.2-alpine branch:

```
helm install -n gloo-system gloo-ee gloo-ee-test/gloo-ee --version 1.16.2-b-alpine-test-release-2a2481a --set-string license_key=$GLOO_LICENSE_KEY --set gloo-fed.enabled=false --set gloo-fed.glooFedApiserver.enable=false --create-namespace
```

Then I created custom images for gloo and gateway-proxy on top of the images used in the binaries from the release.

For the gateway-proxy, I ran `kubectl -n gloo-system get deployments/gateway-proxy -o yaml | grep -iw image` to get the image (`quay.io/solo-io/gloo-ee-envoy-wrapper:1.16.2-b-alpine-test-release-2a2481a`). Then I wrote a Dockerfile:

```
FROM quay.io/solo-io/gloo-ee-envoy-wrapper:1.16.2-b-alpine-test-release-2a2481a

COPY envoy-static /usr/local/bin/envoy
```

which overwrites the envoy binary with the one I made from a custom build. The custom build was created by running `bazel build -c dbg --define tcmalloc=gperftools //source/exe:envoy-static --jobs=$(($(nproc) - 6)) --show_result=1` and I also disabled fission builds as well in `.bazelrc`:

```
# build:linux --fission=dbg,opt
# build:linux --features=per_object_debug_info
```

For gloo, see [this branch](https://github.com/solo-io/solo-projects/commits/1.16.2-alpine/). The [latest commit](https://github.com/solo-io/solo-projects/commit/3e49a5219427e962222a43a30a8f3cc4a6770eee) has the relevant version of gloo with the dynamic stats feature backported onto it. I rebuilt it by running `make -B gloo-ee-docker` which created the `quay.io/solo-io/gloo-ee` image with a checksum of `374ca691d867`. I retagged it by running

```
docker image tag 374ca691d867 gcr.io/solo-test-236622/gloo-ee-dynamic-stats:1.16.2-alpine-dynamic-stats
```

and pushed the image

```
docker image push gcr.io/solo-test-236622/gloo-ee-dynamic-stats:1.16.2-alpine-dynamic-stats
```
