### ISSUE TITLE
Setup syncer test flake

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#9306]
### Which tests failed?

have seen this a few times, but kicking seems to resolve it
```
  [FAILED] Expected
      <string>: rpc error: code = Unavailable desc = error reading from server: EOF
  to contain substring
      <string>: received message larger than max (19 vs. 1)
  In [It] at: /home/runner/work/gloo/gloo/test/kube2e/gloo/setup_syncer_test.go:162 @ 04/01/24 19:35:36.218
```
https://github.com/solo-io/gloo/actions/runs/8512608565/job/23314570766?pr=9276

further up in the logs there are some instances of
```
failed to start HTTPS Server in Test Server: &errors.errorString{
  s: "10.244.0.6 - - [01/Apr/2024 19:32:29] \"GET / HTTP/1.1\" 200 -\ncommand terminated with exit code 137\n (exit status 137)",
}
```
which could be related

**Comment by sam-heilbron** [comment]
I have moved this to blocked. I merged a PR that I believe should address this. If after 1 week, there are no more of these flakes, I will close it.
