### ISSUE TITLE
enable append/remove headers

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#936]
these are an envoy feature which live on VirtualHosts, Routes, and weighted clusters

see: `RequestHeadersToAdd`, `RequestHeadersToRemove`, `ResponseHeadersToAdd`, `ResponseHeadersToRemove`

**Comment by yuval-k** [comment]
can we add supporting host-rewrite as well? it in the same area..
note that these (except host-rewrite) can be applied not only on the route level but also on the destination level.

**Comment by zamrokk** [comment]
server header is never removed. Is there a bug here ?
