### ISSUE TITLE
Log level management improvements

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#945]
Updating this ticket as a general issue to track usability of logging. Related issues:
* https://github.com/solo-io/gloo/issues/1620
* https://github.com/solo-io/gloo/issues/2115
* https://github.com/solo-io/gloo/issues/2058

**Comment by rickducott** [comment]
We need a better answer for doing this on the server. Currently it's only configurable via admin UI. We may want to preserve across restarts, and may make sense as a backend setting in the CRD for persistence.

**Comment by kdorosh** [comment]
Additionally, we need to make it possible to change envoy/gloo log levels before the pods start up.

**Comment by rickducott** [comment]
Updated this ticket to capture all the ideas related to logging improvements.

**Comment by bdecoste** [comment]
Also add helm values for `--component-log-level `and `--log-level` as command line options in the gateway-proxy deployment
