### ISSUE TITLE
glooctl util for testing domain string to see which virtual service will handle it

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#955]
As more Virtual services and more wild card domain specs are added, it becomes difficult to know which VS will handle a given domain string

possible command syntax:
`glooctl util show-handler --domain my123.domain.com`
would respond with: `gloo-system.my-vs by '*.domain.com'`

Here is how Envoy determines the handler:
https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/route/route.proto#L44
expanded:
```
  // Domain search order:
  //  1. Exact domain names: ``www.foo.com``.
  //  2. Suffix domain wildcards: ``*.foo.com`` or ``*-bar.foo.com``.
  //  3. Prefix domain wildcards: ``foo.*`` or ``foo-*``.
  //  4. Special wildcard ``*`` matching any domain.
```

**Comment by rickducott** [comment]
Closing as stale.
