### ISSUE TITLE
Upgrade notes for 1.17 release

### ISSUE THREAD

**Issue by artberger** [solo-io/gloo#9559]
### Version

main (1.17.x beta)

### Describe the requested changes

Update the upgrade notes for the 1.17 release.

In general, check the changelog for breaking changes and other big fixes.

### Particular issues to capture:
- [ ] See discussion of deprecated fields and migration steps in https://github.com/solo-io/gloo/pull/9529
- [ ] 1.17 scale testing

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/main/operations/upgrading/

**Comment by Rachael-Graham** [comment]
I think we just need to summarize the changelog entries. No major features to document according to Nadine.
