### ISSUE TITLE
Settings pre-install hook

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#956]
https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/18-settings.yaml#L9

Is there a reason for:
    `"helm.sh/hook": pre-install`

What it means practically to me is that I cannot easily use GitOps to manage Gloo, since the resource is not deleted when I update the helm release.

Is there a reason for this?

**Comment by rickducott** [comment]
The reason may have been to avoid a race with pods starting up and expecting settings, need to investigate but I’m sure we can find another solution to facilitate your gitops.

**Comment by rickducott** [comment]
There's a related issue which is that we create Namespace and Settings in the preinstall stage, and once in a Settings fails to apply with an error that the namespace doesn't exist yet. Moving settings to the normal install stage should resolve both issues.

**Comment by derrickburns** [comment]
@rickducott Thx!
