### ISSUE TITLE
Gloo APIs related to Kube Gateway API are not synced to solo-apis repo

### ISSUE THREAD

**Issue by jbohanon** [solo-io/gloo#9569]
### Do you have a suggestion for code improvement or tracking existing technical debt? Please describe.

The script at https://github.com/solo-io/solo-apis/blob/gloo-main/hack/sync-gloo-apis.sh has not been updated to sync APIs in the `gateway2/` directory (the directory for Kube Gateway API integration at the time of this writing).

### Describe the solution you'd like

Add syncing if desired, document why we don't have it if not.

**Comment by josh-pritchard** [comment]
We need this in gloo-mesh-enterprise but I think only the gotypes and not the protobufs

**Comment by nfuden** [comment]
Can you link to an issue in gloo-mesh-enterprise with details on how this is to be used there?

**Comment by josh-pritchard** [comment]
Dependency for https://github.com/solo-io/gloo-mesh-enterprise/issues/18646 & https://github.com/solo-io/gloo-mesh-enterprise/issues/18572

**Comment by ashleywang1** [comment]
Here's an example branch into `gloo-main`: https://github.com/solo-io/solo-apis/pull/1314

**Comment by ashleywang1** [comment]
We now need:
1) a new tag off of `gloo-main`, which will happen in a couple of days
2) To update the go.mod solo-apis tag.
