### ISSUE TITLE
Support host-rewrite-header 1.16

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#9579]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.16

### Is your feature request related to a problem? Please describe.

Controlling the host via injected headers from ext proc would be a great way to augment routing based on outside behaviors.

### Describe the solution you'd like

Support configuration of https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-host-rewrite-header in addition to the auto host rewrite.

This should also do basic header validation on the headers name.

### Describe alternatives you've considered

n/a

### Additional Context

Some internal context on my own confusion https://solo-io-corp.slack.com/archives/C02E7LCHSKG/p1716461892925569

Nothing novel here other than an example of a desire for this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207496375785183) by [Unito](https://www.unito.io)

**Comment by davidjumani** [comment]
This is added in 1.17.0 and 1.16.16 when released
