### ISSUE TITLE
TCP keep alives for upstreams and downstream is mostly buried

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#9610]
### Version

main (1.17.x beta)

### Describe the requested changes

Today we have a bare bones downstream keep alive doc that has been proven in many production environments. Particularly with aws. https://docs.solo.io/gloo-edge/latest/guides/integrations/aws/socket-options/ We should update this more thoroughly and modify our warning.
The follow on piece is that this gets confused and misplaced with regards to connections to the actual destinations (upstreams). The ability to set a keep alive there is hard to find as it is stored only on our proto docs which can often be confusing: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk/#connectionconfig  https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk/

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/latest/guides/integrations/aws/socket-options/

https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk/#connectionconfig  
https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk/

### Additional Context

Ideally upstream configuration for tcp keep alive should be well documented with an easy example.
Ideally both downstream and upstream docs are linked so that if there is confusion about one or both they can both be referenced.
Downstream connection is still very much a open format and can cause some issues such as trying to update the options on a running instance and we may want to codify those risks.

**Comment by htpvu** [comment]
@nfuden  This is not in the prioritized backlog for 1.18. Could you work with Product to prioritize this issue or drop it from the list of issues to schedule.

**Comment by andy-fong** [comment]
The second part of this ticket (adding helm settings to allow users to configure dns resolver defaults) has nothing to do with the title but I do have some questions:
1) There are 3 different resolver types available (apple, cares and getaddrinfo), are we going to support all? [reference](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#:~:text=of%20typed_dns_resolver_config.-,typed_dns_resolver_config,-(config.core)
2) For this type of settings where different typed config can be packed into that field, are we going to enumerate all the structures in the helm template from the envoy proto definition or is there some generic way we use to accept "free formed" yaml? 
3) The structures for apple and getaddrinfo are very simple; however, cares has nested structure that are a few level deep and also allow an array of address objects which also contains objects.
4) I assume the settings need some kind of validation? Do we only rely on the data type and json annotation in the go struct?
5) Do we already have a workflow to convert envoy protobuf definition to go struct with proper json annotation for helm use?

**Comment by andy-fong** [comment]
For part 1, our documentation says the tcp idle timeout on AWS NLB cannot be changed but the latest AWS doc says: [The default idle timeout value for TCP flows is 350 seconds, but can be updated to any value between 60-6000 seconds. ](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout)
Is 6000 seconds enough that our customers may not need to use the socket options?

**Comment by andy-fong** [comment]
There are socketOptions for the Gateway, ListenerOption and Proxy CRD. Will need to find out which one controls the downstream tcp connection.

**Comment by andy-fong** [comment]
The documentation changes are live in:
https://docs.solo.io/gateway/latest/traffic-management/tcp_keepalive/
https://docs.solo.io/gloo-edge/main/guides/traffic_management/tcp_keepalive/
