### ISSUE TITLE
Add metadata to gloo secrets to easily filter secret types

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#964]
We should add `gloo-secret`: `aws`, `gloo-secret`: `azure`, etc.. labels to generated secrets so users/glooctl can easily filter by secret type.

Then we can also add a basic `glooctl get secret [secret type]` command leveraging these labels.

**Comment by kdorosh** [comment]
It might be preferable to create our own secret type instead of using labels here.

e.g.,
```
$ kubectl get secrets
NAME                             TYPE                                  DATA      AGE
db-user-pass-96mffmfh4k          ApiKey                                 2         51s
```

instead of

```
$ kubectl get secrets
NAME                             TYPE                                  DATA      AGE
db-user-pass-96mffmfh4k          Opaque                                2         51s
```

**Comment by kdorosh** [comment]
Since the possible secret types are hard coded in kube, and because labels are best left to the end user, I think an annotation is the best path forward here.

**Comment by yuval-k** [comment]
types are not hard codec AFAIK; I believe you can specify your custom types.
