### ISSUE TITLE
ensure reconcilers (such as proxy translators) stay consistent when output objects removed/modified

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#965]
the only thing in our system currently following this principle is discovery. i.e., when an upstream is deleted or modified (in a way that's inconsistent with how discovery wants things), the output objects are immediately resynced. this happens because discovery is watching upstreams themselves

this behavior should be practiced in other places such as proxy translators, otherwise a user error could lead to a bad state / proxy config being out of sync without gloo knowing how to respond (until there is some snapshot jitter)

short  relevant discussion: https://github.com/solo-io/gloo/pull/946#discussion-diff-310253615R39

**Comment by yuval-k** [comment]
same goes for propagating statues back (i.e the proxy status on a virtual service)

**Comment by rickducott** [comment]
The principle makes sense, however the issue is stale and unclear when / if we plan to tackle more cases. We can open new issues as necessary to track specifics.
