### ISSUE TITLE
Does Gloo support decrypting of request bodies ?

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#967]
If my HTTP client sends a request encoded with gzip (using a `Content-Encoding` header), can Gloo (via Envoy) decrypt that transparently as in https://github.com/envoyproxy/envoy/issues/4445 .

**Comment by yuval-k** [comment]
it seems that today the gzip filter doesn't support decompression (https://github.com/envoyproxy/envoy/issues/4445#issuecomment-422289545) (only compression is currently supported)
When this gets added to envoy we can add a plugin to support it in gloo

**Comment by yuval-k** [comment]
closing as answered, please feel free to re-open.

**Comment by yorudy** [comment]
@yuval-k, Work on https://github.com/lyft/envoy-mobile/issues/664 has been accepted and merged into the envoy-mobile project.

Does this create an opportunity to re-open this issue and build support for decoding gzipped requests in gloo?
