### ISSUE TITLE
Add helm value to configure Redis cert name

### ISSUE THREAD

**Issue by DuncanDoyle** [solo-io/gloo#9699]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.11

### Is your feature request related to a problem? Please describe.

When you set `gloo.redis.cert.enabled` to `true`:

> If set to true, a secret for redis will be created, and cert.crt and cert.key will be required. If redis.disabled is not set the socket type is set to tsl. If redis.disabled is set, then only a secret will be created containing the cert and key. The secret is mounted to the rate-limiter and redis deployments with the cert and key. Default is false.

However, there are users where the creation of the secret with cert.crt and cert.key is managed outside of the Gloo Edge (Helm) installation process. Second, organizations might have different naming standards and conventions for secret names than the secret name Gloo Edge expects for this secret (i.e. `{{.Release.Name}}-redis-ca-cert-secret`).

Although you can work around this via a `kubeResourceOverride` helm value, but it would mean touching array type fields, which basically means rewriting significant parts of the deployment spec, making things error-prone and not very maintainable. 

### Describe the solution you'd like

Add a `gloo.redis.cert.name` Helm value that would allow the user to set the name of the secret that contains the `cert.crt` and `cert.key`. This allows the user to use a secret that adheres to corporate naming conventions and standards.

### Describe alternatives you've considered

Use `kubeResourceOverride`. This would however mean touching array type fields, which basically means rewriting significant parts of the deployment spec, making things error-prone and not very maintainable. 

# Related Issues

- https://github.com/solo-io/solo-projects/issues/6404

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207815495257030) by [Unito](https://www.unito.io)

**Comment by bewebi** [comment]
Should a similar value also be exposed for the Redis TLS secret?

**Comment by bewebi** [comment]
#6751 is now open to address this

Will this need to be backported to 1.16 or is it sufficient to consider this a new feature (which it is) and only include in 1.18?

**Comment by bewebi** [comment]
solo-io/solo-projects#6751 has merged and will be released in v1.18.0-beta1

In it we expose `redis.cert.tlsSecretName` and `redis.cert.caCertSecretName` values which allow giving the Redis TLS and CA cert secrets custom names respectively

**Comment by DuncanDoyle** [comment]
Reopening. Customer request to backport to 1.16 and 1.17.

**Comment by sam-heilbron** [comment]
Slack context for request: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1724967658964019

**Comment by sam-heilbron** [comment]
Per slack: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1725369929194459?thread_ts=1724967658.964019&cid=CEDCS8TAP, we have agreed to not backport this further, have notified the customer, and they have accepted it.
