### ISSUE TITLE
Create Service Endpoints for pod prometheus endpoints

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#972]
Currently the Prometheus endpoints on all of our pods are only reachable by communicating directly with the pod. However, technologies like the [prometheus operator](https://github.com/coreos/prometheus-operator) require an Endpoint/Service to scrape the metrics. In order to support this use case we should add the ability to create service port entries to access Gloo prometheus metrics.

**Comment by rickducott** [comment]
Closing in favor of #1773
