### ISSUE TITLE
generic gloo gradual upgrade

### ISSUE THREAD

**Issue by yuval-k** [solo-io/gloo#973]
with https://github.com/solo-io/gloo/issues/778 when introduced a way to gradually upgrade to new gloo.
We can extend this to a generate upgrade strategy, even when no new API is introduced.
To accomplish this, we'll need to make sure that envoy communicates to the correct gloo. we can do this by implementing an install-id, to create different gloo and gateway\gateway-proxy deployments and proxy CRD.

this can reduce risk by allowing to upgrade gloo and gradually allowing it to receive traffic, while the old gloo is running side by side (similar to canary rollout).

**Comment by rickducott** [comment]
We have an install ID now, and have other issues to track upgrade docs and operator.

**Comment by kdorosh** [comment]
We dropped installation ID in favor of tracking the release in helm3's written k8s secret
