### ISSUE TITLE
old build showing up on OSS changelog page

### ISSUE THREAD

**Issue by craigbox** [solo-io/gloo#9767]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.17.x

### Is your feature request related to a problem? Please describe.

https://docs.solo.io/gateway/latest/reference/changelog/open-source/ suggests there is a v2.0.0 series of Gloo Gateway.

### Describe the solution you'd like

I think that removing https://github.com/solo-io/gloo/releases/tag/v2.0.0-beta1 will probably help fix this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207890508307652) by [Unito](https://www.unito.io)

**Comment by DuncanDoyle** [comment]
@sam-heilbron Can you take a look at this one?
