### ISSUE TITLE
[FAIL] Kube2e: helm upgrades [It] uses helm to update the settings without errors

### ISSUE THREAD

**Issue by inFocus7** [solo-io/gloo#9788]
### Which tests failed?

  [FAIL] Kube2e: helm upgrades [It] uses helm to update the settings without errors
  /home/runner/work/gloo/gloo/test/kube2e/helm/helm_test.go:141

```
  [FAILED] Expected
      <string>: 1.0.0ci1
  to equal
      <string>: 1.0.0-ci1
  In [It] at: /home/runner/work/gloo/gloo/test/kube2e/helm/helm_test.go:141 @ 07/15/24 06:19:54.568

  Full Stack Trace
    github.com/solo-io/gloo/test/kube2e/helm_test.init.func2.4.2()
    	/home/runner/work/gloo/gloo/test/kube2e/helm/helm_test.go:141 +0x9ad
```

### Additional Information

- caught in [1.17 nightly](https://github.com/solo-io/gloo/actions/runs/9934459185/job/27438843441#logs).

**Comment by npolshakova** [comment]
Happened on nightlys: https://github.com/solo-io/gloo/actions/runs/10448006334
