### ISSUE TITLE
Go 1.23

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#9819]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.18

### Is your feature request related to a problem? Please describe.

I want Gloo Edge to use the latest stable Go version

### Describe the solution you'd like

- [] Walk through the Go release notes, understanding what has changed since 1.22 (https://tip.golang.org/doc/go1.23)
- [ ] Write up a document that outlines the changes (including field deprecations, new features, breaking changes) that are relevant to the Gloo Edge product. In this document, propose which of these changes we will incorporate in this feature request, and perhaps a set of features that we should consider supporting in the future.
- [ ]  Schedule a review of this plan, inviting members of the Edge team, @solo-io/gloo-edge-leads , and a lead/member of the GME team, get buy in on the plan.
- [ ] Execute the plan, following https://github.com/solo-io/gloo/issues/8474 and previous upgrades as inspiration
- [ ] Identify additional tests/tools that will improve the stability of our Go integration, or provide a rationale for why that is not necessary
- [ ] Work with @solo-io/solo-docs to update our support matrix and any other relevant user-facing docs that are impacted by this change (likely none)
- [ ] Determine which versions of Gloo Edge this can safely be backported to

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1207635280052738/1208102409618301) by [Unito](https://www.unito.io)

**Comment by tjons** [comment]
@sam-heilbron and I discussed yesterday that we combine this upgrade with the k8s upgrade to cut down on the number of dependency upgrade PRs to open.

**Comment by SirNexus** [comment]
Are we standardizing on v1.23.0 or v1.23.1 now that it's released?

**Comment by nfuden** [comment]
In 1.18.0-beta1
