### ISSUE TITLE
Span Name changes for OTEL filter

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#9848]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.17.0

### Is your feature request related to a problem? Please describe.

Split from https://github.com/solo-io/gloo/issues/9313

In order to migrate from legacy tracing filters such as zipkin we should have a similar ux and make sure to be mostly compliant with OTEL spec.
In this case Span name is set to "ingress" and does not comply with spec https://github.com/open-telemetry/opentelemetry-specification/blob/v1.33.0/specification/trace/api.md#span 

### Describe the solution you'd like

Contribute upstream a way to get more reasonable span names.
Likely name is based on path but may need some extra steps such as a regex or something as the last piece of a path may be replaceable.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1208133634962007) by [Unito](https://www.unito.io)

**Comment by nfuden** [comment]
This likely is a blocker to https://github.com/solo-io/gloo/issues/9488

**Comment by ashishb-solo** [comment]
Design document link: https://soloio.slab.com/posts/open-telemetry-span-name-support-drlrm3c2#hnyrv-the-x-envoy-decorator-operation-header

**Comment by ashishb-solo** [comment]
> This likely is a blocker to https://github.com/solo-io/gloo/issues/9488

It is possible that it is not a blocker. https://github.com/solo-io/gloo/issues/9488 has to do with the tracer extension - that extension solely takes responsibility for converting the span to opentelemetry format and sending it to the collector. I don't think that we are going to end up making any changes in the opentelemetry tracer itself to implement this support - I could always be wrong though.

**Comment by ashishb-solo** [comment]
Tracking progress updates for this in [this document](https://docs.google.com/document/d/19PSZWU_ViwN4mRy7ta7bcBnVpAdTLEQ37sMkcpszXNk/edit?usp=sharing)
