### ISSUE TITLE
Improve gloo regression and e2e test logging

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#985]
Original thread and ideas mentioned on this PR: https://github.com/solo-io/gloo/pull/977

The idea:
> some of the things we might want to put in these logs:
> 
> * logs from all pods in `gloo-system` namespace
> * yaml of all virtual services and proxies
> * envoy config dump
> 
> not sure what the intention is here, but that's something me and @yuval-k have been wanting to bring back for some time. some of this implemented in old-master:
> https://github.com/solo-io/gloo/blob/old-master/test/kube_e2e/kubernetes_suite_test.go#L23

> To add to that, we're adding all of this into glooctl, so we should call glooctl commands when we implement that other stuff.

**Comment by kdorosh** [comment]
A lot of the kube dump logic already exists in gloo: https://github.com/solo-io/gloo/blob/master/test/helpers/kube_dump.go

Looks like we just need to call it in gloo-ee tests.

might be nice to add the container statuses as well though, to get detailed information when images fail to pull (i.e., add the following)

```go
fmt.Sprintf("for i in $(kubectl get pod -n %s); do echo STATUS FOR %s.$i kubectl pod -n %s $i -o go-template=\"{{range .status.containerStatuses}}{{.state}}{{end}}\"; done", namespace, namespace, namespace),

```

**Comment by kdorosh** [comment]
A lot of the kube dump logic I wanted was added in https://github.com/solo-io/gloo/pull/1016/files#diff-f06960fe5048687aaaf1b75302448199L11-L43

**Comment by yuval-k** [comment]
@kdorosh is this done?

**Comment by kdorosh** [comment]
@yuval-k no this is not done. leaving open because we could still add an envoy config dump and virtual service/proxy yaml dump pre fail handlers.

the kube dump logic is done though 👍

**Comment by rickducott** [comment]
closing as stale
