### ISSUE TITLE
Improve Gloo -> Gloo Enterprise Helm UX

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#989]
Since gloo-ee has gloo as a dependency, you need to prepend values with "gloo." to access them when installing gloo-ee. Instead, we should use global values for things that would apply equally to gloo and gloo-ee, including:
* Image prefix (done)
* Upgrade 
* Envoy bootstrap config
* Namespace 
* Settings

**Comment by rickducott** [comment]
gateway, discovery, gateway proxy config

**Comment by kdorosh** [comment]
A @yuval-k original idea is to use a "proxy" chart to include the Gloo chart as a dependency so every helm value we include in either version of Gloo is prefixed with `gloo`.

**Comment by rickducott** [comment]
Closing in favor of these:
#2100 
#1958
