### ISSUE TITLE
add custom aws secret converter for interop with gitops tools

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#991]
Currently, our AWS secrets expect an annotation
This means that https://github.com/godaddy/kubernetes-external-secrets will not be able to create valid AWS secrets (cannot set annotations)

We don't need to use annotations to identify AWS secrets. We will implement a custom secret converter that removes the annotation requirement. Along the way, make it easier to specify AWS secret parameters.

Kubernetes secrets that have the following fields will be interpreted as AWS secrets:
```
data:
  aws_access_key: YWNjZXNzX2tleV92YWx1ZQo=
  aws_secret_key: c2VjcmV0X2tleV92YWx1ZQo=
```

this will be easier for the user and tools to generate than the current, internally-generated format (which will continue to be valid):
```
data:
  aws: YWNjZXNzS2V5OiBhY2Nlc3Nfa2V5X3ZhbHVlCnNlY3JldEtleTogc2VjcmV0X2tleV92YWx1ZQoK
```

**Comment by mitchdraft** [comment]
implemented in https://github.com/solo-io/gloo/pull/990

**Comment by antoniotamer** [comment]
Hi @mitchdraft 

The only docs I could see for this fix is this issue, which above refers to keys
```
aws_access_key
aws_secret_key
```

however, the code uses the more conventional `aws_access_key_id` and `aws_secret_access_key` (which worked great for me)

Could this feature be documented a little bit better so as to avoid confusion?

Thank you by the way for this implementation, it was a much needed feature for me and my team.
