### ISSUE TITLE
Re-evaluate the "squash and merge" PR merging settings

### ISSUE THREAD

**Issue by timflannagan** [solo-io/gloo#9925]
### Do you have a suggestion for code improvement or tracking existing technical debt? Please describe.

The current "squash and merge" PR merging settings create a squash commit that aggregates all the commits in the branch into a single commit. In the case that a branch has N commits, this can produce a squashed commit with a lot of additional noise. The following commit helps illustrate the current approach:

<details>

```
commit f808d90048770a6705408dac7bdbc9be3f0e17fc
Author: Tim Flannagan <timflannagan@gmail.com>
Date:   Mon Aug 19 16:35:52 2024 -0400

    .github: Update PR template to use comment formatting for instructions (#9918)
    
    * .github: Update PR template to use comment formatting for instructions
    
    This commit updates the pull request template to improve the usability
    and clarity of the template. The changes involve converting the instructions
    and guidelines under each section into comment formatting (`<!-- ... -->`).
    
    This allows contributors to fill out the template without needing to delete
    instructional text, reducing friction and ensuring that the template remains
    clear and organized.
    
    Signed-off-by: timflannagan <timflannagan@gmail.com>
    
    * Add changelog entry
    
    Signed-off-by: timflannagan <timflannagan@gmail.com>
    
    * Add skipCI: true to the changelog entry
    
    Signed-off-by: timflannagan <timflannagan@gmail.com>
    
    ---------
    
    Signed-off-by: timflannagan <timflannagan@gmail.com>
```

</details>

Updating our GH settings for this repository can help reduce the noise and help improve devexp when running `git log` history locally.

### Describe the solution you'd like

Enable "fixup" style commits when squashing N commits into a single commit. This allows you to keep the commit or PR title without batching each individual commit into the squashed commit's description. Note: this is also the approach we took with the closed source GME repository as well.

### Additional Context

See https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1724177036147899 for more context on this.

**Comment by sam-heilbron** [comment]
@timflannagan per the Slack conversation, I have updated the repository settings for Gloo and Solo-Projects to rely on the PR title for Squash commits. I believe this should resolve this issue.

For developer consistency across our other repos, I also updated a series of other libraries that gloo developers contribute to:
- ext-auth-service
- rate-limiter
- solo-kit
- go-utils
- k8s-utils
- solo-apis

Let me know if you think that is unnecessary (or the wrong move)

**Comment by timflannagan** [comment]
@sam-heilbron Thanks for the quick action man. I'll close this out!
