### ISSUE TITLE
make location of discovered upstreams configurable and document

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#993]

**Comment by leosunmo** [comment]
For easy discoverability in the UI and through the commandline I would like to have the option to tell Gloo's Discovery function to distribute the auto-generated Upstreams to their appropriate namespaces. 

I can see a case for keeping auto-generated objects in a separate namespace (`gloo-system`) to not mix them with user created ones, but if you're already planning on relying on the auto-generated Upstreams you might as well have them in their respective namespaces.

I can see issues arising if a user creates their own Upstreams in a non-Gloo namespace and use the same naming format as Gloo. I guess Gloo would just leave those alone, or perhaps label the ones it created and is actively managing.

**Comment by rickducott** [comment]
I'm going to close as stale (and closed a related issue). We've found using the single write namespace for Gloo config to be helpful, and for long-term use cases upstreams are typically saved in a source of truth like a git repo -- so often the discovered upstream is useful early on, but not necessarily for ongoing production use, meaning the namespace for discovery is less relevant at this point.
