### ISSUE TITLE
seeing different installed CRDs depending on order of install

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#994]
if you install `knative` before `gateway` no `route` CRD  is installed.

need to validate that, regardless of install order, Gloo ends in a predictable state

**Comment by CelsoSantos** [comment]
I've done some more testing around this (creating further minikube clusters) and results are inconsistent, as sometimes it will create everything as expected, including `route`s and other times it won't.

However, all the functionality seems to be there as expected.

Might also be related to #996.

**Comment by rickducott** [comment]
Closing as stale and not clear if there is a real problem here -- we can reopen as necessary.
