### ISSUE TITLE
ability to customize Gloo error messages

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#995]
if an upstream is unavailable, e.g. part of a version upgrade, Gloo may report an error "503 no healthy upstream". Users want an ability to customize text to be a more meaningful error message in the context of their application that includes Gloo

**Comment by leosunmo** [comment]
I have this usecase and would love a simple way of changing default error messages. No clue what the functionality in Envoy is for this, will have to look in to it.

**Comment by yuval-k** [comment]
this is the relevant issue in envoy
https://github.com/envoyproxy/envoy/issues/1178

**Comment by rickducott** [comment]
Though this issue is stale, the linked envoy issue has been receiving a fair amount of attention lately and appears to be coming pretty soon -- going to leave open.

**Comment by mercenaire** [comment]
Envoy has added the feature : https://github.com/envoyproxy/envoy/pull/11007
Can we get a way to specify this configuration from within Gloo Edge?
This would allow us to migrate from HAProxy.

**Comment by lgadban** [comment]
dupe: https://github.com/solo-io/gloo/issues/3466

**Comment by sam-heilbron** [comment]
As @lgadban mentions above, this is a duplicate of https://github.com/solo-io/gloo/issues/3466. To avoid parallel requests, I am going to close the current issue. Please follow up on the linked issue if you would like to see the priority of this work increased.
