### ISSUE TITLE
add `glooctl dump` command

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#997]
Implement an easy to use command for now, add things as we go

- `glooctl check` <- users immediately hone in on anything that looks unhealthy
  - `glooctl check -f` <- for use with `--dry-run` outputs or other pre-deployed resource files to answer questions like: what ec2 instances will match for this config
- `glooctl dump` <- users create an archive they can send us on slack

**Comment by rickducott** [comment]
Check exists, will use this issue to track `glooctl dump`

**Comment by rickducott** [comment]
Specifically I would love a way to scrape all the logs and print any error log from any of our containers. If we publish this on CI we will be able to identify real bugs.
